### ISSUE TITLE
check back button (firefox)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1000]
ef1ba726e40cb2df0d2ab678df1781a9

i was doing a test booking and tried to go back to add 2 more pax but it took me forward each time and on the last press it actually booked the tour.

![image](https://cloud.githubusercontent.com/assets/10079829/14176251/13262554-f71e-11e5-83dd-7348c2a77b6f.png)

**Comment by ronenreinheimer** [comment]
this was in firefox browser

**Comment by bradatkins** [comment]
Does it happen in Chrome?

**Comment by ronenreinheimer** [comment]
It happens every time in firefox

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>



From: Ronen Reinheimer
Sent: Thursday, March 31, 2016 8:57 AM
To: '206Tours/DB' <reply@reply.github.com>
Subject: RE: [206Tours/DB] check back button (#1000)

I don’t think so, ill check again

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK I'll have to install FF

**Comment by ronenreinheimer** [comment]
It’s a good idea. It is one of the best browsers and has a ton of useful addons:
https://addons.mozilla.org/en-US/firefox<https://addons.mozilla.org/en-US/firefox/>



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
n1

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
