### ISSUE TITLE
Registration form question

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1010]
I think "Passenger #2" shouldn't show there unless they check off to add another pax

![image](https://cloud.githubusercontent.com/assets/8440903/14259517/40cead1e-fa75-11e5-9054-66aab1b267ef.png)

**Comment by ali206** [comment]
why is this one closed

**Comment by bradatkins** [comment]
Because that's the way Ronen designed the form. Review with Ronen, it's not a bug.

**Comment by ali206** [comment]
ronen re-added to github b/c he said he can't control it and if it should be removed you have to do it, so I don't know
