### ISSUE TITLE
EXT Cancellation Plan added to a World Youth Day Invoice  - Order #419690 Tour #KW2016 July 24, 2016 (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1012]
![image](https://cloud.githubusercontent.com/assets/10079829/14287011/39182852-fb1f-11e5-8dda-9d60ce7bc731.png)

**Comment by bradatkins** [comment]
This is awkward, Yaritza added it Feb 03 at 9:50
