### ISSUE TITLE
Guadalupe September Pilgrimage | Trouble Registering for Pilgrimage | Philippine Currency (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1014]
![image](https://cloud.githubusercontent.com/assets/10079829/14319814/a961defc-fbe0-11e5-920b-d1c788a35d45.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14319834/b824e376-fbe0-11e5-96b9-2fcfe48a1403.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14319851/c62eca0e-fbe0-11e5-9a6b-6e95dccb17ed.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14319801/9c68f212-fbe0-11e5-95d1-d6d325256c94.png)

**Comment by ronenreinheimer** [comment]
Hi accounting and Ronen

This client is still having some trouble processing her deposit for this tour, I attached the screen shots that she has provided. Client is from the Philippines and she said the website does not accept the currency specified in USD  when she tries to process her payment.
Can you look into this?

Thank you,

Donna

![image](https://cloud.githubusercontent.com/assets/10079829/14395677/0e90e43c-fda1-11e5-85d6-4940633d1a3c.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14395682/16dde77a-fda1-11e5-83a8-9fb4d5223ff2.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14395687/22927112-fda1-11e5-80c7-f659c7dfb7a5.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14395692/2a32d0ec-fda1-11e5-8daf-dc5060354f8f.png)

**Comment by bradatkins** [comment]
OK I think I found it. There was a difference in what Elavon and our currency conversion tool wants to see for a country code for the Philippines. One said PHL the other said PHP; hence, the transaction was failing.

It should be OK now. I suggest Ali checks this one in Elavon when it is processed

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
