### ISSUE TITLE
DB Error - Flight summary

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1015]
![image](https://cloud.githubusercontent.com/assets/10079829/14319916/0ff584d4-fbe1-11e5-8d45-4bf0c9ef2394.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14320245/5fb566b4-fbe2-11e5-90bd-fb9d89a648aa.png)

**Comment by bradatkins** [comment]
Just so I'm clear, just the "RETURN" date is incorrect, not all the other
dates, right?

[image: Inline image 1]

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/14328702/d88daa38-fc05-11e5-9a30-01a393e786d3.png)
