### ISSUE TITLE
Refer a Friend Terms not showing on website on Clients side (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1017]
Can you put a link called 'Terms & Conditions' and link it here:
http://www.206tours.com/ronen/booking/new/refer-a-friend/terms/index.htm

![image](https://cloud.githubusercontent.com/assets/10079829/14320624/c75849ac-fbe3-11e5-8a0f-5af5f864e3cc.png)

**Comment by bradatkins** [comment]
Done
