### ISSUE TITLE
Database Issue | Clients end putting through a payment  (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1018]
![image](https://cloud.githubusercontent.com/assets/10079829/14321830/c22eac64-fbe8-11e5-86ad-908d019916aa.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14321842/d30de658-fbe8-11e5-9c5b-436439c58bfb.png)

**Comment by bradatkins** [comment]
Not really sure, seems to be working for most. If this happens now though we'll be able to see the screenshots
