### ISSUE TITLE
Trying to update email address-422729

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1019]
Trying to update email address here and after clicking save i just see a blank page:

![image](https://cloud.githubusercontent.com/assets/8440903/14323003/ca3c764e-fbec-11e5-9726-588a9e7f7742.png)

session id: 16426ff83575968997c351b77ff31d3c

![image](https://cloud.githubusercontent.com/assets/8440903/14323020/de624d7e-fbec-11e5-969a-c3162936a038.png)

**Comment by bradatkins** [comment]
Try now
