### ISSUE TITLE
Email Addresses Not Updating Properly (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1020]
https://www.206tours.com/register/copysource/invoice_html.php?OrderID=422729&TravelerID=29464&GENERATED=TRUE&BLUE_SHEET=Y

![image](https://cloud.githubusercontent.com/assets/10079829/14323208/9adcdfc8-fbed-11e5-8b33-bb187afdef7a.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14323200/9592747e-fbed-11e5-9947-249e08678783.png)

**Comment by bradatkins** [comment]
Try now
