### ISSUE TITLE
Refer a Friend - Keep a Log / Tracking (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1022]
![image](https://cloud.githubusercontent.com/assets/10079829/14328611/74d1e22a-fc05-11e5-9e74-9f13d9661605.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/15201450/14d6b55a-17bf-11e6-894e-803db6d055be.png)
