### ISSUE TITLE
423038 - had to apply commission 2x

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1023]
I applied commission, balance on booking was $0.00 - Sammie went to check invoice and it said the amount due was commission amount so i had to reapply - nots ure why

![image](https://cloud.githubusercontent.com/assets/8440903/14329750/f0baa00c-fc0a-11e5-869d-5327cbcb3f47.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
