### ISSUE TITLE
422036 - had to apply comm 2 x again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1024]
![image](https://cloud.githubusercontent.com/assets/8440903/14329791/22788744-fc0b-11e5-9fe3-8ca5d0d781db.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14329817/34f17548-fc0b-11e5-8a71-c39feb10c81f.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
