### ISSUE TITLE
what prevents us from adding "!" to SD / priest's order ?  (Sandy / Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1025]
![image](https://cloud.githubusercontent.com/assets/10079829/14359360/0d6e49f6-fcbf-11e5-8dc5-81ff7cbad6da.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14359352/0560f790-fcbf-11e5-9187-258fcc1ec816.png)

**Comment by bradatkins** [comment]
I'm not really sure what you mean?

**Comment by ronenreinheimer** [comment]
Instead of “!” can we make it a cross (†) to identify it is a S/D ?

“!”  usually means warning


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/14361249/0d04e34a-fcc8-11e5-8eba-8a22ea839674.png)

**Comment by ronenreinheimer** [comment]
n1

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
How does it Identify who is a Spiritual Director?

**Comment by bradatkins** [comment]
When a Tour Departure is created, the SD is defined in this drop down box:

![image](https://cloud.githubusercontent.com/assets/8440255/14383318/4fe628b4-fd62-11e5-9115-39c1bf5e4fe1.png)

**Comment by ronenreinheimer** [comment]
can you make a distinction between priests that are simply booked on a tour and priests that are also booked on a tour but they are also the spiritual leaders? does that make sense?

**Comment by bradatkins** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/8440255/14387383/296c569e-fd77-11e5-86cb-461b84a60bc7.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Milanka asked me to make some changes.
**1.** she would like the ability sort by spiritual leader - either a dropdown menu or a check box? not sure what would work better? or something else?
**2.** instead of the ✝ can you add an icon of a priest? in the **# of Psngrs** column?
https://www.206tours.com/register/images/priest-icon.png
**3.** Rinda wants to know if you can make this icon show up anywhere in the DB where a spiritual leader is indicated?
**4.** Milanka said that up until about 6 months ago the ! (in red) used to indicate that the passenger is a spiritual leader but then it suddenly stopped? so she is confused on why it stopped working? example is **Fineo**

![image](https://cloud.githubusercontent.com/assets/10079829/14393814/e49c4608-fd96-11e5-8adc-6b69f01887e6.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Milanka asked me to send you some edits, please review them in GH.

Thank you.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
The exclamation mark was there because the DB used to automatically put in
a "coupon" that required approval (hence the exclamation mark).

Ali requested that it put in a Payment instead, as sometimes she needs to
modify the S/D amount.

I'll mark this as an enhancement and we can add it to the list, but
everything you mentioned is doable.

**Comment by ronenreinheimer** [comment]
Thank you Brad, I will inform Milanka.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Added back in a different way for her

![image](https://cloud.githubusercontent.com/assets/8440255/14446820/15c1c63e-0028-11e6-85e0-afb5f4de01cd.png)
