### ISSUE TITLE
DB - take a peak and tweak/ correct as needed (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1028]
![image](https://cloud.githubusercontent.com/assets/10079829/14394738/c3c55654-fd9b-11e5-894d-456db213eaaf.png)

**Comment by bradatkins** [comment]
Birthday's are working, there are no PAX's with Birthdays in the next 30
days.

For #2 we only email if their tour Departure is in the future. For some
reason, that number wasn't following the same criteria.
