### ISSUE TITLE
Back to Previous Page Not Working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#103]
When we click on "Back to previous page" button this is the page it takes me to:

![image](https://cloud.githubusercontent.com/assets/8440903/5252185/6f910342-7969-11e4-9371-5b16a475c1cf.png)

**Comment by ali206** [comment]
It's multiple pages for natasa when she's using the DB, she's using IE 9 is that why?

**Comment by bradatkins** [comment]
Likely something to do with her browser, it seems to work OK for me ...does it work for you and everyone else?

**Comment by ali206** [comment]
As far as i know yes
