### ISSUE TITLE
Travel Insurance Recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1031]
We need to get this working 100% ASAP bc the way Irena's doing it now is soooo time consuming. 

Can you please get rid of tour code column and add in DOB, Rtn date, Zip code, state client's from, and location they're traveling to?

**Comment by bradatkins** [comment]
Ali, are we pretty much done this?

**Comment by ali206** [comment]
With the additions of columns yes but DB report does not match Irena's so she will be getting back to you on that. 

I will close this issue for now though
