### ISSUE TITLE
Date not showing on invoice? 4 (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1033]
![image](https://cloud.githubusercontent.com/assets/10079829/14429674/63a990e0-ffcc-11e5-92e9-5524f71d149e.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14429709/840e54c4-ffcc-11e5-8c9e-91bbb192a22f.png)

**Comment by bradatkins** [comment]
Fixed
