### ISSUE TITLE
mismatched amadeus names

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1035]
what's wrong with this one?
![image](https://cloud.githubusercontent.com/assets/8440903/14432657/0dba2ed0-ffd9-11e5-94f0-f8b708cabd65.png)

**Comment by bradatkins** [comment]
Ahh she's an infant. I was waiting for an example of an Infant because it's different.

Let me fix this up.

**Comment by bradatkins** [comment]
Actually hmm she's not the infnat, Margaret is. Anyway, let me look into it

**Comment by bradatkins** [comment]
OK it's "fixed". The infant thing was incorrectly flagging Joy (mom I'm guessing) of Margaret.

Margaret's name in Amadeus does not have "Carol" in it.

Have a look and let me know.
