### ISSUE TITLE
Blank Screen after making Payment (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1039]
![image](https://cloud.githubusercontent.com/assets/10079829/14438469/562fb4bc-fff4-11e5-9155-8659d705d443.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14438510/786ce2d4-fff4-11e5-9f96-c7209dce278f.png)

**Comment by bradatkins** [comment]
This is what it says today?

![image](https://cloud.githubusercontent.com/assets/8440255/14660041/4b3d9ff2-066f-11e6-8e61-f808359fbcf4.png)
