### ISSUE TITLE
DB Error | 423287 | GERGEN / ANITA | MT2016K | $10,988.00 of $12,296.00 remaining (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1040]
a0115fde93b01d382322445bd34a0a45

![image](https://cloud.githubusercontent.com/assets/10079829/14438560/b741524c-fff4-11e5-8ea7-68a3bebf45f6.png)

**Comment by bradatkins** [comment]
Fixed the order. Not sure of root cause yet

**Comment by ronenreinheimer** [comment]
Hi Brad,

Did you have a chance to find out the root cause of this issue?
