### ISSUE TITLE
URGENT: 421613 - Commission effecting payments and it shouldn't be

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1046]
This client made a CC payment yesterday and was trying to pay in full but the DB deducted the amount of commission even though Prayer Experience is a GROSS agent. Below balance due is showing as commission amount applied which is wrong.  The DB should've charged him in full and his balance should be $0.00:

![image](https://cloud.githubusercontent.com/assets/8440903/14467376/0b747290-00a9-11e6-8994-87202f578f68.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14467412/39e18c9e-00a9-11e6-9d4b-a712fbf9f8e7.png)

Feb 10, shouldn't be showing as an approved payment - it's commission.
![image](https://cloud.githubusercontent.com/assets/8440903/14467419/40425744-00a9-11e6-8df4-a16d45bd6768.png)

**Comment by bradatkins** [comment]
Fixex
