### ISSUE TITLE
DB Headers - switch from correct header to generic header after continue button

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1047]
cf5c90e20dc88520141c256ceb6f1bc1

Tour 2

![image](https://cloud.githubusercontent.com/assets/10079829/14468784/4f0a8570-00af-11e6-8268-8f8bb2e4b430.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14468792/54ba8fd8-00af-11e6-82b3-c714080b40bf.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
