### ISSUE TITLE
URGENT: orders screen blank

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1050]
![image](https://cloud.githubusercontent.com/assets/8440903/14473608/eb6c2e5c-00c6-11e6-8bc9-65ffbeed2a1b.png)

**Comment by bradatkins** [comment]
My internet is giving me troubles, sometimes stopping in the middle of an
upload.

Hopefully it fixes itself shortly...

**Comment by ali206** [comment]
ok tks

**Comment by bradatkins** [comment]
Should be OK now. I'm gonna wait until my internet is back to normal before
fixing anything else
