### ISSUE TITLE
ARC tickets section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1053]
Now that Amadeus is communicating with the DB i have not been importing tickets from ARC. 

But that ARC Tickets section has nothing available since 2015.  

Can you just switch the location where tickets were being pulled from to show in there as well so we can see tickets issued on specific dates and what not?

**Comment by bradatkins** [comment]
I have hooked up this to Amadeus:

![image](https://cloud.githubusercontent.com/assets/8440255/15002727/5a9755fc-1172-11e6-9720-ff0ca7cead8d.png)
