### ISSUE TITLE
How come I cant do this? amount with cents ?

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1058]
![cc](https://cloud.githubusercontent.com/assets/14838466/14539729/89f9d90a-024f-11e6-8148-13fd8d13f0c1.png)

**Comment by Irena206** [comment]
Sorry Brad, I need this to be fix ASAP , please !
Thank you :)

**Comment by bradatkins** [comment]
Hmm that's odd...Can you try in Chrome or IE?

**Comment by Irena206** [comment]
I just tried on Chrome, is not working... it is weird , I noticed like two days ago before that it worked just fine.

**Comment by bradatkins** [comment]
I did a change because people were entering the dollar symbol. Let me check

**Comment by Irena206** [comment]
Any news ? :) :+1:

**Comment by bradatkins** [comment]
Try now?

**Comment by Irena206** [comment]
O yeah !
you are the BEST !
