### ISSUE TITLE
URGENT: 422649 - math wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1059]
base price with add on airfare should be $4594 so her balance due is wrong:

![image](https://cloud.githubusercontent.com/assets/8440903/14541816/d219f7e2-0259-11e6-9e7a-d2e97206267c.png)

**Comment by bradatkins** [comment]
Just did an update with Honor = N and it's OK

**Comment by ali206** [comment]
but it should've honored the original so why would we have to switch that to no?
