### ISSUE TITLE
Future Website - Search Box Size

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#106]
Hi Brad,

I am going to incorporate the search box that you built, into the new layout.

This is the how the current search box looks:
![image](https://cloud.githubusercontent.com/assets/10079829/5318974/0745e494-7c73-11e4-9cba-891ec426609e.png)

it is extended with empty space to the right.

Can you please make the search box 226 x 148 px:
www.206tours.com/index5.htm

![image](https://cloud.githubusercontent.com/assets/10079829/5319584/7e5ba1f4-7c78-11e4-9249-08198385b81e.png)

**Comment by bradatkins** [comment]
I've changed the width, have a look

![image](https://cloud.githubusercontent.com/assets/8440255/6216911/49db196c-b5dc-11e4-8208-a7984e02c66c.png)

**Comment by ronenreinheimer** [comment]
Perfect!
http://www.206tours.com/index6.htm


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
