### ISSUE TITLE
Installments not coming through to Elavon?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1060]
I made this one Inactive because the amount was wrong since they had to PIF by Apr 16th but i'm not sure if this was a client or DB error:

![image](https://cloud.githubusercontent.com/assets/8440903/14562435/914860aa-02ea-11e6-8c2a-af97c848dfd9.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14562442/9d84f770-02ea-11e6-8546-3ff1b49a0177.png)

Also, the installment didn't make it to Elavon?

![image](https://cloud.githubusercontent.com/assets/8440903/14562427/82b0ea62-02ea-11e6-94da-8342dd89bbfc.png)

**Comment by bradatkins** [comment]
Fixed
