### ISSUE TITLE
Issues with registering existing clients| 132c9ac83c987bef16827d05d452a4f7 (session id) - Piernha

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1062]
please review video i FW to you.

132c9ac83c987bef16827d05d452a4f7 

![image](https://cloud.githubusercontent.com/assets/10079829/14565942/72526694-02fb-11e6-8f82-05e5a9158cfc.png)

**Comment by bradatkins** [comment]
Fixed
