### ISSUE TITLE
DB issue | DB is generating excel spreadsheet from recap page (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1063]
![image](https://cloud.githubusercontent.com/assets/10079829/14567737/85051efa-0303-11e6-893e-e35754d2139b.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14567727/74b1c788-0303-11e6-81bd-1e66fb4b9a67.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
ty
