### ISSUE TITLE
DB issue | unable to process new reservation (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1064]
I FW to you an email with a video

![image](https://cloud.githubusercontent.com/assets/10079829/14570837/3bdb0544-0314-11e6-93d8-0d9202c23016.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14570795/0c9b1792-0314-11e6-8f96-b4fb10610ac6.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14570821/26cc34ac-0314-11e6-9591-3413c967c215.png)

**Comment by bradatkins** [comment]
Is Yaritza using the same version of Chrome as others? I noticed she has some themes applied as well.
