### ISSUE TITLE
no order # in email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1065]
![image](https://cloud.githubusercontent.com/assets/8440903/14580891/e744ff60-03ab-11e6-87c9-87451139455c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14580894/edafed42-03ab-11e6-85c4-5a3e089ce796.png)

**Comment by bradatkins** [comment]
Do you see a payment for that amount around that date and time

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/14605418/7715cdf4-0546-11e6-9c2b-964cdbf83820.png)

**Comment by bradatkins** [comment]
We haven't had this happen in a while, post new example if it ahppens
