### ISSUE TITLE
FP030616 - Can't open recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1067]
i just keep getting a blank page:

![image](https://cloud.githubusercontent.com/assets/8440903/14581265/88995460-03b6-11e6-9848-2da20be5a0c2.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14581266/8d8409e8-03b6-11e6-8fd3-a13c563698b1.png)

**Comment by bradatkins** [comment]
Fixed
