### ISSUE TITLE
honor original price -is not working properly -#406906

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1069]
Invoice is from 2012 and was PIF, we want  to update an address and now is showing a refund due. 
and also If you could remove that number "414" from the address, it was never entered. 

![capture1212](https://cloud.githubusercontent.com/assets/14838466/14609594/7f430caa-0558-11e6-942e-a36b880b591d.PNG)

![2134](https://cloud.githubusercontent.com/assets/14838466/14609599/8615033a-0558-11e6-9210-553d4fc58c4e.PNG)

Thank you.

**Comment by bradatkins** [comment]
Lots of things have changed since 2012 (this feature didn't even exist back then).

I can't support changed to an order that is over 4 years old
