### ISSUE TITLE
Future Website - End User Home Page Login Box

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#107]
Hi Brad,

Can you please initiate a login box with a mouse over trigger for the My Account button.

![image](https://cloud.githubusercontent.com/assets/10079829/5320856/dc7cc4f6-7c83-11e4-88c0-e3c883c97fc9.png)

www.206tours.com/index5.htm

If you need anything from my end, please let me know.

**Comment by bradatkins** [comment]
Where do you want the New client link to go?

**Comment by bradatkins** [comment]
OK So this is pretty much done.

I replaced the my account image section from this:

<a href="https://www.206tours.com/register/loginaccount.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image38','','hp-images/top-nav/my-account2.png',1)"><img src="hp-images/top-nav/my-account7.png" width="122" height="26" id="Image38" border="0"></a>

to this:

    <a href="https://www.206tours.com/register/loginaccount.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image38','','../hp-images/top-nav/my-account2.png',1)"><img src=http://www.206tours.com/hp-images/top-nav/my-account7.png><i><form method=POST action=https://www.206tours.com/register/login.php><input type=image src=https://www.206tours.com/register/images/signin.jpg border=0></form></i></a>

and added the following css:

a {
    position: relative;
    cursor: pointer;
}

a > i {
    text-align: center;
    font: italic normal 90% Georgia, serif;
    line-height: 150%;
    color: black;
    text-shadow: white 0 1px;
    background: #FFF;
    background-clip: padding-box;
    box-shadow: 0 0px 2px rgba(0, 0, 0, 0.5);
    border: 2px solid #111;
    border: 2px solid rgba(0, 0, 0, 0.5);
    border-radius: 3px;
    position: absolute;
    width: 250px;
    left: 50%;
    margin-left: -125px;
    padding: 5px 0;
    top: 100%;
    margin-bottom: 15px;
    visibility:hidden;
    opacity:0;
    -webkit-transition: all .3s ease; 
    -moz-transition: all .3s ease; 
    -ms-transition: all .3s ease; 
    -o-transition: all .3s ease; 
    transition: all .3s ease;


}

a > i:before, a > i:after {
    content: "";
    position: absolute;
    border-left: 10px solid transparent;
    border-right: 10px solid transparent;
    bottom: 100%;
    left: 50%;
    margin-left: -10px;
    margin-top: 10px;
}

a > i:before {
    border-top: 10px solid #111;
    border-top: 10px solid rgba(0, 0, 0, 0.5);
    margin-top: 5px;
}

a > i:after{
    border-bottom: 10px solid #FFF;
    margin-top: -2px;
    z-index: 1;
}

a:hover > i {
    visibility: visible;
    opacity: 1;
}

This is what it looks like.

![image](https://cloud.githubusercontent.com/assets/8440255/6090580/2b21393a-ae4c-11e4-8842-b56018974305.png)

Check it out here:

https://www.206tours.com/register/test2.php

You'll have to move your skype box down a bit

**Comment by ronenreinheimer** [comment]
Hi Brad,

I don’t think it is working correctly. I also can’t move the skype button, the layout is set the way we like it. Can you please work around this issue please.

Here is a mockup of how we would like this login mouse over to work (can you trigger it with a mouse over?)
http://www.206tours.com/index6-login-test.htm

Maybe you can place the login box image in some kind of floating div box?

[cid:image002.png@01D04459.7FDECB70]


[cid:image003.png@01D04459.7FDECB70]




God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Maybe you can find out what code amazon is using to make it work? If you hover over the your account button, the small sign in box should appear. If it doesn’t work, you might have to press refresh a few times. I hope this helps. I got it show up in IE browser.

[cid:image001.jpg@01D04459.DDBE9FE0]

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

We noticed that on the main client login page – NEW end users don’t have an option to sign up. So we will need to revamp this page.
https://www.206tours.com/register/loginaccount.php



God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
K, I've fixed the mouse over, I had to add a div around your skype table:

![image](https://cloud.githubusercontent.com/assets/8440255/6217450/fd9a3b18-b5e1-11e4-967f-894bf7147b10.png)

Please try this page again:

https://www.206tours.com/register/test2.php

**Comment by ronenreinheimer** [comment]
Hi Brad,

This is working on Chrome but not IE.

Looks like we are getting there. It also need a sublink for new clients.

This is kind of wide, can you match it to the image I send you?

Current:
[cid:image001.jpg@01D049F0.F1D76BF0]

Ideal:
[cid:image002.png@01D049F0.F1D76BF0]


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
I'm not seeing any images in your post?

**Comment by bradatkins** [comment]
I've changed the width, have a look

**Comment by ronenreinheimer** [comment]
Really? I’ll try again.


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Can you move white arrow of the box over to the first C in the word Account?

Can you make the border 1px, it looks like it is 2x now?

[cid:image001.png@01D049F2.DE8229D0]


See if you can match it to this, 2nd attachment in this email.

[cid:image002.png@01D049F2.DE8229D0]


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Done.

**Comment by ronenreinheimer** [comment]
I apologize Brad,

What I meant is for the entire box to shift to the right. The top white arrow should be directly under the first C – with the entire box centered under it. Attached is an image mockup.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Ok I've moved it.

![image](https://cloud.githubusercontent.com/assets/8440255/6222020/c44c795a-b61a-11e4-8e01-4f4515c1f1b2.png)

Still checking on Internet Explorer though

**Comment by ronenreinheimer** [comment]
Hi Brad,

It is perfectly positioned. It is working in Chrome, but not IE.

Can you also add the buttom link for new clients? as attached jpg?


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
What font class is that?

**Comment by bradatkins** [comment]
What font class is that?

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/6279483/fc3bb57c-b86f-11e4-96ae-d3af7932222c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/6279487/000c7b00-b870-11e4-882d-117249a40ccb.png)


Still working on IE

**Comment by ronenreinheimer** [comment]
Hi Brad,

I see this is coupled with the top navigation project you are working on, so it is difficult to see the sample. It looks correct on IE and Chome, but on my screens I don’t see a 1pt border around the box?

Please review attached ss.


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Border is there now...

![image](https://cloud.githubusercontent.com/assets/8440255/6314441/0bf4fb2a-b9ad-11e4-8afd-65c0a792eb6d.png)

**Comment by ronenreinheimer** [comment]
OK, great, when the top nav is all set, we will fine tune this login box.

Thank you Brad.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
works great, would just love to have it perfectly centered if possible?
