### ISSUE TITLE
422354 - commission not showing in correct spot

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1070]
and balance showing in view orders?

![image](https://cloud.githubusercontent.com/assets/8440903/14609646/cd27a296-0558-11e6-9583-536fe7b3ae00.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14609656/d528e996-0558-11e6-8222-12c8c2293a64.png)

**Comment by bradatkins** [comment]
This agent isn't setup correctly as he doesn't have a commission structure setup in "All Agents"
