### ISSUE TITLE
422163 - base price not showing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1071]
![image](https://cloud.githubusercontent.com/assets/8440903/14611449/47476d8e-0560-11e6-84f2-ea2f9beb9021.png)

**Comment by bradatkins** [comment]
That's because Stefanie cancelled them 

![image](https://cloud.githubusercontent.com/assets/8440255/14622263/bfe115f2-0596-11e6-8873-b43a0f5e919a.png)
