### ISSUE TITLE
0 Passengers with Birthdays within 30 days  (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1075]
![image](https://cloud.githubusercontent.com/assets/10079829/14614821/d996fb68-0570-11e6-9774-e8c5be17fefd.png)

**Comment by bradatkins** [comment]
This is correct. The only PAX with a birthday in the next two months is Mr Aguiar Order ID 420158

**Comment by ronenreinheimer** [comment]
from Rinda:

![image](https://cloud.githubusercontent.com/assets/10079829/14677635/58a976b8-06e0-11e6-9a45-de280ed9fe75.png)

**Comment by bradatkins** [comment]
Oh duh. I was checking if the birthday was between Today and 30 days from
today :(

Fixed

**Comment by ronenreinheimer** [comment]
TY!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
