### ISSUE TITLE
421523 - order status for regular DB users

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1076]
At some point they were given access to the order status drop down menu (i'm not sure when) but cannot actually change the order status still. The DB won't save it. 

I'm not sure if they're supposed to have access to that or not?

![image](https://cloud.githubusercontent.com/assets/8440903/14616096/e204f63c-0576-11e6-9df7-3e026bda16d4.png)

**Comment by bradatkins** [comment]
I tested it and it worked find. I need an example.
