### ISSUE TITLE
Wrong Return Date on Invoice | 206 Tours Inc.  - Order #423386 Tour #PG100316 October 11, 2016 (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1077]
![image](https://cloud.githubusercontent.com/assets/10079829/14618645/a20c024a-0581-11e6-9717-be08ec7bec9f.png)

**Comment by bradatkins** [comment]
I don't see any addons that would even trigger that? Does that make sense?

**Comment by ronenreinheimer** [comment]
Amanda said that the wrong date is listed.

**Comment by bradatkins** [comment]
Fixed
