### ISSUE TITLE
Future Website - Home Page Automatic Slide Show

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#108]
Hi Brad,

Can you please help me to setup an automated slide show for this section of the home page:
![image](https://cloud.githubusercontent.com/assets/10079829/5320908/6c6a62bc-7c84-11e4-9b6d-9b22fdce8c27.png)

Possibly with end user navigation controls – left & right) as per:
www.seabourn.com

Also do you know if we can maintain the rounded corners for the images?
www.206tours.com/index6.htm

*the exact size for the image is 704px x 201px
i really need it to be this size, i don't know if you can maintain the beveled edges?

**Comment by bradatkins** [comment]
I have it working on my test file:

https://www.206tours.com/register/admin/test.php

Can you upload the images you want to use so I can test them out?

Then we can fine tune it in your index6.htm

**Comment by ronenreinheimer** [comment]
Sure Brad, let me give you 3 images – hold on…..

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

Try these.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Upload them to the site please...

**Comment by bradatkins** [comment]
Can you upload them please?

**Comment by ronenreinheimer** [comment]
Done
http://www.206tours.com/hp-images/italy-hp.png
http://www.206tours.com/hp-images/holyland-hp.png
http://www.206tours.com/hp-images/fatima-hp.png
http://www.206tours.com/hp-images/greece-hp.png


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
OK check it out:

https://www.206tours.com/register/admin/test.php

I have the speed on image change every 1 second, only for testing...I can change it to whatever you want once we are done.

**Comment by ronenreinheimer** [comment]
OK cool – we going to have to change your name to Machine soon!

Can I have control of the script once you are finished? I think it just needs some minor tweaking if possible. Can we also do fading or other effects? We can’t have too much bouncing and stuff, most of our clients are older and we don’t want too much pizazz - we will need it to be smooth & classy.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
You'll be able to do whatever you want with it :)

**Comment by ronenreinheimer** [comment]
n1 OK cool!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

we need the script to be moved 49px to the right. It should start under the H of Home. Below and attached is the mockup site. Does this make sense?

[cid:image001.png@01D049F8.290F4CD0]

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Fixed, and I changed the speed to be 4 seconds on transitions

![image](https://cloud.githubusercontent.com/assets/8440255/6222113/61eb424e-b61c-11e4-8f7e-de22f1441b1c.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

I really like it. Please review 2 attached ss. On IE the images have to move more to the right and on Chrome they have to move up to line up with the top of the search box.

I know that cross browsing is annoying, but we will need it to be the same on IE & Chrome, a lot of people also use firefox, but that should line up pretty closely with Chrome.


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/6259789/a9ff0208-b7a4-11e4-80f0-7807d26fa192.png)

IE:

![image](https://cloud.githubusercontent.com/assets/8440255/6259881/c1f4aaf6-b7a5-11e4-94b4-9ef1b0c16422.png)

**Comment by ronenreinheimer** [comment]
n1 Brad!

Things are really falling into place!

Can you just give us a little space between the images? Please review screen shots.

Thank you again so much..

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
No sorry, the space cannot be changed. And really, it's only visible as the image is scrolling across for 2 seconds :)

**Comment by ronenreinheimer** [comment]
Maybe I can work the space in the images themselves. I’ll have to test that theory.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you relocate the control buttons for the slide show? Maybe centered directly under the slide show?

[cid:image002.jpg@01D0511D.11EA8CF0]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
