### ISSUE TITLE
Title on the invoice | booking 423399 - Fr. Thomas Corcoran (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1080]
![image](https://cloud.githubusercontent.com/assets/10079829/14646238/b74c581c-0626-11e6-828e-adbadce6f984.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/14659388/99aa019a-0669-11e6-8cda-4233d47d6f72.png)
