### ISSUE TITLE
Database not sending invoices to the right agent TOUR AM060316 | 206 Tours Inc. Order #423075: New Payment Received (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1082]
![image](https://cloud.githubusercontent.com/assets/10079829/14676931/81f06494-06dd-11e6-9ce1-9f1dbef5683f.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14676923/7da519b6-06dd-11e6-9351-d542e740ae9d.png)

**Comment by bradatkins** [comment]
This likely isn't a Series tour I'm guessing.

Series tours always goto rok@

![image](https://cloud.githubusercontent.com/assets/8440255/14695587/702d8f98-0741-11e6-9fb8-4bd518aad341.png)

**Comment by ronenreinheimer** [comment]
Can you tell me who set Series to YES?

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Elise

**Comment by ronenreinheimer** [comment]
TY Sir. I take it, you are the one who changed it to NO?

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Nope, I didn't touch it

**Comment by ronenreinheimer** [comment]
But when I checked it now, it was set to NO. does the DB tell you who changed it?

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Amanda
