### ISSUE TITLE
DB | Pilgrim Cap | Tour BG110716 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1084]
![image](https://cloud.githubusercontent.com/assets/10079829/14678277/0c6a0968-06e3-11e6-9685-862669d4e549.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14678322/346f678c-06e3-11e6-98f2-4991877ed7a3.png)

**Comment by bradatkins** [comment]
Yes it was the cancelled PAX. Fixed
