### ISSUE TITLE
Installment payments- weired !

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1085]
Hi Brad, 
This person is set up for installment payments, however I cant find her in all installment payments neither nor in all payments, so whats going there ? please help !
![captureaaaaaaaa](https://cloud.githubusercontent.com/assets/14838466/14679039/3a67ff52-06e6-11e6-80f7-ef639c808586.PNG)

**Comment by bradatkins** [comment]
Closing as we rewrote this installments stuff so lets see if this happens again.
