### ISSUE TITLE
DB PROBLEM: Account does not update (Katherine)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1091]
![image](https://cloud.githubusercontent.com/assets/10079829/14684762/797b2264-06ff-11e6-9dbe-f2202e4abaed.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14684805/b08fcc1e-06ff-11e6-8021-06f654f07e8d.png)

**Comment by ronenreinheimer** [comment]
Please let him know the single supplement option doesn't update as well

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
