### ISSUE TITLE
422579 - Blank ACH email again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1092]
Irena applied a $200 discount not that long ago to this booking and right after i received this email:

![image](https://cloud.githubusercontent.com/assets/8440903/14689421/39d37bf0-0715-11e6-88c0-ca50031d8263.png)

**Comment by ali206** [comment]
It seems to be so far any time Irena has done something, i have more examples if you need

**Comment by bradatkins** [comment]
Is she doing this when placing  an order or applying a payment from the admin?

**Comment by ali206** [comment]
applying discounts/payments from admin so far

**Comment by bradatkins** [comment]
I couldn't reproduce it, but I put in what I think will fix it. Let me know
