### ISSUE TITLE
 login situation for Harvest ?    FW: New Bookings.    (Sandy / Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1095]
![image](https://cloud.githubusercontent.com/assets/10079829/14711443/5515c714-07a7-11e6-8d02-4fd0beca7f03.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14711430/4c540f5a-07a7-11e6-82cc-40225c0a888b.png)

**Comment by bradatkins** [comment]
Sorry, what's their issue?

**Comment by ronenreinheimer** [comment]
Peter from Harvest is set up as the agent for the Agent Portal. 

Bronwyn works for Harvest and is doing most of the communications with us .  She needs her own log in on the same agent portal so both will be able to see eithers registrations.  

At this time Bronwyn is listed as the Harvest agent in our system ? 

Basically we need the agent portal to be available for multiple agents in the same office and for DB to have multiple agents on the same account as well. 

Does that make sense ?

**Comment by ronenreinheimer** [comment]
Peter from Harvest is set up as the agent for the Agent Portal.

Bronwyn works for Harvest and is doing most of the communications with us .  She needs her own log in on the same agent portal so both will be able to see eithers registrations.

At this time Bronwyn is listed as the Harvest agent in our system ?

Basically we need the agent portal to be available for multiple agents in the same office and for DB to have multiple agents on the same account as well.

Does that make sense ?


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
It makes sense; however, is currently not setup that way. One Agent cannot see another agent's info (regardless if they work for the same company)

**Comment by ronenreinheimer** [comment]
From Rinda:

Milanka worked hard to get them to work with us . Harvest brings us a large amount of business and this needs to be made a priority to make this happen and work properly for the client.

**Comment by bradatkins** [comment]
OK I made some changes; however, Peter and Bronwyn are not setup as the same company?
