### ISSUE TITLE
Invoice not updating 421555 (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1096]
![image](https://cloud.githubusercontent.com/assets/10079829/14720045/821ff9b6-07cd-11e6-8285-31ab1cd1daae.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14720044/7de17e10-07cd-11e6-98ab-9b2a72451e26.png)

**Comment by bradatkins** [comment]
Seems to be OK now
