### ISSUE TITLE
FYI - DB | CC payment on online reservation | booking 423424 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1097]
![image](https://cloud.githubusercontent.com/assets/10079829/14720135/ea473d1a-07cd-11e6-8944-6895b848513c.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14720139/ee2875b6-07cd-11e6-9cf3-6621da59ef8d.png)

**Comment by bradatkins** [comment]
There was a problem previously in specific situations where the CC form wouldn't show up. Let me know if you hear of it again
