### ISSUE TITLE
EC091216 - no tour dates showing on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1099]
![image](https://cloud.githubusercontent.com/assets/8440903/14744293/389eb424-0874-11e6-88c9-d4b44e87d5d0.png)

**Comment by bradatkins** [comment]
Likely fixed with a previous bug:

![image](https://cloud.githubusercontent.com/assets/8440255/14769815/6f7cf50c-0a2f-11e6-9e6c-3e62516d558a.png)
