### ISSUE TITLE
PG100316 - no dates

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1101]
![image](https://cloud.githubusercontent.com/assets/8440903/14748208/644bfb9c-0886-11e6-924a-ab36ef1b9d80.png)

**Comment by bradatkins** [comment]
Because they all have addons the departure dates are here:

![image](https://cloud.githubusercontent.com/assets/8440255/14750159/57305d1c-0891-11e6-801f-67493f38d149.png)

**Comment by ali206** [comment]
woops sorry
