### ISSUE TITLE
2017 Dates for Tour 222 Active in DB but not on Website at all (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1102]
![image](https://cloud.githubusercontent.com/assets/10079829/14754167/9082cb7a-08a7-11e6-809e-36fd021c870f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14754189/c6cb4f36-08a7-11e6-8861-9be11081f025.png)

**Comment by bradatkins** [comment]
This should be set to ALL

![image](https://cloud.githubusercontent.com/assets/8440255/14769798/14d6e432-0a2f-11e6-9872-e6dfb585787b.png)

**Comment by ronenreinheimer** [comment]
Ah yes, forgot about this code. TY!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
