### ISSUE TITLE
DB -  TI & Total cost of trip  | Tour JS060616 | Thomas Rose-423455 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1103]
Liz could not find the session ID

![image](https://cloud.githubusercontent.com/assets/10079829/14754640/9e65b5b0-08aa-11e6-8ddd-dd27fbf5c4eb.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14754636/96266e94-08aa-11e6-8c72-c16a907b3eb1.png)

**Comment by bradatkins** [comment]
Closing as we've done a lot of work in this area since then
