### ISSUE TITLE
No CC drop downs when registering

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1104]
![image](https://cloud.githubusercontent.com/assets/8440903/14792965/d4477d02-0aea-11e6-8ca4-b5d4690e7470.png)

tried to still confirm and got this message:
![image](https://cloud.githubusercontent.com/assets/8440903/14792971/db332738-0aea-11e6-9177-7fdb5c682476.png)

**Comment by bradatkins** [comment]
What is your session ID? If you didn't grab it, please do another test...

**Comment by ali206** [comment]
c14ddba305a987d35711334cda74c1ec

**Comment by bradatkins** [comment]
Fixed
