### ISSUE TITLE
currency drop down error

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1105]
i keep selecting united kingdom and when page refreshes pricing stays as USD but says Australia in currency box

![image](https://cloud.githubusercontent.com/assets/8440903/14793236/0f8413fc-0aec-11e6-8c27-28c47fc3defe.png)

**Comment by bradatkins** [comment]
Odd, I couldn't reproduce it...

![image](https://cloud.githubusercontent.com/assets/8440255/14803076/6c2d11d4-0b24-11e6-8356-9fc669d91d22.png)

**Comment by ali206** [comment]
I was doing it under tr #202 - still not working:

http://www.206tours.com/tour202/index.htm#tours

same thing under #111:
http://www.206tours.com/tour111/index.htm#tours

**Comment by bradatkins** [comment]
Fixed
