### ISSUE TITLE
ARC import

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1107]
i just imported a report from 0417, then tried the 0424 report and i just keep getting a blank screen. 

Is it the file name or DB error?
![image](https://cloud.githubusercontent.com/assets/8440903/14834022/227ff572-0bd0-11e6-88da-a98cc69a781c.png)

**Comment by bradatkins** [comment]
Any reason we are still importing this? I'm not sure we really need to?

**Comment by ali206** [comment]
B/c there is no feature for this with Amadeus and i need it for recap purposes

**Comment by bradatkins** [comment]
Sorry, I'm confused, what data is the ARC import giving you that Amadeus doesn't?

**Comment by ali206** [comment]
I need this b/c no tickets are showing in recaps before the start date of Amadeus officially posting ticket information. So for most of my April recaps for ex. do not show airfare in the recaps.

Do you remember when Amadeus started communicating correctly/officially with DB?

**Comment by bradatkins** [comment]
So really what we need is the recaps to look at Amadeus? This would remove
the need to import ARC, no?

**Comment by ali206** [comment]
no that's not what we need

I am no longer keeping my own excel sheet of tickets issued.  However i still need to check tickets that have been issued on a daily basis.

Currently, there is no link for me to look at tickets issued on a daily basis. 

I also need to be able to occassionally export all ARC issued tickets, but DB is not putting issued Amadeus tickets anywhere here:
![image](https://cloud.githubusercontent.com/assets/8440903/14889744/05c9d894-0d2e-11e6-9b20-21977c2b27c2.png)

And i need to import all tickets issued before Amadeus began communicating with the DB. 

Is that a little more clear?

**Comment by bradatkins** [comment]
Can you email me an ARC file so I can test?

I don't think we should be doing this, but if you think we do that's up to you :)
