### ISSUE TITLE
Recurring CC charges not showing as pending in DB?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1115]
![image](https://cloud.githubusercontent.com/assets/8440903/14887632/a1960ff4-0d24-11e6-8b29-c0ab540693b9.png)
![image](https://cloud.githubusercontent.com/assets/8440903/14887643/ab8f63c0-0d24-11e6-9855-3cc415bde4c0.png)

**Comment by bradatkins** [comment]
Hmm it appears as though the job wasn't running.

You should see ones for the following orders as well. I can run the jobs here manually to get the pending payments there too.

Let me know if you see an associated payment in Elavon for which orders and I can run them

![image](https://cloud.githubusercontent.com/assets/8440255/14905569/e031714e-0d7f-11e6-8c14-4aacc22639f4.png)

**Comment by ali206** [comment]
so far i don't see any of the above charges - is that what you're asking me to check?

**Comment by bradatkins** [comment]
I guess both, you should see a recurring charge. If not, it's likely you will need to set one up and we need to link it to the DB. 

I can pull the Transaction ID's if you want to look it up that way if that'd help?

**Comment by ali206** [comment]
Ok hold on sorry i'm a little confused by this one...you're saying the above picture of orders/payments are payments that have actually been made?

But they didn't post as pending to the DB?

So...

423080 - should not have been charged but i don't remember when you switched installments to not charge the next day, thought it was before this?
422646 - i see in Elavon now, not in DB
423149 - I don't see it in Elavon
423158 - i don't see in Elavon
423204 - I don't see in Elavon
423305 - cxld test booking, nothing in Elavon
422970 - I don't see in Elavon
423012 & 423011 - you already know about

**Comment by bradatkins** [comment]
Those orders are orders with Installments, and from my perspective didn't
"reoccur" and post a Pending payment in the DB...

**Comment by ali206** [comment]
ok so they can all be ignored b/c most of them in the list were set to "charge" the same or next day after the first initial payment which is wrong. 

so we can just ignore right?

**Comment by bradatkins** [comment]
I'm not sure...if they look OK in Elavon and are not posting in the DB I should probably update them...

**Comment by ali206** [comment]
Barely any of those were in Elavon though as charges on that date?

**Comment by ali206** [comment]
Why did you close this? Installment payments are still not showing as pending in the DB

**Comment by bradatkins** [comment]
Because we need to put in the revamped code that we were testing, and it
will solve these ones going forward

**Comment by ali206** [comment]
oh ok
