### ISSUE TITLE
Database issue when registering more than 2 clients  (Bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1116]
![image](https://cloud.githubusercontent.com/assets/10079829/14889054/2582593e-0d2b-11e6-8e7f-91ac71e9686b.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14889124/79cf71f2-0d2b-11e6-881c-bc74bd064478.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
