### ISSUE TITLE
418799 - balance should be $0.00

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1117]
![image](https://cloud.githubusercontent.com/assets/8440903/14892431/b979c048-0d38-11e6-8eb4-e21a95007931.png)

**Comment by bradatkins** [comment]
The SD Discount is now declined though?

**Comment by ali206** [comment]
Because the promo SD is showing on the invoice and it was applying it twice so i declined the payment we applied

**Comment by bradatkins** [comment]
I don't understand why you think the balance should be zero? There are no payments and no discounts on the order...

https://www.206tours.com/register/copysource/invoice_html.php?OrderID=418799&TravelerID=20736&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by ali206** [comment]
there were so i don't know how they just disappeared on their own..
