### ISSUE TITLE
Update: Currency Option  (*UK)   (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1120]
![image](https://cloud.githubusercontent.com/assets/10079829/14900263/c70760f6-0d5d-11e6-92a5-484d513ca57c.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
n1!!!!!!!!!!!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
