### ISSUE TITLE
#423080 big error ! DB charged a clinet after being PIF 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1122]
Im not sure how installment payment was set up when the client was  PIF. DB should know and communicate if the invoice has been PIF. Charge didnt post on the invoice, so Im going to apply it manually and obviously make installment payment inactive.
Please investigate further. 
Thank you !

![11](https://cloud.githubusercontent.com/assets/14838466/14956002/8668267a-104b-11e6-937d-800c6218222f.PNG)

![22](https://cloud.githubusercontent.com/assets/14838466/14956007/8b8787ea-104b-11e6-9b9a-f75bffc51c62.PNG)

**Comment by bradatkins** [comment]
This happened because Elise manually applied a payment of $2,794.00, outside of the installment cycle.
