### ISSUE TITLE
ASCENSION16 promo not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1124]

**Comment by bradatkins** [comment]
Ali -

Is this the same one Ronen was working on?

Brad

**Comment by bradatkins** [comment]
yes

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ali206** [comment]
yes that was the one Ronen was working on.  He said it was okay to go so I retried it and it didn't work. 

Not sure why you closed this b/c it's still not working?

**Comment by bradatkins** [comment]
Not working from creating the code?

**Comment by ali206** [comment]
I guess?

The promo code is active int he DB but doesn't work on bookings

**Comment by bradatkins** [comment]
It's setup incorrectly

![image](https://cloud.githubusercontent.com/assets/8440255/14971113/50026256-109d-11e6-85bd-0eb39b60d7de.png)

**Comment by ali206** [comment]
I didn't see that woops, ok i fixed it
