### ISSUE TITLE
URGENT:  423552- unable to apply any kind of discount

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1126]
we need to apply $600 discount and are unable to apply it in any way

![image](https://cloud.githubusercontent.com/assets/8440903/14967093/a31aacf6-1083-11e6-8ae9-8727695bab0a.png)

**Comment by bradatkins** [comment]
They worked fine for me, except this new one is setup with an invalid expiry date:

![image](https://cloud.githubusercontent.com/assets/8440255/14971110/3ec09b34-109d-11e6-82ec-e99746937cf5.png)
