### ISSUE TITLE
recurring payments not pending in DB from yest

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1127]
![image](https://cloud.githubusercontent.com/assets/8440903/14985183/5881a4b0-1114-11e6-8bc8-54848136e2e1.png)

**Comment by ali206** [comment]
Was Jose Maria Mendoza made inactive in All Installments? Because he should still be active, did I do that?  That's he didn't show as pending in the DB as well.

I still don't know why barbara's didn't post though - 423149

**Comment by bradatkins** [comment]
Jose's shouldn't be INACTIVE, I've fixed the bug. I didn't switch it back to ACTIVE though.

I think there was a previous bug around the time of Barb's order.

I can create an installment for her if you want. I'll need:

The amount 
The cycle (monthly, weekly, etc)
Date to process the next amount

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/15044835/2f62adbc-12a5-11e6-90f9-e4cb5aad10dc.png)
chg 6/3/16

Can you make Jose's Active? I can't do that and it should be
![image](https://cloud.githubusercontent.com/assets/8440903/15044890/81a482d0-12a5-11e6-941e-7ff9c638305a.png)
