### ISSUE TITLE
Client didn't receive invoice sent from data base (Bika / Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1128]
![image](https://cloud.githubusercontent.com/assets/10079829/14986475/15d30392-111a-11e6-8073-321202fc8dda.png)

**Comment by bradatkins** [comment]
If we (206 Tours) received the copy we were BCC'd on, then it's not a DB
issue unfortunately

**Comment by bradatkins** [comment]
Just a further note on this, the DB sent the email to: kblaser89@bellsouth.net not her icloud.com address. 

![image](https://cloud.githubusercontent.com/assets/8440255/15002847/99f337e2-1173-11e6-9650-4a2c7377af00.png)

**Comment by bradatkins** [comment]
Sorry, correction. It was accepted by ROK but blocked by her email provider:

![image](https://cloud.githubusercontent.com/assets/8440255/15002913/4502fc9e-1174-11e6-882d-4a9a3458b178.png)
