### ISSUE TITLE
419852 - tckt issued and in DB but not showing on recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1130]
![image](https://cloud.githubusercontent.com/assets/8440903/14992417/0591a3e8-1134-11e6-94f3-88014e7e9ab8.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14992426/0f17beb6-1134-11e6-8246-0e5c9d1177ac.png)

**Comment by bradatkins** [comment]
Check now
