### ISSUE TITLE
423549 - Client didn't receive email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1131]
![image](https://cloud.githubusercontent.com/assets/8440903/14996555/8cd5b218-1148-11e6-8716-282ae1b9a62e.png)

**Comment by bradatkins** [comment]
I believe this was reported already, and was told that we (206 Tours) received it (as the CC)

And since we received it OK, it's not a DB thing unfortunately

**Comment by bradatkins** [comment]
Duplicate of #1128 so I'll close this one
