### ISSUE TITLE
422407 - tckts issued but not showing on recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1132]
![image](https://cloud.githubusercontent.com/assets/8440903/15016611/fb78639a-11df-11e6-8659-04b6d79e0e0b.png)

No tckt #'s on flight itinerary in DB either:
https://www.206tours.com/register/flight_itinerary.php?OrderID=422407&PassengerID=25314299

**Comment by ali206** [comment]
nothing for wakely on flight itine ither:
https://www.206tours.com/register/flight_itinerary.php?OrderID=422407&PassengerID=25314298

**Comment by bradatkins** [comment]
That's because we haven't received the ticket #'s from Amadeus yet...if you
see them in Amadeus, can you send me a screenshot (including the PNR)

**Comment by ali206** [comment]
But they were issued on April 21 so how could they not be received yet?

I don't use amadeus

**Comment by bradatkins** [comment]
I'll need the PNR from Amadeus to track it down. Can you get it from someone?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/15018083/364a3268-11e6-11e6-9147-504b870350fd.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15018102/42802074-11e6-11e6-90e4-8ac76aabf8af.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15018109/4b0c25f8-11e6-11e6-927b-5147d2419a5d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15018130/5c327666-11e6-11e6-8edd-6a1e470e6522.png)

**Comment by bradatkins** [comment]
The agent didn't put the DB Order # in the Remarks from what I can see in
my files. Can you confirm?

**Comment by ali206** [comment]
then how would the flight itin show if no order # was associated with it?

**Comment by bradatkins** [comment]
because it was there at one point. Check the record in Amadeus and see if it still has it...

**Comment by ali206** [comment]
Rinda re-entered but still not showing, she did at 12:45 and Sandy said it takes an hr to update in the DB

**Comment by bradatkins** [comment]
It's because they were still associated on PNR #3SCVA8 for whatever reason?

Check now.
