### ISSUE TITLE
423310 unable to pay in her currency through website

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1133]
![image](https://cloud.githubusercontent.com/assets/8440903/15019777/6d3c65e6-11ed-11e6-9331-087c59d98d36.png)

![screen shot 2016-05-04 at 11 15 51 pm](https://cloud.githubusercontent.com/assets/8440903/15019790/7a3ecbd0-11ed-11e6-802e-e1b23d6bf9c9.png)

![screen shot 2016-05-04 at 11 15 46 pm](https://cloud.githubusercontent.com/assets/8440903/15019799/7eeb9866-11ed-11e6-8b20-6d59173c793f.png)

**Comment by bradatkins** [comment]
Hey -

I logged in as her with both IE and Chrome and couldn't reproduce any errors, nor do I see any errors on the screenshots? Perhaps you can ask her what was going wrong?

**Comment by ali206** [comment]
We don't want to bother client too much about this so we just rebooked her in USD so we can process payment
