### ISSUE TITLE
Payments not going through (Patrick)

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1134]
Hey,

Client went online to make a payment to register for Tour 200 – June Departure – and the page timed out on making a payment.

I went in to fill out her info, got to the page to make a Payment, filled in the info and hit “Confirm Order” – and it brought me back to the Payment Page to re-enter in all of the info for on reason. (Payment Page is in Stop Motion)
![patrick](https://cloud.githubusercontent.com/assets/8440903/15025222/44e4a964-1206-11e6-84a8-f63df4d49fc2.jpg)

**Comment by bradatkins** [comment]
Need more info...type of payment etc...

**Comment by ali206** [comment]
I think this was the clients CC - will close

**Comment by ali206** [comment]
Asking patrick for more info

**Comment by ali206** [comment]
This is all info he has:
Payment was attempted with a Visa Debit card. On the clients end (via the website), and then I tried through the database with no success.

**Comment by bradatkins** [comment]
Is VISA Debit the same thing as a Visa? I'm not familiar with that...it may
not be supported by Elavon?

**Comment by ali206** [comment]
Debit card is the same as an ATM card - Elavon accepts it

**Comment by bradatkins** [comment]
Debit transactions seem to be structured differently in Elavon though, so I don't think we (the DB) supports it...

![image](https://cloud.githubusercontent.com/assets/8440255/15046590/9299355a-12ae-11e6-8f14-e3f810530e36.png)

**Comment by ali206** [comment]
Why can't the DB support it? A lot of people use their debit card

**Comment by bradatkins** [comment]
The DB can support it, but I was requested to set it up for credit cards.

Please enter a separate request and we can mark it for future enhancements.

**Comment by ali206** [comment]
Is there a different way of processing Debit Cards?

**Comment by bradatkins** [comment]
I should currently you process them manually. The DB does not support Debit cards currently. We'd have to add it to the enhacenemnt list

**Comment by ali206** [comment]
I know, Sandy asked me if they get processed differently than CC's and I didn't know the answer that's why I asked you

**Comment by bradatkins** [comment]
Apparently they Elavon has a difference way to process the Debit cards...not really sure what it is yet...nor why it would be different, but I'm sure there's good reason.
