### ISSUE TITLE
Return to Database Main Page (Patrick)

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1135]
Hey,

Forced through a Registration (via Check) – made the registration through Database, and on the last page – there is no link to click that will bring me back to the Main Page? No “Back to Order” link so I can get back to Admin Page for Database?
![patrick1](https://cloud.githubusercontent.com/assets/8440903/15025261/6ef5f442-1206-11e6-84ab-5c0e58a23fe6.jpg)

**Comment by bradatkins** [comment]
That's because the order wasn't placed starting from the admin...

**Comment by ali206** [comment]
From Patrick:

No, it was all booked through the database. Brad keeps saying that, but none of my reservations are done through the website - always database.

**Comment by bradatkins** [comment]
He needs to start his order from here:

![image](https://cloud.githubusercontent.com/assets/8440255/15045912/139a7c80-12ab-11e6-969b-ac3064dead0c.png)
