### ISSUE TITLE
how do i change generic terms and conditions for all series tours?

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1136]
![image](https://cloud.githubusercontent.com/assets/10079829/15027572/7d81a202-1212-11e6-836c-0c3e697c4932.png)

**Comment by bradatkins** [comment]
in the www/register/ directory there is a file called terms.txt

**Comment by ronenreinheimer** [comment]
OK, thank you – that is what I thought  -  I just didn’t have a copy on our local server.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
