### ISSUE TITLE
URGENT:  need ASAP -- unable to login as pax - 423585

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1140]
![image](https://cloud.githubusercontent.com/assets/8440903/15050315/112d3a76-12c1-11e6-9478-df28abeb45d2.png)

I was trying to login as client to see if we can set her up for installments b/c we can't do it through payments section in DB

**Comment by bradatkins** [comment]
once you've made the initial payments, you can't sign up for installments
currently

**Comment by ali206** [comment]
that seems odd b/c of certain bookings that start installments months after already making a payment but ok i guess

**Comment by ali206** [comment]
Why is this closed? I still can't login as any pax through the website

![image](https://cloud.githubusercontent.com/assets/8440903/15114697/2be4317a-15c9-11e6-9f8b-bd39ab9ea270.png)

**Comment by bradatkins** [comment]
Because you can't make installment changes...

The page loads fine for me. Is it loading for anyone else?

**Comment by ali206** [comment]
no i get the installment thing but i can't login as anyone which was the orig. issue of this post

Irena can login is under 423585 but i can't

**Comment by bradatkins** [comment]
If Irena can but you can't, it's not a DB thing...
