### ISSUE TITLE
Question about pdf invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1141]
since we no longer have access to pdf invoices, when we need to save an invoice to email it out to insurance company etc., how are we supposed to do that?

**Comment by bradatkins** [comment]
You can email it right out from the admin?

**Comment by ali206** [comment]
I know but we can't add attachments in that area and with the ins. company we usually have to attach the paperwork they sent us.  So if we did it through the DB we'd have to send the ins. company 2 separate emails for 1 claim which is confusing.  

We've been sending the invoices to ourselves and then fwding that email to the ins. company but we were wondering if there was an easier way.

**Comment by bradatkins** [comment]
Unfortunately the PDF invoice has been decommissioned. It's not compatible with the current layout.
