### ISSUE TITLE
URGENT:  422130/422131 - made 7 payments none of them in DB????

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1144]
7 payments of $203 on 4/28 showing in Elavon...not a single one of them in the DB:

![image](https://cloud.githubusercontent.com/assets/8440903/15055013/5531ad9e-12d8-11e6-996c-b6efb779b9a1.png)

**Comment by bradatkins** [comment]
This hasn't happened since, and it happened on the 28th again...I think I must have been mucking around in there.
