### ISSUE TITLE
urgent for Brad (Sandy / Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1147]
![image](https://cloud.githubusercontent.com/assets/10079829/15075829/6d63176c-1374-11e6-910a-59db43ad190a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15075834/73d8e5cc-1374-11e6-92d9-f001ee955f1c.png)

**Comment by bradatkins** [comment]
They just have to cancel the order...
