### ISSUE TITLE
DB Update: TSA SR & RM Coded automatically in 1 Line!!! and there's more! Big Deal (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1149]
![image](https://cloud.githubusercontent.com/assets/10079829/15083628/425dd836-139c-11e6-8ccb-b6e52cd2ad7f.png)

**Comment by bradatkins** [comment]
Yes it can be done. I'll add it as an ehancement for this phase.

Provide me a few complete examples (existing orders) of some of the
scenarios?

Preferrably orders that have been issued by Amadeus already.

**Comment by ronenreinheimer** [comment]
**from chris:**

I was playing around a bit more with this.

It works best with individually booked clients because you actually DO need to put “/p1” after each command, for some reason.

So, if there is a record with a single passenger as follows, this line works:

1.ROGERS/PAUL MICHAEL
SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL;rm 422098; sr GFML;sr wchr; ffn ua-90909809 – works beautifully with or without the /p

BUT If another person is on the record with him, for some poorly thought out reason they cannot share passenger # variable, ex:

1.ROGERS/PAUL MICHAEL     2.ROGERS/KATHLEEN ANN
SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL;rm 422098;sr gfml ;sr wchr; ffn ua-90909809/p1 – doesn’t work……

SO the following code, inputting passenger number in a whole host of places is required, irritatingly.

SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL/p1;rm 422098/p1;sr gfml/p1;sr wchr/p1; ffn ua-90909809/p1 – works, unbelievably stupidly

Still, I would organize the db in the ideal manner (with only a single /p or none at all). This would still dramatically cut down on work, boost data accuracy - and it would encourage everyone to book passengers individually. We should reach out to Amadeus to see if there is a way to reduce such a pointless redundancy by placing the passenger number elsewhere or w


I was playing around a bit more with this.

It works best with individually booked clients because you actually DO need to put “/p1” after each command, for some reason.

So, if there is a record with a single passenger as follows, this line works:

1.ROGERS/PAUL MICHAEL
SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL;rm 422098; sr GFML;sr wchr; ffn ua-90909809 – works beautifully with or without the /p

BUT If another person is on the record with him, for some poorly thought out reason they cannot share passenger # variable, ex:

1.ROGERS/PAUL MICHAEL     2.ROGERS/KATHLEEN ANN
SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL;rm 422098;sr gfml ;sr wchr; ffn ua-90909809/p1 – doesn’t work……

SO the following code, inputting passenger number in a whole host of places is required, irritatingly.

SR*DOCSYYHK1-P-US-429165654-US-16SEP56-M-10SEP17-ROGERS-PAUL-MICHAEL/p1;rm 422098/p1;sr gfml/p1;sr wchr/p1; ffn ua-90909809/p1 – works, unbelievably stupidly

Still, I would organize the db in the ideal manner (with only a single /p or none at all). This would still dramatically cut down on work, boost data accuracy - and it would encourage everyone to book passengers individually. We should reach out to Amadeus to see if there is a way to reduce such a pointless redundancy by placing the passenger number elsewhere or with a different command.

![image](https://cloud.githubusercontent.com/assets/10079829/15686977/7c84aec4-2740-11e6-9d1e-1981ad2a418e.png)

**Comment by ronenreinheimer** [comment]
**More from Chris:**

Maybe he can do it like this, seems to work:

1.	Wright/Chris    2. Wright/Meg
SR*DOCSYYHK1-P-US-000000000-US-10JUN83-m-30MAR21-wright-chris/p1;rm 425255;sr wchr;sr gfml;ffn dl-098767678/p1
This actually worked and only required 2 passenger number inputs; 1 after the TSA info, & 1 after all the following - order number, wheelchair, meals, frequent flyer number.

Here is the booking after I typed that code:

  1.WRIGHT/CHRIS   2.WRIGHT/MEG                                                 
  3  DL 044 Q 15JUN 3 JFKDUB HK2        4  1018P 950A+1 333 E0 D                
     MOVIES                                                                     
     6**SKY PRIORITY IN C                                                       
     DELTA ONE SVC THIS FLT                                                     
     SEE RTSVC                                                                  
  4  DL 045 T 25JUN 6 DUBJFK HK2        2  1145A 156P   333 E0 L                
     MOVIES                                                                     
     6**SKY PRIORITY IN C                                                       
     DELTA ONE SVC THIS FLT                                                     
     SEE RTSVC                                                                  
  5 SSR DOCS YY HK1 P/US/000000000/US/10JUN83/M/30MAR21/WRIGHT/C                
       HRIS/P1                                                                  
  6 SSR WCHR DL NN2/S3                                                          
  7 SSR WCHR DL NN2/S4                                                          
  8 SSR GFML DL NN2/S3                                                          
  9 SSR GFML DL NN2/S4                                                          
 10 SSR FQTV DL HK/ DL098767678/P1                                              
 11 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE & CHECK-IN:                    
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS - 12 RM 425255

Please add this email to existing github, it will be the most helpful

![image](https://cloud.githubusercontent.com/assets/10079829/15688175/be111480-2746-11e6-99a5-9941ae82421d.png)

**Comment by bradatkins** [comment]
I see a lot of comment back and forth, I just need to know what the line
needs to look like.

As well, I need to know the breakdown as to what is in the line (eg
departure date, etc)...what is each segment in the lin.

**Comment by ronenreinheimer** [comment]
Brad,

I am going to be away until tue the 7th. If there is anything urgent, please email me reinheimer@optonline.net<mailto:reinheimer@optonline.net>


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Have a look:

https://www.206tours.com/register/admin/listdata.php?FORM=Passengers&Search_TourDepartureDepartureID=8626&AmadeusTSA=Y

**Comment by chris206** [comment]
it is working great. is the /p going to be added soon after every specific request?

Until then we are adding it manually
