### ISSUE TITLE
Incorrect invoice   FW: 421290 - please make balance Zero apply $22.50 discount pp  (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1150]
![image](https://cloud.githubusercontent.com/assets/10079829/15084679/0e685afe-13a3-11e6-80f2-1348af561abd.png)

![image](https://cloud.githubusercontent.com/assets/10079829/15084680/14ca2274-13a3-11e6-8f14-3507a2cda37b.png)

**Comment by bradatkins** [comment]
Fixed
