### ISSUE TITLE
Agent filter / editing not working (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1151]
![image](https://cloud.githubusercontent.com/assets/10079829/15085455/659ac668-13a8-11e6-93b7-543b81e934e0.png)

![image](https://cloud.githubusercontent.com/assets/10079829/15085447/545a599a-13a8-11e6-8a28-3dfbf6b1052e.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY!
