### ISSUE TITLE
423619 - Ascension promo applied but not in payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1155]
client registered themselves and applied the Ascension promo which shows on her invoice but what she paid did not include the discount so now she's overpaid:

![image](https://cloud.githubusercontent.com/assets/8440903/15115588/c5b9c31a-15cd-11e6-8741-9418dd38eb9a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15115592/cee5d62c-15cd-11e6-94c6-b33dcf220516.png)

**Comment by bradatkins** [comment]
Fixed
