### ISSUE TITLE
423487 - Installments starting after registration

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1156]
I know you said this can't be done but it's being done - 423487:

she registered and made payments in then initiated monthly installments in May...

![image](https://cloud.githubusercontent.com/assets/8440903/15116226/7241db98-15d0-11e6-9127-0075d0d75f44.png)

This is all that's in the order audit though:

![image](https://cloud.githubusercontent.com/assets/8440903/15116266/90f47a1e-15d0-11e6-86da-b2f6316205c4.png)

**Comment by bradatkins** [comment]
How do you know this is an installment? I have no record of this order having any installments...

![image](https://cloud.githubusercontent.com/assets/8440255/15132475/31e541b8-1628-11e6-8819-fe1b6a4f6e2f.png)

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/15152493/6e1b2bae-16a3-11e6-9c06-3112dcfdd4d3.png)

**Comment by bradatkins** [comment]
We've done a lot of work on installments since then, if you notice it again, please post with new example
