### ISSUE TITLE
Order #423616  |  Brogan  |  Invoice Did Not Add Second Pax  |  Did Not Calculate Correct  |  Resent Invoice Never Arrived

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1158]
![image](https://cloud.githubusercontent.com/assets/10079829/15118565/be742804-15da-11e6-9663-9032ee0f0d1d.png)

**Comment by bradatkins** [comment]
Issues 1-3 I think are fixed.

Issue #4 is on AOL's side, they rejected the message:

![image](https://cloud.githubusercontent.com/assets/8440255/15167387/81af2a1e-16f6-11e6-9008-07a9dcd8b47a.png)
