### ISSUE TITLE
URGENT: 422639 - Payments in DB/Elavon $ amount not matching

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1160]
Transaction ID matches on Suzanne's payment on 4/28 but the $ amounts do not match.  

Processed in Elavon as $2,000 and in DB is showing as $5,488????

We will manually update it after you look at it.

![image](https://cloud.githubusercontent.com/assets/8440903/15122783/94e91f30-15ee-11e6-8c80-b39fc4249035.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15122788/9a1c6282-15ee-11e6-817b-36759fc8df70.png)

**Comment by bradatkins** [comment]
You can go ahead and update it now, as I'm tied up and won't be able to look at it, the screenshots are sufficient.

**Comment by bradatkins** [comment]
I'm guessing it was something I was doing that day since it hasn't happened. If you see a new order like this let me know
