### ISSUE TITLE
418828 - payment issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1162]
payment made not matching what's in DB (last one) - i updated booking

![image](https://cloud.githubusercontent.com/assets/8440903/15123169/6966c8c4-15f0-11e6-9fd9-a7912aca15cb.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15123178/76436be2-15f0-11e6-98a8-21b615f0d834.png)

**Comment by bradatkins** [comment]
I'm guessing it was something I was doing that day since it hasn't happened. If you see a new order like this let me know
