### ISSUE TITLE
DB | 2nd pax info missing | booking 423666 | Tour 118A | June 19 departure (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1164]
![image](https://cloud.githubusercontent.com/assets/10079829/15161147/0accfa50-16cb-11e6-82b5-9f1343f9e846.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15161162/152ce3a2-16cb-11e6-8123-cf1797375749.png)

**Comment by bradatkins** [comment]
Fixed. This was happening when the PAX was using the Go Back button
