### ISSUE TITLE
420842 - sent email to myself and never got it

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1166]
![image](https://cloud.githubusercontent.com/assets/8440903/15188428/baa4db34-1773-11e6-811e-37cf7ea094aa.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15188432/be8c7126-1773-11e6-86fe-a0f88044a938.png)

**Comment by ali206** [comment]
It's not just that order # either, i tried a few other bookings so it seems like an overall problem

**Comment by bradatkins** [comment]
Does this happen to anyone else? It seems to work fine for me...

![image](https://cloud.githubusercontent.com/assets/8440255/15525708/5e90c81c-21fa-11e6-8df4-fa522db59bb8.png)

**Comment by ali206** [comment]
I just tried again and got it so I don't know, guess it fixed itself
