### ISSUE TITLE
Flight Schedules in the DB (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1167]
Hi Brad,

please change the message as per Sandy:

--------------------

Dear <FIRST_NAME>,

We are delighted to provide your flight schedule for <TOUR_NAME> on <TOUR_DATE>. 

Please note: 
Your ticket has been issued as per your passport name provided to 206 Tours. If your name below appears differently on your passport please advise us by 12 noon (EST) tomorrow. The TSA (Transportation Security Administration) requires that the name on your airline ticket matches your passport exactly.

Please be advised that your final documents will be shipped approximately 3-4 weeks prior to departure via FedEx. In your final documents package, you will receive a copy of your flight schedule, a Magnificat, a final instruction booklet with important information that will help you prepare for your trip along with other informational material.

Did you know? 
You can now log-In to your account to track your package, view your flight schedule, edit personal information and more…
TO LOG IN:  Use your e-mail address OR 6 digit order #:  https://www.206tours.com/register/loginaccount.php

Please do not hesitate to contact us regarding any questions.

God Bless,

<font style=font-size:13.0pt;font-family:Arial,sans-serif;font-weight:bold;padding:0px;margin-left:0px;>206 Tours</font>
<font style=font-size:11.0pt;font-family:Arial,sans-serif;padding:0px;margin-left:0px;>333 Marcus Blvd<br>Hauppauge, NY 11788 USA
Tel: (631) 361-4644 or (800) 206-8687<br>Fax: (631) 361-3682</font>
<a href=mailto:orders@206tours.com>orders@206tours.com</a>
<a href=http://www.206tours.com>www.206tours.com</a>

<font size=5 style=font-size:8.0pt>Message ID: 1e</font>

![image](https://cloud.githubusercontent.com/assets/10079829/15189567/70ee31c4-1779-11e6-970e-6bb30ddeb990.png)

**Comment by bradatkins** [comment]
Done
