### ISSUE TITLE
Refer a Friend

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1174]
Hi Brad,

Can you link the terms link to this url:  http://www.206tours.com/refer/terms/index.htm

And then link it back to:  https://www.206tours.com/register/invite.php

![image](https://cloud.githubusercontent.com/assets/10079829/15260287/009354d4-1924-11e6-8f37-881fca248b0a.png)

**Comment by bradatkins** [comment]
Done, You can change your link in the terms file to just close the window.

**Comment by ronenreinheimer** [comment]
TY
