### ISSUE TITLE
Invoice # 423760 & 423682 | Showing Fr. Fr. twice  (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1179]
![image](https://cloud.githubusercontent.com/assets/10079829/15337651/b9f78a02-1c4a-11e6-9651-79563d8b158c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/15337645/b4fb35bc-1c4a-11e6-9171-8f357aad6b79.png)

**Comment by bradatkins** [comment]
Because he put Fr. in his First Name and his title

![image](https://cloud.githubusercontent.com/assets/8440255/15337758/2405fa28-1c4b-11e6-988e-2c7c1af88dc4.png)
