### ISSUE TITLE
Future Website - Mouse Over Trigger - Rollover Menu

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#118]
Hi Brad,

Can you please add Mouse Over Trigger (Hover) Rollover Top Navigation:
as per sample: www.seabourn.com

we changed the top navigation color, so i don't know about the color scheme yet - please leave it flexible: www.206tours.com/index6.htm

i will need to have access to the code, so i can modify the content (edit, delete, add), breakdown (order of info etc..), links, and colors? does this make sense? is this possible?

![image](https://cloud.githubusercontent.com/assets/10079829/5384917/8b48e9b4-808b-11e4-8b49-4b5138dc1094.png)

**Comment by bradatkins** [comment]
Here it is Ronen:

https://www.206tours.com/register/test.html

You can apply whatever CSS changes you want

<style>
/* Menu Styles */

.third-level-menu
{
    position: absolute;
    top: 0;
    right: -150px;
    width: 150px;
    list-style: none;
    padding: 0;
    margin: 0;
    display: none;
}

.third-level-menu > li
{
    height: 30px;
    background: #999999;
}
.third-level-menu > li:hover { background: #CCCCCC; }

.second-level-menu
{
    position: absolute;
    top: 30px;
    left: 0;
    width: 150px;
    list-style: none;
    padding: 0;
    margin: 0;
    display: none;
}

.second-level-menu > li
{
    position: relative;
    height: 30px;
    background: #999999;
}
.second-level-menu > li:hover { background: #CCCCCC; }

.top-level-menu
{
    list-style: none;
    padding: 0;
    margin: 0;
}

.top-level-menu > li
{
    position: relative;
    float: left;
    height: 30px;
    width: 150px;
    background: #999999;
}
.top-level-menu > li:hover { background: #CCCCCC; }

.top-level-menu li:hover > ul
{
    /* On hover, display the next level's menu */
    display: inline;
}


/* Menu Link Styles */

.top-level-menu a /* Apply to all links inside the multi-level menu */
{
    font: bold 14px Arial, Helvetica, sans-serif;
    color: #FFFFFF;
    text-decoration: none;
    padding: 0 0 0 10px;
    
    /* Make the link cover the entire list item-container */
    display: block;
    line-height: 30px;
}
.top-level-menu a:hover { color: #000000; }
</style>
<ul class="top-level-menu">
    <li><a href="#">Home</a></li>
    <li>
        <a href="#">Pilgrimages</a>
        <ul class="second-level-menu">
            <li><a href="#">Austria</a></li>
            <li><a href="#">Czech Republic</a></li>
            <li>
                <a href="#">Italy</a>
                <ul class="third-level-menu">
                    <li><a href="#">The Shrines of Italy</a></li>
                    <li><a href="#">All Italian Shrines</a></li>
                    <li><a href="#">Classic Italy</a></li>
                    <li><a href="#">Rome & Assisi</a></li>
                </ul>
            </li>
            <li><a href="#">Jordan</a></li>
        </ul>
    </li>
    <li><a href="#">Custom Tours</a></li>
</ul>

**Comment by ronenreinheimer** [comment]
Hi Brad,

How can we test this? Do you need access to a .index file?


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Just view the source of that page and take the code...

**Comment by ronenreinheimer** [comment]
Which url?

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you please give me the URL?

Thank you.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
https://www.206tours.com/register/test.html

**Comment by ronenreinheimer** [comment]
Thank you Brad,

I took the code, but where do I place it? I placed it in the head area? This is a test:
www.206tours.com/index6-roll.htm<http://www.206tours.com/index6-roll.htm>

feel free to do whatever you want with this html file.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
You'd place it wherever your existing menu is.

**Comment by ronenreinheimer** [comment]
My current menu is just rollover images:

[cid:image001.jpg@01D04B97.3E4A0E50]


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Right, so replace those rollover images with the stuff you grabbed....we
can work on the look of it.

**Comment by ronenreinheimer** [comment]
Here is a test Brad, it is not working in IE, it is working better in Chrome:
http://www.206tours.com/index6-roll3.htm



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Will you be able to make it look exactly like the current top nav?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
I am not sure if this helps – they changed their rollover menu, but I used the internet archive and found their old home page:
http://web.archive.org/web/20131230114829/http://www.seabourn.com/main/Main.action<http://web.archive.org/web/20131230114829/http:/www.seabourn.com/main/Main.action>



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Obviously no where near done yet, but working in IE and Chrome:

http://www.206tours.com/register/test2.php

You'll note that the Pilgrimages link has 2 sub menus, and the my account has the sign in and new customers link.

Now just to make it look pretty.

**Comment by ronenreinheimer** [comment]
Cool Brad, it’s going vertical in IE, but I am sure you are aware of that. just FYI, Milanka views everything in IE. Many of our clients are older, so we expect them to be on IE (not savy enough to download other browsers)

Keep going, I know you can do it. If you can get this project done, I’ll be able to start building all the internal pages, which will make Milanka happy.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
So I can get it pretty close:

http://www.206tours.com/register/test2.php

**Comment by ronenreinheimer** [comment]
Keep going Brad, this top nav is probably the most important aspect we need to move forward.

Try to make the buttons this color:
http://www.206tours.com/index6.htm


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK I got it in both IE 9 and Chrome. The images will need to change a tiny bit, but it works! Check it out and let me know

**Comment by ronenreinheimer** [comment]
I see a box on IE browser, on the left side:

[cid:image001.jpg@01D05012.94F0D930]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
What version of IE are you using?

**Comment by ronenreinheimer** [comment]
[cid:image001.png@01D05015.7DA90AB0]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad,

This is how it looks on my IE (below 1st ss). On Chrome it looks pretty good, it will just need some small cleanups. Will the buttons also rollover?


[cid:image001.jpg@01D05038.55E0C950]


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Same with this one, seems to work OK on the emulator for IE11 and my wife's computer so not sure?

**Comment by bradatkins** [comment]
WOrks on IE11 on my laptop...

![image](https://cloud.githubusercontent.com/assets/8440255/6380536/52894538-bd08-11e4-94da-3fe028b5be5c.png)

**Comment by ronenreinheimer** [comment]
What version of windows are you running?


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
7

**Comment by ronenreinheimer** [comment]
I got it work, it was my compatibility settings!

OK, this is great, now we can fine tune the top nav.



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad,

I didn’t want to make comments on the top nav – as I know you are still working on it. Milanka just called me and she wants to know where we stand with this segment of the project.

This is why I am reaching out to you.

This is your version:
http://www.206tours.com/register/test2.php

This is my html mockup:
http://www.206tours.com/tour96/index9.htm

Do you think they will be identical when you are finished?


If you need a sample of the top nav we want to emulate, please look at this link:

Try this:
http://web.archive.org/web/20140528100353/http://www.seabourn.com/main/Main.action<http://web.archive.org/web/20140528100353/http:/www.seabourn.com/main/Main.action>


Thank you again,

Ronen

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
working great!
