### ISSUE TITLE
Database Insurance Calculation Error (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1180]
96c4d2e6db57ac77957d058e03b7162e

![image](https://cloud.githubusercontent.com/assets/10079829/15337924/c921d86a-1c4b-11e6-9663-cc8bfa5f25f5.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15337930/cf147b60-1c4b-11e6-8db2-e12e0501dfa0.png)

**Comment by bradatkins** [comment]
Duplicate of #1186
