### ISSUE TITLE
#420566 internal comments 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1181]
Hi Brand, 
I tried this morning applying commissions on two orders #420566 and #423319 , and if I write something on internal comments , takes a payment away. If I go back to all payments is not showing it there. If I dont write anything there  payment gets applied, inst that weird ? 

Also after applying a commission (423319)  and order being PIF , still is showing on all orders like outstanding balance. 

![10](https://cloud.githubusercontent.com/assets/14838466/15362940/ee42ad1a-1ce4-11e6-8924-ce0b69a8c932.PNG)

![11](https://cloud.githubusercontent.com/assets/14838466/15362950/f5e275be-1ce4-11e6-801e-341b51e0386a.PNG)

**Comment by bradatkins** [comment]
Sorry, I'm not really sure what you mean because it shouldn't work like this.

Can you take a before and after picture?
