### ISSUE TITLE
423604 - unable to apply commission through payment screen

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1183]
I applied manually through the external link already but...

5e233c1774fc47a70752ac86b9e37c0a

![image](https://cloud.githubusercontent.com/assets/8440903/15395083/5f8faef4-1da4-11e6-9231-b68dcb2421c4.png)

After clicking yes this is the page i get and nothing happens:

![image](https://cloud.githubusercontent.com/assets/8440903/15395100/6970f5f4-1da4-11e6-8dfe-cba60a97f794.png)

**Comment by bradatkins** [comment]
Try now?
