### ISSUE TITLE
DB glitch, listing Alaska in name list when clients live in Colorado (Sandy / Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1184]
![image](https://cloud.githubusercontent.com/assets/10079829/15407352/60915012-1dd8-11e6-9036-4d605050d4bf.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15407348/5c4a25a6-1dd8-11e6-9f54-8672d3ca8d3f.png)

**Comment by bradatkins** [comment]
Fixed the data as I think was related to an old bug. Let me know if you see it again
