### ISSUE TITLE
2016 or 2017 Year is listed incorrect or missing throughout the website (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1185]
![image](https://cloud.githubusercontent.com/assets/10079829/15437090/2cd2fb52-1e93-11e6-9d20-26cf212552e2.png)

![image](https://cloud.githubusercontent.com/assets/10079829/15437086/273c8fb4-1e93-11e6-99f2-9717bce7a354.png)

**Comment by bradatkins** [comment]
Fixed
