### ISSUE TITLE
Installment for someone we can't find in DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1187]
![image](https://cloud.githubusercontent.com/assets/8440903/15475487/556b68d2-20d8-11e6-9a19-87f5904f6a96.png)

**Comment by bradatkins** [comment]
Looks like 420930 from what I can tell

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/15542292/20374424-225e-11e6-80d7-718fc506ecd9.png)

**Comment by bradatkins** [comment]
Oh, then I'm not really sure?

I wonder if there's a field where I can put the order number in the Elavon system. Let me check

**Comment by bradatkins** [comment]
Hmmm...unfortunately there's no "notes" field per say...
