### ISSUE TITLE
Installments for Camp

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1188]
Can you tell which 2 out of the 4 installments are associated with the 2 active bookings?

I need to suspend 2 of the installments but don't know which to select

![image](https://cloud.githubusercontent.com/assets/8440903/15475701/5bdddf78-20d9-11e6-8a36-e4771e913676.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15475714/6a1e4fd2-20d9-11e6-940d-c5f21289d757.png)

**Comment by bradatkins** [comment]
You can compare the DB's transaction ID and ELavon's transaction ID to find out the right one

**Comment by ali206** [comment]
I did that already, none of them match

**Comment by bradatkins** [comment]
I'd go with the first one then, but remember, there really isn't a relationship once it's in Elavon, so it doesn't really matter
