### ISSUE TITLE
All Tours Options - Search by DB code is not working

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#119]
Hi Brad,

In the All Tours Options section - the search by DB code is not working. can you please fix it when you have a moment. thank you.

![image](https://cloud.githubusercontent.com/assets/10079829/5439349/22c9c74e-844d-11e4-8a93-5d6fc7a503eb.png)

![image](https://cloud.githubusercontent.com/assets/10079829/5439384/4cc9fa00-844d-11e4-8936-2963527ec3df.png)

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/5714464/46824570-9a97-11e4-8fd3-4041dc1d0588.png)
