### ISSUE TITLE
Tour# Credit CV - shouldn't show on website

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1190]
I set this tour to not be displayed and i set the dept as sold out but it's still showing up on the website when searching by 3/22/17. 

This is a credit for future travel for a client, should never show up anywhere on the website so i'm not sure why it is. 

Can you fix please?

![image](https://cloud.githubusercontent.com/assets/8440903/15480534/166dc6cc-20f4-11e6-9d58-45ac42988cd1.png)

**Comment by bradatkins** [comment]
Fixed, but if you check there are a few other "credit" tours that have set the Display = "Yes"

**Comment by ali206** [comment]
ok i'll try to fix those
