### ISSUE TITLE
Incomplete Orders | RM100516 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1191]
![image](https://cloud.githubusercontent.com/assets/10079829/15480933/0193175a-20f6-11e6-9083-9fb6cd67b0cf.png)

**Comment by bradatkins** [comment]
His transaction was declined by Elavon

**Comment by ronenreinheimer** [comment]
from Liz

![image](https://cloud.githubusercontent.com/assets/10079829/15546662/c0cca298-226e-11e6-9071-a56f56934db3.png)

**Comment by bradatkins** [comment]
Please leave the order here so I can look

**Comment by ronenreinheimer** [comment]
Liz doesn't have this order anymore
