### ISSUE TITLE
Airfare not exporting to excel recap - JS060616

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1193]
https://www.206tours.com/register/admin/reports_recap.php?TourID=3439&TourDepartureID=32079&RecapType=ADMIN

![image](https://cloud.githubusercontent.com/assets/8440903/15552239/87787f44-2287-11e6-88e1-f4028f3b2d4d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15552253/93128750-2287-11e6-86bc-56a89b407ce9.png)

**Comment by ali206** [comment]
this tour also:
PZ053116

**Comment by bradatkins** [comment]
Ya it would impact all tours

**Comment by bradatkins** [comment]
Fixed
