### ISSUE TITLE
Manually adding costs box - needs more characters

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1196]
We were trying to add this cost to 421611 and i finally realized it wasn't working b/c the description was to long, can you add more characters?

I had to dumb down the description a lot but what we wanted to enter would look nicer on the invoice:

Hotel Sant'Andrea, June 10-11, Hotel Quirinale, June 11-16, transfer to train station on June 10, airport transfer on June 16 from hotel to airport

**Comment by bradatkins** [comment]
Fixed
