### ISSUE TITLE
419554 - made an ACH payment but i never received bank info

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1199]
![image](https://cloud.githubusercontent.com/assets/8440903/15778177/7fb38ad8-2962-11e6-92e0-e02ac345082d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15778205/a1133156-2962-11e6-8415-f4688e8ea7d6.png)

**Comment by bradatkins** [comment]
I think we fixed that previously, here's the info

![image](https://cloud.githubusercontent.com/assets/8440255/20780369/525c600e-b748-11e6-8b89-61bbebcee913.png)
