### ISSUE TITLE
search not working properly

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#120]
If you search for Aviv – you should get all the tours that feature tel-aviv. Tour 163 does not show up.

**Comment by bradatkins** [comment]
163 doesn't have "aviv" in the name?

![image](https://cloud.githubusercontent.com/assets/8440255/5696336/a94e230c-999a-11e4-9a09-845e6fc8bced.png)


only FIT-HL does

![image](https://cloud.githubusercontent.com/assets/8440255/5696337/b1059062-999a-11e4-85a9-d173bd845420.png)
