### ISSUE TITLE
URGENT: 422746 - Made ACH payment but i never received info

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1200]
This is 2nd one now

![image](https://cloud.githubusercontent.com/assets/8440903/15828532/ab847352-2bdd-11e6-8acd-b3f544b5f118.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15828537/b2ae4572-2bdd-11e6-816d-64841eda57d2.png)

**Comment by bradatkins** [comment]
Duplicate of #1215
