### ISSUE TITLE
Outstanding Balances in Reg. pax wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1201]
![image](https://cloud.githubusercontent.com/assets/8440903/15836151/77e8469e-2c01-11e6-8b0c-c190dcd87228.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15836167/80a4d2ca-2c01-11e6-82ee-2b00df866493.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15836173/8960ce1e-2c01-11e6-98e6-56a097df8260.png)

**Comment by bradatkins** [comment]
This agent is setup as GROSS, so the commissions apply to their outstanding balance. I'm confused?

**Comment by ali206** [comment]
No, only NET applies to pax balances. 

Gross shows on invoice/recap as *PRO which should not affect balance due

**Comment by ali206** [comment]
Gross still affecting balance due in orders screen
![image](https://cloud.githubusercontent.com/assets/8440903/17153668/a59b18a2-534b-11e6-8912-8fd72c91644e.png)


![image](https://cloud.githubusercontent.com/assets/8440903/17153675/b034cdf8-534b-11e6-836d-8e9b584a49e4.png)

**Comment by bradatkins** [comment]
Fixed
