### ISSUE TITLE
pilgrimages.com 2016 / 2017 Dates

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1202]
Hi Brad,

Can you please look into this issue. It shows 2016 dates, but it should be 2017 and a couple of our clients are complaining about it.

Also, any chance you can move **,17** to the same line?

www.pilgrimages.com/keas

![image](https://cloud.githubusercontent.com/assets/10079829/15861770/64985364-2c9b-11e6-8af7-7dfef1b5bd30.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Thank you Brad.

Any idea what is happening with this site? (this is a VIP client)

http://pilgrimages.com/frcalloway/holyland-december/

[cid:image001.png@01D1DEAC.259F19A0]

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/16886031/c6650638-4a9f-11e6-97b8-7302410925ac.png)

**Comment by bradatkins** [comment]
Which tour?

**Comment by ronenreinheimer** [comment]
http://pilgrimages.com/frcalloway/holyland-december/
DC122617

http://pilgrimages.com/frcalloway/mexico/
DC122716

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
