### ISSUE TITLE
ACH made thru DB not showing when searching in payments

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1204]
When i search by ECHECK and PENDING this ACH does not show on the list???

![image](https://cloud.githubusercontent.com/assets/8440903/15869120/fdcd9b94-2cb8-11e6-848f-25388580a892.png)

**Comment by bradatkins** [comment]
I tried it (with approved of course) and it seemed to work. Can you try again?

![image](https://cloud.githubusercontent.com/assets/8440255/16171005/e8254bca-3532-11e6-9e9e-8717faa94ad2.png)

**Comment by ali206** [comment]
Approved was never the issue, just that odd pending one. 

Seems ok so far...
