### ISSUE TITLE
Add to Github - Verification  (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1206]
![image](https://cloud.githubusercontent.com/assets/10079829/15873337/36d48b10-2ccc-11e6-8492-8801d21f17c4.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15873351/4f41bc86-2ccc-11e6-85d9-1032b884c715.png)

**Comment by bradatkins** [comment]
That's correct, it's not a required field...
