### ISSUE TITLE
Can't Create New Tours (Ronen / Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1208]
it goes to a blank screen. i didnt see a session id, but this might be it: f060edbfe541197df1f7093ff252f95a

![image](https://cloud.githubusercontent.com/assets/10079829/15897493/a80b9328-2d62-11e6-8268-397fb6e003b8.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15897499/ace90d26-2d62-11e6-89a0-05e4605779fa.png)

**Comment by bradatkins** [comment]
Is this still an issue?

**Comment by ronenreinheimer** [comment]
i think its ok now
