### ISSUE TITLE
Uploading documents for PAX to view - uploading to Tour Departure instead of pax

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#121]
We should be able to upload a single file to the specific departure which would be accessible to all registered participants.
From what everyone in the office is aware, we must upload a KBYG file to EACH passenger which is a substantial drain on time.

**Comment by bradatkins** [comment]
You can now upload documents to Tour Departures by going to the Departure, and at the bottom of the Departure:

Inline image 1
![image](https://cloud.githubusercontent.com/assets/8440255/7843052/2df6e720-0475-11e5-9ae0-a62b6ff5474e.png)


They then show up in the Customer Portal:

Inline image 2
![image](https://cloud.githubusercontent.com/assets/8440255/7843051/2b3e7278-0475-11e5-875e-8e91815f27fe.png)


Give it a try.
