### ISSUE TITLE
DB and Blue Sheet do Not Match (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1210]
![image](https://cloud.githubusercontent.com/assets/10079829/15907144/eeeb3eca-2d89-11e6-8adc-423c72ec2e7d.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15907133/e61b4b5a-2d89-11e6-98fa-3a85fb4a393a.png)

**Comment by bradatkins** [comment]
I'm confused:

![image](https://cloud.githubusercontent.com/assets/8440255/16170994/81d87c02-3532-11e6-8dbb-439acad0877c.png)

**Comment by ronenreinheimer** [comment]
Dear Ronen, 

                I had put the information back in on the DB side that is why he is seeing it.  I was just calling to your attention that sometimes things that are built in during registration will show on the blue sheet but when you go into the DB side to update and info you notice blanks.  This is especially crucial for rooming arrangements.  Thank you.

Sammie mentioned that phone numbers are not being retained lately.  Not sure what can be done.

**Comment by bradatkins** [comment]
Closing as we've done a lot of work in this area, if you have a new example please provide
