### ISSUE TITLE
Pre / Post Series Tour Options not showing up for clients

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1213]
c9cfb7f2237100f2e17135809c75c78e

Hi Brad,

It was working and now we don’t see them.

![image](https://cloud.githubusercontent.com/assets/10079829/15975335/0e04a480-2f1b-11e6-914d-80774746db01.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15975339/11d29914-2f1b-11e6-8956-7970bb0e8190.png)
![image](https://cloud.githubusercontent.com/assets/10079829/15975353/16bc6a72-2f1b-11e6-93a5-e8cd0234322c.png)

**Comment by bradatkins** [comment]
The option isn't marked as a "Stay" therefore it will not show up here.

To show it on the last page (after the order) mark it as a Post

![image](https://cloud.githubusercontent.com/assets/8440255/16065385/40a39256-3278-11e6-97e1-416ecb736632.png)

**Comment by ronenreinheimer** [comment]
thank you!
