### ISSUE TITLE
URGENT: ACH payment made but i never got bank info - still happening

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1215]
![image](https://cloud.githubusercontent.com/assets/8440903/16008073/0d4b7994-3144-11e6-93cc-84187e34fe11.png)

**Comment by bradatkins** [comment]
122000496/0091696203

I'm checking why it wasn't sent

**Comment by bradatkins** [comment]
Did you happen to receive it, just in a different email?

![image](https://cloud.githubusercontent.com/assets/8440255/16065643/9db33cc4-327a-11e6-86bc-9adca566c142.png)

**Comment by ali206** [comment]
This is all i got - but just noticed in your image....why is that email going to sales all of a sudden?

![image](https://cloud.githubusercontent.com/assets/8440903/16082401/2ded5554-32df-11e6-8b33-ad682a0ff572.png)

**Comment by bradatkins** [comment]
It wasn't going to sales, but coming "from".

Keep an eye out for another ACH and let me know if it's not working.

**Comment by bradatkins** [comment]
I think I fixed this up with the previous issue. Let's close this and open a new one if it happens again
