### ISSUE TITLE
Terms and conditions on the bottom of the invoice

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#122]
I just noticed, the invoice shows the incorrect link for the terms and conditions. The correct one is http://www.206tours.com/terms/wyd/ I tried to find where to update and I noticed the same information is on the recap but  I can’t update it.

 
![image](https://cloud.githubusercontent.com/assets/8440601/5460003/3afc69bc-852d-11e4-9453-faaa92a48441.png)

**Comment by bradatkins** [comment]
You can change this text in the Order Edit screen...
