### ISSUE TITLE
Flight Itinerary in DB  (Piernha)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1221]
![image](https://cloud.githubusercontent.com/assets/10079829/16050394/85f27844-3229-11e6-9d68-8cdbdc40d50c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/16050368/7024c9b8-3229-11e6-8f59-f9b0a0690cb3.png)

![image](https://cloud.githubusercontent.com/assets/10079829/16050352/66e4344c-3229-11e6-9325-d57766192d61.png)

**Comment by bradatkins** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/8440255/16065702/186c7cb4-327b-11e6-8cb2-89f78e8a8bfc.png)
