### ISSUE TITLE
Editing payment status screen

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1223]
After approving/editing the status of a payment in All payments, can you have DB stay on that screen?

Currently after you approve a payment it brings us back to all payments, then we have to type in booking # again etc..

57d3db277702b1105ede6884a4008f4d
![image](https://cloud.githubusercontent.com/assets/8440903/16119000/80afce34-33a7-11e6-8fdc-ef01905c86b6.png)

57d3db277702b1105ede6884a4008f4d
![image](https://cloud.githubusercontent.com/assets/8440903/16119005/87abd624-33a7-11e6-8c5d-cc59c27f943c.png)

**Comment by bradatkins** [comment]
Done
