### ISSUE TITLE
424101 - payments don't have a status in orders 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1224]
![image](https://cloud.githubusercontent.com/assets/8440903/16119169/4b76ebfc-33a8-11e6-9475-f12fde91c891.png)

but they do in payments:
![image](https://cloud.githubusercontent.com/assets/8440903/16119177/5ab12510-33a8-11e6-90f9-34e7436b45ad.png)

**Comment by bradatkins** [comment]
Fixed the bug, but I didn't update the payments status
