### ISSUE TITLE
Add to Git Hub: Searching "Tour Departures"

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1227]
![image](https://cloud.githubusercontent.com/assets/10079829/16164414/05791a12-34ac-11e6-9fd8-21c1a75ab37f.png)

**Comment by bradatkins** [comment]
I just did the same search and it seemed to work fine? Can you try again?

![image](https://cloud.githubusercontent.com/assets/8440255/16170848/0774aa02-352e-11e6-830d-952fdc8a1c8e.png)
