### ISSUE TITLE
#422196 DB not calculating totals correctly 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1229]
Hi Brad, 

The subtotal column is not reflecting correct totals. Updating the order is not working. 

---

Teresa Marie Kopietz 
17650 Wright St Suite 7
Omaha, NE 68130
United States
4024936650
kopietztravel@cox.net
Order #422196
Date: Jan 26, 2016
Tour TK082916
Destination: Pilgrimage to Assisi & Rome with Teresa Kopietz
Dates: Aug 29, 2016 - Sep 6, 2016
Trip Website:http://www.pilgrimages.com/kopietz

---

Dear Teresa Marie Kopietz,

We are delighted to confirm your reservation for your pilgrimage.
All trip inclusions are outlined as per the tour website: http://www.pilgrimages.com/kopietz
Below is your invoice, some helpful tips and general information.
Thank you for choosing 206 Tours.

Last / First, Middle Name   Departure City  Base Cost   Travel
Insurance   Protection
Plan    Sub-Total
1. Barie / Koni, Louann Omaha(OMA), NE/ 
Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****0037
    Expiration: Dec 4, 2024  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
1. Daley / Kristi, Sue  Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   Declined    Declined    $3,699.00
   Passport #: *****1818
   Expiration: Jun 22, 2019                
2. Floersch / Stacey, Jo    Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   $225.00 Declined  
   Passport #: *****3436
   Expiration: Jan 2, 2022  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
3. Kanne / Lisa, Ann    Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   Declined    Declined  
   Passport #: *****1680
   Expiration: Jan 24, 2023  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,699.00
4. Keating / Christa, Marie Phoenix(PHX), AZ/ 
   Phoenix(PHX), AZ    $4,049.00   $240.00 Declined  
   Passport #: *****5090
   Expiration: Mar 20, 2018  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $4,289.00
5. Kennedy / Mary , Joan    Omaha(OMA), NE/ 
   Atlanta(ATL), GA    $3,699.00   Declined    Declined  
   Passport #: *****7458
   Expiration: May 19, 2023  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00  
   Returning to Atlanta    $250.00         $3,949.00
6. Kocina Kerzman / Pamela, Ann Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   $225.00 Declined  
   Passport #: *****4680
   Expiration: Oct 17, 2023  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
7. Kopietz / Teresa, Marie  Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   $225.00 Declined  
   Passport #: *****5083
   Expiration: Aug 25, 2021  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
8. Marcil / Deborah, Lynn   Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   $225.00 Declined  
   Passport #: *****9265
   Expiration: Feb 26, 2026  
   Colosseum visit on September 5  $69.00  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
9. Micek / Laura, Anne Omaha(OMA), NE/ 
   Omaha(OMA), NE  $3,699.00   Declined    Declined  
   Passport #: *****8384
   Expiration: Jan 4, 2020  
   Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,699.00
10. Miller / Catherine, Ann Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****7139
    Expiration: Aug 7, 2018  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
11. Moore / Denise, Ann Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****7415
    Expiration: Sep 3, 2017  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
12. Moyer / Melynda, Karol  Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   Declined    Declined  
    Passport #: *****3690
    Expiration: May 12, 2026  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00  
    Full Day tour to visit Florence, on September 4 $360.00         $4,047.00
13. Nelson / Kimberly, Katherine    Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****6033
    Expiration: Aug 1, 2017  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
14. Shalgren / Lisa, Marie  Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****8382
    Expiration: May 6, 2025  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
15. Stibbs / Monica, Ann    Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****8642
    Expiration: Mar 15, 2026  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
16. Stratman / Nora, Ann    Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****3655
    Expiration: Dec 7, 2019  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
17. Sullivan / Constance, Rose  Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****1050
    Expiration: Feb 16, 2020  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
18. Taylor / Julie, Ann Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $240.00 Declined  
    Passport #: *****0921
    Expiration: Jan 25, 2022  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00  
    Full Day tour to visit Florence, on September 4 $360.00         $4,047.00
19. Woods / Anne, Therese   Omaha(OMA), NE/ 
    Omaha(OMA), NE  $3,699.00   $225.00 Declined  
    Passport #: *****4993
    Expiration: Feb 12, 2019  
    Colosseum visit on September 5  $69.00  
    Vatican Museums & Sistine Chapel visit on September 2   $54.00          $3,924.00
    
    Order Total:    $80,904.00
    Payment By  Date    Form of Payment Received
    Constance Sullivan  Jan 26, 2016    Credit card ($725.00)
    Koni Bari   Jan 26, 2016    Credit card ($725.00)
    Catherine Miller    Jan 26, 2016    Credit card ($725.00)
    Nora Miller Jan 26, 2016    Credit card ($725.00)
    Teresa Kopietz  Jan 29, 2016    Credit card ($725.00)
    Stacey Floersch Jan 29, 2016    Credit card ($7,848.00)
    Lisa A Kanne    Jan 29, 2016    Credit card ($500.00)
    Monica Stibbs   Feb 4, 2016 Credit card ($500.00)
    Monica Stibbs   Feb 4, 2016 Credit card ($225.00)
    Kimberly Nelson Feb 4, 2016 Credit card ($725.00)
    Deborah Marcil  Feb 9, 2016 Credit card ($725.00)
    Kristi Daley    Feb 9, 2016 Credit card ($500.00)
    Lisa Shalgren   Feb 9, 2016 Credit card ($725.00)
    Anne T Woods    Feb 10, 2016    Credit card ($725.00)
    Julie Ann Taylor    Feb 12, 2016    Credit card ($725.00)
    Pamela Ann Kocina Kerzman   Feb 16, 2016    Credit card ($725.00)
    Laura Micek Mar 3, 2016 Credit card ($500.00)
    Mary Kennedy    Mar 3, 2016 Credit card ($500.00)
    Patrick H Stibbs    Mar 3, 2016 Credit card ($725.00)
    Patrick H   Mar 31, 2016    Credit card ($750.00)
    Denise A Moore  Apr 1, 2016 Credit card ($725.00)
    Lori Matthews   Apr 22, 2016    Credit card ($3,199.00)
    Melynda Moyer   Apr 26, 2016    Credit card ($500.00)
    Patrick H   May 2, 2016 Credit card ($650.00)
    Patrick H   Jun 13, 2016    Credit card ($1,074.00)
    Stacey J    Jun 13, 2016    Credit card ($123.00)
    Stacey J    Jun 13, 2016    Credit card ($488.00)
    Christa M   Jun 13, 2016    Credit card ($123.00)
    Deborah L   Jun 13, 2016    Credit card ($3,322.00)
    Kimberly K  Jun 14, 2016    Credit card ($3,322.00)
    Nora Stratman   Jun 14, 2016    Credit card ($3,322.00)
    Lisa M  Jun 14, 2016    Credit card ($1,400.00)
    Constance R Jun 14, 2016    Credit card ($3,322.00)
    Denise A    Jun 14, 2016    Credit card ($3,322.00)
    Lori Matthews   Jun 15, 2016    Credit card ($123.00)
    Lisa M  Jun 15, 2016    Credit card ($1,422.00)
    Lori Matthews   Jun 17, 2016    Credit card ($2,900.00)
    Koni L  Jun 17, 2016    Credit card ($3,322.00)
    Laura Micek Jun 20, 2016    Credit card ($3,253.00)
    Mary Kennedy    Jun 20, 2016    Credit card ($3,503.00)
    Anne T  Jun 20, 2016    Credit card ($1,600.00)
    Anne T  Jun 20, 2016    Credit card ($1,722.00)
    Katie Miller    Jun 20, 2016    Credit card ($3,322.00)
    Balance Due on or before Jun 30, 2016 : $14,822.00

For Payments you may:
- Log into your account: https://www.206tours.com/register/loginaccount.php
- Call our office and we gladly take the payment over the phone: 1-800-206-8687
- Mail payment to : 206 Tours ~ 333 Marcus Boulevard ~ Hauppauge , NY 11788
- All prices in US Dollars.
  Terms and Conditions:
- Please be aware of terms & conditions as per: www.206tours.com/terms.
- Names on tickets must match names on passport (to avoid penalties or denied boarding).
- You can Expect final documents 3 to 4 weeks prior to departure.
- Valid passport & VISA are the sole responsibility of each passenger.

How to prepare for your journey:
For additional information about your destination and how to prepare for your trip please visit: http://www.pilgrimages.com/kopietz

Please feel free to contact us with any questions, concerns or special requests! We thank you very much for choosing 206 Tours. We wish you a wonderful journey!

Sincerely,
206 Tours Sales Team

---

206 Tours, Inc, 333 Marcus Blvd, Hauppauge, New York 11788, USA
Tel. (631) 361-4644  |   orders@206tours.com   |   www.206tours.com

**Comment by bradatkins** [comment]
Closing as we've done a lot of work in this area, if you have a new example please provide
