### ISSUE TITLE
#417177 apply a discount and fix invoice

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1230]
Hi Brad, 
for some reason discount is not being applied properly,(after updating still doesn't work) they should be PIF, so can you please make an invoice to show as PIF. 

![417177](https://cloud.githubusercontent.com/assets/14838466/16239870/ecf2e1e2-37b4-11e6-86c4-d37b78390b3d.PNG)

**Comment by bradatkins** [comment]
Done
