### ISSUE TITLE
Urgent: 422172 - balance due of $599 but payment won't work

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1235]
In orders balance due is showing as $599 which is correct but when you go to make a payment on the order it's showing a $0.00 balance due so no payment will go through. 

Katherine said this is not the first time this is happening today but this is the only example i have.

![image](https://cloud.githubusercontent.com/assets/8440903/16277429/e57c95a8-3880-11e6-8abb-c14192c26d26.png)

Session ID: 2da6462b749311f3122f879b3c2a4d21
![image](https://cloud.githubusercontent.com/assets/8440903/16277437/f1028c5c-3880-11e6-8b27-a619ea5a5ecf.png)

**Comment by bradatkins** [comment]
Seems to be OK now
