### ISSUE TITLE
DB Amadeus did not catch Name miss match (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1239]
![image](https://cloud.githubusercontent.com/assets/10079829/16283274/30b74a72-389a-11e6-9378-5d96a6847efd.png)

**Comment by bradatkins** [comment]
Fixed:

[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/16305055/19dcd0a6-3926-11e6-99a8-84502c29bc53.png)

**Comment by bradatkins** [comment]
This is odd, Brendon is no longer showing up on the latest update of this PNR?
