### ISSUE TITLE
ACH emails from DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1241]
In the email we're supposed to get with banking information, can you please add name of client and tour ID?

**Comment by ali206** [comment]
So there's 2 emails that come through for ACH payments, one with only bank information and then "New Payment Information" which has some of the things i listed above:

![image](https://cloud.githubusercontent.com/assets/8440903/16530416/02b106ec-3f96-11e6-8c98-73ec2ff2e9c5.png)


Can you combine both emails to create only 1 email as per above additions so we're only receiving 1? 
I'm not sure why there's 2 to begin with.

**Comment by bradatkins** [comment]
It now shows the requested info.

I don't seem to be getting duplicates when I tested.

Order ID: 424496
Tour Number: NEWLOOK
Departure Date: Jun 6, 2027
Customer: Brad Atkins
Routing #: 122000496
Account #: 0091696203
Payment Amount: 400.00

**Comment by ali206** [comment]
seems to only be showing for new registrations, i think you just tried to make another payment and i got no info:

![image](https://cloud.githubusercontent.com/assets/8440903/16846219/840818ac-49b9-11e6-844d-edc4a7138650.png)

**Comment by bradatkins** [comment]
OK I got it. You should have received one email for a payment of $103 with
the routing number and another email with the invoice (which is sent to the
client)

**Comment by ali206** [comment]
This came through without any tour/client name etc. info:

![image](https://cloud.githubusercontent.com/assets/8440903/16964788/38a23616-4dcb-11e6-98fe-b48b45227639.png)

**Comment by bradatkins** [comment]
I think we cleaned this up already
