### ISSUE TITLE
"Print all flight schedules" Issue (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1245]
![image](https://cloud.githubusercontent.com/assets/10079829/16317090/8605d21a-3957-11e6-8c9d-6a5a2ee59c73.png)

**Comment by chris206** [comment]
Hey Brad,

Zip file is now being compiled - but I am unable to open the html files on any computer. Additionally, the whole purpose is for us to be able to drag and mass print them - that doesnt work.

Any way to have a different file format? PDF, XLS, etc?

**Comment by bradatkins** [comment]
Closing this as #1571 would take care of it
