### ISSUE TITLE
Travel Power air from Atlanta - Having Issue displaying Atlanta as the default departure city (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1251]
Hi Brad,

I set Atlanta as the default departure city, but it is not reflecting on the website for clients. Can you please check to see why it is not working?

www.pilgrimages.com/travelpowerinc
## DB CODE: **NJ060917**

![image](https://cloud.githubusercontent.com/assets/10079829/16387966/0c60adca-3c65-11e6-8044-eb5a1778a45c.png)

**Comment by bradatkins** [comment]
Fixed
