### ISSUE TITLE
DB -Website: if only 1 airport (EWR) is possible, then why prompt to CHOOSE button?  (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1254]
Hi Brad,

If there is only 1 airport, can it simply display that airport without asking client to select for an airport?

![image](https://cloud.githubusercontent.com/assets/10079829/16423756/4d31e7d0-3d2b-11e6-957f-4b65eb7eade5.png)
---

![image](https://cloud.githubusercontent.com/assets/10079829/16423796/805a49a4-3d2b-11e6-8684-d07503c541de.png)

**Comment by bradatkins** [comment]
Done
