### ISSUE TITLE
421052 - DC081516

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1260]
Clients have insurance but not exporting on recap

![image](https://cloud.githubusercontent.com/assets/8440903/16493369/320e9712-3eb3-11e6-81fc-9214b9c2d0dc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16493415/63858fa8-3eb3-11e6-9d76-475d8d7189d1.png)

**Comment by ali206** [comment]
same with booking 421050, 421039 etc

**Comment by bradatkins** [comment]
When these were added as Travel Insurance add on costs, they weren't selected from the drop down.

I've fixed the orders

**Comment by ali206** [comment]
ok thanks, i sent out an email not to long ago to everyone in the office to remind them to select insurance option from drop down instead of manually typing
