### ISSUE TITLE
421051 - add on airfare wrong on recap DC081516

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1261]
should be $295 but showing as $445 on recap

![image](https://cloud.githubusercontent.com/assets/8440903/16493809/dcf51e48-3eb4-11e6-8c0e-fc21fa4b83e3.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16493834/f9b14372-3eb4-11e6-9a84-832b4b3978b4.png)

**Comment by bradatkins** [comment]
Fixed
