### ISSUE TITLE
423812 - cxlation ins problem

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1264]
Only cxlation insurance was accepted but was not showing on invoice. 

So we added it manually, and then when i tried to decline it and update the booking accordingly, it just brings me to a blank page and the invoice won't update.  

That's why cxl ins is showing as $598 pp which is wrong:

![image](https://cloud.githubusercontent.com/assets/8440903/16504190/a9e18246-3ee4-11e6-9039-6672cab5376b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16504193/b30c47f2-3ee4-11e6-80e6-99747dd5e528.png)

**Comment by ali206** [comment]
Irena managed to fix the cxlation insurance in a ridiculous way but the subtotal pp is still wrong, can you please fix that?

She had to decline all insurances, cancel the clients, un-cancel, update, that didn't work so she cancelled them again, un-cancelled them, accepted insurances and updated and for some reason that made the $299 show correctly?!? Kooky.

**Comment by bradatkins** [comment]
Im guessing we haven't had this show up again so it was fixed with a different fix. Let me know if you see it again
