### ISSUE TITLE
DB not saving uploads? (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1265]
![image](https://cloud.githubusercontent.com/assets/10079829/16521834/9840f3f4-3f67-11e6-9fa1-8eb6ac94d794.png)

**Comment by bradatkins** [comment]
There is no maximum, however you must upload one at a time (no CTRL+ENTER).

I suggest you delete and then re-add the attachments

**Comment by ronenreinheimer** [comment]
from Stef:
As it is saving the upload disappears. Attached you may find the video 

(i am fw video for you)

**Comment by bradatkins** [comment]
Fixed. It was the size so I increased the limit
