### ISSUE TITLE
423881 - ACH payment made but no bank info came through to my email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1267]
![image](https://cloud.githubusercontent.com/assets/8440903/16530374/cfe3bf70-3f95-11e6-9dd2-be8c9f0def72.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16530386/e0f82cec-3f95-11e6-9b58-d4dab88f737d.png)

**Comment by bradatkins** [comment]
I show it being emailed at 21:58 on June 30th?

![image](https://cloud.githubusercontent.com/assets/8440255/20780004/3dce1d82-b746-11e6-9664-71b5340954c9.png)
