### ISSUE TITLE
Limited Availability - on Websites (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1270]
![image](https://cloud.githubusercontent.com/assets/10079829/16629119/9d60a2de-4382-11e6-8c70-0282e31a78fc.png)

**Comment by bradatkins** [comment]
What would you like to do?

**Comment by ronenreinheimer** [comment]
should i create a button?

**Comment by bradatkins** [comment]
Up to you...

**Comment by ronenreinheimer** [comment]
Please try this:
http://www.206tours.com/register/images/limited-space-button.png


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
