### ISSUE TITLE
Orders issue - multiple bookings coming thru instead of just 1

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1274]
Last 4-5 new registrations that were entered last night either by client or 206 staff are all coming through multiple times:

![image](https://cloud.githubusercontent.com/assets/8440903/16687638/d97018de-44e7-11e6-875b-4c51dc7acf33.png)

**Comment by bradatkins** [comment]
People are double clicking the confirm your order button (sometimes more than double) Perhaps the site is running slow causing people to be inpatient.
