### ISSUE TITLE
Agent Portal Enhancement

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#128]
What if the agent wanted to rebook an existing client? there is no section like travelers with the shopping card on the agent portal end.

![image](https://cloud.githubusercontent.com/assets/8440601/5570867/60090994-8f56-11e4-9567-635b2ba34410.png)

**Comment by bradatkins** [comment]
Done. They can only see clients they've placed an order for before...

![image](https://cloud.githubusercontent.com/assets/8440255/8026467/f0131ff4-0d44-11e5-9add-a310ebaaff8c.png)
