### ISSUE TITLE
Database Error: Listing PAX 1 twice  | Sandoval/Robert & Emily | Tour JG092816 | Booking 424398

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1282]
![image](https://cloud.githubusercontent.com/assets/10079829/16735397/e319a56e-4756-11e6-9d76-c47f12cae324.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16735409/ef356612-4756-11e6-9719-35f522df2fe7.png)

**Comment by bradatkins** [comment]
Seems to be OK now
