### ISSUE TITLE
Database blanking out passengers and double charging them (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1283]
![image](https://cloud.githubusercontent.com/assets/10079829/16735735/378befca-4758-11e6-8c91-347206496d24.png)

**Comment by bradatkins** [comment]
Travel Arrangements weren't selected?

![image](https://cloud.githubusercontent.com/assets/8440255/16752183/5724eb34-47ad-11e6-8f14-9f7c934cafd6.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/16804730/364ce46e-48db-11e6-9cf7-c1a9875ca5da.png)
