### ISSUE TITLE
Not able to view blue sheets or edit orders (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1284]
![image](https://cloud.githubusercontent.com/assets/10079829/16735883/bfeebb04-4758-11e6-933f-f6eae3ab28a6.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16735915/da86c77c-4758-11e6-9957-7fae38eb74dc.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY
