### ISSUE TITLE
FYI - DB Invoice Terms concerning visa requirement (Sandy / Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1285]
Hi Brad,

Please edit the terms and conditions section of the invoice as follows:

Terms and Conditions:
- Please be aware of terms & conditions as per: www.206tours.com/terms.
- Names on tickets must match names on passport (to avoid penalties or denied boarding).
- You can Expect final documents 3 to 4 weeks prior to departure.
- Valid passport & VISA (when required) are the sole responsibility of each passenger.

![image](https://cloud.githubusercontent.com/assets/10079829/16737949/9f3f99e2-4761-11e6-879d-257ce1f84747.png)

![image](https://cloud.githubusercontent.com/assets/10079829/16737966/b0440bf6-4761-11e6-8e04-6f00717c6f4d.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY
