### ISSUE TITLE
Order #424418  Tour #111 October 15, 2016 | No name listed  (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1286]
![image](https://cloud.githubusercontent.com/assets/10079829/16739184/e8f3f448-4766-11e6-8589-62f16647ff21.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16739174/e0b95264-4766-11e6-9557-cc192052ba51.png)

**Comment by bradatkins** [comment]
Looks like the PAX double clicked the Confirm button.
