### ISSUE TITLE
 Double Orders & Double charges- over the weekend and I noticed one from today

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1287]
Please take a look at this list and  how serious the problem that we are having is.
Orders and credit card charges are being done twice, names are being overwritten. Orders in red are the bad ones.

All of them I just fixed and applied refunds manually.
![11](https://cloud.githubusercontent.com/assets/14838466/16740808/b4c0f484-476e-11e6-9abf-e27a16f007b8.jpg)

**Comment by Irena206** [comment]
from today 7/11



![capture2222](https://cloud.githubusercontent.com/assets/14838466/16740867/e5478640-476e-11e6-90a1-594aa698481c.PNG)



I was able to void this one, but Im sending you so you can see the time between two charges. 

![capture 33333](https://cloud.githubusercontent.com/assets/14838466/16740969/5939c00e-476f-11e6-9019-9cebdaff7ea0.PNG)

**Comment by bradatkins** [comment]
These are because the PAX double clicked the confirm button twice.
