### ISSUE TITLE
Database error: Duplicate paxs on same invoice | Lugo/Carlos & Maria | Tour EH110816 | Booking 424421 (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1289]
![image](https://cloud.githubusercontent.com/assets/10079829/16742657/ac0e98de-4776-11e6-9222-3adfb128009e.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16742673/b984d08c-4776-11e6-9afc-2d33d9a4c3c1.png)

**Comment by bradatkins** [comment]
I fixed this order; however, I'm not 100% sure I've fixed the root cause. If it happens again, please open a new issue.

**Comment by ronenreinheimer** [comment]
OK
