### ISSUE TITLE
URGENT - Dupe name | DB | Booking 424426  (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1290]
![image](https://cloud.githubusercontent.com/assets/10079829/16743664/70c13fe8-477b-11e6-84fe-14a40c00ea3e.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16743689/915655e0-477b-11e6-8fc1-a0c61d708ac9.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY
