### ISSUE TITLE
Database error: Duplicate paxs on same invoice | Lugo/Carlos & Maria | Tour EH110816 | Booking 424421 (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1293]
![image](https://cloud.githubusercontent.com/assets/10079829/16778852/dcbe6bd6-483d-11e6-946f-a97aa436ed61.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16778924/269404a0-483e-11e6-9abb-04e0262ff4aa.png)

**Comment by bradatkins** [comment]
This one is an odd one because the DB thinks there's only one PAX. What's the name of the other PAX?

**Comment by ronenreinheimer** [comment]
from Amanda:

It happened on a different booking as per my previous email too, 424416.

Brad’s comment doesn’t make sense at there is only one passenger but the database listed the passenger twice in one booking. 

(i am FW the email)

**Comment by bradatkins** [comment]
Seems to be fixed now
