### ISSUE TITLE
#424355 NZD client -clergy discount is  not showing correctly -urgent because client is waiting 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1295]
Hi Brad, 
This invoice is in NZD because client  wishes to pay in their currency. So amount for clergy discount in USD is $1058.80 and as per today exchange rate in NZD supposed to show as NZD 1,451.46. Clergy discount was applied in NZD as you can see below, but on blue sheet showing amount in NZD as USD, and on  customer invoice as "O" , so how we can fix this because client is waiting to receive  invoice and make a payment. 

![capture 11](https://cloud.githubusercontent.com/assets/14838466/16808544/ed7c861c-48ea-11e6-9005-b27749bce4f2.PNG)

![capture 22](https://cloud.githubusercontent.com/assets/14838466/16808561/f65c81d8-48ea-11e6-8629-66e3779d336e.PNG)

![capture 33](https://cloud.githubusercontent.com/assets/14838466/16808572/00c350ca-48eb-11e6-9d0b-152a638b3436.PNG)

![capture 44](https://cloud.githubusercontent.com/assets/14838466/16808579/07828444-48eb-11e6-8f9b-467b2a2f0d0e.PNG)

**Comment by bradatkins** [comment]
Fixed

**Comment by Irena206** [comment]
Thank you Brad !
