### ISSUE TITLE
DB to notify end users who do not complete their booking process - email that will offer a $100 discount

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1299]
Hi Brad,

Milanka would like the DB to send an email to end users who do not complete their booking process - which will offer them a $100 discount if they go back and finalize their order (it should be sent 24 hours after the process was initiated). Offer them Promo Code: **COMPLETE206**

Makes sense?

**Comment by bradatkins** [comment]
Yup makes sense

**Comment by ronenreinheimer** [comment]
Wow you are fast

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Doesn't mean it's done though ;)

**Comment by ronenreinheimer** [comment]
Of course – you are not God.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
This was done as part of the current work, 4GETMENOT was the discount code. It just needs to be turned on

**Comment by chris206** [comment]
Ok, great. I will let Sandy know.

Can we turn it on? Is there an on off switch that we have access to? (I dont have access to certain features)

**Comment by bradatkins** [comment]
No, it's something I have to turn on, but you guys can modify the email message / subject here:

![image](https://cloud.githubusercontent.com/assets/8440255/22294753/696f18f2-e2e2-11e6-830b-3d5b1da74da8.png)

Once you're ready I will turn it on and do some more tests.
