### ISSUE TITLE
Shipping Address in Orders (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1300]
![image](https://cloud.githubusercontent.com/assets/10079829/16843016/907293e4-49ad-11e6-81f8-4ba667fd5a2e.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16842999/84b06f36-49ad-11e6-9ae7-4c52cbf3874a.png)

**Comment by bradatkins** [comment]
This is now done
