### ISSUE TITLE
Sending Flights through DB| Flights are incorrect. (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1302]
![image](https://cloud.githubusercontent.com/assets/10079829/16847013/e2282ffa-49bc-11e6-9a3a-fbbdfccec2b7.png)

**Comment by bradatkins** [comment]
What's the PNR #?

**Comment by ronenreinheimer** [comment]
4G95AM

**Comment by bradatkins** [comment]
Hmm...I have PNR #5UWMRL associated with this order. Please check Amadeus
for conflicting records.

And PNR #4G95AM has no Order number in the RM section, so it would never
associate.
