### ISSUE TITLE
invoice showing wrong date on return  (Bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1303]
![image](https://cloud.githubusercontent.com/assets/10079829/16852015/289dfffc-49d4-11e6-83f9-d871162a62cd.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16852018/2c1d7126-49d4-11e6-9ae0-83c6757d551d.png)

**Comment by bradatkins** [comment]
Fixed
