### ISSUE TITLE
Missing Client CS031317 - (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1306]
463510e04f18cdc4107788041381e1c5

![image](https://cloud.githubusercontent.com/assets/10079829/16956509/b7fa2eca-4da6-11e6-9c8a-11cf7f9ae83d.png)

**Comment by bradatkins** [comment]
He seems to be there?

![image](https://cloud.githubusercontent.com/assets/8440255/17817405/5bcbc5c2-660c-11e6-8674-0342a1f6f961.png)

**Comment by chris206** [comment]
great - seems to be fixed
