### ISSUE TITLE
Database Class of Service Error (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1310]
![image](https://cloud.githubusercontent.com/assets/10079829/16964548/f8f03190-4dc9-11e6-9858-e4864a10cac3.png)

![image](https://cloud.githubusercontent.com/assets/10079829/16964053/743cbf38-4dc7-11e6-9952-6103ef6c40de.png)

**Comment by bradatkins** [comment]
I've put in an except for Alitalia.
