### ISSUE TITLE
issues with applying checks 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1311]
Hello Brad,
I just noticed something after just applied some payments(checks) to the invoice.
As you can see below outstanding balance on the main page in DB is not changing,but when you open actual invoice you can see the payment. However on the invoice that was email out to the client payments are not reflecting accordingly. 
Please take a look at. 
Thank you !

![capture 1](https://cloud.githubusercontent.com/assets/14838466/16993769/ba53e3d8-4e72-11e6-9b35-dba9599051cc.PNG)

![capture2](https://cloud.githubusercontent.com/assets/14838466/16993778/c63ebcea-4e72-11e6-99f5-73c87886738a.PNG)

![capture3](https://cloud.githubusercontent.com/assets/14838466/16993783/cda2ae1a-4e72-11e6-8b47-3f84f48c1f28.PNG)

**Comment by bradatkins** [comment]
Seems to be OK now..
