### ISSUE TITLE
RE: Shipping Error In DB (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1313]
![image](https://cloud.githubusercontent.com/assets/10079829/16998911/8ccb5fce-4e89-11e6-9f71-7cd9214eb69d.png)
![image](https://cloud.githubusercontent.com/assets/10079829/16998969/cdf51058-4e89-11e6-8e8a-05f58d40ad0c.png)

**Comment by bradatkins** [comment]
Fixed
