### ISSUE TITLE
All Orders showing balances and shouldn't be

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1314]
![image](https://cloud.githubusercontent.com/assets/8440903/17000289/ce5e15e8-4e8f-11e6-8142-256e8a8973c6.png)

**Comment by ali206** [comment]
Any chance you could fix this today?

**Comment by bradatkins** [comment]
Unfortunately not as I'm at the cottage

**Comment by ali206** [comment]
Lucky....when you get back then?

**Comment by bradatkins** [comment]
Yes, I'm back Monday night.

If possible, can you get me some examples of goth net and gross? I can't seem to nail this one without messing up the other.

**Comment by ali206** [comment]
Here are some examples but that's not what this particular issue is about. 

In All Orders (current Year) - every single booking is showing a balance due regardless if payments have been made. 


Net:

![image](https://cloud.githubusercontent.com/assets/8440903/17297729/f0be1f86-57d4-11e6-8e6c-0a95341cd284.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17297764/0ae0df5c-57d5-11e6-8a89-25e66563218a.png)


Gross:

![image](https://cloud.githubusercontent.com/assets/8440903/17298306/620f310a-57d7-11e6-8cce-15751aa6a819.png)


![image](https://cloud.githubusercontent.com/assets/8440903/17298304/5c0a632e-57d7-11e6-8da3-687e2c4f8dbe.png)
