### ISSUE TITLE
424574 - add costs making foreign currency disappear

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1315]
You can't tell now b/c i went in and updated the booking....

but sammie booked these pple in CAD thru our website, everything showed correctly and then she added an add cost, the booking only showed in USD. 

I updated and now it's back to showing USD & CAD.

CAD should never disappear though...

![image](https://cloud.githubusercontent.com/assets/8440903/17000571/1becb1f6-4e91-11e6-8e65-1f231b459fd5.png)

**Comment by bradatkins** [comment]
I couldn't reproduce it, but not sure I did it right?

![image](https://cloud.githubusercontent.com/assets/8440255/20779868/44679d4a-b745-11e6-834e-87806600877c.png)

**Comment by ali206** [comment]
i'll let you know if it happens again
