### ISSUE TITLE
 urgent!!  international charges -not working #424574

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1316]
Not able to process a payment through DB.
Manual Charges that need to be applied (for cc's we can only use external payment link) are not converting.
Discount was applied, showing as O on clients side (invoice) - not converting
Finally I processed the payment manually (merchant) , so now Im not even able to apply that payment , because its reading it as USD instead of CAD .Can you please take a look at and try to fix it. Client needs to see the invoice.

**Comment by bradatkins** [comment]
What is the CAD or USD value of the payment that needs to be applied?

**Comment by Irena206** [comment]
CAD 13,031.88

**Comment by bradatkins** [comment]
I'm confused, I used this link:

https://www.206tours.com/register/admin/applypayment.php?type=payment&OrderID=424574

and it worked OK?

**Comment by Irena206** [comment]
For us didn't work.
It was showing just "0".
Please fix discount , and both invoices should be PIF.

**Comment by bradatkins** [comment]
Can you try again, and I will look at the record

**Comment by Irena206** [comment]
I have to leave the office now, will do around 2 pm

**Comment by Irena206** [comment]
OK Brad I see now what you have been saying.
So you applied the payment through payments section, however I did via external link because I had to process the charge manually ( because through DB didn't work), so my only way to apply that payment was through the link. So, did you charge the card and that how the payment was processed? ( I mean sample charge) because I can apply just a payment there without charging a card .So im confused :)

**Comment by ali206** [comment]
Brad - irena's above message is still the issue at hand.....however she is fixing your test payment by applying the correct Transaction ID and client name so it shows kind of correctly for client (she just called about the payment that said test name that's why we're fixing it). 

However, the discount still is not converting.

**Comment by ali206** [comment]
Discount's applying twice on USD invoice = wrong:

![image](https://cloud.githubusercontent.com/assets/8440903/17037043/221a9e18-4f5d-11e6-9e5b-c4c1c9fbc5cc.png)

**Comment by ali206** [comment]
Any chance you could fix this invoice today?

#1. Refund of $196.50 is in CAD but DB thinks we applied a USD payment. It needs to show $196.50 on CAD inv and then you need to convert it for USD invoice.

#2. Discount of $200 USD is not converting to CAD on the CAD invoice.

we owe them more of a refund but it's confusing b/c not everything's converting in the right spots.

**Comment by bradatkins** [comment]
Fixed, have a check now.
