### ISSUE TITLE
DB Flight Summary Error - Missing ticket info (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1317]
![image](https://cloud.githubusercontent.com/assets/10079829/17025787/7ed09aea-4f2b-11e6-93ff-d922e87694e5.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17025795/88b49430-4f2b-11e6-80ab-695de71cd7ce.png)

**Comment by bradatkins** [comment]
Please take a screen shot of the Amadeus screen which includes the ticket #
so I can follow it up.

**Comment by bradatkins** [comment]
Must have been waiting on a PNR update, as it's there now:

![image](https://cloud.githubusercontent.com/assets/8440255/17027162/d3bc4a72-4f30-11e6-9bb0-ab561d379b1b.png)
