### ISSUE TITLE
URGENT - ACH bank information not coming through to my email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1320]
The only ACH email i received was for Kathleen Hayden..

![image](https://cloud.githubusercontent.com/assets/8440903/17030857/74c747a6-4f3f-11e6-8d3e-233c4bb2f91a.png)

**Comment by bradatkins** [comment]
You did get them, and so did I:

![image](https://cloud.githubusercontent.com/assets/8440255/17086713/38fec142-51c7-11e6-935a-ba7e70269675.png)

![image](https://cloud.githubusercontent.com/assets/8440255/17086714/48536ec2-51c7-11e6-9144-2bb943a20aff.png)

![image](https://cloud.githubusercontent.com/assets/8440255/17086715/548d11ca-51c7-11e6-860b-ef6099c42b6d.png)

![image](https://cloud.githubusercontent.com/assets/8440255/17086718/5fe77a24-51c7-11e6-835f-1743ece3a84f.png)

**Comment by ali206** [comment]
I never got those - maybe i'm not on payments email?

**Comment by ali206** [comment]
Emails being sent to that account were being spammed for some reason, sandy fixed it
