### ISSUE TITLE
FW: Shipping Errors in DB (Sandy / Steve)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1326]
![image](https://cloud.githubusercontent.com/assets/10079829/17062728/22ffa2a6-5002-11e6-9286-ec1db8099c79.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17062742/39beb0fe-5002-11e6-8b93-e93ca833f7d8.png)

**Comment by bradatkins** [comment]
Fixed, there was no field for Phone Number in this section.
