### ISSUE TITLE
RE: Disconnect credit card option - stop sending email reminders. (Sandy / Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1327]
![image](https://cloud.githubusercontent.com/assets/10079829/17104100/66cb77e0-524f-11e6-800a-62611bceafb7.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17104091/615b31ce-524f-11e6-8df5-cb28c5c48c96.png)

**Comment by bradatkins** [comment]
We talked about this previously, and came to the conclusion that there was no "clean" way of doing this.

**Comment by ronenreinheimer** [comment]
Brad,

Basically what we are looking for is a way not to have notification emails sent out to clients.
Is there a way to do this?>
Thank you,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold

206 Tours Inc.
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
We can stop the notifications, perhaps if the departure is marked as unlikely.

What we couldn't land on was how to stop clients from making payments
