### ISSUE TITLE
RL091916 - recap issues

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1328]
These $1.00 charges shouldn't be showing on recap:

![image](https://cloud.githubusercontent.com/assets/8440903/17107119/ea02cdb4-525b-11e6-9c8c-138061e6579f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17107127/f341fe4a-525b-11e6-858c-b781d7078b6b.png)

**Comment by bradatkins** [comment]
Fixed
