### ISSUE TITLE
Shipping Error In DB (Steve / Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1334]
![image](https://cloud.githubusercontent.com/assets/10079829/17112817/a4a08c1a-5275-11e6-9fe1-6b35f324e355.png)

**Comment by bradatkins** [comment]
This isn't a DB error. Fedex is saying their zip code isn't matching the
state?

**Comment by bradatkins** [comment]
Whoops, scratch my comment above. Fixed
