### ISSUE TITLE
ARC ticket issued 7/24 not showing in DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1335]
![image](https://cloud.githubusercontent.com/assets/8440903/17113555/44007344-5279-11e6-97c0-6c6af831ec06.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17113566/4fc70daa-5279-11e6-9191-d2db4cf06251.png)

**Comment by bradatkins** [comment]
Tickets will only show in there if they are successfully tied to an order. What order # does that ticket belong to?

**Comment by ali206** [comment]
Ok, Yaritza just added it in to the DB - 419726

I thought all tickets were supposed to show there regardless if they were tied to an order....

the way it is now, I still have to go 1 by 1 in IAR to check tickets then b/c the export from DB won't have all issued tickets either then...seems silly, how can we make this better?

**Comment by ali206** [comment]
Should i still be uploading weekly reports then so all tickets are in DB?

**Comment by bradatkins** [comment]
The purpose of hooking up to ARC was to produce itineraries, not for "general validation". I would assume everyone is validating the tickets before issuing the itinerary from the clients.

I don't even think it's possible to upload the weekly reports to the DB, as I've removed that menu option

**Comment by ali206** [comment]
They are validating and Rinda checks tickets as well but i'm also supposed to check tickets...make sure clients are PIF, names are spelled correctly etc. 

Why did you disable that feature again?

Going 1 by 1 in IAR is so time consuming and i'll do it if I have to but there has to be a better way, i'll talk to sandy

**Comment by bradatkins** [comment]
It was disabled because the whole structure behind the scenes changed.

I'm not sure why you have to go into IAR 1 by 1 as that report would still give the info, no?

**Comment by ali206** [comment]
Well it's not giving all info b/c you said not all tickets are there unless tied to orders...and not everyone in the office is good at doing that so it's not an efficient way of checking tickets necessarily if they all won't be in there

**Comment by ali206** [comment]
I can't do it that way currently anyway b/c the search box isn't working and the export info is not accurate

**Comment by bradatkins** [comment]
I just did a search and it was OK:

![image](https://cloud.githubusercontent.com/assets/8440255/17114672/eec9effe-527d-11e6-9101-8d38a516e1ca.png)

**Comment by ali206** [comment]
That parts ok but issue date still isn't working

**Comment by bradatkins** [comment]
Building a work around because "people aren't good at doing it" isn't a good idea.

**Comment by bradatkins** [comment]
Seems to work OK for the date?

![image](https://cloud.githubusercontent.com/assets/8440255/17114741/402139a2-527e-11e6-90e5-a647cfb0d49e.png)

**Comment by ali206** [comment]
That's dept date, i need issue date to work as well

I know a work around is not a good idea i'm not really suggesting that, but I can't control what pple in the office do so i'm trying to think of a better way to have consistent/correct information in the DB for ARC

**Comment by bradatkins** [comment]
Fixed issue date search
