### ISSUE TITLE
Tickets issued 7/22/16 in DB - few questions

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1337]
How is it possible for there to be dupes?
![image](https://cloud.githubusercontent.com/assets/8440903/17117431/039cdffc-528a-11e6-8040-b34727662d45.png)

These are seats a client purchased - is there any way you can clarify that in the DB that they're not regular tickets?
![image](https://cloud.githubusercontent.com/assets/8440903/17117449/1808db94-528a-11e6-9feb-b1a6b7bae401.png)

All of these tickets were voided - shouldn't they all show as $0.00?
![image](https://cloud.githubusercontent.com/assets/8440903/17117487/30b3a7d2-528a-11e6-81d9-602c98a6f743.png)

**Comment by bradatkins** [comment]
1) I've fixed the issue with the dupes going forward, you will still see dupes prior to today.

2) Is there a field in Amadeus that indicates the ticket was purchased by the customer? If so please take a screenshot. This data may or may not be included in our feed

3) I don't even see those tickets in the review screen?

**Comment by ali206** [comment]
#2. Will ask Sandy, I have no idea b/c i don't use Amadeus.

#3. They seem to have disappeared??  But the one's now showing in DB are showing without ticket cost??
![image](https://cloud.githubusercontent.com/assets/8440903/17144081/9431d3ee-5323-11e6-895e-68c03712080c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17144089/9b3bd2ac-5323-11e6-8a6e-d21f4f0933a2.png)


How do you search by ticket number?

I tried typing 006-7895696008, 0067895696008, 7895696008 and none of them worked

**Comment by bradatkins** [comment]
I search for 006-7895696048 and it came up OK?

**Comment by ali206** [comment]
Stef said that an issued seat will say DT instead of a ticket which says ET:

![image](https://cloud.githubusercontent.com/assets/8440903/17149184/32c7fad8-5338-11e6-88b1-02ca38d65325.png)


Ok searching by ticket is working, weird.

**Comment by bradatkins** [comment]
I do not have that field in the existing Amadeus feed unfortunately

**Comment by ali206** [comment]
Ok, so is there another way we can separate the 2?

**Comment by bradatkins** [comment]
Do you have any more examples?

**Comment by ali206** [comment]
If I find any i'll send them to you

**Comment by bradatkins** [comment]
Closing as we've done a lot of work in this area, if you have a new example please provide
