### ISSUE TITLE
Shipping label error | State | Order #421374  (Alexis)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1338]
Session ID: 25bdf3d9bd636a596fc005d57014cf79

![image](https://cloud.githubusercontent.com/assets/10079829/17146711/5d3feba0-532d-11e6-9123-d22ed3437aef.png)

**Comment by bradatkins** [comment]
Unfortunately those duplicates are because of historical "stuff" so they can't be removed, but I've put in a fix so this will still work. Try out the labels now.
