### ISSUE TITLE
DB "Choose Departure City" when NO CHOICE -- to open on city and price showing instead of (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1339]
![image](https://cloud.githubusercontent.com/assets/10079829/17148318/aed61b18-5334-11e6-8b0c-639ebea8a6b3.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17148331/c06487ca-5334-11e6-8ca9-19890a8ed77f.png)

**Comment by bradatkins** [comment]
Done, please test.

**Comment by ronenreinheimer** [comment]
TY!
