### ISSUE TITLE
422341 - order cxld but invoice says PIF, delighted to confirm registration etc

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1344]
![image](https://cloud.githubusercontent.com/assets/8440903/17153830/6dfc7fa2-534c-11e6-9036-92a4e5d1e205.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17153840/7de0e82c-534c-11e6-97b4-f6276e8107d4.png)

**Comment by bradatkins** [comment]
Fixed
