### ISSUE TITLE
Payments w/o an order ID on admin page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1349]
I'm trying to decline both of these and when i select decline, then save it brings me to a blank page. When I go back to this area your payment said declined though but 4 payments are still showing....can all of them be removed from this area?

Session ID: 5d0df45c487f2dfe5068394c6a94f1c3
![image](https://cloud.githubusercontent.com/assets/8440903/17189483/a4b1e384-540f-11e6-9ff1-ebff7c62310d.png)

Session ID: 5d0df45c487f2dfe5068394c6a94f1c3
![image](https://cloud.githubusercontent.com/assets/8440903/17189506/b9e712e2-540f-11e6-8fb6-86ee247c8956.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17189526/d14337c2-540f-11e6-9fd1-aba9e32bbea1.png)

**Comment by bradatkins** [comment]
Done
