### ISSUE TITLE
UrGENT: CAn you do this ASAP?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1350]
Can you add a section for us to put who made the CC payment on the external link?

We have to apply payments to around 300 people individually and don't want to have to go back to each payment just to update the name

**Comment by bradatkins** [comment]
by who made the payment do you mean which 206 Tour Staff member or the name on the CC?

**Comment by bradatkins** [comment]
And what link are you using?

**Comment by ali206** [comment]
name on the CC - like all payments were made by Dynamic Catholic

https://www.206tours.com/register/admin/editorder_old.php?OrderID=406210

**Comment by bradatkins** [comment]
Ok try now (i didn't test it)

**Comment by ali206** [comment]
works, thank you!
