### ISSUE TITLE
DB Air Itinerary Glitch - not finding ETKT (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1352]
![image](https://cloud.githubusercontent.com/assets/10079829/17220023/ae8f3f6c-54bb-11e6-8141-9eed32bffa96.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17220031/bac286b8-54bb-11e6-887a-704d09e09ec3.png)

**Comment by bradatkins** [comment]
Sometimes it takes a little time to get and process the PNR. I see the ETKT:

![image](https://cloud.githubusercontent.com/assets/8440255/17220192/3b49d02a-54bc-11e6-8c15-f3dd57eff5a6.png)
