### ISSUE TITLE
Flight schedules through DB still not working | order # 421898 (Stef)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1355]
![image](https://cloud.githubusercontent.com/assets/10079829/17250022/7f3cf0aa-5570-11e6-82c2-526c8673c751.png)

**Comment by bradatkins** [comment]
Fixed; however, please note I only see an itinerary  for Gabrielle in the PNR, not for the other two PAX

PNR #: ZJARRQ
