### ISSUE TITLE
Fedex - can you double check measurements?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1356]
I know you said you changed the measurements on 7/13 to be 16x14x6, could they have reverted back to old measurements since then?

I just checked a shipment from 7/20 and it's still showing measurements of 108x5x5??

![image](https://cloud.githubusercontent.com/assets/8440903/17301012/f154c23e-57e2-11e6-98fc-214dafc768b0.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/17423846/41c3e6cc-5a8c-11e6-9f60-be1fa9f3c884.png)

Those are in INCHES

**Comment by ali206** [comment]
Weird ok, I told our Fed Ex rep so I guess it's on their side that it's wrong now.
