### ISSUE TITLE
Shipping label warning | Order #421935 (elise)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1357]
![image](https://cloud.githubusercontent.com/assets/10079829/17304539/1925ba0a-57f4-11e6-9550-20552308f9c1.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17304531/1000d9fa-57f4-11e6-9147-d8021c76e174.png)

**Comment by bradatkins** [comment]
Seems to be resolved
