### ISSUE TITLE
missing social media icons

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#136]
Hi Brad,

Our social media icons are suddenly missing (I noticed it the last couple of days)
www.206tours.com/tour111
 
 
![image](https://cloud.githubusercontent.com/assets/10079829/5589230/297133c8-90e8-11e4-824a-72576ebd5f07.png)

**Comment by bradatkins** [comment]
Seem to be back now

![image](https://cloud.githubusercontent.com/assets/8440255/5692759/bee5fb60-98d0-11e4-8b30-b4f3f7014231.png)
