### ISSUE TITLE
Flight Itinerary (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1361]
![image](https://cloud.githubusercontent.com/assets/10079829/17335900/d2fdeb5e-58a9-11e6-9d10-5ada90909240.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/17457555/3de5bae2-5bc9-11e6-86a8-5bf9568fc82a.png)
