### ISSUE TITLE
GLITCH: DB Flight itineraries merge problems - in need of troubleshoot and permanent fix (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1362]
![image](https://cloud.githubusercontent.com/assets/10079829/17338329/09fa8828-58b5-11e6-9c7a-8f2e982b1b35.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17338320/02cb0f96-58b5-11e6-9f55-49ca6742cb19.png)

**Comment by bradatkins** [comment]
Error 1:

Do not put a /P1 etc after the order number in the RM. Just list the Order ID's in the order the PAX are listed.

The instructions never said to put a /P1 etc after, so not sure why this is being done :)


Error 2:

I'm showing Fr David on PNR #7OINBD not HS7JM (I do not even see PNR #HS7JYM)
I'm showing Matthew on PNR #Y6DX4U not MQYICL (I do not even see PNR #MQYICL)
I do not have PNR GURCFC.

Can you try re-triggering the above PNRs?

**Comment by chris206** [comment]
so - we are including passenger number now, right?
It is important and more secure option than doing them in order.

Additionally, passenger association is required for all special requests anyway.
