### ISSUE TITLE
Top Navigation & Search Bar shifted

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1366]
Hi Brad,

Can you please look over this code, it shifted the header after I setup the links.

Feel free to go into the HTML file:
www.206tours.com/assets/html/home.html

            <nav class="top-navigation">
              <ul data-drilldown class="top-menu">
                <li><a href="../../pilgrimages/index.htm">Pilgrimages</a>
                  <ul class="sub-menu">
                    <li><a href="../../pilgrimages/index.htm">All Pilgrimages</a></li>
                    <li><a href="http://www.206tours.com/tour212">Canada</a></li>
                    <li class="has-sub"><a href="#">Combined Countries</a>
                      <ul class="last">
                        <li><a href="#">&nbsp;Fatima, Spain &amp; Lourdes</a><br><a href="#">&nbsp;Prague, Salzburg, Vienna &amp; Budapest</a></li>
                      </ul>
                    </li>
                    <li><a href="../../search/france">France</a></li>
                    <li><a href="../../search/greece">Greece</a></li>
                    <li><a href="../../search/israel">Holy Land</a></li>
                    <li><a href="../../search/ireland">Ireland</a></li>
                  </ul>
                </li>
                <li><a href="../../specials/index.htm">Custom Tours</a>
                  <ul class="sub-menu">
                    <li><a href="../../specials/index.htm">Specials</a></li>
                    <li><a href="mailto:groups@206tours.com">Build a Tour</a></li>
                    <li><a href="../../independent">Independent Travel</a></li>
                  </ul>
                </li>
                <li><a href="../../sitemap/index.htm">Information</a>
                  <ul class="sub-menu">
                    <li><a href="../../terms">Terms & Conditions</a></li>
                    <li><a href="../../insurance">Insurance</a></li>
                    <li><a href="../../cancellationprotection">Cancel Protection Plan</a></li>
                    <li><a href="../../info">Know Before You Go</a></li>
                    <li><a href="../../letters">Client Letters</a></li>
                    <li><a href="../../international-travellers">International Pilgrims</a></li>
                    <li><a href="../../airports">Airport Directory</a></li>
                    <li><a href="../../spanish">iSe Habla Espanol</a></li>
                    <li><a href="../../sitemap">Site Map</a></li>
                  </ul>
                </li>
                <li><a href="../../aboutus/index.htm">About us</a>
                  <ul class="sub-menu">
                    <li><a href="../../aboutus/index.htm">Employees</a></li>
                   </ul>
                <li><a href="../../contact/index.htm">Contact Us</a>
                  <ul class="sub-menu">
                    <li><a href="mailto:sales@206tours.com">sales@206tours.com</a></li>
                    <li>1-800-206-8687</li>
                    <li><a href="../../skype">Skype</a></li>
                    <li><a href="#">Live Chat</a></li>
                    <li><a href="mailto:yaritza@206tours.com">iSe Habla Espanol</a></li>
                  </ul>
                </li>
                <li><a href="../../groups/index.htm">Lead a group</a>
                  <ul class="sub-menu">
                    <li><a href="../../groups/index.htm">Organize a Group</a></li>
                    <li><a href="../../promote/index.htm">Promote a Group</a></li>
                    <li><a href="mailto:groups@206tours.com">email us</a></li>
                  </ul>
                </li>
              </ul>
            </nav>

![image](https://cloud.githubusercontent.com/assets/10079829/17374407/6c429da2-597a-11e6-8868-6b799ee7ede5.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17374413/75eabbd2-597a-11e6-843e-3713b7910318.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17374419/7d9642f2-597a-11e6-8c23-278189295197.png)

**Comment by bradatkins** [comment]
This happens because a bunch of the menu examples have sub sub menus which impact the layout.

I suggest you go back to Big Drop and tell them to modify the navigation so it does not have any sub-sub menus.

**Comment by ronenreinheimer** [comment]
OK, I will work it out with them.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
