### ISSUE TITLE
Your Trip Includes Section - Tour Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1367]
Hi Brad,

Can you please remove the bullet point from the following items (they should be indented) and underline the flight bag - so it will appear as a link.

http://www.206tours.com/assets/html/tour-details.html

Thank you!

![image](https://cloud.githubusercontent.com/assets/10079829/17374629/86ee54e2-597b-11e6-9583-f47038296488.png)

            <div class="user-content">
              <div class="column-list">
                <ul>
                  <li>Round-trip airfare</li>
                  <li>&nbsp;&nbsp;&nbsp;*Fares available from other US or Canada Airports</li>
                  <li>&nbsp;&nbsp;&nbsp;*You may book without airfare (land only option)</li>
                  <li>All airport taxes &amp; fuel surcharges</li>
                  <li>Centrally located hotels: (or similar)</li>
                  <li>&nbsp;&nbsp;&nbsp;~ 3 nights:  Hotel Michelangelo or Visconti Palace, Rome ****</li>
                  <li>&nbsp;&nbsp;&nbsp;~ 2 nights:  Hotel Gran Paradiso, San Giovanni Rotondo ***</li>
                  <li>&nbsp;&nbsp;&nbsp;~ 3 nights:  Hotel Giotto, Assisi ****</li>
                  <li>Breakfast and Dinner daily</li>
                  <li>Wine with dinners</li>
                  <li>Assistance of a professional local Catholic guide(s)</li>
                  <li>Transfers as per itinerary</li>
                  <li>Sightseeing and admissions fees as per itinerary</li>
                  <li>Catholic Priest available for Spiritual Direction</li>
                  <li>Mass daily &amp; Spiritual activities</li>
                  <li>Luggage handling (1 piece per person)</li>
                  <li><a class='underline' href="http://www.206tours.com/documents/index.htm">Flight bag &amp; portfolio of all travel documents</a></li>
                </ul>
              </div>
            </div>

**Comment by bradatkins** [comment]
You were missing the OL tags. I added them to the tour-details.html file to show you. You can apply it to the rest

![image](https://cloud.githubusercontent.com/assets/8440255/17387050/1298d96c-59be-11e6-9144-9e1640d0952a.png)

**Comment by ronenreinheimer** [comment]
It is not the OL tag, I tried that – I am not looking for an ordered list. I need it blank.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
seems to work as per the screenshot though?

**Comment by ronenreinheimer** [comment]
OK, let me look it over.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
I think that did it, just need to match the same font.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Thank you. Can you please figure out how to implement the same font as the rest of this section?

[cid:image001.jpg@01D1EE4A.58358C70]

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/17409657/26ffe7a8-5a3e-11e6-9371-268f53761c5e.png)
