### ISSUE TITLE
Tour 167 issue in the DB

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#137]
Hi Brad,

i am trying to build tour 167 in the DB, but it says that the tour exists already. looks like the same issue we had with tour 35. can you please fix this issue.

thank you.

![image](https://cloud.githubusercontent.com/assets/10079829/5589614/a0537246-90f0-11e4-82d1-cf5726641df7.png)

**Comment by bradatkins** [comment]
Fixed
