### ISSUE TITLE
Please try to fix ASAP:  100158 Aug 28 dept

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1371]
Elise needs to get these packages out today and Sandy wants them sent through the DB like the rest of the group:

trying to generate fedex labels for pax and error message keeps popping up:

![image](https://cloud.githubusercontent.com/assets/8440903/17403492/05b427e8-5a26-11e6-83b5-56b97eb05397.png)

**Comment by bradatkins** [comment]
Try now

**Comment by ali206** [comment]
Elise said only 1 worked...these are still not working and it seems the 3 digit state code is showing up before the zip code instead of the actual state:

#422239 - Armando John Flocchini 
#421939 - Joan Graham
#422172 - Audrey Owens Mchugh
#4421936 - Vitore Vulaj Merhige 
#422211 - Beth Demarco

**Comment by bradatkins** [comment]
No state or country in the documents section of the order.

**Comment by ali206** [comment]
is this what you're talking about?
![image](https://cloud.githubusercontent.com/assets/8440903/17438798/a1fbfd16-5af2-11e6-9c26-156dba645bb9.png)

**Comment by bradatkins** [comment]
Yes. This needs to be filled out when an order is assigned to an agent

**Comment by ali206** [comment]
This is what Elise said:
Thank you, but I sent multiple packages out without filling out that section and the database was able to create a label. I also filled the section out for a few packages I have here and it’s still not working.

**Comment by bradatkins** [comment]
I need some examples of both.


You only have to fill that section out if it's an order attached to nn agent...

**Comment by ali206** [comment]
422239 & 421939- just tried to create a new label and it just brings me to a blank page:

![image](https://cloud.githubusercontent.com/assets/8440903/17462232/97aa1946-5c74-11e6-863f-cf7f4125b082.png)

**Comment by bradatkins** [comment]
Ya no state on the first one or second one

[image: Inline image 1]

[image: Inline image 2]

**Comment by ali206** [comment]
But she's saying she doesn't fill that section out and is able to create labels....how does that work then?

Also i just added the state for both pax on 422239 and got this:
![image](https://cloud.githubusercontent.com/assets/8440903/17462305/c86c6f96-5c76-11e6-9613-fea972f84253.png)

**Comment by bradatkins** [comment]
I think she may have provided some incorrect information. Remember, only if
the order is attached to an attach is this section used.

Ya, I added this error message instead of the blank screen

**Comment by ali206** [comment]
Ok but if I added the state then why the error message now?

![image](https://cloud.githubusercontent.com/assets/8440903/17462329/6b1a1072-5c77-11e6-9506-5a2244f49022.png)

**Comment by bradatkins** [comment]
Sorry, error message is misleading. You need the whole address in there.
I'll adjust.
