### ISSUE TITLE
No CC info section | DB online reservation | Tour PK093016 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1372]
![image](https://cloud.githubusercontent.com/assets/10079829/17411181/3498821a-5a45-11e6-82b6-e66becc3eb2a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17411204/5d790da8-5a45-11e6-91c2-3627f4112ed2.png)

**Comment by bradatkins** [comment]
It seemed to work for me OK. She needs to try again and give me the session ID if it doesn't work

**Comment by ronenreinheimer** [comment]
TY
