### ISSUE TITLE
424666 - dept and base price issues

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1373]
![image](https://cloud.githubusercontent.com/assets/8440903/17411213/6b356fb8-5a45-11e6-93c9-a2deeee2434d.png)
![image](https://cloud.githubusercontent.com/assets/8440903/17411221/7337d0a2-5a45-11e6-8eb4-403c301fe136.png)

**Comment by bradatkins** [comment]
Fixed. The View order screen wasn't picking up tour specific departure city costs
