### ISSUE TITLE
Please fix ASAP: client inquiring about this 2nd time now

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1374]
Base price does not match what is showing on website in CAD:

![image](https://cloud.githubusercontent.com/assets/8440903/17412437/c222354a-5a4a-11e6-954c-2af72d173adf.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17412447/cb39830e-5a4a-11e6-8a57-6cfbe55a89ce.png)

**Comment by bradatkins** [comment]
I'm confused, this is currency fluctuation...it's not a hard value.

**Comment by ali206** [comment]
Ok then the website should not be a hard value either right?

**Comment by bradatkins** [comment]
No, it's not...it fluctuates as well

**Comment by ali206** [comment]
Irena added an issue in github for this client...she applied the payment in USD but we need you to add the exch rate so the CAD payment will show on the CAD invoice for April payment - $819.43 CAD was charged

**Comment by bradatkins** [comment]
Check now

**Comment by ali206** [comment]
Ok but that's what i'm confused about....if the website fluctuates to the exch rate at that moment then it shouldn't just keep saying $5452 all the time, 

That's the price that showed yesterday as well when Irena booked her, but showed on her invoice as $5494 instead?

**Comment by bradatkins** [comment]
It may not fluctuate all the time, but it grabs the rate at a point in
time...

**Comment by ali206** [comment]
Hmmm ok, seems odd.  What is an example of "a point in time"? Like every 3 days it updates, once a day at noon?

**Comment by bradatkins** [comment]
Like the rate at the moment; how often the source updates the rate I don't
know...

**Comment by ali206** [comment]
Ok but it's still not making sense. 

If the rate updated let's say once a day, our website would not show $5452 every time I go look at it.

**Comment by bradatkins** [comment]
It would if the rate didn't substantially change.

**Comment by ali206** [comment]
Ok i'll keep checking everyday, will let you know if it stays the same or not
