### ISSUE TITLE
smooth scroll code for Book Now Button

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1376]
http://www.206tours.com/assets/html/tour-details.html?TOUR_NUMBER=96#dates

Hi Brad,

can you add it to this button:
![image](https://cloud.githubusercontent.com/assets/10079829/17442469/ef80f1ac-5b03-11e6-95f0-56fa31af4621.png)

same as it works here:
![image](https://cloud.githubusercontent.com/assets/10079829/17442502/14f14996-5b04-11e6-82e4-deb7fc92f541.png)

**Comment by bradatkins** [comment]
Hey -

Just add this div tag around the a href tag:

<div class="bookNowButton">

like so:

![image](https://cloud.githubusercontent.com/assets/8440255/17445603/b76a6536-5b13-11e6-8695-69778bc8ee36.png)

You can see it in action here:

http://www.206tours.com/register/assets/html/tour-details.html?TOUR_NUMBER=96

**Comment by ronenreinheimer** [comment]
n1

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
thank you so much. i was trying to apply this method to these 2 links (they need to go to the same section), but it did not work. can you please take a look:

![image](https://cloud.githubusercontent.com/assets/10079829/17447328/dc1bd9a2-5b1b-11e6-86b0-0b1a9d7cd917.png)

**Comment by bradatkins** [comment]
Done, I added this:

<div class="bookNowButton" style="display:inline">
