### ISSUE TITLE
FW: 206 Tours Inc. Confirmation - Order #424756  Tour #158 November 3, 2016 (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1377]
![image](https://cloud.githubusercontent.com/assets/10079829/17446961/e3346800-5b19-11e6-862c-47c08a994450.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17446963/e7884106-5b19-11e6-96e7-02a38e4f74ac.png)

**Comment by bradatkins** [comment]
Seems to be OK now?

![image](https://cloud.githubusercontent.com/assets/8440255/17457490/b4485066-5bc7-11e6-8c7c-1014c076fd13.png)
