### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1378]
Hi Brad,

Can you please make these icons work the same way as you did on the previous site:

http://www.206tours.com/tour96/index.htm

![image](https://cloud.githubusercontent.com/assets/10079829/17448413/1771bdea-5b22-11e6-8408-1715869e5d3a.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17448426/20dd18f2-5b22-11e6-9aa1-7c6758f01afb.png)

**Comment by bradatkins** [comment]
Done
