### ISSUE TITLE
424402 - same name showing twice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1385]
Sophia williams is showing twice but one should be Vanessa Jo Ann Edwards DOB 4/4/89

![image](https://cloud.githubusercontent.com/assets/8440903/17521688/353c8a46-5e22-11e6-8766-4659f9f68b7f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17521690/381eccba-5e22-11e6-8a89-9474394163c9.png)

**Comment by bradatkins** [comment]
Fixed
