### ISSUE TITLE
DV Glitch: Yellow Sheet Incorrectly lists Post-Option (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1389]
![image](https://cloud.githubusercontent.com/assets/10079829/17532278/df24c89a-5e4d-11e6-9264-14fe51809981.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17532282/e28d2f0e-5e4d-11e6-967e-c765351bf7ca.png)

**Comment by bradatkins** [comment]
Fixed
