### ISSUE TITLE
Extended Cancellation Protection - DB Issue - URGENT

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#139]
Hi Brad,

We can't offer extended cancellation protection for any World Youth Day tour - but it is still showing up in the registration page. Can you please look into this issue. Thank you!

![image](https://cloud.githubusercontent.com/assets/10079829/5597541/14222546-9272-11e4-9bd2-d85d37ec8de0.png)

![image](https://cloud.githubusercontent.com/assets/10079829/5597542/1eabb2ac-9272-11e4-9e29-60306c82e13f.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/5692754/9dd59af2-98d0-11e4-8f93-3bbf34905f39.png)

**Comment by ronenreinheimer** [comment]
Awesome thank you!
