### ISSUE TITLE
Dates on webpage showing incorrectly | Tour #96 Shrines of Italy  (Stef)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1398]
![image](https://cloud.githubusercontent.com/assets/10079829/17631496/4f51744c-6092-11e6-9f8b-1e9bd1d73bad.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17631493/4aa5e694-6092-11e6-8365-b1c6063689ef.png)

**Comment by bradatkins** [comment]
This is fixed
