### ISSUE TITLE
Tour # 114A   Single supplement listed correct in DB but higher on website ! 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#140]
RE: tour # 114A --- please correct:" Single supplement $1198 ( not $1599 = too high) ) 

Its already $1,198.00 but still showing the wrong amount on website

**Comment by bradatkins** [comment]
It's showing as 1198 for me? Maybe I'm looking at the wrong one?

![image](https://cloud.githubusercontent.com/assets/8440255/5692737/0ff42d5c-98d0-11e4-98d1-8c90bf0d6970.png)

**Comment by ali206** [comment]
She said it's correct in the DB but is showing incorrectly on the website - i just asked Ronen if he could update it
