### ISSUE TITLE
OCC automatic invite not working on new site

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1403]
Can you check the code, The OCC Auto Invite is not working on the new site:

![image](https://cloud.githubusercontent.com/assets/10079829/17678020/6e0f3ce8-6303-11e6-8941-c8b0bca8cd1d.png)

**Comment by bradatkins** [comment]
Add this code just after the body tag:

`<script type="text/javascript">
(function() {
var occ = document.createElement('script'); occ.type = 'text/javascript'; occ.async = true;
occ.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'www.onlinechatcenters.com/code-29129-66811.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(occ, s);
})();
</script>  `

**Comment by ronenreinheimer** [comment]
TY!
