### ISSUE TITLE
RE: Please create website | www.pilgrimages.com/frbadeaux (Kat)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1404]
www.pilgrimages.com/frbadeaux

DB CODE:  **KB042017**

![image](https://cloud.githubusercontent.com/assets/10079829/17678753/795a59ae-6306-11e6-9db2-627bb983fda0.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/17682484/e24bd5f6-6319-11e6-8654-48cf927980c3.png)

**Comment by ronenreinheimer** [comment]
It was a glitch?



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Bug ya
