### ISSUE TITLE
DB Quick Fix - Air Itineraries (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1405]
![image](https://cloud.githubusercontent.com/assets/10079829/17678912/27787624-6307-11e6-960f-0326481233ed.png)

**Comment by bradatkins** [comment]
It is not currently case sensitive. 

Please provide an example.

**Comment by ronenreinheimer** [comment]
From chris

Tell him I don’t know. I was trying to figure out why the connections weren’t being made and that was one idea


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Better to provide me of examples of connections not being made, so I can
investigate them.
