### ISSUE TITLE
DB | Incorrect payment amount | PA102616 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1407]
![image](https://cloud.githubusercontent.com/assets/10079829/17701743/fbfe3370-6398-11e6-95e2-10ed7adf7f49.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17701762/16d43636-6399-11e6-96d5-8f5a531b0dd7.png)

**Comment by bradatkins** [comment]
Duplicate of the one I just commented on, closing
