### ISSUE TITLE
Country Tabs

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1410]
Hi Brad, i need to get this up for Sandy. 
http://www.206tours.com/index6.htm  (test page)

I added the tour to the correct section, but it should not be showing on the home page. can you please tell me what i am doing wrong?

# **This is good:**
![image](https://cloud.githubusercontent.com/assets/10079829/17715280/6d2df6d8-63d1-11e6-970d-c33b63ff7c7c.png)

## # **This is not good: Classic Italy Tour 98 should not show up on the home page view all tab**
![image](https://cloud.githubusercontent.com/assets/10079829/17715302/7cce6852-63d1-11e6-8f12-f7c38d43177f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17715306/817fd4f8-63d1-11e6-89a2-53771445cf36.png)

**Comment by bradatkins** [comment]
I'm confused why wouldn't Tour 98 show up on the "View All"...isn't the purpose of "viewing all" to see them all?

**Comment by ronenreinheimer** [comment]
We only want our top 9 tours to show up on the view all tabs (that is the default view when you go to the home page)

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
They said these links should help us:
http://prnt.sc/byli4y
http://prnt.sc/bylhfd



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
This is the code:
www.206tours.com/index6.htm<http://www.206tours.com/index6.htm>


<section class="b-popular">
          <div class="section-title">
            <h4>popular pilgrimages</h4>
          </div>
          <div class="row">
            <div class="small-12 columns b-arrow">
              <div class="horizontal-scroll">
                <ul class="tab-list">
                  <li><a href="javascript:void(0)" data-anchor="italy">ITALY</a></li>
                  <li><a href="javascript:void(0)" data-anchor="holyland">HOLY LAND</a></li>
                  <li><a href="javascript:void(0)" data-anchor="france">france</a></li>
                  <li><a href="javascript:void(0)" data-anchor="spain">Spain</a></li>
                  <li><a href="javascript:void(0)" data-anchor="poland">poland</a></li>
                  <li><a href="javascript:void(0)" data-anchor="medjugorje">MEDJUGORJE</a></li>
                  <li><a href="javascript:void(0)" data-anchor="combined">COMBINED</a></li>
                  <li class="active"><a href="javascript:void(0)" data-anchor="all">
                  view all</a></li>
                </ul>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="italy" class="popular_item">
                <div class="b-img">
                                                                                <a href="<? echo $TOUR_INFO['96']['TourWebsite']; ?>" style="background-image: url('assets/images/img1.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="<? echo $TOUR_INFO['96']['TourWebsite']; ?>">
                    <h5><? echo $TOUR_INFO['96']['TourName']; ?></h5></a>
                  <p>Pope Francis</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td><? echo $TOUR_INFO['96']['TourNumber']; ?></td>
                      <td><? echo $TOUR_INFO['96']['TourNumDays']; ?> days</td>
                      <td>Italy</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="holyland" class="popular_item">
                <div class="b-img">
                                                                                <a href="<? echo $TOUR_INFO['111']['TourWebsite']; ?>" style="background-image: url('assets/images/p2.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="<? echo $TOUR_INFO['111']['TourWebsite']; ?>">
                    <h5><? echo $TOUR_INFO['111']['TourName']; ?></h5></a>
                  <p>Walk Where Jesus Walked</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td><? echo $TOUR_INFO['111']['TourNumber']; ?></td>
                      <td><? echo $TOUR_INFO['111']['TourNumDays']; ?> days</td>
                      <td>Israel</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="spain" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour37/index.htm" style="background-image: url('assets/images/p3.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour37/index.htm">
                    <h5>Fatima, Spain &amp; Lourdes</h5></a>
                  <p>The Marian Shrines</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>37</td>
                      <td>10 days</td>
                      <td>Portugal, Spain, France</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="france" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour8/index.htm" style="background-image: url('assets/images/p4.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour8/index.htm">
                    <h5>Lourdes, Nevers, Lisieux &amp; Paris</h5></a>
                    <p>Our Lady &amp; the Saints of France</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>8</td>
                      <td>9 days</td>
                      <td>France</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="mexico" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour206/index.htm" style="background-image: url('assets/images/p5.png')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour206/index.htm">
                    <h5>Guadalupe &amp; Mexico City</h5></a>
                    <p>Our Lady of Guadalupe</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>206</td>
                      <td>6 days</td>
                      <td>Mexico</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="poland" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour168/index.htm" style="background-image: url('assets/images/p6.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour168/index.htm">
                    <h5>Poland</h5></a>
                    <p>In the Footsteps of St. John Paul II &amp; St. Faustina
                    (Divine Mercy)</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>168</td>
                      <td>9 days</td>
                      <td>Poland</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="spain" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour70/index.htm" style="background-image: url('assets/images/p7.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour70/index.htm">
                    <h5>El Camino - The Way of St. James</h5>
                    </a>
                  <p>A Walking Pilgrimage</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>70</td>
                      <td>11 days</td>
                      <td>Spain</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="italy" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour103/index.htm" style="background-image: url('assets/images/p8.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour103/index.htm">
                    <h5>All Italian Shrines</h5></a>
                 <p>Florence, Padua &amp; Venice!</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>103</td>
                      <td>14 days</td>
                      <td>Italy</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
                                                <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="italy" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour98/index.htm" style="background-image: url('assets/images/home-page-thumbs/tour98-classic-italy-pilgrimage1.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour98/index.htm">
                    <h5>Classic Italy</h5></a>
                  <p>Sorrento, Pompeii & Amalfi Coast</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>98</td>
                      <td>14 days</td>
                      <td>Italy</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="small-12 medium-6 large-4 columns bottommargin">
              <div data-locate="combined" class="popular_item">
                <div class="b-img">
                                                                                <a href="../../tour202/index.htm" style="background-image: url('assets/images/p9.jpg')" class="popular_img"></a></div>
                <div class="popular_descr"><a href="../../tour202/index.htm">
                    <h5>Ireland</h5></a>
                    <p>In the Footsteps of St. Patrick</p>
                  <table>
                    <tr>
                      <th>Tour</th>
                      <th>Duration</th>
                      <th>Destination</th>
                    </tr>
                    <tr>
                      <td>202</td>
                      <td>10 days</td>
                      <td>Ireland</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="b-custom">
          <div class="section-title">




God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
This is not possible the way they have it coded unfortunately. The View All
will show all tours that are under each tab, which to me makes sense, and
that's how they coded it.

**Comment by bradatkins** [comment]
This is not possible the way they have it coded unfortunately. The View All
will show all tours that are under each tab, which to me makes sense, and
that's how they coded it.
