### ISSUE TITLE
MR082916 - Recap opens to blank page when i try to generate excel doc

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1411]
![image](https://cloud.githubusercontent.com/assets/8440903/17715607/f03f253c-63d2-11e6-9871-dddc9060ea48.png)

**Comment by bradatkins** [comment]
I just tried again and it worked OK (I didn't change anything) can you try? I was working in that file previously so maybe you caught me in the middle

**Comment by ali206** [comment]
ok working now

**Comment by ali206** [comment]
Sorry it's still a blank page actually when i click on generate excel doc:

![image](https://cloud.githubusercontent.com/assets/8440903/17775770/cddad8f0-6527-11e6-9452-614dab9a5aea.png)

**Comment by bradatkins** [comment]
Ahh fixed. You were trying the ADMIN recap

**Comment by bradatkins** [comment]
Seems to be OK now
