### ISSUE TITLE
FW: New Group Request (Linda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1412]
![image](https://cloud.githubusercontent.com/assets/10079829/17715742/8ae6ebce-63d3-11e6-885c-812a47c9bd29.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17715735/831490e0-63d3-11e6-938d-b1014184a7a7.png)

**Comment by bradatkins** [comment]
It had failed because he provided so much text in his Inclusions. I've increased that column in the database. I also checked the logs to make sure no others were missing
