### ISSUE TITLE
DB PNR Mismatch - RM number in limbo on blank old record (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1413]
![image](https://cloud.githubusercontent.com/assets/10079829/17738314/bad1bc2a-645e-11e6-9713-ccbfd5ff0cd2.png)

**Comment by bradatkins** [comment]
Cancellations must be completed without removing the Order ID from the PNR. I've fixed up this order, but going forward, do not remove the Order ID
