### ISSUE TITLE
Email Replys to included agent in charge of group (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1415]
![image](https://cloud.githubusercontent.com/assets/10079829/17740266/fe4a0b72-6465-11e6-96fb-e020bb7e0f02.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17740257/f797dafc-6465-11e6-9cb0-425b5aeed953.png)

**Comment by bradatkins** [comment]
It does. The DB sends it from 206Tours@206Tours.com and CC's the Tour Manager; however, if the customer click Reply-To instead of Reply-All the Tour Manager won't get it
