### ISSUE TITLE
DB Error - DB is finding record, but failing to compile it into a readable summary (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1416]
![image](https://cloud.githubusercontent.com/assets/10079829/17748541/e76cc76a-6487-11e6-9bed-f11789626df5.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17748544/ead374e4-6487-11e6-80cb-37054cc6d67e.png)

**Comment by bradatkins** [comment]
As mentioned before, do not add /P1 /P2 after the order

**Comment by ronenreinheimer** [comment]
from chris:

Woah woah. The Amadeus code is designed to have a p2 added. Is he saying that the association to passenger number is irrelevant as long as:

1. the order is somewhere on the record, even if other order numbers are present on the same record?
We will need to revise the code then - this is a more significant issue.

![image](https://cloud.githubusercontent.com/assets/10079829/17775972/bd37ba12-6528-11e6-821b-94526e2d0bbe.png)

**Comment by ronenreinheimer** [comment]
from Sandy:

Awesome! It worked. We really need to stop associating passenger to RM – it is more work and creating problems.

Will alert the office that our current procedure is wrong.

**Please ask brad to definitely change the Amadeus TSA code line regarding the RM**

**Comment by bradatkins** [comment]
Maybe we are confusing things here.

In the Remarks section, I notice it had RM 423403/P2 (line 17 in his screenshot)

The /P2 portion is not required there.

The RM's for Order ID's should be inserted in the order of the passengers.

**Comment by ronenreinheimer** [comment]
from Chris

![image](https://cloud.githubusercontent.com/assets/10079829/17780633/1b5ab728-653a-11e6-86a1-13b413bd6d43.png)

**Comment by bradatkins** [comment]
For #2, if there's are multiple passengers on one PNR on different order #'s the order numbers should be in the same order as the passengers on the PNR.

For Nancy's issue, I'll look into it.

**Comment by bradatkins** [comment]
This wouldn't impact the AMadeus TSA code line

**Comment by ronenreinheimer** [comment]
That's complicated. Couldn't we just keep it like it on our end (associating the passenger number to order RM) and change the db to recognize the passenger number in Amadeus?

**Comment by bradatkins** [comment]
It's not complicated and has been working for others

**Comment by ronenreinheimer** [comment]
Sandy asked if you could please call Chris when you have time.
631-257-1240

**Comment by bradatkins** [comment]
Oddly enough, seems to be OK, but I didn't change anything, but it does look like there was an update to the PNR today at 11:42..

**Comment by chris206** [comment]
We still seem to need to add the RM number in the order that clients are on the record. It is getting better though, clearly.
