### ISSUE TITLE
Custom Addon Departure Cities Doubled

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1417]
5562cf2574436c2cafa12c88f7d9300b

https://www.206tours.com/register/admin/listdata.php?FORM=TourDepartureCities&Search_TourID=3562&TourID=3562

![image](https://cloud.githubusercontent.com/assets/10079829/17748835/3c601d34-6489-11e6-8cc6-3b8889c5bbb4.png)

**Comment by bradatkins** [comment]
Fixed. I expect there will be a few more of these gremlins as we work out this departure city stuff

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
