### ISSUE TITLE
Single Supplement was added to clients on same day flights sent through DB | Booking # 424622 & 424807 (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1418]
Brad, can you please investigate:

![image](https://cloud.githubusercontent.com/assets/10079829/17752174/a89bff9a-6498-11e6-9943-ec09482f3873.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17752186/b2826440-6498-11e6-9eed-c5a2a568329d.png)

**Comment by bradatkins** [comment]
Not sure what's up here, I've fixed the order.

The Amadeus thing is unrelated.
