### ISSUE TITLE
Linking agent to a booking already created

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#142]
Hi Brad, 

If a client registers on their own, but is going with one of our travel agent's groups how do we link the agent to that booking?

I thought if we edited the order and selected the agent that would work, but Stef tried this yesterday with Booking #417407 and it doesn't seem like Helen Zec is linked to the order:

![image](https://cloud.githubusercontent.com/assets/8440903/5681909/75f97832-97ea-11e4-8477-a95e04360b01.png)

![image](https://cloud.githubusercontent.com/assets/8440903/5682218/573c91ca-97ec-11e4-8115-c5eb9e898307.png)

![image](https://cloud.githubusercontent.com/assets/8440903/5682226/6216054a-97ec-11e4-99ed-6ddde69623af.png)

**Comment by bradatkins** [comment]
It's because this part shows the Agent company name.

In this case, the Company is blank. I've made it a required field now.

![image](https://cloud.githubusercontent.com/assets/8440255/5692728/71d938a6-98cf-11e4-8848-8dad98e0f6b3.png)
