### ISSUE TITLE
Paypal payment - no email received

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1420]
This payment was made on the 16th and we never got a notification of payment:

Only 1 we were notified about was from 8/10

and order audit report says nothing about the payment being approved so not sure how that happened:

![image](https://cloud.githubusercontent.com/assets/8440903/17781340/eca3d646-653c-11e6-94d3-ddda10c7b2ee.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17781282/b7ce8966-653c-11e6-9f6b-40880cfd14a2.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17781301/c6c2d8aa-653c-11e6-9c96-245d3bf58322.png)

**Comment by bradatkins** [comment]
Fixed
