### ISSUE TITLE
banner images clickable  (SANDY)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1422]
Hi Brad,

how do i link these images to a tour?

![image](https://cloud.githubusercontent.com/assets/10079829/17788150/3ef125c6-655a-11e6-90b4-2fc325ece855.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17788183/6a618ef8-655a-11e6-9c06-a02b3d69be4d.png)

**Comment by bradatkins** [comment]
Not really sure what you mean?

**Comment by ronenreinheimer** [comment]
i want to link the slide image to a tour. like the italy image to <a href="http://www.206tours.com/tour96/index.htm">

**Comment by bradatkins** [comment]
Oh so just adding a link so they can click on the picture to bring them to the Tour?

**Comment by ronenreinheimer** [comment]
Yes!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Just try putting your hyperlink around the yellow highlighted section:

![image](https://cloud.githubusercontent.com/assets/8440255/17813763/9c3ec42c-65fa-11e6-8d8b-2af03f1cc7cd.png)

**Comment by ronenreinheimer** [comment]
You da man!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
