### ISSUE TITLE
Search Results Order (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1425]
Hi Brad,

We noticed that when we type in "Fatima Anniversary 2017" which is DB Code: **FAT2017A** it appears at the bottom of the search results. So it appears that the DB code determines which result comes up first. Can you change this algorithm?

![image](https://cloud.githubusercontent.com/assets/10079829/17814656/d199c35c-65fe-11e6-990e-29c82484f2b9.png)

![image](https://cloud.githubusercontent.com/assets/10079829/17814644/c76fa40a-65fe-11e6-875a-33c9cb3defbe.png)

**Comment by bradatkins** [comment]
It was supposed to be ordering it based on the algorithmic score, but wasn't for some reason.

It is now:

![image](https://cloud.githubusercontent.com/assets/8440255/17816955/da492654-6609-11e6-85cb-d61c53a8aa48.png)

**Comment by ronenreinheimer** [comment]
Thank you Brad!

Could you tell us what determines this order?

FAT2017A is the main tour for this series.



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I think we discussed this over email, so closing for now
