### ISSUE TITLE
DB Glitch: Air Itineraries not compiling & Suffix still not being included in TSA info (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1426]
![image](https://cloud.githubusercontent.com/assets/10079829/17859263/dc1f6462-6856-11e6-8f51-4d2377478d61.png)

**Comment by bradatkins** [comment]
They should all be good except:

422291 - Patrick. Seems as though there's another PAX on this PNR but no order # for them (ARMATO / ALBERT LAWRENCE)

but check them to make sure

**Comment by chris206** [comment]
this seems to be resolved. Al's ticket meshes with the DB
