### ISSUE TITLE
Tour 111 Gallery Images / KBYG Section Moved

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1427]
Hi Brad,

I compared the code with another tour and it appears to be identical. Perhaps its the UI section?
http://www.206tours.com/tour111

Looks good here:
http://www.206tours.com/tour37

![image](https://cloud.githubusercontent.com/assets/10079829/17859747/dc33aab0-6858-11e6-94ba-ddbb6e39cd46.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17859948/83c4f73e-6859-11e6-89f3-7db87e6d4fd0.png)

**Comment by bradatkins** [comment]
Could be the size of the images?

**Comment by ronenreinheimer** [comment]
Look at this older version, seems to be OK:
www.206tours.com/tour111/index-08-16-16.htm<http://www.206tours.com/tour111/index-08-16-16.htm>


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
