### ISSUE TITLE
Tour # 70 - MAY 29, 2017 - should be SOLD OUT (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1428]
![image](https://cloud.githubusercontent.com/assets/10079829/17861759/5ba50670-6860-11e6-8559-d85fd86a1764.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17861786/7451198e-6860-11e6-9966-1b47921b8757.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/17863525/ef2e2c62-6867-11e6-9274-f9c756e81014.png)
