### ISSUE TITLE
Recaps not exporting with correct balance

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#143]
Hi Brad, 

Recaps are not exporting with the correct balance. 

For Example:  JS020115

There are 3 people with a balance = $128 (which i'm about to fix so that all are showing as PIF)

![image](https://cloud.githubusercontent.com/assets/8440903/5682295/c1ded6e6-97ec-11e4-8508-328794a8fa2a.png)

But when you open the recap in the DB the balance due is showing as $3,639.00 and the commission payment i applied for Bennett in the amount of $4,099 is not showing in the payments section on the recap. 

![image](https://cloud.githubusercontent.com/assets/8440903/5682315/ffcd1aee-97ec-11e4-8265-55e6739dc966.png)

All recaps need to be showing correctly in the DB.

**Comment by ali206** [comment]
Also, the total tour amount for cxld passengers is incorrect:

![image](https://cloud.githubusercontent.com/assets/8440903/5682627/6543d974-97ef-11e4-9bec-b47ac5ada2f6.png)

Insurance was manually applied and is showing twice on recap for some reason:

![image](https://cloud.githubusercontent.com/assets/8440903/5682647/832a2e8e-97ef-11e4-9f70-5e117ce3fb8e.png)

Total tour amount is wrong as well:
In DB it's $117,658
On my recap I have $113,030 + Free trip of $5,198 = $118,228

**Comment by bradatkins** [comment]
Have a look now and let me know

**Comment by ali206** [comment]
Subtotal for cxld pax is still incorrect, everything else seems ok with this recap

![image](https://cloud.githubusercontent.com/assets/8440903/5939831/f3618c9e-a6d4-11e4-87e7-34b45d128a7f.png)
