### ISSUE TITLE
Space between dates in UI - (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1430]
Hi Brad,

Milanka feels there is too much space between each travel date. Can you please cut it in half and we can reevaluate.

![image](https://cloud.githubusercontent.com/assets/10079829/17866313/123cefe8-6874-11e6-81e7-613696ebea3a.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY!
