### ISSUE TITLE
Fr. Calloway Mexico UI double up  (DC122716)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1432]
Hi Brad,

This looks like a glitch:
http://pilgrimages.com/frcalloway/mexico/index2.htm

**DC122716**

![image](https://cloud.githubusercontent.com/assets/10079829/17867659/5f47ac1a-6879-11e6-85d3-dda7901ae86c.png)

**Comment by bradatkins** [comment]
Fixed. Also the year was wrong on the return date

**Comment by ronenreinheimer** [comment]
TY
