### ISSUE TITLE
Wrong insurance premium on this invoice?!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#144]
Hi Brad, 

This person registered this year in 2015 but Travel Guard insurance premium popped up on their reservation? Can you please look in to this, we have to honor it now as the client already received a copy of their invoice.

![image](https://cloud.githubusercontent.com/assets/8440903/5686170/ae63ac14-980e-11e4-9198-d9cfda946d01.png)

**Comment by bradatkins** [comment]
Fixed. It originally calculated correctly; however, in the process of adding the additional cost of the pre-night, there was a bug.
