### ISSUE TITLE
NEW DB accounting error with paypal | 424974 (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1444]
![image](https://cloud.githubusercontent.com/assets/10079829/18054182/c86c1c06-6dd0-11e6-9137-05877c3a3dfd.png)

**Comment by ali206** [comment]
Seems was only processed once but showing up in the DB a million times:

![image](https://cloud.githubusercontent.com/assets/8440903/18057370/be40f3c0-6ddd-11e6-9438-b2707355ba71.png)

**Comment by bradatkins** [comment]
Phewf....

**Comment by ali206** [comment]
Can i decline all other payments that posted or do you need to check out what happened first

**Comment by bradatkins** [comment]
Go ahead and decline them

**Comment by ronenreinheimer** [comment]
Can i decline all other payments that posted or do you need to check out what happened first

from Ali

**Comment by bradatkins** [comment]
Yes

**Comment by bradatkins** [comment]
Ok I think I fixed it. I couldn't reproduce it, so let's keep an eye out
