### ISSUE TITLE
DB Client Messages Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1445]
not sure what happened, but i setup the promo and i went back to edit it and it is not there. not sure what i did wrong, sorry.

![image](https://cloud.githubusercontent.com/assets/10079829/18054631/a6993986-6dd2-11e6-980c-78a9e6367d2a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18054657/b9a423c4-6dd2-11e6-8957-54c31500752c.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/18054738/06f42c32-6dd3-11e6-96b5-1f70f50b080e.png)

**Comment by bradatkins** [comment]
Send me the HTML if you can

**Comment by ronenreinheimer** [comment]
Poland & Prague <font size="4" color="#e6c096">$200 Discount</font>Special - Book Tour <a href="http://www.206tours.com/tour169" class="link">169</a> or <a href="http://www.206tours.com/tour174" class="link">174</a> in 2016. For new reservations Only. Valid until September 2, 2016. Use Promo Code <font size="4" color="#e6c096">POLAND16</font>



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
**i see the 2 edit buttons are working differently!**

![image](https://cloud.githubusercontent.com/assets/10079829/18059714/3bf8a15a-6de8-11e6-8e91-297244c9944a.png)

**Comment by bradatkins** [comment]
Si it's working? Those buttons do the same thing...

**Comment by ronenreinheimer** [comment]
no, the right edit button goes to something totally different:

![image](https://cloud.githubusercontent.com/assets/10079829/18092622/f8c6059a-6e9a-11e6-8e6f-daa9764eb02f.png)
