### ISSUE TITLE
New KBYG Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1446]
Hi Brad,

Can you please check why the following items are not working:

**new document:**
http://www.206tours.com/assets/html/country-description-italy.html

**original document:**
http://www.206tours.com/assets/html/country-description.html

feel free to work to modify new document..

![image](https://cloud.githubusercontent.com/assets/10079829/18064520/cc1bceb4-6dfd-11e6-8099-bd4ebcb39aed.png)

![image](https://cloud.githubusercontent.com/assets/10079829/18064638/414214e6-6dfe-11e6-95d6-e36b6de91a83.png)

**Comment by bradatkins** [comment]
Hey -

It's not really clear to me why it's happening. I suggest starting from the original file and adding in some stuff a bit at a time and checking...

FYI I use a little tool to check differences: https://www.diffchecker.com/  and I didn't see anything that stood out

**Comment by ronenreinheimer** [comment]
OK, I will start again.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
OK, when i replaced the footer code, the page stopped working.
http://www.206tours.com/assets/html/country-description-italy2.html


**current footer code:**
[current-footer-code.txt](https://github.com/206Tours/DB/files/445303/current-footer-code.txt)
![image](https://cloud.githubusercontent.com/assets/10079829/18096153/485099e8-6ea7-11e6-8282-95e63e33bb2b.png)


**new footer code:**
[new-footer-code.txt](https://github.com/206Tours/DB/files/445306/new-footer-code.txt)
![image](https://cloud.githubusercontent.com/assets/10079829/18096122/30edc55a-6ea7-11e6-94b8-91762b9aaf49.png)
