### ISSUE TITLE
FW: Home Page - 2nd Tier Navigation 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1447]
Hi Brad,

The update is also supposed to give us a 2nd tier navigation.

Can you please check if this is working? I copied the code from their sample, but I don’t see it working.

This is their sample:
http://206tours.bigdropinc.net/dist/html/home.html

this is a sample I uploaded:
http://www.206tours.com/index7.htm

![image](https://cloud.githubusercontent.com/assets/10079829/18092406/2c73f880-6e9a-11e6-8cf5-95d6c6f49811.png)

**Comment by bradatkins** [comment]
Seems to be there?

![image](https://cloud.githubusercontent.com/assets/8440255/18096461/41dc52d6-6ea8-11e6-884c-a64d74857bb8.png)

**Comment by ronenreinheimer** [comment]
no, look at the screen shot I sent you. it is supposed to have little arrows and the next tier is supposed to expand into the right.

like this:
http://joxi.net/a2XWkR8fKpEamg

[cid:image001.png@01D202B5.59DAE6E0]



God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
