### ISSUE TITLE
Urgent: 423631 | Please ask Brad to unmask the client who is signed up, paid for - but appears nowhere on the trip (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1448]
![image](https://cloud.githubusercontent.com/assets/10079829/18095300/8a7c5760-6ea4-11e6-8bc3-468b60925258.png)

**Comment by bradatkins** [comment]
What do you mean?? This request isn't clear

**Comment by ronenreinheimer** [comment]
There are 2 people booked on this invoice, but only 1 is showing.

Ask Brad if he can clarify why the clients subtotal completely doesn’t match her trip cost. I just got off the phone with client and she is expecting her husband to be listed with her.
Is he not on there? We had another similar issue with the family that booked but the son wasn’t showing.

**Comment by bradatkins** [comment]
Fixed
