### ISSUE TITLE
425061 - paypal payment posting more than once

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1449]
same issue as yesterday - actually only charged once but in DB showing a bunch:

![image](https://cloud.githubusercontent.com/assets/8440903/18096354/dedc1428-6ea7-11e6-8164-c7abf2084469.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18096382/f75ad30e-6ea7-11e6-93e9-17e7640ed524.png)

**Comment by bradatkins** [comment]
Ok I think I fixed it. I couldn't reproduce it, so let's keep an eye out
