### ISSUE TITLE
DB | Incorrect Payment Amount | Tour JH090116 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1452]
![image](https://cloud.githubusercontent.com/assets/10079829/18101767/02167a4e-6ebe-11e6-88af-904d3531022d.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18101825/33ea0176-6ebe-11e6-933d-de9c55577bf1.png)

**Comment by bradatkins** [comment]
Seems to be OK now

![image](https://cloud.githubusercontent.com/assets/8440255/18815456/3302e2b8-8300-11e6-934d-48d5df694acd.png)
