### ISSUE TITLE
425065: CAD conversion problem with promo code

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1453]
Promo code is $150 pp USD, but on CAD invoice still only deducted off $300 instead of $196.50 x 2.

![image](https://cloud.githubusercontent.com/assets/8440903/18104862/1906ea60-6ecb-11e6-88e9-6b90463bd203.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/20653837/34bb1ea0-b4e1-11e6-8bae-28e5528b2f35.png)
