### ISSUE TITLE
DB Custom Addon Rates Not Working - URGENT!

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#146]
Hi Brad,

When clients are booking tours with a custom addon rate - it is not coming through on the review & confirmation section of the DB.

![image](https://cloud.githubusercontent.com/assets/10079829/5711398/3bd0012c-9a78-11e4-8435-dbf521917716.png)

![image](https://cloud.githubusercontent.com/assets/10079829/5711381/11c67cf8-9a78-11e4-9e79-8e6a3c4c6ac8.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/5713707/0788bb42-9a8d-11e4-81b7-44560e8ad64a.png)

**Comment by ronenreinheimer** [comment]
if we set a default departure city in the tours departure section, it doesn't calculate correctly.

**Comment by bradatkins** [comment]
What should the calculations be? Please provide an example

**Comment by ronenreinheimer** [comment]
i looks to be corrected now.
