### ISSUE TITLE
424974 - paypal payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1461]
this is the only email we got saying she made a payment:

![image](https://cloud.githubusercontent.com/assets/8440903/18169116/a37c16f0-7026-11e6-85b7-87c3df017068.png)

Which popped up as a payment 3 times with the conf # from the 1st paypal payment on the 29th?

![image](https://cloud.githubusercontent.com/assets/8440903/18169132/bd74ee74-7026-11e6-86d7-9a88acec0054.png)

And she didn't actually make a new payment...so i'm confused
![image](https://cloud.githubusercontent.com/assets/8440903/18169270/49109aaa-7027-11e6-918f-20e7ce407dcd.png)

**Comment by bradatkins** [comment]
That's really odd, especially considering it's the same ID on different dates and times.

Let's keep an eye out if it happens again. I almost think this would be related to some system instability on our side or Paypal, as it makes no sense.
