### ISSUE TITLE
Country Tabs on Home Page (need your help please) - Milanka

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1463]
Hi Brad,

We are sorry to be a pain but Milanka is asking about this section and we really need to get it to work properly now. It is top priority.

If the update that Helen sent is not working (attached email), please let them know and copy us. If you need anything from our end, please let us know.

Thank you so much – I will GH this.

![image](https://cloud.githubusercontent.com/assets/10079829/18181367/d551e790-7058-11e6-97d2-dd2303163ce5.png)

**Comment by bradatkins** [comment]
What's wrong with it?

**Comment by ronenreinheimer** [comment]
When I added new tours to a tab, it would also add it to the home page. do you recall that you reviewed the code and you told helen that the way they had it setup it would never work properly? Since then they updated the code and zip it up for us.

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I'll call you next week to discuss. I'm unclear still

**Comment by ronenreinheimer** [comment]
Can you call me now?

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I wish...at the cottage, only have enough signal to barely send an email

**Comment by ronenreinheimer** [comment]
OK, enjoy weekend!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
