### ISSUE TITLE
Client Welcome Letter (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1467]
Hi Brad,

Here is a mockup of the welcome letter that we want clients to receive:
www.206tours.com/ronen/welcome-letter

Please review and let us know if you have any questions.

thank you.

**Comment by bradatkins** [comment]
This is now complete

**Comment by chris206** [comment]
Hey Brad - looks good, but the confirmation email inst being added to the audit. Can you add it to the audit?

![image](https://cloud.githubusercontent.com/assets/22382144/21319162/1e6c9e4e-c5da-11e6-9c29-9eeffe0f6d27.png)

**Comment by bradatkins** [comment]
It will be added to the audit 24 hours later, as Sandy wanted the email to
go out 24 hours after the order is placed

**Comment by chris206** [comment]
The welcome letter email is not being added to the audit, which is a glitch - as we discussed in email

Please also copy "orders" when sending this letter to client

**Comment by bradatkins** [comment]
Done.
