### ISSUE TITLE
New UI for future website

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#147]
Hi Brad,

The new UI has to be 591px wide. Can you construct the new truncated UI from the current UI code that you have?

Please let me know.

Sample of new series tour layout:
www.206tours.com/tour96/index9.htm

![image](https://cloud.githubusercontent.com/assets/10079829/5723012/d1e09578-9b0e-11e4-80f4-a30a0b6e94c4.png)

Current UI size:

![image](https://cloud.githubusercontent.com/assets/10079829/5723020/e0610150-9b0e-11e4-947c-fc36281516e6.png)

**Comment by bradatkins** [comment]
Almost Done, I had to remove the "height" section of the TD and add a couple of line breaks...

![image](https://cloud.githubusercontent.com/assets/8440255/6090194/30c87f36-ae3f-11e4-8947-225078f3da54.png)

![image](https://cloud.githubusercontent.com/assets/8440255/6090289/efdd319e-ae41-11e4-834c-1ba9d9be0d6c.png)

I just need to know what font sizes etc you used...

**Comment by ronenreinheimer** [comment]
Hi Brad,

I know it might be tough, but I need the entire UI to be no bigger than 591px

The font size is the same as the current UI, except the font size for the days of the week: you can try this style: notincltxt6 from corporatestyle.css which is font size 9.

Setting up the new UI will be critical to the new layout.

[cid:image002.png@01D04453.B757E6F0]

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Have a look now:

![image](https://cloud.githubusercontent.com/assets/8440255/6217572/5b7b090a-b5e3-11e4-80d3-46837f7a11a3.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you get it as close to this as possible? Items need to be spaced out a little bit more. I can point out the difference if it helps you? I can also setup additional font sizes if it will help you?
http://www.206tours.com/tour96/index9.htm

[cid:image001.png@01D049F1.7A761790]

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Please point out what needs to be changed.

**Comment by ronenreinheimer** [comment]
Hi Brad,

Let me know if this helps you. I created a mockup with your new UI (on top) and my mockup on the bottom. If you can shift the items to the light blue guides.


1.       Move (days the week to the left and use a smaller font) *if you need me to create a smaller font in the .css file, please let me know.

2.       Move the radio buttons to the left

3.       Move the dropdown menu to the left

4.       Move the land only price to the left

5.       Move the book now button to the left

Thank you again with your patience with all these projects, I know it’s not easy work.

[cid:image001.jpg@01D04B9B.9A713970]



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
How's this:

![image](https://cloud.githubusercontent.com/assets/8440255/6259736/ed53d282-b7a3-11e4-89e5-664a81d77d81.png)

**Comment by ronenreinheimer** [comment]
OMG Brad, this looks AMAZING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Amazing work Brad, I am really impressed!!!

I just see a small decadency between IE and chrome. Chome it came out perfect, IE needs a tiny space between Airfare and drop down menu. I also noticed that the mouse changes status over the UI – from a pointer to a hand.

Please review screen shots.

Thank you again Brad, I am thrilled with how it came out!


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed.

**Comment by ronenreinheimer** [comment]
Looks exquisite! Amazing Job Brad!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

n1

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
