### ISSUE TITLE
DB | Suffix on registration |  Tour JH090117 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1471]
f12ead3a2caa3ac80aadf3b858e4e3a9

![image](https://cloud.githubusercontent.com/assets/10079829/18402279/b2a63ca0-76ac-11e6-8add-5adccf0050f0.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18402308/d01ad002-76ac-11e6-9547-274c392e4647.png)

**Comment by ronenreinheimer** [comment]
f12ead3a2caa3ac80aadf3b858e4e3a9

![image](https://cloud.githubusercontent.com/assets/10079829/18402398/285f7a42-76ad-11e6-8660-9b683b95f12a.png)

**Comment by bradatkins** [comment]
Fixed
