### ISSUE TITLE
DB| AUDIT invoice reflecting incorrectly (sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1473]
Session ID: 8eb1da55deaa091f9bc907346e9ca31b

![image](https://cloud.githubusercontent.com/assets/10079829/18475319/f8925fc0-7993-11e6-922e-db09cb95f5e6.png)

**Comment by ronenreinheimer** [comment]
**However, the invoice the client received is correct**

**Comment by bradatkins** [comment]
Seems to be OK now?
