### ISSUE TITLE
RM might not be working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1477]
tckts not showing in DB but order # is in RM in Amadeus...sandy said maybe RM isn't working??

![image](https://cloud.githubusercontent.com/assets/8440903/18486410/f45e4b46-79be-11e6-8056-39e0c073eb75.png)

**Comment by bradatkins** [comment]
On the PNR for 424880 (2VINHA) why is there an RM for Order #422552 ?

Same thing for 424295 (2S3JWW)

I bet if you remove the RM for 4222552 on the above two PNR's it'll be all good

**Comment by ali206** [comment]
ok i told sandy what you said...she said she took care of it but only the ticket for 424880 is showing. 

the other 2 are still not showing in the DB

**Comment by bradatkins** [comment]
OK Fixed. The DB wasn't able to handle an Active and a Dead PNR on the same message from Amadeus. Good now
