### ISSUE TITLE
FREE trip issued when doing it through Apply a payment button

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#148]
When trying to apply a FREE this way, we need the option of not being forced to select one of the items in the box that pops up:

I need to apply a FREE of $1,849.50 which does not go with any of the options in the box and therefore DB won't let me apply it this way. 

![image](https://cloud.githubusercontent.com/assets/8440903/5723914/cd496b0a-9b15-11e4-9cae-cae9bdad5336.png)

**Comment by bradatkins** [comment]
What does it apply to? Or is it just some random number?

**Comment by ali206** [comment]
She earned a free trip of $3699 but is splitting it with her friend who is on a different booking #

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/5829434/1a1ebc62-a0e0-11e4-92d8-9ec5015d0305.png)
