### ISSUE TITLE
Waitlist is not Showing up on Invoice (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1481]
![image](https://cloud.githubusercontent.com/assets/10079829/18521692/31ad66e6-7a7b-11e6-934c-91b0f3f492bf.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18521717/49c11796-7a7b-11e6-8c80-03cc046d59e0.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18521731/54bc01a6-7a7b-11e6-900d-e20558f0d7a1.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18521746/5f27a780-7a7b-11e6-9d47-a95dcb5fe520.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18521755/65a978f4-7a7b-11e6-9585-de776e0656dd.png)

**Comment by bradatkins** [comment]
Where and what should be showing up?

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/18558245/6051d354-7b40-11e6-92a3-9ad1667cea95.png)

**Comment by ronenreinheimer** [comment]
**Sample Wait list FW: 206 Tours Inc. Wait List - Order #425222  Tour #FAT2017H October 9, 2017**
![image](https://cloud.githubusercontent.com/assets/10079829/18561267/2da9f9c4-7b4d-11e6-97ad-048404ccc86f.png)

**Comment by ronenreinheimer** [comment]
Oy oy oy  ---------------- it should come out waitlisted NOT confirmed . Ronen didnt Brad fix this ?    FW: 206 Tours Inc. Confirmation - Order #425282  Tour #FAT2017A October 9, 2017

**Comment by bradatkins** [comment]
Fixed
