### ISSUE TITLE
DB Glitch Issue: We take every single reservation twice because of irregularities in the DB (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1482]
![image](https://cloud.githubusercontent.com/assets/10079829/18525611/3bedcd3e-7a8b-11e6-8be1-54e0d23339bf.png)

**Comment by bradatkins** [comment]
If there's glitches, please report them, and I will fix them. A general bug "things are broken" don't help

**Comment by ronenreinheimer** [comment]
Occasionally, the database deletes things that are entered correctly like: phone number, email, zipcode (as I mentioned in the email). This is background for my email rather than a complaint.

The issue is that, because of this, people are reluctant to rely on the database. This causes them to seek non-technological solutions – such as keeping physical files and printing out documents every time there is a change of any kind. There are multiple employees handwriting instructions (each with difficult to read handwriting) on thousands of 1 inch thick bundles of paper. They are taking every reservation twice – this is the complaint that requires a solution.

Rather than enhancing accuracy, this decreases accuracy and leads workload fatigue. Everything should be databased – but to overcome objections to this, we need to create protections with those legitimate concerns in mind that do not rely on taking reservations twice and handwriting thousands of notes that cannot be searched.

I’m not saying that the database can or should be perfect – but it can automate redundant or archaic processes and problems.

**Comment by bradatkins** [comment]
I need some examples of when this happens so I can track it down. If it happens, please post it as a separate issue.
