### ISSUE TITLE
#425214 -invoice was not updating properly 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1484]
Client registered on her own departing from Tampa and had add on for insurance of ($308) which was the difference between base price and total tour cost.

For some reason, maybe b/c she was booked twice by accident, the insurance wasn’t showing on her invoice so it looked like there was a price discrepancy but there actually wasn’t.

I updated and cancelled manually everything. 

![55](https://cloud.githubusercontent.com/assets/14838466/18526897/6b264432-7a90-11e6-9190-a383041ca6d7.jpg)

**Comment by bradatkins** [comment]
This order is cancelled?

**Comment by Irena206** [comment]
Yes, was cancelled after because order wasn't pricing correctly.
