### ISSUE TITLE
please set all series tours back to "Choose a Departure City" (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1485]
![image](https://cloud.githubusercontent.com/assets/10079829/18555208/03de7eac-7b35-11e6-8872-3bf01a69dbc8.png)

**Comment by bradatkins** [comment]
Fixed, but I couldn't test it because I couldn't remember which tour had this setup. Please check

**Comment by ronenreinheimer** [comment]
please set it also for older tours:
www.206tours.com/tour9

**Comment by bradatkins** [comment]
Done.
