### ISSUE TITLE
MR101716 - unable to scroll beyong pax #9 in Admin recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1496]
![image](https://cloud.githubusercontent.com/assets/8440903/18642706/b9a449f0-7e6f-11e6-97ec-e9a7020fe26b.png)

**Comment by bradatkins** [comment]
Seems to be OK for me?

![image](https://cloud.githubusercontent.com/assets/8440255/18812276/f6a72346-829c-11e6-9cef-f834f59ef6e8.png)

**Comment by ali206** [comment]
Irena and i both can't, she uses Chrome i use IE

**Comment by bradatkins** [comment]
Ahh ok I see it now. It's not an IE vs Chrome thing.

https://www.206tours.com/register/admin/reports_recap.php?TourID=3560&TourDepartureID=32245&RecapType=ADMIN

**Comment by bradatkins** [comment]
Fixed
