### ISSUE TITLE
Dates wrong on payments in this Recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#15]
https://www.206tours.com/register/admin/reports_recap.php?TourDepartureID=28740&TourID=2811

Dates should be throughout all recaps as MM/DD/YY

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/8020058/5c0310fa-0c39-11e5-8797-792ddf365c81.png)

![image](https://cloud.githubusercontent.com/assets/8440255/8020064/7fd512ee-0c39-11e5-8a3c-42b695799fcd.png)
