### ISSUE TITLE
Bookings marked as Moved show in Reg. pax still

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#150]
Hi Brad,

When we mark bookings as “moved” it still shows up as a registered passenger for that group. Example below.  They shouldn’t show up in this list at all.

![yari](https://cloud.githubusercontent.com/assets/8440903/5741174/a64f7b9e-9bd7-11e4-865f-ff0ca4e7e0e5.png)

**Comment by bradatkins** [comment]
Fixed, but please note 417080 is currently set to "New Request" not "Moved"

**Comment by ali206** [comment]
I know, she was just pointing out that the new booking and the old moved booking (417130) were showing in the same list.

thanks!
