### ISSUE TITLE
Barkett ticket

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1500]
should only be $1049.67 but in DB is as per below:
![image](https://cloud.githubusercontent.com/assets/8440903/18646494/cdeb1f0a-7e7f-11e6-868b-1965aaf30a15.png)

And tckt endig 4016 is a seat for $46:
![image](https://cloud.githubusercontent.com/assets/8440903/18646512/e8c20686-7e7f-11e6-81e7-73f3fc8d2db5.png)

**Comment by bradatkins** [comment]
Right, there's two tickets associated to him, hence the recap is suming them. If one of those tickets is invalid let me know.

**Comment by ali206** [comment]
It's not that one is invalid - one is a valid ticket and one is a valid purchased seat. 

The problem is the $ amounts....DB is doubling the ticket amounts and overriding the actual cost. 

6362 - $1049.67
4016 - $46

**Comment by bradatkins** [comment]
6362 exists on two PNR. It needs to be removed from one of the PNRs (the order ID RM)

![image](https://cloud.githubusercontent.com/assets/8440255/18770468/2e476878-8104-11e6-8c78-9d6386c1069f.png)

4016 is now $46
