### ISSUE TITLE
DB Error: Deleted Clients Last Name & Fails to Create Shipping Label due to missing State in "View Order" field (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1503]
![image](https://cloud.githubusercontent.com/assets/10079829/18673043/57c8063c-7f18-11e6-9d65-bf8482750033.png)

**Comment by bradatkins** [comment]
Seems to be OK now?

**Comment by chris206** [comment]
I was able to fix it, but could you see why it happened in the first place and correct the error?

**Comment by bradatkins** [comment]
Unfortunately I can only investigate them in the moment type thing. Once
the record has changed, I can't debug it

**Comment by chris206** [comment]
This dis-incentivizes our attempts to fix a problem ourselves with a work-around - as it actually eliminates the posibility that the cause will be fixed.
Alternatively, if we know a work around - this can reduce client frustration and make sure that we dont leave problems unadressed

is there a middle ground - where we can fix it in the short term and you can still re-creat the issue?

**Comment by bradatkins** [comment]
I understand the pain it creates, but typically this is the only way. I
can't fix a problem I can't reproduce.
