### ISSUE TITLE
Can you possibly URGENTLY fix ticketing in DB?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1505]
I know Chris talked to you over the phone about passengers being selected or something so that needs to be fixed.  Ex: for 2 people with same last name on an order, DB doesn't know which pax to apply tickets to and so then 1 of them always ends up with an error message or no ticket info showing. 

Also  A LOT of the costs for tickets is now even more wrong than before. 

It's impossible to keep checking tickets and recaps this way, confusing and time consuming.

HELP!

**Comment by bradatkins** [comment]
The amadeus stuff isn't an exact science, as there are many many ways we
can get a bunch of information. As we continue to investigate issues, we
have to fix them.
