### ISSUE TITLE
Registered Pax - can't go to 2nd page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1506]
![image](https://cloud.githubusercontent.com/assets/8440903/18683662/278bdb5c-7f3f-11e6-94ba-30689ac8f73b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18683653/2322899e-7f3f-11e6-8f53-5ffd872c1e8d.png)

e13a51426d516a36fb2751c4c22c6638

**Comment by bradatkins** [comment]
Fixed
