### ISSUE TITLE
registration page - spelling error (sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1509]
![image](https://cloud.githubusercontent.com/assets/10079829/18722991/d7d6c650-8004-11e6-955c-3191457d95ac.png)

![image](https://cloud.githubusercontent.com/assets/10079829/18722970/c50c576a-8004-11e6-9652-d4ce0d6d0603.png)

**Comment by bradatkins** [comment]
Fixed
