### ISSUE TITLE
CC charges don't always show correct name

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#151]
Hi Brad, 

Is there any way that when we/clients make payments to have the correct name show next to the payment?

Ex. 417600
Kathleen actually made the payment but it's showing under Nancy's name, i'm assuming b/c her name is the one the invoice is registered under.  But people panic/get worried when they don't see the correct name next to CC charges.

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417600&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
You need to specify it here (206 Tours Staff applied payments):

![image](https://cloud.githubusercontent.com/assets/8440255/5789102/d790688a-9e2a-11e4-8197-34c4c4a5606d.png)

Or here (customer applied payments):

![image](https://cloud.githubusercontent.com/assets/8440255/5789106/fafb3ef8-9e2a-11e4-958e-5147633a5456.png)

**Comment by ali206** [comment]
It is specified in both of those fields and it still doesn't show the correct name, it's only showing the name of the person the booking is registered under.

**Comment by bradatkins** [comment]
I'm confused...

![image](https://cloud.githubusercontent.com/assets/8440255/5810531/e06635f6-a015-11e4-8d60-075e1b498b98.png)

**Comment by ali206** [comment]
That's because I already manually fixed that specific payment for that booking. 

It's does that on all bookings, not just this one.

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/5930242/3bb6f878-a65b-11e4-97e3-0be60e6b015d.png)

I'm not sure because it seems to work OK for me?

**Comment by ali206** [comment]
It just worked for me too, but is it because i'm ADMIN Maybe?  Other "USERS" in the office it doesn't seem to be working for.

**Comment by bradatkins** [comment]
Can you get a non-ADMIN level user to try?

**Comment by ali206** [comment]
Jennie just charged this card today:

Name on card that she entered after clicking on apply payment was Doris Phillips:
![image](https://cloud.githubusercontent.com/assets/8440903/5941423/f8c5328a-a6de-11e4-8ab5-b3f88e209e51.png)

**Comment by ali206** [comment]
I just watched chris register himself as a fake booking but use my CC and it happened again:

![chris](https://cloud.githubusercontent.com/assets/8440903/5941841/913bc3c4-a6e1-11e4-947b-eeeb93cf77a4.jpg)

![image](https://cloud.githubusercontent.com/assets/8440903/5941847/96f93e36-a6e1-11e4-9d01-25d952dc373e.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6072743/2337a1ca-ad73-11e4-9097-cd31abe122bb.png)
