### ISSUE TITLE
DB Error: Amadeus generated code still not including name suffix (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1511]
![image](https://cloud.githubusercontent.com/assets/10079829/18724023/e107764e-8008-11e6-90ff-01e4e32df1c6.png)

**Comment by bradatkins** [comment]
I've added it, hopefully that's the right spot

![image](https://cloud.githubusercontent.com/assets/8440255/18734761/93629c9c-8045-11e6-9c69-6a84da9505ee.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/18751091/b9ee477e-80ab-11e6-95cc-c3aa194364e7.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
Great, thank you so much it works great
