### ISSUE TITLE
www.206tours.com/tour70  (Sandy / Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1512]
please swap Tour Name and Tour Length

![image](https://cloud.githubusercontent.com/assets/10079829/18728505/65c27c82-801b-11e6-95e3-1f47d51f3c4e.png)

**Comment by bradatkins** [comment]
Yes, just use:

<? echo $TOUR_INFO['TourNumDays']; ?>

Instead of:

<? echo $TOUR_INFO['TourNumber']; ?>

**Comment by ronenreinheimer** [comment]
I got this result:

http://www.206tours.com/tour70/index3.htm

 
![image](https://cloud.githubusercontent.com/assets/10079829/18755138/fb300fe4-80b8-11e6-9bfe-d1e26982b2e6.png)

**Comment by bradatkins** [comment]
Huh? Obviously you have to remove the word days and change the other text.

**Comment by ronenreinheimer** [comment]
can you help me to center tour numbers that exceed 3 characters?
http://www.206tours.com/tour206
![image](https://cloud.githubusercontent.com/assets/10079829/18838671/3f93edac-83d6-11e6-9c4f-d6b2aef79807.png)
![image](https://cloud.githubusercontent.com/assets/10079829/18838702/5e485b3e-83d6-11e6-841b-fbc15b5e1848.png)

**Comment by bradatkins** [comment]
Probably change "float-left" to float-left centered" on the second div tag?
