### ISSUE TITLE
423939 - state not showing on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1514]
state is showing in all passengers and when you click on client's name but not on invoice? Where else does it need to be?

![image](https://cloud.githubusercontent.com/assets/8440903/18755129/f5f623b0-80b8-11e6-8dfc-e27e109dfca3.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18755179/1f2e41b8-80b9-11e6-9b49-4c99a522925d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18755192/3048af1a-80b9-11e6-9209-01a0c60fa485.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18755229/591ae1f6-80b9-11e6-8700-f871953421a0.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
State is showing as VA but it should be IA:

![image](https://cloud.githubusercontent.com/assets/8440903/18849665/f80603b8-8401-11e6-8af7-8a165f829a2a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18849669/fd963028-8401-11e6-9dd3-78709ef19bf4.png)

**Comment by bradatkins** [comment]
Fixed
