### ISSUE TITLE
discounts and payments are not reflected in all orders 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1520]
![image](https://cloud.githubusercontent.com/assets/14838466/18888272/9475c1b6-84c5-11e6-944e-74e916022821.png)

![image](https://cloud.githubusercontent.com/assets/14838466/18888287/a9c35ace-84c5-11e6-91ff-72fa39f066e4.png)

![image](https://cloud.githubusercontent.com/assets/14838466/18888302/b82fbd64-84c5-11e6-8684-68736e512e2a.png)

**Comment by bradatkins** [comment]
Fixed
