### ISSUE TITLE
promotion code 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1521]
https://www.206tours.com/register/admin/formgenerator.php?FORM=ClientMessages&ClientMessageID=6&RecordID=6&PrimaryKeyField=ClientMessageID

For some reason I can’t add a none breaking space code:

![image](https://cloud.githubusercontent.com/assets/10079829/18890636/f6218eea-84cf-11e6-8d29-ae898d6d91de.png)

The DB is erasing that code.

![image](https://cloud.githubusercontent.com/assets/10079829/18890591/c0c9efc6-84cf-11e6-8cbd-ce181946b43e.png)

**Comment by bradatkins** [comment]
Where are you trying to put it?

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/19004539/5aa98eb6-8724-11e6-97a1-ef5e6eb04e01.png)

after you save it, it disappears

**Comment by bradatkins** [comment]
It's there, but it'll just show up as a space:
![image](https://cloud.githubusercontent.com/assets/8440255/19014872/9b627772-87c6-11e6-813b-a67f9dc491f2.png)
