### ISSUE TITLE
STFRANCIS16 promo code not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1525]
i don't know if ronen mentioned this or not to you but we are not able to add as a promo code 

Melissa doesn't have screen shots but here's an ex: - Irena manually applied discount already:

![image](https://cloud.githubusercontent.com/assets/8440903/18891191/2bc1419c-84d2-11e6-93c5-aa2a034b8680.png)

And i see nothing wrong with how it's set up?
![image](https://cloud.githubusercontent.com/assets/8440903/18891200/3513030c-84d2-11e6-9332-7caae1df802d.png)

**Comment by bradatkins** [comment]
Fixed
