### ISSUE TITLE
Move travel dates to top of invoice if Pre/Posts are the same for each PAX

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1526]
1. Date Range is deleted (highlighted in yellow)
2. Date range under each client is wrong (highlighted in red). Land only should be May 8-20, 2017 (including 4 post-stay nights). Instead, it reads May 7-17, 2017

![image](https://cloud.githubusercontent.com/assets/22382144/18915961/c2723cd4-8560-11e6-83c9-b1de0befe7b0.png)

**Comment by bradatkins** [comment]
This isn't a glitch, it's by design. As soon as there's a post/pre, the dates switch to here as different PAX can have different dates.

**Comment by chris206** [comment]
Hmm - I see. So, because each passenger may have different dates, it leaves this blank. Maybe we could eliminate the Gap or place the regular tour dates there and (with date deviations) note. otherwise it looks like a glitch and the client calls. Also, can you make the travel dates larger with an explanation of what those dates are? Should I switch this to "Idea"?
