### ISSUE TITLE
MAJOR GLITCH: Booking multiple passengers repeats first passenger info, flips gender, deletes specific requests

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1527]
Hi Brad,

1. Please build a test booking on any tour with multiple clients.
2. Use different gender for each
3. Select random meals, rooming, departure, air/land and make note
4. complete booking and check order information

-Gender will be switched
-Specific selections will be deleted and/or things that you didnt select will be present (such as child meal, wheelchair etc)

**Comment by bradatkins** [comment]
Hey Chris -

I did this, and the only thing that got mixed up was the Gender:

![image](https://cloud.githubusercontent.com/assets/8440255/19020546/eeea4d58-8879-11e6-8945-0d1b2d1ff09d.png)

**Comment by bradatkins** [comment]
I've fixed up the gender mixup.

**Comment by chris206** [comment]
People's departure cities are being defaulted to blank, insurance purchases are being switched from yes to no (425510), the gender thing is good if that is resolved. I have to fix them as they come up otherwise it will get lost since the problem is recurring.

I just saw a reservation blank out an entire account (425477 - I had to rebuild it piece by piece) - which is weird because there used to be a separation between the two. Is there any way that we can stop a reservation from overwriting an account IF it is trying to overwrite it with blank information?

**Comment by bradatkins** [comment]
Chris -

Please try and report separate issues in separate GH issues, it gets
confusing trying to sort out what information belongs with what problem.

**Comment by chris206** [comment]
ok - i wasnt going to create a new issue because I've already fixed those records and you said that you couldnt chase causes on ones that I've fixed already. I was just using this for background on the main topic - which is info being lost and overwritten.

**Comment by bradatkins** [comment]
I don't think this has happened in a while? If so, please run the recording tool and post a new issue
