### ISSUE TITLE
424555 - state should be IL but showing as VA & pax not showing in all pax

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1529]
![image](https://cloud.githubusercontent.com/assets/8440903/18917706/8860d932-8566-11e6-9c09-c21231756c57.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18917711/8f04b22c-8566-11e6-96ce-ed47edc53e86.png)

I tried to check her address in All pax but for some reason she isn't in there? I searched by first and then last name - nothing

**Comment by bradatkins** [comment]
Fixed
