### ISSUE TITLE
No idea how this happened?! Pax are cxld for some reason

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#153]
Hi Brad, 

I was trying to fix the math on booking 417509 because it was off by $274pp. I went in to Edit Orders to select no (honor pricing) to see if that would work.  I clicked updated, went back to view orders to find the booking and now the pax are both cxld, don't even exist, and i can't add un-cancel them?!?!

when you look at the order audit report i didn't change anything though?

![image](https://cloud.githubusercontent.com/assets/8440903/5822835/75373b82-a0a5-11e4-9213-8fcf2c02b7c8.png)

**Comment by bradatkins** [comment]
They aren't showing as cancelled?

**Comment by ali206** [comment]
There are no registered pax in View Orders: And therefore nothing can be done to their booking
![image](https://cloud.githubusercontent.com/assets/8440903/5942069/2851f246-a6e3-11e4-850a-49c9d4b8a303.png)
