### ISSUE TITLE
GLITCH: Unable to select departure cities for only 1 passenger (2nd instance, same tour)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1530]
Here is the latest client,everything was looking great, charged her for a Dallas departure BUT it disappeared and now she is listed as a JFK departure.

This happened to Ms Edwards on the Same tour - "fortunatly" i am unable to fix it, so there should still be a trail.

![image](https://cloud.githubusercontent.com/assets/22382144/18924980/19eb8b22-8580-11e6-8415-0730e1c0bcbc.png)

**Comment by bradatkins** [comment]
The order is cancelled?

**Comment by chris206** [comment]
no - it is paid in full - but missing the additional charge for her Dallas departure city. I am avoiding fixing things so that you can find the source

**Comment by chris206** [comment]
Hey Brad, can you please open this order up so that I can change her to the correct city? DFW.

**Comment by bradatkins** [comment]
This is not a bug. This tour is setup with local departure cities, and there's only two.

![image](https://cloud.githubusercontent.com/assets/8440255/19137373/4f90aaca-8b41-11e6-8060-c71512aa8607.png)

![image](https://cloud.githubusercontent.com/assets/8440255/19137374/523267e6-8b41-11e6-9bf4-830a42d4bad0.png)
