### ISSUE TITLE
arghhhhhh its happening again -- = waitlisted tour -----  206 Tours Inc. Confirmation - Order #425439  Tour #FAT2017H May 9, 2017 (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1531]
![image](https://cloud.githubusercontent.com/assets/10079829/18928365/b4ae19ba-858d-11e6-800b-338d8060e690.png)

**Comment by bradatkins** [comment]
I just did it and it worked fine?
