### ISSUE TITLE
button link not working

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1532]
can you see why this link button doesnt work:
http://www.206tours.com/tour37

we need this link to help people book the 2017 event.

![image](https://cloud.githubusercontent.com/assets/10079829/18929409/5884b37e-8592-11e6-84b1-40eaae6273e4.png)

![image](https://cloud.githubusercontent.com/assets/10079829/18929312/0112d530-8592-11e6-80fc-9545dd00ae12.png)

**Comment by bradatkins** [comment]
Not sure. You'll have to ask Big Drop, it's giving this error though:

![image](https://cloud.githubusercontent.com/assets/8440255/18936627/e5bd70ea-85b6-11e6-9c8e-ea6576e87b98.png)
