### ISSUE TITLE
Complete Pilgrimages Directory

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1533]
Hi Brad,
Did you have any luck making this page work? I know you were going to make this entire page DB driven?
1.      Complete Pilgrimage Directory Default
   https://invis.io/EP80UNJ26#/175364841_206-Tours_Complete-Directory
2.      List View
   https://invis.io/ST7Y6SO7N#/172505574_206_Tours_Complete_Directory_Listview_

http://www.206tours.com/assets/html/complete-directory-grid.html
http://www.206tours.com/assets/html/complete-directory-list.html

**Comment by bradatkins** [comment]
Hey -

I haven't done this one just yet because most of the tours don't have a Tour Destination set, so this page wouldn't really work well...

**Comment by ronenreinheimer** [comment]
I beleive so, but let me know if you think it's not?

**Comment by ronenreinheimer** [comment]
I thought we fixed that. Can you do a test?

**Comment by ronenreinheimer** [comment]
sandy said that she tested it today but it is not working.

**Comment by ronenreinheimer** [comment]
That's because there's no departure cities setup for Italy:

Before you set the Destination Country, there needs to be the Departure
Cities for that destination country setup

[image: Inline image 1]

**Comment by bradatkins** [comment]
There's already a link for copy base departure cities

**Comment by ronenreinheimer** [comment]
look at new GH entry:
**Complete Pilgrimage Directory (Milanka) #1619**
