### ISSUE TITLE
order audit not showing pax updates 424249

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1538]
Pax updated their own info but it doesn't show that anywhere:

![image](https://cloud.githubusercontent.com/assets/8440903/19075721/2e6c4a08-8a14-11e6-89f0-ed3358e3d738.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19075730/37711926-8a14-11e6-81f0-a75942587e3c.png)

**Comment by bradatkins** [comment]
It wasn't the PAX that did it, but there was a bug hiding the updates

![image](https://cloud.githubusercontent.com/assets/8440255/20736383/1f4b77ec-b674-11e6-9457-5ae0864d3909.png)
