### ISSUE TITLE
425241 - can't submit new info 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1539]
I logged in as Mr. Moon, clicked on edit order, scrolled down to click continue to see what he was talking about how the DB makes it look like he's repurchasing his tour...and i just got a blank page. 

so i'm not sure how he even got tot he end:

![image](https://cloud.githubusercontent.com/assets/8440903/19076147/a92e294a-8a15-11e6-9897-6571e7d95dd9.png)

**Comment by bradatkins** [comment]
Fixed
