### ISSUE TITLE
URGENT! 417654

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#154]
I just rebooked these pple in hopes it would correct the math problem and it didn't.

Pre & Post stay is $155 and $119 per night, they are staying 2 nights for each tour.  The correct total for each pre/post is showing correctly on the invoice but the DB is only adding it for 1 night in to the total tour cost. 

Can you please fix?

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417654&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Fixed
