### ISSUE TITLE
423416 - unable to edit order on client side

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1540]
I logged in as myself but am unable to edit any information, says to call 206?

![image](https://cloud.githubusercontent.com/assets/8440903/19076446/cf3e582a-8a16-11e6-94ba-f8b2db2f2304.png)

**Comment by bradatkins** [comment]
Because it's within 60 days or past tour

**Comment by ali206** [comment]
well the dept date makes sense but not the rtn date so that's why?

![image](https://cloud.githubusercontent.com/assets/8440903/19076586/64cc5f72-8a17-11e6-842f-250f06a5987f.png)

**Comment by bradatkins** [comment]
Fix the return date to something after Jun 6 and see if that fixes it.
