### ISSUE TITLE
421754 - balance due of $200 but DB won't let us charge her CC

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1542]
![image](https://cloud.githubusercontent.com/assets/8440903/19077649/794a9172-8a1b-11e6-987b-7502724800ef.png)

Session ID: 0487bef3a3ee8d73a85af4cd9f302790
![image](https://cloud.githubusercontent.com/assets/8440903/19077679/8d410c24-8a1b-11e6-8993-70f7503b4c41.png)

the error message is wrong b/c i charged her card manually and it went through

**Comment by bradatkins** [comment]
What payment value was entered?

**Comment by ali206** [comment]
200.00

**Comment by bradatkins** [comment]
That error message is from Elavon, not the DB. If you can reproduce it let me know
