### ISSUE TITLE
423192 - cxld mesg on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1544]
where is Db pulling this date from?

![image](https://cloud.githubusercontent.com/assets/8440903/19085543/a32bfba8-8a38-11e6-913b-52b88f44ad3a.png)

**Comment by bradatkins** [comment]
It's at the time of order, so someone entered an invalid date.

I made it so you can edit it here:

![image](https://cloud.githubusercontent.com/assets/8440255/19136977/a3ae209a-8b3e-11e6-9512-3d9305ab6b79.png)
