### ISSUE TITLE
Should be waitlisted !!!       FW: 206 Tours Inc. Confirmation - Order #425534  Tour #FAT2017G May 1, 2017 (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1546]
![image](https://cloud.githubusercontent.com/assets/10079829/19091556/3072dcd0-8a51-11e6-96cb-e5fe970d857e.png)

**Comment by bradatkins** [comment]
It seemed to be an issue with new clients, fixed
