### ISSUE TITLE
424629 - payments not showing in correct date order

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1548]
![image](https://cloud.githubusercontent.com/assets/8440903/19114242/1fd316c6-8adb-11e6-9834-93ed9bac929f.png)

**Comment by bradatkins** [comment]
It's always been this date order, what do you want it to be?

**Comment by ali206** [comment]
No it hasn't, it's always been in chronological order like below:

![image](https://cloud.githubusercontent.com/assets/8440903/19361809/139e2c38-9152-11e6-9237-fc2b26cf77aa.png)


Above is 9/20 first then 9/19

**Comment by bradatkins** [comment]
Commissions will show up at the end, even though it's part of the payments section.

The order for payments is oldest to newest
