### ISSUE TITLE
423859 - email address showing as middle name

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1549]
![image](https://cloud.githubusercontent.com/assets/8440903/19114298/676f5224-8adb-11e6-82ca-92008157c174.png)

But she's not registered anywhere with email in the wrong spot

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/19137187/1218753e-8b40-11e6-99a1-1541d1fa5693.png)
