### ISSUE TITLE
Reposition 'Confirm your booking button' - DB

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#155]
Hi Brad,

Can you please reposition this button:

![image](https://cloud.githubusercontent.com/assets/10079829/5824927/ba25ceec-a0b5-11e4-8da6-c98794debe2c.png)

**Comment by bradatkins** [comment]
Do you want the button under the line with the double ** or under the "I,
Ronen" line?

Brad

**Comment by ronenreinheimer** [comment]
Hi Brad,

I would say above the ** line

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

Please let me know when you can change the location of the button?

Thank you.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
hi Brad, will you be able to make the adjustment?

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/9431382/decb16ea-49dd-11e5-94ed-e4cb284b3eaa.png)

**Comment by ronenreinheimer** [comment]
Thank you Brad! It is so much clearer now.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
