### ISSUE TITLE
Supposed to be waitlisted .......Fwd: 206 Tours Inc. Confirmation - Order #425586  Tour #FAT2017A May 9, 2017 (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1562]
![image](https://cloud.githubusercontent.com/assets/10079829/19271626/74f8fc26-8f93-11e6-985c-bd6392cbce35.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/19293093/fa616820-8fee-11e6-9b89-8be99da40c70.png)
