### ISSUE TITLE
terms and conditions date code (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1565]
Hi Brad,

Milanka wants the date on the terms and conditions to remain up to date, each time a client has to confirm the terms during the booking process.

On this page, I have a code that does that: www.206tours.com/terms

Can you do the same thing for the DB?

![image](https://cloud.githubusercontent.com/assets/10079829/19273202/9b9f6152-8f99-11e6-987e-126433c36533.png)
![image](https://cloud.githubusercontent.com/assets/10079829/19273217/aa826778-8f99-11e6-9b3c-1370f37b6212.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY
