### ISSUE TITLE
URGENT: Sold out tours still confirming people

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1567]
![image](https://cloud.githubusercontent.com/assets/8440903/19275046/601452d0-8fa0-11e6-892b-e7907085538f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19275066/6ff8f584-8fa0-11e6-9bf5-c52df5664178.png)

**Comment by ali206** [comment]
Ex: 425586

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/19293086/e62b9fba-8fee-11e6-88bd-07b8b20f60fc.png)

Fixed
