### ISSUE TITLE
passengers who are cancelled are still listed on rooming list

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1568]
Clients who are cancelled are still showing up on name and, most importantly, rooming list

For some reason, even though a cancellation has been processed and the order knows that it is cancelled, the rooming list doesn't. This is related to the fact that the "status" has to be manually changed to "cancelled", but only management can do this (users have a drop down that doesnt change anything) and it is a second step.

The solution is to translate a cancellation from the order to the rooming list - irrespective of what the "order status" is. It is giving us incorrect passenger counts.

Session ID: d3b5547eaad936392cfb2b1637c356c0

![image](https://cloud.githubusercontent.com/assets/22382144/19314427/14f4c9d8-9068-11e6-88de-ae27f621de6a.png)

**Comment by bradatkins** [comment]
When I pull the rooming list for this departure I get nothing? Where are you pulling the rooming list from?

![image](https://cloud.githubusercontent.com/assets/8440255/19314658/fbbe4312-9068-11e6-8603-1dcfca7622a6.png)

**Comment by chris206** [comment]
wrong departure - hers is Nov 20

**Comment by bradatkins** [comment]
Fixed.

**Comment by chris206** [comment]
ok perfect, thanks

Is it fixed for this order, or for future?

**Comment by bradatkins** [comment]
Past, current and future...and this order too

**Comment by chris206** [comment]
excellent, thank you
