### ISSUE TITLE
New Agent User Name Drop down box out of order

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#157]
on Admin screen, click on new agent. 

The username drop down box is all scrambled and should be in alphabetical order. 

Can you please fix that?

![image](https://cloud.githubusercontent.com/assets/8440903/5845105/525f3aaa-a187-11e4-9202-e060d494263b.png)

**Comment by bradatkins** [comment]
Fixed. It was actually sorted by Username. Now it's sorted by First Name, Last Name
