### ISSUE TITLE
Group Fedex Labels & Group Flight Itineraries - Idea for a change

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1571]
The current process that we use for printing as a a group is extremely helpful to me BUT has too many steps and is confusing to way too many staff members. The effect of this is that nobody else uses it, which is unfortunate.

compiling each itinerary/label to its own file creates individual files and adds them to a zip file, requiring unzipping - and you have to unzip them to your own pc because they dont print from the networked drive. Additionally, we use chrome, so the fact that they need to be opened in IE (the flight itineraries) creates confusion.

it would be better if clicking the group flight button generated a single file with all itineraries in it (like a 40 page hosted file). Think of it as a single .php flight itinerary that included ALL tickets and just kept going.

you would just wait as it compiled and then print from the DB, like we do when printing individual airfares or mailing labels. One click to compile, one click to print.

You wouldn't have to save the zip, or extract the files to the desktop, or open your ie browser, or drag and drop all files into print queue, or wait for each file to open individually.

Of course, printing individual itineraries and labels would remain unchanged.

Is this possible? Please let me know if my explanation is unclear

**Comment by bradatkins** [comment]
is this the same as #1245 ? @chris206

**Comment by chris206** [comment]
yes

**Comment by bradatkins** [comment]
This is now done.

**Comment by chris206** [comment]
OK - great, so my first test of a departure with tons of itineraries went great. All printed, in the proper format, separate from one another, with 2 clicks

That is intuitive. Once people can more consistently have the RM code added in, this feature will take off.

The fedex one is just cycling and doing nothing, though. Take a look at my session from Time: 09:17:24

**Comment by chris206** [comment]
I think it might be crashing on the flight schedules. Take a look at JP050917

There are a number of pilgrims booked outside of group space here. There RM's are correctly linked with the DB and I've printed them already - but only 2 pilgrims are showing up in the group print......

Can you maybe include a read-me in each HTML that will print with all of the order numbers that failed to print?

**Comment by bradatkins** [comment]
Hey -

I've added a list of error messages you can now see:

![image](https://cloud.githubusercontent.com/assets/8440255/25095906/a8a77270-236b-11e7-8438-62b4372136bf.png)

**Comment by bradatkins** [comment]
What departure are you trying the FedEX thing on? Please give me the Tour # and departure date.

**Comment by chris206** [comment]
**I tried it on SM042717 - this is now compiling stuff, but it doesn't actually give us the HTML or PDF**
![image](https://cloud.githubusercontent.com/assets/22382144/25096242/65de0be6-236d-11e7-9ff3-7ca778b41577.png)

 **& JP050917 - same issue**
![image](https://cloud.githubusercontent.com/assets/22382144/25096255/72fc5328-236d-11e7-9984-d00ff0b2fb01.png)

**Comment by chris206** [comment]
As far as SM042717 is concerned, i dont believe it is trying to pull all passengers. This departure has plenty of passengers who have no itineraries. why isnt it showing those order numbers and expressing failure in that readme?
![image](https://cloud.githubusercontent.com/assets/22382144/25096383/f57a8068-236d-11e7-9ce8-2e9812345c94.png)

**Comment by bradatkins** [comment]
The FedEX one wasn't showing you the link cause I had it commented out! ha, sorry :) It's there now:

![image](https://cloud.githubusercontent.com/assets/8440255/25096606/f85fd840-236e-11e7-8214-52f86966c738.png)

**Comment by chris206** [comment]
Ok, so fedex works great. People are going to flip

If you could just summarize the failures to something that doesnt take up so much space,
like: "41514 Failed - Postal State Mismatch"

**Comment by bradatkins** [comment]
I've added the order #'s of the ones that have no Amadeus info yet:

![image](https://cloud.githubusercontent.com/assets/8440255/25096815/e94adb06-236f-11e7-80d5-8e4413efbfee.png)

**Comment by bradatkins** [comment]
This is the best I could shrink the FedEx stuff down to, hope it helps:

![image](https://cloud.githubusercontent.com/assets/8440255/25097041/da9c3acc-2370-11e7-971c-8e767ecd4624.png)

**Comment by chris206** [comment]
yes - we are solid here - looks great works great. Thank you so much

I will open new requests for glitches
