### ISSUE TITLE
Add "/P" to each specific input in Amadeus Code

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1572]
![image](https://cloud.githubusercontent.com/assets/22382144/19318056/1efe6260-9075-11e6-892c-42ae8a7d1476.png)

This is still generating in the old format

It should now have the "/p" after each unique input:

SR*DOCSYYHK1-P-US-436705957-US-25APR40-M-29JAN18-BUDDE-KATHLYN-GRACE/p;RM 425269/p;FFN DL-2147218404/p

**Comment by bradatkins** [comment]
Check now:

SR*DOCSYYHK1-P-US-436705957-US-25APR40-M-29JAN18-BUDDE-KATHLYN-GRACE/p;RM 425269/p;FFN DL-2147218404/P

**Comment by chris206** [comment]
really great - thank you
