### ISSUE TITLE
Add "KnownTraveler/Global Entry" to Amadeus Code

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1573]
SR*DOCOYYHK1--K-TTXXXXXXXXXXXXXX/P

(the x's represent the number in the known traveler/global entry box in the reservation)

they would need to be added to the code after the preceeding "/p"  by using a **;**  
 just like everything else

**Comment by bradatkins** [comment]
It's done, just not 100% sure it's in the right spot or not:

SR*DOCSYYHK1-P-US-513002829-US-09MAY39-F-04MAR24-INGHILTERRA-MARY-CATHERINE-K-tt11fzf1v/p;RM 419832/P

**Comment by chris206** [comment]
Hey Brad - it actually would need to read as follows:
(black is the constant, red is the variable)
![image](https://cloud.githubusercontent.com/assets/22382144/21195518/197a45c0-c202-11e6-94f8-686a3b16bc21.png)

Here is a picture of a test booking, followed by the line input (with passenger number manually applied), followed by verification of success

![image](https://cloud.githubusercontent.com/assets/22382144/21195562/485fdf80-c202-11e6-9244-b5a56a6c7e9f.png)

I know what you were trying to do, because the SR*DOCSYYHK1- is the same, but I have tried to integrate them in different formats - but the only one that works is the one verified

**Comment by bradatkins** [comment]
OK have a look:

SR*DOCSYYHK1-P-US-513002829-US-09MAY39-F-04MAR24-INGHILTERRA-MARY-CATHERINE/p;RM
419832/p;SR*DOCOYYHK1--K-TT11FZF1V/P

**Comment by chris206** [comment]
looks and works amazingly.
