### ISSUE TITLE
Gift Certificate Process Streamlined & Automated (Patrick)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1580]
**Problem:**
We are currently handwriting gift certificates which is crazy - this deters clients from purchasing and is tremendously time consuming on our end.

**Desired Solution:**
We would like to automate and simplify this process on the client and agent side- similar to the way [Abercrombie and Kent ](https://www.abercrombiekent.com/travel_gifts/)does it. We would like to be able to set the expiration period with a universal default as per terms(TBD) BUT with individual order override if needed.

**Possible Mechanics of Solution:**
- System would generate a number that would be recognized automatically upon redemption
- System would generate an invoice for giver's records
- System would generate a printable gift certificate for recipient

Information could be extremely brief - an abbreviated order process that hid all fields other than billing info and First & Last name of recipients

The transfer could be done on our end in "Edit Order" - where it would be defaulted as "gift card" (a new drop down option)

![image](https://cloud.githubusercontent.com/assets/22382144/19398154/3faa6464-9219-11e6-9b2d-9a350dabd6fb.png)

Changing it to "New Request" could open up all other fields like a normal order, and the "Change Tour" featured could be used to migrate it over. - just an idea***\* you know possibilities and limitations better than we do!

**Comment by bradatkins** [comment]
I think we completed this already?

**Comment by bradatkins** [comment]
http://www.206tours.com/gift/index.htm

**Comment by chris206** [comment]
Beautiful! I have no idea if it works, but it looks really great

**Comment by chris206** [comment]
Is there a way to notify us in "All Orders"? Also, in "incomplete orders" in case of a glitch?
Even though it doesn't generate an order number (some number would be a good idea, even randomly assigned), it would be helpful for it to be searchable and correctable.

Did we make the decision to limit payment to credit cards?

Also - how can I process a test? Where would it show up?

**Comment by bradatkins** [comment]
It creates a record here:

https://www.206tours.com/register/admin/listdata.php?FORM=Promotions

It is only limited to credit cards

You can test it here:

https://www.206tours.com/gift

**Comment by chris206** [comment]
"The Credit Card Number supplied in the authorization request appears to be invalid."

How do I complete it without a credit card?

**Comment by bradatkins** [comment]
You can't, it's no longer in test mode, but you can do a gift card for
$0.01, keep in mind there a processing costs

If you want, touch base with Ronen as he was involved in the testing too
