### ISSUE TITLE
.php form access - gift certificate - urgent please (SANDY)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1582]
Hi Brad,

Where can I access this form? Can you duplicate it for a gift certificate page - so I can use it for this page:
http://www.206tours.com/gift

We need it soon for Christmas etc..
We want to make it similar to this page:
www.abercrombiekent.com/travel_gifts

![image](https://cloud.githubusercontent.com/assets/10079829/19442634/f8e58ff4-9457-11e6-80cc-0d447490390d.png)

![image](https://cloud.githubusercontent.com/assets/10079829/19442673/27a68780-9458-11e6-908f-a1e9637dbd64.png)

**Comment by bradatkins** [comment]
This is done
