### ISSUE TITLE
Paypal pmnt made - no email received

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1584]
But it's showing in DB

![image](https://cloud.githubusercontent.com/assets/8440903/19484410/8324ec82-9525-11e6-94d9-6d26aa314d7c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19484357/57881a68-9525-11e6-9207-f06cd1ac1369.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19484384/6dc50714-9525-11e6-8c2b-08b98cd38852.png)

**Comment by bradatkins** [comment]
I see it in your email inbox a 6:55??

And I see it in my logs:

![image](https://cloud.githubusercontent.com/assets/8440255/20735969/9a7965b2-b671-11e6-9ffb-3c1a7722cd1e.png)

**Comment by ali206** [comment]
No i meant no email from paypal - i guess not a DB issue then.  We got it eventually if i remember correctly but like a day later, it was odd.
