### ISSUE TITLE
broken account & order 425720 (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1587]
This account is broken. I've tried everything I could think of twice

![sammieerror](https://cloud.githubusercontent.com/assets/22382144/19574534/da466888-96d8-11e6-8818-59df48a688d7.jpg)

Client is unable to log in to account with email, password or even order number

**Comment by chris206** [comment]
any ideas on this?

**Comment by bradatkins** [comment]
The actual traveler associated to this order is:

![image](https://cloud.githubusercontent.com/assets/8440255/19826693/8cf4733a-9d5f-11e6-9cd2-8002aad9e70c.png)

**Comment by chris206** [comment]
Yep - why are we unable to log into her "my account" using email, password or even order number?

at one point it was coming up with wrong client contact info

**Comment by chris206** [comment]
Hi Brad- clients needs update and is getting worried because she has no access to her info

**Comment by bradatkins** [comment]
Who's the correct traveler from the "All Travelers" section?

**Comment by chris206** [comment]
Clotilde

**Comment by bradatkins** [comment]
Try now

**Comment by chris206** [comment]
Ahh! My fault

wrong invoice - the correct invoice is 425720!! this is the problem one

**Comment by bradatkins** [comment]
Yes, undone.

Seems to be OK?

![image](https://cloud.githubusercontent.com/assets/8440255/19984531/3698a648-a1e5-11e6-94d2-fe7883b05a52.png)

**Comment by chris206** [comment]
So the client was apparently still unable to log-in and was having other issues (related to fact that her order number was no longer associated to her account - so we transferred her info over to a new account and new order number to start over. That new order is: **425946**

She is now letting us know that she can log in, but she is irritated by the fact that - although her information is right in her account and on her invoice - whenever she tries to changer her address online - it changes "Maine" to "Alaska" without any input.

Minor glitch - but annoying enough that it could cause other clients to not see it and update the wrong state. I've sent the video to you via email
