### ISSUE TITLE
Mike Milano - # 422065

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1588]
i applied a discount from 206 for $300 and it shows correctly on invoice but on recap says Mike Milano but it should be 206 Tours.

Also is not deducting  from the recap it should be $619 over payment. 

![image](https://cloud.githubusercontent.com/assets/14838466/19655179/1993b9ba-99e9-11e6-9fb6-3bd3f2da8ba3.png)

![image](https://cloud.githubusercontent.com/assets/14838466/19655203/2eb1779c-99e9-11e6-812f-674278381a02.png)

**Comment by bradatkins** [comment]
Fixed
