### ISSUE TITLE
Subjects of emails need to be corrected

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#159]
I know this is a previous issue but i'm starting it over again - Subjects of Sales emails need to be corrected.

When someone makes a payment on their existing order, the invoice does not automatically get sent to the client.  So we manually email it to the client via the DB. That subject of that email SHOULD NOT say Pilgrimage Confirmation & Invoice (because they've already been confirmed).  It should say Payment Confirmation or "Thank you for your payment on order #000000" 
Ex:
![image](https://cloud.githubusercontent.com/assets/8440903/5863806/31c56ada-a24a-11e4-9e2b-fb11314e4393.png)

When someone simply updates a birth date or passport #, the subject of the email SHOULD NOT say Pilgrimage Confirmation & Invoice (b/c that was already done when registered).  It should instead go back to saying "Updated Invoice".
Ex:
![image](https://cloud.githubusercontent.com/assets/8440903/5863844/8d6830b6-a24a-11e4-8ec1-2b48c5afbe01.png)

**Comment by bradatkins** [comment]
Please touch base with Ronen, as I believe he's working on this with
Milanka.

**Comment by ali206** [comment]
Milanka is not working with Ronen on this i just checked.

**Comment by bradatkins** [comment]
I think this one is pretty much done now
