### ISSUE TITLE
Payment confirmation emails to clients - 425615

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1591]
Are not showing the payment made on the invoice attached to the email:

![image](https://cloud.githubusercontent.com/assets/8440903/19655960/d8077ec0-99eb-11e6-83e4-3f80268bb0a5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19655969/e1876618-99eb-11e6-941a-9970e01a79b9.png)

![image](https://cloud.githubusercontent.com/assets/8440903/19655975/e8989f9e-99eb-11e6-82f8-82f21a259ffd.png)

Other examples:
425713
425637

**Comment by bradatkins** [comment]
Fixed
