### ISSUE TITLE
DB error | no drop down for dept city (stef)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1594]
C776f7b27972483c38d0b7bbf662462 

![image](https://cloud.githubusercontent.com/assets/10079829/19699526/a9485790-9ac1-11e6-973f-16a8d0015535.png)

**Comment by bradatkins** [comment]
Can you try again and record your session using Mozilla

**Comment by ronenreinheimer** [comment]
i am sending you an email with the recording

**Comment by ronenreinheimer** [comment]
Stefanie -

Can you please make your recording from the start of the process?

Thanks,
Brad

**Comment by ronenreinheimer** [comment]
Oh OK. Then the message directed at you :)

**Comment by bradatkins** [comment]
Fixed.
