### ISSUE TITLE
Who emails are being sent to

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#160]
When we click the email button in the DB, instead of having all emails go to sales@206tours.com, can each invoice be sent to the person in our office who is in charge of that group?

For ex:
This only needs to be sent to Amanda & accounting@206tours.com, not the whole office
![image](https://cloud.githubusercontent.com/assets/8440903/5863916/545393c8-a24b-11e4-86c9-51daf0f79d00.png)

For series tours #1-208 they would all need to only go to rok@206tours.com & accounting@206tours.com

When we link an agent in our office to a specific group, can that how the DB will know where to send emails?  And if no agent is selected then default to sales@206tours i guess?

**Comment by bradatkins** [comment]
So just to confirm:

- For Tours 1-208 will bcc rok@206tours.com instead of orders@206tours.com
- For all other tours, the DB will lookup the "Account Manager" and Bcc them
Inline image 1
![image](https://cloud.githubusercontent.com/assets/8440255/7826922/a5871daa-03ee-11e5-8a93-8229890b0e03.png)

- If there is no account manager the DB will Bcc orders@206tours.com

**Comment by bradatkins** [comment]
Sandra: I feel that all should still be sent to orders but CC the account manager into it.

Bcc accounting too

**Comment by ali206** [comment]
no need to bcc accounting, i get orders emails

**Comment by bradatkins** [comment]
OK :)

**Comment by bradatkins** [comment]
This is now complete. The DB will 

- Bcc orders@206tours.com
- CC rok@206tours.com for tours #1-208
- CC the selected account manager(s) for any other tours

Someone will need to goto each tour and select the appropriate account manager(s)

![image](https://cloud.githubusercontent.com/assets/8440255/7851165/86f4376c-04b9-11e5-9013-a82e2ca675fe.png)

**Comment by ali206** [comment]
this is working, woo!
