### ISSUE TITLE
FW: New Groups Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1600]
Hi Brad,

I pretty much finished to configure this page: www.206tours.com/groups/organize-group-brad.htm
1.  Can you please configure the form
2.  The search bar is not working:

![image](https://cloud.githubusercontent.com/assets/10079829/19741726/daf63efa-9b8f-11e6-8758-1c278b965e96.png)
1.  The top promo section is also not working:

![image](https://cloud.githubusercontent.com/assets/10079829/19741720/d22e0492-9b8f-11e6-9105-b66418b7e488.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
it worked! ty!
