### ISSUE TITLE
RE: Passport expiration update (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1603]
![image](https://cloud.githubusercontent.com/assets/10079829/19815102/5048c1ca-9d0f-11e6-9a0e-5988ecf0a53d.png)

**Comment by bradatkins** [comment]
Should be good now

![image](https://cloud.githubusercontent.com/assets/8440255/20246322/97a4b144-a982-11e6-9be6-f92c0506fab0.png)


![image](https://cloud.githubusercontent.com/assets/8440255/20246320/8df73b80-a982-11e6-8ff1-c3fc2ced384d.png)

**Comment by chris206** [comment]
Also, can you make it so that the passport expiration date column appears directly after the departure date, followed by the specific  passenger column?

As of right now we need to scroll across 3 screens for all of that info

**Comment by bradatkins** [comment]
Please create a separate issue for this. It's confusing the extra comments when it's unrelated
