### ISSUE TITLE
Database email issues (Bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1614]
![image](https://cloud.githubusercontent.com/assets/10079829/19947102/f93039ba-a11c-11e6-8723-868cb042b39d.png)

**Comment by bradatkins** [comment]
Hmm I just tried it myself, and it seemed to work OK..

Let's keep an eye out if this is just a fluke or not

![image](https://cloud.githubusercontent.com/assets/8440255/20246047/8915691c-a97c-11e6-98e0-ec3dffcd05db.png)
