### ISSUE TITLE
DB | Incorrect post tour return date | Tour VVS052517 | Booking 425901 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1615]
![image](https://cloud.githubusercontent.com/assets/10079829/19967012/cb086d22-a1a4-11e6-89d1-123365b95b98.png)

**Comment by bradatkins** [comment]
Fixed the bug.

You can fix the orders using this option in the edit order screen:

![image](https://cloud.githubusercontent.com/assets/8440255/19989974/7dae725e-a200-11e6-8acb-e46ed1dee438.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/20110564/e4ea573e-a5b2-11e6-8f21-d35f70ff4a0d.png)

**Comment by bradatkins** [comment]
Doesn't look like the return date was over ridden? I just tried it and it worked OK

![image](https://cloud.githubusercontent.com/assets/8440255/20246350/0571f39e-a983-11e6-9d59-9552725137b4.png)
