### ISSUE TITLE
Add to Github: Database no longer Generates Fed Ex Labels (patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1618]
![image](https://cloud.githubusercontent.com/assets/10079829/19973197/e8b42800-a1ba-11e6-9dd5-71d2dba12899.png)

**Comment by bradatkins** [comment]
Patrick - the error seems obvious. The zip code and state don't belong to each other, so there's a wrong piece of info there.
 
That zip code belongs to OH

![image](https://cloud.githubusercontent.com/assets/8440255/19989688/a1e01d78-a1fe-11e6-9c8e-953e2f0bb17a.png)
