### ISSUE TITLE
Pre Post 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#162]
From: Rinda Kanidinc 
Sent: Monday, December 15, 2014 11:05 AM
To: 'Brad Atkins'
Cc: Sandra Lippold; Milanka Lachman
Subject: : Pre and Post night + transfer options

Hi Brad,

The pre / post night option needs to be listed as per person  ( not per room) 

Please do not hesitate to contact me with any additional questions.

Wishing you a Blessed Advent. 

Rinda Kanidinc 
Tour Series Director
206 Tours Inc.
206Tours.com 

Tel: 800.206.8687   |   631.361.4644  ext. 115   |   Fax: 631.361.3682
rinda@206Tours.com   |   Skype: rinda-206tours

```
     client letters
```

From: Rinda Kanidinc 
Sent: Monday, December 15, 2014 11:03 AM
To: Ronen Reinheimer
Cc: Sandra Lippold; Milanka Lachman
Subject: RE: Revision : Pre and Post night + transfer options

Hi Ronen,

Prices I send you are per person – not per room

Please do not hesitate to contact me with any additional questions.

Wishing you a Blessed Advent. 

Rinda Kanidinc 
Tour Series Director
206 Tours Inc.
206Tours.com 

Tel: 800.206.8687   |   631.361.4644  ext. 115   |   Fax: 631.361.3682
rinda@206Tours.com   |   Skype: rinda-206tours

```
     client letters
```

From: Ronen Reinheimer 
Sent: Monday, December 15, 2014 10:54 AM
To: Rinda Kanidinc
Cc: Sandra Lippold; Milanka Lachman
Subject: RE: Revision : Pre and Post night + transfer options
Importance: High

Hi Rinda,

How does this look?

Wishing you a Blessed Advent!

---

Ronen Reinheimer 
Art Director
206Tours.com 

From: Rinda Kanidinc 
Sent: Thursday, December 11, 2014 2:19 PM
To: Ronen Reinheimer
Subject: Revision : Pre and Post night + transfer options

TEL AVIV : 
Pre night:            $155 pp  (dble)     // $289 ( Sgle) 

Transfer arrival :  $78  pp 
Transfer departure:  $78 pp 

JERUSALEM :
Post night :         $119 pp ( dble)    // $206 ( Sgle) 

Transfer arrival:  $78  pp 
Transfer departure: $78 pp

AMMAN:
Pre night:            $85 pp  (dble)     // $149 ( Sgle)

Transfer arrival:  $78  pp 
Transfer departure: $78 pp 

LISBON : 
Pre night:          $96 pp  (dble)     // $177 ( Sgle) 

Transfer arrival: $ 49 pp

LOURDES: 
Pre night:          $139 pp  (dble)     // $248  ( Sgle) 
Post night :          $139 pp  (dble)     // $248  ( Sgle)

Transfer arrival Pau airport :  $95 pp      Please note : specify airport to be PAU as there is multiple airports to depart from 
Transfer departure Pau airport : $95 pp 

PARIS: 
Pre night :          $175pp  (dble)     // $350   ( Sgle)
Post night :          $175pp  (dble)     // $350   ( Sgle)

Transfer Arrival  Paris , CDG airport :  $105 pp Please note : specify airport to be Paris, CDG  as there is multiple airports to depart from
Transfer departure Paris , CDG airport :  $105 pp 

More to follow 

Please do not hesitate to contact me with any additional questions.

Wishing you a Blessed Advent. 

Rinda Kanidinc 
Tour Series Director
206 Tours Inc.
206Tours.com 

Tel: 800.206.8687   |   631.361.4644  ext. 115   |   Fax: 631.361.3682
rinda@206Tours.com   |   Skype: rinda-206tours

```
     client letters
```

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/5888065/8fcf5f62-a3be-11e4-885a-9b8ccec9b40f.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Thank you for looking into this issue. I showed the update to Rinda - it still needs some refinement. Basically, nothing should we labeled as 'Per Room' please mark everything as 'Per Person'.

![image](https://cloud.githubusercontent.com/assets/10079829/5941724/d6a04512-a6e0-11e4-9a05-4ad27d055842.png)

**Comment by bradatkins** [comment]
Ok will do

**Comment by ronenreinheimer** [comment]
Thank you Brad.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Thank you Brad!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ali206** [comment]
Hi Brad, 
We're going to change pre/post tours up a bit - too much wording and can be much simpler as per image below.  Whatever is crossed out in red can be removed.

![pre post tours](https://cloud.githubusercontent.com/assets/8440903/6022819/9fd8e172-ab8d-11e4-9fb5-fdf74a914e7b.png)
