### ISSUE TITLE
promo codes -kicked out- urgent

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1622]
Hi Brad, 
Is there is any way you can fix all promo codes that got kicked out ,without messing the booking I already readjusted. I have been going through for the past 2 days, and adjusting manually and its taking forever because apparently its so many of them. 

FYI- all different codes not just one
vip codes,joy,christmas,lent,mothersday,birthday....etc 

Thank you !

**Comment by bradatkins** [comment]
Unfortunately not.

**Comment by ali206** [comment]
Ok then moving forward can you prevent promo codes from being kicked out after they expire? It was working until recently.  It's a lot of extra work for Irena.

**Comment by bradatkins** [comment]
What do you mean by kicked out?? Maybe I'm misunderstanding

**Comment by ali206** [comment]
kicked out being that a promo code was applied to a dept in April, and now looking back on the invoice it looks like the client owes us $200.

**Comment by bradatkins** [comment]
Is this still an issue? Can you do a test:

1) Create a promo code that expires Dec 31st
2) Log an order with that promo code
3) Change the promo code to have an end date of Oct 1st

This would simulate the problem. I thought I fixed this. Obviously orders
that this had a problem on will need to be manually fixed, but I want to
know if the issue still exists.

**Comment by Irena206** [comment]
OK, I just created a test promo code  , and this is what came out "as a zaro" 


![image](https://cloud.githubusercontent.com/assets/14838466/20015159/91f8b2b6-a290-11e6-9eae-be0a620dd89c.png)


![image](https://cloud.githubusercontent.com/assets/14838466/20015176/a0cb9e3e-a290-11e6-98c2-2a627dbf8cb7.png)

**Comment by Irena206** [comment]
OK, please see below, I just did a test. It came out as zero !
I still cant believe that I have to adjust every single invoice manually, so I really hope we can prevent this for happening in a future. 


![image](https://cloud.githubusercontent.com/assets/14838466/20015202/e03611b2-a290-11e6-802e-b28b8c1fae65.png)


![image](https://cloud.githubusercontent.com/assets/14838466/20015196/d1ec8a00-a290-11e6-8524-d52e99a4df1b.png)

**Comment by bradatkins** [comment]
because your promo code start date is in the Future. Put the promo code
start date as Oct 1st and put your End date as Dec 31st. Then place your
order, then go and change the End Date to be Oct 31st.

**Comment by Irena206** [comment]
fixing now

**Comment by ali206** [comment]
adjusted dates as per above 10/1-11/4, promo code applied correctly.  changed end date to 10/31, updated booking, promo code disappeared.

![image](https://cloud.githubusercontent.com/assets/8440903/20015534/36e2f768-a292-11e6-8f67-afe92e2b7d22.png)

![image](https://cloud.githubusercontent.com/assets/8440903/20015523/2ed7e61e-a292-11e6-9e50-c4b0907f8b24.png)

**Comment by bradatkins** [comment]
Fixed.

**Comment by Irena206** [comment]
Hi Brad,
OK so this keeps happening, we have to work on this and prevent of happening in future.
This particular promo code is - LAUNCH16 
Client made final payment and promo code got bumped out -see below.
Im going to apply manually and fix it.

![image](https://cloud.githubusercontent.com/assets/14838466/20570610/4f7bec64-b172-11e6-93fb-bb77954d5e27.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20570630/64dba932-b172-11e6-9af9-ee7a87766bb0.png)

**Comment by bradatkins** [comment]
Ohh ok. This is the client making the final payment. Previously it was 206 Tours making an edit. Let me check

**Comment by bradatkins** [comment]
This is fixed.
