### ISSUE TITLE
Booking Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1623]
Can you please change it to read:
**Select your currency**

and button to:
**BOOK NOW**

![image](https://cloud.githubusercontent.com/assets/10079829/20011661/c9fa0d12-a282-11e6-80b0-1c2e6ba44805.png)

thank you!

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/20030296/93209ec6-a338-11e6-8a07-275b587726ff.png)
