### ISSUE TITLE
Installment Issue - client not registered

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1626]
She's under All Travelers but not registered in the DB but somehow has 2 installments set up:

![image](https://cloud.githubusercontent.com/assets/8440903/20068337/5473d77e-a4e6-11e6-93f3-8ec252e484cd.png)

![image](https://cloud.githubusercontent.com/assets/8440903/20068354/683f2bf0-a4e6-11e6-8e46-7334810aafc5.png)

**Comment by bradatkins** [comment]
This is an odd one here. Not exactly sure what happened here.

I've rebuilt the order as best as I could: #426025 but you may want to contact her and replace the order
