### ISSUE TITLE
Land Only clients being shown Air/Land dates on invoice

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1631]
Hi Brad,

Recent changes have altered the invoices of our Land Only clients

ALL TOURS (except for Mexico and Canada Tours) SHOULD have an air/land departure date that is 1 day prior to arrival. Land Only clients tour should start the day after people leave the US.

Mexico & Canada are unique, in that the air/land as well as land only dates are the same. This is now working.

Currently - ALL Tours are showing land only clients as having the same start date as land only clients. This is no longer working Here is an example:

![image](https://cloud.githubusercontent.com/assets/22382144/20073779/9991fae2-a4fb-11e6-8715-8a2c5bfe32bc.png)

**Comment by bradatkins** [comment]
K, that was confusing, can you try and reword, preferrably breaking it down with examples.

**Comment by chris206** [comment]
Ok. Sorry

1. If im going to Mexico or Canada, I take a flight from NY on Dec 15, arrive mexico or Canada Dec 15.
    If I'm going to mexico or canada and handling my own air (land only) my tour begins Dec 15th

2. If I'm going to Europe, I take a flight from NY on Dec 15, arrive Europe Dec 16
    If I'm going to Europe and handling my own air (land only) my tour begins on Dec 16th

Invoices need to reflect this. The image in the topic illustrates that the client is traveling land only BUT is being shown that their trip starts the day before the tour begins. It should say Sept 25th

**Comment by bradatkins** [comment]
Fixed I believe. If you find that's not the case please provide example order numbers

**Comment by chris206** [comment]
ok great - seems to be good.

Thanks
