### ISSUE TITLE
#425899 -question 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1634]
Hi Brad, 
Is there any chance you can change only for this particular invoice on form of payment section-instead of CC to say-GRANT , or if not just to remove where says credit card??

Thank you, 
![image](https://cloud.githubusercontent.com/assets/14838466/20117944/b63f2932-a5d0-11e6-9cee-1fc906158118.png)

**Comment by bradatkins** [comment]
Unfortunately I can't do one of's on a particular invoice...

**Comment by Irena206** [comment]
Thank you !!!
