### ISSUE TITLE
Canadian Pilgrims Showing CAD package prices, USD additions

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1636]
Kind of confusing. Maybe we can just add a USD after the $ sign on our HTML end

![image](https://cloud.githubusercontent.com/assets/22382144/20152007/6fdf4c8c-a68a-11e6-82a4-6a2d5b500420.png)

**Comment by bradatkins** [comment]
Are those hard coded options?

**Comment by chris206** [comment]
They are not DB driven. I think on the old site they just need to specifically be listed as "USD", because it is odd to show CAD tour prices and assume that other prices are in USD, unless specifically mentoned.

This is more of a Ronen thing, right?

**Comment by bradatkins** [comment]
Yes, a Ronen thing.
