### ISSUE TITLE
GC questions

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1639]
So if someone registers themselves they will have their own promo code that they can apply and it’s automatically approved and shows as a payment?

Does that mean the deposit/insurance mandatory payment will no longer be mandatory if paying with a GC?

So lets say a GC is issued on 11/10/16, but isn’t claimed until 2/10/17, what date is it going to show up under in payments section?

If they use that GC for insurance purposes i'm just wondering how accounting is going to know accurately when a "payment" was posted

**Comment by bradatkins** [comment]
The gift card can only be used when placing the Order.

**Comment by ali206** [comment]
Ok i'm confused sorry...

If it can only be used when placing the order then why is it sitting in DB payments section without an Order #?  Wouldn't it only show up once - when the order is placed?

Can you answer my first 2 questions though still please?

**Comment by bradatkins** [comment]
Remember, a person (Sender) buys a gift card for someone else (Recipient). So...

1) So if someone registers themselves they will have their own promo code that they can apply and it’s automatically approved and shows as a payment?

Sender will buy a gift card for Recipient.  The gift card will show up in the payment section as a gift card with no order id:

![image](https://cloud.githubusercontent.com/assets/8440255/20191838/34d13c56-a755-11e6-9b5e-6b34e5150243.png)

When Recipient goes to place an order, they will redeem the gift card and it will show up in payments as a payment with an order id

![image](https://cloud.githubusercontent.com/assets/8440255/20191852/4426ff42-a755-11e6-9af0-cf74f0f41dbb.png)

2) Does that mean the deposit/insurance mandatory payment will no longer be mandatory if paying with a GC?

This is still currently mandatory.

**Comment by ali206** [comment]
Ok so they'd be applying let's say a $500 GC plus $580 deposit, ok. 


So this still remains a question as well:

So lets say a GC is issued on 11/10/16, but isn’t claimed until 2/10/17, what date is it going to show up with under the payments section?

**Comment by bradatkins** [comment]
2/10/17

**Comment by ali206** [comment]
Ok thanks.

**Comment by ali206** [comment]
Sorry, few more. 

The person who is receiving the GC, they'll know how much the GC is for I guess? 

How are they receiving their promo code?

What if GC is for full amount of trip, will the DB still require them to make a deposit?

**Comment by bradatkins** [comment]
Yes, the receiver knows:

![image](https://cloud.githubusercontent.com/assets/8440255/20194369/02269980-a760-11e6-97a4-18d1f574f86d.png)

It won't require a deposit if the gift cert is for the full amount.

**Comment by ali206** [comment]
Ok thank you! I have been in the dark with this and finally just got to your email so had a million questions of course
