### ISSUE TITLE
Pending payments section - orders without names 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1640]
HI Brad, can you please remove this from page 4 ?

![image](https://cloud.githubusercontent.com/assets/14838466/20196682/cf4cc566-a769-11e6-911f-67adfef332a3.png)

**Comment by bradatkins** [comment]
How did you get to this? I don't see these

**Comment by Irena206** [comment]
Its on page 4, 5 at this moment, and it has been there since 2012,2013,2014 . 

Pending payments, page 4,-5
