### ISSUE TITLE
New Order Process - CC button doesnt expand CCinfo , so you cant charge clients

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1641]
CC button doesn't expand CC info (there is nowhere to input card or address info) , so you cant charge clients on new booking.

It has happened on both bookings i've made today, both from new client an existing client (i controlled for that factor)

![image](https://cloud.githubusercontent.com/assets/22382144/20277425/7ee724ba-aa6e-11e6-9d89-ccd0736c98d3.png)

7ee724ba-aa6e-11e6-9d89-ccd0736c98d3

**Comment by bradatkins** [comment]
Can you please record this in Mozilla? Thanks.

**Comment by chris206** [comment]
This is the same one as I just posted in liz's issue.

I haven't been able to get the typable prompt creating ANY reservations at all

[CC fails to prompt for CC info.pdf](https://github.com/206Tours/DB/files/595810/CC.fails.to.prompt.for.CC.info.pdf)
