### ISSUE TITLE
Add to Github: Credit Card Payment info Not opening (patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1643]
![image](https://cloud.githubusercontent.com/assets/10079829/20284627/eb036b82-aa8b-11e6-837e-088189358769.png)

**Comment by bradatkins** [comment]
Recording  from mozzilla?

**Comment by ali206** [comment]
Liz has a problem with this as well when trying to register new clients and pay with CC - she uses Chrome
