### ISSUE TITLE
#426033-  Apply a payment section (button ) not working 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1645]
HI Brad, 
From apply a payment button  Im not able to apply discount, is not reflecting, just brings me to the blank screen. Please see below steps. Thanks, 

![image](https://cloud.githubusercontent.com/assets/14838466/20317687/1746c708-ab35-11e6-918e-61e573c3e4b2.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20317574/a0ff5eca-ab34-11e6-85a4-21e3acfc4e62.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20317596/b3347b5c-ab34-11e6-9eff-faf3a2019833.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20317611/c4ea9bd8-ab34-11e6-98e2-3bc2ce95ba40.png)

**Comment by bradatkins** [comment]
Try now

**Comment by Irena206** [comment]
Its good now. Thanks !
