### ISSUE TITLE
DB | Travel ins and ext cxl premiums | VVS052517

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1647]
![image](https://cloud.githubusercontent.com/assets/10079829/20322710/143e3ab0-ab48-11e6-9c99-580e1dc87656.png)

**Comment by bradatkins** [comment]
Can you record your session in Mozilla, as I did it and it seems to be OK?

![image](https://cloud.githubusercontent.com/assets/8440255/20323597/770b02ce-ab4b-11e6-8379-b3075d35b6c6.png)
