### ISSUE TITLE
Registering/confirming not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1649]
![image](https://cloud.githubusercontent.com/assets/8440903/20349424/6656d68c-abd8-11e6-9ced-a9d45b99a1ff.png)

We still have quite a few clients having issues registering/confirming trips. 

This guy clicked confirm, nothing happened and he waited 10 mins. 

If there is something wrong, or the tour is sold out etc, there should be an error message that pops up for the client so they know what's going on

**Comment by bradatkins** [comment]
This could be related to the BigDrop required fields that we are waiting for. I just did a test order on this tour and it worked fine.

**Comment by chris206** [comment]
Milanka referenced the need for an "auto-reply". I've outlined the template in another GH
Incomplete Order - Email to Client (Sandy) #1693
