### ISSUE TITLE
Add blue sheet icon to confirmation page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#165]
From: Yaritza Rodriguez 
Sent: Wednesday, November 05, 2014 1:33 PM
To: Ali Boulanger (ali@206tours.com); Sandra Lippold
Subject: Email to Brad

Can you please add the “blue sheet”   icon to the booking confirmation page. This way we can just print it out from this very same page. I am not sure if you are aware, but blue sheets is how we print out each order. We print them in blue sheet and that’s why it’s called that.

**Comment by bradatkins** [comment]
There is now a link to the blue sheet on the confirmation page

**Comment by ali206** [comment]
Can this be an icon and not a link?

The bottom of this confirmation page (which clients see) looks messy:

![image](https://cloud.githubusercontent.com/assets/8440903/9582823/b240c20c-4fd5-11e5-8983-98fea3e281e5.png)

**Comment by bradatkins** [comment]
The clients will not see this link.

It only shows up for 206 Tours staff. I took that screenshot before
cleaning it up (for some reason) I've added some line breaks and stuff.
