### ISSUE TITLE
FW: WEB - SOLD OUT  vs  BOOK NOW (rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1651]
Hi Brad,

Can you please change the color of the button for SOLD OUT and WAITING LIST?

Try this hex # for waiting list: **#edff34**

Try this hex # for SOLD OUT:  **#f42626**

![image](https://cloud.githubusercontent.com/assets/10079829/20365959/0f2b8148-ac17-11e6-94ea-8759af54857e.png)

**Comment by bradatkins** [comment]
Hey -

I can't figure out their CSS, it's odd. I tried to add a theme-btn nowait and theme-btn wait and i couldn't get it to go. Please ask BD
