### ISSUE TITLE
RE: website error - Australian Dollar conversion | RM070517 (bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1652]
Hi Brad,

Can you please try to put that code back – so the price will correct?
www.pilgrimages.com/frmartello

![image](https://cloud.githubusercontent.com/assets/10079829/20367538/edc39dc2-ac1d-11e6-9226-72d9fa7d2d22.png)

**Comment by bradatkins** [comment]
Added back, pilgrimages.com/frgrady seems OK too

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/20395318/7a09a0d2-acb0-11e6-8f47-f9ab9d111eb9.png)
