### ISSUE TITLE
SUPER VIP CLIENT - need your help ASAP for Milanka

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1658]
Hi Brad,

I am setting up this website and the pre / post tour prices are not showing up (2rd screen shot). I am taking the ID from this section (3rd sceen shot) They are showing in the booking section (4th  screen shot).
www.pilgrimages.com/eastern

here is the code:
![image](https://cloud.githubusercontent.com/assets/10079829/20494836/c463f9ea-afec-11e6-933f-d5003aff4c2a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/20494848/cabd09da-afec-11e6-8307-768069895a80.png)
![image](https://cloud.githubusercontent.com/assets/10079829/20494863/d114db64-afec-11e6-8639-f24f8aeceff4.png)
![image](https://cloud.githubusercontent.com/assets/10079829/20494869/d47a1d6e-afec-11e6-8e11-fcb44f7f1d39.png)

**Comment by bradatkins** [comment]
You are missing this line:

<? $TOUR_INFO = get_tour_info_responsive($TOUR_NUMBER); ?>

Compare it to the index for tour206
