### ISSUE TITLE
Payments Section - load time 84 seconds, way to long

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#166]
It takes FOREVER to decline a payment or do anything in the payments section, did something change?

I declined a payment and this is how long it took:

![image](https://cloud.githubusercontent.com/assets/8440903/6022730/fdcdcafa-ab8c-11e4-8581-b498162d9a50.png)

**Comment by bradatkins** [comment]
it's kinda weird. I checked and it's slow first, then I reload the page and it's fast. It'll take me some time to figure out whether it's the DB or the server.

**Comment by bradatkins** [comment]
Seems to be ok now
