### ISSUE TITLE
#426171 CAD payment is showing as "0"

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1660]
Please fix ASAP we have to send an invoice to the client
Amount  that was charged is CAD 2,813 and is showing as "O" 
![image](https://cloud.githubusercontent.com/assets/14838466/20501073/40009a7c-b006-11e6-9793-54bcef1bb694.png)

**Comment by bradatkins** [comment]
Hey -

I can do that; however, this order seems to be messed up as it's showing a currency conversion rate of $1 CAD = $1 USD?

**Comment by Irena206** [comment]
Hey, yes , please check #1659

**Comment by Irena206** [comment]
Brad , I just charged another payment and I need this invoice correct ASAP.
Thanks,

**Comment by Irena206** [comment]
Hi,

1. The payments applied  are in CAD $, but are only showing on USD invoice.
2.This is the payment that settled from 11/21 in USD $

![brad](https://cloud.githubusercontent.com/assets/14838466/20541317/acbfa0bc-b0ca-11e6-9676-fbe4c7d871ac.png)


3. The payment from today doesn't settled til 6pm , so i dont know the exchange rate yet.

4. We never emailed the client invoice, so that why we need it asap.

**Comment by bradatkins** [comment]
have a look nwo

**Comment by Irena206** [comment]
Hi Brad, so now we had to apply 2 X$150 discount(USD)  , and again is not reflecting it in CAD ("0"), can you please fix ? invoice has to show over payment now I believe 402CAD if we do as per exchange rate from yesterday of 1.34.

**Comment by Irena206** [comment]
Can you check up on this please ?

**Comment by Irena206** [comment]
I really neeeeeed this :)

**Comment by bradatkins** [comment]
Check now
