### ISSUE TITLE
please remove (per person) from appearing on website - Tour Departure Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1663]
Hi Brad,

You did the same thing for our in the ALL OPTIONS section. Can you please do the same for the Tour Departure Section:

Please remove the words (per person) from appearing on the website:

![image](https://cloud.githubusercontent.com/assets/10079829/20502080/873eedb8-b00a-11e6-984d-c05a3a90967d.png)
![image](https://cloud.githubusercontent.com/assets/10079829/20502085/8ae9224e-b00a-11e6-9304-ea6f523adf3b.png)

**Comment by bradatkins** [comment]
You have to remove it from your HTML:

![image](https://cloud.githubusercontent.com/assets/8440255/20505459/324885e2-b01b-11e6-84a7-13bb6909cc9d.png)
