### ISSUE TITLE
#426196 Agent commission -is not reflecting 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1664]
![image](https://cloud.githubusercontent.com/assets/14838466/20530371/2455aed4-b0a1-11e6-82e7-cc0ea273c47d.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20530395/35461ad0-b0a1-11e6-9078-7f0c8e030d64.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20530602/f3d2fef0-b0a1-11e6-8fea-8b679a5da598.png)

**Comment by bradatkins** [comment]
fixed

![image](https://cloud.githubusercontent.com/assets/8440255/20549351/665cb7f2-b0f9-11e6-87c6-08821955d22d.png)
