### ISSUE TITLE
FedEx Label exported wrong person

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#167]
As per Yaritza's email i just fwded you from today:

From: Yaritza Rodriguez 
Sent: Tuesday, February 03, 2015 11:33 AM
To: Ali Boulanger
Subject: Email to Brad

Hi Brad, 

I clicked on the FedEx icon to generate a FedEx label for Jane Cihon. It instead generated a FedEx label for an Elizabeth Martin and a package ended up at the wrong address. When you click on Jane Cihon’s name, it shows her correct address but this isn’t what is reflected in the label.

Can you please fix this?

**Comment by bradatkins** [comment]
Fixed
