### ISSUE TITLE
#425655 update installment payment 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1672]
Hi Brad, 
Is there any way you can update installment payment in DB to show new correct amount-I just updated in Elavon for $545 , 

![image](https://cloud.githubusercontent.com/assets/14838466/20631166/57be57b2-b303-11e6-9ed6-20ccd81e38b4.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20631194/709dac60-b303-11e6-8207-8bfef2982b24.png)

**Comment by bradatkins** [comment]
Done. How come  you had to update it?

**Comment by Irena206** [comment]
Client just change her mind  for amount on payment.


Thanks,
