### ISSUE TITLE
#426227 please reflect correct CAD amount, asap for Milanka

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1673]
Again is not reflecting on customer invoice, please apply as a clergy discount $755.73

![image](https://cloud.githubusercontent.com/assets/14838466/20633549/c6265aee-b315-11e6-8311-ff1a4abf8ff9.png)

**Comment by bradatkins** [comment]
Check now. I don't think I fixed discounts for International currency

**Comment by Irena206** [comment]
Perfect, Thanks !!!!
Yes please we should fix that too, especially when the client is on the phone  and waiting for invoice to revive.,
Thanks !!!

**Comment by bradatkins** [comment]
This is now fixed.
