### ISSUE TITLE
#426254 please remove CRSPAIN17

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1676]
After updating invoice this promo code CRSPAIN17 was applied to invoice ( was not on original invoice), this code does not apply to the tour , so I was asked to be removed. After removing it, on invoice is showing "early" now and Im not sure how to remove it, it bribing me to the blank screen. 

Original invoice:

![image](https://cloud.githubusercontent.com/assets/14838466/20682428/05542d60-b576-11e6-8ee4-feedc3671d76.png)

After updating information(not applying the code): 

![image](https://cloud.githubusercontent.com/assets/14838466/20682636/c3495926-b576-11e6-8fa1-7f1718e8194e.png)

After removing the code -

![image](https://cloud.githubusercontent.com/assets/14838466/20682486/3a5ddbbe-b576-11e6-84aa-62f2af00dcda.png)

**Comment by bradatkins** [comment]
Fixed.
