### ISSUE TITLE
RB041917 - 426178 & 426128  - issues with adding a pax

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1678]
426178 - Elise added Harold/William to 426178 by accident, however I am unable to even cxl him b/c he's not showing up as a passenger.  But he is showing on the invoice and in registered pax.  Please remove him from 426178 and from reg pax.

![image](https://cloud.githubusercontent.com/assets/8440903/20714506/387aadaa-b61a-11e6-87b1-1cc58340db11.png)

![image](https://cloud.githubusercontent.com/assets/8440903/20714509/3eb2cc16-b61a-11e6-8edb-4dd0b9033aa8.png)

![image](https://cloud.githubusercontent.com/assets/8440903/20714540/515c9d56-b61a-11e6-8d45-de43918bc1a0.png)

426128 - Harold/William is supposed to be on this booking, but he's showing up twice on invoice/reg pax but not at all under # of pax in all orders.  Please cxl both of him off of 426128 and remove him from reg pax.

When this is all fixed i'm going to have Elise rebook him.

**Comment by bradatkins** [comment]
Check now
