### ISSUE TITLE
#426292 -Insurance is not  reflecting ? 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1680]
Brad, please take a look, same thing like yesterday. 
Insurance has been selected, but not reflected on invoice. (this time I didnt update the invoice), please investigate. 

![image](https://cloud.githubusercontent.com/assets/14838466/20729008/4fce53c4-b64e-11e6-8b58-d0feb5564eb8.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20729029/66b3803c-b64e-11e6-99f2-a6714d8101ba.png)

**Comment by bradatkins** [comment]
K, I think I fixed it, but I couldn't reproduce it myself so I'm not 100% sure. Keep an eye out for me.
