### ISSUE TITLE
Tour Code: CR041717:Apr 17 not Apr 16 (natasha)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1686]
![image](https://cloud.githubusercontent.com/assets/10079829/20773057/12d355fc-b71e-11e6-8488-ef2fa3096080.png)

**Comment by bradatkins** [comment]
This is because these orders have an Option that is setup incorrectly.

Because this isn't a pre stay it should not have a PRE or a departure / return date.

![image](https://cloud.githubusercontent.com/assets/8440255/20778104/a006a80a-b739-11e6-92fb-ff5ac571394d.png)
