### ISSUE TITLE
FW: Tour 103 Pre/Post/Transfer Costs Project

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1688]
Any idea why the pre tour info is not showing up?

a6ac6d9afd905916a83a5d2a181b56b4

http://www.206tours.com/tour103

![image](https://cloud.githubusercontent.com/assets/10079829/20809609/97dca152-b7d4-11e6-9636-9ec58b428883.png)

![image](https://cloud.githubusercontent.com/assets/10079829/20809614/9c33d3d8-b7d4-11e6-89e5-a2136b58b965.png)

**Comment by bradatkins** [comment]
For whatever reason the Tour # drop down box in the admin screen was showing inactive tours and for the Pre Stay you selected a Tour 103 that was inactive.

I've fixed it

**Comment by ronenreinheimer** [comment]
TY
