### ISSUE TITLE
Replication of Top Navigation for all new BigDrop pages

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1689]
Hi Brad,

Can we setup a .txt or an external .htm file or something that will allow me to update the top nav once and it will apply to all new pages simultaneously? So if I make edits in the future, it will apply to all pages that have the same code. Does this make sense?

            <nav class="top-navigation">
              <ul data-drilldown="" class="top-menu">
                <li><a href="http://www.206tours.com/pilgrimages/index.htm" target="blank">Destinations</a>
                  <ul class="sub-menu">
                    <li><a href="http://www.206tours.com/pilgrimages/index.htm" target="blank"><b>All Pilgrimages</b></a></li>
                    <li><a href="http://www.206tours.com/search/italy" target="blank">Italy</a></li>
                    <li><a href="http://www.206tours.com/search/israel" target="blank">Holy Land</a></li>
                    <li><a href="http://www.206tours.com/search/france" target="blank">France</a></li>
                    <li><a href="http://www.206tours.com/search/spain" target="blank">Spain</a></li>
                    <li><a href="http://www.206tours.com/search/mexico" target="blank">Mexico</a></li>
                    <li><a href="http://www.206tours.com/search/poland" target="blank">Poland</a></li>
                    <li><a href="http://www.206tours.com/search/greece" target="blank">Greece</a></li>
                    <li><a href="http://www.206tours.com/search/ireland" target="blank">Ireland</a></li>
                    <li><a href="http://www.206tours.com/search/combined-countries" target="blank">Combined Countries</a></li>
                  </ul>
                </li>
                <li><a href="http://www.206tours.com/specials/index.htm" target="blank">Special Pilgrimages</a>
                  <ul class="sub-menu">
	   <li><a href="http://www.206tours.com/specials/index.htm" target="blank"><b>Customized Tours</b></a></li>
                    <li><a href="http://www.206tours.com/fatima2017/index.htm" target="blank">Our Lady of Fatima 100th Anniversary</a></li>
                    <li><a href="http://www.pilgrimages.com/frcalloway/index.htm" target="blank">Fr. Calloway Pilgrimages</a></li>
                    <li><a href="http://www.206tours.com/oberammergau/index.htm" target="blank">Oberammergau Passion Play</a></li>
                    <li><a href="http://www.206tours.com/wmof/index.htm" target="blank">World Meeting of Families</a></li>
                    <li><a href="mailto:groups@206tours.com" target="blank">Build a Tour</a></li>
                    <li><a href="http://www.206tours.com/independent" target="blank">Independent Travel</a></li>
                  </ul>
                </li>
                <li><a href="http://www.206tours.com/sitemap/index.htm" target="blank">Information</a>
                  <ul class="sub-menu">
                    <li><a href="http://www.206tours.com/terms" target="blank">Terms & Conditions</a></li>
                    <li><a href="http://www.206tours.com/insurance" target="blank">Insurance</a></li>
                    <li><a href="http://www.206tours.com/cancellationprotection" target="blank">Cancel Protection Plan</a></li>
	    <li><a href="http://www.206tours.com/holidaysale" target="blank">Holiday Sale</a></li>
                    <li><a href="http://www.206tours.com/info" target="blank">Know Before You Go</a></li>
                    <li><a href="http://www.206tours.com/206-tour-2015/index.html" target="blank">Online Brochure</a></li>
                    <li><a href="http://www.206tours.com/international-travellers" target="blank">International Pilgrims</a></li>
                    <li><a href="http://www.206tours.com/airports" target="blank">Airport Directory</a></li>
                    <li><a href="http://www.206viajes.com" target="blank">www.206viajes.com</a></li>
                    <li><a href="http://www.206tours.com/sitemap" target="blank">Site Map</a></li>
                  </ul>
                </li>
                <li><a href="http://www.206tours.com/aboutus/index.htm" target="blank">About us</a>
                  <ul class="sub-menu">
	    <li><a href="http://www.206tours.com/letters" target="blank">Client Letters</a></li>
                    <li><a href="http://www.206tours.com/aboutus/index.htm" target="blank">Employees</a></li>
                   </ul>
                <li><a href="http://www.206tours.com/contact/index.htm" target="blank">Contact Us</a>
                  <ul class="sub-menu">
                    <li><a href="mailto:sales@206tours.com">sales@206tours.com</a></li>
                    <li>1-800-206-8687</li>
                    <li><a href="http://www.206tours.com/skype" target="blank">Skype</a></li>
                    <li><a href="http://www.onlinechatcenters.com/chat/29129-66811?SESSID=buveaotoa7iaip6mrtnbm6fvd6&amp;ref=http%3A%2F%2Fwww.206tours.com"  onclick="window.open(this.href,'targetWindow', 'toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=800, height=450');return false;">Live Chat</a></li>
                    <li><a href="mailto:sales@206tours.com">iSe Habla Espanol</a></li>
                  </ul>
                </li>
                <li><a href="http://www.206tours.com/groups/index.htm" target="blank">Lead a group</a>
                  <ul class="sub-menu">
                    <li><a href="http://www.206tours.com/groups/index.htm" target="blank">Organize a Group</a></li>
                    <li><a href="http://www.206tours.com/promote/index.htm" target="blank">Promote a Group</a></li>
                    <li><a href="mailto:groups@206tours.com">Email us</a></li>
                  </ul>
                </li>
              </ul>
            </nav>

![image](https://cloud.githubusercontent.com/assets/10079829/20811635/74a16724-b7dc-11e6-9b4e-25cbd7e8d4f5.png)

**Comment by bradatkins** [comment]
Done:

[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
n1
