### ISSUE TITLE
How  to mark a client in DB to NOT be part of Email blast ? 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#169]
Hi Brad ,

Quick question if pilgrims receive this email and they would like to be removed off future email  blast is there a feature  in DB that will allow us to mark for them not to receive such emails .

**Comment by bradatkins** [comment]
This is done a while ago:

![image](https://cloud.githubusercontent.com/assets/8440255/7770761/d8a4a96a-005f-11e5-80f9-bb979b5c0d99.png)
