### ISSUE TITLE
#426350 Please remove protection plan $299

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1692]
Hi Brad, so this keeps reflection even though is not selected and I try to update, cancel re cancel and nothing is working, please remove protection plan and update order accordingly. passenger #2 
![image](https://cloud.githubusercontent.com/assets/14838466/20841413/afeab83a-b881-11e6-8578-d5baa9788524.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20841429/c30d9270-b881-11e6-9b93-f53c8a7c1f16.png)

**Comment by bradatkins** [comment]
Fixed
