### ISSUE TITLE
blank departure city in UI

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1694]
Hi Brad,

we noticed that in the drop down menu for all series / specials 

1st gen / 2nd gen UI that the first option doesn't offer a departure city - but has a price - and is selectable by clients. Can you please look into this:

![image](https://cloud.githubusercontent.com/assets/10079829/20849024/c08d8eee-b8a2-11e6-8ed6-4f115ed1cbc5.png)

![image](https://cloud.githubusercontent.com/assets/10079829/20849031/cc1857bc-b8a2-11e6-9473-2d4fbaecab33.png)

![image](https://cloud.githubusercontent.com/assets/10079829/20849034/d15ca412-b8a2-11e6-8a72-f60cc31a1dac.png)

![image](https://cloud.githubusercontent.com/assets/10079829/20849039/d92c2ef6-b8a2-11e6-85df-89e5845befea.png)

**Comment by bradatkins** [comment]
Fixed
