### ISSUE TITLE
3rd passenger overwriting with duplicate info 424837 (Caterina)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1695]
As per Caterina - "On Dec 1st, 

-I  tried adding Arlyn De Leon to Juan’s invoice, but the Database didn’t add her correctly to the invoice.  

-I cancelled Juan but it still shows Arlyn twice (on Order #424837).  

-I then tried to re-register Arlyn and Juan on one registration but it wouldn’t allow me to add another passesenger on the booking page.  

I tried today to register Juan and Arlyn on one new reservation but the Database is not allowing me to.  Please assist!  Thanks"

**Comment by chris206** [comment]
Arlyn was added twice and husband one (3 total)
But only husband is showing up.

Please delete duplicate Arlyn, and ensure that the single instance of arlyn is reflected on blue sheet

![image](https://cloud.githubusercontent.com/assets/22382144/21015786/4200c080-bd31-11e6-9673-2f7fc0b00c0d.png)

![image](https://cloud.githubusercontent.com/assets/22382144/21015711/0e1db6f6-bd31-11e6-91a2-94c466f28ccb.png)

**Comment by chris206** [comment]
Any word on this brad? I cant give you an IDE on it yet, but I am doing a few bookings with it running just in case

**Comment by bradatkins** [comment]
Done
