### ISSUE TITLE
ACH emails not being sent to us

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1697]
424563:

Irena just entered in clients ACH info through the apply payment button, and we did not receive an email

**Comment by bradatkins** [comment]
K. Maybe I'm confused but if you just entered it, why do you need it emailed to you lol ?

**Comment by ali206** [comment]
Because that's how the DB is supposed to work

She was entering it in for another coworker - bc that's how other people in the office let us know when there's an ACH to be processed, but they can't do it that way if the DB isn't working

**Comment by chris206** [comment]
We strive for consistency in record-keeping!

**Comment by bradatkins** [comment]
Did you get this one?

![image](https://cloud.githubusercontent.com/assets/8440255/21036630/519cd7d6-bd95-11e6-967b-5cf9b8ba0cbb.png)

**Comment by ali206** [comment]
yes

**Comment by bradatkins** [comment]
OK s hould be good now!

**Comment by ali206** [comment]
ok great, will let you know if we run in to any problems
