### ISSUE TITLE
RE: DB issue: Filter not working (nat)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1699]
Session ID: 07285da0e96f4db789c0a911ecf5034d

![image](https://cloud.githubusercontent.com/assets/10079829/20896466/e93eba70-baeb-11e6-9dc6-b38da87c2173.png)

**Comment by bradatkins** [comment]
Should be fixed now

**Comment by chris206** [comment]
This has re-broken itself since this morning
![image](https://cloud.githubusercontent.com/assets/22382144/21021720/a5852978-bd47-11e6-89d7-c8f94c987ac0.png)

**Comment by bradatkins** [comment]
Fixed
