### ISSUE TITLE
Search fields not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1701]
i searched by tour code originally which pulled up below:

![image](https://cloud.githubusercontent.com/assets/8440903/20934378/e6ad8080-bba8-11e6-94f8-ddd7e3972d3e.png)

But then when i search by dep date of 12/11/2016 it doesn't pull anything up:

![image](https://cloud.githubusercontent.com/assets/8440903/20934395/f6d13ace-bba8-11e6-8df2-e2dcccc00d57.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
all dates are showing now - it was working this morning though:

![image](https://cloud.githubusercontent.com/assets/8440903/20987979/b80bb52c-bc9c-11e6-9bed-5ad97f0580aa.png)

**Comment by bradatkins** [comment]
Ya I had to disable it temporarily. It's fixed now

**Comment by chris206** [comment]
This has re-broken itself since this morning
![image](https://cloud.githubusercontent.com/assets/22382144/21021705/9c499f38-bd47-11e6-9803-94e211554181.png)

**Comment by bradatkins** [comment]
Fixed
