### ISSUE TITLE
"Blue Sheets" Are missing important internal comments

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1703]
**Problem:**
Currently, no internal comments are showing up on blue sheets. We need them to be

**Background on Blue Sheets:**
We use our "Blue Sheets" in a primitive way; to take internal notes that we review prior to processing orders. They are still important, because there is currently no another way to see all internal comments in a list of important details for each tour. This is a problem, but one that we have not yet thought about. _(probably better if all internal notes were added to a single list like the "yellow sheet" - and associated to each passenger or order)_

**Examples:**
Here are 3 photos of order 426424 to illustrate what the blue sheet is now missing - but this seems to be universal.

![image](https://cloud.githubusercontent.com/assets/22382144/20940323/56d7309c-bbc0-11e6-87b6-907c3e8afda1.png)

![image](https://cloud.githubusercontent.com/assets/22382144/20940482/f7525114-bbc0-11e6-8494-50ae6999109a.png)

![image](https://cloud.githubusercontent.com/assets/22382144/20940496/0269ff7a-bbc1-11e6-8c1f-add0c6f1eb64.png)

**Comment by bradatkins** [comment]
Fixed.
