### ISSUE TITLE
Re-Name "Extended Cancellation" to "Cancel For Any Reason Protection Plan"

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1706]
As per Milanka's instructions, I need to rename every instance of "Extended Cancellation Protection Plan" to:
"Cancel For Any Reason Protection Plan"

https://www.206tours.com/register/payment.php is the main place for the change (in two places). please re-word this section to read:

"Cancel For Any Reason Protection Plan

I would like to purchase the Cancel For Any Reason Protection Plan - $299

*Travel Insurance must be purchased prior to selecting the Cancel For Any Reason Protection Plan
*The prior purchase requirement does not apply to New York Residents. The Cancel For Any Reason Plan can be purchased as a stand-alone protection for New York Residents
*The Cancel For Any Reason Plan must be purchased at the time of booking"

![image](https://cloud.githubusercontent.com/assets/22382144/20973361/5910d1f0-bc66-11e6-892e-34bbc8ba6adb.png)

After selecting the option, it also appears at the summary of selections:
![image](https://cloud.githubusercontent.com/assets/22382144/20973624/4a9eed40-bc67-11e6-92cc-ec0e702b7f96.png)

**Comment by bradatkins** [comment]
Done
