### ISSUE TITLE
#425630 Invoice error in DB 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1708]
entered 3 new pax under Den Todaro’s invoice. The invoice is reflecting 22 which is correct but when I went back into the DB its showing only 19. Can you help ?

![image](https://cloud.githubusercontent.com/assets/14838466/20985616/378381fe-bc93-11e6-81b9-90fca8ed4a04.png)

![image](https://cloud.githubusercontent.com/assets/14838466/20985637/47f173f2-bc93-11e6-9ebf-150ea9159784.png)

**Comment by bradatkins** [comment]
Fixed
