### ISSUE TITLE
agents commission

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#171]
i deleted the 10% commission off of the brase price under this agent's name and changed her to GROSS, updated the booking and the math is correct now but commissions are still showing?

If someone has no commissions listed, and only selects GROSS, shouldn't the PRO column not show up after the order total? And the commission earned under the order total should disappear right?

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417831&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Can you take me through the steps you took that you did to do this: "i deleted the 10% commission off of the brase price under this agent's name and changed her to GROSS, updated the booking".

This way I can track down where the issue is

**Comment by ali206** [comment]
Ok I went to All Agents, clicked Edit on Bev Mickelson (bottom of page 2) 

Before I changed anything, she was showing as:
![image](https://cloud.githubusercontent.com/assets/8440903/6081064/a0defb8e-ade4-11e4-94a6-14d405b8b6f4.png)

Then I removed commission off base price and switched her to Gross:
![image](https://cloud.githubusercontent.com/assets/8440903/6081069/b1d8c866-ade4-11e4-9bfd-5f6518b3c307.png)

Then I went to View Orders, clicked on her booking # and clicked update.

That's pretty much it.

**Comment by bradatkins** [comment]
I think we have agent commissions all wrapped up now
