### ISSUE TITLE
URGENT - 426438 - registration/addt'l pax problems

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1710]
Melissa just registered these clients and when she selected to add a 2nd passenger, the DB kept trying to add 3 so she registered Charles by himself. 

Went back to the booking, tried to/did add Mary Ann, but in All orders and when you go in to the booking only Charles is there. 

We are unable to see/edit any of Mary Ann's info - are you able to make her show up or does Melissa need to rebook?

![image](https://cloud.githubusercontent.com/assets/8440903/21014202/17724a42-bd2b-11e6-8da9-8fe4a1e8f456.png)

![image](https://cloud.githubusercontent.com/assets/8440903/21014188/02287e22-bd2b-11e6-900f-6adf237600ee.png)

**Comment by bradatkins** [comment]
Fixed
