### ISSUE TITLE
Re-Design"Send Email" Generator for ease of use (Rinda)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1711]
When we click the email icon, this pops up:

![image](https://cloud.githubusercontent.com/assets/22382144/21016057/3d33e54a-bd32-11e6-82fe-e0412be5ab54.png)

This is great

Rinda advise that a mild irritation is that the "SEND" Button is at the bottom of the window. This requires a needless scroll down. It would be best if the button could be located at the top of the box:

here is the mock-up:
![image](https://cloud.githubusercontent.com/assets/22382144/21016230/e1028190-bd32-11e6-8e03-190f68088016.png)

**Comment by bradatkins** [comment]
I don't get to decide where the buttons go unfortunately. What I can do is move the box to the top-left so that may help

**Comment by chris206** [comment]
Great idea - please do.

As long as we dont have to click more buttons than necessary - it is good.

**Comment by bradatkins** [comment]
Done

**Comment by chris206** [comment]
Fantastic - thank you
