### ISSUE TITLE
Melissa 2 orders with Zeroed out passengers

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1716]
**First: 426450 - the info is in the blue sheet, but it is not showing as a passenger**

![image](https://cloud.githubusercontent.com/assets/22382144/21027301/3e17051a-bd5e-11e6-81ab-28beb79b019f.png)
![image](https://cloud.githubusercontent.com/assets/22382144/21027317/4daa8c04-bd5e-11e6-95f4-e117e61172d7.png)

**Second: 426452 -this is more serious as no info was retained**

![image](https://cloud.githubusercontent.com/assets/22382144/21027444/d12243c4-bd5e-11e6-81cf-b996fc3c505d.png)
![image](https://cloud.githubusercontent.com/assets/22382144/21027457/dba02de8-bd5e-11e6-9220-c82b62c095ac.png)

**Comment by bradatkins** [comment]
She really needs to start recording her orders...

**Comment by bradatkins** [comment]
Fixed the first order. I need some info on the second one

**Comment by chris206** [comment]
what info do you need?

**Comment by bradatkins** [comment]
I need to know the name of the PAX

**Comment by chris206** [comment]
ok - apparently there was no info whatsoever, so it just appeared after she booked the other 2.
