### ISSUE TITLE
disappearing passengers 426456

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1717]
I created the booking and everything went reasonably well BUT, I selected 3 passengers and 4 passenger input spaces opened.

I deleted this unneccesary passenger and continued - and the booking went through just fine.

Then, Rinda advised that she wanted to add a **_4th_** person to the booking - so I did an "add passenger", requested a single room and updated price and everything. The 4th passenger WAS NOT ADDED to the traveler list - but he was on the blue sheet (but not in single)

FORTUNATELY - i captured both of the described transactions in IDE. I will send them in a separate email.

This is a consistent and ongoing problem all week and needs to be fixed. We are missing passengers on lists and it is a recipe for disaster.

![image](https://cloud.githubusercontent.com/assets/22382144/21029044/e2d0952e-bd65-11e6-8265-f3b051033713.png)

![image](https://cloud.githubusercontent.com/assets/22382144/21028878/29450e46-bd65-11e6-9155-4d3bc79b7cd8.png)

**Comment by bradatkins** [comment]
OK try again

**Comment by chris206** [comment]
Still showing 3 - there should be 4

![image](https://cloud.githubusercontent.com/assets/22382144/21052752/7fa8a092-bdf4-11e6-8b7d-da0e9065afe0.png)

**Comment by chris206** [comment]
Any luck on this?

**Comment by bradatkins** [comment]
FIxed the 4th

**Comment by chris206** [comment]
Thanks Brad
