### ISSUE TITLE
Selenium IDE Running Concurrently with each order

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1719]
Hey Brad,

Is it possible to have a debugger built into the database; concurrently recording inputs, but disconnected from the DB code (pretty much like building selenium into our database or just our html server)

It would create a record of EVERY transaction passively and record them somewhere accessible to staff if there was an issue. 

This would allow for a separate retention of records - as all passenger info is recorded here automatically, so it would make it impossible to lose info.

Additionally, we would just need to notify you of the error and you would have access to the HTML degugger by default

**Comment by chris206** [comment]
It seems that Selenium webdriver may have just what we need.
http://www.seleniumhq.org/

**Selenium WebDriver**

If you want to
create robust, browser-based regression automation suites and tests
scale and distribute scripts across many environments

Then you want to use Selenium WebDriver; a collection of language specific bindings to drive a browser -- the way it is meant to be driven.

Selenium WebDriver is the successor of Selenium Remote Control which has been officially deprecated. The Selenium Server (used by both WebDriver and Remote Control) now also includes built-in grid capabilities.

**Comment by bradatkins** [comment]
Ya, unfortunately that's not it...That's for running scripts on the web to
run something like daily tests.

This is the creation of them. They are done in the IDE or Programmed in java

**Comment by chris206** [comment]
Would it be crazy or impossible to build it into the server? There must be something capable or automatically logging inputs

**Comment by bradatkins** [comment]
Closing as it's not a feature of Selenium
