### ISSUE TITLE
back to the top button (near scroll bar area)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#172]
Hi Brad,

Milanka wants a button that will fade in as a client scrolls towards the bottom of a web page. It will be located near the scroll bar area on the right side of pages (image sample below). When a client clicks on the button, it will use a SLOW scroll back to the top of the webpage. Here is a page with a sample:
http://www.webtipblog.com/adding-scroll-top-button-website

![image](https://cloud.githubusercontent.com/assets/10079829/6068421/ea075f72-ad49-11e4-8495-51392928977d.png)

**Comment by bradatkins** [comment]
Is this for the DB or the website?

**Comment by ronenreinheimer** [comment]
Future website.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
(I am adding in 2 more github requests)

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
I've added the button to this page, try it out

http://www.206tours.com/register/admin/test.php

![image](https://cloud.githubusercontent.com/assets/8440255/6217121/abbbcb3e-b5de-11e4-8677-3541b1d8f6a2.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

I saw that it worked on Chrome, but not IE.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
FYI, even in your example link the scroll to top doesn't work in IE:

http://www.webtipblog.com/adding-scroll-top-button-website/

**Comment by ronenreinheimer** [comment]
Oh I see, but I think we saw it work in other website, what I showed you is just a sample code – there must be a dozen codes to get this button to work. Do you need me to find more codes?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
If you can find another example that'd be great.

**Comment by bradatkins** [comment]
Hey -

Interestingly enough, I found a website (browserstack.com) which allows me to emulate IE 11.

It seems to work OK there, and my wife's computer??

**Comment by ronenreinheimer** [comment]
Do you work on a MAC or PC?

I see the website, but you have to pay for this service.


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
PC, and you can do a free trial.

**Comment by ronenreinheimer** [comment]
works great thank you!
