### ISSUE TITLE
#422823 please remove outstanding balance 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1720]
![image](https://cloud.githubusercontent.com/assets/14838466/21057913/938c554e-be09-11e6-8843-57e286ded8ba.png)

![image](https://cloud.githubusercontent.com/assets/14838466/21057926/a40d10de-be09-11e6-842c-41a421d3a7b4.png)

**Comment by Irena206** [comment]
#423637 
![image](https://cloud.githubusercontent.com/assets/14838466/21058030/1e2d9f14-be0a-11e6-88c4-98058456f80b.png)

![image](https://cloud.githubusercontent.com/assets/14838466/21058041/2bd98ccc-be0a-11e6-84de-524591d2aef2.png)

**Comment by bradatkins** [comment]
Done
