### ISSUE TITLE
Already Registered Notification in Explorer (Natasha)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1721]
Natasha was trying to sign up a new client using IE. 
After she had selected the tour and the "Sign In or Create a New Account" page showed up, she typed in an email address and hit the "create new account" button.

Nothing happened - no swirling waiting gif, just nothing.

We determined that the client was already registered, and then I tried to replicate it in Mozila.

I received a "this email address is already registered" notification which I almost missed.

Can you:

1. Make this notification more pronounced - either red, bold or red & bold type?
2. Try to figure out why IE didn't let client know that they were already registered

![image](https://cloud.githubusercontent.com/assets/22382144/21105622/e574505e-c058-11e6-886a-4dc03cc77c39.png)

**PS- I've attached the ide file in Natasha's GH email**

**Comment by bradatkins** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/8440255/21124746/c4be5502-c0ae-11e6-95ed-30ee37106824.png)

It displayed fine in IE. Get her to try again?

**Comment by chris206** [comment]
looks great - thank you!
