### ISSUE TITLE
Search Orders Column - Departing & Returning Dates as 2 columns (Sandy & Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1724]
Sandy and Sammie were discussing the new format - they decided that they would prefer 2 columns; one for departure dates, and one for return dates.

The benefits of being able to search both together are outweighed by the confusion that it causes for those who use the feature regularly.

Can you revise this?

![image](https://cloud.githubusercontent.com/assets/22382144/21114826/79fbfba0-c07c-11e6-8ff9-d6e3f3b225e2.png)

**Comment by bradatkins** [comment]
OK I've split them up

**Comment by chris206** [comment]
Excellent, thanks for doing it so quickly
