### ISSUE TITLE
Business Class Upgrade for Mexico / Canada / Argentina - Email Request Option (Sandy) 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1725]
Brad,

for these tours, we don't have prices, can you set up a link that says upon request and have it link to sales@206tours.com ?

makes sense?

**Tour Page:**

![image](https://cloud.githubusercontent.com/assets/10079829/21152556/c2ead620-c134-11e6-9e8f-444b8f748b21.png)

**In the Tour Departure Section:**

![image](https://cloud.githubusercontent.com/assets/10079829/21152639/2adf73da-c135-11e6-9083-d68d853085ec.png)

**Comment by bradatkins** [comment]
If it's blank for all departures it will show Upon Request already

**Comment by chris206** [comment]
Verified and understood
