### ISSUE TITLE
Quick Fix: Change "All Travelers" to "All Accounts"

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1727]
Please change the "All Travelers" link to "All Accounts" - it is confusing and inaccurate, so nobody uses it

Leave "All Passengers" alone

If you could make the quick change to the hyper link in main panel - great. Sub-directories (https://www.206tours.com/register/admin/listdata.php?FORM=**Travelers**) you can take time with, or just leave alone.

![image](https://cloud.githubusercontent.com/assets/22382144/21188318/ff70c578-c1e8-11e6-8bfc-9a3bcb50ae29.png)

**Comment by bradatkins** [comment]
I understand your first point, your second point I don't know what you mean?

**Comment by chris206** [comment]
the sub-directory, when i click on the link, it takes us to "https://www.206tours.com/register/admin/listdata.php?FORM=Travelers".

You don't need to change this right away to
https://www.206tours.com/register/admin/listdata.php?FORM=Accounts" 

If you meant my comment about "all passengers", i just wanted to make sure that you didn't change that. I will have another idea about that in the future (in a seperate GH).....

**Comment by bradatkins** [comment]
Oh that part won't be changing (the FORM=) part as it's part of how the DB
runs

**Comment by chris206** [comment]
great - can you just re-tile this page:

![image](https://cloud.githubusercontent.com/assets/22382144/21196089/6ebc6980-c204-11e6-8fe5-fd87c9e63fc9.png)

**Comment by chris206** [comment]
Hey Brad,

It used to be that changing the address in "All Travelers/Accounts" would change the address on the bookings.
What happened? Did they disconnect? Changing all travelers isnt doing anything anymore

2 years ago they were disconnected and it let to many problems - did something change?

**Comment by bradatkins** [comment]
The address is now order specific, click on the customer name on the orders screen.

**Comment by chris206** [comment]
That is a big mistake. Please undo this change.

I checked with Sandy that this change is not desired and would return us to the situation that we were in 2 years ago - changing contact info in multiple places. We specifically wanted to get away from order specific contact info.

The Accounts feature is exactly what we want to govern contact info. There is main/shipping address, there is billing address, account name, email, phone numbers, subscription status, etc.

Each account has an individual passenger mailing address override - but each order should have "read Only" contact info. Any changes must be made to account

**Comment by bradatkins** [comment]
We'll have to talk about this. Rolling this back is a huge change.

**Comment by chris206** [comment]
Ok - but, if it is a huge change to change it back, that implies that a huge change was made recently. Why did this change? Was it an oversight or was it specifically requested?

We have other ideas for changes to the structure of Accounts, Passengers, & Orders but need to discuss them more thoroughly before making the request.

**Comment by bradatkins** [comment]
Putting addresses on the order was changed a few phases ago, it was
requested by Milanka.,

**Comment by chris206** [comment]
Requested phases ago, but implemented last week?

**Comment by bradatkins** [comment]
Are you talking about when I renamed the words on the main page?

**Comment by chris206** [comment]
no - that just happened yesterday.

I meant the major change that disconnected the main accounts ability to control orders.

**Comment by bradatkins** [comment]
The disconnection was months ago...

**Comment by chris206** [comment]
That is crazy - we've only noticed the disconnect as of this week. Lat week I was changing account addresses and the address immediately showed up on invoice

**Comment by bradatkins** [comment]
I'll close this issue for now.

**Comment by chris206** [comment]
Accounts disappeared

![image](https://cloud.githubusercontent.com/assets/22382144/21330558/0999f1ce-c60c-11e6-8559-88b3af3c44f3.png)

**Comment by bradatkins** [comment]
I thought you wanted me to rename it back to All Travelers?

**Comment by chris206** [comment]
No - I wanted you to make "the Accounts" page the one that determines the address on all orders.

For example - changing anything here:
![image](https://cloud.githubusercontent.com/assets/22382144/21330638/6f26ebfa-c60c-11e6-99df-2908883d5ced.png)

Changes everything Here:
![image](https://cloud.githubusercontent.com/assets/22382144/21330675/99584a86-c60c-11e6-829d-ea1adc9fbecf.png)

& Here

![image](https://cloud.githubusercontent.com/assets/22382144/21330690/b0fe56f8-c60c-11e6-8c7b-546ef27aa063.png)


The only exception is if an individual passenger fills out special shipping request here, in which case a FEDEX label is created in addition to the main one.:

![image](https://cloud.githubusercontent.com/assets/22382144/21330737/ee073826-c60c-11e6-975e-7616c90403d3.png)

**Comment by chris206** [comment]
But in the short term, keep it labeled "All Accounts"

**Comment by bradatkins** [comment]
Renamed
