### ISSUE TITLE
some kind of option to restrict this DB area

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1728]
![image](https://cloud.githubusercontent.com/assets/10079829/21231738/551d5616-c2b7-11e6-8cc9-e222ce6801b7.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/21235227/f461d5e2-c2c3-11e6-9ce1-121d60477d3a.png)

**Comment by bradatkins** [comment]
This is done
