### ISSUE TITLE
Indicate "Wait List" on Blue Sheet

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1729]
Hey Brad,

"Wait List" IS indicated on client invoices = Great
"Wait List" is NOT indicted on Blue Sheets = NOT Great.

Can you include indication here?

![image](https://cloud.githubusercontent.com/assets/22382144/21235877/9dd47bf0-c2c6-11e6-88df-c828a4192f06.png)

**Comment by bradatkins** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/8440255/21294251/6c0b05ca-c506-11e6-9e40-ec1b9f14e7e8.png)
