### ISSUE TITLE
Slow / Smooth scroll back to the top script

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#173]
Hi Brad,

I need a script for this rollover button - that will take clients back to the top of the webpage, but it has to scroll slowly and smoothly.

all pages will have this button area:
https://www.206tours.com/index6.htm

![image](https://cloud.githubusercontent.com/assets/10079829/6068497/8f01012c-ad4a-11e4-9c03-20f7b6fae224.png)

**Comment by bradatkins** [comment]
Isn't this the same as 172?

**Comment by ronenreinheimer** [comment]
Yes, similar script, except this rollover button already exists.

The request for #172 will be a button that fades in and out in a different location of the webpage.

Does this make sense?

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
yup

**Comment by ronenreinheimer** [comment]
Work your magic.

I am working on 1 more github request

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
This is now complete.

**Comment by ronenreinheimer** [comment]
Looks to be working perfectly.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
