### ISSUE TITLE
search fields not working properly in orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1737]
![image](https://cloud.githubusercontent.com/assets/8440903/21323214/6fbebd3a-c5ea-11e6-8919-97349b1193cc.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
ok thanks - why is september mixed in the bottom for this last name?
![image](https://cloud.githubusercontent.com/assets/8440903/21323485/abbd7078-c5eb-11e6-8c26-c3c917d730e4.png)

**Comment by bradatkins** [comment]
What's the issue?  Sorry I'm not understanding what your arrow is showing as wrong?

**Comment by ali206** [comment]
The dept dates are not in date order

![image](https://cloud.githubusercontent.com/assets/8440903/21324663/bd181c1a-c5f0-11e6-837e-e2c4ad76ffa4.png)

**Comment by bradatkins** [comment]
It's ordered by Order ID

**Comment by ali206** [comment]
I'm losing my mind sorry - i guess it's always been that way
