### ISSUE TITLE
Question ? button towards the bottom right of web pages (near scroll bar)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#174]
Hi Brad,

Milanka wants to add a ? button on the bottom of all web pages towards the right scroll bar area. you can see an example on pinterest.com

![image](https://cloud.githubusercontent.com/assets/10079829/6069799/5d61aeb8-ad55-11e4-9c79-11c48bbf5348.png)

when a client press the ? button (it will fade a little) they will see the following message:

![image](https://cloud.githubusercontent.com/assets/10079829/6069567/85813abe-ad53-11e4-9798-acbeec371a78.png)

and it will link them to this page:
www.206tours.com/contact

*I will email you a .png image that you can use.

*we may want to incorporate the + button in the future, but for the time being we are not really sure what to use it for.

**Comment by bradatkins** [comment]
This is done, but not working in IE just yet... (if ever,...not sure)

![image](https://cloud.githubusercontent.com/assets/8440255/6321498/e6bb0afe-bacc-11e4-9d0a-6952c7affa25.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Do you think we need to find a different code to use? If it will not work on IE, Milanka will probably not approve.

I see the buttons, but I don’t see any icons on them:

[cid:image002.png@01D05012.26C43290]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I just got IE 11 put on my laptop, and it seems to work fine?

![image](https://cloud.githubusercontent.com/assets/8440255/6380507/266b7160-bd08-11e4-81e5-b4bc0a3d960f.png)

**Comment by ronenreinheimer** [comment]
Is this the url?
http://www.206tours.com/register/admin/test.php


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Yes

**Comment by bradatkins** [comment]
Yup!

**Comment by ronenreinheimer** [comment]
I saw that it wasn’t working. So I changed the link from https:// to http://     that made a difference for me in chrome.

I don’t get it, we have the same version at this point, but it is still not working for me on IE. I will send the link to other computers in the office and see if it works for them.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you make the help box go away when they click back on the website? does that makes sense?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Will do

**Comment by ronenreinheimer** [comment]
I am so happy it is working correctly on my pc, now it will be easier to refine everything.

Great job Brad!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
works great!
