### ISSUE TITLE
Add Flight Itineraries to the Audit

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1747]
Flight itineraries should be added to the audit after being sent to the client.

This would be very helpful, because once a flight departs, all Amadeus info is erased. It is surprisingly difficult to get this info from anyone, yet is is often necessary for insurance purposes, lost baggage, retroactive frequent flyer miles application, etc.

Here is the new rule for DB Sent documents and their relationship with the Audit:
"Anything that the Database is sending to clients should BOTH copy Orders AND be added to the Audit for record and review."

**Comment by bradatkins** [comment]
I checked and the flight itineraries are already there?

![image](https://cloud.githubusercontent.com/assets/8440255/21406207/5a6ed820-c798-11e6-9d7a-ba96dfc438fc.png)

**Comment by chris206** [comment]
what the - thats great then. They werent there last week
