### ISSUE TITLE
Tour 1 - prices not showing in 1st gen code

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1748]
It is only happening on this tour, very strange:

http://www.206tours.com/tour1/index34.htm

![image](https://cloud.githubusercontent.com/assets/10079829/21397854/4515ff14-c773-11e6-92a3-343a4439349a.png)

**Comment by bradatkins** [comment]
Try now

**Comment by ronenreinheimer** [comment]
TY!!!!!!!!!!!!!
