### ISSUE TITLE
Please copy all .css files etc to pilgrimages.com server

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1753]
Please copy all .css files etc to pilgrimages.com server

**Comment by bradatkins** [comment]
Done. Made a backup directory assets_20161228 as well

**Comment by ronenreinheimer** [comment]
thank you, i am going to upload a couple of files to test.

**Comment by ronenreinheimer** [comment]
please let me know how to fix these test files:
http://www.pilgrimages.com/scotthahn/index-splash-2016.htm
http://www.pilgrimages.com/scotthahn/fatima/index-2016.htm

**Comment by bradatkins** [comment]
your pointing to /home/tours206/ instead of /home/pilgrimages/ in your
include at the top (I'm guessing you just copied them over)

**Comment by ronenreinheimer** [comment]
you are correct. i tried /pilgraimages/ but so no change and then i tried /pilgrima/ and something changed - but it still needs some work..

i changed this file:
http://www.pilgrimages.com/scotthahn/index-splash-2016.htm

![image](https://cloud.githubusercontent.com/assets/10079829/21524134/d62784a0-cce1-11e6-811f-96983e5fd617.png)

**Comment by bradatkins** [comment]
This link is wrong...

![image](https://cloud.githubusercontent.com/assets/8440255/21524547/d9f3d28e-cce4-11e6-8271-589a6d1a303c.png)

**Comment by ronenreinheimer** [comment]
what should it be linked to?

**Comment by ronenreinheimer** [comment]
It's wherever you store that file.

**Comment by ronenreinheimer** [comment]
looks like we are making progress. there appears to be an issue with the tour slide & slide navigation.
http://www.pilgrimages.com/scotthahn/fatima/index-2016.htm

**Comment by ronenreinheimer** [comment]
do you need BD to look at it?
