### ISSUE TITLE
Pre / Post Tour Options - Per Person - has # of nights available (URGENT!)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#176]
Hi Brad,

when we setup a post tour option - which is set for per person, the DB is allowing clients to select # of nights. they should not have this option (only when we set it to per room) we need to have the drop down menu disabled as soon as possible. Here is a DB code sample: FR030514

![image](https://cloud.githubusercontent.com/assets/10079829/6082316/955620e4-adee-11e4-9378-904353262ef5.png)

**Comment by bradatkins** [comment]
I'm confused because this was changed when we did this:

https://github.com/206Tours/DB/issues/162

**Comment by ronenreinheimer** [comment]
Hi Brad,

Basically, if we set something to per room – The end user should have the drop down menu to select # of nights.
If something is set to per person - the end user should not have an option for # of nights in the drop down menu.

Does this make sense?


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7102333/e068ea38-e04a-11e4-98d8-365d05cc480e.png)

**Comment by ronenreinheimer** [comment]
thank you!
