### ISSUE TITLE
Amount Received Not Matching Amounts Paid (Liz)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1767]
When you search any specific order, the amount due matches the Total amount, no matter what was paid.

When we view orders generally, the amount matches

**Viewed Generally = Good:**
![image](https://cloud.githubusercontent.com/assets/22382144/21656364/d0ed186a-d28b-11e6-881d-efef4720ab78.png)

**Viewed by Order = Bad:**
![image](https://cloud.githubusercontent.com/assets/22382144/21656380/e4b03d0a-d28b-11e6-9eb9-205a7027ade6.png)

**Comment by chris206** [comment]
It also is broken when we search it in any way. Here is an example with lots of results, but specific name searched.

![image](https://cloud.githubusercontent.com/assets/22382144/21656593/d148418a-d28c-11e6-825d-79c7120eb250.png)

**Comment by chris206** [comment]
This is becoming a more serious issue as it is affecting manual work processes

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
thank you sir
