### ISSUE TITLE
Prior Passenger Drop Down still deleting gender when more than 1 passenger booked

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1773]
- When I did drop down for Dr. Test from prior info, his DOB appeared.
- When I added his wife, Beta, her DOB appeared (I think)  - but it overwrote Dr. Test's with BLANK for some reason?
- I corrected this, but now Beta (the fake wife) isnt showing a gender, even though it was in the drop-down

Can you fix? 

I was attempting to duplicate another reported error regarding post-tours, but I couldn't (good thing?)
I noticed that this was still a problem. It is somewhat important because this information is required as part of TSA info and is easy to overlook if it isnt there.

![image](https://cloud.githubusercontent.com/assets/22382144/21729828/d2d25272-d41a-11e6-8d13-47f71b8b3e43.png)

Please let me know when I can cancel this test booking

**Comment by bradatkins** [comment]
Fixed.
