### ISSUE TITLE
#422921 outstanding balance is wrong 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1774]
![image](https://cloud.githubusercontent.com/assets/14838466/21731169/0feb8e20-d421-11e6-9870-1b9f2d17d22c.png)

**Comment by ali206** [comment]
this one as well:
![image](https://cloud.githubusercontent.com/assets/8440903/21776034/85a771c8-d666-11e6-8b61-5fe916546a64.png)

**Comment by bradatkins** [comment]
Fixed
