### ISSUE TITLE
Terms & Conditions box before confirming registration

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#178]
Terms and conditions.  It says  fare and rates are based on Jan, 2012 which should be February 2, 2015 may seem outdated to passengers.  Also it seems some of words are missing in terms and conditions.
![k](https://cloud.githubusercontent.com/assets/8440903/6086457/db585032-ae0f-11e4-9571-ba8a268ab0aa.png)

**Comment by bradatkins** [comment]
Updated
