### ISSUE TITLE
social media icons missing

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1783]
can you please check the code to see why the social media icons are missing?
www.206tours.com

![image](https://cloud.githubusercontent.com/assets/10079829/21898936/7eba126e-d8bc-11e6-939c-10627ab74338.png)

**Comment by bradatkins** [comment]
I can see the HTML there, not sure why it's not showing up? My guess something with the CSS. Check with BD

                  <p class="socials">Follow us: <a href="https://twitter.com/206Tours" class="icon-twitter" target="blank"></a> <a href="https://www.facebook.com/206tours" class="icon-facebook" target="blank"></a> <a href="#" class="icon-gplus"></a> <a href="https://www.linkedin.com/company/206-tours" class="icon-linkedin" target="blank"></a></p>
