### ISSUE TITLE
Child Discount

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#179]
From Stef:

The child discount is auto deducting but the child will be 12 at the time of travel (ineligible for child discount) 

Can the database be fixed to avoid this in the future? 

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417831&GENERATED=TRUE&BLUE_SHEET=Y

**Comment by bradatkins** [comment]
Done. It's now based on the tour return date. Please test.

**Comment by ali206** [comment]
Hi Brad, 

This isn't working correctly.

Maeve is 2 now, bday is in March so she should only be receiving the child discount of $150.00 as per return date of Nov 2015.

![image](https://cloud.githubusercontent.com/assets/8440903/6338581/e5417a08-bb7d-11e4-9409-f9961bc91d99.png)

Instead, she's receiving the $1,000 discount.  Her base price should be $4,399 and insurance should be $244.

**Comment by bradatkins** [comment]
Fixed.
