### ISSUE TITLE
Unable to view inactive clients - clients mysteriously becoming inactive

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1790]
Please allow me to view inactive clients in "all accounts"

as it is now, we can only see the first page, and then it page 2 goes back to active.

**Comment by chris206** [comment]
clients are becoming inactive without any input. Old and new. My test booking name is gone. What is going on?

This is happening to clients

**Comment by chris206** [comment]
Ok, I've run into the problem with 3 over the ast 2 days and have never had the issue before.

It is really hard to find their travelerID, but once I do i can just replace travelerid in the url of an active traveler.

Brian Coellner
Test Testerton

**Comment by bradatkins** [comment]
My data shows you should probably ask Alexis what she was doing on January 9th from about 9:15 to 3:50 PM

**Comment by chris206** [comment]
She was instructed by Milanka to deacvivate blank accounts where only the name existed. Maybe my test guy went out by accident?

She received a prompt whenever she hits the X, and it still comes up.

What about Coellner? His account in inactive and his email is still messing me up (i cant add a new account, because the email is in use - Even though it isnt coming up). Here is his email: teng53@netzero.net.

I cant find him because I am unable to look inactive people up

I click "show inactive" which works BUT when I hit page 2, it resets to active. I can't search inactive pages or for inactive records - so I can't even fix the problem without work arounds that are inconsistent

**Comment by bradatkins** [comment]
She deactivated Coellner as well

**Comment by chris206** [comment]
ok, I have removed the urgent tag. 

Any word on why we are unable to view inactive? Why it resests to active when we leave the first page?

**Comment by bradatkins** [comment]
You can see inactive by clicking this link:

![image](https://cloud.githubusercontent.com/assets/8440255/22175070/cc63a34e-dfbb-11e6-9a3c-6c6f3f65c3e0.png)

**Comment by chris206** [comment]
I can view the first page - clicking any other page changes the view back to active

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
awesome

**Comment by chris206** [comment]
Hey Brad,

I can now see all pages, but I cannot search them. When I search any variable, it searches only Active - whether I am on Active or inactive

**Comment by bradatkins** [comment]
Try now

**Comment by chris206** [comment]
ok great, it works.

but I am clueless as to why I can't create an account for km284071@gmail.com
because it tells me the address is already taken
and there is nobody in active or inactive passengers

**Comment by bradatkins** [comment]
Try again, please log a separate issue if this reoccurs
