### ISSUE TITLE
Please add "payment due/overdue" auto generated emails into the audit

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1797]
I cant see any evidence of these being sent.

![image](https://cloud.githubusercontent.com/assets/22382144/21987803/e6d3610c-dbd2-11e6-8f3f-bed5da605548.png)

**Comment by bradatkins** [comment]
It's already there:

![image](https://cloud.githubusercontent.com/assets/8440255/22048355/6ad55bae-dcfa-11e6-8862-180fb47408f3.png)

**Comment by chris206** [comment]
![image](https://cloud.githubusercontent.com/assets/22382144/22072830/8d4eb2d0-dd71-11e6-8494-bb0ac63f7bdd.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22072867/b1f7b4b0-dd71-11e6-842a-54fa5493ec18.png)

**Comment by bradatkins** [comment]
OK I think I've found the issue, it won't fix historical orders but future emails

**Comment by chris206** [comment]
Ok - it wont fix historical orders; like any orders that are currently booked?

Or just ones that have already missed trigger dates?

Will it be sending payment due in future AS WELL as missed payment reminders?

**Comment by bradatkins** [comment]
It will be for ones that missed their trigger dates.

**Comment by chris206** [comment]
ok, no problem

Will it be sending payment due in future AS WELL as missed payment reminders?

**Comment by bradatkins** [comment]
it will send payment dates in the future.
