### ISSUE TITLE
Math wrong on invoice 416939

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#180]
Lindy's total trip costs should be $3,807

Then the order total should be $$7,722

They should then be overpaid by -$108

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=416939&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
I'm confused on all accounts then...why would Lindy's insurance only be $108??

![image](https://cloud.githubusercontent.com/assets/8440255/6089812/a3aca170-ae36-11e4-95cd-39590563daa2.png)

**Comment by ali206** [comment]
B/c Sandy applied a discount of $3,699 = Lindy's trip cost. Free trips get lowest ins. premium
