### ISSUE TITLE
Unable to Add Value in "Tours" (Amanda)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1800]
Similar to the orders issue last week, where modifications weren't being saved, we are unable to "add value" in our Tours section

This means we are unable to add new tours to the DB, which is a problem

We CAN change/save data in existing tours, however - the progress wheel spins and returns us to "Tours", where changes have been confirmed.

But when we try to add a tour, it just goes to a blank page - doesn't return us to tours. it doesn't come up when searched either. I tried the number amanda was using (to ensure this wasnt the issue) and various others - none worked

**Comment by bradatkins** [comment]
This was the Deposit thing, same issue. Fixed
