### ISSUE TITLE
Foreign Addresses No Longer Allowing Booking 426975 (Sandra)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1801]
Even though foreign States are available at the account level, when attempting to create a booking from another country - no options for State come up for many countries. This effectively blocks foreigners from moving to the next page or signing up which is bad - hence the urgency.

Is this related to the State clean-up requested #1722? If so - whoops

![image](https://cloud.githubusercontent.com/assets/22382144/21999478/56c0c60a-dc08-11e6-98ff-30bd5a2f54b6.png)

**Comment by chris206** [comment]
This is still an urgent problem - foreign pilgrims are unable to sign up as they have no states.

Any updates?

**Comment by bradatkins** [comment]
So I've made it now that if we do not have any States for a particular Country, the DB will show a text input box:

![image](https://cloud.githubusercontent.com/assets/8440255/22522016/04476064-e888-11e6-8def-440a7dc72b9e.png)

**Comment by chris206** [comment]
And this will not add states into the database - just on the account, right?

If so, great workaround

**Comment by chris206** [comment]
I'm creating an account, selected Mongolia - and still 1000 states and characters are coming up. I'm unable to type in anything

Maybe move the country above the street address?

**Comment by bradatkins** [comment]
No, the issue was if NO states show up.

**Comment by chris206** [comment]
Feature is not working for CC, though

![image](https://cloud.githubusercontent.com/assets/22382144/22527474/61f0da3c-e89d-11e6-9075-5715b6e339a7.png)

**Comment by bradatkins** [comment]
Forgot about that one, good cathc. Fixed
