### ISSUE TITLE
Deposit Required in "Tours" table needs to default to "Blank", not "Yes" (Elise)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1802]
Tour departure DEPOSIT needs to default to "blank" - because "YES" is a null value and causes problems
Is this just a weird glitch? I've never noticed this before

![image](https://cloud.githubusercontent.com/assets/22382144/22025019/146bd942-dc9a-11e6-805e-17ad175a5aa8.png)

**Comment by bradatkins** [comment]
Fixed. Not sure why it was doing that.

**Comment by chris206** [comment]
great!
