### ISSUE TITLE
Tidy-Up Bonus to Increase Rate of User Adoption

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1804]
Please make a universal change in "Tours" table:

For ANY of the following file manager names (but no other names - this is important) - please change them to the file manager **ROK Team** 

"Wherever the following values are found in Tours Table, change to value: ROK Team"

1. Stephanie
2. Rinda
3. Donna
4. Melissa
5. Nicole
6. Sammie
7. Piernha

So, there will be a single file manager to represent all of those people. If easily doable, we could even temporarily exclude those individuals from the list of file managers with a yes/no toggle in their associated USER entry.

**Can this be done without screwing up other file manager entries?**

![image](https://cloud.githubusercontent.com/assets/22382144/22030870/01473aec-dcad-11e6-9937-ba5d867659c7.png)

**Comment by bradatkins** [comment]
There isn't really a clean way to do this based on name without hardcoding
it...Unless we go based on whether they are Series tours or not.

**Comment by chris206** [comment]
oh man, i would have thought that would be easy.

What if we created the value for any of those people that they would show up and be searchable as ROK in BONUS? It doesnt really matter what the entry is, i guess, just how they appear and how they are searchable in BONUS

**Comment by bradatkins** [comment]
Why wouldn't you just put the tour manager as ROK? I'm confused as to why this is an issue.

![image](https://cloud.githubusercontent.com/assets/8440255/22034516/8d1b8534-dcba-11e6-9eb2-d65537db6f70.png)

**Comment by chris206** [comment]
Thats exactly what I want to do!

**Comment by bradatkins** [comment]
Then any tour with those peoples names should be switched to "ROK Team" in
the Tour itself, then it will be reflected in the BONUS file accordingly.

**Comment by chris206** [comment]
I know! haha
Thats what I was asking!

**Comment by bradatkins** [comment]
You guys have to do it, as I don't know which ones should be ROK

**Comment by chris206** [comment]
These defined values should be changed to  the value ROK Team

Stefanie Meyer
Rinda Kanidinc
Donna Strucic
Melissa Mulligan
Nicole Martins
Sammie Gough
Piernha Marc

**Comment by chris206** [comment]
Awesome. 

Can we make the departure code column linkable to the particular departure in DB?
Can we make the passenger number hyperlink to the following:
https://www.206tours.com/register/admin/roominglist.php?TourDepartureID=VALUE&TourID=VALUE

**Comment by chris206** [comment]
I have 2 more requests...

1. These defined values in Account Manager should be changed to the value Cakes Team

Caterina Viti
Elise D
Ingrid G
Sandra Lippold
Katherine Iverson
Alexis D
Yaritza Rodriguez

2. If a departure is a SERIES departure, the account manager should be changed to ROK Team (only)

**Comment by bradatkins** [comment]
I've linked the columns

**Comment by bradatkins** [comment]
Done the 2 updates as well

**Comment by chris206** [comment]
great! Can you default the view to departures today and afterward?
(we just needed prior dates searchable which they weren't before)

**Comment by chris206** [comment]
Great! Very close to throwing the old spreadsheet away

1. Departure codes are no longer searchable - they need to be
2. Passenger count is still including cancelled passengers - we need it to not include cancelled passengers
3. Can you default the view to departures today and afterward?
(we just needed prior dates searchable which they weren't before)
4. please exclude any SERIES departures from BONUS unless there is at least 1 passenger registered
(dont worry about the custom or semi-custom departures handled by ROK, they should still be listed even if 0)

![image](https://cloud.githubusercontent.com/assets/22382144/22079218/0743197a-dd89-11e6-8b3a-3e64cf54808d.png)

**Comment by chris206** [comment]
Once the numbers are accurate (and dont include cancelled passengers) - can we have a running tally of ROK vs AdHoc passenger numbers for a given year? It can even show up in Bonus like orders shows up in "forecasts". Nothing fancy like a basketball scoreboard or anything

ROK's numbers would just be a total of ALL active passengers on ALL ROK tours with a departure date in a given calendar year 

AD Hok's numbers would be a total of ALL active passengers on ALL with a file manager who is NOT ROK Team.

No duplication in numbers

**Comment by bradatkins** [comment]
I've done 1, 2, 3. 

For # 4 I can only hide all or none. So I've hidden any tour with 0 PAX.

**Comment by bradatkins** [comment]
Sorry, your running total number is a bit more involved and I can't do that outside of a new enhancement.

**Comment by chris206** [comment]
The default view is now Jan 2018 and running backwards in time.

Can you make the default view today's date Ascending?

![image](https://cloud.githubusercontent.com/assets/22382144/22081444/9b30d4d0-dd91-11e6-8bb7-32cd34cf3f85.png)

**Comment by bradatkins** [comment]
Well you can't have your cake and eat it too..

You want future dates and past dates, "today" ends up in the middle :)

**Comment by chris206** [comment]
crud. okay so send it back to the way it was - ascending.

Regarding hidden; can we have a button to view hidden? That can be the compromise so that Sandy can review her stuff

**Comment by chris206** [comment]
crud. okay so send it back to the way it was - ascending.

Also - dont have "air" underneath Total Pax. This single number needs to include all passengers, regardless of air

![image](https://cloud.githubusercontent.com/assets/22382144/22083048/5626a67e-dd98-11e6-976e-1bf775bb37a8.png)

Regarding hidden; can we have a button to view hidden? That can be the compromise so that Sandy can review her stuff

It is also important to Rinda that we have the ability to either: 
Export this to excel
OR
Copy and paste the columns/rows that we need into excel direct from DB

(they use this for other things that would be too much to add at the moment.

**Comment by chris206** [comment]
I am still unable to search group code - i need to look up either:
DV or DV031017 - so it cant require typing in full

**Comment by chris206** [comment]
total number of passengers needs to include ALL passengers - you've excluded the land only column without re-adding them to the total.

This is priority

**Comment by bradatkins** [comment]
I've added in land

**Comment by bradatkins** [comment]
The search is fixed.

Exporting to excel was not requested (since we are doing this to get away from the excel) therefore would be an additional enhancement

**Comment by chris206** [comment]
ok thanks

can we just make the columns pasteable?

**Comment by bradatkins** [comment]
Not sure why they wouldn't be pasteable already? There's nothing stopping
it from being copied and pasted.

**Comment by chris206** [comment]
Who is Tammy? Is that just what the DB is labeling departures where a file manager isnt selected?
We dont have a Tammy

1. Can you default those to ROK team?
2. Can you reverse tour order to the way you had it originally? with current date at top, later dates as you go down list?
3. Searching user is still case sensitive, can you make it not case sensitive?
4. When I copy the columns and try to paste them into excel, it just plops all data into one single cell

![image](https://cloud.githubusercontent.com/assets/22382144/22084267/72c96cbc-dd9d-11e6-9e14-74dfbbb4762e.png)

**Comment by chris206** [comment]
Apparently viewing earlier dates at the top first, then later as we go down is called "ascending" dates. This is what we want.

I was confusing myself because with letters and numbers that is inverse

**Comment by bradatkins** [comment]
Just to be 100% clear:

Do you want

A)

2018
2017
2016


OR

B)

2016
2017
2018

**Comment by chris206** [comment]
B

**Comment by bradatkins** [comment]
Done

**Comment by chris206** [comment]
awesome - it looks like we will cease using our spreadsheet bonus in the next few days if each spot check comes out accurately

Thanks for finishing this up so rapidly - It has made me look like i am somewhat competant

**Comment by chris206** [comment]
Sandy brought up her need for the "hidden" departures (with zero passenger value

I thought of a compromise that could work.
can we exclude ONLY series departures with 0 passenger value? (rather than making the exclusion based on File manager)

**Comment by chris206** [comment]
Sandy brought up her need for a link to also view the "hidden" departures (with zero passenger value)

I thought of a compromise that could work.
can we exclude ONLY series departures with 0 passenger value? (rather than making the exclusion based on File manager)

**Comment by chris206** [comment]
Also,

Instead of searching for departures that have an 8 ANYWHERE (for ex) in the code, we just want to have tours where 8 is in the beginning

another example, if I type in SM, i only want codes starting with SM to come up (not something line 0105SM625)

like departures and tours allows us to search.

![image](https://cloud.githubusercontent.com/assets/22382144/22119212/b51d7a26-de48-11e6-8d7d-b0ad7f6d57e0.png)

**Comment by bradatkins** [comment]
I've changed it as follows:

if you type in just 8 it will do an exact match

If you type 8* it will search for a tour # starting with 8
If you type *8 it will search for a tour # ending with 8
If you type *8* it will search for a tour # that has the number 8

**Comment by bradatkins** [comment]
Here for Sandra:

![image](https://cloud.githubusercontent.com/assets/8440255/22120530/13152b38-de4e-11e6-8a66-62d468776b32.png)

**Comment by chris206** [comment]
Both great, thank you

**Comment by chris206** [comment]
Hey Brad,

Milanka is asking about certain features and comparing them unfavorably with "registered passengers"

1. How does the next departure come up at initial view? Past departures are also available.
2. Can we have an alternating color scheme; like grey then white then grey
3. Can you switch the following 2 column locations: Document Status and Tour Code

**Comment by bradatkins** [comment]
1) We talked about this already, we can have PAST / CURRENT / FUTURE or FUTURE / CURRENT / PAST
2) I'll check into the alternating, for some reason it's not working
3) Done
4) Done

**Comment by chris206** [comment]
Hey Brad - we are looking at a February 6th retirement of the old Bonus - but I was just alerted to a big problem...

If Bonus is showing ALL departures with a single passenger registered (or waitlist)
WHY does it only show 2 departures
When registered passengers already shows 11?

![image](https://cloud.githubusercontent.com/assets/22382144/22350224/fb74df12-e3e0-11e6-9db8-6d9592a745d0.png)


![image](https://cloud.githubusercontent.com/assets/22382144/22350229/007b2a0c-e3e1-11e6-9460-9d2dada431c8.png)

**Comment by bradatkins** [comment]
Fixed the issue. For some reason it was only searching till a certain day in 2018 even though no day was specified.

However, this only brings it to 9 records instead of 11 because the BONUS file does not include LAND ONLY Pax.

**Comment by chris206** [comment]
When you say it doesn't include Land Only files - I'm confused

**Comment by chris206** [comment]
sorry, forgot to add the "ok great, thanks for the quick response" part

**Comment by bradatkins** [comment]
Ya I guess there was some old logic there. I've removed it. Should match up now

**Comment by chris206** [comment]
Perfect. A few things:

1. Amanda brought up another great point - if a departure is listed as Cancelled - does it still appear in BONUS? I imagine that it would appear in active BONUS AND if there were 0 pax, it would be in the full bonus

2. On the topic of Full BONUS - just like the problem we had in searching hidden accounts, I can open Full BONUS, but once I search any field it brings me back to Active BONUS

**Comment by bradatkins** [comment]
1) Inactive tour departures show in the bonus (if there's more than zero PAX on it) 

2) Fixed

**Comment by chris206** [comment]
As per discussion with Rinda and Sandy, can you eliminate passengers who are "wait listed" from being appearing as part of the total passengers in bonus?

**Comment by bradatkins** [comment]
Done

**Comment by chris206** [comment]
Can we change the Tour code to the color RED if the departure is cancelled?

**Comment by bradatkins** [comment]
Example departure please...

PS: It's to a point where we need to draw the line for additional changes to the Bonus file. Future changes must be logged as an enhancement.

**Comment by chris206** [comment]
JY042717

Sure - I will start building new requests for any additional features

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/22564024/e2dfdcf2-e950-11e6-8edd-b737e89343d4.png)

**Comment by chris206** [comment]
FANTASTIC!
