### ISSUE TITLE
Not Compiling Name/Rooming List to Excel File

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1805]
Sandy & Milanka need Dr. Hahn prior passenger info - but some of the departures glitch out and go to a blank page when we try to export to excel. Is it the sheer number of pilgrims?

Please fix these 2 and the underlying error causing the problems.

https://www.206tours.com/register/admin/roominglist.php?TourDepartureID=29256&TourID=2905
https://www.206tours.com/register/admin/roominglist.php?TourDepartureID=26245&TourID=2264

![image](https://cloud.githubusercontent.com/assets/22382144/22033974/a3c6e1b8-dcb8-11e6-87d5-75da22653abd.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22034062/eb7160e2-dcb8-11e6-8d0d-09b235fc2622.png)

**Comment by bradatkins** [comment]
https://www.206tours.com/register/admin/roominglist.php?TourDepartureID=29256&TourID=2905 came up fine?

As did 

https://www.206tours.com/register/admin/roominglist.php?TourDepartureID=26245&TourID=2264

**Comment by chris206** [comment]
these are both just going to blank screen for me and patrick and sandy

**Comment by bradatkins** [comment]
Ah sorry, just noticed you were running the group leader excel. It's fixed

**Comment by chris206** [comment]
Works Great, thanks Brad. 
Was the problem that the group exceeded max value for compiling (because it was huge) - and the fix that you elevated max value?

**Comment by bradatkins** [comment]
No, it was failing on a specific piece of data
