### ISSUE TITLE
Phantom duplicate passenger added to invoice (Sammie & Nicole) 420397

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1814]
The passenger isnt listed in registered passengers, just on invoice and blue sheet.
It isnt even messing up the price

![image](https://cloud.githubusercontent.com/assets/22382144/22160056/c35eba68-df11-11e6-9f43-db4927b16691.png)

**Comment by bradatkins** [comment]
This is an old bug, but I fixed the order.

**Comment by chris206** [comment]
Pricing is broken - please figure out why the prices dont add up (even after we update)

**Comment by bradatkins** [comment]
Fixed
