### ISSUE TITLE
Duplicate Orders - Duplicate Payments - Order Tally still doesnt work (Alexis)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1816]
Hey Brad,

A 2 issues that need to be resolved - 

First - the inaccurate orders remaining balance has still not been resolved, so it make reviewing files fir dupe paymants more difficult

Second - client was charged twice and had 2 orders created - 42704**1** is good, 42704**2** was blank.
I know that she probably hit the submit button twice.

![image](https://cloud.githubusercontent.com/assets/22382144/22165457/dcc932ae-df29-11e6-8eb8-75b6af30fe1a.png)

**Comment by bradatkins** [comment]
Hit the button twice
