### ISSUE TITLE
427104 - Installment dates/amuont incorrect

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1818]
I adjusted the amount in Elavon to only be charged $2137 but I can't adjust the date or $ amount on the invoice to show correctly ($2137 monthly to be PIF by 3/23):

![image](https://cloud.githubusercontent.com/assets/8440903/22216076/96871704-e16b-11e6-90ce-1cce6d926a20.png)

He's only scheduled for 2 payments (2/23 & 3/23) but DB is adding an extra "payment" in the date section. 

![image](https://cloud.githubusercontent.com/assets/8440903/22216093/addb6aa4-e16b-11e6-8248-28f9d90e47c0.png)

**Comment by bradatkins** [comment]
Fixed
