### ISSUE TITLE
DB insurance question

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#182]
Trying to put the order for Patterson/Jo Ann Margaret and I am getting strange message about insurance.
“We are sorry but only passengers from the US or Canada can purchase insurance”
She is from Atlanta and under MK who is also in US – not sure why is this happening.

When new order is created DB will not let us add insurance and also DB reset  chosen departure city
Once booking is created we can go back update the order and add insurance without problems.

Not sure what would happen if people try to book online themselves – if they would have the same problem.

![nat](https://cloud.githubusercontent.com/assets/8440903/6108591/5be22398-b042-11e4-97d6-1af1c8edc381.jpg)

![nat1](https://cloud.githubusercontent.com/assets/8440903/6108597/60c396c6-b042-11e4-8fd8-2c7b8edb1b2b.jpg)

**Comment by bradatkins** [comment]
If this was from Natasa, please try again. I think I fixed it over the
weekend.
