### ISSUE TITLE
All Departures Is Messed Up - Needs Urgent Fix

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1822]
I cant find any series departure info. 2027 departure is first to appear. Please help.

![image](https://cloud.githubusercontent.com/assets/22382144/22220474/df55796a-e17c-11e6-92e6-8f816feb4de1.png)

**Comment by bradatkins** [comment]
What's wrong with it? I see a bunch of departures there?

**Comment by chris206** [comment]
There are no results for Tour 111!!!!
Probably countless other number tours

it's really weird

**Comment by bradatkins** [comment]
Checking now.

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
ok, great. what was excluding them from search?

**Comment by bradatkins** [comment]
It was a bug
