### ISSUE TITLE
425694 - 2 payments made, no idea how

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1824]
2 $400 payments were made on 1/5/17...we did not manually charge them and it looks as though they were not processed through the DB so I have no idea how they wre charged b/c she also didn't have an installment plan?!

Any idea or can you see anything in the DB as to what happened?

![image](https://cloud.githubusercontent.com/assets/8440903/22266618/b33031fe-e24e-11e6-8ea7-ac4ca2360d68.png)

**Comment by bradatkins** [comment]
Do you have the transaction ID's?

**Comment by bradatkins** [comment]
I can see an error in the DB that she typed the following in the Payment amount:

"400.00 to cover travel ins and day early travel costs"

I couldn't reproduce it, but I didn't have a number filter on the Amount field. I've since put one in that should fix this.
