### ISSUE TITLE
Pricing is very wrong on this departure (Sammie) 

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1825]
More than 1 passenger is calculating a totally erroneous subtotal.
We have tried troubleshooting it on our end, to no avail.

Any ideas? Can you let me know what the difficulty is?

![image](https://cloud.githubusercontent.com/assets/22382144/22300653/22089998-e2f6-11e6-9bd6-9c0178e97561.png)

**Comment by bradatkins** [comment]
All I did was update the order on this screen and it's fixed

![image](https://cloud.githubusercontent.com/assets/8440255/22316388/e14660e4-e33a-11e6-95ec-b57ef69e9b3c.png)

**Comment by chris206** [comment]
We updated it in 5 different places (in order old price, in order new price/in edit old price, in edit new price/in tour code), reviewing numbers each time. It almost always works, but we couldn't get it

Where did you update it that it worked? Are you sure nothing else was done?
