### ISSUE TITLE
Insurance & Cancel for any reason erratically being applied and omitted without request 427120 (Patrick)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1826]
Client never asked for CFARP plan, but was charged. He also mentioned being double charged for folklore ballet

I've been noticing other orders where the insurance isnt what was initially intended - or when CFAR was almost defaulted to yes

![image](https://cloud.githubusercontent.com/assets/22382144/22306322/d3985304-e30c-11e6-944d-52f34409d9cf.png)

**Comment by chris206** [comment]
here is another

![image](https://cloud.githubusercontent.com/assets/22382144/22306479/6eb49aaa-e30d-11e6-97f1-611e1daf81fd.png)

**Comment by bradatkins** [comment]
Hey -

I can see that it doesn't look like he selected CXL protection. I tried to reproduce it but was not successful.

Can you try ?
