### ISSUE TITLE
Random Email Receiving Privileged Client Info 426015 (Piernha)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1827]
Random Email Receiving Privileged Client Info.

Please help us understand how this email is being copied in.

![image](https://cloud.githubusercontent.com/assets/22382144/22341572/4d210006-e3bf-11e6-8102-21a4ebe30839.png)

**Comment by bradatkins** [comment]
There's a Tour Agent on the Tour. I've removed it

![image](https://cloud.githubusercontent.com/assets/8440255/22344335/d0d1c30e-e3c9-11e6-9310-c2ffe8e37a50.png)

**Comment by chris206** [comment]
That didnt even occur to me... Thanks
