### ISSUE TITLE
"All Orders" Can't Search by Departure Code (Bika)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1828]
Try any DC departure ie; DC031317

It can search dates, but this isn't helpful to their team.
It is searchable in Registered passengers & all Departures

![image](https://cloud.githubusercontent.com/assets/22382144/22341838/5d9cb514-e3c0-11e6-9f9d-efbb1b33e2d6.png)

**Comment by bradatkins** [comment]
You have to do dc* 

FYI this is not URGENT

**Comment by chris206** [comment]
You are correct - because it works elsewhere it isnt urgent.

Thats unusual though - is that new? We can type only DC anywhere else (all departures, BONUS, registered passengerts, tour code)

**Comment by bradatkins** [comment]
Yes, but you were trying to find 111 but coming up with other results you requested the ability :)
