### ISSUE TITLE
All Yellow Sheets/Name/Rooming lists show Gibberish and fail to compile (Liz)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1831]
Clicking Yellow Sheet returns gibberish (export feature)
Clicking export name list returns gibberish
Clicking export rooming list returns gibberish

are you working on db at moment?

![image](https://cloud.githubusercontent.com/assets/22382144/22375213/26878c7c-e477-11e6-9ad6-bbc0693ae49f.png)

**Comment by bradatkins** [comment]
Very strange, it seems all Excel related items are not working hmmm

**Comment by bradatkins** [comment]
Fixed. Computer's are so picky. Apparently I left an extra line break which was causing things to mess up

![image](https://cloud.githubusercontent.com/assets/8440255/22379635/0ac38f66-e488-11e6-92ad-a77cff4f3a5b.png)

**Comment by chris206** [comment]
Databasing is mindbogglingly complex. It is a miracle that any of it works.
The more I learn about computing, the less I understand
Thank you for the quick fix
