### ISSUE TITLE
Phantom Passenger, 0 value unable to cancel (Melissa) 427214

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1836]
What kind of tool might we have access to to delete these 0 passengers with a real balance?

I added a fake passenger, which broke the amount due issue - but i didnt want to do that

![image](https://cloud.githubusercontent.com/assets/22382144/22384074/b255d43e-e49a-11e6-93eb-a76fee126eab.png)

**Comment by bradatkins** [comment]
Admin and Accounting have access to this feature

![image](https://cloud.githubusercontent.com/assets/8440255/22532864/38eea4be-e8b8-11e6-9dde-05c56077e23b.png)

**Comment by bradatkins** [comment]
it zero's out the order
