### ISSUE TITLE
Installment payment- #427089 and #426951 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1838]
Hi Brad, 
Please adjust installment payments  to show correctly. I made incorrect ones inactive. 

#427089
![image](https://cloud.githubusercontent.com/assets/14838466/22429897/42bfbc56-e6da-11e6-9857-bfa14aefc834.png)

#426951
![image](https://cloud.githubusercontent.com/assets/14838466/22429907/4d89da36-e6da-11e6-8d0a-893c2010782b.png)

**Comment by bradatkins** [comment]
What is the correct amount? 1166 and 499.71 respectively?

**Comment by Irena206** [comment]
Yes, that is correct amount.
