### ISSUE TITLE
Future Login Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#184]
Hi Brad,

can you please update our login page: https://www.206tours.com/register/loginaccount.php

please add option for new clients to sign up with 206 Tours. please link the email address and bold the phone number. thank you. i will email you the sign up button.

![image](https://cloud.githubusercontent.com/assets/10079829/6115998/9caf0712-b077-11e4-9a32-29fd1d02622a.png)

**Comment by bradatkins** [comment]
Done. The new customer part is not going to be done that way, it'll be a link on the mouseover.
