### ISSUE TITLE
RM/PNR Mismatch 427029 & 426623

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1841]
The RM code from the old booking was not deleted.

![image](https://cloud.githubusercontent.com/assets/22382144/22441908/4ae2e156-e707-11e6-99b7-73eaa063701e.png)

**Comment by bradatkins** [comment]
You need to fix the duplicate in Amadeus by removing the Order ID on one of the PNRs

**Comment by chris206** [comment]
But we cant - thats really the issue with these things.
Once the old pnr is cancelled - we are unable to delete the RM line. We need to have a feature that just no longer looks at that old rm line.

**Comment by bradatkins** [comment]
Hmm maybe the DB isn't checking if the PNR is cancelled. Let me look into it

**Comment by chris206** [comment]
Perfect. This would fix alot of problems and make our systems much more seemless when we can overcome this issue

**Comment by bradatkins** [comment]
K. I've fixed it for this order. Cancellations in the future will be processed. And it should resolved as you view even past itineraries (the DB reprocesses the PNR cached so they will eventually fix all)
