### ISSUE TITLE
Payment Reminder Emails NOT being sent (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1842]
Hey Brad,

Sammie was going through orders and found that these clients were not sent a reminder email.

Did they just miss the date cut, or was there a glitch stopping the process. ALSO - can we receive copies of the sent reminders? Copying orders would do the trick.

![image](https://cloud.githubusercontent.com/assets/22382144/22478038/52a115fc-e7b6-11e6-941f-26dc6dc3daf0.png)

**Comment by chris206** [comment]
any update here?

**Comment by bradatkins** [comment]
Why would 427241 need a payment reminder? Order placed and paid for Jan 30

They must have missed cutoff, as some were sent out today even:

![image](https://cloud.githubusercontent.com/assets/8440255/22524685/375732d6-e892-11e6-82aa-a95239cc6714.png)

**Comment by bradatkins** [comment]
and account@206tours.com is already Bcc'd on the email

**Comment by chris206** [comment]
Touche on Sheperd

but what about 425448? This guy in unpaid - and he signed up in 2016 - did he miss the trigger by a day - liek the day before we implemented?
