### ISSUE TITLE
Yellow Sheets Not Including Pre-Post RB091917 (Katherine)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1845]
Yellow Sheet used to include pre/post column. This departure code HAS correctly registered pre/post options, but they are not appearing on yellow sheet.

![image](https://cloud.githubusercontent.com/assets/22382144/22487104/11998a16-e7da-11e6-87e4-904b04551f51.png)

**Comment by bradatkins** [comment]
Fixed
