### ISSUE TITLE
DB Airport Mis-Match - Blank Departure/Return City (Milanka & Bika)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1847]
**Departure Code: HM101517 - Some recent change to DB has cause 3 passengers to have departure city issues.**

**INVOICE/BLUE SHEET:** Was showing up with "Boston (BOS)", but without the ",MA"
![image](https://cloud.githubusercontent.com/assets/22382144/22511077/6e1bdfae-e862-11e6-8904-08df40559ee5.png)

**RECAP:** Missing Any departure City whatsoever for last 3 clients registered
![image](https://cloud.githubusercontent.com/assets/22382144/22511713/87461268-e864-11e6-866c-dd1e0b8ada44.png)

**ORDER:** I checked each order and saw that the drop-down departure city was BLANK. I corrected this and the "MA" returned, but the price went up by $95 per person.

**TOUR CODE:** Airport was added correctly, add-on price $0.

**ORDER AUDIT:**  Checked departure city after my addition, the Boston being used here doesnt match the Boston in the TOUR CODE departure city.
![image](https://cloud.githubusercontent.com/assets/22382144/22511898/25430426-e865-11e6-836a-540e3610db1c.png)

**Comment by bradatkins** [comment]
Fixed
