### ISSUE TITLE
Phantom Deviation Return - Unable to Delete 426833 (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1849]
I found the manual overide date in the order & attempted to delete this deviation (by cycling the drop-down to default), but it would not update after multiple attempts.

1. Why was this added in the first place (there were no post-stays available)
2. Why cant it be updated back to default?

![image](https://cloud.githubusercontent.com/assets/22382144/22512119/f0108a5c-e865-11e6-87dd-817671b755f4.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/22532075/fe6d5c54-e8b2-11e6-8226-dcad847e23ac.png)
