### ISSUE TITLE
Tour #208 - not resolved

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#185]
Hi Brad, 

I thought this was resolved but it's not. 

When i look for Tr#208 in the DB it looks correct, but on the invoices is still showing the incorrect destinations.  Is that why you said you would move everyone over?  what are you moving them over to?

Only Tr#208 11 days should be showing - if i make the 13 days inactive will it mess everything up again?
![image](https://cloud.githubusercontent.com/assets/8440903/6130831/ea4aff46-b115-11e4-9a6f-f49a66a16e93.png)

there's only 1 dept.
![image](https://cloud.githubusercontent.com/assets/8440903/6130873/35c82ba6-b116-11e4-8f4b-9a5f537d3ab0.png)

**Comment by bradatkins** [comment]
Example invoice?

**Comment by ali206** [comment]
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=416967&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Seems to be OK
