### ISSUE TITLE
Client Side Account Error & Question

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1851]
2 things:

1. Address is spelled incorrectly.
2. Clients are asking about their ability to see prior orders with us. Is the "past" view option supposed to be a toggleable view?

![image](https://cloud.githubusercontent.com/assets/22382144/22521498/2899cad0-e886-11e6-887c-d3b067d99a2e.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
fantastic! thanks
