### ISSUE TITLE
Tour/Departure Dates Mismatch FAT2017B100 (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1854]
I'm not going to make this urgent, but it is pretty weird.

![image](https://cloud.githubusercontent.com/assets/22382144/22559568/81941a8c-e93f-11e6-8b76-5a57c75cbe78.png)

**Comment by bradatkins** [comment]
Check the order itself...I bet the Override Return Date has May in it.

**Comment by chris206** [comment]
Nope, checked. Super weird

**Comment by chris206** [comment]
wait - im an idiot

**Comment by chris206** [comment]
The real question is what causes this - this has been coming up this week - but nobody actually changed it - especially on this order because there are 3 passengers. That is a bizarre thing to change for each one

**Comment by bradatkins** [comment]
Because it had a post tour on it of :

Post Tour to Spain and Lourdes with a return date of May 20th

**Comment by chris206** [comment]
But there is no post-tour on their orders now - why was it added?

**Comment by chris206** [comment]
Apparently they were converted from another departure. The post tour seems to have been transfered with them
