### ISSUE TITLE
Disappeared Departure Cities - Blank List (Liz)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1857]
![image](https://cloud.githubusercontent.com/assets/22382144/22596046/f2e77bee-e9f7-11e6-91cd-854f6e92cfdf.png)

**Comment by bradatkins** [comment]
Not a bug, someone has not fully setup the Destination of "Portugal"

![image](https://cloud.githubusercontent.com/assets/8440255/22598164/8a758016-ea00-11e6-81a8-92ade61c9a2b.png)

**Comment by chris206** [comment]
Somebody selected "Portugal" as the destination country in the Tour Code.
Our instructions advise users to leave it blank for Europe Holy Land.

This is why this issue never comes up. User Error on set-up
