### ISSUE TITLE
Orders pending invoice email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#186]
As you can see below there is only 1 page of invoices pending that need to be emailed out (there are only 23)

![image](https://cloud.githubusercontent.com/assets/8440903/6175444/d9a75706-b2c4-11e4-9991-5392e4fb970c.png)

So when i go to search by Nov 2015 this is the only booking that should come up:
![image](https://cloud.githubusercontent.com/assets/8440903/6175473/178d9742-b2c5-11e4-8b32-bc743eef6857.png)

However, the DB keeps bringing me to All Orders which is wrong:
![image](https://cloud.githubusercontent.com/assets/8440903/6175488/35dfd8a4-b2c5-11e4-85b7-13b1640bca0a.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6653436/655d79ea-ca69-11e4-896d-29ec40233c0b.png)
