### ISSUE TITLE
Invoices, Recaps, and Blue Sheets are not coming up when clicked URGENT

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1860]
invoices and blue sheets are not coming up

however, past invoices come up in audit

**Comment by chris206** [comment]
This is a big deal, stopping work processes

**Comment by chris206** [comment]
flight itineraries are all disconnected to

**Comment by bradatkins** [comment]
You caught me in the middle of an upload...it's all good

**Comment by chris206** [comment]
so what is the eta? I just want to give people and eta

**Comment by bradatkins** [comment]
Take a screenshot? It's working for me?

**Comment by bradatkins** [comment]
Sorry, found it. Try now

**Comment by chris206** [comment]
fantastic

**Comment by chris206** [comment]
flight itienraries are still disconnected. The departure DV031017 code used to populate, now nobody has a working itienrary

**Comment by bradatkins** [comment]
This is unrelated, please log a seperate issue...

**Comment by bradatkins** [comment]
And it's working for other tours
