### ISSUE TITLE
DV031017 No Longer Populating Flight Itineraries

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1861]
Just started today

flight itienraries are still disconnected. The departure DV031017 code used to populate, now nobody has a working itienrary

**Comment by bradatkins** [comment]
At first glance, there's quite a few different Orders on PNR #YIM4VT which isn't typical...

**Comment by bradatkins** [comment]
And it's not all of them, for example:

https://www.206tours.com/register/flight_itinerary.php?OrderID=425284&PassengerID=25325956

So it looks like whomever did these bookings did them differently?

**Comment by chris206** [comment]
YIM4VT is pretty typical. We dont only have people from a single order on a PNR.

Here is a snapshot of that transfer list. This morning, I took a glance at it and it helped me recognize an inconsistency (which is great) - but the lsit was totally populated. Now, it only has 2 names, and 3 duplicates of the ray guy

![image](https://cloud.githubusercontent.com/assets/22382144/22608716/0fbaad5c-ea2c-11e6-87c4-6345a7f6e936.png)

**Comment by bradatkins** [comment]
It's fixed, but I'm not sure if this fix broke a previous one I put in for cancelled PAX (the one where the DB lists an error because there are two PNR's)

Anyway, if we do come up with that issue, I've put in a note in the code to remind us. 

This tour should be OK now

**Comment by chris206** [comment]
![image](https://cloud.githubusercontent.com/assets/22382144/22663139/77692d08-ec79-11e6-83db-118d3e2eddb6.png)

The transfer list info doesnt seem to be meshing for some passengers. Also, the new yellow sheet column is confused (it used to have all Y's down the column. It looked great

![image](https://cloud.githubusercontent.com/assets/22382144/22663167/9b0a45f8-ec79-11e6-90ff-1df473432ed9.png)

**Comment by bradatkins** [comment]
Sorry, forgot to mention you'll need to click on the plane icon for each
PAX so the DB can reprocess their PNR
