### ISSUE TITLE
URGENT - Client booked waitlisted tour and was confirmed (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1862]
![image](https://cloud.githubusercontent.com/assets/10079829/22654526/fdd10740-ec5a-11e6-8d24-6ae1540d668a.png)

**Comment by bradatkins** [comment]
Why do you think this was confirmed? It says Wait Listed in the screenshot?

**Comment by bradatkins** [comment]
Fixed.

This was happening when the user saved the order and came back
