### ISSUE TITLE
Account 308090 Disappeared

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1868]
Account 308090 is nowhere to be found; in active or inactive.

Can you please fix and explain what is going wrong?

424409	Sager / Rebecca	CS031317

**Comment by bradatkins** [comment]
Why are  you referencing that #?

PS: The number is actually 30890...you had an extra zero

But there was an issue, it's showing up now (but inactive):

![image](https://cloud.githubusercontent.com/assets/8440255/22765916/bc7ad996-ee40-11e6-9a48-b9e43cffab7a.png)
