### ISSUE TITLE
2 Reservation Deviation Issues 427412 (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1869]
2 issues related to deviated departure/return dates

1. Invoice comments not appearing on invoice (i put them in 4 different places to troubleshoot, none of which worked)
2. Although I manually overwrote the return date, the original return date still shows.

_BTW - even though the client is leaving on a different date than group, he comes up when we search the group's date (as I requested) - THIS IS GREAT - I wasn't aware that this was functional_

![image](https://cloud.githubusercontent.com/assets/22382144/22744837/986e96b8-edec-11e6-8d88-552aa52514f0.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22744828/935387e2-edec-11e6-87f9-a5deda8e9e5d.png)

**Comment by bradatkins** [comment]
1) Fixed

2) This Return date is and always has been the standard tour return date, because we only show one return date (eg if two PAX are returning on different dates, we only show one date here).

**Comment by chris206** [comment]
But I overwrite the return date and there is only 1 passenger

**Comment by chris206** [comment]
nevermind, looks like you fixed it
