### ISSUE TITLE
Free's applied in the DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#187]
If a free is applied to an invoice shouldn't the subtotal and order total also say free? i don't remember what was decided on that:

![image](https://cloud.githubusercontent.com/assets/8440903/6176953/ce86a960-b2d0-11e4-8d0a-fb0be5fcf60e.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/7102229/cb2301f2-e047-11e4-828d-4eb10da73fcd.png)
