### ISSUE TITLE
URGENT: need help with order audit - 424919

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1871]
Client's inquiring about $6,740 payment made by check on 8/18...we can't find this payment anywhere.

The audit never says the payment was applied, just that Katherine created the order and then made a "payment" of $6,740.  I'm assuming this was a pending payment as she's not an ADMIN user to approve payments. 

Can you see anything about that?  Did someone approve a pending payment by accident?

![image](https://cloud.githubusercontent.com/assets/8440903/22749599/e825e6ca-edfb-11e6-8af1-0c402d0605ad.png)

**Comment by bradatkins** [comment]
I see Katherine logging the payment in Pending status.

I also see the payment in Approved status.

I'm trying to search my logs, but unfortunately there's a problem that I'm getting WiredTree to look into right now. I'll report back

**Comment by bradatkins** [comment]
Irena set the payment status to approved on September 15th, 2016 at 12:45:56
