### ISSUE TITLE
DB-- No info on invoice (sam)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1872]
![image](https://cloud.githubusercontent.com/assets/10079829/22791281/d809a586-eeb6-11e6-9c3e-683f5db6ee10.png)

**Comment by bradatkins** [comment]
Hmmm...strange. Checking

**Comment by bradatkins** [comment]
Found the problem, looks like the customer went to edit something and the DB barfed. I'll restore their info

**Comment by bradatkins** [comment]
Fixed
