### ISSUE TITLE
Total Passenger Selection Prior to "Book Now"

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1874]
Since the "number of passengers" drop down is now static (with no plans for re-activating it), please hide it from view. It's just clutter and we are all easily confused (particularly the travel agents who might see it and dont use the DB every day)

![image](https://cloud.githubusercontent.com/assets/22382144/22831366/230808e0-ef78-11e6-8eec-5e012ca694f4.png)

**Comment by bradatkins** [comment]
Done

**Comment by chris206** [comment]
That's a new record!
