### ISSUE TITLE
Departure/Return Cities Deleted/ No audit history

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1878]
I added passport info for these client earlier today and it blanked out their depature city. There is no mention of this change, though

until I added it back

![image](https://cloud.githubusercontent.com/assets/22382144/22840453/9e8cec38-ef9b-11e6-81ba-df1eb67c5169.png)

**Comment by bradatkins** [comment]
Do you know when it removed them?

**Comment by chris206** [comment]
maybe 3 hours ago?

**Comment by chris206** [comment]
The edit button blanks out the departure/return city for EVERY order that ive checked today

**Comment by bradatkins** [comment]
Found the issue. Originally this tour was setup with the regular departure cities (eg all of them) then was switched to only a subset. When this happens, the City's unique identifier changes.

Putting in some code to accommodate this

**Comment by bradatkins** [comment]
Fixed. FYI this wouldn't show up in the log because it was a bug...

**Comment by chris206** [comment]
perfect, thank you
