### ISSUE TITLE
Default font size larger

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#188]
![yari](https://cloud.githubusercontent.com/assets/8440903/6177917/5961a5ce-b2d8-11e4-8b26-c52c99a72d52.jpg)

![yar](https://cloud.githubusercontent.com/assets/8440903/6177921/5ce6dd72-b2d8-11e4-992d-5b21a5725da5.png)

**Comment by bradatkins** [comment]
Done. Changed it from 11 I believe to 13

![image](https://cloud.githubusercontent.com/assets/8440255/9431436/2de795e0-49df-11e5-92fd-d5029ab15d04.png)
