### ISSUE TITLE
Most people could not find "know before you go" link (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1880]
Hi Brad, please add a KBYG link in the client My Orders section of the DB. 

![image](https://cloud.githubusercontent.com/assets/10079829/22857162/dd66c4f6-f06d-11e6-962e-01a2a0419be1.png)

please link it to this url

![image](https://cloud.githubusercontent.com/assets/10079829/22857194/6f34c856-f06e-11e6-85e9-b6ce30fbf838.png)

![image](https://cloud.githubusercontent.com/assets/10079829/22857168/fb1830ca-f06d-11e6-90e2-23a0ecf8ca31.png)

**Comment by bradatkins** [comment]
Done, if the link exists on the Tour, it'll show up here:

![image](https://cloud.githubusercontent.com/assets/8440255/22862514/468eda82-f0fe-11e6-86a6-699d80c4804a.png)
