### ISSUE TITLE
URGENT - can't change booking status to OPEN

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1882]
DB code: DC061017

When we change this to OPEN, it doesn’t save

![image](https://cloud.githubusercontent.com/assets/10079829/22890749/4ea7627e-f1db-11e6-944c-cf8425b3a5d3.png)

![image](https://cloud.githubusercontent.com/assets/10079829/22890758/53f48cc0-f1db-11e6-82f7-841131b27b80.png)

**Comment by bradatkins** [comment]
fixed
