### ISSUE TITLE
Duplicate Name - Overwrite all original info

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1885]
at approximately **15:35:46**
I took this order (the way a client would because she was from NZ)

I immediately noticed some overlap when I added a passenger, but fixed in order. Client went in to update a single piece of info - and ended up ruining the order completely (names now overlap, she had to try and change it 5 times) this is the usual client experience when it comes to DIY edits and it infuriates them.

This just adds fuel to the fire to the idea that information needs to be segmented. 

![image](https://cloud.githubusercontent.com/assets/22382144/22904513/c66966d4-f20a-11e6-94e4-36d2a520be74.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22904749/98313656-f20b-11e6-8273-b897860454d4.png)

**Comment by bradatkins** [comment]
Fixed
