### ISSUE TITLE
Order Disconnected from its own Audit - Flight Schedules non-responsive (Sandy) 427176

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1891]
Two problems, same order

1. Sandy has an email - which was sent by the database on 2/14 - but there is no record of this event in the audit.
![image](https://cloud.githubusercontent.com/assets/22382144/22980025/38fbb9d4-f366-11e6-88fb-9e4720b10b14.png)

2. Sandy has been sending flight schedules, but not only do they **not appear in the audit**, they dont send at all. We tried one this morning at about 9:55:00 AM from "Sandy" if you want to take a look at what happened.

**Comment by bradatkins** [comment]
The order audit was barfing on a change I made a while back (in certain situations).

It's working now:

![image](https://cloud.githubusercontent.com/assets/8440255/23000677/8e836d2c-f3af-11e6-8c4c-8dadab503434.png)

Just pay attention if you don't for some reason see the footer of the page, the page likely crashed:

![image](https://cloud.githubusercontent.com/assets/8440255/23000701/9f5b7dec-f3af-11e6-9894-9f47bdf6e111.png)

**Comment by chris206** [comment]
There seems to be quite a few of these. Should I report each as a new GH? There will probably be quite a number

**Comment by bradatkins** [comment]
If there are please report them.
