### ISSUE TITLE
Super Weird Extra Passenger 423793 (Bika)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1895]
1 person booking looks fine, until you look at blue sheet. Random passenger who was never added is listed. I looked in audit and it says Amanda added her - but there is no female who has ever been added to this booking

It seems to be duplicating this info from her actual order - crossed streams or somethine

![image](https://cloud.githubusercontent.com/assets/22382144/22991024/04b51e04-f389-11e6-8647-c0844b7770f4.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22991036/0a37e230-f389-11e6-84e5-439e0725d878.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22991050/15ac25a4-f389-11e6-92c7-21d77bee4323.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22991060/1c64394a-f389-11e6-91ec-2e4ba686d940.png)

**Comment by bradatkins** [comment]
Fixed the order. Not sure where the bug came from, kind of old. Keep an eye out if it happens again and open a new issue
