### ISSUE TITLE
Waitlist Orders totally unsearchable (Patrick)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1896]
We cant narrow down by departure date, tour code, anything. I remember when Sandy asked about this feature and we said it didnt find info by partial tour code - but as it is now, it is unhelpful

For example - how would we find all SH050917 waitlisted clients?

Also - this page should have the earliest sign up at the top, latest toward the bottom

![image](https://cloud.githubusercontent.com/assets/22382144/22991909/e9d90c28-f38b-11e6-92a1-97d5217ec3f2.png)

**Comment by bradatkins** [comment]
Fixed
