### ISSUE TITLE
Option to eliminate Flight Bags (URGENT)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#190]
Hi Brad,

For some of our cutstom groups - we don't want them to have our flights bags. Can you give us the option to either show or hide this option from clients:

![image](https://cloud.githubusercontent.com/assets/10079829/6194223/350c14e4-b390-11e4-834f-543f283487d5.png)

**Comment by Sandra206** [comment]
We will also need to update and change some of the options
Tote Bag
Duffel Bag
Messenger Bag
Backpack 
None

**Comment by ronenreinheimer** [comment]
This is for land only bookings?

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by Sandra206** [comment]
No for all


________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>

**Comment by bradatkins** [comment]
You can now specific whether or not a bag or not. By default all departures will have a bag, unless No is specified.

![image](https://cloud.githubusercontent.com/assets/8440255/9430291/44fa9e20-49bd-11e5-8289-58f5247f36c3.png)

**Comment by Sandra206** [comment]
Anyway we have an option to edit flight bags ?

We just got a new messenger bag I would like to add to the list.

Feel free to contact me with any questions.

With Kind Regards,

Sandra Lippold
Director of Operations
206 Tours<x-apple-data-detectors://0/0>
333 Marcus Boulevard<x-apple-data-detectors://0/0>
Hauppauge, NY 11788<x-apple-data-detectors://0/0>
Phone: (631) 361-4644<tel:(631)%20361-4644> or (800) 206- 8687<tel:(800)%20206-%208687>
E-mail: sandra@206tours.com<mailto:sandra@206tours.com>
www.206tours.com<http://www.206tours.com/>

On Aug 23, 2015, at 5:35 PM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


You can now specific whether or not a bag or not. By default all departures will have a bag, unless No is specified.

[image]<https://cloud.githubusercontent.com/assets/8440255/9430291/44fa9e20-49bd-11e5-8289-58f5247f36c3.png>

**Comment by bradatkins** [comment]
Messenger bag is in the list now

**Comment by Sandra206** [comment]
Is there any way that we have the option to edit that section?
For instance we only have 1000 messenger bags and they may run out so we may put in another bag or just get rid of that one.


________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>
