### ISSUE TITLE
Report Glitch Link Doesnt Show Up on Reservation Confirmation Page?

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1901]
Hey Brad, apparently the report glitch link isnt showing up when taking a reservation for us?

This would be hugely helpful to you and everyone if it would - particularly regarding accounting issues.

**Comment by bradatkins** [comment]
Sorry, I have no idea what you are talking about? :)

**Comment by chris206** [comment]
the whole point of the "report issue" link at the top of the page was to report oddities as we found them.

![image](https://cloud.githubusercontent.com/assets/22382144/23069752/a31f887c-f4f6-11e6-820d-a22675c80db1.png)

How can we do that when the link doesnt exist during a booking?

![image](https://cloud.githubusercontent.com/assets/22382144/23069765/b024336a-f4f6-11e6-8327-8984e74dfdc1.png)

**Comment by bradatkins** [comment]
Added for staff:

![image](https://cloud.githubusercontent.com/assets/8440255/23094721/2e6271bc-f5cc-11e6-90cf-62b42d4536cb.png)
