### ISSUE TITLE
"Save and come back later" feature needs quick fix

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1904]
Many complaints about button placement and confusion about whether they should hit "save" or continue.
It is obstructing bookings

Can we relocate the button and rename it to "come back later" or something like that?

**Comment by bradatkins** [comment]
Ronen can change the button. I can move it.

Good news is that button also does the same as continue.

**Comment by chris206** [comment]
ok thats good news. maybe their issue is on the final page? there is no continue there, only submit or something

**Comment by chris206** [comment]
We are going to change it to "Come Back Later"

**Comment by chris206** [comment]
Apparently

A. Ronen can't change it
B. Sandy wants it to say "Save For Later"
C. Rinda very smartly asked "why doesn't continue automatically save the information and continue".......

**Comment by bradatkins** [comment]
A) OK
B) OK
C) We can do that, but I think the intent was for the PAX to know they can
come back later, hence the button would indicate that.

**Comment by chris206** [comment]
So please do A) and B) 
and we will leave C) alone for now

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/23048029/539012ec-f481-11e6-89a6-274bb1d6f6af.png)

**Comment by chris206** [comment]
Fantastic!
