### ISSUE TITLE
Insurance Broken on Initial Payment Page 427611 (Nicole)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1909]
From: Nicole Martins 
Sent: Friday, February 17, 2017 2:04 PM
To: Chris Wright <chris@206tours.com>; Ronen Reinheimer <ronen@206tours.com>
Subject: travel insurance 

Travel insurance showed 0 when I tried to register online. Then the blue sheet showed insurance declined had to go back in and manually switch it  

427611	Gault / Ernest	168	Sep 18, 2017   Sep 26, 2017
--------------------
Session ID: a5d879f1649de9c4c7b553ce77377d2a
Time: 14:01:28

**Comment by bradatkins** [comment]
The video helped, I was able to reproduce it.

**Comment by bradatkins** [comment]
K I think I've got this fixed. If you see this again, please report it.
