### ISSUE TITLE
Dropdown menu not working - URGENT

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#193]
Hi Brad,

you can't select departure city for some reason. can you please look into this issue as soon as you can.

thank you.
http://www.pilgrimages.com/danielstabile

**Comment by bradatkins** [comment]
It's working on other tours, so it's likely how this one is setup that is
the problem. My guess is it's set to have only specific departure cities
and none are setup.

**Comment by ronenreinheimer** [comment]
Hi Brad,

I’ve never seen this issue before. This is the DB code: DS070515 and I looked it over and it is setup correctly. It is very strange.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
Hi Brad, that setting is correct – that is used to either show addons or not and this tour is not going to offer addons. I’ve never seen this kind of issue before.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
If it's not having other addons, you need to specific the departure cities,
like other tours have done.

**Comment by ronenreinheimer** [comment]
Departure city is set in the DB for Washington DC

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
You need to setup your departure cities here:

![image](https://cloud.githubusercontent.com/assets/8440255/6235314/9a9a9cb4-b6af-11e4-9ed4-5d0a5888cca2.png)

**Comment by ronenreinheimer** [comment]
That worked! Thanks Brad.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
