### ISSUE TITLE
Helping clients with Login Information (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1932]
Brad please look into this password issue.

![image](https://cloud.githubusercontent.com/assets/10079829/23348788/6d8e90f4-fc7b-11e6-94e6-ec0b1fe1a3c7.png)

**Comment by chris206** [comment]
Brad - is this related to a clients account being set to "inactive"?

If an account is set to "inactive" and that client requests to reset their password; instead of sending them an unworking temp code because their account remains inactive, can we:

**1. Set account to active** (extremely important first step)
2. Reset password
3. Send Reset password to client

**Comment by bradatkins** [comment]
That's probably the issue. I just checked this persons account and it is
inactive.

I'll make that change.

**Comment by chris206** [comment]
It is odd actually, this woman had 2 accounts: one under gmail, the other under hotmail.
Neither had any info or bookings associated,

There are really **2** solutions possible when these clients are attempting to reset passwords:
a. If the email/account is set to "inactive" **we can treat it like is isn't in our system at all and advise them to create a new account or use a different email**
OR
a. if the email/account is set to "inactive" **we can set it to active, then reset the password.**

Could we combine these 2 solutions for best effect?

IF the inactive account has NO current or past orders associated AND has no phone number or address noted, **we will treat is like it doesn't exist and notify clients of this fact**

IF the inactive account **has** a current or past order associated OR a phone number or address noted, **we will change it to ACTIVE and reset their password when requested**

Doable?

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
you implemented those fixes that quickly? It was complicated in my brain.

**Comment by bradatkins** [comment]
If there was an account, I already was resetting the password, I just added the resetting the Active flag to Yes.

**Comment by chris206** [comment]
What about this one:

"It is odd actually, this woman had 2 accounts: one under gmail, the other under hotmail.
Neither had any info or bookings associated,

There are really 2 solutions possible when these clients are attempting to reset passwords:
a. If the email/account is set to "inactive" we can treat it like is isn't in our system at all and advise them to create a new account or use a different email
OR
a. if the email/account is set to "inactive" we can set it to active, then reset the password.

Could we combine these 2 solutions for best effect?

IF the inactive account has NO current or past orders associated AND has no phone number or address noted, we will treat is like it doesn't exist and notify clients of this fact

IF the inactive account has a current or past order associated OR a phone number or address noted, we will change it to ACTIVE and reset their password when requested

Doable?"

**Comment by bradatkins** [comment]
Whether or not the account has an order against it is irrelevant, we treat
it the same (activate and reset password).

**Comment by chris206** [comment]
It's not irrelevant; If a client hasnt added any info to their account,  has no orders associated, AND their account is inactive....

They may be using the wrong email to log in (as this client was). My suggestion was intended to stop clients from making duplicate accounts as there is currently no way to lasso those accounts back together.

**Comment by chris206** [comment]
nevermind - maybe I'm overthinking it. lets try this before you spend any time on the other one
