### ISSUE TITLE
Zeroed Out Passenger with NO Audit History (427777 Milanka)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1938]
Order Created On: 2017-02-25 
Time: 08:54:41

Zeroed Out Passenger with NO Audit History, but no evidence of audit crash.
No booking record at all
However, very specific payment recieved

![image](https://cloud.githubusercontent.com/assets/22382144/23369291/dbfce1c2-fcde-11e6-9f10-92843a86c2f6.png)

![image](https://cloud.githubusercontent.com/assets/22382144/23369298/e37c7ad4-fcde-11e6-8d0c-f1f969e29d42.png)

![image](https://cloud.githubusercontent.com/assets/22382144/23369305/e9286dc6-fcde-11e6-825d-17751a0daf7e.png)

**Comment by bradatkins** [comment]
What does this mean:

"However, very specific payment recieved"

**Comment by bradatkins** [comment]
i found the issue and resolved it.

Is order 427819 replacing order 427777? If so I won't bother fixing the order

**Comment by chris206** [comment]
i meant specific balance due.

Yes, 427819 is the good one, can you please cancel 427777?
