### ISSUE TITLE
FW: "Your passport is not required to register" (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1939]
Hi Brad,

Please make the following adjustment to reg page:

1.	Please add the following: 
Nickname – For Name Tag

2.	Make Gender mandatory

3.	Please add the following information prior to passport number - Not mandatory until 45 days prior to departure

4.	Please have uniform and adequate space between all form elements

![image](https://cloud.githubusercontent.com/assets/10079829/23376546/815887f0-fcfa-11e6-823a-ee90eac41b4d.png)

**Comment by bradatkins** [comment]
Done
