### ISSUE TITLE
Social Media Icons look strange

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#195]
![image](https://cloud.githubusercontent.com/assets/10079829/6252008/480a14a0-b765-11e4-8e84-b9b806c01651.png)

http://www.206tours.com/tour111/

**Comment by bradatkins** [comment]
Hey -

I don't define the image itself, my guess is where ever that class is coming from in your CSS:

        <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_facebook"></a>
        <a class="addthis_button_twitter"></a>
        <a class="addthis_button_pinterest"></a>
        <a class="addthis_button_email"></a>
        </div>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-51da16582fdebec2"></script>

**Comment by ronenreinheimer** [comment]
they are back to normal now
