### ISSUE TITLE
Land Only Out-Bound Dates Arent Being Overridden (Mario)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1955]
Outbound dates should change to whatever they are manually overridden to.
Mario's example isolated this problem only to land only people, whose dates don't budge

![image](https://cloud.githubusercontent.com/assets/22382144/23528751/fe9c5d0c-ff68-11e6-98e1-efb69653b000.png)
--------------------
Session ID: 2f27b9adcf64577d3aa378d21dc4bdf4
Time: 16:40:07

**Comment by bradatkins** [comment]
Fixed.

**Comment by chris206** [comment]
but it overwrote with the day after the date requested? It should be a straight overwrite - if may 3 is requested, it shouldnt go to the 4th just because it is land only
