### ISSUE TITLE
New tabs for Booking section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1958]
http://206tours.bigdropinc.net/dist/html/tour-details.html
https://pastenow.ru/01f7c58a20f66a92e63ebc490f6f2ae3

![image](https://cloud.githubusercontent.com/assets/10079829/23569181/13786b9e-002c-11e7-9f30-227a9d2140a0.png)

**Comment by bradatkins** [comment]
Sent an email back to Andrew, as some of this doesn't make sense the way they've done it.

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/24086959/d851ef02-0cee-11e7-8b04-b222fe217823.png)
