### ISSUE TITLE
Florida Client Offered CAD Currency (Patrick)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1959]
Can you take a look at this client's video and try to figure out why she would have been offered CAD instead of USD. Is she using a VPN without knowing it, is it a glitch?

2017-03-06 11:13:07	Carton / Margret, DOWNEY

![image](https://cloud.githubusercontent.com/assets/22382144/23630035/81c55b68-0287-11e7-84ef-ce5662a9c456.png)

**Comment by bradatkins** [comment]
The DB started off with an external download of IP to Location mapping.

At times it can be incorrect. I've change this mapping to point
to SARASOTA, FLORIDA.

**Comment by chris206** [comment]
Hmmm. So her IP wasnt in the externally hosted library so we needed to add it to our own library that serves as a supplement when the main one is missing info?

ok - its more complicated than a VIN number
