### ISSUE TITLE
425328 - payment approved by who?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1960]
This ECHECK for $7198 should still show as pending b/c i just processed the payment today. 

Can you see who approved it? Audit says nothing.

![image](https://cloud.githubusercontent.com/assets/8440903/23667178/10343718-032b-11e7-8827-64f8377bae59.png)

![image](https://cloud.githubusercontent.com/assets/8440903/23667208/1e92f132-032b-11e7-8db5-c8ca0b190ed2.png)

**Comment by bradatkins** [comment]
Chris Wright

**Comment by ali206** [comment]
since when are others allowed to approve payments??

**Comment by bradatkins** [comment]
Chris is listed as an ADMIN

**Comment by bradatkins** [comment]
And it was Sandra who changes his access level

**Comment by chris206** [comment]
Its my fault! I forgot to change myself back this time.
