### ISSUE TITLE
Correct 2019 Date in DB, Incorrect 2018 Date Appearing on Website (Jen)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1964]
She entered info into DB correctly, but it is reflecting incorrectly on website.
Is the DB capped at displaying 2018 as the max date?

Tour 112 - is this DB wide or isolated to Tour 112?

![image](https://cloud.githubusercontent.com/assets/22382144/23707691/4b4f7248-03e1-11e7-9031-7b9dbe1d09db.png)

**Comment by bradatkins** [comment]
Fixed
