### ISSUE TITLE
Deviation Dates are Wrong (426469)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1965]
Both clients look like the are leaving on July 24 - but only 1 is.
I've tried it a few different ways - any other way shows Eugenia as the one leaving July 24, but it is her husband who is

![image](https://cloud.githubusercontent.com/assets/22382144/23717655/a75ef92a-0402-11e7-81ec-e5f9542e5556.png)

**Comment by bradatkins** [comment]
Fixed, but is one really leaving July 24th and one is leaving September?  July and September seem to be quite a ways apart :)

**Comment by chris206** [comment]
it is unusual, but occasionally the case
