### ISSUE TITLE
2016 Dates in the DB for Series Tours

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#197]
Hi Brad,

Can you create a space between the 2015 and the 2016 dates? and word it '2016 Departures'?

![image](https://cloud.githubusercontent.com/assets/10079829/6254045/a394f9bc-b773-11e4-9aff-9581a53e117f.png)

**Comment by Sandra206** [comment]
Having a different color in the background would help it stand out.

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/7826949/1222a100-03ef-11e5-9421-5be68c854f47.png)

**Comment by Sandra206** [comment]
Can it say 2016 dates?

Feel free to contact me with any questions.

With Kind Regards,

Sandra Lippold
Director of Operations
206 Tours<x-apple-data-detectors://0/0>
333 Marcus Boulevard<x-apple-data-detectors://0/0>
Hauppauge, NY 11788<x-apple-data-detectors://0/0>
Phone: (631) 361-4644<tel:(631)%20361-4644> or (800) 206- 8687<tel:(800)%20206-%208687>
E-mail: sandra@206tours.com<mailto:sandra@206tours.com>
www.206tours.com<http://www.206tours.com/>

On May 26, 2015, at 9:35 PM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/8440255/7826949/1222a100-03ef-11e5-9421-5be68c854f47.png>

**Comment by bradatkins** [comment]
Ronen, can you send me the HTML you want for this? Thanks

**Comment by Sandra206** [comment]
That or that it just generates a new label with new tracking.

We only get billed by fedex if the label is scanned. So if one is created and never used its no big deal.

Feel free to contact me with any questions.

With Kind Regards,

Sandra Lippold
Director of Operations
206 Tours<x-apple-data-detectors://0/0>
333 Marcus Boulevard<x-apple-data-detectors://0/0>
Hauppauge, NY 11788<x-apple-data-detectors://0/0>
Phone: (631) 361-4644<tel:(631)%20361-4644> or (800) 206- 8687<tel:(800)%20206-%208687>
E-mail: sandra@206tours.com<mailto:sandra@206tours.com>
www.206tours.com<http://www.206tours.com/>

On Jun 6, 2015, at 9:29 AM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Ronen, can you send me the HTML you want for this? Thanks
