### ISSUE TITLE
final payment reminders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1971]
Are they being emailed out based on Order Status? I can't remember.

425692 was PIF in February but received a Reminder yesterday...and her order status says deposit

![image](https://cloud.githubusercontent.com/assets/8440903/23856336/b3fdc712-07cf-11e7-8edf-14ea6d1be0a2.png)

**Comment by bradatkins** [comment]
It's based on balance...not status.

Can you email me the reminder please

**Comment by bradatkins** [comment]
The DB wasn't taking into account Promotions. Fixed.
