### ISSUE TITLE
428009 Changed Post-Stay Add-on without Audit Record

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1975]
Hey Brad,

Client signed up with 2 day post-stay,
For some reason, they now have 1 night post-stay?

Did this happen by accident when the add-cost transfers were removed? Thats just my guess because they open together, but there is no record of this change

**Comment by bradatkins** [comment]
I tried to look it up in smartlook; however, it isn't showing there.

Do you know what browser Melissa uses?

**Comment by bradatkins** [comment]
Fixed. You'll need to fix the order
