### ISSUE TITLE
Sound Search Problem

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1976]
Literal spellings should take precedence over potential sound similarities.

It seems like we have the order flipped - where "Mayhall" would come before Tamayo because they both sound similar to "Tamayo". Neither one has a higher priority than the other.

![image](https://cloud.githubusercontent.com/assets/22382144/23922581/4922e20a-08d9-11e7-81d0-a139eda60eab.png)

![image](https://cloud.githubusercontent.com/assets/22382144/23922587/4fa7ac14-08d9-11e7-81cd-7f66b7cf41d7.png)

**Comment by bradatkins** [comment]
It was sorting that way because of the Tour #. The DB was sorting by: Tour Series, Ranking, then Tour Number.

I've added in the search "score" which cleans this up

**Comment by chris206** [comment]
great, is it just an average based on a weighted value system?
good idea
