### ISSUE TITLE
Default Departure City for www.pilgrimages.com

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#198]
Hi Brad,

Can you please change the automatic default city from New York to 'Choose a Departure City'

thank you.

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Thank you!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
