### ISSUE TITLE
Update Order to Send Flights Through Amadeus (Sammie)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1980]
Flight Itineraries are ALL requiring update with no change in order to connect itinerary to order

This is Urgent because, every time they update order, cities are reseting to NY.

![image](https://cloud.githubusercontent.com/assets/22382144/23970287/b5c12270-099f-11e7-917a-8defd9f901a1.png)

-------------------- 
Session ID: f24d85b6b6e2711f717ad768a42d903d 
Time: 16:48:14

**Comment by bradatkins** [comment]
Why do we think an order update is required to connect the flight itinerary?

**Comment by bradatkins** [comment]
I've fixed the departure city thing, but I'm still curious to see an order where you have to click the update. I know it'd happen from time to time, but shouldn't be the case for every order.

**Comment by chris206** [comment]
I wanted you to look at Sammie's DB session Time: 16:48:14 to see that all itineraries had the "broken" icon  until she went in to update,

**Comment by bradatkins** [comment]
So what's happening is at the time we are getting the PNR, there's a name mismatch. What then happens a little later is one of two things:

1) The name is corrected in Amadeus
or
2) The name is corrected in the DB

This then allows the itinerary to go through.

If for "every" order then there's an issue, but my guess is it's only happening on some

**Comment by chris206** [comment]
Ok, understood.

I think that mis-match needs to be a bit less sensitive. For example - with spaces.

If there is a space after "robert **"**, but we have "robert" in amadeus - there shouldnt be a mismatch.

**Comment by chris206** [comment]
Also - can we not allow special characters in the "Name as per passport" section? No hyphens, apostrophe's, periods, etc
People are putting apostrophe's and it is screwing up the amadeus key.

**Comment by chris206** [comment]
Also - can we not allow special characters in the "Name as per passport" section? No hyphens, apostrophe's, periods, etc
People are putting apostrophe's and it is screwing up the amadeus key.

You can allow them to enter the characters, just don't record them - record spaces instead

**Comment by chris206** [comment]
just sn update with yuor thoughts on these changes. I think theyd go a long way

**Comment by bradatkins** [comment]
I think it doesn't matter, actually, because for some reason I'm not using that field?? I'm just using their first middle last name fields?

**Comment by chris206** [comment]
What field?

I was talking about characters in First, Middle and Last Name fields.

For example:

John Brown O'Hara

If I leave a space after "John" in the first name field, it stays in the reservation and causes a name mismatch.

If someone enters an apostrophe in the last name field "O'Hara", we get a name mismatch because amadeus doesnt allow that character.

**Comment by bradatkins** [comment]
I'll check the space thing; however, the DB won't let you type in the apostrophe...or anything not a regular alphabetical character...

**Comment by bradatkins** [comment]
OK I've added code so you can't have a leading or trailing space...

**Comment by chris206** [comment]
ok great - everyone is still complaining that we have to update EVERY one.

It may not be EVERY one, but it feels like it, so something has changed

**Comment by bradatkins** [comment]
If you grab me a handful of orders I can check and see if there's a pattern

**Comment by chris206** [comment]
ok, ive asked that they send them and not fix them

**Comment by bradatkins** [comment]
I think I found out what may have been causing erroneous name mismatch flags

For whatever reason, when the order was updated the DB was checking if there was a matching PNR for the PAX. If there was no matching PNR the DB was setting the name mismatch flag.

This will only stop the annoyance (hopefully) for orders going forward.

**Comment by chris206** [comment]
ahh that makes sense. Annoying, but one step further.

I know that the mismatch icon doesnt actually mean that the itinerary wont compile - is there a way to open in new tab and have it compile, but it wont if you just left click on it?

**Comment by chris206** [comment]
ahh that makes sense. Annoying, but one step further.

I know that the mismatch icon doesnt actually mean that the itinerary wont compile (ive added the non-working account and order number to a working fight itinerary and it compiles) - is there a way to open in new tab and have it compile, but it wont if you just left click on it?

**Comment by chris206** [comment]
Sandy is having the issue with spaces still - also, the special characters should be dropped once client hits submit.

![image](https://cloud.githubusercontent.com/assets/22382144/24171687/d1a114a8-0e5b-11e7-8756-0efa422f6368.png)

**Comment by bradatkins** [comment]
This order was put in before I put the trimming of blank space in, that's why it got through.

I've put in the code in the editing of an order to trim the whitespace as well.

As for the Apostrophe, Caterina actually added it back in :)

I've added the code in the admin to remove it.

**Comment by chris206** [comment]
Even if someone types an apostrophe or any character - it should overwrite the save with a "delete" value.

For example, O'DOYLE could save as ODOYLE.

Alternatively, you could overwrite the save with a "space" value
For example,  O'DOYLE could save as O DOYLE

I dont think it matters. Spaces should just not register as a discrepancy because they dont register as discrepancies in Amadeus

**Comment by chris206** [comment]
Even if someone types an apostrophe or any character in the DB - it should overwrite the save with a "delete" value. They type it, so they dont have to modify their behavior - but that character just doesn't save because we've corrected their bad behavior for them.

For example, O'DOYLE could save as ODOYLE.

Alternatively, you could overwrite the save with a "space" value
For example, O'DOYLE could save as O DOYLE

I dont think it matters. Spaces should just not register as a discrepancy because they dont register as discrepancies in Amadeus

**Comment by chris206** [comment]
Even if someone types an apostrophe or any special character in the TSA Name field - it should overwrite the save with a "delete" value. They type it, so they dont have to modify their behavior - but that character just doesn't save because we've corrected their bad behavior for them.

For example, O'DOYLE could save as ODOYLE.

Alternatively, you could overwrite the save with a "space" value
For example, O'DOYLE could save as O DOYLE

I dont think it matters. Spaces should just not register as a discrepancy because they dont register as discrepancies in Amadeus

**Comment by bradatkins** [comment]
Agreed, I hadn't put that code in the ADMIN side. It was there on the registration side. It is now in both
