### ISSUE TITLE
booking section - land only issue

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1981]
Hi Brad,

This tour is only offering land only, but that is not being reflected on new format:

DB CODE: MB122217

Old site:
www.pilgrimages.com/holyspiritseminary

![image](https://cloud.githubusercontent.com/assets/10079829/23997499/f046e21c-0a27-11e7-8906-fb094c303b36.png)

New site:
www.pilgrimages.com/holyspiritseminary/index34.htm

![image](https://cloud.githubusercontent.com/assets/10079829/23997510/fa9295e0-0a27-11e7-96ec-4a266bbf02aa.png)

**Comment by bradatkins** [comment]
Fixed; however, is the correct departure date Thursday Dec 21? This may be a bug in both versions

![image](https://cloud.githubusercontent.com/assets/8440255/24014444/59c01550-0a5b-11e7-95d2-3885e8bf8c64.png)

**Comment by ronenreinheimer** [comment]
TY!
