### ISSUE TITLE
#428120 CAD pricing is wrong-invoice is not correct 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1983]
Hi Brad, 
Can you please adjust this invoice to show correct amount/pricing ? as per below. 

![image](https://cloud.githubusercontent.com/assets/14838466/24013669/92709f3a-0a58-11e7-98c2-17055791aa51.png)

![image](https://cloud.githubusercontent.com/assets/14838466/24013632/6aac8252-0a58-11e7-8c31-a4caa8e31997.png)

**Comment by bradatkins** [comment]
That value is correct, as the CAD value changes.

This order was placed at 1.34 conversion rate.

What you are seeing is the current rate (today) of 1.33

**Comment by Irena206** [comment]
Is there any way we can reverse ?

**Comment by bradatkins** [comment]
Reverse? I'm confused. It's the correct exchange rate at the time?

**Comment by Irena206** [comment]
OK sorry, they say its fine now, client is saying that is OK and we just processed one payment .
Lets close the issue.
Thanks !
