### ISSUE TITLE
Please change email wording and re-add name tag

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1984]
Dear PILGRIM,

Thank you for booking with 206 Tours! Below you will find a copy of your invoice.

Please carefully review the information provided. If any update are required, you may contact us via email at orders@206tours.com , by phone at (631) 361-4644 or (800)206-8687. Our Staff will be at your service to answer any questions or concerns you may have regarding your reservation.

You may also log into your account at www.206tours.com/register/loginaccount to make any updates to your profile, upgrades, add pre and/or post stays, make payments or view your invoice. 
Closer to the pilgrimage you will be able to view your pilgrimage info as well as flight schedule and tracking information for your package.

206 Tours is committed to doing everything possible to meet your expectations and to provide you with a well planned pilgrimage tour, so that its fruits will last a lifetime.

All of us at 206 Tours are looking forward to serving you.

**Comment by bradatkins** [comment]
This is when an order is placed?

**Comment by chris206** [comment]
Yes

**Comment by bradatkins** [comment]
Done.

And it can be modified here:

![image](https://cloud.githubusercontent.com/assets/8440255/24072186/6edcc366-0bb9-11e7-887e-542261b4f735.png)
