### ISSUE TITLE
Unable to Change Base Price SH030118 (Liz) - Urgent

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1985]
We've lowered the base cost of this pilgrimage to $4899.

Liz has been attempting to manually go into each Air & Land order and update to current base pricing, but no matter what she does, the base price doesn't change for anyone and remains at $3999

I remember having this issue previously - where "change to current pricing" was unresponsive to order updates. I remember that you fixed it immediately and didnt understand why we were being so daft, which is understandable. Now that we have the ability to look back in video, can you please look at Liz's session from 11:35 AM to watch that no matter what she selects, the update does nothing?

**Comment by chris206** [comment]
correction - price should be $4899

**Comment by bradatkins** [comment]
I do not see any orders with this Tour #? SH030118

**Comment by chris206** [comment]
sorry! SH010318

**Comment by chris206** [comment]
426684
426686
427054

these are the 3 that arent changing and need to be lowered. please let me know if the glitch cannot be fixed today

**Comment by bradatkins** [comment]
These orders are associated to an inactive departure. I've moved them over to the active one.

**Comment by bradatkins** [comment]
I also found 427111 .

You will now be able to go in, and set Honor Price = N and update the order.
