### ISSUE TITLE
Need to Re-Assign Order 427720 to Account 33915

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1988]
I would help if accounting could re-assign orders under **inactive** accounts to **active** accounts

![image](https://cloud.githubusercontent.com/assets/22382144/24104217/081358de-0d58-11e7-9c7a-5921d0d30433.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24104338/614b9376-0d58-11e7-92b7-56dcc73e37a8.png)

**Comment by bradatkins** [comment]
Done

**Comment by chris206** [comment]
can I do this? it seems like it could be simple - just changing account association.

**Comment by bradatkins** [comment]
It is simple, but there is no screen for it. I did it in the backend
database

**Comment by chris206** [comment]
What about here? We could just type in the account number that we want, maybe it could show first and last name in a scroll down menu

Like this:

427720 - Esther Nardino

![image](https://cloud.githubusercontent.com/assets/22382144/24121231/f4a44fd4-0d8d-11e7-96e6-eef65cd0616e.png)

**Comment by chris206** [comment]
What about here? We could just type in the account number that we want, maybe it could show first and last name in a scroll down menu

Like this:

33915 - Esther Nardino

![image](https://cloud.githubusercontent.com/assets/22382144/24121231/f4a44fd4-0d8d-11e7-96e6-eef65cd0616e.png)

**Comment by bradatkins** [comment]
Sorry, there's lots of screens we can add it to, it just doesn't exist on any.

**Comment by chris206** [comment]
ok, no problem.

We could seriously tidy up the DB with this. If it is a rare need though, it wouldnt be worth the time

**Comment by bradatkins** [comment]
This is the first time anyone has requested this
