### ISSUE TITLE
Departure Calendar Missing SM042717

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1989]
Why is my calendar missing my most important departure in May: SM042717

I'm listed as handler, it is active and open - is it a glitch?

![image](https://cloud.githubusercontent.com/assets/22382144/24105468/57bfd0c6-0d5b-11e7-95d8-d210b56db519.png)

**Comment by bradatkins** [comment]
Found the issue. Investigating the fix

**Comment by bradatkins** [comment]
Fixed. For some reason the someone entered the tour name enclosed in quotes..
