### ISSUE TITLE
dates and prices not showing up for a new series tour

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1994]
Hi Brad,

DB code **90**

any idea why the dates and prices not showing up?
http://www.206tours.com/tour90/index34.htm

![image](https://cloud.githubusercontent.com/assets/10079829/24203566/7fac3074-0eec-11e7-8b76-e982d96bd077.png)

**Comment by bradatkins** [comment]
Looks OK on tour 208. Grab it's HTML and start from there. Doesn't look like a DB Problem.

Please don't put URGENT unless it's a wide ranging problem.

**Comment by ronenreinheimer** [comment]
looks like it resolved itself
