### ISSUE TITLE
SM042717 | STEP random name redundancy

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1995]
The auto-compling STEP list randomly duplicates names in a similar way to the arrival departure list

![image](https://cloud.githubusercontent.com/assets/22382144/24213223/151346dc-0f08-11e7-84de-0ad3daf9acf4.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24213175/f6f29392-0f07-11e7-9446-29505de9bd25.png)

**Comment by bradatkins** [comment]
Fixed
