### ISSUE TITLE
SM042717 | Arrival Departure list duplicates names

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1996]
Why do clients appear a random number of times?

Can you correct that underlying issue?
 
![image](https://cloud.githubusercontent.com/assets/22382144/24213256/378ebb88-0f08-11e7-8e0a-c5e7ccbc1f45.png)
--------------------
Session ID: 9d68cbdd1ec2ba1a7baa0f3159481a0f
Time: 13:55:33

**Comment by bradatkins** [comment]
Fixed
