### ISSUE TITLE
"Donation" showing as Booking # when it wasn't a Donation???

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#201]
Instead of it saying Donation under # box, it should say 417722

![image](https://cloud.githubusercontent.com/assets/8440903/6275082/73b31800-b84a-11e4-8d24-81dd070ab7ec.png)

How does that even happen when applying a normal payment and payment donation drop down box is selected as No?
![image](https://cloud.githubusercontent.com/assets/8440903/6275122/b81935c4-b84a-11e4-8fd1-575c1ee43c31.png)

**Comment by bradatkins** [comment]
How would you like to note it's a donation?

**Comment by bradatkins** [comment]
[image: Inline image 1]

**Comment by bradatkins** [comment]
Ok it will not show Donation, and it's live now
