### ISSUE TITLE
Waitlisted Passengers Should Not be on Yellow Sheet (Sandra)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2012]
SH050917 - 426874

Waitlisted Clients Shouldnt appear on Yellow Sheet.

They dont appear on Name or Rooming List.

We use Yellow Sheet to issue tickets, hence the urgency - If we incorrectly issue air, we are out alot of money

**Comment by chris206** [comment]
It's also appearing in registered passengers. Probably shouldn't be here. 

We are trying to figure out where it would be best 

![image](https://cloud.githubusercontent.com/assets/22382144/24426473/c41424a4-13d5-11e7-96d1-8a2f073d7299.png)
![image](https://cloud.githubusercontent.com/assets/22382144/24426478/c8c8029a-13d5-11e7-9043-def2f0c040c5.png)

**Comment by bradatkins** [comment]
Removed from both places

**Comment by chris206** [comment]
SM042717 still lists wait listed passengers on rooming list

![image](https://cloud.githubusercontent.com/assets/22382144/24711686/a68808fa-19ee-11e7-8d74-ad70b4beeae2.png)

**Comment by bradatkins** [comment]
Fixed
