### ISSUE TITLE
DB is REALLY slow right now

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#202]
Is there anything you can do to speed it up? Reset anything?

Thanks!

**Comment by bradatkins** [comment]
It seems to come and go. I just noticed it took you 49 seconds to load the
payments screen, I just did it and it took "0 seconds".

This isn't related to the speed of your internet.

Can you try again?

**Comment by ali206** [comment]
I didn't mean for me specifically with the payments page - though that's still a problem. The only time the payment screen takes forever is after i make a change to, or approve a payment.  

Rinda said in General the DB is very slow today.
