### ISSUE TITLE
Currency when client logs in

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#2020]
This guys lives in Canada and is paying in CAD so when he logs in to his account shouldn't he only see CAD currency?

![image](https://cloud.githubusercontent.com/assets/8440903/24553277/c0111546-15f7-11e7-9598-1bac66f2772a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/24553299/cffefb80-15f7-11e7-8e2a-a20bd11c3f43.png)

**Comment by bradatkins** [comment]
Oddly enough it actually was. There was a bug where in the admin it wasn't applying the currency conversion to the Promotion value
