### ISSUE TITLE
Deepening USER/ADMIN Distinctions (Sandra)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2022]
USERS should have selectable privileges, such as "Developer", or "Advanced User"

This would allow selected users access beyond the basic.

It could also allow us to tidy up the basic view to only features that are widely used and helpful.

For Example:

New employees dont need access to as much as they have - in fact, it is confusing and raises the learning curve. A Basic View could be selected for them with just a few tools, then later expanded once they got the hang of it.

Developers (like me and Ronen) need access to messaging, administrative, but not to the ability to confirm payments or zero out orders.

It doesn't need to be complex, but in the User Profile, we could Asterisk features that would be viewable to each user. We dont need to go crazy, but some additional nuance would be helpful

**Comment by bradatkins** [comment]
Please identify the screens Users and "Advanced Users" would have.

**Comment by chris206** [comment]
Well, maybe we would just need USERS and then a box to limit the views for beginners, and a box to expand the view for Developers.

Regular Users should not view 

![image](https://cloud.githubusercontent.com/assets/22382144/24559532/0eee0984-160d-11e7-823d-05ad6d15f9a3.png)

**Comment by chris206** [comment]
Well, maybe we would just need USERS and then a box to expand priveleges to "advance user" or expand further to "developer"

Regular Users should not view the highlighted

![image](https://cloud.githubusercontent.com/assets/22382144/24559628/66061ab8-160d-11e7-8ec7-8decabd336b3.png)

**Comment by chris206** [comment]
Well, maybe we would just need USERS and then a box to expand priveleges to "advance user" or expand further to "developer"

This is going to take me a little time - anything NOT highlighted should be what a USER with "advanced" privileges sees.

I will need to whittle down to what a basic user would see later, and build up for what a developer would see.

![image](https://cloud.githubusercontent.com/assets/22382144/24559628/66061ab8-160d-11e7-8ec7-8decabd336b3.png)
