### ISSUE TITLE
Replace Invoice Insurance Info (Irena)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2024]
We just need to replace the Highlighted Insurance info ASAP with:

Travel Insured International at 844-228-3679

Plan Code T-20010

![image](https://cloud.githubusercontent.com/assets/22382144/24563053/22c52880-161b-11e7-8d92-0506b9543170.png)

**Comment by bradatkins** [comment]
Done, but are the rates changing?

**Comment by chris206** [comment]
I dont believe so - the tables were updated months and months ago, I think we just never noticed on our end.

**Comment by chris206** [comment]
Also, thanks for the fast answers - I thought you were busy today?
I dont like interrupting personal time, it hurts to have to do it.

**Comment by bradatkins** [comment]
I had a small window of a break :)
