### ISSUE TITLE
Discounts not appearing in RECAP (SC050417 - Elise)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2025]
Not urgent, but I cant figure it out and haven't seen it yet.

Discounts are not reflecting in the Recap **but** show PIF in invoice.

![image](https://cloud.githubusercontent.com/assets/22382144/24564793/34c5101c-1621-11e7-8263-46c0a0c9056f.png)

**Comment by chris206** [comment]
I'm just thinking - if clients are not marked as "PIF", then they are likely getting payment reminders even though their invoice says "Paid in Full" right?

I dont want clients to be upset.

**Comment by bradatkins** [comment]
No...it's actually based on amount paid, not order status

**Comment by bradatkins** [comment]
Fixed
