### ISSUE TITLE
424508 - state needs to be adjusted

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#2029]
Something very odd happened with this booking's address....

Her name and info was showing correctly but her address was in Canada and she had no idea where that was coming from. 

I clicked on her name in view orders and it popped up with your name and information. 

I adjusted it in all passengers but I don't have any US state options to select from, only canadian. 

She's from Nebraska if you can change it please.

![image](https://cloud.githubusercontent.com/assets/8440903/24619961/e3815cec-1869-11e7-8cf1-05fe3a25efba.png)

Also - she made a full payment yesterday of around $14,000 but DB only charged her $7599

**Comment by bradatkins** [comment]
Already on it
