### ISSUE TITLE
Uploading Docs to bookings

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#203]
Uploading is working but when you login on the clients side and click on the document it just brings you to our website??

**Comment by ali206** [comment]
As per Rinda's email she just copied you in she used:

I used : mnovkovic@maritimetravel.ca & 206tours as password

![rinda](https://cloud.githubusercontent.com/assets/8440903/6289499/98cc5d28-b8ee-11e4-958e-9bf14e17e83b.png)

![rinda 2](https://cloud.githubusercontent.com/assets/8440903/6289502/9cc08814-b8ee-11e4-889b-c3743f95d19c.png)

**Comment by bradatkins** [comment]
Fixed
