### ISSUE TITLE
home page slider images preview

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#2034]
hi brad,

can you make these links clickable, so i can get a quick preview of what the banner looks like.

thank you.

![image](https://cloud.githubusercontent.com/assets/10079829/24675362/dc132e84-194c-11e7-8f98-7805cc4caebd.png)

![image](https://cloud.githubusercontent.com/assets/10079829/24675396/f90a28da-194c-11e7-96ae-df163db08600.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
YOU DA BEST!
