### ISSUE TITLE
Password Retrieval Issues - Requires Review

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2037]
These clients shouldn't be having problems - their accounts are active and the emails match. Can you see if the emails are being sent?

![image](https://cloud.githubusercontent.com/assets/22382144/24710075/ff37488a-19e9-11e7-9bc0-2e320bfce451.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24710087/06a87b0c-19ea-11e7-8c27-7cbcd5f60e3f.png)

**Comment by bradatkins** [comment]
Hmm. I just tried it myself and it worked fine?

![image](https://cloud.githubusercontent.com/assets/8440255/24731788/4d012c16-1a3a-11e7-887f-3f112b808340.png)

**Comment by chris206** [comment]
ok, they just came in back to back so I was wondering if the emails were stuck somewhere
