### ISSUE TITLE
Unable to Modify Messages - Really important

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2039]
Nobody is able to modify client/internal messages. They arent saves and we cannot change them at all, nobody can.

It is not isolated to me or to the browser we are using.

A number of our new features are here and we haven't been able to use them because of this glitch.

Can you log in and try to modify them?

**Comment by bradatkins** [comment]
Can you take a screenshot please

**Comment by chris206** [comment]
--------------------
Session ID: def97d81ac979cb97fbb74f634e66abb
Time: 10:04:53


![image](https://cloud.githubusercontent.com/assets/22382144/24758566/c6d1d9a2-1ab0-11e7-8544-527f0d8ddf62.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24758574/ca7806c6-1ab0-11e7-8de8-fab82a269ec8.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24758583/ce522fba-1ab0-11e7-820a-d402c41aabeb.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
fantastic!
