### ISSUE TITLE
Final Payment Reminders - Revised

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2041]
As discussed previously, we will need final payment reminders to go out - each with different wording.

1. 10 Days **Before** Final Payment Date: "Final Payment Reminder" (we already have this with built in rules, we just need to shift when it is sent)

2. 10 Days **After** final payment date: "Overdue Final Payment Reminder" (I think it would be the same rules, just shift it to be sent 10 days AFTER the date and have Overdue added to the subject line)

**Comment by bradatkins** [comment]
1) This is already in place

2) I've added this but disabled it until you go into the messages section and modify the message. Once you're ready let me know

![image](https://cloud.githubusercontent.com/assets/8440255/24780583/7aceed50-1b06-11e7-9ab4-5caedd6d4af3.png)

**Comment by chris206** [comment]
1. Oh, ok - thats great.
2. Go ahead and activate it, wording is fine. If Sandy wants to alter it she can do so any time.

**Comment by bradatkins** [comment]
I've enabled it. If you know of any orders in this situation, please let me
know so I can validate it's working.
