### ISSUE TITLE
Add File to Group Request Broken - links to Error page/Home Page

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2049]
Add File to Group Request Broken - links to Error page/Home Page

Please take a look at my session
--------------------
Session ID: 1cdf030d40240ea1feec933128638276
Time: 10:39:12

**Comment by bradatkins** [comment]
Hmm I was able to do it just fine. What type of file are you uploading?

**Comment by bradatkins** [comment]
Actually just saw it...fixed the issue

**Comment by chris206** [comment]
fantastic
