### ISSUE TITLE
SD Discounts

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#205]
I thought this was working correctly (as in showing in view payments) but it doesn't seem to be. 

Melissa created this order for this SD.  After confirming him, his SD Discount popped up twice so his invoice was showing as overpaid. 

the only way to fix it is by declining the SD Discount that shows up in View Payments, which defeats the purpose of being able to edit the amount if need be. 

![image](https://cloud.githubusercontent.com/assets/8440903/6330145/f0dd4dcc-bb43-11e4-8d97-a0b20b02213d.png)

**Comment by ali206** [comment]
Also happened with this booking 418201 - Melissa went to add insurance and discount popped up a 2nd time causing an "overpayment" and the only way to fix that is by declining the SD discount in payments.

**Comment by bradatkins** [comment]
I only see 1 SD discount in the payment section?

![image](https://cloud.githubusercontent.com/assets/8440255/6383950/29ab677e-bd24-11e4-8ba1-cb2678c40eea.png)

**Comment by ali206** [comment]
Right, b/c the other one never shows up remember? That was the original issue, that i could not edit the amount of the SD Discount that was automatically applied in the DB when registered SD's.

If you look at the invoice, you'll see that amount is not in view payments.

**Comment by bradatkins** [comment]
OK it's fixed:

![image](https://cloud.githubusercontent.com/assets/8440255/7717510/cbbefae8-fe70-11e4-8a69-dc21a44ce6dd.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7717513/d12e7666-fe70-11e4-926e-6b511afd69c3.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7717514/d5a0b858-fe70-11e4-9feb-84ef207fd3e4.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7717517/da61b130-fe70-11e4-8010-3118de9eb17b.png)

**Comment by ali206** [comment]
This is still happening as per above: Booking #419518

Melissa created this order for this SD. After confirming him, his SD Discount popped up twice so his invoice was showing as overpaid.

the only way to fix it is by declining the SD Discount that shows up in View Payments, which defeats the purpose of being able to edit the amount if need be.

**Comment by ali206** [comment]
Just sent you an email from Melissa showing the steps she took to register and at what point the dble discount showed up

From: Melissa Mulligan 
Sent: Monday, June 29, 2015 3:20 PM
To: Ali Boulanger
Subject: Please See Priest Registration Process | Double Discount

Dear Ali, 

                As per our conversation I took some screen shots as I registered a priest.  He has already travelled with us before and was in all travelers.  Everything went fine until I went back into the record to add insurance it duped the discount.  Please see as follows:

**Comment by ali206** [comment]
Melissa just tried to register this priest as an SD and the only thing that comes up is clergy discount:
![image](https://cloud.githubusercontent.com/assets/8440903/9638362/5d434720-5174-11e5-8f35-58e12ee76f3e.png)

420159 - showing dupe ins.

Math wrong on this one:
![image](https://cloud.githubusercontent.com/assets/8440903/9638432/be67bbc6-5174-11e5-8a58-bc52b31f5841.png)

**Comment by ali206** [comment]
SD discount applied but not deducting from invoice?
![image](https://cloud.githubusercontent.com/assets/8440903/9640096/c1de8574-517d-11e5-9635-1d612fa740ea.png)

**Comment by bradatkins** [comment]
I don't see him on this invoice anymore and I think SD Discounts are working ok if I'm not mistaken
