### ISSUE TITLE
Email not being sent to account email or ROK@206 Tours - 426827

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2054]
DB sent to client, rok never recieved a copy
But I got it when I sent it to myself

![image](https://cloud.githubusercontent.com/assets/22382144/24880929/3c498be2-1e0a-11e7-971e-e677d962f9fe.png)

**Comment by bradatkins** [comment]
Sorry, there must be something else up, as I can confirm from the email server it sent a copy to rok@

![image](https://cloud.githubusercontent.com/assets/8440255/24984259/4163deb4-1fba-11e7-83cb-7d5668bdcfd6.png)

**Comment by chris206** [comment]
Good enough for me. I'll close this and open another if it is an issue again.
