### ISSUE TITLE
PNR MisMatch due to Suffix? (Liz 426775)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2058]
I used the blocked passenger's ID: 25333855
And substituted it in passenger ID for his wife (whose itinerary is working)

It populated - but the suffix seems to be creating the disconnect and it goes beyond just this order
![image](https://cloud.githubusercontent.com/assets/22382144/24932114/148fefcc-1ede-11e7-8832-a6c164c15f88.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24932130/230a59a2-1ede-11e7-912d-87d8f4252f0f.png)

**Comment by chris206** [comment]
It is definitely the suffix her is another example - 428151

We were having a hard time getting the ticket number to appear on this guys itinerary - so I blanked out the suffix box and just typed "III" after his last name. All data imported. 

When I changed it back - data broke again. Is it the period in the drop-down that is screwing it up?

![image](https://cloud.githubusercontent.com/assets/22382144/24976177/6e335e20-1f96-11e7-940b-85e29efe3d41.png)

![image](https://cloud.githubusercontent.com/assets/22382144/24976184/7335d7c2-1f96-11e7-8aae-1b3e4581437c.png)

**Comment by bradatkins** [comment]
Yup, makes sense. The DB isn't matching with the suffix. I'll add it in.

**Comment by bradatkins** [comment]
OK I've added the suffix now.

**Comment by chris206** [comment]
![image](https://cloud.githubusercontent.com/assets/22382144/24979740/5b2b78a0-1fa3-11e7-8d38-28f75726c6f0.png)

still not working BUT I can use my work-around using the passenger number. Maybe just dont mis-match f the client has a value in the suffix drop-down? go straight to itinerary

**Comment by bradatkins** [comment]
This should be OK. let me check

**Comment by bradatkins** [comment]
Missed a spot, fixed

**Comment by chris206** [comment]
Both of them are still broken.

![image](https://cloud.githubusercontent.com/assets/22382144/25007202/94ec1876-202d-11e7-9062-7e4e3c583c3a.png)

![image](https://cloud.githubusercontent.com/assets/22382144/25007208/9981c070-202d-11e7-8638-d370dcb8c01e.png)

**Comment by bradatkins** [comment]
Ahh geez. I was fixing it for the part as PNR's came in.

This was missing when updating the order. Fixed

**Comment by chris206** [comment]
Wahoo!
