### ISSUE TITLE
Order Audit Report

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#206]
Is not correct for most bookings in general that i've looked at

Ex:

My name is the last line and there's nothing next to it but I declined an approved payment
![image](https://cloud.githubusercontent.com/assets/8440903/6330199/5b62d504-bb44-11e4-886f-edb6751fa4a5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6330233/8f92c3b6-bb44-11e4-908c-8cadba386171.png)

**Comment by bradatkins** [comment]
Fixed for changes going forward, the donation stuff broke it.

![image](https://cloud.githubusercontent.com/assets/8440255/6341991/c5066150-bb9f-11e4-94ce-fc0dafb4ab10.png)
