### ISSUE TITLE
Split Record RM Amadeus Issue

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2063]
So these 5 passengers had working pnr's and then I split 2 from the record onto a new pnr.
The 3 remaining passenger records broke?

![image](https://cloud.githubusercontent.com/assets/22382144/25096676/41133bd6-236f-11e7-9b3c-f2f64c83189d.png)

I cant really understand why. Here is the record info for the 2 paradis pilgrims (the only idea I have is the mention of the former pnr at the ver ybottom:

--- TST TSM AXR RLR MSC SFP ---                                                 
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1706Z   63WHY6                 
  1.PARADIS/JOANNE MARIE   2.PARADIS/JOSEPH ROBERT                              
  3  LH 425 S 09MAY 2 BOSMUC HK2        E   820P 945A+1 *1A/E*                  
  4  LH 688 S 10MAY 3 MUCTLV HK2        2  1205P 440P   *1A/E*                  
  5  LH 695 V 18MAY 4 TLVFRA HK2        3   800A1130A   *1A/E*                  
  6  LH 422 V 18MAY 4 FRABOS HK2        1   105P 305P   *1A/E*                  
  7 AP NYC 631 361-4644 - 206 TOURS - A                                         
  8 AP 8002068687-O                                                             
  9 AP #CCT#DE#ETX                                                              
 10 APE ACCOUNTING@206TOURS.COM                                                 
 11 APE ACCOUNTING@206TOURS.COM/SPONSOR                                         
 12 TK OK30MAR/NYC1S21JQ//ETLH                                                  
 13 /SSR RQST LH HK2 BOSMUC/25BN,P1/25CN,P2/S3   SEE RTSTR                      
 14 /SSR RQST LH HK2 MUCTLV/16CN,P1/16BN,P2/S4   SEE RTSTR                      
 15 SSR RQST LH HK2 TLVFRA/23CN,P1/23BN,P2/S5   SEE RTSTR                       
 16 /SSR RQST LH HK2 FRABOS/31DN,P1/31EN,P2/S6   SEE RTSTR                      
 17 SSR OTHS 1A PLS ISS AUTOMATIC TKT BY 26APR17/2359Z OR LH                    
       OPTG/MKTG SEGS WILL BE XLD. APPLIC FARE RULE APPLIES IF                  
       IT                                                                       
 18 SSR OTHS 1A ///DEMANDS EARLIER TKTG.                                        
 19 SSR DOCS LH HK1 P/US/469805746/US/12NOV53/F/24MAY20/PARADIS/                
)>m
--- TST TSM AXR RLR MSC SFP ---                                                 
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1706Z   63WHY6                 
       JOANNE/MARIE/P1                                                          
 20 SSR DOCS LH HK1 P/US/469852330/US/15JUL54/M/25MAY20/PARADIS/                
       JOSEPH/ROBERT/P2                                                         
 21 SSR DOCO LH HK1 /K/O130607532/P2                                            
 22 SK RESTRICTED                                                               
 23 SK RESTRICTED                                                               
 24 SK RESTRICTED                                                               
 25 SK RESTRICTED                                                               
 26 RC NYC1S21JQ-W/CW                                                           
 27 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE & CHECK-IN:                    
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -                
       GGAMAUSHAZ/S3,6                                                          
 28 RM POS US                                                                   
 29 RM MOP:CREDIT CARD                                                          
 30 RM PNR MODIFIED BY THE END USER (THURSDAY-MARCH-30-2017)                    
 31 RM PNR MODIFIED BY END USER IP_ADDRESS 47.21.136.58                         
 32 RM 423482/P1                                                                
 33 RM 423481/P2                                                                
 34 RM DEAD                                                                     
 35 RM *EMAIL:ACCOUNTING@206TOURS.COM/EN                                        
)>m
--- TST TSM AXR RLR MSC SFP ---                                                 
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1706Z   63WHY6                 
 36 RM *EMAIL:ACCOUNTING@206TOURS.COM/EN/CF3                                    
 37 RM *PCSOFFICE*RECEIVED ON 30.03.2017 22:51H FROM NYCLH08YZ                  
 38 RM *PCSOFFICE*TRAVELINFO FORWARDED ON 30.03.2017 22:51H TO                  
       ACCOUNTING@206TOURS.COM                                                  
 39 FA PAX 220-7993687083/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S3-6/P1                                                                 
 40 FA PAX 220-7993687084/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S3-6/P2                                                                 
 41 FA PAX 220-8211780212/DTLH/USD11.00/30MAR17/NYCLH08YZ/339928                
       36/P2/E14                                                                
 42 FA PAX 220-8211780213/DTLH/USD11.00/30MAR17/NYCLH08YZ/339928                
       36/P1/E14                                                                
 43 FA PAX 220-8211780214/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P2/E13                                                                
 44 FA PAX 220-8211780215/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P1/E13                                                                
 45 FA PAX 220-8211780216/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P2/E16                                                                
 46 FA PAX 220-8211780217/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P1/E16                                                                
)>m
--- TST TSM AXR RLR MSC SFP ---                                                 
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1706Z   63WHY6                 
 45 FA PAX 220-8211780216/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P2/E16                                                                
 46 FA PAX 220-8211780217/DTLH/USD35.00/30MAR17/NYCLH08YZ/339928                
       36/P1/E16                                                                
 47 FB PAX 0000000000 TTP/ET OK ETICKET/S3-6/P1-2                               
 48 FB PAX 0000000000 TTM/M1,2,3,4,5,6/RT OK EMD/P2/E14                         
 49 FB PAX 0000000001 TTM/M1,2,3,4,5,6/RT OK EMD/P1/E14                         
 50 FB PAX 0000000002 TTM/M1,2,3,4,5,6/RT OK EMD/P2/E13                         
 51 FB PAX 0000000003 TTM/M1,2,3,4,5,6/RT OK EMD/P1/E13                         
 52 FB PAX 0000000004 TTM/M1,2,3,4,5,6/RT OK EMD/P2/E16                         
 53 FB PAX 0000000005 TTM/M1,2,3,4,5,6/RT OK EMD/P1/E16                         
 54 FE PAX NONEND/REFRERTEINFOTHRUAGTVLD AC/LH/LX/OS/SN/UA                      
       ONLY-BG:LH/S3-6/P1-2                                                     
 55 FM PAX *F*0.00/S3-6/P1-2                                                    
 56 FP CHECK                                                                    
 57 FT PAX *F*267BR/S3-6/P1-2                                                   
 58 FV PAX *F*LH/S3-6/P1-2                                                      
 59 AB NA-MILANKA LACHMAN/A1-1450 RIDGE RD/ZP-11791/CI-SYOSSET/                 
       ST-NY/CO-US                                                              
  * SP 31MAR/CKSU/NYC1S21JQ-6SN4PN

**Comment by chris206** [comment]
Here is the record for the 3 broken passengers (ignore the RM dead, I put those in when it was already broken - which tends to work, but I think that we are reading 2 pnrs from this record.

--- TST AXR RLR MSC SFP ---                                                     
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1705Z   6SN4PN                 
  1.CARBONE/PATRICIA MARY   2.GOSSELIN/DENISE ANN                               
  3.VELLIQUETTE/JOYCE ANNE                                                      
  4  LH 425 S 09MAY 2 BOSMUC HK3        E   820P 945A+1 *1A/E*                  
  5  LH 688 S 10MAY 3 MUCTLV HK3        2  1205P 440P   *1A/E*                  
  6  LH 695 V 18MAY 4 TLVFRA HK3        3   800A1130A   *1A/E*                  
  7  LH 422 V 18MAY 4 FRABOS HK3        1   105P 305P   *1A/E*                  
  8 AP NYC 631 361-4644 - 206 TOURS - A                                         
  9 AP 8002068687-O                                                             
 10 AP #CCT#DE#ETX                                                              
 11 APE ACCOUNTING@206TOURS.COM                                                 
 12 APE ACCOUNTING@206TOURS.COM/SPONSOR                                         
 13 TK OK30MAR/NYC1S21JQ//ETLH                                                  
 14 SSR OTHS 1A PLS ISS AUTOMATIC TKT BY 26APR17/2359Z OR LH                    
       OPTG/MKTG SEGS WILL BE XLD. APPLIC FARE RULE APPLIES IF                  
       IT                                                                       
 15 SSR OTHS 1A ///DEMANDS EARLIER TKTG.                                        
 16 SSR DOCS LH HK1 P/US//US/21DEC48/F//CARBONE/PATRICIA/MARY/P1                
 17 SSR DOCS LH HK1 P/US/544580981/US/03MAR66/F/09MAY26/GOSSELIN                
       /DENISE/ANN/P2                                                           
 18 SSR DOCS LH HK1 P/US/474682677/US/04OCT92/F/03OCT20/VELLIQUE                
)>m
--- TST AXR RLR MSC SFP ---                                                     
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1705Z   6SN4PN                 
       TTE/JOYCE/ANNE/P3                                                        
 19 SK RESTRICTED                                                               
 20 SK RESTRICTED                                                               
 21 SK RESTRICTED                                                               
 22 SK RESTRICTED                                                               
 23 SK RESTRICTED                                                               
 24 SK RESTRICTED                                                               
 25 RC NYC1S21JQ-W/CW                                                           
 26 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE & CHECK-IN:                    
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -                
       GGAMAUSHAZ/S4,7                                                          
 27 RM 423858/P1                                                                
 28 RM 424310/P2                                                                
 29 RM 423624/P3                                                                
 30 RM POS US                                                                   
 31 RM MOP:CREDIT CARD                                                          
 32 RM PNR MODIFIED BY THE END USER (THURSDAY-MARCH-30-2017)                    
 33 RM PNR MODIFIED BY END USER IP_ADDRESS 47.21.136.58                         
 34 RM DEAD                                                                     
 35 RM *EMAIL:ACCOUNTING@206TOURS.COM/EN                                        
)>m
--- TST AXR RLR MSC SFP ---                                                     
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1705Z   6SN4PN                 
 36 RM *EMAIL:ACCOUNTING@206TOURS.COM/EN/CF3                                    
 37 RM *PCSOFFICE*RECEIVED ON 30.03.2017 22:51H FROM NYCLH08YZ                  
 38 RM *PCSOFFICE*TRAVELINFO FORWARDED ON 30.03.2017 22:51H TO                  
       ACCOUNTING@206TOURS.COM                                                  
 39 FA PAX 220-7993687081/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P1                                                                 
 40 FA PAX 220-7993687082/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P2                                                                 
 41 FA PAX 220-7993687085/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P3                                                                 
 42 FB PAX 0000000000 TTP/ET OK ETICKET/S4-7/P1-3                               
 43 FE PAX NONEND/REFRERTEINFOTHRUAGTVLD AC/LH/LX/OS/SN/UA                      
       ONLY-BG:LH/S4-7/P1-3                                                     
 44 FM PAX *F*0.00/S4-7/P1-3                                                    
 45 FP CHECK                                                                    
 46 FT PAX *F*267BR/S4-7/P1-3                                                   
 47 FV PAX *F*LH/S4-7/P1-3                                                      
 48 AB NA-MILANKA LACHMAN/A1-1450 RIDGE RD/ZP-11791/CI-SYOSSET/                 
       ST-NY/CO-US                                                              
  * SP 31MAR/CKSU/NYC1S21JQ-63WHY6                                              
>m
--- TST AXR RLR MSC SFP ---                                                     
RP/NYC1S21JQ/NYC1S21JQ            CK/SU  17APR17/1705Z   6SN4PN                 
 36 RM *EMAIL:ACCOUNTING@206TOURS.COM/EN/CF3                                    
 37 RM *PCSOFFICE*RECEIVED ON 30.03.2017 22:51H FROM NYCLH08YZ                  
 38 RM *PCSOFFICE*TRAVELINFO FORWARDED ON 30.03.2017 22:51H TO                  
       ACCOUNTING@206TOURS.COM                                                  
 39 FA PAX 220-7993687081/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P1                                                                 
 40 FA PAX 220-7993687082/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P2                                                                 
 41 FA PAX 220-7993687085/ETLH/30MAR17/NYC1S21JQ/33608514                       
       /S4-7/P3                                                                 
 42 FB PAX 0000000000 TTP/ET OK ETICKET/S4-7/P1-3                               
 43 FE PAX NONEND/REFRERTEINFOTHRUAGTVLD AC/LH/LX/OS/SN/UA                      
       ONLY-BG:LH/S4-7/P1-3                                                     
 44 FM PAX *F*0.00/S4-7/P1-3                                                    
 45 FP CHECK                                                                    
 46 FT PAX *F*267BR/S4-7/P1-3                                                   
 47 FV PAX *F*LH/S4-7/P1-3                                                      
 48 AB NA-MILANKA LACHMAN/A1-1450 RIDGE RD/ZP-11791/CI-SYOSSET/                 
       ST-NY/CO-US                                                              
  * SP 31MAR/CKSU/NYC1S21JQ-63WHY6

**Comment by bradatkins** [comment]
OK I've added some code to check for this duplicate PNR issue and fix it if possible.

Try those itineraries again and report back

**Comment by chris206** [comment]
excellent, works great.
What did you clarify?
