### ISSUE TITLE
Web MB122217 (amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#2065]
http://www.pilgrimages.com/holyspiritseminary/

![image](https://cloud.githubusercontent.com/assets/10079829/25135555/b922bcbc-2420-11e7-8cd2-98cdba0e6a47.png)

![image](https://cloud.githubusercontent.com/assets/10079829/25135592/d9f587da-2420-11e7-924c-92d9051d22f4.png)

**Comment by chris206** [comment]
This is a weird glitch

there is one passenger registered, but there is nobody coming up in "registered passengers"

I checked for a duplicate tour or departure, but cant find one

![image](https://cloud.githubusercontent.com/assets/22382144/25135811/6262aff8-2421-11e7-8335-3e0bfe4b1be6.png)

**Comment by bradatkins** [comment]
Fixed
