### ISSUE TITLE
New Order Interface

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2067]
I shouldn’t need to add country and state into final documents in order to remove gluten free meals
--------------------
Session ID: 4dc6c60cbb7d955aa3b46684f0294141
Time: 13:04:39

**Comment by chris206** [comment]
Also - please add the view to Sandy as well. Ronen doesnt have as much to do with the order side, but Sandy sees lots of things that I miss.

**Comment by chris206** [comment]
Please also add **steve** to those who can use the new interface

Sandra	Lippold	**Sandra**	ADMIN	Sandra@206tours.com
steve	steve2016	**steve**	USER	steve@206tours.com	Rinda Kanidinc

**Comment by chris206** [comment]
I changed the billing address in and it didnt even alter the address that came up when I selected CC.
also, foreign CC's arent allowing me to charge.

![image](https://cloud.githubusercontent.com/assets/22382144/25148767/0df3abba-244a-11e7-94cd-c44f67be5020.png)

![image](https://cloud.githubusercontent.com/assets/22382144/25148773/119bd2d8-244a-11e7-90b1-90a82f7ec084.png)

**Comment by bradatkins** [comment]
I've added Steve and Sandra.

Unfortunately those fields are required fields, so not much I can do there, unless we remove them as required

**Comment by bradatkins** [comment]
Please post your billing address as a separate GH issue. It's confusing having everything in one issue.
