### ISSUE TITLE
Cancelled Passenger Still Appearing on Rooming List | BL061317 (Liz)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#2068]
Although I've changed the order status to "Cancelled", as we have discussed previously, once the passenger is cancelled: this should be the event that removes them from the rooming list (just as it adds the penalty and removes them from the recap.)

The reason it needs to be passenger specific is: if there are 3 passengers, and 2 of them cancel (so the account status is still deposit or something) - we wouldnt want those 2 cancelled passengers to appear on the rooming list.

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/22382144/25146076/b1b69eba-2440-11e7-92e3-37672addc51b.png)

**Comment by bradatkins** [comment]
Fixed, there was a slight break in the logic
