### ISSUE TITLE
www.206tours.com/tour99   (dates not showing up)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#208]
Hi Brad,

i checked the DB, i have no idea why the travel dates and prices are not showing up for this tour:
www.206tours.com/tour99

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you tell me what the issue was or it was just a glitch?


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
There was a bug. When you setup the departures, it was associating the
departures to an old Tour #99. I've fixed the bug and moved the departures
to the right Tour #99

**Comment by ronenreinheimer** [comment]
Super, there might be a few more that coworkers pointed out to me, I’ll have to review the issues.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
