### ISSUE TITLE
Dates and Prices not showing up on a few tours

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#209]
same issue as tour99 that you fixed

www.206tours.com/tour168a
www.206tours.com/tour68
www.206tours.com/tour39
www.206tours.com/tour43
www.206tours.com/tour113
www.206tours.com/tour164
www.206tours.com/tour166
www.206tours.com/tour167

**Comment by bradatkins** [comment]
Tour 43 has no 2015 departures.

All the rest are fixed.

**Comment by ronenreinheimer** [comment]
thank you Brad.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
