### ISSUE TITLE
URGENT: Fixing the Speed of DB messed other things up

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#210]
I'm assuming...

#1.  But Tour # is no longer showing in view payments

![image](https://cloud.githubusercontent.com/assets/8440903/6374078/9622893e-bcdc-11e4-9f3f-ecaabbca0530.png)

#2.  Jane Cihon Dec. Trip  (RL120714) is missing pax - ex. Mr. Hubbard 415614.  When you search by that booking # nothing comes up.  He registered May 24th but you said searching for orders before 6/1/14 would pop up....they're not.

Maybe there can be a better fix to the speed of the DB?  People should not go missing when group leaders are looking at their tours and clients etc.

**Comment by bradatkins** [comment]
I'm stilling working on improving performance on the Payments screen. The
tour number is temporarily removed as it was part of causing the slowness...

**Comment by ali206** [comment]
Ok but we cannot pull past bookings up and this is a HUGE problem!!

can't pull up 415505 or the one above, 415614...you said we'd still be able to and we can't and that needs to be fixed ASAP please.  We have clients caling in that want to make changes and we're unable to make them b/c DB won't let us pull up the booking.

**Comment by bradatkins** [comment]
K I will check on this

**Comment by bradatkins** [comment]
Fixed
