### ISSUE TITLE
Ins. issue on 417661

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#211]
I tried to change Noreen's ins. to the correct amount of $230 as an add cost but when i did that and then updated the booking it changed the other 2 passengers to $230 as well?

Invoice doesn't show it b/c client needed updated booking asap but i just wanted to let you know it's not working.

**Comment by bradatkins** [comment]
I couldn't seem to reproduce it?

![image](https://cloud.githubusercontent.com/assets/8440255/6658982/481e5038-cb50-11e4-8e6c-f646cded83ca.png)

**Comment by ali206** [comment]
try it on noreen's booking then maybe?

**Comment by bradatkins** [comment]
Closing, hasn't happened again since
