### ISSUE TITLE
Blue sheets opening as pdf's in Firefox?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#212]
Amanda uses Firefox and up until today, every time she opened the blue sheet it would open as a separate tab in her browser. 

Today for some reason it started downloading to her computer and then opening as a pdf, which takes awhile especially when there are clients on the phone. 

How come it started working differently all of a sudden?  Can it be switched back?

**Comment by bradatkins** [comment]
This isn't something the DB controls. It's a setting somewhere in her
Firefox browser.
