### ISSUE TITLE
External Link

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#213]
Can you add a section to this link for us where we can enter the payee's name please?

https://www.206tours.com/register/admin/editorder_old.php?OrderID=406210

**Comment by bradatkins** [comment]
I'm confused as to why you are still using that page? I haven't update that page in over 1.5 years so it could be causing problems.

Any reason why you are not using the editing functionality right off the orders screen?

**Comment by ali206** [comment]
We cannot get rid of this link b/c we need to be able to apply a discount if a booking is PIF, or we need to be able to apply refunds with transaction ID's etc...

**Comment by bradatkins** [comment]
Why would you not do that from the payments screen?

**Comment by ali206** [comment]
Because I can't apply discounts in the payments screen if someone is overpaid or PIF or if the discount is more then balance due. 

And there's no option to enter a CC payment in that screen that i charged manually.
