### ISSUE TITLE
Cxling pax and insurance issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#214]
Alejandro cancelled his trip and had all the same add ons as Helen.

When we cxl a client, the add ons remain on the invoice and show the total amount in total addt'l options still but they do not calculate in to the total penalty amount. 

That can be confusing to clients when for ex. $1,094 shows under total addt'l options but it's not included in the penalties.  

So I removed all addt'l options but that reduced the insurance premium to $285 which was incorrect.  

So I declined ins, added it manually to the invoice, and now it won't calculate in to the penalties like it was doing before.

The only way right now that we can show correct penalties is to leave the $350 under ins. but include it in the penalties like i did below (which can also be confusing to clients) or to decline ins. and add the $350 to penalties (but then it looks like the client never had insurance).

I know this all sounds a little confusing so if you need me to explain further i'll try. 

The point is, is there anyway to cxl a pax and the add ons i guess without it effecting the insurance premium?  Or if we have to manually add ins. premium can you have it calculate in to penalties automatically like it normally does?

![image](https://cloud.githubusercontent.com/assets/8440903/6400523/6ee3638e-bdc7-11e4-9744-fdc7c9e1b343.png)

**Comment by bradatkins** [comment]
When cancelling a PAX, I've set it so the additional options will be hidden and not affect the insurance.
