### ISSUE TITLE
Commission not deducting from total balance due

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#215]
418086

Balance due should be $8,280.66 not $9154

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=418086&GENERATED=TRUE&SHOW_COMMISSION=Y

Also we see the net amount and commission show on this invoice but when it gets emailed out to the travel agent, commission and net price disappears?

**Comment by ali206** [comment]
It only shows the correct balance due in view orders which isn't really helpful:

![image](https://cloud.githubusercontent.com/assets/8440903/6414068/e81d59f8-be62-11e4-8235-aacc9363ca10.png)

**Comment by bradatkins** [comment]
I've fixed the balance due.

Where are you sending the email from? Ie how are you triggering the email...

**Comment by ali206** [comment]
Stef was emailing out from i'm assuming the orders page.

**Comment by bradatkins** [comment]
There is no email to the agent from the orders page, so I don't know how that'd be the case
