### ISSUE TITLE
www.pilgrimages.com/frzapf    URGENT

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#216]
hi Brad,

for some reason, the drop down menu does not work - to select dept city:
http://www.pilgrimages.com/frzapf

**Comment by bradatkins** [comment]
You have the tour set to hide departure cities, but have no tour specific departure cities setup.

FYI, for future reference, if the drop down box is working on other tours, there's likely some issue with how the tour has been setup

**Comment by ronenreinheimer** [comment]
Why is this closed, I still cant select a dept city? or it was not setup correctly?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Ok thanks

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
