### ISSUE TITLE
View Payments Section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#217]
Daisy Mendieta made an $800 payment on 5/20/14 but when you search by her last name or booking #416645 in view payments it does not show:

![image](https://cloud.githubusercontent.com/assets/8440903/6421139/0581013e-be9a-11e4-870b-c9ef73736102.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6421151/1312d7b4-be9a-11e4-8149-2bbd532afede.png)

Searching by last name and booking # does not work either

![image](https://cloud.githubusercontent.com/assets/8440903/6421157/1d9a5266-be9a-11e4-99a6-d30c43977334.png)

**Comment by bradatkins** [comment]
Fixed.
