### ISSUE TITLE
417554 remove cxld pax

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#219]
Please remove Denise from this booking:
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417554&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
I'm confused as to why I'm doing this? It says cancelled on their invoice line and this is operating as it has been since the feature was implemented?

**Comment by ali206** [comment]
the client doesn't want to see the cancelled pax on her invoice

**Comment by bradatkins** [comment]
I've removed it on this one, but I"m going to mark this as an enhancement because I can't keep doing this when this happens.
