### ISSUE TITLE
Order Audit keeping pdf's of invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#221]
Next to where it says Irena - invoice email sent (below).  It would be great if there was a pdf attachment in the order audit next to each time someone in the office emails out an invoice.  That way we can keep track of the invoice from the beginning to the end and see what was added/changed etc.

![image](https://cloud.githubusercontent.com/assets/8440903/6444443/9e835354-c0cb-11e4-9440-5d8e13a8a50b.png)

**Comment by bradatkins** [comment]
This is now complete. It will work for emails sent from today forward.

![image](https://cloud.githubusercontent.com/assets/8440255/7803518/e736510a-031f-11e5-9387-8fc14febba9c.png)
