### ISSUE TITLE
hitting enter in registration locked melissa out of state field

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#222]
I accidentally hit enter while registering a client at the zip code, when the screen came back it locked me out of the State field.  Thank you.

![melisasa](https://cloud.githubusercontent.com/assets/8440903/6444561/5a567d68-c0cc-11e4-92e2-ae2f99cf2fc4.png)

**Comment by bradatkins** [comment]
I tried to reproduce this but couldn't...can you? If you can, please tell me step by step in detail (ie clicked in this field, typed in 53112 then hit enter) type thing
