### ISSUE TITLE
Change all subjects of emails to say ORDER instead of BOOKING

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#223]
Invoice is showing “Order#”
Email says “ Booking#”

When people are on the phone they sometimes say “Ohh I don’t know what’s my booking# but my order# is %$^%^””

So we should adjust the subject of the emails and confirmation to read the same as invoices and change everything to show as ORDER
.
![nat](https://cloud.githubusercontent.com/assets/8440903/6445033/8c5d81be-c0cf-11e4-88ab-7d532736c307.png)

![nat 1](https://cloud.githubusercontent.com/assets/8440903/6445035/8f4fe3bc-c0cf-11e4-90ba-7537579c9ccc.jpg)

**Comment by bradatkins** [comment]
Done
