### ISSUE TITLE
SOOO CONFUSED - 415171

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#226]
The payment of $1,238 on 4/16/14 at 12:10am shows on the invoice and in view orders when clicking on order total:
![image](https://cloud.githubusercontent.com/assets/8440903/6448227/6734761a-c0e6-11e4-9bcb-c09c54acc082.png)

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=415171&GENERATED=TRUE&SHOW_COMMISSION=Y

BUT NOT in View Payments or in Merchant??

![image](https://cloud.githubusercontent.com/assets/8440903/6448232/7181f49e-c0e6-11e4-90de-386d88e7c3dc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6448236/780a9db6-c0e6-11e4-84a5-31c2bc195222.png)

I tried searching by the transaction ID and it was not pulling anything up in Merchant.

**Comment by bradatkins** [comment]
uhhh, maybe i'm confused but it's the first one - the amounts match? Times may be slightly off depending on the time we have on the 206tours.com webserver and the Merchants servers.

**Comment by ali206** [comment]
It's not the first payment, names don't match and neither do transaction Id's.

**Comment by bradatkins** [comment]
It's in the view payments now:

![image](https://cloud.githubusercontent.com/assets/8440255/6656840/44940d42-cb0d-11e4-93ad-26a2a3566008.png)

Those transaction ID's come from the merchant. Can you search by it?

AA49315-CB9E89D7-7676-41C4-BAA1-715F4C58BF5A

If that doesn't come up, I suggest reaching out to the Merchant.

**Comment by ali206** [comment]
Ok but it's still not in Merchant so i have no idea where this payment even came from or if it's even a valid payment which is very scary....

there's 3 $1238 payments in here and there should only be 2 as per Merchant and Kathleen's transaction ID doesn't match up with Merchant..

**Comment by bradatkins** [comment]
Closing, hasn't happened again since
