### ISSUE TITLE
Issue in Orders Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#227]
Hi Brad,

we are trying to add a pre post option to 2 clients. it worked for 1 client but not the 2nd client. can you please look into this issue?

this is the DB code: DCA110215
this is the order #: 417761

![image](https://cloud.githubusercontent.com/assets/10079829/6471635/b83944e4-c1ba-11e4-9c17-81be60aa8359.png)

![image](https://cloud.githubusercontent.com/assets/10079829/6471638/c1e7e41e-c1ba-11e4-9776-dfdf3ade43c7.png)

**Comment by bradatkins** [comment]
Try now
