### ISSUE TITLE
Departing section in Excel group leader list

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#228]
Hi Brad, 

Each  Excel Group Leader List shows a “departing ….” message on the top right hand corner with today’s date, which is incorrect/misleading because for example, the group below is departing on April 9 not March 4th (today). 

Can you please either put in the actual group departure date or if the name list is going to have today’s date then it shouldn’t say “departing..”
![yari](https://cloud.githubusercontent.com/assets/8440903/6489753/f7f8c532-c26e-11e4-96cb-20a3abb51399.png)

**Comment by bradatkins** [comment]
Fixed, it now shows the departure date.
