### ISSUE TITLE
As per Stef - issue with DB tracking #'s

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#230]
The screen goes blank it doesn’t display tracking info
![stef](https://cloud.githubusercontent.com/assets/8440903/6490682/179288fe-c276-11e4-8992-e5a53fa98528.png)
![stef 1](https://cloud.githubusercontent.com/assets/8440903/6490687/1ac850d0-c276-11e4-8a47-b729e32e2018.png)

**Comment by bradatkins** [comment]
How is she getting there? That's Fedex's website so I can't really fix it :)

**Comment by ali206** [comment]
From: Stefanie Meyer 
Sent: Wednesday, March 04, 2015 2:19 PM
To: Ali Boulanger; Rinda Kanidinc
Subject: RE: DB error with tracking numbers

I am getting there by clicking on the tracking number under their order number

**Comment by bradatkins** [comment]
Fixed, looks like they changed their website link.
