### ISSUE TITLE
addt'l tour not showing in review section when registering

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#231]
Hi Ali,

I selected the tour option as per below but it is not included in Review section of webpage as per below.  

![liz 1](https://cloud.githubusercontent.com/assets/8440903/6490756/98c05686-c276-11e4-85a4-290b333c4b56.png)
![liz](https://cloud.githubusercontent.com/assets/8440903/6490759/9cf720b8-c276-11e4-9dff-362ccb6f04dd.png)

**Comment by bradatkins** [comment]
Tour # and order # please

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6667189/dc455386-cbc0-11e4-9f68-b4cf831076f9.png)

**Comment by bradatkins** [comment]
Fixed.
![image](https://cloud.githubusercontent.com/assets/8440255/7101887/6b650532-e03b-11e4-8222-947f62fd8488.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7101886/665832f8-e03b-11e4-9e1b-d41eaba6eceb.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7101888/768895dc-e03b-11e4-91bd-496e264c52e3.png)
