### ISSUE TITLE
Balance due section on invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#233]
Hi Brad, 

On invoices can you align the balance due under the same column as the payments received?

And can you include the payment due date in the “balance due to 206 Tours line” (Ex: Balance due on July 15, 2015 to 206 Tours)?  That way everything will be on 1 

![image](https://cloud.githubusercontent.com/assets/8440903/6513541/aff330b6-c349-11e4-9024-0ce6ef8328d3.png)

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/6656727/42078f44-cb09-11e4-8023-b83c02c28461.png)

**Comment by ali206** [comment]
Thanks. 

Can you include the payment due date in the “balance due to 206 Tours line” (Ex: Balance due on July 15, 2015 to 206 Tours)? That way everything will be on 1 line instead of how it looks above

**Comment by bradatkins** [comment]
Done 

![image](https://cloud.githubusercontent.com/assets/8440255/6886099/d1dbd8ee-d600-11e4-9bdc-20a281454df0.png)

**Comment by ali206** [comment]
I don't see it lining up like your picture above:
![image](https://cloud.githubusercontent.com/assets/8440903/6898279/3d7f5f82-d6c7-11e4-9738-2b599e5f08db.png)

**Comment by bradatkins** [comment]
Fixed
