### ISSUE TITLE
Client Orders - Can you display what device it was booked with in the invoice?

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#235]
Hi Brad,

Milanka would like to know if it is possible for the DB / invoice to show what device the client booked with? Desktop / Tablet / Mobile?

Thank you and Please let us know.

**Comment by bradatkins** [comment]
Now you'll see a couple of new icons on the orders screen when someone places an order on an mobile device (phone, table).

In fact, someone placed an order on an iPhone when I was working on it. Good test :)

This only works for orders going forward.

If you mouse over the icon you can tell if it was an iPhone/iPad or a generic phone/tablet

![image](https://cloud.githubusercontent.com/assets/8440255/9430550/8986e3ea-49c8-11e5-875f-fb42d26203c3.png)
