### ISSUE TITLE
For the next phase

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#236]
having the ability to edit the whole written top part of invoices instead of just being able to add to what already exists.

Ex:
Dear <FIRST NAME>,

Thank you for making your final payment. Please find your invoice below reflecting a $0.00 balance.

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/8026677/d7990146-0d4e-11e5-9dd9-118541fbc3d4.png)

![image](https://cloud.githubusercontent.com/assets/8440255/8026679/dbf7dbe0-0d4e-11e5-8e08-adedac1ebcac.png)
