### ISSUE TITLE
All Travelers Section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#237]
Hi Brad, 
When we go to all travelers, and go to Fr. Salvo and click edit, on the bottom of the screen it shows all of his previous/current bookings. 

#1.Where do those get generated from?

#2. Yaritza was able to edit the first order to correct his address to 405 ....
but when i tried to update the 2nd address which was incorrect, it wouldn't actually update.  We jsut don't want the old address to show up at any point in the future.

When i go to the 2nd booking in view orders and click on his name it shows correctly but in the All travelers section the address doesn't seem to have updated on the 2nd booking:
![image](https://cloud.githubusercontent.com/assets/8440903/6514678/43ff48d2-c352-11e4-81c5-566c4c93f4bc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6514578/87916dc4-c351-11e4-87bb-d0dd9a12d120.png)

**Comment by bradatkins** [comment]
Umm not really sure what you mean by "#1.Where do those get generated from?" ...

Those are generated from previous bookings?

To be honest, I don't think you should be changing the second address, as it was a previous order and likely was correct at the time, no?

**Comment by ali206** [comment]
She was having an issue with the address that was pulling up on the fedex label so we thought if we changed all locations that had the old address maybe the DB wouldn't pull the wrong address anymore.
