### ISSUE TITLE
417327 - DB wouldn't save passport info

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#238]
From: Richard Baron [mailto:ride678@hotmail.com] 
Sent: Sunday, March 08, 2015 9:48 PM
To: orders
Subject: entering passport numbers to order; Order number 417327

Your website would not retain the passport numbers I entered. I tried to do it under edit passenger, but was unsuccessful. I just want to make sure that this is taken care of before I make a final payment.
Please let me know how I can enter passport information to my order.
Thank you.
Richard Baron

**Comment by bradatkins** [comment]
Seems to work OK now:

![image](https://cloud.githubusercontent.com/assets/8440255/7099801/2244d06c-dfcd-11e4-93a6-51a1cc0c9f0c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7099802/25f3a828-dfcd-11e4-87aa-ad7e00872798.png)
