### ISSUE TITLE
Address was not reflecting correctly 418323

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#239]
Sent: Monday, March 09, 2015 1:02 PM
To: Milanka Lachman; Ali Boulanger
Cc: Donna Strucic; Brad Attkins (brad@youreshop.com); Rinda Kanidinc
Subject: RE: 418323 - what happened to person's address? 

I used the shopping cart to register them and then I went into the booking to update with the address information however it still does not reflect

Please do not hesistate to contact me should you need further assistance. 

May God shed His grace on you throughout this Lenten season!

 	Piernha Marc 
Travel Consultant
206Tours.com

Tel: 800.206.8687 | 631.361.4644 ext. 105 | Fax: 631.361.3682
 206 Tours Inc., 333 Marcus Blvd, Hauppauge, NY 11788
 piernha@206Tours.com | Skype: live:piernha

   client letters

	

From: Milanka Lachman 
Sent: Monday, March 09, 2015 1:01 PM
To: Ali Boulanger
Cc: Donna Strucic; Piernha Marc; Brad Attkins (brad@youreshop.com); Rinda Kanidinc
Subject: 418323 - what happened to person's address?

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6653099/b423e992-ca5a-11e4-8009-4130fc89aaa4.png)
