### ISSUE TITLE
New UI - land only option - date not changing forward 1 day.

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#240]
Hi Brad,

I was looking over the new UI and when you press the land only option the date is not moving up 1 day:

https://www.206tours.com/register/test2.php

![image](https://cloud.githubusercontent.com/assets/10079829/6576216/ee098e34-c70b-11e4-8bfb-2f43ee2c1dfd.png)

![image](https://cloud.githubusercontent.com/assets/10079829/6576223/f63338f8-c70b-11e4-8901-8dc1ea5d068a.png)

**Comment by bradatkins** [comment]
This test was setup as tour #206 which doesn't have the +1 day rule. I changed it to tour #111 and it works OK:

![image](https://cloud.githubusercontent.com/assets/8440255/6653062/605c1f4c-ca59-11e4-9523-050c0a32e486.png)

![image](https://cloud.githubusercontent.com/assets/8440255/6653063/6472dc60-ca59-11e4-968f-11afcfbff254.png)

**Comment by ronenreinheimer** [comment]
Great. I did notice that 2016 Year is not showing up.

[cid:image001.png@01D05EB6.A9E684E0]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
thank you!
