### ISSUE TITLE
Order Audit: 418303

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#241]
I just changed a pending payment to Declined and it's not showing that in the order audit for 418303:

Payment status changed from Approved to Approved for $400.00 2015-03-10 10:03:39 Ali 

![image](https://cloud.githubusercontent.com/assets/8440903/6576379/3c1e1044-c70d-11e4-8da7-853b0fddb222.png)

**Comment by bradatkins** [comment]
This ones a little complicated for me to sort through due to the multitude of changes.

Can you tell me what you did with:

1) The check. Ie from what status to what status
2) The $400 CC payment from what status to what status

**Comment by ali206** [comment]
I didn't touch any of the CC payments - those stayed as is. 

The only thing i did was change  a Pending check to a Declined Check

**Comment by bradatkins** [comment]
I think what happened is you and Jen were in the payments section for this order at the same time, and the DB got messed up, based on what I can see:

![image](https://cloud.githubusercontent.com/assets/8440255/7101641/fff0e23a-e030-11e4-8894-be155cb2e7ae.png)

**Comment by ali206** [comment]
But jennie doesn't have the ability to change anything in the payments section so why would the matter?

**Comment by bradatkins** [comment]
We just resolved this I beleive
