### ISSUE TITLE
418318 - ins. not calculating in to order correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#242]
The 2 people with $189 ins. should have an order total of $2588 not $2602 and updating isn't working

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=418318&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Fixed. There was a bug with addon insurance and multiple passengers

![image](https://cloud.githubusercontent.com/assets/8440255/6578130/a58c8e06-c718-11e4-9f07-6c8e3903054e.png)
