### ISSUE TITLE
Martin Bancroft - DB pulling incorrect information that doesn't exist anymore?!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#243]
We deactivated all incorrect accounts in All Passengers, the information in All Travelers is up to date. 

But when i go to Existing clients, and try to register fr mickey for Tr#103 Sept 2015, the name in the drop down menu for select a previous traveler ends up entering all of his old passport information. 

Where is it pulling that from?!?!

![image](https://cloud.githubusercontent.com/assets/8440903/6581691/1fd801de-c72f-11e4-9c80-8d588eec81b9.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6581790/6f9eae2a-c72f-11e4-8fa0-ef38c839e1a1.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6581800/7ddbc630-c72f-11e4-8fbd-7e9de7a5f463.png)

**Comment by ali206** [comment]
Ali,

Can you add to GitHub ? I don’t understand how Fr. Bancroft received and email regarding passport expiration as in his latest order the passport expires in 2024. 

This email was generated from which order # ? 

From: Natasha Tosic 
Sent: Tuesday, March 10, 2015 10:04 AM
To: Rinda Kanidinc
Cc: Ali Boulanger; Sandra Lippold; Milanka Lachman; Liz Shea
Subject: DB: Passport Expiring Soon Notifications

Hey I bet it came for this order:406698 as for that order name is Fr Fr Martin.
Maybe we should tell Brad to make DB send emails about passport renewal only for future trips not past. 
As this trip is from 2012.

**Comment by bradatkins** [comment]
The first part is fixed. The DB was ignoring whether a PAX was Active or Not in the Previous PAX drop down box.

**Comment by bradatkins** [comment]
The DB will also check the PAX's Tour Departure Date and the departure date is upcoming (ie not in the past) it'll send the passport email.

If the departure date is in the past, it will not send a passport email
