### ISSUE TITLE
Suppress order email for initial confirmations

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#245]
#1.  Can you make the initial confirmation email after a new registration Inactive again?  Having that automatically go out to clients does not work for us b/c not all clients need to get a copy of their invoice, or discounts haven't been applied yet, etc.
We would eventually like with new registrations to have the option to select on our side "Suppress Order Email" before confirming an order.

**Comment by bradatkins** [comment]
I've suppressed the initial order email.

Keep in mind though, if a PAX completes their own order, they as well will not get a confirmation email
