### ISSUE TITLE
Initial confirmation emails going out

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#246]
#2.  Is there any way (other than manually copying and pasting the correct message in to the email box) to send out that same email from the DB?

**Comment by bradatkins** [comment]
I'm not sure what is meant by this request?

**Comment by ali206** [comment]
We don't want new order confirmations to be automatically sent out as per previous issues posted.  

We need it to be inactive until you are able to maybe create a "suppress order email" button option before confirming an order. 

However, Milanka still wants to be able have that same new order confirmation email sent out. 

The only way i can see that getting done is by having everyone in the office copy and paste that message when manually sending out the invoice.

**Comment by bradatkins** [comment]
Ah ok. I"ll default that text box to the new email text.

**Comment by ali206** [comment]
WAIT! what text box....when manual emails get sent out, that pop up box?

**Comment by bradatkins** [comment]
Yes.

1) Initial confirmations will be suppressed
2) When sending out emails from admin (initial emails) default text will be from #1

**Comment by ali206** [comment]
Ok so the DB will recognize that no email has been sent yet and default to #1 message ONLY for manually sending first email after order being confirmed?

**Comment by bradatkins** [comment]
You got it

**Comment by bradatkins** [comment]
So I've stopped the initial emails, all emails will need to be sent out manually until you advise otherwise.

When you access the "Orders pending Invoice Email" link from the admin, and click the send email icon, you will see this.

First Name, Tour Name and Tour Date will be replaced with the appropriate text. You can change the rest of the email text as you see fit.

![image](https://cloud.githubusercontent.com/assets/8440255/6588171/6e36ee96-c764-11e4-8fc4-a613b495c478.png)

**Comment by ali206** [comment]
Ok this isn't working properly then.  I've sent out multiple emails from my test booking #418019 
And this is the email message that popped up which is wrong:

![image](https://cloud.githubusercontent.com/assets/8440903/6618700/1ece9d1c-c89b-11e4-91fa-22f74cde7756.png)


Should only say Attached is a copy of your invoice.

**Comment by ali206** [comment]
I sent this from orders screen btw and clicked customer

**Comment by bradatkins** [comment]
The first line says attached you will find a copy....I added some of the
text from the initial confirmation there as well to keep it conistent (ie
name, signature, etc)

**Comment by ali206** [comment]
Ok but as per above, you said that email text for initial confirmation was ONLY going to show for the initial confirmation email.  You said the DB would be able to recognize the initial email and then switch back to saying only Attached is a copy of your invoice.

![image](https://cloud.githubusercontent.com/assets/8440903/6619238/5dab801e-c89f-11e4-881b-f2550f061783.png)

**Comment by bradatkins** [comment]
It does. The initial email text is slightly different:

[image: Inline image 1]

**Comment by ali206** [comment]
No that text shows every time we go to send an email now, not just the first initial email.

I guess people have gotten used to it though so it can be left alone
