### ISSUE TITLE
Adding discounts before confirming orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#247]
#3. With new registrations, can you create a way for us to add a discount or discount code before confirming order and without a promo code existing or having to be created? Ex.  If Rinda approves a new registration (returning clients) for a $100 discount per person, can we have the ability to add that before having to confirm the booking?

**Comment by bradatkins** [comment]
You can now apply a discount to an order while creating it. This functionality is only available to 206 Tours Staff and not customers (obviously).

You must start the order using one of these two links:

Inline image 2
![image](https://cloud.githubusercontent.com/assets/8440255/8026101/29662718-0d38-11e5-96a4-73e794fdfd37.png)


You will be prompted for the discount value and to define whether your discount is PER PAX or against the ORDER TOTAL

![image](https://cloud.githubusercontent.com/assets/8440255/8026103/2ee9170e-0d38-11e5-9532-1779a2f3f8aa.png)
