### ISSUE TITLE
Creating more then 1 tracking # per order

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#250]
#6. We need the ability to be able to create more than 1 tracking # on the same order

**Comment by chris206** [comment]
Tracking numbers need to be autogenerated for all subordinate addresses on order
![image](https://cloud.githubusercontent.com/assets/22382144/21945507/9c825732-d9a9-11e6-89de-f1f0a3633214.png)

**Comment by bradatkins** [comment]
Duplicate of #1807
