### ISSUE TITLE
New registrations on existing accts have to many boxes for shipping/billing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#251]
#7.  New registrations on existing accounts in DB will show 4 boxes for shipping/billing in the booking instead of 2 like there should be (4 are not necessary).

**Comment by bradatkins** [comment]
Screenshot please?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6923966/3882b9fc-d7a3-11e4-8843-baf9a0d7e15b.png)

**Comment by bradatkins** [comment]
Fixed 
![image](https://cloud.githubusercontent.com/assets/8440255/7101593/0dbd9406-e02e-11e4-9dcb-c9cc4efd55f3.png)
