### ISSUE TITLE
searching for pax invoice is not registered under

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#254]
#10.  If 2 people are registered on the same booking, and the 2nd pax calls but doesn't have any order information, searching by their name in the DB will not pull up the order # they are on.  Can the DB, in Orders screen, search by all registered pax so that we'll be able to pull up any pax much easier?
Sometimes clients don't remember the trip info. For the tour they signed up for, they don't know their order # since the order is not registered in their name, etc.  so instead of having to ask them who they may be register under, above solution would be great.

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/9455417/04149226-4a99-11e5-9fc8-22fff98c0b90.png)

**Comment by ali206** [comment]
This can only be done in All Orders, not from admin screen from my test.  Is that the only place you added that feature?

**Comment by bradatkins** [comment]
This is now done.
