### ISSUE TITLE
Dupe accounts in DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#260]
Hi Brad, 

If we go through dupe accounts in DB where should we ONLY be removing them from, All Passengers or All Travelers?

**Comment by bradatkins** [comment]
Do not remove anything from All Passengers. This is order related data.

I ran a query, and I do not see any duplicate accounts. Why do you think there are duplicate accounts in the Travelers section?

**Comment by ali206** [comment]
There have been dupes in All Travelers throughout the year because it creates a problem when trying to register people sometimes.  But that's the only time i've noticed them.  Milanka and others keep telling me there are dupes that shouldn't be there, i haven't checked yet

**Comment by bradatkins** [comment]
OK I think I found a loop hole.

It looks like the DB was allowing Staff to edit Traveler accounts and update accounts with new email address that were already in use. I've closed this loop hole

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/7099855/bceb275e-dfcf-11e4-97f4-2e2a97c0b3f8.png)

**Comment by ali206** [comment]
Stef had an issue with this yesterday...

If you search by Jeanne Adams or her email adress (happymom_61@yahoo.com) only 1 account shows up.  So there are no old Travelers to make inactive?? Uness they're in a different location?

**Comment by ali206** [comment]
Zip code and phone # we're unable to save b/c of that dupe warning:
![image](https://cloud.githubusercontent.com/assets/8440903/7141191/e8de2070-e29d-11e4-8f55-5a96aa08d8d6.png)

**Comment by ali206** [comment]
Can you please fix this ASAP? There are lots of changes that we need to make to all travelers and no one is able to b/c of the duplicate account warning, even if they don't have dupe accounts. 

When i try to make an account inactive (ex. Megan Sacchitella has 3 accounts) i'm unable to b/c of the dupe warning. 

Thanks!

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
I have bad news, it's not working:

![image](https://cloud.githubusercontent.com/assets/8440903/7203287/92ddc940-e4e7-11e4-9447-87e460e730b9.png)

**Comment by bradatkins** [comment]
Which email?

**Comment by ali206** [comment]
Take your pick - it was/is doing this for multiple if not all clients:

![image](https://cloud.githubusercontent.com/assets/8440903/7371853/617ccfe2-ed91-11e4-8520-0f8bee3cd8df.png)

**Comment by bradatkins** [comment]
That's a paypal screen, nothing to do with the DB. Not sure what your
paypal username and password is?

**Comment by ali206** [comment]
no idea how that ended up in there, weirdddd sorry. 

This is actually what i pasted:

![image](https://cloud.githubusercontent.com/assets/8440903/7372548/54f4a480-ed95-11e4-9121-68b6885e0e41.png)

**Comment by bradatkins** [comment]
That email has 3 active accounts

![image](https://cloud.githubusercontent.com/assets/8440255/7550336/c9ff8102-f62b-11e4-9dbb-9850c4f873b1.png)

**Comment by ali206** [comment]
Right but we are unable to make any of them inactive b/c of the dupe warning still

![image](https://cloud.githubusercontent.com/assets/8440903/7590743/004efc92-f898-11e4-96ae-0e3bdd938468.png)


![image](https://cloud.githubusercontent.com/assets/8440903/7590745/03d5a28a-f898-11e4-94ba-0c4c3b1fb7a1.png)

**Comment by ali206** [comment]
Hi Brad, 

This is super URGENT.  It's so difficult to work within the DB when we are unable to update anyone's information, even if they don't have a dupe account.  Can you please fix this ASAP?

I know there are phases etc. but this is really urgent.  Clients want correct invoices and we're unable to provide them that b/c of this issue.

Coelho only has 1 account in travelers but when i try to update his address, pword etc. i get the dupe msg shown above.  it's driving everyone nuts!

![image](https://cloud.githubusercontent.com/assets/8440903/8574697/16636bb2-2566-11e5-8575-fb5a5c17ef35.png)

**Comment by bradatkins** [comment]
I tried updating him (changed his Title to Mr.) and it worked fine? I'm not
sure of the error message you are getting...can you take a screen of the
Edit screen and the error message too?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/8575151/7cf3ab4c-2568-11e5-9874-7f77f48c1d90.png)
After clicking save i get this error msg still:

![image](https://cloud.githubusercontent.com/assets/8440903/8575028/d556d59e-2567-11e5-8949-eb8910112ca5.png)

**Comment by bradatkins** [comment]
Ahh ok. I was using George! Let me check

**Comment by bradatkins** [comment]
This is a dupe account. Remember, dupe accounts are determined based on an
email address. These two accounts have the same email address.

I don't think there's a bug.

[image: Inline image 1]

**Comment by ali206** [comment]
Ok, Donna told me they had gotten rid of a dupe account.  I guess not sorry. 

What about for Elly chia though?

Trying to set her dupe account to inactive and after clicking save we get dupe error msg:
![image](https://cloud.githubusercontent.com/assets/8440903/8576244/b0ffd662-256e-11e5-9751-42c3e2ba9404.png)

**Comment by bradatkins** [comment]
I've moved the error check. The update will happen, but you will get the
error message still (which is OK)

**Comment by ali206** [comment]
Ok Stef is trying now.  

What is the point of still seeing the error msg if it's not actually an error anymore?  Also, can you see who/when the 2nd account was created? I know dupes should not really be an issue anymore but there still seems to be a bunch here and there

**Comment by bradatkins** [comment]
You'll see the error because you are inactivating an account, but the DB
doesn't know that until it's been inactivated. The next time you'd not see
that.

I can have a look to see who created it, but it could have been an old one.

**Comment by bradatkins** [comment]
Closing, hasn't happened again since
