### ISSUE TITLE
Different arrival/dept city's

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#261]
From: Sandra Lippold 
Sent: Monday, March 09, 2015 3:50 PM
To: Brad Atkins
Cc: Milanka Lachman; Rinda Kanidinc; Ali Boulanger
Subject: DB: Different arrival and departure city’s

Hi Brad,

RE: Being able to choose a different departure and arrival city

Where are we with this step?
We still don’t see it on our side and I don’t believe it is on the client side either

![sandy](https://cloud.githubusercontent.com/assets/8440903/6584110/510c48cc-c73f-11e4-8ffb-f0fa88944be2.png)

**Comment by bradatkins** [comment]
OK, so just as a first step, I've enabled the return city just for 206 Tours staff:

![image](https://cloud.githubusercontent.com/assets/8440255/6656692/f523b7da-cb07-11e4-8ee1-b9158969d290.png)

![image](https://cloud.githubusercontent.com/assets/8440255/6656709/58495522-cb08-11e4-9f97-739364a438f3.png)


Please provide your feedback. It's been a while so there might be some work required to make this go.
