### ISSUE TITLE
Future Website - sent to top / info button Chrome

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#262]
Hi Brad,

the buttons are working good on IE, but now they are not working on Chrome:

![image](https://cloud.githubusercontent.com/assets/10079829/6585053/cd762fb2-c745-11e4-8dc9-8b79b15ba83d.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Great! Thank you.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
