### ISSUE TITLE
No address stored in All travelers for Mary Savage

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#263]
Hi,

Client called to change error in address. In orders page, I pulled up her order and clicked on client’s name to update address. 
![yari](https://cloud.githubusercontent.com/assets/8440903/6585203/c4ee995a-c746-11e4-8905-e0a5defef834.jpg)

![yari 1](https://cloud.githubusercontent.com/assets/8440903/6585208/ceb897e2-c746-11e4-86af-7623423974c5.jpg)

Then I went to travelers, to update address in there as well.

 No address was stored there. 
 
![yari 3](https://cloud.githubusercontent.com/assets/8440903/6585213/d4c64b84-c746-11e4-9f6a-e638d221c704.jpg)

**Comment by bradatkins** [comment]
Her account was created back in 2013, so there's a number of things that have been fixed since then. My guess is this is just an old issue
