### ISSUE TITLE
418276 - approved commission payment not showing on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#264]
![image](https://cloud.githubusercontent.com/assets/8440903/6598115/d401fc0c-c7d7-11e4-95ab-ae3fa9595200.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6598116/d9cdac6c-c7d7-11e4-874e-b0c00fbbd630.png)

**Comment by bradatkins** [comment]
Fixed. There was a bug that would only show commission payments if there were other payments already applied
![image](https://cloud.githubusercontent.com/assets/8440255/6652099/c5161224-ca38-11e4-95ef-1ca910e9dcaa.png)
