### ISSUE TITLE
Incomplete Orders section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#265]
In Incomplete Orders, how do we remove orders that don't need to be completed?
![image](https://cloud.githubusercontent.com/assets/8440903/6598716/ee6094ba-c7db-11e4-91f5-00f042914395.png)

**Comment by bradatkins** [comment]
Done:

![image](https://cloud.githubusercontent.com/assets/8440255/7825352/fc113c7e-03d9-11e5-8aec-abf5ea0934a2.png)
