### ISSUE TITLE
Fedex label showing old address

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#266]
The DB is generating a FedEx label for the old address of the account on this order. It should reflect the current address of the account.

![yari](https://cloud.githubusercontent.com/assets/8440903/6599664/7b48bbb4-c7e1-11e4-9ae1-ffad0b3370c6.jpg)

![yari 1](https://cloud.githubusercontent.com/assets/8440903/6599677/8570a9c6-c7e1-11e4-8098-cd1b3b23c777.jpg)
![yari 2](https://cloud.githubusercontent.com/assets/8440903/6599679/87476d7a-c7e1-11e4-94c7-733eae791b6d.jpg)

**Comment by bradatkins** [comment]
The DB wasn't setup to regenerate a FedEX label if the address was changed. It does that now
