### ISSUE TITLE
418297 order audit

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#268]
Elise just sent an email to herself via the DB and it's showing as the Customer did that - does everything Elise do show up as customer?!

![image](https://cloud.githubusercontent.com/assets/8440903/6600164/5f048a8e-c7e4-11e4-9806-e54b31a73030.png)

**Comment by bradatkins** [comment]
Was Elise's DB account deleted? I don't see her in the user list anymore?

**Comment by bradatkins** [comment]
I fixed it, but I still can't find her account.

![image](https://cloud.githubusercontent.com/assets/8440255/6652056/86ac7fc0-ca36-11e4-9750-1fd6404090f6.png)

**Comment by ali206** [comment]
Ok she has an account now, sandy said she only created her in the cpanel by accident
