### ISSUE TITLE
418021 - 2nd pax not showing on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#271]
![image](https://cloud.githubusercontent.com/assets/8440903/6602693/8a5e52fa-c7f3-11e4-8a37-cdf42af4456b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6602698/8fc58eac-c7f3-11e4-8ce5-0d3a0b93694f.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6610181/fc29a996-c831-11e4-9f10-4a3b84bfa3bb.png)
