### ISSUE TITLE
Can't enter a different email address when clicking on someone else

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#272]
When you try to send an email to "Someone Else" there is no box to enter a different email adderss:

![image](https://cloud.githubusercontent.com/assets/8440903/6619283/b3bbcf9a-c89f-11e4-8639-d570b01f9308.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6651908/298e1c8c-ca30-11e4-9bf9-c3824c655ed8.png)
