### ISSUE TITLE
6 pax added only 1 showing 418378

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#273]
From Chris:

I just built this booking for client, only one name is showing up when 6 passengers have booked.

What’s the deal? I left out the address for the main account because I don’t have it. I will get it – I’m expecting to add another 17 passengers at some point.
 
![chris](https://cloud.githubusercontent.com/assets/8440903/6619754/c6ab9286-c8a2-11e4-94ea-9ce38024b4e7.jpg)

**Comment by bradatkins** [comment]
Fixed. Same as 274

![image](https://cloud.githubusercontent.com/assets/8440255/6652001/b35f1fe8-ca34-11e4-9725-474f7a020f8f.png)
