### ISSUE TITLE
418379 - 8 pax booked only 6 showing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#274]
![image](https://cloud.githubusercontent.com/assets/8440903/6619833/4c80db50-c8a3-11e4-9e26-423301aeda68.png)

**Comment by bradatkins** [comment]
Fixed. There was a bug when adding new PAX to an existing order

![image](https://cloud.githubusercontent.com/assets/8440255/6651976/0f3bb20a-ca34-11e4-8b3e-9ca2fcecfdd9.png)
