### ISSUE TITLE
Phone # won't save 418382

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#276]
even though it's in all travelers and all other spots i can think of:

![image](https://cloud.githubusercontent.com/assets/8440903/6624419/772a0982-c8bf-11e4-8c72-425960a1e76e.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6624426/7b989bc8-c8bf-11e4-9552-9825cd7e8b13.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6624452/b8a9133a-c8bf-11e4-894c-a101c3d7d5ad.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6651903/0bcdce18-ca30-11e4-9a22-0dd893c93a36.png)
