### ISSUE TITLE
Hide Dept City question

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#277]
Hi Brad, 

Sorry i can't remember but when we select Hide Dept. City is that only for new registrations or does that apply to the whole tour, even after registered?

as per liz:

This is regarding tour MJ051115.  

There are 3 passengers booked under 417630 but one of passengers Jamie Valenta would like to fly out of DSM instead of CID ias originally she registered.  I told her that there will be additional $100.00 for flying out of DSM and I added the cost to tour as per below.. 

![liz](https://cloud.githubusercontent.com/assets/8440903/6640196/06be7374-c96c-11e4-8ed2-935b573bd9d2.png)

However, when I go to the order and select DSM to update Jamie’s departure city of DSM,  entire departure cities show on the list even though Hide regular departure cities is selected as per below.
![liz 1](https://cloud.githubusercontent.com/assets/8440903/6640204/12ecd294-c96c-11e4-8969-37337a424951.png)

**Comment by bradatkins** [comment]
Hide Regular Departure cities is typically used in the following scenarios:

1) if the base price of the tour is to be departing from somewhere other
then NY
2) if the tour is only offered as a departure from a smaller list
3) If the tour has different departure city costs for whatever reason
