### ISSUE TITLE
Future website - Account Login mouse over box

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#278]
Hi Brad,

can you please shift the yellow button 5 pix to the right. please then center text under it. thank you. (if you need a new image, let me know)

![image](https://cloud.githubusercontent.com/assets/10079829/6640303/c349694a-c96c-11e4-8433-305e08eede47.png)

OR PLEASE MAKE THE ENTIRE WHITE FRAME 9 PIX NARROWER FROM THE RIGHT SIDE:

That will center the entire frame. thank you!

![image](https://cloud.githubusercontent.com/assets/10079829/6640423/a47712aa-c96d-11e4-976d-8709a48a01bd.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/6651886/f28df92e-ca2e-11e4-87f0-4d4b069eb294.png)

That's as good as I can get it. Can we please get this moving to make it live

**Comment by ronenreinheimer** [comment]
OK agreed, but can you perfect it later?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
We can try, but there are some limitations. I tried for a bit and this is where I could get it

**Comment by ronenreinheimer** [comment]
I think it is good enough for now, but it is off center. We can revisit this issue later.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
