### ISSUE TITLE
418363 - last name wrong and we can't fix

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#279]
We went to all pax, travelers, the booking and updated and it's not fixing the top of the invoice:
Last name needs to show as Cernoch:

Is there somewhere we're missing where last names need to be updated??

![image](https://cloud.githubusercontent.com/assets/8440903/6646072/e6edd702-c997-11e4-9fbf-5954a0918a92.png)

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/6651899/c9d56c6e-ca2f-11e4-8fac-29eaa7b5536e.png)

**Comment by ali206** [comment]
Did you fix it in a way that we were missing? Or there was a bug etc.

**Comment by bradatkins** [comment]
It was a bug. I fixed the bug.
