### ISSUE TITLE
Post tour not reflecting - Tour # FGF090615 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#280]
Seems to be created correctly unless i'm missing something...

It showed up when Irena was registering clients this morning but after the booking was confirmed there was no PT on the invoice.

![irena](https://cloud.githubusercontent.com/assets/8440903/6668480/9fb1ab0a-cbc9-11e4-8ba9-fa160d893bba.png)
![irena 1](https://cloud.githubusercontent.com/assets/8440903/6668482/a333dbd6-cbc9-11e4-9e2b-da6fd1d8b268.png)

**Comment by bradatkins** [comment]
Fixed.

For whatever reason it was only showing PRE tours.

![image](https://cloud.githubusercontent.com/assets/8440255/7101548/5ddf9f76-e02c-11e4-9d43-6dbd814b4373.png)
