### ISSUE TITLE
CC Charged and not showing on invoice?? 418424

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#281]
Elise charged this card this morning and she said it went through without any problems but now is not showing on the clients' invoice for some reason.

![image](https://cloud.githubusercontent.com/assets/8440903/6673940/e0bf0188-cbec-11e4-8911-3155fe89d529.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6673946/eb3a9b54-cbec-11e4-8be8-a1e367577358.png)

Transaction ID: 160315B39-97217356-FE49-45EE-A19D-B8CB0C4B8159

**Comment by bradatkins** [comment]
Does it show up in the payments screen, or orders screen?

**Comment by ali206** [comment]
Nothing shows in in View Payments and nothing in view orders
![image](https://cloud.githubusercontent.com/assets/8440903/6674153/3f79b3d4-cbee-11e4-88b1-5aa4203f8a52.png)

**Comment by bradatkins** [comment]
OK This was likely my previous changes. I will need to investigate more.
Please manually add a payment to balance the order.

**Comment by ali206** [comment]
ok it also just happened with #418423 ($400 deposit charged today)

**Comment by ali206** [comment]
and 3 charges from the wknd didn't post either
418410, 411 & 412

![image](https://cloud.githubusercontent.com/assets/8440903/6675368/4accebb8-cbf6-11e4-8440-75a523b1a2d1.png)


![image](https://cloud.githubusercontent.com/assets/8440903/6675374/5125aeb4-cbf6-11e4-967d-f190d208fe74.png)

**Comment by bradatkins** [comment]
Shoot. Let me reverse that change right now

**Comment by bradatkins** [comment]
I've reversed the change.
