### ISSUE TITLE
trying to register a client under an agent

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#282]
![image](https://cloud.githubusercontent.com/assets/8440903/6694602/ab41ee74-ccb1-11e4-90c9-93fa18372353.png)

page not working:
https://www.206tours.com/register/tourlist.php

**Comment by bradatkins** [comment]
What do you mean not working?

![image](https://cloud.githubusercontent.com/assets/8440255/6885995/a2b5689a-d5fc-11e4-9e75-f38b3500180e.png)

**Comment by ali206** [comment]
select thu-lan, then click on new order as agent.  Type in 111 and it doesn't bring you anywhere.

**Comment by bradatkins** [comment]
Fixed 

![image](https://cloud.githubusercontent.com/assets/8440255/6910363/b800764e-d71f-11e4-97eb-0df45b470947.png)

**Comment by ali206** [comment]
This isn't bringing us to the list of tours now anymore, just a blank page:

![image](https://cloud.githubusercontent.com/assets/8440903/6920260/6a1dd64e-d78b-11e4-96f8-449210f13b9e.png)

**Comment by bradatkins** [comment]
Fixed
