### ISSUE TITLE
Address updated and not showing correctly on new registration

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#283]
Trying to register Fr. Fineo - Liz just updated his Address in All Travelers but it's not sowing correct address when she goes to book him.

She went to All Travelers, updated address, then clicked on shopping cart, entered the tour and then this shows:

![image](https://cloud.githubusercontent.com/assets/8440903/6736212/d7845196-ce39-11e4-96e9-e4f957ca9926.png)

This should be new address showing on new regis.:
![image](https://cloud.githubusercontent.com/assets/8440903/6736230/e60ed592-ce39-11e4-95da-40a70ef1fc44.png)

**Comment by bradatkins** [comment]
Fixed that as part of a previous bug. Have a try now

**Comment by bradatkins** [comment]
And I don't know my states well, but zip code 77024 (Houston) is part of Texas not North Dakota :)
