### ISSUE TITLE
Needs to be resolved ASAP:  Applied commission and now balance due is wrong 417874

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#284]
I approved commission and it's actually showing on the invoice but now the balance due is not correct.  It should be showing as $4,058.20.

DB is deducting commission twice for some reason??

![image](https://cloud.githubusercontent.com/assets/8440903/6752948/d00678c2-cee8-11e4-9a60-8f9c2e4468bb.png)

**Comment by ali206** [comment]
another example:
![image](https://cloud.githubusercontent.com/assets/8440903/6759881/0e082432-cf1a-11e4-9df1-c03efa7cbc40.png)

**Comment by ali206** [comment]
another example:

![image](https://cloud.githubusercontent.com/assets/8440903/6921727/9e119982-d794-11e4-8b7f-8d0502b0f09a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6921738/a9c3c660-d794-11e4-9062-6fe58d6d81c9.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6997818/1a093074-db99-11e4-93f4-dd183d526b8b.png)

**Comment by ali206** [comment]
this is the same issue as #314 still

**Comment by bradatkins** [comment]
Hey -

We seem to be bouncing around here as to what should happen with commissions. I'm no longer even sure what should be happening now...

**Comment by ali206** [comment]
Commission earned should either deduct correctly as a payment or just simply show on the invoice. 

As per the #314 i think it should just simply show on the invoice so that when i approve the pending comm. payment, that will be the only amount deducting as a payment and this double amount will no longer be deducting. 

Commission earned is not deducting as a payment until i approve the pending comm. payment.

**Comment by bradatkins** [comment]
OK Check now...

**Comment by ali206** [comment]
commission payment i approved now has disappeared but is still an approved payment?

![image](https://cloud.githubusercontent.com/assets/8440903/7372448/c2bba1a4-ed94-11e4-8f8b-a66a8ac01547.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7372451/cbe256d8-ed94-11e4-9a3f-f03ea2566451.png)


Approved comm. payment should still show in payments section though.

Math is still off on this one b/c comm. is now not calculating in. 

Maybe just only have approved commission payment be the only comm. calculating in then.  Net orders will just show commission twice, once below order total (not sure why it's there) and then once in payments section where it actually calculates.

**Comment by ali206** [comment]
If i'm not making sense maybe address this issue with rinda/sandy/milanka

**Comment by bradatkins** [comment]
I'm pretty sure this is all fixed up with the recent commission work?

**Comment by ali206** [comment]
yes but the below bookings are still incorrect and re-adding commission with the fixes isn't correcting anything. Invoice looks correct but in view orders showing balance due of commission amount

417874
418474

**Comment by bradatkins** [comment]
I'm pretty sure commissions are all good now
