### ISSUE TITLE
DT061315 - 417477

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#285]
Something very odd happened here...

Stefanie created or someone had created the tour correctly.  

At some point after that, the tour# disappeared from All Dept., orders, etc.

When you went to edit order the tour that showed up was BCO-Nachef ...: 
![image](https://cloud.githubusercontent.com/assets/8440903/6753861/7a87d696-ceef-11e4-81ba-1a41acfe1a3a.png)

The order audit disappeared so i don't know if someone in our office did that by accident or the DB did. 

Also this message kept coming up which was wrong and had the wrong dates:
![ali](https://cloud.githubusercontent.com/assets/8440903/6753887/a744d008-ceef-11e4-8ea5-156376f1e998.png)

I was able to fix it by changing the tour to the correct tour it was originally booked on but just wondering how/why this happened??

**Comment by ali206** [comment]
Hi Brad, 

Does this have anything to do with why the wrong tours are showing up randomly on invoices??

When Irena went to apply the payment, she believes she edited the pending payment that was showing in All payments.  

And for every payment that you click "edit" for, this tour shows up:

![image](https://cloud.githubusercontent.com/assets/8440903/6757985/7e1e5e44-cf0b-11e4-96d7-01ce970dc4e4.png)

**Comment by bradatkins** [comment]
Possibly! I'll use this to have a look.

I'm guessing she didn't change the tour "on purpose" (ie the DB did it) ??

**Comment by ali206** [comment]
Correct

**Comment by bradatkins** [comment]
if this happens again, please let me know before the order is changed. Unfortunately there's tons of changes to this order and it'll take me forever to figure out

**Comment by ali206** [comment]
It happened some time last week (don't remember the booking #) but it was when Irena applied a payment from the external link, and then edited the payment from the payments section b/c she forgot for ex. to enter the ck #.

**Comment by bradatkins** [comment]
hmm..the order audit hasn't disappeared per say, but it is huge. There are 2,995 changes to this order (obviously not individual changes by Staff, but changes Staff initiated which triggers the DB to update stuff).

The DB is 'stopping' from showing them because it'll take everything down.

The tour # was showing up, but it was for donations, so that part doesn't matter, but I've fixed it anyways

![image](https://cloud.githubusercontent.com/assets/8440255/7101458/aa2c0238-e028-11e4-8d7b-b06d1cb718e9.png)

When/if this happens again to an order, please leave the order along so I can have a look

**Comment by ali206** [comment]
Ok so you're saying this should never happen again in the future then right?

**Comment by bradatkins** [comment]
I'm not saying that :)

I'm saying:

"When/if this happens again to an order, please leave the order along so I can have a look"

**Comment by bradatkins** [comment]
Do you have a new order where this happened with?

**Comment by ali206** [comment]
not that i'm aware of since last time, if there was i probably fixed it sorry
