### ISSUE TITLE
417844 - edit order has wrong dept date and showing wrong tour again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#286]
The other day (3/18) this final reminder email was sent out and the Tour# didn't show in the subject. 

I just sent a test email to myself and it's not showing.  

But when you go to edit order the dept. date is showing as 2010 and if you click on change tour it's showing the BOS-Nachef thing again?!?!?!

![image](https://cloud.githubusercontent.com/assets/8440903/6757182/89851404-cf05-11e4-82aa-44c1e77c632c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6757190/943d8e30-cf05-11e4-94f8-0bccf27fef7d.png)

**Comment by bradatkins** [comment]
There was two 168-A tours.

For some reason, this order was associated to the inactive 168-A
