### ISSUE TITLE
rooming list issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#287]
From: Yaritza Rodriguez 
Sent: Friday, March 20, 2015 12:42 PM
To: Ali Boulanger
Subject: Email to Brad

Hi Ali, 

There is “Dec 31” written in the middle of the rooming list. Can you please ask Brad why and ask him to remove it? It is unnecessary.

![yari](https://cloud.githubusercontent.com/assets/8440903/6757768/ef28ff7e-cf09-11e4-87eb-f4ccd8e38f08.jpg)
![yari 1](https://cloud.githubusercontent.com/assets/8440903/6757770/f1aff112-cf09-11e4-9b1a-621bf8f6d4e5.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6885992/7a53b28a-d5fc-11e4-86ad-c1d1e0856d58.png)
