### ISSUE TITLE
418089 - phone # not reflecting

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#290]
Yaritza updated client’s phone number in travelers and in the orders page, but the change does not reflect on her invoice.

**Comment by bradatkins** [comment]
What's the correct phone #?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6898753/d48e5c3c-d6c9-11e4-9818-c354211cdcb9.png)

**Comment by bradatkins** [comment]
Fixed, there wasa  bug.

![image](https://cloud.githubusercontent.com/assets/8440255/6909820/36357f44-d718-11e4-97a6-099a62f612c3.png)
