### ISSUE TITLE
Chrome not recognizing a tour

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#291]
When in Chrome the DB doesn’t recognize this tour (I was trying to update the invoices, # 417844 & 417845)
![meliss](https://cloud.githubusercontent.com/assets/8440903/6811844/48167082-d241-11e4-850b-ac3d3cd46364.png)
![nelissa](https://cloud.githubusercontent.com/assets/8440903/6811843/481273b0-d241-11e4-8b9f-fb0e371b6072.png)

**Comment by bradatkins** [comment]
What screen are you getting that Tour Departure error one? Can you take a screenshot of the screen before the error message?
