### ISSUE TITLE
Creating an email/alert for when pple in office transfer tours now for accting

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#293]
Since everyone in the office now has access to transfer tours, is there anyway you can have an email sent to accounting or some thing to alert me when someone transfer tours?  

I'm going to tell everyone to email me but i know majority of the office will not do that. 

I need to know EVERY time someone transfers tours so i can double check the math and update insurance information etc. if necessary.

**Comment by ali206** [comment]
If an email to accounting then subject can be REBOOKING from original tour to new tour

**Comment by bradatkins** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/8440255/6885957/331f456a-d5fb-11e4-8a19-be5de23c64eb.png)

**Comment by ali206** [comment]
ok was i supposed to receive that email for 418588? Because I didnt...

**Comment by bradatkins** [comment]
Oh I didn't actually test with sending it to you. I had it sending it to me when I was testing. Feel free to try yourself on this order.
