### ISSUE TITLE
#162 not showing dept. dates when trying to change tours

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#296]
But they exist in the DB:

418529 - Melissa tried to transfer to tour #162 7/3 dept. and since no dept. dates showed up i'm assuming that's why the clients all of a sudden disappeared from the invoice.

nothing in drop down menu to click on:
![image](https://cloud.githubusercontent.com/assets/8440903/6827900/f6131cae-d2e0-11e4-895d-6081037f0405.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/6885933/4f148b9c-d5f9-11e4-874e-099bb08da09e.png)

Worked OK for me, does it work for her and you? I didn't change anything

**Comment by ali206** [comment]
It's showing now but for some reason wasn't when i added this issue
