### ISSUE TITLE
Name will not show correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#297]
The spelling of “Enrique” in the address section. I can’t tell you how many times his name has been corrected in so many different places in the DB. Why  does his name still appears misspelled?

![yari 1](https://cloud.githubusercontent.com/assets/8440903/6828064/0e5e373e-d2e2-11e4-841c-dd52fecbfad8.png)
![yari](https://cloud.githubusercontent.com/assets/8440903/6828065/0e5f6910-d2e2-11e4-95e1-30106496a638.png)

**Comment by bradatkins** [comment]
Can you email me his email address and password so I can test?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6869220/ca09be7c-d468-11e4-92a8-b3814db40d85.png)
 
Try pword: 206tours

**Comment by bradatkins** [comment]
Hmm doesn't seem to work, but anywho.

The DB will pull the name/address from his latest order, which is 416683. There you can see his name is spelled incorrectly:

![image](https://cloud.githubusercontent.com/assets/8440255/6885676/7a337e9c-d5f8-11e4-955a-330c4182f1a5.png)

Correct it on this order and when you go to place his next order, it'll be good

**Comment by ali206** [comment]
According to Yaritza:

This is not fixed. I just tested it and when you create an order, his name still shows wrong in the address section:

![yari](https://cloud.githubusercontent.com/assets/8440903/7073837/248cda2c-dec4-11e4-88fd-838d62b76b6d.jpg)

**Comment by bradatkins** [comment]
OK, apparently I've been lieing! Ha, or more like not saying what was happening.

The DB was *supposed* be grabbing the latest address info (ie the info from the previous order) for the next order, but it wasn't.

It is now. This should clear up a lot of the address confusion we've been having for repeat orders I think

![image](https://cloud.githubusercontent.com/assets/8440255/7099762/90bbdc40-dfcb-11e4-9256-49202f6a2cef.png)
