### ISSUE TITLE
417949 - add cost not calculating in

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#298]
balance due should be $0.00

![image](https://cloud.githubusercontent.com/assets/8440903/6831195/184c24fa-d2f5-11e4-8170-6e69c0dc8230.png)

**Comment by bradatkins** [comment]
Hmm.. the way it's coded now is the SD Discount is 100% of the subtotal, hence why it's showing a refund of 132.

It's been like this forever, except for CLERGY discount. CLERGY is on Base Price only.

**Comment by ali206** [comment]
Ok. 

But somehow the SD Discounts are not showing in payments section so i can't edit the SD Discount. 

If i were able to edit the SD Discount $ amount then this "refund" could be avoided. 

not everything that gets added to a priests invoice is free.

![image](https://cloud.githubusercontent.com/assets/8440903/6921201/3dafd7a0-d791-11e4-8ffa-c2447c75fd58.png)

**Comment by bradatkins** [comment]
The SD Discounts are calculated at time of order (like Promotions) and are not currently editable.

Are all SD Discounts the same (ie what is free) ?

**Comment by ali206** [comment]
You did make them editable at some point that, i was able to do that.  It was an enhancement you activated and somewhere along the way it no longer worked.

All SD Discounts should be Editable, same as FREEs. No they're not all the same.  Some are Base price + single room, some are just base price, some are insurance some are not.
