### ISSUE TITLE
SOT2015G tour not showing all pple on recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#299]
There are 17 people on this tour and only 9 show up on the recap:

![image](https://cloud.githubusercontent.com/assets/8440903/6847192/fb53a8c2-d39a-11e4-87e2-2c9d83a9b8ba.png)
![image](https://cloud.githubusercontent.com/assets/8440903/6847199/01bd5b36-d39b-11e4-8bfe-5439b7fa962b.png)

**Comment by bradatkins** [comment]
There are 4 separate departures for this Tour:

2015-04-12: 2 PAX
2015-04-26: 8 PAX
2015-05-24: 9 PAX

The recap you are showing is for 2015-05-24, hence only showing 9 PAX

**Comment by ali206** [comment]
Sorry :( I know pregnancy brain is scientifically not a real thing but it has definitely been happening to me lately.
