### ISSUE TITLE
pending payments

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#301]
this also might be an old issue but can you please deactivate pending payments to reflect as a "payment" against the order total for when people try to make CC charges?

It used to be working correctly and somewhere along the way it went back to acting as a "payment" which is wrong.

**Comment by bradatkins** [comment]
It does list that there is a pending payment, but doesn't seem to affect the order. For example

This order total is $9289

![image](https://cloud.githubusercontent.com/assets/8440255/6885552/f1e60fe6-d5f2-11e4-8377-b22a50317a91.png)

I then chose full amount:

![image](https://cloud.githubusercontent.com/assets/8440255/6885553/f71ffad0-d5f2-11e4-8029-f0f137aabd34.png)

And then applied the payment, balance remaining is $0

![image](https://cloud.githubusercontent.com/assets/8440255/6885557/4381b832-d5f3-11e4-9356-b826fed39385.png)

**Comment by ali206** [comment]
I guess you can't recreate the issue then but it's definitely an issue. 

I get calls/emails all day long to void pending payments b/c pple in office are trying to put through CC's and they can't.

Next time it happens i'll let you know

**Comment by bradatkins** [comment]
Please do let me know, and if possible, do not apply the payment (ie leave
the order untouched) and take some screenshots
