### ISSUE TITLE
URGENT:: Agents don't have option to make payments via agent portal

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#304]
Hi Brad, 

How come agents don't have the ability to make payments from the agent portal?

Can you please add that as a feature ASAP?

The agent below is looking to make payments for her clients via her agent portal and is unable to.  She travels with us a lot. 

![image](https://cloud.githubusercontent.com/assets/8440903/6904499/2d011c72-d6ef-11e4-9019-ec9f5db45b65.png)

**Comment by ali206** [comment]
Sandy said agents used to have this feature

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/7845098/c65908ce-0482-11e5-9d0e-77a17f752479.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7845101/c929905a-0482-11e5-810e-93ac3d34078a.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7845104/cbfa6246-0482-11e5-89e1-ddba4d59c690.png)
