### ISSUE TITLE
"Departure" in subject of emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#306]
I thought this looked nicer but can you please remove the word departure from the subject of emails? Milanka no longer wants it there.

**Comment by bradatkins** [comment]
There is no "Departure" word, do you mean the Departing <Date> ??

**Comment by ali206** [comment]
yes

**Comment by bradatkins** [comment]
Done

**Comment by ali206** [comment]
We still need the dept. date just not the word Departing

**Comment by bradatkins** [comment]
Hmmm, that's going to look odd in my opinion no?

How are they going to know what that date is? It's sort of going to be "hanging" out there with no reference to what it is? I'll do it, but just wanted to provide an example before I did. Let me know

206 Tours Inc. Confirmation - Order #418595 Tour #FN042315 April 23, 2015

**Comment by ali206** [comment]
That's fine, milanka doesn't want the word in there. 

Can you add the date back though? You removed that whole part.

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/7333193/2ca78d80-eb33-11e4-8669-ff7e2eb99a73.png)
