### ISSUE TITLE
416876 - priest booking discounts/#'s not matching up

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#309]
Another priest invoice - SD discount was automatically applied, not showing in payments section, but on invoices is saying we owe them a refund of $5,095 which is wrong. 

And in view orders section the balance due is the cost of insurance so nothing's matching up.

![image](https://cloud.githubusercontent.com/assets/8440903/6921232/85973568-d791-11e4-881c-047ee0ec8ee8.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6921211/5598a45a-d791-11e4-91ad-017c6e6535fd.png)

**Comment by bradatkins** [comment]
It's showing fine to me? If that's because you've change the order, please create a test order to demonstrate the problem to me.

![image](https://cloud.githubusercontent.com/assets/8440255/7099438/f052d722-dfc0-11e4-9f2b-ddd127b31ca9.png)

**Comment by ali206** [comment]
SD Discount was manually applied b/c it didn't automatically apply when booking was created. 

So i just went in to the booking to remove insurance since it shows up as the incorrect premium, and after clicking update SD discount automatically applies itself.  

Then i would normally go decline the payment that we applied, which is unnecessary work.

![image](https://cloud.githubusercontent.com/assets/8440903/7188150/b885063a-e443-11e4-9b85-4f1bec346c74.png)

**Comment by bradatkins** [comment]
I think we fixed this functionality up previously
