### ISSUE TITLE
418075 - math is wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#310]
in view orders balance due is correct but when you open the invoice it's $3,548 balance due which is wrong.  Off by $150 for some reason:

418075 Feb 13, 2015 Endaya / Francisco 111 May 24, 2015  $3,698.00 $4,498.00 2 Deposit 

![image](https://cloud.githubusercontent.com/assets/8440903/6922912/793613ec-d79c-11e4-8a75-c5dd0d15820a.png)

**Comment by bradatkins** [comment]
Can you check this order again and tell what it should be?

**Comment by ali206** [comment]
It's PIF but invoice is still wrong - there's no refund due:
![image](https://cloud.githubusercontent.com/assets/8440903/7005052/2edcb670-dc42-11e4-9e25-7a4cfb825b66.png)

**Comment by ali206** [comment]
Same with 418666 - balance due on invoice is deducting an extra $150

**Comment by ali206** [comment]
Same with this one as well:
 https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=418660&GENERATED=TRUE&SHOW_COMMISSION=Y
![image](https://cloud.githubusercontent.com/assets/8440903/7068383/075fa002-dea0-11e4-90ea-2ceeb5732027.png)

**Comment by ali206** [comment]
Also 418665
