### ISSUE TITLE
Adding addt'l pax option

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#311]
can we have the ability to select a # from a drop down screen perhaps of how many pax we want to add to the invoice? Doing it 1 by 1 is sooo time consuming.

I registered 8 at once but now have to add an additional 27 1 by 1.

![image](https://cloud.githubusercontent.com/assets/8440903/6924150/6474045c-d7a4-11e4-9616-3ba000bc30eb.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/9456889/3bf3af30-4aab-11e5-8d6a-77c017b5dfaa.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9456891/3f0eee6e-4aab-11e5-9f34-4f1ca8cb5121.png)

**Comment by ali206** [comment]
This is done but there are issues i posted separately, i'll close this one
