### ISSUE TITLE
Commissionable Items for Agents

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#313]
Can you add Post Tour/pretour as an option to select that agents get commission on?

![image](https://cloud.githubusercontent.com/assets/8440903/6942623/d354414a-d856-11e4-83d4-0dc69a5b15d0.png)

**Comment by bradatkins** [comment]
Done.

**Comment by ali206** [comment]
Thanks!

Will this only be included if the pre/post was done as an option?  Not as an add cost right?

**Comment by bradatkins** [comment]
Correct. As an option not an add on cost
