### ISSUE TITLE
417185 - commission deducting twice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#314]
The commission payment i applied manually is the only commission that should be deducting from the order total.

![image](https://cloud.githubusercontent.com/assets/8440903/6942676/2e812efc-d857-11e4-9cd3-be8614e25f07.png)

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/6964579/8a6c5fa4-d918-11e4-8fc3-78bb4154db8d.png)


![image](https://cloud.githubusercontent.com/assets/8440903/6964588/a9bc1854-d918-11e4-954a-85cdc491fc99.png)

**Comment by bradatkins** [comment]
The DB is programmed to calculate the commission, are you saying it shouldn't be?

**Comment by ali206** [comment]
No it should still do that. 

But it doesn't calculate the balances correctly that's why i always have needed to approve the commission payment.  

Also, if i don't approve the pending commission payment in view payments it will always need to be declined.  What's the point of a pending commission payment automatically generating then?

**Comment by ali206** [comment]
The problem is that commission is set to calculate but it doesn't actually calculate in to the balance due.  Ex below:

If commission were calculating correctly the balance due would show as $0.00

![image](https://cloud.githubusercontent.com/assets/8440903/7005326/f487390c-dc44-11e4-9a9f-a1ade05873a2.png)

**Comment by bradatkins** [comment]
The commission is completely different, so not sure what to do.

To be honest with you, I'm not really even sure what you said above, as to me it's confused :(

**Comment by ali206** [comment]
Ok sorry i'll try to explain better...

The DB should calculate commission.  However the way it's currently working is not making sense on invoices.

If an agent is set up with commission like the above booking, it shows commission earned and that comm. earned will show as a pending payment in view payments.

How it's been working lately is that if I were to go approve the commission amount, that $532,22 will deduct twice from the invoice showing that we owe the client a refund of $532.22, which is wrong.  (don't actually use the above booking as an ex. in the DB b/c it's miraculously showing correctly now).

If the commission earned is going to show on the invoice, that's all it should do, show on the invoice. A pending comm. payment is always automatically generated and when i approve that, that should be the only comm. amount deducting as a payment.

Make more sense?

**Comment by bradatkins** [comment]
OK Fixed.
