### ISSUE TITLE
418520 - something very odd happened

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#316]
Customer made payment of $1,500 via CC (which is all that was charged in merchant):

![image](https://cloud.githubusercontent.com/assets/8440903/6948291/daf98580-d87a-11e4-9026-5d23832e1a9c.png)

Then the emails that were sent out automatically since customer made payment say thank you for payment of -$5,598???
![image](https://cloud.githubusercontent.com/assets/8440903/6948304/f42efd64-d87a-11e4-8410-11747b746e4f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6948310/fbd792c4-d87a-11e4-98b5-11daacb1104c.png)

But this was the first email sent out:

![image](https://cloud.githubusercontent.com/assets/8440903/6948341/29818d24-d87b-11e4-9b20-30a347938d04.png)

Why were there other emails sent out with the wrong amount then?

So confusing.

**Comment by bradatkins** [comment]
Forget that...it's fixed. What happened is he made a payment of $1500 then went and edited a PAX and made a payment but the DB got messed up.

Fixed now
