### ISSUE TITLE
Philipp Ehrman 415291  DOB wrong pax tried to change, but it will not update

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#317]
![image](https://cloud.githubusercontent.com/assets/8440903/6971006/7f676b6a-d947-11e4-9405-ef6f59ce706d.png)

from stef:
I first updated address in travelers and saved
![stef](https://cloud.githubusercontent.com/assets/8440903/6971027/a6ed7a3a-d947-11e4-91e8-ccb72cc7386a.png)

Then I went into all orders clicked his name and changed and saved
![stef 1](https://cloud.githubusercontent.com/assets/8440903/6971032/ae3e415c-d947-11e4-8ebe-727567b2f47b.png)

After that I clicked his order number (417477) and went to the bottom and updated.  I know I updated address last week. I can’t view audit to see exact date and time but I believe it was the next day that it properly reflected correct address.  
![stef 2](https://cloud.githubusercontent.com/assets/8440903/6971042/bb48c908-d947-11e4-8814-77ab4ec447e0.png)

**Comment by bradatkins** [comment]
what is the correct address?

**Comment by ali206** [comment]
that is the correct address...i think the issue is that it didn't show correctly after Stef updated everything.  But the next day it was correct?

**Comment by bradatkins** [comment]
it's very possible that I fixed a bug in between there. There's no jobs that run overnight that would fix it automatically the next day
