### ISSUE TITLE
418296 - email and order audit not matching - weird!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#318]
DB says customer made an ACH payment of $4,095:
![image](https://cloud.githubusercontent.com/assets/8440903/6972229/5f9d79f6-d950-11e4-8598-332dc9d56503.png)

But then an email was sent out as if the client made a CC payment?!

![image](https://cloud.githubusercontent.com/assets/8440903/6972244/6f7f5a7e-d950-11e4-9abd-f3880da0ecc1.png)

![image](https://cloud.githubusercontent.com/assets/8440903/6972259/792b6144-d950-11e4-9942-0362c79800f7.png)

**Comment by bradatkins** [comment]
Looks like agent Thu-Lan originally made a $200 CC payment on 418298 then mayde a $4,095 ECHECK payment on 418296.

The DB got mixed up with the email because two payments on two separate orders.
