### ISSUE TITLE
Emails over the weekend came through without a Tour#

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#319]
![image](https://cloud.githubusercontent.com/assets/8440903/7004590/9d94b56a-dc3b-11e4-8ff3-9c087fb4e522.png)

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/7024307/d7981b3e-dd09-11e4-9adc-9f31c0a5b274.png)

**Comment by bradatkins** [comment]
Fixed but will wait till this emails out again to be sure.

**Comment by ali206** [comment]
I'm not sure what you mean...wait til this emails out again?

**Comment by bradatkins** [comment]
Ya..to validate it's working

**Comment by ali206** [comment]
Oh like the type of email, another final payment reminder. Got it! lol
