### ISSUE TITLE
418642 - weird & wrong emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#322]
Order audit doesn't show anyone making a payment and sending an email:
![image](https://cloud.githubusercontent.com/assets/8440903/7008991/1ca27224-dc65-11e4-90c9-224c348102c3.png)

But these 2 emails were generated:
![image](https://cloud.githubusercontent.com/assets/8440903/7009002/318704a2-dc65-11e4-8d1b-5cfb049fba39.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7009005/36b64ffa-dc65-11e4-8cea-5868e839e655.png)

But the invoice emailed (#1) out doesn't even match the invoice in the DB (pic #2):
![image](https://cloud.githubusercontent.com/assets/8440903/7009019/564da534-dc65-11e4-8c73-5f16255ae220.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7009021/5fe4ea6c-dc65-11e4-8a0a-aebb8b3aedd6.png)

**Comment by bradatkins** [comment]
Originally Sammie logged a payment with the order via check for $0, that explains the odd email to payments@.

Can you forward me the emails for this order that you received?

**Comment by ali206** [comment]
forwarding now - another "Payment" email just came through with the incorrect invoice but there's nothing in the order audit report showing that anyone tried to make a payment today.

**Comment by bradatkins** [comment]
I couldn't seem to reproduce it, but I've put in some additional logging. If this happens again, please let me know

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/7252775/ecff57c4-e805-11e4-8b1e-8e576ccc45fc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7252801/0966724e-e806-11e4-8629-4d9bfc45220e.png)

**Comment by bradatkins** [comment]
Hmm I still can't reproduce it, but may have found the issue. Let me know if you see another one.
