### ISSUE TITLE
IMPORTANT: 416910 invoice won't open

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#323]
![image](https://cloud.githubusercontent.com/assets/8440903/7009557/2592f3be-dc69-11e4-9f80-f0fdb703301d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7009570/2dc70782-dc69-11e4-8b57-14596d0fade2.png)

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=416910&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by ali206** [comment]
Neither will this one:

![image](https://cloud.githubusercontent.com/assets/8440903/7073216/d15c5e26-debf-11e4-942d-332d14526013.png)

**Comment by bradatkins** [comment]
Try now?

![image](https://cloud.githubusercontent.com/assets/8440255/7099315/c009b2b4-dfbd-11e4-8be4-5acc338f9c30.png)

**Comment by ali206** [comment]
Ok working thanks. 

Freddie's total trip costs are wrong though, should only be $5898 and updating didn't fix it.

**Comment by bradatkins** [comment]
Maybe I click update a little harder then you guys, but updating it worked fine to fix the cost?

I tend to click on the "d" of "Update" if that makes any different? :)

![image](https://cloud.githubusercontent.com/assets/8440255/7149881/37fbb206-e2e1-11e4-8b70-d802f28b01b9.png)

**Comment by ali206** [comment]
So strange, none of this was literally working for us.
