### ISSUE TITLE
liz unable to open blue sheet normally for tour FM090615

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#325]
She's using IE version 11 and when she clicks on the blue sheet nothing happens or opens up. 

the only way she's able to look at it is by right clicking on the blue sheet and selecting open in new tab

**Comment by bradatkins** [comment]
Worked OK for me. Does it work for anyone else in IE 11 at the office?

![image](https://cloud.githubusercontent.com/assets/8440255/7099298/70668ff2-dfbd-11e4-952d-603f65e0bcd4.png)

**Comment by ali206** [comment]
Yes but it's not working for her with the same version of IE

**Comment by bradatkins** [comment]
Sorry, it's not an issue with the DB then. Have Ronen have a look or something. Not much I can suggest.
