### ISSUE TITLE
Edit Order Page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#327]
Anyway you can make bag option and roommate fit better?
![sandy](https://cloud.githubusercontent.com/assets/8440903/7049169/88c8caee-dde5-11e4-815f-729b4c779786.png)

**Comment by bradatkins** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/8440255/7099280/20fb72e8-dfbd-11e4-843d-92f782240ece.png)

**Comment by ali206** [comment]
good thanks!
