### ISSUE TITLE
Promo code issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#330]
Hi Brad, 

So the invoice the client received in the mail for this booking shows a balance due of $9,698 which they paid by check.  However, after the payment was applied the balance due then showed as $100.00.  Only thing we can think of was that it was a promo code glitch again.  

They do actually owe us $100 so the invoice below looks correct but just letting you know about it. 

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417432&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
But the invoice looks OK? I think?

![image](https://cloud.githubusercontent.com/assets/8440255/7127246/43cbfec4-e20f-11e4-9ed8-17b1e9ce3a1f.png)

**Comment by ali206** [comment]
Because we were forced to absorb the $100 balance that he technically owed so we lost money b/c of this.

Take out that $100 discount and you'll see what i was talking about

**Comment by bradatkins** [comment]
Hmm I think I found it, perhaps.

Look at the subtotals. It looks like the DB is taking $100/PAX. I'm guessing it should only be taking $100 order total?

![image](https://cloud.githubusercontent.com/assets/8440255/7265780/39c9e026-e86d-11e4-8a66-a469ea98bf0d.png)

**Comment by ali206** [comment]
Nope, promo codes should be taken out per pax subtotal but only show in payments section not actually deduct again against the order total.

**Comment by bradatkins** [comment]
K sorry, it has been doing this forever (deducting against the passenger total. This is a large change to modify this functionality. I'll have to mark it a an enhancement as it has been like this forever.

**Comment by ali206** [comment]
Hang on, when you say deduct against the passenger total you mean in the payments section on the invoice?  B/c if that's what you mean then how come we've never had a problem with it calculating until now?

**Comment by bradatkins** [comment]
This is likely fixed with all the fixes we made recently If not, please reopen
