### ISSUE TITLE
Future website - UI

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#331]
Hi Brad,

i am using the same code for both tours, but on tour 1 the DB looks different for some reason:

Tour 1:
http://www.206tours.com/tour1/index8.htm

![image](https://cloud.githubusercontent.com/assets/10079829/7117501/fd3b644c-e1c6-11e4-8abb-24cd77b391ad.png)

Tour 96 looks better:
http://www.206tours.com/tour96/index11.htm

![image](https://cloud.githubusercontent.com/assets/10079829/7117508/04c65334-e1c7-11e4-8f64-ff96b3e2e627.png)

**Comment by bradatkins** [comment]
Hey -

To be honest, it looks the same to me? Except one has wait list buttons and
the other doesn't...

You must have good eyes.

**Comment by ronenreinheimer** [comment]
Hi Brad,

Right now I am building my 3rd tour and I don’t see the issue. So I will get back to you on this matter. Please leave it open in GHub for now.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

I see the issue, when its wed – wed or 2 long days of the week, it pushes everything over to the right. 

What if we change the format to Wednesday – Wednesday and we eliminate the  (  )  ?

![image](https://cloud.githubusercontent.com/assets/10079829/7235696/cf7fdb86-e75d-11e4-8f89-d7a61d2b3995.png)
