### ISSUE TITLE
DB for tour not working?  - URGENT!

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#332]
Hi Brad,

We are trying to land a huge client, I am putting together a sample site for them. Any idea why the DB is not working?

http://pilgrimages.com/focus

DB code:
FO052017

**Comment by bradatkins** [comment]
Fixed. Tour # was missing:

![image](https://cloud.githubusercontent.com/assets/8440255/7127182/69a684a8-e20e-11e4-946f-f73b176e0888.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7127184/6e9045d0-e20e-11e4-8e7a-d8caf6e9423d.png)
