### ISSUE TITLE
Option to display separately 2015 & 2016 dates for a specific series tour - URGENT!!!

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#334]
Hi Brad,

Tour 8 (any many other similar tours) are going to change in 2016, but we need to display 2 different inclusions and itineraries for clients (being it is still 2015 we still need to show them the 2015 inclusions and itinerary). So Basically Milanka needs you to give us an option in the DB to select which year we want clients to see for any given tour.

For example:
I will build a splash page for Tour 8 and it will have 2 links - click here for 2015 dates and prices and a 2nd link for 2016 dates and prices. So on the Tour 8 2015 page we only want 2015 tour dates to display and the same for the Tour 8 2016 page.

Milanka needs this as soon as possible, can you please help us!

![image](https://cloud.githubusercontent.com/assets/10079829/7143477/d696cd30-e2ad-11e4-8206-46730c54ebdc.png)

![image](https://cloud.githubusercontent.com/assets/10079829/7143481/deca5eb8-e2ad-11e4-9e59-e7979887f653.png)

**Comment by bradatkins** [comment]
Done
