### ISSUE TITLE
417290 - all but 1 pax missing from invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#336]
There should be 15 not 1:
![image](https://cloud.githubusercontent.com/assets/8440903/7160447/0eb21310-e357-11e4-8f84-ca35ecb3d78f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7160451/14872168-e357-11e4-82cf-697c813bebdf.png)

**Comment by bradatkins** [comment]
Fixed.

**Comment by ali206** [comment]
The order total isn't updating though now

**Comment by bradatkins** [comment]
For whatever reason, passengers didn't have Travel Arrangements (Land or Air) and the DB wasn't alerting.

I've added the alerting. Once you specify all the arrangements and update the order, the order total will be fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/7264480/e31e3c8a-e859-11e4-84d4-7de9fd3e4302.png)

**Comment by ali206** [comment]
not working correctly - air + land is selected and there's only 1 pax on this invoice (418664):

![image](https://cloud.githubusercontent.com/assets/8440903/7283725/8a720dca-e906-11e4-93b7-90f95236eff0.png)

**Comment by bradatkins** [comment]
I didn't fix this one. I fixed 417290. Try that one and let me know

**Comment by ali206** [comment]
ok i added that as a separate issue. 

417290 - not correct internally but balance due is now correct:

![image](https://cloud.githubusercontent.com/assets/8440903/7298276/74c7ee68-e99c-11e4-9998-1e8968634428.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7298284/8139385a-e99c-11e4-9c06-a65455d4d2e2.png)

**Comment by bradatkins** [comment]
Fixed the air and land thing
