### ISSUE TITLE
small triangle on future website top navigation

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#339]
Hi Brad,

Thank you (and Ronen of course) for doing such an amazing job on the new site.
There is just one small thing that I was hoping you could adjust.

When you hover over the top navigation you see this triangle show up.
Can you please remove this?

 
![image](https://cloud.githubusercontent.com/assets/10079829/7235743/31c0bbb2-e75e-11e4-9abe-58695d8190e3.png)

![image](https://cloud.githubusercontent.com/assets/10079829/7235746/3a0f535a-e75e-11e4-91c7-015cb0217a98.png)

![image](https://cloud.githubusercontent.com/assets/10079829/7235740/28e47ae2-e75e-11e4-876a-afff6ec23508.png)

**Comment by bradatkins** [comment]
Remove this section:

#cssmenu > ul > li.has-sub::after {
  right: 10px;
  top: 20px;
  border: 5px solid transparent;
}

**Comment by ronenreinheimer** [comment]
You are the man!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
