### ISSUE TITLE
Recaps and addt'l options row

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#341]
For pple that do not accept addt'l options they should not have that row show under their name:

![image](https://cloud.githubusercontent.com/assets/8440903/7258101/42f4888a-e828-11e4-9858-d163d02316ad.png)

I go one by one deleting those rows b/c they're unnecessary and make the recap chaotic for me. 

Can you fix that?

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7264125/4c2a1b62-e856-11e4-9f8a-ccf0e68c919b.png)
