### ISSUE TITLE
418863 - i didn't receive any emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#343]
Sandy registered through 206Tours website as a "client" yesterday and she received the correct confirmation email, however i didn't receive any emails that a new order had been created??

418863 Apr 21, 2015 Lippold / Sandra 1 Dec 3, 2016  $2,198.00 $2,198.00 1 New
Request

**Comment by bradatkins** [comment]
Pretty sure I fixed this, but obviously can test getting orders@ emails.

Please get Sandra to do another test.

**Comment by ali206** [comment]
I just did a test booking and got the confirmation email:
![image](https://cloud.githubusercontent.com/assets/8440903/7300528/9e778422-e9aa-11e4-9feb-389b4e66fae3.png)
