### ISSUE TITLE
Blue sheet payments question

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#344]
Are all types of payments, including comm. payments supposed to show on blue sheet?

Sorry i never use the blue sheet but Piernha all of a sudden is saying the blue sheet is missing all these things:

Blue sheet
![image](https://cloud.githubusercontent.com/assets/8440903/7279023/00d1395c-e8e7-11e4-82ec-c38c1913dbb7.png)

invoice:
![image](https://cloud.githubusercontent.com/assets/8440903/7279034/13021e20-e8e7-11e4-8ac1-0759bf5a74f6.png)

**Comment by bradatkins** [comment]
Nothing Agent related (commissions, address, etc) have ever shown on the blue sheet

**Comment by bradatkins** [comment]
Not to say they can't, but it was never written that way
