### ISSUE TITLE
418866 - issues on customer side

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#345]
Customer is unable to pay by cc apparently. He said on his screen there's no option to log out and that it's not letting him enter in a $ amount, he has a few different cards to use.

**Comment by bradatkins** [comment]
Can you tell me their email address? Or Order #?

**Comment by ali206** [comment]
418866

**Comment by bradatkins** [comment]
Not really sure what his issue is?

![image](https://cloud.githubusercontent.com/assets/8440255/7550319/10ec52b2-f62b-11e4-8dcb-76bfb4d84a22.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7550321/1b0a3cc8-f62b-11e4-8ba9-c21851710af6.png)

**Comment by ali206** [comment]
I'm just passing on the message we received from the client, i don't actually know what he was looking at. 

Is there another option other than full payment?

**Comment by bradatkins** [comment]
Closing as the new interface seems to beOK
