### ISSUE TITLE
417988 - email says CC but i just applied a ck

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#347]
I just applied a check payment for $378.00.  After applying a check and you get the payment confirmation screen, i clicked the email icon button from there which does not give option to edit email text.  

Also, clicking the email icon from that page sends an email out such as below stating that it was a CC applied and not a check??

![image](https://cloud.githubusercontent.com/assets/8440903/7305841/0809f64e-e9cf-11e4-9212-3ac6f1535133.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7309902/4dd4834c-e9f2-11e4-92e2-e206b7a11985.png)
