### ISSUE TITLE
Order audit for 418885

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#348]
Customer hasn't touched this booking yet so why does it say that next to payment by Check?

![image](https://cloud.githubusercontent.com/assets/8440903/7320847/dff21f62-ea6c-11e4-9933-4df39be3aaba.png)

**Comment by bradatkins** [comment]
Fixed, there was a bug in the tracking in the payments screen

![image](https://cloud.githubusercontent.com/assets/8440255/7333124/43b4ad26-eb30-11e4-8cf0-f7dd977d1275.png)
