### ISSUE TITLE
Bag type issue during registration?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#349]
I tried to sign up a Pilgrim and they said they weren’t sure what bag so I left it blank and then this came up
![sammie](https://cloud.githubusercontent.com/assets/8440903/7322962/659c2caa-ea79-11e4-9bff-a28355075736.png)

If we put “none” as the bag type we might assume they didn’t want one but really at the time of booking they were not sure.

**Comment by bradatkins** [comment]
It's currently a required field, I can make it not required and you can leave it as blank then. Let me know.

But be aware, then people won't be forced what to pick

**Comment by ali206** [comment]
Can you maybe add a "not sure" or an "I don't know" option to the drop down then? I think it should remain mandatory

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/10530558/e0e02aa2-7376-11e5-9eb5-d830525a204f.png)
