### ISSUE TITLE
416504 - cxl calculation problems

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#353]
i'm trying to cxl joyce but there's no box for me to enter in the amount of cancellation i need to apply ($471):

![image](https://cloud.githubusercontent.com/assets/8440903/7327251/be68cb84-ea99-11e4-8335-86907e51d392.png)

**Comment by bradatkins** [comment]
Click the X next to their name again and you should be able to

![image](https://cloud.githubusercontent.com/assets/8440255/7333062/3f866f76-eb2d-11e4-96c5-ea3f67cd93a1.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7333063/4303b852-eb2d-11e4-845c-fa10a9398941.png)

**Comment by ali206** [comment]
i know but that uncancels them - when i try to re-cancel them those boxes don't show up

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7550363/79558b32-f62d-11e4-9204-1c89dd5d0b71.png)
