### ISSUE TITLE
Unable to search by pmnt date and customer name

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#355]
Can't search by payment date and customer name in payments section

![image](https://cloud.githubusercontent.com/assets/8440903/7351026/be927298-ecd0-11e4-85c7-70780bab8697.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
this is the message i'm getting now:

![image](https://cloud.githubusercontent.com/assets/8440903/7371537/9b95e468-ed8f-11e4-8151-25b6c75d1efa.png)

**Comment by bradatkins** [comment]
Can you take a screenshot of the screen before?

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/7372282/e544f37a-ed93-11e4-8532-440839768975.png)
 from all payments or all payments current year

**Comment by bradatkins** [comment]
This is fixed now, correct?

**Comment by ali206** [comment]
nope still not working

**Comment by bradatkins** [comment]
Seems to be working now

![image](https://cloud.githubusercontent.com/assets/8440255/20246435/b0b1e36c-a984-11e6-8917-8dc40b0cb623.png)
