### ISSUE TITLE
Clients not getting payment confirmations

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#357]
![image](https://cloud.githubusercontent.com/assets/8440903/7374175/a8883400-ed9e-11e4-8750-30b3db3b2f00.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7441439/3db00016-f0b6-11e4-9da2-314de28c4221.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7441443/46fbb8cc-f0b6-11e4-8534-538ad0a03945.png)
