### ISSUE TITLE
order audit not correct for 418914

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#358]
Did customer really do a check payment? I'm thinking no...
![image](https://cloud.githubusercontent.com/assets/8440903/7374601/41fa6e9e-eda1-11e4-978c-cdb35fdadacf.png)

**Comment by bradatkins** [comment]
Fixed. I've put some additional logic in here to prevent this, but I couldn't reproduce it myself. Keep an eye out.

![image](https://cloud.githubusercontent.com/assets/8440255/7441324/0e69ea42-f0b1-11e4-8f49-eac85cd3577c.png)
