### ISSUE TITLE
Initial Confirmation Email for 418914

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#359]
Liz registered this client and then emailed her the confirmation to herself but the email text is incorrect.  She may not have understood my question and i didn't see the steps she took in registering/emailing but can you see why the email didn't come through correct?

![image](https://cloud.githubusercontent.com/assets/8440903/7374938/29afd6ce-eda3-11e4-874e-51481d213263.png)

**Comment by bradatkins** [comment]
Hmm odd. Everything from the logs indicates it should have worked correctly. I tried it myself and got the right result.

Tell her to keep an eye out for the steps next time:

![image](https://cloud.githubusercontent.com/assets/8440255/7441414/49a671b2-f0b5-11e4-872c-1ff2ef2ce730.png)
