### ISSUE TITLE
wrong info pulling up when registering client

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#360]
All Travelers is correct info but when we go to register this guy wrong info pops up - where is this info being pulled from? Should be from all travelers...

![image](https://cloud.githubusercontent.com/assets/8440903/7393242/a75cd8b2-ee5a-11e4-817f-3512808c0def.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7393244/ab45f06c-ee5a-11e4-9884-a78533c6d770.png)

**Comment by ali206** [comment]
I just updated info here from a past order but we shouldn't have to update a past order's information in order for current information to show up on a new registration. 

I don't think it makes sense that DB is pulling information from this location:
![image](https://cloud.githubusercontent.com/assets/8440903/7393304/f76361dc-ee5a-11e4-9f0d-e24e00b5f678.png)

**Comment by bradatkins** [comment]
I'm confused, looks ok to me?

![image](https://cloud.githubusercontent.com/assets/8440255/7550312/c52c670e-f62a-11e4-8b80-fd7df0e430e6.png)

**Comment by ali206** [comment]
See 2nd message i sent about this please (above)

**Comment by bradatkins** [comment]
It pulls the latest address. If that's not the address you want, you can select "No" under "Use these addresses for this order.

That's the way it works...

**Comment by ali206** [comment]
But you don't think it's pulling the latest address from the wrong spot?

Shouldn't the DB be pulling the latest address from All Travelers?  Currently it's pulling it from where you click on the clients name in All orders section

**Comment by bradatkins** [comment]
Old interface, I don't think this is hapenning now
