### ISSUE TITLE
What is going on with commission?!?!!?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#361]
Commission payments i've manually applied (even if client is not set up as an agent) are not showing on invoices when sent to the person that's registered so their balance that they're seeing is wrong?!

1st pic is invoice in DB & 2nd pic is copy of invoice that comes through when emailed:

![image](https://cloud.githubusercontent.com/assets/8440903/7394359/0d4d6f6e-ee61-11e4-8821-66cacd968d46.png)
![image](https://cloud.githubusercontent.com/assets/8440903/7394364/13034690-ee61-11e4-8648-ac89fe5307ae.png)

**Comment by bradatkins** [comment]
Ali -

Commissions only show up in two situations

1) If 206 Tours staff is looking at the invoice
2) An agent is emailed the invoice

In this scenario commissions will not show up if the person is not setup as an Agent
