### ISSUE TITLE
Radio button in orders - Urgent

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#363]
Hi Brad,

Melissa has an issue with this order, she needs to get rid of the post tour, but it came up as a radio button and not a check button. Can you please look into this issue, she needs to fix it for the client.

417908

![image](https://cloud.githubusercontent.com/assets/10079829/7434475/120a284a-f009-11e4-8f13-40f28c055530.png)

**Comment by bradatkins** [comment]
Check the box at the bottom to delete all options.

**Comment by ronenreinheimer** [comment]
She is scared it will delete everything? I don’t really deal with orders, so I am not familiar with this section of the DB.


God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
No it'll just delete any adding tht are checked...I'm pretty sure ;)

**Comment by ronenreinheimer** [comment]
lol, OK I’ll tell her to try.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
