### ISSUE TITLE
Orders pending Invoice Email - Not loading

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#364]
https://www.206tours.com/register/admin/showorders.php?page=1&FORM=Orders&QueryType=Orders_SendInvoice&LIMIT=500

Hi Brad
When you go to Orders pending Invoice Email (69) its only loading the first few (5) on page 1 when you click next its loading page 2 but page 1 only the first 5 load

**Comment by bradatkins** [comment]
Fixed

**Comment by Sandra206** [comment]
Yey! tested and working
