### ISSUE TITLE
CSS link color assistance - New Site

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#365]
Hi Brad,

I have a lot of links in white and blue depending on the background color. the issue is that the visited links appear dark on the dark backgrounds and if i adjust it for the dark background you cant see the visited links on light backgrounds. i think a solution might be to use 2 different .css files maybe one dedicated to links? how can we resolve this issue?

![image](https://cloud.githubusercontent.com/assets/10079829/7517583/e55a80d4-f4a3-11e4-8a3c-9cf26b401d97.png)

**Comment by bradatkins** [comment]
This isn't a DB issue...but

a:visited { 
    color: white;
}
