### ISSUE TITLE
URGENT: agent needs copy of invoices ASAP 418917

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#366]
We switched her to Gross Commission but after updating the booking it's not showing correctly on the invoice. 

Net amount should be removing itself now that she's GROSS.  

And commission to be approved by me should be for $999.60

![image](https://cloud.githubusercontent.com/assets/8440903/7567771/d3ab4f68-f7cc-11e4-8438-64c50835dc4e.png)

**Comment by ali206** [comment]
and her booking 418276

**Comment by bradatkins** [comment]
Can you try taking the agent off this order then re-adding them?

Brad

**Comment by ali206** [comment]
didn't work and i just tried doing a new registration and it's still not coming up correctly. 

If we book a GROSS agent commission earned should not be showing ever.

She needs a correct invoice, with "commission earned" not showing, any way to remove that immediately?
