### ISSUE TITLE
Payments section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#367]
also unable to search by payment date and type of payment

![image](https://cloud.githubusercontent.com/assets/8440903/7574785/e7b9d0b6-f7fd-11e4-81bd-ee497e7331a0.png)

Just brings me here - same page:
![image](https://cloud.githubusercontent.com/assets/8440903/7574793/f1e0de36-f7fd-11e4-8930-0c44307b0266.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/7577724/c63bab00-f819-11e4-867e-edee2de4c0be.png)
