### ISSUE TITLE
418974 - mcnamara SD issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#368]
I removed him as SD for this tour updated invoice and it's not correcting itself. 

Subtotal should be $1,400 and SD discount should remove itself unless i'm missing a step?

![image](https://cloud.githubusercontent.com/assets/8440903/7575424/a156d3c6-f802-11e4-8134-ed1e2c701fd5.png)

**Comment by bradatkins** [comment]
Looks like it was fixed.
