### ISSUE TITLE
Registering as an agent

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#370]
if i logged in with a password why is DB asking me for another pword confirmation?

![image](https://cloud.githubusercontent.com/assets/8440903/7594830/52121956-f8b1-11e4-9675-e6801a63a418.png)

**Comment by bradatkins** [comment]
I can't check, but what the DB does is the following:

1) Checks for the entered email and password combination
2) if it doesn't find one, and doesn't find that email address, it assumes you are a new customer.

So what I suspect happened here is this email address didn't exist in the DB at the time as a Traveler it's registering you as a new Traveler
