### ISSUE TITLE
Gross Commission Example

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#371]
This agent is listed as GROSS and commission earned should not be showing - the $900 should be in the PRO column instead:

![sandy](https://cloud.githubusercontent.com/assets/8440903/7595824/6a0eb734-f8b7-11e4-914d-a887214efb31.png)

**Comment by bradatkins** [comment]
Fixed . I did put the COMMISSION back to Pending though

![image](https://cloud.githubusercontent.com/assets/8440255/7666485/eb16cd3a-fbb4-11e4-9b95-5bfc1cd5c010.png)
