### ISSUE TITLE
418984 - very odd emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#374]
![image](https://cloud.githubusercontent.com/assets/8440903/7619365/34caeda2-f986-11e4-9d18-b5096a5b6f29.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7619375/49186bea-f986-11e4-9dab-33f2a3bb0b2d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7619378/4ee96d76-f986-11e4-8e71-80dba0ece92c.png)

**Comment by bradatkins** [comment]
I'm not seeing these anymore, are you?

**Comment by ali206** [comment]
not recently
