### ISSUE TITLE
Wrong agent linked to order on invoice but not in all orders?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#376]
Jan Paytas should not be agent linked to this order like it shows on invoice:

![image](https://cloud.githubusercontent.com/assets/8440903/7633245/043a0178-fa21-11e4-8f7f-b066ace882fb.png)

In all orders though the correct agent is showing???

![image](https://cloud.githubusercontent.com/assets/8440903/7633252/10fefbd4-fa21-11e4-8065-597905e3b63f.png)

How do i fix that?

**Comment by bradatkins** [comment]
Fixed, it was a bug

![image](https://cloud.githubusercontent.com/assets/8440255/7644990/fcb3cdf2-fa7b-11e4-8cb6-63eece30d3ed.png)
