### ISSUE TITLE
Re-entering existing clients account info when registering?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#377]
should not have to do that if they already have an account right?

![yari](https://cloud.githubusercontent.com/assets/8440903/7633323/6f41d5f4-fa21-11e4-95e7-6dc5f202113b.png)

![yari 2](https://cloud.githubusercontent.com/assets/8440903/7633327/72fea866-fa21-11e4-9b1b-4d46e2cc50bc.jpg)

**Comment by bradatkins** [comment]
This was likely fixed a while ago:

![image](https://cloud.githubusercontent.com/assets/8440255/9026269/318cd3b6-38f7-11e5-9c1c-9c00854eec94.png)
