### ISSUE TITLE
Internal Search Engine - Security?

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#378]
Hi Brad,

On google chrome we are seeing this:

![image](https://cloud.githubusercontent.com/assets/10079829/7638102/8a2ec02e-fa40-11e4-926e-de72f907a058.png)

is this in cause for alarm?

can you also change the color of D in the word Dates to white, it is currently blue.

thank you.

**Comment by bradatkins** [comment]
I notified Sandra on this already...haven't heard back. I don't think it's
a "good" thing...but probably not overly bad either.

But I guess from a user's perspective, I would probably be alarmed.

It's not a DB thing

**Comment by ronenreinheimer** [comment]
OK thank you Brad. Can you please see why the letter D in Dates is blue?

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
