### ISSUE TITLE
trying to manually apply a discount and not working 418342

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#379]
through the payment section screen and it's not posting to the invoice. 

![image](https://cloud.githubusercontent.com/assets/8440903/7640428/35b934c8-fa51-11e4-870c-892634be8871.png)

After confirming that discount the invoice was still showing a balance due of $5,624.00.

I manually added the discount through my external link and it finally worked so i don't know if you'll be able to see the issue on this one.

**Comment by bradatkins** [comment]
Fixed
