### ISSUE TITLE
418776 - payment email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#382]
i believe this email was sent out from the payment confirmation page but no $ amount showed up in email?

![image](https://cloud.githubusercontent.com/assets/8440903/7681685/153e993a-fd40-11e4-8272-6f3c8de6b4d2.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7681689/1b19d810-fd40-11e4-81a3-103fb2f032e5.png)

**Comment by ali206** [comment]
There's also this email that came through first for a payment that wasn't even made on the invoice?!

![image](https://cloud.githubusercontent.com/assets/8440903/7681707/3c41b6f2-fd40-11e4-8538-519b386a0adf.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
