### ISSUE TITLE
Email with no order # again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#383]
????

![image](https://cloud.githubusercontent.com/assets/8440903/7684285/e108f896-fd52-11e4-888a-8a05b638bfdb.png)

**Comment by ali206** [comment]
another example:
![image](https://cloud.githubusercontent.com/assets/8440903/9637304/02b21224-516e-11e5-8906-11c0f39f428f.png)

**Comment by bradatkins** [comment]
OK I think I may actually know what's going on...or at least where it's
going on!

**Comment by bradatkins** [comment]
OK I wasn't able to reproduce it, but I've put in a fix which I think will work
