### ISSUE TITLE
418972 - name not showing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#385]
in view orders

![image](https://cloud.githubusercontent.com/assets/8440903/7710913/1fde2ffe-fe35-11e4-97b8-ac0d91c49533.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7710917/25faa20a-fe35-11e4-8cfa-766f798c7ce3.png)

**Comment by bradatkins** [comment]
K, I have no idea what Elise was doing when she made this booking lol

She first searched for Steve in All Travelers, couldn't find him
Then went to place an order as an existing PAX but didn't provide an email address
Then she searched in admin in All Travelers for him again
Then created his Traveler record in the admin
Then went and finished her order 

So long story short, I suggest Elise stick to one train of thought to have more success :)

I've fixed this order

![image](https://cloud.githubusercontent.com/assets/8440255/7762352/56107820-0001-11e5-83d7-77bb3f98b75f.png)

**Comment by ali206** [comment]
Thanks, not sure why she did that either. 

It's showing 0 pax registered but he's not cancelled, i can't fix that:

![image](https://cloud.githubusercontent.com/assets/8440903/7771379/f0d280b6-0064-11e5-90d2-3daeeae65e23.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/9026279/7385e744-38f7-11e5-991c-6db4227c603b.png)
