### ISSUE TITLE
registered passengers not searching properly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#388]
When i type in tour#111 in registered passengers it pulls up all past tours first (2010) 

![image](https://cloud.githubusercontent.com/assets/8440903/7779480/ba8c3770-00a2-11e5-83ee-8f0eba66c053.png)

so then i click on page 2 and it brings me to all random tours. 
![image](https://cloud.githubusercontent.com/assets/8440903/7779482/c337ed2e-00a2-11e5-808a-1feceba69d7d.png)

**Comment by bradatkins** [comment]
Fixed. I also sorted it by Departure Date DESC
