### ISSUE TITLE
2016 Bold Dates

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#389]
The website tour pages has some formatting inconsistencies. 

For example.. 
http://www.206tours.com/tour1/      has 2016 without bold

http://www.206tours.com/tour1b/     2016 dates are not bolded 

thank you

**Comment by bradatkins** [comment]
which function are you calling in each of those pages? the _phase8 one?

**Comment by ronenreinheimer** [comment]
Each one is different, I didn’t upgrade tour 1b yet.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by bradatkins** [comment]
OK. I'm only fixing _phase8 now...I'm not applying the changes to
both..I've 'retired' the original one

**Comment by ronenreinheimer** [comment]
Understood!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>

**Comment by ronenreinheimer** [comment]
Hi Brad,

When you can, Sandy asked if you can please bold the 2016 dates:

thank you!

![image](https://cloud.githubusercontent.com/assets/10079829/9612661/e99e348e-50b4-11e5-9a98-8255ef082991.png)
