### ISSUE TITLE
Unable to open pdf invoices from orders emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#390]
![image](https://cloud.githubusercontent.com/assets/8440903/7815783/7b13713c-0398-11e5-8330-9a7082875104.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7815792/823afb74-0398-11e5-816a-89ade5a20b50.png)

**Comment by bradatkins** [comment]
Can you forward me the email?

**Comment by ali206** [comment]
just did

**Comment by bradatkins** [comment]
It seems to work OK for me?

**Comment by ali206** [comment]
Not sure why it's working for you?

it's not working for Sandy, myself still or clients either, we got at least 5-10 emails yesterday from people saying they tried to open it and it wouldn't.

**Comment by bradatkins** [comment]
Check Monday and let me know. I think I may have fixed something, but i couldn't reproduce it so not sure.

**Comment by ali206** [comment]
so far things are ok...
