### ISSUE TITLE
unable to open any invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#392]
![image](https://cloud.githubusercontent.com/assets/8440903/7816817/92ad481c-039e-11e5-990d-211fb18139aa.png)

**Comment by bradatkins** [comment]
I tried a bunch? Can someone else try? Maybe it's your computer?

![image](https://cloud.githubusercontent.com/assets/8440255/7817062/2bdcc8b8-03a0-11e5-9c7c-b904abe44ecf.png)

**Comment by ali206** [comment]
ok odd, i just closed IE and reopened and it's fine now, sorry
