### ISSUE TITLE
When We Change Tours in Database the Audit does not Reflect correct

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#395]
I have seen this on other invoices as well, just snagged this shot for you.  Was on Tour 37 moved to Tour 40, never was 117-a or 119-a.  Thank you.

**Comment by bradatkins** [comment]
I did a test before fixing anything and this is what I got Are you expecting something different or?

![image](https://cloud.githubusercontent.com/assets/8440255/8016778/2ddf284a-0bb6-11e5-87d9-73c63453d0ac.png)

**Comment by Sandra206** [comment]
Yes. That's perfect thank you

Feel free to contact me with any questions.

With Kind Regards,

Sandra Lippold
Director of Operations
206 Tours<x-apple-data-detectors://0/0>
333 Marcus Boulevard<x-apple-data-detectors://0/0>
Hauppauge, NY 11788<x-apple-data-detectors://0/0>
Phone: (631) 361-4644<tel:(631)%20361-4644> or (800) 206- 8687<tel:(800)%20206-%208687>
E-mail: sandra@206tours.com<mailto:sandra@206tours.com>
www.206tours.com<http://www.206tours.com/>

On Jun 5, 2015, at 7:08 PM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


I did a test before fixing anything and this is what I got Are you expecting something different or?

[image]<https://cloud.githubusercontent.com/assets/8440255/8016778/2ddf284a-0bb6-11e5-87d9-73c63453d0ac.png>
