### ISSUE TITLE
419217 - promo & clergy discount problems

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#396]
So Leona received the promo code for Memorial day wknd but the $150 is not showing in the payments section?

Also the Clergy discount came through automatically but what is the % it's calculating off of? It's not showing in the payments section so i can't edit the amount but it's wrong. It should be $598.80

**Comment by bradatkins** [comment]
The discount thing should be fixed now.

The DB currently says it's 20% of the Base Price

![image](https://cloud.githubusercontent.com/assets/8440255/9027495/403ff4d2-3925-11e5-8c89-a029fcc2f3ed.png)

**Comment by ali206** [comment]
Ok if it's 20% then it should be $598.80 not:
![image](https://cloud.githubusercontent.com/assets/8440903/9040266/eab7b2d4-39ce-11e5-8d85-a8cb8484d80d.png)

**Comment by bradatkins** [comment]
I think they are working now?

**Comment by bradatkins** [comment]
Closing, hasn't happened since
