### ISSUE TITLE
419217 - cc issue with state autogenerating

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#398]
When trying to charge a cc through the DB, the state should not automatically pop up as the person the invoice is registered under.  I should be able to type that in manually no?

This person lives in Canada but someone living in Nevada is making a payment and i can't charge through the DB b/c the only state options are in Canada

![image](https://cloud.githubusercontent.com/assets/8440903/7863136/723fa594-0528-11e5-9924-dedc8f9fd1a4.png)

**Comment by bradatkins** [comment]
Fixed.
