### ISSUE TITLE
is email address correct? 419276

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#400]
not sure if this is how it normally looks for group leaders so just dbl cking
![image](https://cloud.githubusercontent.com/assets/8440903/7886887/1d7517f0-05fb-11e5-9504-1ac0b3bd26d3.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7886895/33a0c3e4-05fb-11e5-92d0-0098c87d6b2e.png)

**Comment by bradatkins** [comment]
Someone put incorrect information on the departure for MM102015:

[image: Inline image 1]

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/7894186/f4990164-0633-11e5-92a0-2fb808c6ee1c.png)
