### ISSUE TITLE
ARC - schlachter

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#401]
when you look in ARC Tickets and DB her refunded ticket is the only one showing:

![image](https://cloud.githubusercontent.com/assets/8440903/7887162/2c5c7c02-05fd-11e5-92e2-48a6e9b32b11.png)

when i go to arc tickets requiring review - there is nothing in there under her last name that needs to be fixed

So where's her original ticket?

A refund should not override an existing ticket.

**Comment by bradatkins** [comment]
Closing, hasn't happened again since
