### ISSUE TITLE
When booking as an agent

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#405]
When making a reservation as an agent it asks us to log in as the agent shouldnt that step be skipped since we are already selecting the agent on the main page of the DB screen

![agent](https://cloud.githubusercontent.com/assets/8440601/7942066/995023fc-0929-11e5-8097-ee0ae4cdae74.jpg)

 
![image](https://cloud.githubusercontent.com/assets/8440601/7942056/7cbb8970-0929-11e5-9eca-fb78c56bc6f2.png)

**Comment by bradatkins** [comment]
That's functioning as designed. What this does is creates an order and attaches it to an agent.

This is because an "Agent" isn't necessarily a "Traveler"...
