### ISSUE TITLE
3 diff. accounts mixed in to 1 order

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#406]
From Yaritza:

While putting this reservation through, I took a call and to assist another client on the phone, I opened a new tab to access that client’s invoice. I then hung up and resumed with the reservation below. I went to confirm the order I was putting through, and it didn’t allow me and it highlighted the address on top of the reservation which was the account information of the client I spoke to on the phone that had nothing to you with the order I was trying to process. The systems asked me if I wanted to use that highlighted address and I clicked on “no” and the system then retrieved the address of the person I was trying to register that I entered in the beginning. I then got to the payment page, and on the bottom, I went to check off the terms and it had another person’s name next to them. There were a total of 3 different accounts mixed in this order I was trying to process. 
![yari](https://cloud.githubusercontent.com/assets/8440903/7965034/e173e5f0-09e8-11e5-9fde-286a5537a053.jpg)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
