### ISSUE TITLE
Recaps not generating properly 	100158 July 5

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#407]
Hi Brad,

Recaps are generating strange with blank names and Your trip includes is only the first few lines

![image](https://cloud.githubusercontent.com/assets/8440601/7966189/6497be46-09f0-11e5-838f-c1192d32ed6f.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/8013462/668dd624-0b97-11e5-92c4-aee8decd9818.png)

![image](https://cloud.githubusercontent.com/assets/8440255/8013465/69bb8cc4-0b97-11e5-9a40-02a484f9fd37.png)

**Comment by Sandra206** [comment]
Great this is now working properly
