### ISSUE TITLE
"Rebooking" email pdf's won't open

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#408]
![image](https://cloud.githubusercontent.com/assets/8440903/7967448/27ecc5ce-09f8-11e5-9b0a-b3aaa831c1ff.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7967454/2faa8daa-09f8-11e5-8ab5-9a563d68bce5.png)

And i just restarted my comp.

**Comment by ali206** [comment]
same with final payment reminder emails

**Comment by bradatkins** [comment]
Is it just you? Or everyone?

**Comment by ali206** [comment]
Apparently i'm the only one getting final payment reminders and rebooking notices so i guess it's just me? I have no one to compare to

**Comment by bradatkins** [comment]
Can you forward the email to someone?

**Comment by bradatkins** [comment]
Fixed.
