### ISSUE TITLE
acct manager emails not working 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#410]
From: Amanda Fortunato 
Sent: Tuesday, June 02, 2015 1:00 PM
To: Sandra Lippold
Subject: Database Error | Tour FCO041116

Hi Sandra, 

I just registered a passenger for this tour and didn’t receive the confirmation email. 

I checked in the database under “tours” and in the account manager section it states “12” although when I click on edit the tour my name is selected. Please see below:
![amanda](https://cloud.githubusercontent.com/assets/8440903/7969943/7b78329a-0a08-11e5-878c-13c990bb2496.png)
![amanda 2](https://cloud.githubusercontent.com/assets/8440903/7969944/7e8c8b02-0a08-11e5-81ae-a800533885d6.png)

**Comment by bradatkins** [comment]
That's because she placed the order and the emails are held back when Staff place the order.

Once they release it, it does not make sense for the DB to send them the email as well. If the client themselves place the order on her tour she will get an email.
