### ISSUE TITLE
FW: email to Brad | no confirmation page, but multiple orders created

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#411]
email from yaritza just fwded to you 6/3/15 at 4:14pm

**Comment by bradatkins** [comment]
OK, not sure what happened here, but it look like Yaritza created the orders at the following time:

416266 11:47
416267 12:04
416268 12:05
416269 12:08

If there was some odd problem with the DB, I would have expected those times to be all within seconds of each other...so I'm not sure...

**Comment by bradatkins** [comment]
Let's just keep an eye out to see if something similar happens again

**Comment by ali206** [comment]
Her email that i sent you was only in regards to 1 registration though, why would it matter what time she registered other people?
