### ISSUE TITLE
DB showing wrong base price 419332

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#412]
base price is set up as $2099 and from CHI there is no additional add on airfare so why is base price showing as $2349 on invoice?

![image](https://cloud.githubusercontent.com/assets/8440903/7986789/afc00bfa-0aa7-11e5-86ec-3347768c530f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7986796/b9bdb6de-0aa7-11e5-8089-139b7d3b2936.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7986809/cee24b06-0aa7-11e5-8bf9-705c9d900257.png)

**Comment by bradatkins** [comment]
This is probably why:  
![image](https://cloud.githubusercontent.com/assets/8440255/8013254/e4cac7d8-0b95-11e5-84fa-c5ca0864f2a7.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/8013259/eed92fc6-0b95-11e5-86a0-b996ae75fbf3.png)

**Comment by ali206** [comment]
But that's not an actual add on cost that exists on the booking??

![image](https://cloud.githubusercontent.com/assets/8440903/8062249/bfa30e16-0e9c-11e5-8728-31c27fbe976e.png)

**Comment by bradatkins** [comment]
But that's the addon cost associated with the city...there is no addon cost with the order
