### ISSUE TITLE
approving commission not working 418796

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#413]
i approved this commission earlier today and stef just emailed me saying it's not deducting.  I checked the payment status and now it's pending??

![image](https://cloud.githubusercontent.com/assets/8440903/7992458/8b7dd0e4-0acd-11e5-802b-12f5051fb18f.png)

**Comment by bradatkins** [comment]
Fixed bug.

![image](https://cloud.githubusercontent.com/assets/8440255/7995805/9470ee2e-0ae7-11e5-9db0-1e9c18236f5a.png)

**Comment by ali206** [comment]
Ok thanks. 

Is there something wrong with the way Jimmy is set up as an agent?

The approved commission is not deducting in the payments section when you open the invoice so it looks like he still owes us money and he doesn't.

**Comment by bradatkins** [comment]
This was a bug, it's fixed now.

**Comment by ali206** [comment]
ok but as per above message, approved commission isn't posting as a payment still for this order:
![image](https://cloud.githubusercontent.com/assets/8440903/8012715/87c468ea-0b91-11e5-83a7-ae176f8b8f43.png)

**Comment by bradatkins** [comment]
I thought for GROSS it's not supposed to deduct from the order total...

![image](https://cloud.githubusercontent.com/assets/8440255/8012851/6a57415a-0b92-11e5-876c-c38bd0d20401.png)

**Comment by ali206** [comment]
If it doesn't deduct as a payment made then all invoices will show incorrectly with a balance due?

I need it to deduct as a payment

We decided that for GROSS, it would only show on the invoice when i apply manually so i guess i just have to decline the pending comission and enter it manually always for invoices that are gross that i need it to deduct?

**Comment by bradatkins** [comment]
OK so it still need to deduct as a payment. I'll change that.

**Comment by bradatkins** [comment]
Done 
![image](https://cloud.githubusercontent.com/assets/8440255/8013246/d33979ba-0b95-11e5-968e-f9a91c6d548f.png)

**Comment by ali206** [comment]
It needs to deduct as a payment but i remembered that i can apply the commission manually and that's when it will show on the invoice correctly and deduct.  Please undo what you did 4 days ago to have the commission amount deduct without showing it in the payment section.

**Comment by bradatkins** [comment]
Undone, please validate.
