### ISSUE TITLE
418796 order audit wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#414]
anything that my name is next to (other than PIF status) for today i never touched...

And it's not showing that i approved commission ever

![image](https://cloud.githubusercontent.com/assets/8440903/7992487/bc7b3006-0acd-11e5-9319-650c2069fd43.png)

**Comment by bradatkins** [comment]
There was some extra logging in place that would log things even if they didn't change. I've fixed that

![image](https://cloud.githubusercontent.com/assets/8440255/8012550/7673d900-0b90-11e5-8037-9f554f96483b.png)
