### ISSUE TITLE
419247 & 419118

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#415]
I applied payments and then sent emails out from View Orders and the pdf's came through without the payment??!!

![image](https://cloud.githubusercontent.com/assets/8440903/7993867/2a6c18b0-0ad7-11e5-90b5-2e1a7ae7f304.png)

**Comment by ali206** [comment]
Just so you know this is happening to a lot of emails going through to clients - payment confirmations as well.

**Comment by bradatkins** [comment]
What is the time on the email? in the first post?

**Comment by ali206** [comment]
4:17pm - 419247
