### ISSUE TITLE
initial email after applying a payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#416]
another example of the payment not showing on the invoice:

![image](https://cloud.githubusercontent.com/assets/8440903/7993898/6cd9c6d4-0ad7-11e5-8464-dac0728a25e4.png)

**Comment by bradatkins** [comment]
I can't see the time on this email, but the initial order was placed at 11:26, but the CHECK was approved at 15:58.

What time is on the email?

**Comment by ali206** [comment]
4:33pm on 6/4

**Comment by bradatkins** [comment]
Hmm. I wasn't able to reproduce it?

![image](https://cloud.githubusercontent.com/assets/8440255/8144846/d0c86f5a-11bd-11e5-8bf4-cc851f8ae3cf.png)
