### ISSUE TITLE
Paypal not an option when applying payments

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#420]
can you add paypal as an option when applying payments?

[image](https://cloud.githubusercontent.com/assets/8440903/8116127/41decaa2-104e-11e5-839f-cf6548579a2e.png)

**Comment by bradatkins** [comment]
Hmmm. I don't think this will really work, because the PAX will have to give you their Paypal Username and password??

**Comment by ali206** [comment]
No i mean on the admin side.

Paypal payments don't post to clients invoices so i have to apply them manually.  If i go to the coin button option of applying payments, paypal is not listed.

![image](https://cloud.githubusercontent.com/assets/8440903/9041065/feb0cb04-39d3-11e5-9fa8-68288084d373.png)

**Comment by bradatkins** [comment]
This was a bug, so I think we can close this. You shouldn't need to manually post paypal payments
