### ISSUE TITLE
419451 - revised order email has wrong tour info

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#423]
i think you're aware of this but in case you're not...

Revised orders are coming through with wrong tour information:

![image](https://cloud.githubusercontent.com/assets/8440903/8138294/8026beae-1117-11e5-9c1f-111e22ef3226.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/8142529/375fbaaa-114d-11e5-9a72-325e06f15ccd.png)
