### ISSUE TITLE
emails not going through from the DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#424]
Might already have this recorded but i couldn't find it...

Emails not showing up in my email that were sent from the DB and are not showing that I emailed an invoice out in the order audit report

Examples: 419441, 419442

**Comment by bradatkins** [comment]
There was a bug that was incorrectly reporting orders as placed by the customer, when in fact they were placed by 206 Tours Staff.

And since they were placed by staff, the order email hasn't been sent out yet

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/8174047/68ebbd4e-13a5-11e5-9ec1-e4d3bd688bc7.png)
