### ISSUE TITLE
order audit wrong 419483

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#425]
Piernha registered this client, not themselves

![piernha](https://cloud.githubusercontent.com/assets/8440903/8183583/137affa2-1407-11e5-8567-45a153056e68.png)

**Comment by bradatkins** [comment]
Fixed this last night as part of a different bug:

![image](https://cloud.githubusercontent.com/assets/8440255/8183748/25c04f54-1408-11e5-9599-d17beb7a68d0.png)
