### ISSUE TITLE
Current Order audit issue 418288

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#426]
This woman received a payment reminder email (final payment maybe?) but it is not showing in the order audit report.  Should anything being sent to the client be in order audit report, even if auto generated by the DB?

![image](https://cloud.githubusercontent.com/assets/8440903/8184844/af60146e-140e-11e5-98b2-64af184df815.png)

**Comment by bradatkins** [comment]
It is auto generated, but I don't think I hooked up those up to the order
audit report. I can do that though.

**Comment by bradatkins** [comment]
From now on it'll post the Balance Due email notification in the audit
