### ISSUE TITLE
Clergy Discounts 419461

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#427]
don't seem to be calculating correctly

Ex:
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=419461&GENERATED=TRUE&SHOW_COMMISSION=Y

Clergy is usually 20% of base price + SS so for invoice above clergy should auto calculate as 1098.80

**Comment by bradatkins** [comment]
Fixed, it wasn't taking into account the airfare portion (295)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/8197605/30e4fa64-1468-11e5-8f55-7d8f5a3b0b82.png)
