### ISSUE TITLE
Emailing from payment confirmation page not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#428]
Applied a payment and from below screen clicked on email icon and it brings me to 2nd pic??

![image](https://cloud.githubusercontent.com/assets/8440903/8215890/23eb4964-1501-11e5-83f2-704b98946fce.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8215905/32d35912-1501-11e5-9a24-27342b4ab5bf.png)

**Comment by bradatkins** [comment]
I may have been working on it, try again

[image: Inline image 1]
