### ISSUE TITLE
Email wasn't received after i sent it 417546 & 417548

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#429]
I sent email from view orders screen and i never received a copy of it and it's not in order audit report:

![image](https://cloud.githubusercontent.com/assets/8440903/8216042/1961aed8-1502-11e5-8a44-4464e8a466f1.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8216048/23c23d48-1502-11e5-8622-9a2089d2b1a9.png)

**Comment by bradatkins** [comment]
Try now
