### ISSUE TITLE
416718 - rtn city not showing correctly on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#431]
Updating this order to reflect client’s changes, was very time consuming because:

1; hitting the save button after choosing the correct departure and return city would take me to a blank page without making the change
2; the option (field) to select a return airport was not available at times
3; Ramon is returning to Laredo and Ryan is returning to Philadelphia. Why aren’t those airports showing on their order?

ALL are departing from SAT San Antonio
RAMON is returing to Laredo
RYAN is returning to Philadelphia

![image](https://cloud.githubusercontent.com/assets/8440903/8240732/bff7cc8e-15d2-11e5-8c42-c1b4fa24fc2a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8240702/9e23bdf2-15d2-11e5-9a73-c8c9b9a77cfe.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8240710/a5954e34-15d2-11e5-852d-486d6e2a6910.png)

**Comment by bradatkins** [comment]
Fixed. I've made it so Departure City and Return City always show up.

![image](https://cloud.githubusercontent.com/assets/8440255/9029112/6463cd76-395b-11e5-94f6-30db96d08c4a.png)
