### ISSUE TITLE
Selecting "No, go back" after applying a payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#432]
After clicking on submit button, we get brought to the 2nd confirmation page:

![image](https://cloud.githubusercontent.com/assets/8440903/8241141/94ba80f4-15d5-11e5-80a8-9c0378394e05.png)

(Below pic) Not sure why there's a d in the left corner? but also, when we select, "no, go back" the DB should bring us back to the page above where we were entering info to make a payment. 

![image](https://cloud.githubusercontent.com/assets/8440903/8241167/ba2f86fe-15d5-11e5-9e2b-33f791b4d914.png)

Currently it brings us to this page which is not helpful:

![image](https://cloud.githubusercontent.com/assets/8440903/8241172/c15db0ae-15d5-11e5-9fa8-ed81dfba6c33.png)

**Comment by bradatkins** [comment]
Fixed
