### ISSUE TITLE
DB Glitch

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#433]
www.pilgrimages.com/frericayers
DB code: EA042616

Hi Brad,

One of our workers built this tour and she put Richmond as the dept city, but it is coming up as Boston on the website.

![image](https://cloud.githubusercontent.com/assets/10079829/8254233/b1e59a62-1664-11e5-9e00-cb0fe6fe60ae.png)

It is also not showing up in the tour dept section of the DB when I search for it:

![image](https://cloud.githubusercontent.com/assets/10079829/8254237/c1185e84-1664-11e5-91f3-7abe4e1bd047.png)

**Comment by bradatkins** [comment]
Seems to be OK now

![image](https://cloud.githubusercontent.com/assets/8440255/9778250/f831d0fe-573b-11e5-88ff-774f7642218c.png)
