### ISSUE TITLE
URGENT: 3.5% cc fee was active on Tr#1?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#434]
Hi Brad, 

Do you know who added the 3.5% cc fee to this tour?  We just had a client make a payment and noticed there were incorrect cc fees.

All series tours should NOT have 3.5% cc fee EVER. 

Is there an easy/quick way for you to double check all series tours to make sure they are not set to have cc fees?  Otherwise we can only go 1 by 1 which is extremely time consuming.

**Comment by bradatkins** [comment]
I will check

**Comment by bradatkins** [comment]
The following Active Series Tours have CC Fees.

Would you like me to set the fee to Zero?

"37JB"
"111-gaw"
"CJBellon"
"DT102912"
"FC040813"
"FITKRUK"
"FITKRUK"
"FM041612"
"FW042913"
"HZ090315"
"JD040213"
"JH012113"
"JP062813"
"MC051413"
"MMFIT"
"MT122213"
"num"
"PS062913"
"PT103011"
"RH092412"
"VS100912"

**Comment by ali206** [comment]
Those all seem to be old tours no? If so then you can leave them.
