### ISSUE TITLE
417381 - email came today i'm assuming for a charge done 2 days ago?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#435]
just received a new payment email for this booking but nothing has been done to this booking since 2 days ago according to the order audit and there is no charge for today either??

![image](https://cloud.githubusercontent.com/assets/8440903/8333632/e8f64e4c-1a61-11e5-9f3d-4b5f1fd5ed43.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8333650/f87ddc4a-1a61-11e5-9f2d-7c057f6a45d6.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8333639/ede2a4a0-1a61-11e5-8f6f-7ec7f0ad133c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8333666/048669da-1a62-11e5-98e3-3cd49a48daef.png)

**Comment by ali206** [comment]
What am i supposed to be reviewing?

**Comment by bradatkins** [comment]
Closing, hasn't happened since
