### ISSUE TITLE
emails coming a day later?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#436]
seems a bunch of these emails were from things done yesterday that i'm just getting now?
![image](https://cloud.githubusercontent.com/assets/8440903/8333693/38093d00-1a62-11e5-9b5f-10dd0ddad8fc.png)

**Comment by bradatkins** [comment]
My guess is it's related to a back log of spam that Sandy was talking about.

If the Order audit indicates the email was sent yesterday and you received
it today, it's the mail server, not the DB
