### ISSUE TITLE
419572 - not letting us update, pricing is all wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#438]
when you go in to the booking to try and update the DB just brings us to a blank screen?

![image](https://cloud.githubusercontent.com/assets/8440903/8386900/10502fc8-1c22-11e5-888d-3f08c5d200c9.png)

**Comment by bradatkins** [comment]
This order has been cancelled, but I'm guessing it's working now. My guess is you caught me when I was updating the code
