### ISSUE TITLE
Changes to Payment Conf. & Invoice Email being sent out

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#44]
![image](https://cloud.githubusercontent.com/assets/8440903/4121170/db75e340-32b8-11e4-8004-9f3b9045fbf6.png)

![image](https://cloud.githubusercontent.com/assets/8440903/4121174/e57e7b86-32b8-11e4-8d19-7a3647f8aba0.png)

![image](https://cloud.githubusercontent.com/assets/8440903/4121182/f5a1f394-32b8-11e4-9cfb-0cc15ad98637.png)

**Comment by bradatkins** [comment]
I think this has been taken care of based on our recent email work.
