### ISSUE TITLE
URGENT: 419669 - discount applied before confirming invoice, not showing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#440]
Hi Brad, 

Melissa just registered this lady, applied a $150 discount before confirming the booking and it showed it was deducting correctly when she went to make a payment. 

After confirming the booking, she had to go in and update something, which seems to have knocked the discount out as it's now showing as $0.00.

I cannot adjust this because the discount does not show in View Payments?? (It should)

Can you please fix the discount to show as $150 again? And then correct the disappearing issue and have them show in payments?

![image](https://cloud.githubusercontent.com/assets/8440903/8432130/244db36e-1f0c-11e5-9eed-ba6e6746fd03.png)

**Comment by bradatkins** [comment]
The promotion value is 0 (Zero) so the DB is applying that value.

![image](https://cloud.githubusercontent.com/assets/8440255/9026212/1fd12642-38f5-11e5-97a4-4d78e266cbde.png)

**Comment by ali206** [comment]
Then how did it show up correctly on the invoice before she updated the booking as $150?

**Comment by bradatkins** [comment]
My mistake. All fixed
