### ISSUE TITLE
419736 - discount applied before confirming 2nd example

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#443]
stef had to update booking after applying discount and DB kicked it out but left it showing as $0.00 on invoice. 

Please remove the 2 $0.00 discounts.

![image](https://cloud.githubusercontent.com/assets/8440903/8503261/e08639f4-218a-11e5-8796-744e08d83a22.png)

**Comment by bradatkins** [comment]
Fixed. The DB was losing the value
