### ISSUE TITLE
Promo Code Tracking

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#444]
This may have already been added but we will need a way to track promo codes being used or someway be able to come up with a report. It can be something as simple as listing the promo code and amount of people who signed up with that code. Then when you click on the number the invoices show up kind of like when you look at a tour under registered passengers.

**Comment by bradatkins** [comment]
This already somewhat exists:

https://www.206tours.com/register/admin/reports_promo.php

**Comment by Sandra206** [comment]
That’s what I thought. We should Definitely close it out then.
