### ISSUE TITLE
Name associated with CC not showing correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#445]
Hi Brad, 

If a client with a name other than what the order is registered under is making a payment, the payment should show up on that invoice with the new name, not the name of the person that created the booking. 

We've had a bunch of clients calling in asking us to change the name, which i can do.  But it looks bad on our end that the system doesn't show the correct name after they've made a payment. 

Can this be fixed? I know i've asked for this to be fixed in the past but i couldn't find the issue in Github.

**Comment by bradatkins** [comment]
I'm fairly certain I fixed this, can you check and provide me an example of where the payment name on the Invoice is different then the Payee name in the Payments section?

**Comment by ali206** [comment]
When did you fix this? It just happened on Friday:

![image](https://cloud.githubusercontent.com/assets/8440903/9041253/200c6a14-39d5-11e5-9062-b2e155da0c83.png)

Should have shown up like this:

![image](https://cloud.githubusercontent.com/assets/8440903/9041259/2bb97d48-39d5-11e5-9dce-ce87290fdfae.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
