### ISSUE TITLE
FEDEX error

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#448]
Database Fedex Error – Unable to send things to Fr. Jim McNamara

419781
Jul 7, 2015	McNamara / James
fjm100316
Oct 3, 2016   
$2,390.00	$2,390.00

 

________________________________________
 	Chris Wright 
Travel Consultant
206Tours.com

Tel: 800.206.8687   |   631.361.4644  ext. 116   |   Fax: 631.361.3682
 206 Tours Inc., 333 Marcus Blvd, Hauppauge, NY 11788
 chris@206Tours.com   |   Skype: chris-206tours

         client letters

**Comment by bradatkins** [comment]
Can you provide some more information? What's the error? Screen shot?

**Comment by Sandra206** [comment]
Please find attached


________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>

**Comment by bradatkins** [comment]
Hey -

I didn't come through, can you email it to me?

Thanks,
Brad

**Comment by bradatkins** [comment]
Fixed
