### ISSUE TITLE
2016 dates not showing for #187 417870

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#449]
they exist in all depts. though??

![image](https://cloud.githubusercontent.com/assets/8440903/8574835/bcbd32fe-2566-11e5-92ce-fc7694e739ae.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8574851/d492c7ae-2566-11e5-9fe6-d93e6469015c.png)

**Comment by ali206** [comment]
Any way you could fix this today? This client is still waiting on a corrected invoice and we're unable to do that for her until this is resolved.

**Comment by bradatkins** [comment]
I'm guessing this order has been moved, but it's fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9028970/4fb6fc7a-3958-11e5-87bd-6b950025ba5e.png)

**Comment by ali206** [comment]
Yes couldn't wait any longer, thanks.
