### ISSUE TITLE
Updated emails being sent out not consistent

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#45]
Amanda said they sometimes come through normally as per this picture:

![image](https://cloud.githubusercontent.com/assets/8440903/4135986/f4664a3a-337a-11e4-8e95-3e8074f51d66.png)

But sometimes when she updates an invoice and sends out an email they will come through as this:

![image](https://cloud.githubusercontent.com/assets/8440903/4135976/dc599bd6-337a-11e4-9cea-cd5493c1da66.png)

**Comment by bradatkins** [comment]
My guess is this issue can be closed based on the work we've just completed.
