### ISSUE TITLE
Final Payment Reminders shouldn't go out to pple overpaid

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#450]
![image](https://cloud.githubusercontent.com/assets/8440903/8580989/cb9bcd60-258b-11e5-95a8-4ee14122e2c9.png)

**Comment by ali206** [comment]
Or to pple PIF - this is happening to a lot of clients now that are already PIF.

They keep emailing us saying they've already PIF so why are they getting an email

**Comment by bradatkins** [comment]
Another Order #? When you say PIF do you mean the status or the outstanding
balance?

**Comment by ali206** [comment]
yeah 417915, 419213, 418000

All have outstanding balances of $0.00

**Comment by bradatkins** [comment]
I'm going to add myself to the emails to see what's going on. At a first
glance I can't see what's up...

**Comment by bradatkins** [comment]
Likely relating to the server move, let's keep monitoring it.
