### ISSUE TITLE
419452 - final pmnt reminder sent to PIF person and not in order audit

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#451]
The DB isn't recording in order audit report correctly and shouldn't be emailing PIF pple finaly payment reminder emails:

![image](https://cloud.githubusercontent.com/assets/8440903/8596562/1d17bfd6-261e-11e5-9d35-04d0034423dc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8596518/e53bae56-261d-11e5-8384-58ae212ee42c.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8596507/d58e8866-261d-11e5-953e-3ef032fe1a85.png)

**Comment by bradatkins** [comment]
This is likely related to the server switch, but let's keep monitoring it.
