### ISSUE TITLE
419754 - order audit wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#452]
"Customer" should be Natasa, customer didn't register themselves:

![image](https://cloud.githubusercontent.com/assets/8440903/8620545/30eba326-26ee-11e5-985c-20965d1fe7bd.png)

**Comment by bradatkins** [comment]
Odd, I'm not noticing anything in the logs that suggests she went through the admin to place this order?

**Comment by ali206** [comment]
how else could she have done it then? If the client traveled in the past and she logged in as them to register?

**Comment by bradatkins** [comment]
Do you know if she placed the order from the admin? Or she may have originally had the username and password?

**Comment by ali206** [comment]
not sure, she just said she did it online

**Comment by bradatkins** [comment]
She likely didn't do it from the admin.
