### ISSUE TITLE
CC charges on new registrations

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#46]
Just trying to think of the best option in terms of this issue...

For a booking without any payments yet, we used to be able to select "Other Amount" and charge whatever amount.   

Now on a booking w/o any payments, we can still select "Other Amount" and enter in the amount we intend to charge but the DB will not charge the amount specified.  Ex: Katherine just tried to only pay $156 as the first payment on a new booking and the DB charged $556 instead b/c of the $400 deposit that wasn't paid yet. 

If we leave it up to the DB to charge the correct deposit amount, then is there a way to remove "Other Amount" as an option for bookings that have not made any payments yet or something along those lines?

Leaving the Other Amount as an option will mean more charges for me to Void because people may not remember this or may make mistakes, and removing it as an option for initial deposit payments will mean more charges that I may have to manually process.  

I can't think of the best solution - kind of just talking out loud on this one.

**Comment by bradatkins** [comment]
Hmm, I understand what you are saying.

What's confused me is how can an order get through without a payment that's the minimum?

**Comment by ali206** [comment]
Well currently it can't because i guess we made the $400 deposit mandatory.  However, it's not actually mandatory in all situations.  I guess i'll just have to keep voiding incorrect payment amounts

**Comment by bradatkins** [comment]
Is there a defined list of scenarios where the 400 deposit isn't mandatory?

**Comment by ali206** [comment]
Did you close this issue?  I don’t see it in the list

There’s not a specific list of scenarios for this either though. If people ask us if they can only pay $200, I’m assuming we don’t usually say no to that.

It’s a case by case situation though.




[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ali Byrne
Accounting Manager
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687   |   631.361.4644  ext. 127   |   Fax: 631.361.3682
206 Tours Inc., 333 Marcus Blvd, Hauppauge, NY 11788
ali@206Tours.com<mailto:ali@206tours.com>   |   Skype: ali-206tours

[http://www.206tours.com/sigs/ronen/occ-main/occ-icon.png]<http://www.onlinechatcenters.com/chat/29129-66811?SESSID=buveaotoa7iaip6mrtnbm6fvd6&ref=http%3A%2F%2Fwww.206tours.com>  [http://www.206tours.com/sigs/facebook.png] <https://www.facebook.com/206tours>   [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>
