### ISSUE TITLE
Promotional #'s for promo codes

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#463]
Hey Ali,

With September looming around the corner, and more people looking on Catholic websites with the Holy Father visit, what are the status of bookings that have come from the following  Online Promo’s:

-	Code: NCR (Reporter):
-	Code: EWTN (Registry):
-	Code: CNY (New York):

I am not sure if you can find out, or Brad.

**Comment by bradatkins** [comment]
NCR: 0
EWTN: 1 (419810)
CNY: 0
