### ISSUE TITLE
418700 - switching from LO to A/L issues

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#464]
Just switched from Land Only to Air & Land and no dept. city box pops up, just stays as rtn city?

![image](https://cloud.githubusercontent.com/assets/8440903/8702988/ffdd0500-2ae8-11e5-9910-f7c7556b3749.png)

Also, once updated to A/L - pricing won't update but tour is set up correctly:

![image](https://cloud.githubusercontent.com/assets/8440903/8703005/133f2416-2ae9-11e5-8afe-f2a435065bc8.png)

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/8703039/34db48ca-2ae9-11e5-97c8-91927a981445.png)

**Comment by bradatkins** [comment]
Fixed
