### ISSUE TITLE
URGENT: 419538 - clergy discount randomly appeared on invoice?!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#465]
There should be no clergy discount, they PIF on 6/19 and no one had a special title. 

Can you please remove it?

At some point clergy discount added itself and I can't remove it b/c they don't show in All payments for me to edit (they should). 

![image](https://cloud.githubusercontent.com/assets/8440903/8703319/6002998a-2aea-11e5-9927-0bac7888f0b4.png)

**Comment by bradatkins** [comment]
I removed it. Just FYI, these show up as "Coupons" so you can remove it from here:

![image](https://cloud.githubusercontent.com/assets/8440255/8713755/a6573bb6-2b3a-11e5-8e95-2825c94b6b65.png)

**Comment by ali206** [comment]
Shouldn't they show in all payments so I can edit them? Sometimes the amount is wrong or milanka is giving a special amount towards a clergy discount

**Comment by bradatkins** [comment]
It wasn't coded that way originally, but can be changed.

Please log a seperate issue and we can put it as an ehancement for the next
phase
