### ISSUE TITLE
FP051416  DB code not being saved into the Tour Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#466]
Hi Brad,

We are trying to enter this Tour Code into the DB, but it is not saving it.

FP051416 

http://www.pilgrimages.com/stjamescc

**Comment by bradatkins** [comment]
Give it a try now

**Comment by ronenreinheimer** [comment]
Thank you Brad!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
