### ISSUE TITLE
Cannot add new tour information - won't save

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#467]
Although we can now add new tour numbers to this section of the database, if you either;

1.	Put any additional data in addition to the tour code into the new tour creation, the entire thing will fail to save
2.	Save the new tour code and then go back in to add data, none of that data will save.

 
![chris](https://cloud.githubusercontent.com/assets/8440903/8725786/3d703ffc-2ba4-11e5-9822-0157bc8ddcac.jpg)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9026337/07ceb820-38fa-11e5-8334-6a05aebad848.png)
