### ISSUE TITLE
419619 - ppal issue 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#468]
![image](https://cloud.githubusercontent.com/assets/8440903/8726285/3d5d2324-2ba7-11e5-959c-15e536b8c432.png)

**Comment by bradatkins** [comment]
Seems to work OK? I tried it from my account and her account

![image](https://cloud.githubusercontent.com/assets/8440255/9026627/072c1bc4-3904-11e5-988a-641714c49d26.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9026628/0d1e9660-3904-11e5-96e2-500a8ce8905b.png)
