### ISSUE TITLE
HELP! 419961 - Pre stay option not updating pricing correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#470]
![image](https://cloud.githubusercontent.com/assets/8440903/8756518/d85510fe-2ca0-11e5-8213-835d597e499e.png)

**Comment by bradatkins** [comment]
Fixed by a previous bug fix. Phewf :)

![image](https://cloud.githubusercontent.com/assets/8440255/9024126/2afea130-388b-11e5-9d29-d867b7deec76.png)
