### ISSUE TITLE
Emailing out invoices pop up boxes

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#471]
Why does it say OK here after clicking on email icon?

![image](https://cloud.githubusercontent.com/assets/8440903/8802099/1cc0afc0-2f8d-11e5-87fb-603b86d212b5.png)

and here?

![image](https://cloud.githubusercontent.com/assets/8440903/8802102/2643124a-2f8d-11e5-8362-374be97cbea7.png)

**Comment by bradatkins** [comment]
Fixed
