### ISSUE TITLE
email icon on websites

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#472]
This is how the email comes out when clicking on :

 
![image](https://cloud.githubusercontent.com/assets/8440601/8804834/185d70bc-2f9c-11e5-8d9c-c4b5fde6fafa.png)
From: rinda@addthis.com [mailto:rinda@addthis.com] On Behalf Of rinda@206tours.com
Sent: Tuesday, July 21, 2015 9:49 AM
To: Rinda Kanidinc
Subject: Medjugorje Pilgrimage with 206 Tours Catholic Pilgrimages Our all inclusive trip includes a Catholic Priest as spiritual director, Mass daily, Superior accommodations, Sightseeing, Flights, and more   
I think a message from 206 Tours would be nice to add to pilgrim rather then below 
Test 
http://www.206tours.com/tour1/#.Va5NwVIjDhM.email
--- This message was sent by rinda@206tours.com via http://addthis.com. Please note that AddThis does not verify email addresses.
Make sharing easier with the AddThis Toolbar: http://www.addthis.com/go/toolbar-em
To stop receiving any emails from AddThis, please visit: http://www.addthis.com/privacy/email-opt-out?e=vxq4TKRBq2X4FfxRpVC4VuRGpUg
 Additionally: 

From : shouldn’t this be set as default to be always From :  sales206tours.com

Subject: Needs to be simplified:  Tour # 1: Medjugorje 
![image](https://cloud.githubusercontent.com/assets/8440601/8804862/2f7e3e20-2f9c-11e5-8db8-708f85a382fe.png)

Not sure why this is here and what reasoning is behind this 

FYI :   I had hard time reading the moving letters . 
![image](https://cloud.githubusercontent.com/assets/8440601/8804952/a1508058-2f9c-11e5-8158-75031ec323c1.png)

**Comment by bradatkins** [comment]
This is functionality provided by Ronen, not me. Check with him, if he needs help let me know :)
