### ISSUE TITLE
New merchant acct information 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#473]
From: Ali Boulanger

> Sent: Wednesday, July 15, 2015 9:50 AM
> To: 'brad@youreshop.com'; Milanka Lachman; Sandra Lippold
> Subject: New Merchant Acct is approved!
> 
> Hi Brad,
> 
> Here's the info you'll need for the webpage:
> 
> Acct ID = 534818
> Pin # (64 digits): G0KWEOV5V2QE01C2NOIM6XA7ZLZDE1HHS6W5I6A6ITX9TGXCISX41MKGMKATPCMN
> User = 206tourwebpage

**Comment by bradatkins** [comment]
I'm guessing we did this a while ago
