### ISSUE TITLE
417764 - commission deducting and shouldn't be

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#478]
Commission is applied as Gross but in view orders is deducting from order total?

![image](https://cloud.githubusercontent.com/assets/8440903/8934257/cffa8868-3514-11e5-9929-5a40c6a231d6.png)

On invoice is not deducting from order total though which is correct
![image](https://cloud.githubusercontent.com/assets/8440903/8934267/dab3b7e8-3514-11e5-9d47-b3f64335cebf.png)

**Comment by ali206** [comment]
This whole tour is screwed up like above as well: Another ex:

![image](https://cloud.githubusercontent.com/assets/8440903/8939943/51640ad0-3535-11e5-89f0-26aa3d1494d7.png)

**Comment by bradatkins** [comment]
Do you have a recent example of this, or can you provide updated correct numbers so I can validate this is an issue?

**Comment by ali206** [comment]
Well...this might be an old issue but i just applied $714 insurance and selected NO to not be shown on invoice...it doesn't show on recap either:

![image](https://cloud.githubusercontent.com/assets/8440903/13500369/43079cfc-e130-11e5-9a7f-97328d793e76.png)

How do we get it to show on invoice/recap just as *PRO since this is Agent is listed as Gross

**Comment by bradatkins** [comment]
Please log a separate issue for that request and close this one.

**Comment by bradatkins** [comment]
Outstanding balance on orders screen is correct now for GROSS agent

![image](https://cloud.githubusercontent.com/assets/8440255/13621054/7e77369a-e562-11e5-96dc-7ea54e60abc9.png)

![image](https://cloud.githubusercontent.com/assets/8440255/13621059/83eab034-e562-11e5-9feb-20a10b0d8a1a.png)
