### ISSUE TITLE
418873 - Math not correct

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#479]
I appiled a free trip to John and the DB adjusted to show ins. as $108 correctly but the math is not calculating correctly

![image](https://cloud.githubusercontent.com/assets/8440903/8940002/964a823c-3535-11e5-851f-8559408df93d.png)

**Comment by bradatkins** [comment]
Fixed. There was a bug.

![image](https://cloud.githubusercontent.com/assets/8440255/9024108/18f1f7b8-388a-11e5-84c9-ab76d4b2c1a7.png)
