### ISSUE TITLE
Odd emails from me (but not really) to test@test.com?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#480]
Do you know what this is?
![image](https://cloud.githubusercontent.com/assets/8440903/8960985/a430b8f2-35e0-11e5-8ab5-91aa9ded3401.png)

I didn't send any emails out....

![image](https://cloud.githubusercontent.com/assets/8440903/8961002/b57f8dea-35e0-11e5-88f0-2e6dba6c12f1.png)

**Comment by bradatkins** [comment]
That was probably me testing out the new Elavon account, based on the
timestamp.
