### ISSUE TITLE
417278 recap/ins. issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#483]
Fr. doesn't have insurance (image #1) but when you export the recap (image 2) he does?!

![image](https://cloud.githubusercontent.com/assets/8440903/8984104/5f48e738-369d-11e5-8986-fe2aa4b5f7fa.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8984110/691aeb4e-369d-11e5-9c28-c3686e4acb70.png)

**Comment by bradatkins** [comment]
Fixed.
