### ISSUE TITLE
419961 math wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#486]
client has 2 night pre stay but DB isn't calculating in the 2nd night for Ana:
![image](https://cloud.githubusercontent.com/assets/8440903/8984359/15a37d30-369f-11e5-8ca5-d484a0ad3f8e.png)

![image](https://cloud.githubusercontent.com/assets/8440903/8984364/1ea5d568-369f-11e5-8ded-105c2f94a2a2.png)

**Comment by ali206** [comment]
another ex. 420110 = another booking that had post tour math issues

was overcharging the $49 on 1 pax and then was under charging $149 on the other pax. 

I think piernha just removed the options and added them manually so the client could have a correct invoice.

**Comment by bradatkins** [comment]
Fixed the bug. If there's other ones like this, just update the order and it'll fix it

![image](https://cloud.githubusercontent.com/assets/8440255/9019967/a2cbe802-37c4-11e5-964d-3a654dc88f75.png)
