### ISSUE TITLE
Applying payments by Tour ID 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#487]
Hi Brad, 

Can you create an option to apply bulk payments to tour ID's instead of us having to manually break them down per invoice?

Ex: Tour # DCA110215 has over 250 registered pax, which means over 125 booking #'s.  Every Friday they make a payment of $50,000.00 via CC.  At the moment the only way to enter that in the DB is by my external payment link, 1 by 1 = time consuming.

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/10710852/eeafea88-7a37-11e5-803e-783d01705ca0.png)

![image](https://cloud.githubusercontent.com/assets/8440255/10710853/f1606ff0-7a37-11e5-95c0-8554e92e67c5.png)

![image](https://cloud.githubusercontent.com/assets/8440255/10710854/f47b8116-7a37-11e5-9c07-366540bf00d4.png)

![image](https://cloud.githubusercontent.com/assets/8440255/10710855/f794fabc-7a37-11e5-889f-8b78776b1d01.png)
