### ISSUE TITLE
420110 PT math wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#491]
i updated this and it's not calculating correctly but Annette's info should be as per:

![image](https://cloud.githubusercontent.com/assets/8440903/9039291/6b544238-39c8-11e5-85c4-288e1c32e7e7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9039295/70abca26-39c8-11e5-8e44-08fc9ea1f835.png)

**Comment by bradatkins** [comment]
Fixed the order and the bug

![image](https://cloud.githubusercontent.com/assets/8440255/9051492/6e9eec02-3a29-11e5-885e-a4fd1ae992b8.png)

**Comment by ali206** [comment]
The subtotal should be $4196, it's still adding $49 twice for both pax, sorry...

**Comment by bradatkins** [comment]
Closed as we've done a lot of work on this stuff since 2015
