### ISSUE TITLE
Invoice price wrong - Tried to update not working

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#492]
Hi Brad. 

The land only price should be 899. Her husband booked a different invoice and his is correct but hers is still showing incorrect.

I tried to update in the order but the page is just blank
![image](https://cloud.githubusercontent.com/assets/8440601/9039557/480b812c-39ca-11e5-8869-4a0840e1486e.png)

**Comment by bradatkins** [comment]
Where did you try updating the order where the page was blank?

I did it from this page, and it worked OK:

![image](https://cloud.githubusercontent.com/assets/8440255/9051311/0adb75c0-3a27-11e5-80af-535833b3cf94.png)

**Comment by bradatkins** [comment]
FYI Ali reported the same one and here's my response:

This order was placed back in March. 

Based on my audit records, this departure was priced at $999 for L/O during this order date and was changed to $899 April 17th by Yaritza, so the $999 price is not an error from the DB
