### ISSUE TITLE
Back to admin main on page after applying a payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#494]
Back to admin main not working - bringing me to 206tours.com

![image](https://cloud.githubusercontent.com/assets/8440903/9041724/a99f733c-39d7-11e5-95b6-e53b0e03e7a9.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9041735/be2e2d7a-39d7-11e5-8806-3d7eb38a8ce6.png)

**Comment by bradatkins** [comment]
Fixed
