### ISSUE TITLE
States that show up after selecting country in registration form 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#498]
From Patrick:

Along with my previous email, when I was making the registration… when you select “Country”, and then  “State”, it lists a number of duplicates of a lot of States. Also, the results are not being condensed down by what you select in “Country”? By that, it you select “United States”, places like Niigata-ken should not show up etc.

![patrick](https://cloud.githubusercontent.com/assets/8440903/9061702/79fb90c0-3a8b-11e5-894a-196b14b2f9f2.jpg)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
