### ISSUE TITLE
Billing address vs shipping address in registration form

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#499]
From Patrick:

The client is registering their daughter for WYD, and there are two addresses. The first address (113 Main Street, Bloomingdale NJ 07403) was the billing address for the father, and the other (16 Kenilworth Road, Mineola) was for Shipping. I filled out the info correctly for all boxes, and when I went to go to make “Payment” it notes that everything is wrong with the Billing address. I double checked, and everything was entered in correctly. Thanks!

![patrick](https://cloud.githubusercontent.com/assets/8440903/9061722/a719a54c-3a8b-11e5-9a1a-93e37b7fad17.jpg)

**Comment by bradatkins** [comment]
OK i'm able to reproduce this.

**Comment by bradatkins** [comment]
Fixed
