### ISSUE TITLE
State not showing when trying to charge CC's

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#50]
It's not just for that specific booking - Booking #'s 416614,416607,416624,416612,416623 all don't have the state drop down box when trying to pay by a CC - I guess because they're missing certain pieces of information to their address?

This seems to be a new issue so how can we prevent this moving forward? Does something need to change on the registration form in the DB?

It's extra work to have to go update someone's address just to charge a CC.

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/6653338/63c9c610-ca64-11e4-802f-30b383092810.png)
