### ISSUE TITLE
Client's able to see anyone's invoice if they change order # in web address on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#500]
When I'm logged in as a client looking, and i click on "Invoice" for one of my bookings, i'm able to change the order # to anyone's order # and see all their information on their invoice.

![image](https://cloud.githubusercontent.com/assets/8440903/9063806/5ed1ebe4-3a97-11e5-9140-736f3851c341.png)

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=420066&GENERATED=TRUE&SHOW_COMMISSION=Y

Is there a way to not let that happen or protect against that?

**Comment by bradatkins** [comment]
Done.

**Comment by ali206** [comment]
I was still able to change the order number in the web address

**Comment by bradatkins** [comment]
Whoops. Forgot to save it :)
