### ISSUE TITLE
Change UI

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#502]
Hi Brad,

Please make the following changes to the UI:
www.206tours.com/ronen/ui

thank you!

**Comment by bradatkins** [comment]
Done, except for aligning the weekday's. I can't do that without restructuring a bunch of stuff.

![image](https://cloud.githubusercontent.com/assets/8440255/9127039/33f6abba-3c83-11e5-9734-dc9d3dd2e11a.png)

**Comment by ronenreinheimer** [comment]
hi Brad,

it looks a lot better. can you shift this portion of the UI more to the left?

![image](https://cloud.githubusercontent.com/assets/10079829/9612417/93fa0a68-50b3-11e5-9864-e31be956b0a0.png)
