### ISSUE TITLE
Please dbl ck margins of email text being sent out

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#504]
![image](https://cloud.githubusercontent.com/assets/8440903/9087881/5978ca72-3b5b-11e5-8c54-5275d3fc45a9.png)

**Comment by bradatkins** [comment]
Sorry, not really sure what the issue is?

**Comment by ali206** [comment]
Instead of having one short line and a few long lines and then another short line (ex. below)

**Comment by bradatkins** [comment]
Tell me where you want the line breaks to be and I'll put them in there.

Keep in mind, that depending on your monitor resolution, this will be different.
