### ISSUE TITLE
416921 - order audit invoice brings me to our website

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#505]
In order audit, clicked on invoice sent in 2014 and it brought me to this page (2nd pic):

![image](https://cloud.githubusercontent.com/assets/8440903/9091890/c5e3ba72-3b70-11e5-9fa5-1661d34019bd.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9091895/d09ac014-3b70-11e5-9824-3dc1586177e0.png)

**Comment by bradatkins** [comment]
It only works for orders after May 25th (the day I put this change in) so I've hidden the link for old orders:

![image](https://cloud.githubusercontent.com/assets/8440255/9101202/eafe6c8a-3bb1-11e5-9837-12312eb006b3.png)
