### ISSUE TITLE
418556 - tour 100158 Oct dept

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#506]
tour dept. has LO as $899 and it's listed as $899 on trip website but in DB it shows up as $999?

![image](https://cloud.githubusercontent.com/assets/8440903/9093523/8ee935e2-3b7a-11e5-938b-99dfc4cc06f7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9093526/9631e43e-3b7a-11e5-9ea7-798fc8610d04.png)

I fixed it by saying yes keep orig. pricing - but where is the DB pulling $999 from?

**Comment by bradatkins** [comment]
This order was placed back in March. 

Based on my audit records, this departure was priced at $999 for L/O during this order date and was changed to $899 April 17th by Yaritza, so the $999 price is not an error from the DB
