### ISSUE TITLE
420173 - addt'l options not saving

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#508]
Ali, 

What Katherine meant to say was that she needs to add the option Tel Aviv Double Room Jan 4-5 for each passenger on this booking, but every time she tried to select the option she gets this message. For that reason, she had added an “add cost” until this issue is resolved and we’re able to add options the correct way again.

![yari](https://cloud.githubusercontent.com/assets/8440903/9119223/9149058c-3c43-11e5-9b6f-664373c034e7.jpg)

**Comment by bradatkins** [comment]
Fixed
