### ISSUE TITLE
Mexico dept date on invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#510]
Brad 

“if the user has selected Land Only, the Departure date is the date plus on day.”

That is not correct. Please correct that, and I’m shocked no one noticed this until now 
206 or 207 or contains the word Mexico,

With airfare- the Departure Date is the actual departure date (no plus one)

Land only or Without airfare -   the Date is the actual departure date (no plus one)

As we arrive Mexico on same date that we leave USA /Canada.

**Comment by bradatkins** [comment]
So just to be clear, there is no plus one for any mexico tour or 206/207?
