### ISSUE TITLE
commission - deducting only in view orders and it's not supposed to

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#511]
Hi Brad, 

I thought this was resolved?

For commission's that are pending, when i approve them for GROSS groups, they should show in the PRO* column but not actually deduct.  Invoice shows correctly but it's wrong in View Orders.

I'm trying to get rid of pending commissions once and for all.

Above is not the case on this booking though?

![image](https://cloud.githubusercontent.com/assets/8440903/9144793/6568f9ba-3d1d-11e5-9eea-7622e5b85239.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9144795/6af50716-3d1d-11e5-9e59-a7fbfc6fc026.png)

**Comment by bradatkins** [comment]
Fixed
