### ISSUE TITLE
417541 - dept. city won't update

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#514]
dept. city changed to Raleigh Durham but still showing Rochester on invoice, won't update and pricing is wrong.

![image](https://cloud.githubusercontent.com/assets/8440903/9179035/e341f912-3f67-11e5-87cc-32adff4e5026.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9179049/f6f282ba-3f67-11e5-8ebb-1320e4c2d5a5.png)

**Comment by bradatkins** [comment]
Fixed
