### ISSUE TITLE
420119 - ins. wouldn't show on invoicve

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#515]
Melissa already added it manually but it was selected as Yes in the booking but wouldn't show up on the invoice?

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=420119&TravelerID=27394&GENERATED=TRUE&SHOW_COMMISSION=Y

![patrick](https://cloud.githubusercontent.com/assets/8440903/9179147/8746ee78-3f68-11e5-8d48-47d349a33a4f.jpg)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9187286/c08838ac-3f9c-11e5-825a-a0c3cbda9d7b.png)
