### ISSUE TITLE
418531 - PT pricing not showing up correctly on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#517]
Post Tour is listed as $1,100 but shows up on invoice as $1,279?

![image](https://cloud.githubusercontent.com/assets/8440903/9179206/fbc62782-3f68-11e5-9aa4-c19625180991.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9179211/00b3f210-3f69-11e5-9c1b-fab47c194ea9.png)

**Comment by bradatkins** [comment]
Hey -

It's an old order, and my guess is the option used to cost $1279 but now is priced at $1100.

Brad

**Comment by ali206** [comment]
Ok so what does it being an old order have to do with anything?

If the PT pricing since they've registered has been adjusted to $1,100, and they just added the PT, why would the pricing be incorrect?

**Comment by bradatkins** [comment]
All good now
