### ISSUE TITLE
419844 - dept city won't update

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#519]
Dept city updated to LAX from SFO but won't actually update on invoice.

Also added comments in Additional Comments section of DB.  I have updated the order several times but the order still shows departure city as SFO and it doesn’t show added comments

![image](https://cloud.githubusercontent.com/assets/8440903/9179350/ec625d00-3f69-11e5-98fb-ed040f26a2f5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9179355/f1615a54-3f69-11e5-931b-d55b1c788bc5.png)

**Comment by bradatkins** [comment]
Fixed
