### ISSUE TITLE
420208 - 0 pax show = wrong and unable to switch tours

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#520]
This person should not be showing as cancelled - can you get her information to show again?

Yaritza tried switching her tour so i'm assuming that's how the # of pax got messed up b/c she said it wasn't working for her.

![image](https://cloud.githubusercontent.com/assets/8440903/9179510/21f89d0c-3f6b-11e5-8370-892f27b9c84c.png)

Dept dates exist but there is no drop down of dates when trying to switch tours:
![image](https://cloud.githubusercontent.com/assets/8440903/9179534/4fc52be2-3f6b-11e5-9de5-43b7fe151fdb.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9179536/545e6a2e-3f6b-11e5-81ca-94f72ab19d8a.png)

**Comment by bradatkins** [comment]
Should be good now
