### ISSUE TITLE
URGENT: 420223 - 2 pax but 1 pax name shows twice?!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#521]
I tried updating but was brought to a blank screen?
![image](https://cloud.githubusercontent.com/assets/8440903/9182247/af827894-3f77-11e5-9f5a-12cf1c46e815.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9182258/bc6e5078-3f77-11e5-93aa-d7b34928c474.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9182264/c1fd7f0a-3f77-11e5-88bd-f95374f66a15.png)

**Comment by bradatkins** [comment]
Try now

**Comment by ali206** [comment]
nothing updated still

**Comment by bradatkins** [comment]
Fixed
