### ISSUE TITLE
418698 - ins. won't show on invoice but is accepted

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#522]
![image](https://cloud.githubusercontent.com/assets/8440903/9182296/ee3622d4-3f77-11e5-99f8-0ec26e05fd88.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9182301/f3caefd6-3f77-11e5-9eef-43c46d76754c.png)

**Comment by bradatkins** [comment]
I just updated the order and it updated fine?

![image](https://cloud.githubusercontent.com/assets/8440255/9187112/d26b1942-3f9a-11e5-9f50-af30a7778cdf.png)

**Comment by ali206** [comment]
i'm assuming b/c you fixed the bug prior to getting to this issue...
