### ISSUE TITLE
420162 - cc charge didn't post to acct?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#525]
i don't have a cc receipt which would mean i did it manually...

![image](https://cloud.githubusercontent.com/assets/8440903/9202023/d12d387a-401d-11e5-87c0-dcd27995601a.png)

**Comment by ali206** [comment]
any chance you can look in to this today? I need to post it to her account because she's overpaid now and we need to refund her...

**Comment by bradatkins** [comment]
Sorry, what is the issue?

**Comment by ali206** [comment]
the cc payment she made on 8/5/15 didn't post to her invoice

**Comment by bradatkins** [comment]
Fixed
