### ISSUE TITLE
Search Engine Modification

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#527]
Hi Brad,

As per Sandy's request. Please eliminate Tour Inclusions from being searchable.

Thank you,

Ronen

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
Perfect! Thank you Brad!

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
