### ISSUE TITLE
420237 - 2 diff. pple registered but only 1 name shows

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#528]
Is there a bug somewhere? This keeps happening...

**Comment by bradatkins** [comment]
Yes, there must be I noticed on a few new orders. I'll check

**Comment by ali206** [comment]
ok - just happened with 420239 as well

**Comment by bradatkins** [comment]
Fixed both orders. Looking into root cause

**Comment by bradatkins** [comment]
Fixed root cause
