### ISSUE TITLE
Addt'l options showing in wrong column in recaps

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#531]
Addt'l options showing in wrong column in recaps:

Ex: JN071215

![image](https://cloud.githubusercontent.com/assets/8440903/9283496/52278940-42a2-11e5-9a3a-e0077be31a77.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9620743/7cfef768-50ec-11e5-9c98-ff1ebfc04bc9.png)
