### ISSUE TITLE
Blue Sheet Page - Enhancement

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#533]
Hi Brad, 
I would like to add a small enhancement to the Blue sheet page.

I would like to add the words BLUE SHEET to the top because too many people in our office are getting confused...
![image](https://cloud.githubusercontent.com/assets/8440601/9307234/452b2820-44cb-11e5-99fa-dbfddc68619c.png)

**Comment by bradatkins** [comment]
Done. Unfortunately PDF's are wierd and whenever I tried to make the word BLUE SHEET bigger it messed up the PDF

Hope this works 

![image](https://cloud.githubusercontent.com/assets/8440255/9424117/4cb3257a-48ae-11e5-8038-601ed329934d.png)

**Comment by Sandra206** [comment]
Hi Brad,

Thank you! Milanka would also like the following:
1)	There should be a “today’s date” date when printed or scanned
2)	I do not think Blue sheet should have highlighted info

**Comment by Sandra206** [comment]
the highlighted info is the thank you for choosing 206 tours part...
