### ISSUE TITLE
Center information in UI

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#537]
Hi Brad,

as per our conversation, please center the information in the UI:

Current UI in IE / Firefox
![image](https://cloud.githubusercontent.com/assets/10079829/9336100/bdcb8c7c-45a5-11e5-8783-9fb893c5f3c9.png)

Modified UI:
![image](https://cloud.githubusercontent.com/assets/10079829/9336122/d6cc3b4a-45a5-11e5-9135-fafa0e042271.png)

thank you!

**Comment by bradatkins** [comment]
This is the best I can get it

![image](https://cloud.githubusercontent.com/assets/8440255/9777328/ff1076ce-5730-11e5-9a0f-076f488bad23.png)
