### ISSUE TITLE
420302 - email address won't update

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#538]
Email address everywhere says .net but on invoice says .com...where does it need to be fixed??

![image](https://cloud.githubusercontent.com/assets/8440903/9336497/e56b2650-45a7-11e5-9c8b-11e75e002932.png)

**Comment by bradatkins** [comment]
Did you check the "All Travelers" section?

**Comment by ali206** [comment]
yes it says .net
.
![image](https://cloud.githubusercontent.com/assets/8440903/9336875/e7a27d18-45a9-11e5-995e-7146d1c71a8d.png)

**Comment by bradatkins** [comment]
[image: Inline image 1]

[image: Inline image 2]

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/9337961/4967da9c-45b0-11e5-954e-ab1b2aaffdc8.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9337964/4ce95f24-45b0-11e5-87d3-07265680e90c.png)

**Comment by ali206** [comment]
Right. it's already correct in that section as well but it's not updating on the invoice.....???

**Comment by bradatkins** [comment]
This is an odd one. His Order was associated to a Travelers record that was set to Inactive. I've switched things up and it's fixed
