### ISSUE TITLE
420139 - group leader not receiving emails of orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#539]
her email address is listed in the correct spot but she's not receiving any of the invoice being emailed out

Also, do group leaders get BCC'd in those emails?  they shouldn't b/c we'll have no way of knowing if they're getting emails or not

**Comment by bradatkins** [comment]
Fixed 

![image](https://cloud.githubusercontent.com/assets/8440255/9424233/10d4c806-48b3-11e5-91ea-b51756e5ebf0.png)
