### ISSUE TITLE
CC charged once but posting twice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#54]
![image](https://cloud.githubusercontent.com/assets/8440903/4272433/50df4468-3ce2-11e4-83a2-478fbc95efd4.png)

![image](https://cloud.githubusercontent.com/assets/8440903/4272427/3fcddfa4-3ce2-11e4-8f76-5538fd1f9143.png)

**Comment by bradatkins** [comment]
A little late to the game on this one (me) but I haven't seen this happen again?

I suggest we close and if it does we can look into it in more detail

**Comment by ali206** [comment]
this is the same as #232 though so it did happen again

**Comment by bradatkins** [comment]
Looks like it's fixed now
