### ISSUE TITLE
(pre) (Post) shows up after confirming registration

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#541]
why does pre post show up on top of page after confirming registration?
![image](https://cloud.githubusercontent.com/assets/8440903/9358704/62c46ae0-465b-11e5-8208-9ed16a1692c8.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9424140/1399c2d4-48af-11e5-9c0e-56931ffe25f8.png)
