### ISSUE TITLE
ARC - tckt applied to wrong booking

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#543]
Set this status to Pending and went back to check it, it said approved.  I tried with ERROR and same thing happened:

![image](https://cloud.githubusercontent.com/assets/8440903/9364259/6bd284dc-4679-11e5-971c-3fff06cb813e.png)

How do i change the booking # this is applied to since it's applied to the wrong one?

**Comment by bradatkins** [comment]
What order should it be associated to?

**Comment by ali206** [comment]
419783

**Comment by ali206** [comment]
Here is another example:

Should be 419680:
![image](https://cloud.githubusercontent.com/assets/8440903/9585401/a880101a-4fe4-11e5-8dda-bbbf039aaff6.png)

I just set it to error so i could try and maybe change order # and when i went back to look for it it's now showing as approved:

![image](https://cloud.githubusercontent.com/assets/8440903/9585413/c31df75c-4fe4-11e5-84a1-b3f5871652ab.png)

**Comment by bradatkins** [comment]
Fixed. You can change the status now
