### ISSUE TITLE
420328 - client from CT but has foreign currency invoice?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#544]
I clicked on View in USD and below popped up:

![image](https://cloud.githubusercontent.com/assets/8440903/9368501/a330034c-4691-11e5-9ae8-6daf5087f79b.png)

**Comment by ali206** [comment]
Also the payment she made is not on the list of settled cards for that date in Elavon and this Transaction ID from DB is not found in Elavon:

![image](https://cloud.githubusercontent.com/assets/8440903/9368608/444b22c0-4692-11e5-883f-b95bb4b94462.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9368629/601a8428-4692-11e5-9a37-f3148c9f429c.png)

**Comment by bradatkins** [comment]
Checking, not sure I have enough logging turned on to figure this one out yet.

I suggest you cancel the transaction, and I will switch the order to USD

**Comment by bradatkins** [comment]
I also will add more logging to the DB so I can debug this in the future

**Comment by bradatkins** [comment]
That transaction should be showing in the Multi currency account...even if
the card wasn't a MC, the DB posted it to that account.

**Comment by ali206** [comment]
Why should it be showing in the MC Account though if it wasn't a foreign CC?  That means the DB is posting charges to the incorrect account?

**Comment by bradatkins** [comment]
Well, for whatever reason the DB (or the client) picked EUR as the currency.

Elavon does not "check" the card to see if it's a MC card.

So infact, the DB posted it to the "correct" account, it's just that it's
incorrect that the client had the EUR currency
