### ISSUE TITLE
unable to view in USD 420336

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#545]
![image](https://cloud.githubusercontent.com/assets/8440903/9368570/f9774832-4691-11e5-85aa-50a7f2750e73.png)

**Comment by bradatkins** [comment]
Did this charge post to the MC account?

To view the USD invoice:

![image](https://cloud.githubusercontent.com/assets/8440255/9372417/3442cf76-46ac-11e5-8c14-b2b5355f2266.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9372418/37896460-46ac-11e5-9534-6daac88e29ec.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9372420/3b34589a-46ac-11e5-8f05-3de9de48bc41.png)


If that doesn't work, copy me the URL of the invoice pdf.

**Comment by ali206** [comment]
I know how to view the invoice in USD lol but it wasn't working that's why I added this issue.

It settled in the MC account:

![image](https://cloud.githubusercontent.com/assets/8440903/9384069/849611f8-471b-11e5-90a5-02952976e1fa.png)

still not able to view in USD:
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=420336&TravelerID=27591&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
This happens because you are trying to access the invoice directly by URL.
if you access it via the admin, it'll show in USD.

Brad

**Comment by ali206** [comment]
Brad I'm sorry but I'm not sure what you're talking about.  That url link I sent you is the page that opens up directly from the DB and I'm Admin so how am I doing something wrong?

Sent from my HTC

----- Reply message -----

**Comment by bradatkins** [comment]
Try it again tomorrow. I tried it and it worked OK.

But when I clicked on the link from Git it shows the Customer currency

**Comment by ali206** [comment]
Just tried and it's still not working...

I'm clicking on the invoice button and then view in USD and the page that opens up is still in CAD:

![image](https://cloud.githubusercontent.com/assets/8440903/9399388/84842612-4781-11e5-8772-2593c4b3aa0f.png)

**Comment by bradatkins** [comment]
Does it prompt you?

**Comment by ali206** [comment]
like the pop up to open in USD or CAD currency? Yes

**Comment by bradatkins** [comment]
Hmm I can't seem to reproduce it.

Can you close all your browsers and then step by step tell me what you do?

**Comment by ali206** [comment]
Ok I open IE, go to the DB main page, type in order #420440 and click go:

![image](https://cloud.githubusercontent.com/assets/8440903/9521453/fca6d7d2-4c9c-11e5-8e42-33b114ed8af4.png)

Then i click on invoice icon:

![image](https://cloud.githubusercontent.com/assets/8440903/9521465/08822610-4c9d-11e5-95a2-c4660ef8878a.png)

View in USD:

![image](https://cloud.githubusercontent.com/assets/8440903/9521477/12615e26-4c9d-11e5-9f5f-ee642974fcf3.png)

And it opens up in a new tab as CAD still...

![image](https://cloud.githubusercontent.com/assets/8440903/9521484/1f984370-4c9d-11e5-9a59-bc1289c92902.png)
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=420440&TravelerID=25572&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Ahhh...Internet Explorer is stupid haha. It's fixed now. It was specific to IE

**Comment by ali206** [comment]
ok it's working thanks
