### ISSUE TITLE
Int'l CC's charged within the office through DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#547]
this may be a stupid question, but in the DB when someone in the office is trying to charge an int'l card, the DB is automatically going to pick up on that fact and charge in the correct countries currency?

Or that's the eventual goal...

Because Amanda tried charging a card today with address below, which didn't go through for the $53 she entered (she's not aware of the MC yet)...but it's showing in euros...and i'm pretty sure Guyana does not use euros?

![image](https://cloud.githubusercontent.com/assets/8440903/9399442/634b0fc8-4782-11e5-910c-c977016298c5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9399456/81420856-4782-11e5-8bfd-3c7062fa97f7.png)

**Comment by ali206** [comment]
Also the charges Amanda put through posted to the invoice in USD but in converge they're Euros so i don't even know what the correct amount is in, USD?

![image](https://cloud.githubusercontent.com/assets/8440903/9399507/3497541a-4783-11e5-9c05-b104fb1e5d46.png)

**Comment by bradatkins** [comment]
There is no algorithm or indication in a card number that it is
international (non-USD). The DB will never be able to auto-detect a MC
card, because there's no such thing.

The DB had defaulted to Austria as the first currency (which uses Euros)
