### ISSUE TITLE
URGENT: new registrations not actually registering pple

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#548]
![image](https://cloud.githubusercontent.com/assets/8440903/9442350/7f80a1ca-4a49-11e5-81ca-68c6ec6da3e6.png)

**Comment by bradatkins** [comment]
Checking...

**Comment by bradatkins** [comment]
Try a test order please...I have to run to a meeting.

**Comment by ali206** [comment]
tried test orders, one as existing client one as new client and they both went through. 

On the new client registration i was actually able to charge $1.00, is that only an ADMIN thing?

![image](https://cloud.githubusercontent.com/assets/8440903/9443188/b5b7909c-4a4d-11e5-9881-345a3f81dd02.png)

**Comment by bradatkins** [comment]
Yes administration can put whatever they want I believe.

**Comment by bradatkins** [comment]
I have also fixed up the orders, but please validate.
