### ISSUE TITLE
CC payments not able to be processed via DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#549]
![image](https://cloud.githubusercontent.com/assets/8440903/9444567/92bc5336-4a55-11e5-9f98-2f1e4001c9a7.png)
 then i clicked submit payment and you get this:

![image](https://cloud.githubusercontent.com/assets/8440903/9444572/983dfee0-4a55-11e5-9eb0-977a919155e7.png)

Then you approve it and you just get brought to a blank screen that does nothing - i manually charged this card so it's not the CC:

![image](https://cloud.githubusercontent.com/assets/8440903/9444583/a76a2c72-4a55-11e5-8433-efb2cec238b6.png)

**Comment by bradatkins** [comment]
Try now please

**Comment by ali206** [comment]
Ok i just tried one and it worked
