### ISSUE TITLE
Ins. being added to both pax but only 1 pax has it

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#55]
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=416600&GENERATED=TRUE&SHOW_COMMISSION=Y 

Only Raymond Gross should have ins. DB is adding it in to 2nd pax order total for some reason.

**Comment by bradatkins** [comment]
Looks like these PAX are cancelled, so I can't check it. Keep an eye out if this happens again

**Comment by ali206** [comment]
Amanda just had a crazy issue with insurance on 417830 that she finally got to show correctly but maybe you can see her logs?

She accepeted ins. for one pax but it wouldn't show on invoice, then she added it manually and it showed under wrong pax, then she had to accept ins. on top of leaving her manually applied insurance premium just to get it to show/calculate correctly
