### ISSUE TITLE
Terms and Conditions - Gremlins

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#550]
Hey Brad,

The Terms and Conditions for two itineraries that need to be updated asap. Can you updated them as per below.

Note:
-	ALL Terms and Conditions for Splash Pages and Websites for Canonization of Mother Teresa: 
I had retyped the Terms and Conditions, to mirror Special conditions, and I added them to the database when building them. I am not sure if someone has gone in and changed them, or it did not save for some reason, but there are a lot of mistakes. 

I had changed the Insurance info to Travel Ex, and updated with their prices, but Travel Guard is back showing on it, along with Travel Guard prices? 

There are also typos all throughout…  such as anywhere saying “traveling - or - traveler” just read as “ing – or - er” and “cancellation” was replaced with “/n” among others. See below:

 

God Bless,

________________________________________
 	Patrick McKenna 
Business Manager
206 Tours Inc.
333 Marcus Blvd – Hauppauge, NY 11788
206Tours.com

Tel: 800.206.8687 | 631.361.4644 ext. 117 | Fax: 631.361.3682
patrick@206Tours.com | Skype: patrick -206tours

     client letters

**Comment by bradatkins** [comment]
So what should they be updated to?
