### ISSUE TITLE
420393 - CC pmnt didn't post to invoice?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#551]
I had to manually apply this but it was processed through the DB but didn't post to the booking/invoice...

![image](https://cloud.githubusercontent.com/assets/8440903/9452273/50a76af4-4a81-11e5-893c-a18d6a8e0f01.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9452283/57896d36-4a81-11e5-8ce7-dd20a7f6e7a2.png)

**Comment by bradatkins** [comment]
Which one of these were manually applied?

![image](https://cloud.githubusercontent.com/assets/8440255/9454851/413acc16-4a93-11e5-963c-48b1205f30f3.png)

**Comment by ali206** [comment]
Olivia's payment i believe

**Comment by bradatkins** [comment]
Seems to be there now.  This was also on the 24th while I was doing the MC stuff. If payments are going through fine now, I'd suggest we close this.

![image](https://cloud.githubusercontent.com/assets/8440255/9536970/a872d792-4d00-11e5-9e87-a7079cc66c17.png)
