### ISSUE TITLE
420395 - trying to add new pax not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#553]
Piernha tried but could not get past the screen that asked how many pax she was adding.

I tried, was able to enter in 2nd pax information and after clicking update was brought to a blank page, meaning 2nd pax wasn't actually registered:

![image](https://cloud.githubusercontent.com/assets/8440903/9495720/03608022-4bdb-11e5-9bd7-2978814da3b2.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9495742/123ef2b8-4bdb-11e5-9032-c07766adb08a.png)

**Comment by bradatkins** [comment]
Can you get her to try again? It seems to come up OK for me

![image](https://cloud.githubusercontent.com/assets/8440255/9536829/b4683be8-4cfe-11e5-806c-f45ee833e2cc.png)

**Comment by ali206** [comment]
It came up ok like that for me as well but wouldn't save any of the information, just got brought to a blank screen.  She booked the addti'l pax on his own booking, guess she couldn't wait sorry.
