### ISSUE TITLE
418168 - keep orig. pricing not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#554]
![image](https://cloud.githubusercontent.com/assets/8440903/9496756/f0613e9e-4bdf-11e5-8264-15f7961b3f83.png)

Base price should be $2,799 as per original cost of tour

**Comment by bradatkins** [comment]
Fixed. Surprised this hadn't come up before...

![image](https://cloud.githubusercontent.com/assets/8440255/9537091/49dfb5a4-4d02-11e5-81b1-1fe6ecca3f23.png)
