### ISSUE TITLE
Address not updating in name list

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#555]
![image](https://cloud.githubusercontent.com/assets/8440903/9496839/48b93132-4be0-11e5-8698-0d8c65a4f575.png)

**Comment by bradatkins** [comment]
Two questions:

1) What's the right address?
2) What excel report is this?

**Comment by ali206** [comment]
I'll ask Yaritza what excel report but the correct address is above the excel report in first message

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/9579531/62f1866e-4fc1-11e5-9adb-5e6523e22c8f.png)

**Comment by bradatkins** [comment]
Fixed
