### ISSUE TITLE
Incomplete Orders Still Picks-up Wrong Pilgrims

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#556]
![image](https://cloud.githubusercontent.com/assets/8440903/9496889/857eacbe-4be0-11e5-8818-eebc682aaa11.png)

**Comment by bradatkins** [comment]
Can I get a screenshot of the incomplete orders screen highlighting which order she's trying to resume?

**Comment by ali206** [comment]
he's not in there anymore because she registered him - 
![image](https://cloud.githubusercontent.com/assets/8440903/9585197/69342906-4fe3-11e5-9643-95de7c8e39b7.png)

**Comment by bradatkins** [comment]
Let me know if it happens again, and try not t touch it if possible
