### ISSUE TITLE
420376 - cc payment didn't post to a booking in the DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#557]
240815A15-0E4FC3E1-A81D-4622-B9CA-76C4E3D9183F

$943 

![image](https://cloud.githubusercontent.com/assets/8440903/9504115/b08a95da-4c08-11e5-91ba-5e1fb8a62a62.png)

I had to manually apply it

**Comment by bradatkins** [comment]
When you say didn't post to booking do you mean show up on the invoice (or
subtract) from the invoice or didn't post to Elavon?

**Comment by ali206** [comment]
They posted in Elavon. 

They didn't show up on the invoice at all and so the total due showing was wrong as well

**Comment by bradatkins** [comment]
ok checking

**Comment by bradatkins** [comment]
I just ran a test order and it's working OK. This order was placed on a
date when I was making the MC changes, so I think it's related to that.

**Comment by ali206** [comment]
Ok i'll let you know if i see any more
