### ISSUE TITLE
419069 - cc pmnt applied but not showing in all payments

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#559]
payment manually processed and applied in DB but not showing in view payments for the day?

![image](https://cloud.githubusercontent.com/assets/8440903/9504400/69775ef6-4c0a-11e5-9621-c43eb8401325.png)

$2199 8/24

below is all that's showing:

![image](https://cloud.githubusercontent.com/assets/8440903/9504410/713c6244-4c0a-11e5-8f16-7782abef6005.png)

**Comment by bradatkins** [comment]
I just ran a test order and it's working OK. This order was placed on a
date when I was making the MC changes, so I think it's related to that.

**Comment by ali206** [comment]
this is separate from the other 2 issues i just posted so i don't think your response applies?

I processed this payment in Elavon, manually applied the payment/transaction ID to the invoice via my external payments link, but when you go to view payments for that date, the payment does not show anywhere but you can see it applied to the invoice

**Comment by bradatkins** [comment]
Hmm ok but I think you manually applied the payment on the same day (August 24th)?

**Comment by bradatkins** [comment]
Can you try and replicate the issue?

**Comment by bradatkins** [comment]
It was also on the 24th, so please try and replicate, but I'm guessing it was during the MC change....

**Comment by ali206** [comment]
Irena said this payment didn't post to the invoice and so she manually applied it:

300815A15-5E26804E-25D1-4864-8507-8B6549C7BE78
420473

**Comment by bradatkins** [comment]
Fixed

**Comment by bradatkins** [comment]
But please keep an eye out
