### ISSUE TITLE
MC test transaction - used wrong card but no option to resubmit a new card on that error page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#560]
since i tried to process with an AX first i got this error message but there is no submit button on the bottom after i entered in all MC info, i had to start all over:

![image](https://cloud.githubusercontent.com/assets/8440903/9506613/2c6047be-4c17-11e5-8ff4-cba771c0dbf7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9506619/375d80f0-4c17-11e5-9626-54e7746f8344.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9509647/4110b860-4c30-11e5-8f24-cc253f61787e.png)
