### ISSUE TITLE
MC Test Transaction with mastercard

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#561]
#1. It should say somewhere that a VI or MC can only be used before trying any other CC right? I didn't see a message anywhere...

![image](https://cloud.githubusercontent.com/assets/8440903/9506753/e16e80c6-4c17-11e5-9214-df69c076c02a.png)

When i selected other amount i had entered in $100 but wasn't sure that the DB would charge that in CAD (1.33) so i entered the total amount in CAD as $1.33 which showed up as $1.77 b/c the DB DID actually charge the USD amt i entered in to CAD.

![image](https://cloud.githubusercontent.com/assets/8440903/9506819/473f0f56-4c18-11e5-9373-15e12a378f49.png)
(i voided this charge)

Is any of this helpful?

**Comment by bradatkins** [comment]
I've added the message:

![image](https://cloud.githubusercontent.com/assets/8440255/9509127/1ec269b2-4c2a-11e5-974c-b60f3b37bcd1.png)

I just made another change, I was double converting some stuff in certain situations.

So now you'll see this:

![image](https://cloud.githubusercontent.com/assets/8440255/9509150/41ed5f46-4c2a-11e5-8dfe-f16b0f3f0b93.png)

In Elavon, if you do another test, you should see $1 CAD where you see 1.77 today

Then when Elavon closes the batch, that would get paid to 206 Tours as $0.75 USD

Try another test tomorrow and take some screenshots

**Comment by ali206** [comment]
Ok i just did another test, entered in $1.00 (in my head USD) and i'll leave it this time to see how it settles.  Only admin can change the deposit amount but any other payments made after that by someone in the office could be a problem.  If they're making a payment on a Canadian's person booking, they're going to be entering in USD amounts i imagine....am i just confusing myself again? lol

![image](https://cloud.githubusercontent.com/assets/8440903/9521313/1deaa352-4c9c-11e5-8654-ee6ea072bf49.png)


![image](https://cloud.githubusercontent.com/assets/8440903/9521310/18eb87b8-4c9c-11e5-9363-5f27c43bca95.png)


![image](https://cloud.githubusercontent.com/assets/8440903/9521308/1540d758-4c9c-11e5-89b5-ea289ea65b85.png)

**Comment by bradatkins** [comment]
Just remember, you entered $1 in...it's $1 Canadian. That $1 should get
"paid" to 206 tours as $0.75 or whatever the rate is.

Looks like it's working, now let's wait to see what Elavon converts/pays it.

**Comment by ali206** [comment]
Elavon didn't convert anything...

![image](https://cloud.githubusercontent.com/assets/8440903/9548252/764ed71c-4d6d-11e5-9e9f-106f65d0254e.png)

I just emailed you about this

**Comment by bradatkins** [comment]
I think we have this figured out now. Elavon won't show the converted value in this screen, but only convert it when depositing it into 206 Tours bank account
