### ISSUE TITLE
419934 - need to refund through MC Acct...

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#564]
so i have to refund these 2 transactions but should i set the currency to USD when doing so? These were supposed to be USD charges to begin with...

Or do i refund as euros even though they weren't supposed to be?

![image](https://cloud.githubusercontent.com/assets/8440903/9523070/43414a84-4ca6-11e5-87fc-4308eb6da1cf.png)

**Comment by bradatkins** [comment]
Refund in EUR, and I'll set the currency for this order to USD. Is it
supposed to be USD?

**Comment by bradatkins** [comment]
oh and tell me when it's be refunded, then I will reset the currency

**Comment by ali206** [comment]
currency on this invoice was always supposed to be in USD, isn't it showing it's in USD already? - i just refunded the charges.

**Comment by bradatkins** [comment]
Closing, hasn't happened since
