### ISSUE TITLE
unable to search by client last name in all orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#565]
![image](https://cloud.githubusercontent.com/assets/8440903/9550778/630f4a2a-4d7b-11e5-95a2-0353f4db6be7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9550771/5267b73e-4d7b-11e5-9dff-2b14d4dbda91.png)

**Comment by bradatkins** [comment]
Fixed 

![image](https://cloud.githubusercontent.com/assets/8440255/9593940/465313ee-5023-11e5-9aae-8c3e9da03aa0.png)
