### ISSUE TITLE
confirmation page after registering

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#567]
![image](https://cloud.githubusercontent.com/assets/8440903/9582976/aac97ab8-4fd6-11e5-9f90-bbd546bc02d3.png)

**Comment by bradatkins** [comment]
Done

**Comment by ali206** [comment]
Not sure if this was always there or not but how come where arrow is pointing is showing? You can't actually click on any of those options?

![image](https://cloud.githubusercontent.com/assets/8440903/9606182/e9d943fa-508f-11e5-842b-9180b1290315.png)

What about the View Your account and Logout on the bottom? I don't think we need to tell pple what they can do with those links right?

**Comment by bradatkins** [comment]
It's to show them where they are at in the process. This has been there
since we started :)

**Comment by ali206** [comment]
I just double checked with Sandy and she said people should be able to click on those tab options

**Comment by bradatkins** [comment]
Please log that as a separate enhancement for Phase 12 as we discussed yesterday.
