### ISSUE TITLE
Searching in ARC Tickets

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#569]
I tried searching by Nov 2015 but other dates showed up as well:

![image](https://cloud.githubusercontent.com/assets/8440903/9585351/5a855302-4fe4-11e5-93ed-f870125a73c5.png)

**Comment by ali206** [comment]
And when i clicked on page 2, it brought me to all tickets
![image](https://cloud.githubusercontent.com/assets/8440903/9585381/9413bd16-4fe4-11e5-9eed-2873aca6dbc2.png)

**Comment by bradatkins** [comment]
Fixed
