### ISSUE TITLE
418994 - base price won't update to LO pricing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#570]
![image](https://cloud.githubusercontent.com/assets/8440903/9588366/d3d7672a-4ff5-11e5-8130-75989f7a7b07.png)

Updating and all that is not working, should only be $1099

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9594268/0c3609ec-5027-11e5-9f37-e40dad2a7855.png)
