### ISSUE TITLE
Employees charging foreign currency

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#571]
If a client calls up to make a payment anyone in the office can make the payment thorugh the DB.  

If they're making a payment on a Canadian's person booking, they're going to be entering in USD amounts i imagine because they don't know what it should be in CAD, how is that going to work?

The DB (other than deposit and PIF w/in 60 days) doesn't automatically tell you how much to be charged so i am imagining lots of errors.

**Comment by bradatkins** [comment]
As a Canadian, if I called you and told you $100 I would be assuming as the
client, that's $100 CAD, not USD.

**Comment by ali206** [comment]
ok i guess we'll see how this goes then
