### ISSUE TITLE
No AX or DIS CC options anymore

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#572]
![image](https://cloud.githubusercontent.com/assets/8440903/9606389/2f9e8da4-5091-11e5-893c-f38b0a812f0f.png)

420342
![image](https://cloud.githubusercontent.com/assets/8440903/9606393/3805ffb8-5091-11e5-93f2-9b30f2852033.png)

**Comment by ali206** [comment]
Also no state/country option

**Comment by bradatkins** [comment]
Fixed
