### ISSUE TITLE
420493 - notes not saving

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#573]
![image](https://cloud.githubusercontent.com/assets/8440903/9608305/c8db99d0-509b-11e5-887e-fa2dc12bacde.png)

**Comment by bradatkins** [comment]
A quick fix is just to remove the apostrophe.

I noticed Yaritza had put in Flight's cost $3,412 pp

Try

Flights cost $3,412 pp

And I'll put in a fix later.

**Comment by bradatkins** [comment]
Fixed
