### ISSUE TITLE
paypal payments not posting to invoices

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#574]
we're getting emails at info@206tours.com that a client has made a payment and then i'm manually applying the payments to the invoices like i do with ACH's

**Comment by bradatkins** [comment]
Can you forward me one of those emails (if you still have them)

**Comment by bradatkins** [comment]
Fixed 
![image](https://cloud.githubusercontent.com/assets/8440255/9611175/3b99d2e2-50ac-11e5-9665-7c7cb45cfed8.png)
