### ISSUE TITLE
URGENT issue with payments in the DB 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#576]
Shows outstanding balances for people that have made payments and/or are PIF:

![image](https://cloud.githubusercontent.com/assets/8440903/9637145/2fbe1bec-516d-11e5-8ace-c91381df3f9b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9637157/41cda82a-516d-11e5-8292-c02ac0cfe4c4.png)

**Comment by bradatkins** [comment]
Fixed
