### ISSUE TITLE
New Pax added on 420212 - not working correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#577]
![image](https://cloud.githubusercontent.com/assets/8440903/9637652/0f984998-5170-11e5-8904-25c242f02ca3.png)

Should have 3 pple showing as registered:
![image](https://cloud.githubusercontent.com/assets/8440903/9637663/1bb84930-5170-11e5-87bd-12ac9d12661a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9637677/2b126564-5170-11e5-89c1-e48d0ec6100a.png)

Campise not showing:
![image](https://cloud.githubusercontent.com/assets/8440903/9637686/365d5f28-5170-11e5-805e-2f4d64db64d5.png)

All 3 names should be in all 3 places and the departure city should be chicago for the 2 marys and Nashville for Zimmerman – not New York, Tennessee as it is reading….

**Comment by bradatkins** [comment]
Fixed (the audit will still be broken on this one)
