### ISSUE TITLE
419576 - commission issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#580]
showing correctly on invoice but showing as balance due in view payments and it shouldn't be:

![image](https://cloud.githubusercontent.com/assets/8440903/9668659/d3d011ca-5250-11e5-9ad8-269515e8b21b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9668664/da6b3c80-5250-11e5-9814-cf84c5f6bc50.png)

**Comment by bradatkins** [comment]
Fixed
