### ISSUE TITLE
Passenger cant complete reservation 

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#581]
Hi, I have been trying to book Tour 207 (Mexico) for some time. Firstly I was not able to log in but that issue has been resolved. Now when I complete all the information it prompts me to indicate land fare/air fare but the pull down menu doesnt work and doesn't give me the option. I would also like to know if this tour will be departing on 7 Jan. thanks. Lorella

**Comment by bradatkins** [comment]
She was using a Windows 8 device, which shouldn't matter.
 
It looks like the DB prompted her to fill out "Travel Arrangements" (eg Land or Air & Land) even though she selected Land Only.
 
Remote Host:
203-219-62-103.tpgi.com.au [203.219.62.103]

Email Address:
lorella@tpg.com.au
