### ISSUE TITLE
419706 - payment won't show on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#583]
i've tried a few times to apply a payment to this invoice manually and it won't show no matter what i do:

![image](https://cloud.githubusercontent.com/assets/8440903/9747323/08e5288e-564b-11e5-9035-357b5673e8d7.png)

**Comment by bradatkins** [comment]
Fixed and I posted the payment for you

![image](https://cloud.githubusercontent.com/assets/8440255/9776563/c20ae560-5727-11e5-9482-e47d4fe9af52.png)
