### ISSUE TITLE
Phase 12

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#585]
1.	Ability for people to pay with more than 1 CC at a time/combo payment with other cc/check etc.
2.	Include ins. in revised booking emails
3.	Installments – working but not correctly
4.	SD Discounts 
5.	Set up refer a friend type thing
6.     Calendar – we paid for it long time ago, but have no clue what that is all about
7.     206 Tours App (Milanka added this so i'm not sure if you know what it's about or not?)

**Comment by bradatkins** [comment]
Insurance now triggers an email to be sent.

![image](https://cloud.githubusercontent.com/assets/8440255/10531546/3587922a-7381-11e5-87e2-b2d5f0803074.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/10558691/f8831594-74a6-11e5-909f-fc9f8776373d.png)
