### ISSUE TITLE
420335 - commission messed up

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#586]
showing/deducting on invoice but in view orders it's not deducting:
![image](https://cloud.githubusercontent.com/assets/8440903/9772009/a53731fc-5707-11e5-9b9f-12a02b092c5d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9772014/aeb6c562-5707-11e5-82fe-da96d471075b.png)

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/9776660/b91567b8-5728-11e5-97ef-7e5817f6a0cd.png)
