### ISSUE TITLE
search orders by promo codes 

### ISSUE THREAD

**Issue by milanka206** [206Tours/DB#587]
Please give us ability to search orders by promo codes 
We advertise in some media and would like to know if ads are working 
- for now we need: “NCR”  "CNY" "EWTN"

**Comment by bradatkins** [comment]
This is done by the Promotion Codes Report

![image](https://cloud.githubusercontent.com/assets/8440255/20653853/7115a910-b4e1-11e6-95f8-2c9ee4cbc964.png)
