### ISSUE TITLE
420564 - order is a mess

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#589]
![image](https://cloud.githubusercontent.com/assets/8440903/9820778/0b1cb118-5884-11e5-9a02-9a63ef07a467.png)

**Comment by bradatkins** [comment]
This is fixed. There was a glitch because his original submission was paying by check. I placed a test order (a few) and it seems to be OK now. I've also fixed his order.

![image](https://cloud.githubusercontent.com/assets/8440255/9837156/28397e58-5a04-11e5-8f3c-c0c202c5adc4.png)

**Comment by bradatkins** [comment]
Actually, with one exception. I try to make a payment, paying with a TRY currency, and Elavon rejects it.

This is their error message:

![image](https://cloud.githubusercontent.com/assets/8440255/9837206/9534546e-5a05-11e5-90df-84c791bef9c2.png)


This is what I sent them. Perhaps if you could mention this to them, and see what's up.

You'll note:

a) I sent it to the new MC account
b) the ssl_transaction_currency is TRY
c) Their documentation (pg 318 of the Developer Guide, rev July 2015) says TRY is supported.

[ssl_merchant_id] => 534818 [ssl_user_id] => 206tourwebpage [ssl_pin] => G0KWEOV5V2QE01C2NOIM6XA7ZLZDE1HHS6W5I6A6ITX9TGXCISX41MKGMKATPCMN [ssl_show_form] => false [ssl_test_mode] => true [ssl_transaction_type] => ccsale [Type] => ccsale [ssl_amount] => 2899 [Memo] => 206 Tours Inc. [ssl_first_name] => Bradley [ssl_last_name] => James [ssl_avs_address] => 525 Westmountaaa [ssl_city] => Sudburyaa [ssl_avs_state] => [ssl_avs_zip] => 12345 [ssl_cvv2cvc2_indicator] => 1 [ssl_cvv2cvc2] => 123 [ssl_result_format] => ASCII [ssl_card_number] => 4007000000027 [ssl_transaction_currency] => TRY [ssl_exp_date] => 0921

**Comment by ali206** [comment]
ok i'm confused - his payment went through for $2,749 in our old account, not new MC Account.  There must not have been an error message if Piernha was able to process charge right? 

How come she was able to process it in USD?

![image](https://cloud.githubusercontent.com/assets/8440903/9880038/edc8ba8c-5b97-11e5-8259-6b32b83bc0c9.png)


![image](https://cloud.githubusercontent.com/assets/8440903/9879996/cd808944-5b97-11e5-9495-e50cd0c604b3.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
