### ISSUE TITLE
not able to update email

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#590]
Hi Brad,

I am trying to update the email address for this client and when i hit save it creates a fedex lable
![image](https://cloud.githubusercontent.com/assets/8440601/9859098/8f08299c-5af2-11e5-8a30-677ef196684b.png)

![image](https://cloud.githubusercontent.com/assets/8440601/9859099/92991da0-5af2-11e5-914b-459a64b5ab9c.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
