### ISSUE TITLE
Registration Section - Billing address Y / N as Shipping address reversed

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#591]
Hi Brad,

for clients that are registering as new clients - when they say the billing and shipping address are the same - the DB instructs them to filling in their shipping address - and when you press no, it doesnt ask the client to fill in the shipping address. the options are reversed. can you please look into this issue.

thank you.

![image](https://cloud.githubusercontent.com/assets/10079829/9859738/e86125c2-5af5-11e5-9a33-975cd0de2915.png)

![image](https://cloud.githubusercontent.com/assets/10079829/9859741/f1ac4436-5af5-11e5-8933-314e310c111a.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
