### ISSUE TITLE
Address: No box to enter City or State ? 

### ISSUE THREAD

**Issue by milanka206** [206Tours/DB#592]
Address order is not very orderly

Now country works (is prompting me to United states already there), but there is no box to enter Citi and or State and zip code comes before City and State 
In US we write City, than State than Zip Code

Mary Smith
123 Main Street
New York NY 11001
United States

Telephone we should have a pull down 
Work 
Home 
Mobile 

Email

**Comment by bradatkins** [comment]
Closing, hasn't happened since
