### ISSUE TITLE
420008 - there are 3 pax but only 2 in all orders?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#593]
And only 2 when you click on booking #:

![image](https://cloud.githubusercontent.com/assets/8440903/9877220/7c8e23ec-5b89-11e5-92e8-5777c9e5230d.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/9949887/d37b356a-5d81-11e5-9639-cf4c9abdcef4.png)
