### ISSUE TITLE
420559- not receiving emails

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#597]
The 2 emails sent on 9/15 were sent to the correct mpatrick...email address but he never received them?

![image](https://cloud.githubusercontent.com/assets/8440903/9935734/4dc1543c-5d26-11e5-8eb6-f2a25b5d2edd.png)

**Comment by bradatkins** [comment]
You'd have to contact Wired Tree. The DB only logs if it was able to successfully queue up the email message to the server itself. It has no idea of whether or not it's actually sent.

[15-Sep-2015 15:33:36 America/New_York] EMAIL: OrderID: 420559, mpatricktax@sbcglobal.net
