### ISSUE TITLE
420691 - email going out automatically after creating registration?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#599]
natasa created this order and after clicking on confirm order the below email was sent out automatically.  I thought that was disabled??

![image](https://cloud.githubusercontent.com/assets/8440903/9937499/087bd524-5d2f-11e5-9065-78003db5a1d6.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9937467/f350f58a-5d2e-11e5-8bcb-ab26a7807445.png)

**Comment by bradatkins** [comment]
From what I can see, she's not using the Shopping Cart icon or the new order link.

![image](https://cloud.githubusercontent.com/assets/8440255/9949318/2891d1a2-5d79-11e5-963b-05ce35a9bc13.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9949320/2bd105c2-5d79-11e5-9177-fd9cbc2fc761.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9949327/43d1c8d2-5d79-11e5-9690-cf783db5b0ec.png)
