### ISSUE TITLE
Post tour for tour DV021416 - 420668

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#600]
Shouldn't the post tour dates show as what they were entered in as? 23-26?  Or should that only show next to Travel dates on the top of the invoice?

![image](https://cloud.githubusercontent.com/assets/8440903/9944364/cff5bd48-5d54-11e5-9b41-f4c6af9dce13.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9944342/a935c766-5d54-11e5-91d4-65776b8fd907.png)

Also the PT seems like it's been created correctly but is not adding in to the invoice?

**Comment by ali206** [comment]
Also, is there a way to change the name/description of a PT or is the only way to do that to delete the PT option and recreate it?

**Comment by bradatkins** [comment]
Hmm something changed because it's there now:

![image](https://cloud.githubusercontent.com/assets/8440255/9949999/44f75aba-5d83-11e5-8f23-b1cfdd31a93d.png)

And yes, it must be deleted to rename it.
