### ISSUE TITLE
$3,488 payment in DB on 8/10 but no in Elavon?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#601]
I can't find this transaction ID in Elavon and $3,488 didn't post on 8/10/15 in elavon - can you figure out the actual date of this payment?

![image](https://cloud.githubusercontent.com/assets/8440903/9946051/fb309488-5d5e-11e5-9fac-d481bd236c0c.png)

**Comment by ali206** [comment]
i feel like i'm losing my mind...there's only 1 settled batch for 8/10 and these unhighlighted transactions are not showing??

![image](https://cloud.githubusercontent.com/assets/8440903/9946241/0621c622-5d60-11e5-80d4-d7442f64a11a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9946254/197c99f4-5d60-11e5-9a26-29cf7e4bc0e6.png)


![image](https://cloud.githubusercontent.com/assets/8440903/9946232/fae17a78-5d5f-11e5-87b2-9515ff849b0e.png)

**Comment by bradatkins** [comment]
Hmmm I'm seeing it going into the MC account, can you confirm?

**Comment by bradatkins** [comment]
Interesting to note, I think it posted to the MC account as a USD transaction.

This seems to be a gap with orders created before we implemented MC. I've put in some fixes to strength this area.

**Comment by ali206** [comment]
I checked the MC Account but guess i was losing my mind.  i'm used to payments showing in a setttled batch from the day before not the day of sorry.
