### ISSUE TITLE
Wording on a cxld invoice to be changed

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#602]
![image](https://cloud.githubusercontent.com/assets/8440903/9969234/56052a6a-5e1b-11e5-8ccb-8580d383657c.png)

It should show clients when they cancelled (date), penalty, how much 206 Tours refund, how much insurance …how to proceed

**Comment by bradatkins** [comment]
As mentioned in my follow up email this was someone's invoice and not the cancellation statement.

![image](https://cloud.githubusercontent.com/assets/8440255/9983662/edc7f73e-5fd2-11e5-896a-ba2e1638c318.png)
