### ISSUE TITLE
Tour Option Price not being saved in the DB

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#603]
Hi Brad,

we are trying to add a price option to this tour:
http://pilgrimages.com/law

DB code: SL030316 

but it is not saving:
![image](https://cloud.githubusercontent.com/assets/10079829/10104832/9d661c1c-6379-11e5-97b2-899091fa935a.png)

![image](https://cloud.githubusercontent.com/assets/10079829/10104840/ac0f3f32-6379-11e5-8226-b4120a48de82.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
