### ISSUE TITLE
Mexico Addons for Specials ---- URGENT!!

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#604]
Hi Brad,

We have a number of specials that need to mirror our base prices for tour 206 (Mexico). Currently the only way this can be accomplished is if for someone to press the Copy Base Cities link and then to manually enter in all the prices for each departure city.

Milanka would like to have the option to simply mirror our tour 206 (Mexico) prices instantly without going through this entire process – as we have a lot of specials that go to mexico. Can you please help us.

![image](https://cloud.githubusercontent.com/assets/10079829/10109922/0c799732-6398-11e5-85d8-a354952e49b7.png)

Thank you!

Ronen

**Comment by bradatkins** [comment]
How else would the DB know what the prices are? I'm confused.

**Comment by ronenreinheimer** [comment]
Hi Brad,

The same exact way the normal addons work – except we need the option to select normal addons or Mexico addons (like a default addons for mexico only) - so we don’t have to mirror the cities every time we create a special to mexico and then have to manually add in the prices for every addon city – it is extremely time consuming. Does this make sense? I know this sounds confusing, can we talk about on skype or phone?

We really need your help wi th this issue.

God Bless,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com>
