### ISSUE TITLE
Same tour # on same date 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#605]
DB same Tour # on Same Date 2 X listed ? 

![db](https://cloud.githubusercontent.com/assets/14838466/10112013/14f19f6e-63a6-11e5-98af-631e5e179d86.jpg)

**Comment by bradatkins** [comment]
Can you take a screenshot of the whole page please

**Comment by ali206** [comment]
![image](https://cloud.githubusercontent.com/assets/8440903/13472734/30f69ede-e084-11e5-96aa-4e8cf71f0386.png)

**Comment by bradatkins** [comment]
For whatever reason, there was 2 departures created for the same dates...
