### ISSUE TITLE
URGENT - Big Client DB issue

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#606]
Hi Brad,

We have an issue with the DB and it is one of the biggest clients that we have Mathew Kelly.

DB Code: DC030116

Here is an email from one of our workers:

Ronen,

I was trying to help Melissa add a 3rd option for transfers for tour #DC030116. As you will see a circle appears on the first option. Once selected the person registering can’t deselect that option.  We tried having all options (single, double & transfers under the same heading, but the same thing happened). 

Is there a possibility that Brad needs to make a change to the database to allow more than 2 option selections?

![image](https://cloud.githubusercontent.com/assets/10079829/10197365/376eef20-6765-11e5-9329-76dbf973326e.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/10548137/b8540334-7406-11e5-82f6-d9bcf69b867a.png)
