### ISSUE TITLE
Database was charging credit card fee on the top of credit card fee.

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#613]
#421046
Transaction ID of voided payment of amount $37531.08 from Merchant

131015A15-80FA958A-B819-46FF-8983-4957609689B4

from DB -Trans.  ID 
131015B39-AD2AD0D2-DF0A-4001-9DCA-08E6E23F5A43

AMEX credit card

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/10501907/4a5c2e2c-72b4-11e5-9f99-4017d68c8566.png)
