### ISSUE TITLE
Incomplete orders

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#615]
Incomplete orders still doesn’t quite work.  It will show the client on the Incomplete Orders Screen, when you pick it up to complete it, it brings up a different pax.  I have never had an incomplete order pick up with the correct client info.

 
 
![d](https://cloud.githubusercontent.com/assets/14838466/10638185/9d11b8f8-77d7-11e5-8b83-e977b7b0fd10.png)

**Comment by Irena206** [comment]
![p](https://cloud.githubusercontent.com/assets/14838466/10638214/c7542ace-77d7-11e5-9766-3699df79b6fa.png)

**Comment by bradatkins** [comment]
Try closing all your browser windows and doing it again then post back.

**Comment by Irena206** [comment]
Dear Irena, 

Closed all browser windows in both chrome and explorer and opened again, still brought up someone else’s registration info pre-built with Yolly’s email address though she did appear in the drop down this time.  

Pulled her down and all seems to be here except Billing/shipping fields, passport country of issuance and expiry.

![1](https://cloud.githubusercontent.com/assets/14838466/10642448/bc0bb38a-77eb-11e5-9106-fcf76ac3d415.png)



![2](https://cloud.githubusercontent.com/assets/14838466/10642456/c2f816ca-77eb-11e5-88bf-d5c12dfc795b.png)
