### ISSUE TITLE
Single Supplement issue

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#617]
This is an ongoing problem – database will not allow me to price single about 1k

Please let me know if you have any questions. God Bless!

________________________________________
 	Chris Wright 

 

I am unable to increase the single supplement on this departure beyong 999.99

Serious error in need of quick fix – please tell brad

Please let me know if you have any questions. God Bless!

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/10776249/15006d6a-7ce6-11e5-8d9f-38d7f7eae0fa.png)
