### ISSUE TITLE
DB errors , calculating wrong 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#619]
When you get a chance take a look , please . 

#419535:
Not calculating in cancelled person 
Actual Trip Costs : $2099 x  19 + 1529 + 1529 = $42939
Paid:                           $39832.52
Remaining Bal.:      $3106.48

#418715
PIF, database not calculating in cancelled person.

#419170
Database originally had Business class incorrectly listed as 1750 instead of 1850. When it updated it updated the pricing. 
So they are PIF, are you able to change/show that?

#418101
Not calculating discount of $150
& commission/discount need to be applied to absorb remaining balance as per email (from Stef)

#420595 
The database is showing this person still owes $177,  but with the discount (?) he only owes $27? 

$5960-$5783 = $177 - $150 = $27

**Comment by bradatkins** [comment]
419535 seems to be OK now

418715 seems to be OK now; however, it won't be PIF based on the payments / refunds

419170 - You'll need to give them a manual discount of $200 if you want to adjust the balance.

418101 - I do not see a commission on this order (there's no Agent attached)

420595  - Seems to be OK now
