### ISSUE TITLE
DB - place add-on "OZ" 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#621]
![1](https://cloud.githubusercontent.com/assets/14838466/11183960/be395e94-8c42-11e5-8112-bea6868c930a.png)

**Comment by bradatkins** [comment]
Do you know what the correct one is? I

**Comment by Irena206** [comment]
Invoice was made by customer, so I'm not 100% sure, but I'm assuming NY. address and price is from NY.

**Comment by Irena206** [comment]
Also , when you get a chance you can take a look on some problems below this one,
