### ISSUE TITLE
New Look - (new register - passwords don't match)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#629]
Hi Brad,
 
When you register as a new client and the passwords do not match, can you keep the client on the same page? Currently it is going to 2nd SS below:

![image](https://cloud.githubusercontent.com/assets/10079829/11482628/e3dc3b1e-9771-11e5-8bbe-f7a47735897f.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11482641/f1e4c6cc-9771-11e5-972c-ca73c24e9bde.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/11483023/11641974-9774-11e5-882c-8ca0eee15531.png)

**Comment by ronenreinheimer** [comment]
Awesome!!

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
