### ISSUE TITLE
New Look - (retaining email address of client)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#630]
Hi Brad,

If a client puts in the wrong password, can you please retain their email address (2nd SS)? So they don’t have to reenter it?

![image](https://cloud.githubusercontent.com/assets/10079829/11482850/1ea9edc6-9773-11e5-9bf8-0d423cf4eedb.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11482859/29e3d9ae-9773-11e5-9262-d58a15b61cd7.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/11483149/eadcd650-9774-11e5-9f5b-68b91133dd70.png)

**Comment by ronenreinheimer** [comment]
AWESOME!!


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
