### ISSUE TITLE
New Look - Capitalizing Client Name

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#631]
Hi Brad,

if a client registers and doesn't capitalize their name, can you please have the DB automatically do it for them?

![image](https://cloud.githubusercontent.com/assets/10079829/11483412/3064ec66-9776-11e5-8a26-d7f37dc4a6df.png)

**Comment by bradatkins** [comment]
Hey -

I'd prefer not too, as different names have different capitalization. For Example, Robert dePietro...

**Comment by ronenreinheimer** [comment]
OK – but no need to mention the worst goalie in Islanders history lol

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
