### ISSUE TITLE
New Look - Initial Testing - Remove Clergy Names

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#632]
Hi Brad,

Can you please remove Clergy Names from regular registration. Can you also please put the rest in the following order:

Mr.
Mrs.
Ms.
Miss
Dr.

![image](https://cloud.githubusercontent.com/assets/10079829/11483546/e658756a-9776-11e5-81e5-3bac7b3a5b15.png)

**Comment by bradatkins** [comment]
I will wait until we go live to do this, because the existing DB only has 1 field for both clergy & non-clergy titles.

**Comment by ronenreinheimer** [comment]
ok

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
