### ISSUE TITLE
New Look - Initial Testing - Review & Comments Section 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#634]
Hi Brad,

I am making a very simply booking and when i review - View Special Requests & Comments - it shows 
Dec 31, for some reason

https://www.206tours.com/register/payment.php

![image](https://cloud.githubusercontent.com/assets/10079829/11485020/839f8126-977f-11e5-8cfa-1e7c248f46d5.png)

**Comment by bradatkins** [comment]
Did you have any special requests or no?

**Comment by ronenreinheimer** [comment]
no

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed. Did the order go through OK otherwise?

**Comment by ronenreinheimer** [comment]
I don’t see it:

[cid:image002.png@01D12C2A.AC5909E0]

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
What time did you place the order? approximately

**Comment by bradatkins** [comment]
And did you get to the order confirmation page?

**Comment by ronenreinheimer** [comment]
Around the time I sent the github.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
no Sir

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
I just got one.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Ah I'm guessing it's cause of this issue:

https://github.com/206Tours/DB/issues/635

Let's close this one as it's specifically for the comments section
