### ISSUE TITLE
New Look - Initial Testing - Confirm Order Button goes to Purchase Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#635]
Hi Brad,

I attempted to place a very simple order. when i pressed the confirm button, it took me back 2 pages

from here:
https://www.206tours.com/register/payment.php

to here:
https://www.206tours.com/register/purchase_new.php

![image](https://cloud.githubusercontent.com/assets/10079829/11485402/fd73c89e-9780-11e5-8c6d-c4ef37ff6af9.png)

it goes here:

![image](https://cloud.githubusercontent.com/assets/10079829/11485503/7f626658-9781-11e5-9b45-351c9de7b06e.png)

**Comment by bradatkins** [comment]
Can you try again? I just completed one OK

![image](https://cloud.githubusercontent.com/assets/8440255/11506704/b61e7cac-981e-11e5-89e2-2d3d4b239675.png)

**Comment by ronenreinheimer** [comment]
certainly

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
I tried it on IE browser and when I press the confirm button, nothing happens.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK please try in Chrome too.

**Comment by ronenreinheimer** [comment]
It worked on chrome

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
