### ISSUE TITLE
New Look - Initial Testing - Review Page Empty Space

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#637]
hi Brad,

i am placing another test order. on the review page there is some empty space:

![image](https://cloud.githubusercontent.com/assets/10079829/11507464/21449bda-9822-11e5-9644-7ad6f4216ba6.png)

**Comment by bradatkins** [comment]
I forgot to show the subtotal and total. THere will still be a blank space as I have to reserve some space for some fields ...

![image](https://cloud.githubusercontent.com/assets/8440255/11514932/196f0fb8-9849-11e5-8772-d1ffd1a47549.png)

**Comment by ronenreinheimer** [comment]
OK, I had to stop testing to do a project for Milanka, as soon as I am done ill go back to testing.


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
