### ISSUE TITLE
When I look at Registered Passengers pages 

### ISSUE THREAD

**Issue by milanka206** [206Tours/DB#638]
When I look at Registered Passengers pages  going through all 2015 bookings - If I put in the 2015 (where date is) there are 10 pages showing on the bottom, but I'm only able to access 1st page bookings in January 2015...
I get nothing when I click on page 2

**Comment by bradatkins** [comment]
For this, you need to use what's called a wildcard, like this:

2015%

Then it'll work for all pages

**Comment by milanka206** [comment]
Sorry I do not get it?

Thanks and have a great day,

Milanka Lachman
www.206tours.com<http://www.206tours.com>



On Dec 1, 2015, at 8:15 PM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


For this, you need to use what's called a wildcard, like this:

2015%

Then it'll work for all pages

**Comment by bradatkins** [comment]
Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/8440255/11520612/13aec526-9873-11e5-906b-f7ed556a5c00.png)

**Comment by milanka206** [comment]
Got it. Thanks Brad!

Thanks and have a great day,

Milanka Lachman
www.206tours.com<http://www.206tours.com>



On Dec 1, 2015, at 9:32 PM, bradatkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a screenshot:

[image]<https://cloud.githubusercontent.com/assets/8440255/11520612/13aec526-9873-11e5-906b-f7ed556a5c00.png>
