### ISSUE TITLE
Search fields not lining up correctly in All Dept.

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#64]
First search box should be over Tour #
![image](https://cloud.githubusercontent.com/assets/8440903/4448028/b7d8cbf2-480f-11e4-96b7-d9d1fc663e2d.png)

**Comment by bradatkins** [comment]
Now they are:

![image](https://cloud.githubusercontent.com/assets/8440255/6653345/d4354794-ca64-11e4-9889-4341fede8983.png)
