### ISSUE TITLE
Amadeus - DB  421159 - showing itinerary multiple times 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#642]
![order 421159](https://cloud.githubusercontent.com/assets/8495740/11572616/33d4a9b6-99d0-11e5-8c36-a5dfda971610.jpg)

**Comment by bradatkins** [comment]
Yes, this will happen. Note the far right column "Active" Y or N.

**Comment by rinda206** [comment]
yes I did indeed notice this. :-)
