### ISSUE TITLE
Amadeus - DB  405516 - Class of service not matching 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#643]
![order 405516](https://cloud.githubusercontent.com/assets/8495740/11573766/0468a352-99d6-11e5-89be-a4cdd4ed8d45.jpg)

**Comment by bradatkins** [comment]
The Order # in your GH subject doesn't seem to match the one in your screenshot? Which one is correct, please let me know

**Comment by rinda206** [comment]
420559 - WOW that was so off weird. 

Sorry about that

**Comment by bradatkins** [comment]
One last thing, your Amadeus screen shows Elizabeth Doris Miles, but the DB for that order shows 4 people with the last name of Patrick.

I'm confused :)

**Comment by rinda206** [comment]
Me too . Ignore this please
