### ISSUE TITLE
Amadeus - DB 421486 - Return date showing first than departure date 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#644]
![order 421486](https://cloud.githubusercontent.com/assets/8495740/11574038/5fe86068-99d7-11e5-9f30-25eac49dd935.jpg)

**Comment by bradatkins** [comment]
This is "okay", just as long as we are collecting the data. I'll work on the sort order etc when we publish it.

**Comment by rinda206** [comment]
ok thanks
