### ISSUE TITLE
New Look - Initial Testing - DB still thinks I am booked on pilgrimage (but order was cancelled in the DB)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#646]
Hi Brad,

I cancelled myself out of this tour, but when i log back in, it still thinks that i am booked on it:

![image](https://cloud.githubusercontent.com/assets/10079829/11644361/548ef002-9d19-11e5-858a-69dd07e914ed.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11644363/5b323518-9d19-11e5-9e9c-02a5c6d531b9.png)

**Comment by bradatkins** [comment]
The DB goes on the Order status:

![image](https://cloud.githubusercontent.com/assets/8440255/11644414/e00f5d42-9d19-11e5-96ea-e27f0ca18c83.png)

**Comment by ronenreinheimer** [comment]
I was registered as ronen3 reinheimer3

Email: ronen3@206tours.com<mailto:ronen3@206tours.com>

This is the order # 421471

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
421471 is set at "New Request" too...not Cancelled.

**Comment by ronenreinheimer** [comment]
I’ll locate that one and cancel it.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
What do I press to change this status?

[cid:image001.jpg@01D13127.3D2D4E80]



Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
i've cancelled it for you

**Comment by ronenreinheimer** [comment]
OK thx, let me try to login again.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
