### ISSUE TITLE
New Look - Initial Testing - Phone Number Section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#647]
Hi Brad,

you can't enter in the phone number:

![image](https://cloud.githubusercontent.com/assets/10079829/11644584/4118cc08-9d1b-11e5-92be-ef7db3c768aa.png)

**Comment by bradatkins** [comment]
Seems to work OK for me.

Are you testing in IE or Chrome?

![image](https://cloud.githubusercontent.com/assets/8440255/11644651/e3cac8ca-9d1b-11e5-81b3-6d2282035231.png)

**Comment by ronenreinheimer** [comment]
All the testing I am doing now is in Chrome.

Are you on PC or MAC?



Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
PC

**Comment by ronenreinheimer** [comment]
It is so strange, when I log in with Ronen3 that field is blank, but when I log in with Ronen2 is shows these characters preloaded into the text box:

[cid:image004.jpg@01D13128.E967EC90]

[cid:image005.jpg@01D13128.E967EC90]



Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Must be from the initial sign up:

[cid:image001.jpg@01D1319E.0FE31870]

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK, continue with the rest of your tests for now.

**Comment by ronenreinheimer** [comment]
Yes Sir

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
This popup came up for some reason?

[cid:image001.jpg@01D1319F.ECC8AAB0]

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Your picture did not show up. But I did put a popup in there last night because I was too tired and didn't want to lose track of where I was :)

**Comment by ronenreinheimer** [comment]
No problem, I kind of got that feeling. how is hockey season going for the boys?


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed
