### ISSUE TITLE
New Look - Initial Testing - 2nd Passenger Dept Airport Missing

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#648]
when i select airport for passenger #2 i dont get the option to select departure airport:

![image](https://cloud.githubusercontent.com/assets/10079829/11658944/9c87af6e-9d93-11e5-91e0-baa2e0d01573.png)

**Comment by bradatkins** [comment]
Ya I saw that last night. It's on my to-do, thanks!

**Comment by ronenreinheimer** [comment]
Is it OK if I just keep GH stuff for you? I don’t want to give you a headache.


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Keep putting in new ones, it's easier for me to manage. If you run into
something, keep going and I'll eventually fix it. If it stops that
particular test, move onto the next scenario if possible.

**Comment by ronenreinheimer** [comment]
Brad,

I know this is a side issue, and I saw that you disabled the slideshow code on the home page (thank you). I am not sure if you have to charge Milanka for it, but she is freaking out about iphone and ipad – how they display our website. Personally I am not a mac guy at all – but I can’t deny that so many people have their product and truth be told their web browser sucks badly. Even if you have to charge Milanka, can you diagnose this issue so that Safari browser shows the website the same as android & desktop computers?


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
OK

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed
