### ISSUE TITLE
New Look - Initial Testing - was able to proceed without entering 2nd passenger address

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#649]
by mistake i forgot to enter in 2nd passenger address and the DB allowed me to continue with the booking.

![image](https://cloud.githubusercontent.com/assets/10079829/11658988/ed9dcf6e-9d93-11e5-8aa8-5fe7bf9a9c41.png)

**Comment by ronenreinheimer** [comment]
Why did you reopen this?

I put this in GH by mistake.


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Oh, I thought you closed it by mistake? :) You can close it

**Comment by ronenreinheimer** [comment]
LOL

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
