### ISSUE TITLE
Cleaning up All Dept.

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#65]
All Pre Pre & Pre Tour items should be one after the other so they are near each other....same with post tour & post post Tours. Right now they are all over the place.

![image](https://cloud.githubusercontent.com/assets/8440903/4448059/f6e884a4-480f-11e4-8693-c5dc15205281.png)

**Comment by bradatkins** [comment]
I've cleaned up the pre/post tour stuff:

![image](https://cloud.githubusercontent.com/assets/8440255/7826938/e30a9800-03ee-11e5-8416-77b22125739e.png)

**Comment by ali206** [comment]
By cleaned up you mean remove? I don't see them anymore

**Comment by bradatkins** [comment]
Correct
