### ISSUE TITLE
New Look - Initial Testing - back button passenger information was not retained

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#650]
when i pressed the back buttons to edit passenger information, both passengers info was not retained

![image](https://cloud.githubusercontent.com/assets/10079829/11659055/3d24b5fc-9d94-11e5-9d4e-8e7f1aea9286.png)

**Comment by bradatkins** [comment]
Did you press the button on the screen or the browser back button?

**Comment by ronenreinheimer** [comment]
Always screen button.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
the address was not retained:

![image](https://cloud.githubusercontent.com/assets/10079829/11790727/492d964e-a26b-11e5-9c25-50bc0fdb1600.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/11800183/2c43cb60-a2a8-11e5-91e6-34bf97420fb1.png)

**Comment by ronenreinheimer** [comment]
i selected New York, but then it reverted back to Alaska:

![image](https://cloud.githubusercontent.com/assets/10079829/11821437/809a6a22-a337-11e5-93c3-d17dcbf0bf1d.png)
