### ISSUE TITLE
New Look - Initial Testing (Book 1 PAX without airfare) code flood

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#651]
Hi Brad,

I tried to make a booking without airfare and i see all this code. you are probably working on something?

![image](https://cloud.githubusercontent.com/assets/10079829/11719450/de4bcb56-9f28-11e5-8933-1e20e1318ade.png)

**Comment by bradatkins** [comment]
Yes. As mentioned previously Just ignore those types of things.

Brad

**Comment by ronenreinheimer** [comment]
OK!

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
DB tests really nice in Chrome.


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
