### ISSUE TITLE
New Look - Initial Testing - Book 1 PAX with travel insurance

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#652]
I only selected travel insurance – but the DB added Cancel Protection

![image](https://cloud.githubusercontent.com/assets/10079829/11720198/3ee6311a-9f2c-11e5-931e-b926cd161ff5.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/11768915/39d1ad56-a1a9-11e5-9861-e767d61b37ad.png)

**Comment by ronenreinheimer** [comment]
I ran test again and it added cancel protection again. i used land only option.

![image](https://cloud.githubusercontent.com/assets/10079829/11853222/ae9b1240-a40a-11e5-900e-2da3142f3f41.png)
