### ISSUE TITLE
Promotion in DB - order of listing of promotion . 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#653]
HI Brad,

Are you able to put promotions  in order the promotions are offered. This way we always view the latest promotion status first.  

MERCY 
CYBER
THANKS

Etc. 

https://www.206tours.com/register/admin/reports_promo.php

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/11767997/22031258-a18d-11e5-8801-81de1b18ab5f.png)

**Comment by rinda206** [comment]
Hi Brad,

The Christmas one did not run yet that is last year. Can DB be set up to do in order the had the Promo's offered ( perhaps by validity date ? )

**Comment by bradatkins** [comment]
It's sorting it by the start date. If you're reusing the Code year over year, the DB will not know:

![image](https://cloud.githubusercontent.com/assets/8440255/11800272/014eae6a-a2a9-11e5-9229-8fa8ca7f2e8a.png)
