### ISSUE TITLE
New Look - Initial Testing - Book 2 or more PAX with pre/post stays 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#654]
Hi Brad,

I was booking 2 pax with pre & post stays. for pax 1 i selected no airfare with 2 night pre stay. then i selected airfare for pax 2 with 5 night post stay. when i went to press the continue button the website asked me to select the # of post stay nights for pax 1 (this option was not selected)

![image](https://cloud.githubusercontent.com/assets/10079829/11725651/ba527626-9f48-11e5-82db-598d8fc5f255.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11725810/93e96e12-9f49-11e5-8500-d9038f658b7b.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
DB is asking me to select # of nights for a selection that i did not choose.

![image](https://cloud.githubusercontent.com/assets/10079829/11785769/443b1126-a251-11e5-89fe-ed1b208c4c3c.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
I ran another test. I was able to place the order, but it did not reflect correctly in the invoice.

It was placed for land only 2x and 1 night post stay 2x 

![image](https://cloud.githubusercontent.com/assets/10079829/12020770/d5dc1808-ad4d-11e5-979e-73f4fd2c82ae.png)

**Comment by ronenreinheimer** [comment]
it is working with Land Only but It seems to have issues with Air & Land.

**Comment by bradatkins** [comment]
I just placed order #421768  and it seemed to work ok with Air & Land?

**Comment by ronenreinheimer** [comment]
I’ll test it again.

Why are these dates different?

[cid:image001.png@01D142F9.5C133E70]

We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
It worked. But I don’t know why the dates are different. I’ll GH it.

[cid:image001.png@01D142FA.A63CE180]

We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Good question, please log it as a seperate GH issue.
