### ISSUE TITLE
New Look - Initial Testing - Book 2 or more PAX with pre/post stays

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#655]
i ran the same test again and i selected land only option and 1 night pre stay and then i told the DB to match options for pax 2 from pax 1. when i pressed the continue button, it only showed pre stay for pax 1: I still confirmed the order to see what would happen and i got email and no PDF was attached to the order.

![image](https://cloud.githubusercontent.com/assets/10079829/11726684/d1f526fc-9f4d-11e5-9e40-d11ea00bbf18.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/11767813/3bb8a726-a188-11e5-80bb-c5c2a6342729.png)

**Comment by ronenreinheimer** [comment]
I’ll run this test again.


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/11785368/7ce2e802-a24f-11e5-851b-ec442ba1c3c7.png)

i tried to clear the selected options and it would not let me do it.
