### ISSUE TITLE
New Look - Initial Testing - Express Checkout

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#659]
error in invoice - Land Only appearing in Departure City Column. I selected Philadelphia as departure city.

![image](https://cloud.githubusercontent.com/assets/10079829/11784611/433e750c-a24b-11e5-9fc9-223f85e83596.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/11799517/d2bd8766-a2a2-11e5-8414-ea6cf25d003a.png)
