### ISSUE TITLE
Honor Orig. pricing - changing from Land Only to Air + Land

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#66]
Hi Brad, 

#1. Can you not close an issue until i've checked it out after your response please? I keep having to ask you another question about the same issue or it's not actually fixed. 

#2. As per previous issue, the way you explained we had to do that has a few unnecessary steps that just waste time. 

Can you break down the honor orig. pricing by "Travel Arrangements" so it's not so general? If it applies separately to Air + Land and then Land Only we wouldn't have to do those additional steps you mentioned.  The pricing should just change to the orig. cost of the new travel arrangements being selected.

**Comment by bradatkins** [comment]
Originally when we put in the Honor Original pricing, it was pretty rigid. It either honored the original pricing on an order or not.

Sometimes this doesn't make sense though, for example when changing Travel Arrangements from AIR & LAND to LAND only or vis-versa.

Now the DB will always update the pricing when they switch travel arrangements.

![image](https://cloud.githubusercontent.com/assets/8440255/8026708/390ff8e8-0d50-11e5-9000-406d41029f88.png)

![image](https://cloud.githubusercontent.com/assets/8440255/8026710/3d02bdd2-0d50-11e5-8280-3ae63e140a94.png)
