### ISSUE TITLE
New Look - Initial Testing - Select Title

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#662]
I was able to continue to next page without selecting a title:

![image](https://cloud.githubusercontent.com/assets/10079829/11853129/22e0d0e6-a40a-11e5-928f-95133dade643.png)

**Comment by bradatkins** [comment]
Makes sense, I think Ineed to remove the Star, as Title isn't mandatory.

**Comment by bradatkins** [comment]
Title isn't a required field, I've removed the red asterics

![image](https://cloud.githubusercontent.com/assets/8440255/11860383/48043b0a-a442-11e5-91bd-e70d398ca294.png)

**Comment by ronenreinheimer** [comment]
OK, please do that.

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
TY

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
