### ISSUE TITLE
New Look - Initial Testing - Book 1 PAX with travel insurance (selecting passengers)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#663]
Hi Brad, I was able to select Travel Insurance without applying it to any passenger (and was able to submit order), can you please force end user to select passenger(s) or they have to unselect the option. does this make sense? maybe if there is only 1 passenger, the end user should not have to select any passengers?

![image](https://cloud.githubusercontent.com/assets/10079829/11853435/e579281e-a40b-11e5-9eb0-8e8ba328a659.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11853398/aeebae70-a40b-11e5-95f2-cc808cd89103.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
it is still adding cancel protection plan to order
![image](https://cloud.githubusercontent.com/assets/10079829/11906916/058c6ede-a59e-11e5-9526-da45b6c95de4.png)

**Comment by ronenreinheimer** [comment]
is it going to add insurance to all passengers?

**Comment by bradatkins** [comment]
OK fixed it for real this time I'm pretty sure. Please test 
![image](https://cloud.githubusercontent.com/assets/8440255/11911118/2f221fba-a5d9-11e5-801d-7ca85e2e5b7d.png)

**Comment by ronenreinheimer** [comment]
I ran another test and it looks correct!

We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
