### ISSUE TITLE
New Look - Initial Testing - Client Account Already Exisits

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#665]
Hi Brad,

If  a client is already in our system (determined by the email they use) can the DB block them from registering more than once?

![image](https://cloud.githubusercontent.com/assets/10079829/11881717/722385be-a4d6-11e5-8901-8dc4b03640b2.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/11888520/6d1aed42-a50c-11e5-89be-255a152ac801.png)

**Comment by ronenreinheimer** [comment]
n1!

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Now I can’t log in:

[cid:image001.jpg@01D13980.C37D7030]

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
checking

**Comment by ronenreinheimer** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY!!

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>




From: Brad Atkins [mailto:brad@youreshop.com]
Sent: Friday, December 18, 2015 11:14 AM
To: Ronen Reinheimer <ronen@206tours.com>
Cc: 206Tours/DB <reply@reply.github.com>; 206Tours/DB <DB@noreply.github.com>
Subject: Re: URGENT!!!

Fixed

On Fri, Dec 18, 2015 at 10:43 AM, Ronen Reinheimer <ronen@206tours.com<mailto:ronen@206tours.com>> wrote:
Now I can’t log in:

[cid:image003.jpg@01D13985.FB9E1550]

Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
