### ISSUE TITLE
New Look - Initial Testing - Flight Bags (for Land Only clients)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#666]
Hi Brad,

Currently if someone selects Land Only, they will not see the option to select flight bags - however, every client gets a flight bag regardless if they purchase land only or with airfare. so we need this option showing at all times:

![image](https://cloud.githubusercontent.com/assets/10079829/11902753/2cb509c4-a582-11e5-95da-2a5b175e50a1.png)

**Comment by bradatkins** [comment]
Should it be called something else if it's Land Only? Complimentary Tour
Bag or something?

**Comment by ronenreinheimer** [comment]
I don’t think so, but we can check with Sandy (she is currently out of the office)


Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done, but it looks a little confusing calling it a complimentary flight bag when I selected land only

![image](https://cloud.githubusercontent.com/assets/8440255/12053410/d48b44d4-aee6-11e5-8bba-6f9f43c3e71a.png)

**Comment by ronenreinheimer** [comment]
I understand, but every pilgrim gets a flight bag regardless of L/O or A&L


We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
