### ISSUE TITLE
New Look - Initial Testing - Can't Place Order or Advance to Next Page

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#671]
Hi Brad,

I noticed that on 2 occasions today i was not able to place an order or advance to the next page. Is it because you are currently working on the DB or is it something else? the website remains in a loading phase. Now, other workers are telling me the DB is not loading for them.

![image](https://cloud.githubusercontent.com/assets/10079829/12053843/0908d20e-aeeb-11e5-9450-d9fd5a2ae40f.png)

**Comment by bradatkins** [comment]
Hey...somethings going on with the server itself...I'm checking into it...

**Comment by ronenreinheimer** [comment]
OK, thank you Brad

We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK things seem to have come back to normal...

**Comment by ronenreinheimer** [comment]
OK, I’ll keep you posted.

We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
