### ISSUE TITLE
New Look - Initial Testing - 2 different Departure Dates for same pilgrimage (2 PAX)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#672]
![image](https://cloud.githubusercontent.com/assets/10079829/12054139/70113556-aeee-11e5-9439-7a618284d2b0.png)

**Comment by bradatkins** [comment]
Partially messed up because the end date for the option is the 19th:

![image](https://cloud.githubusercontent.com/assets/8440255/12054366/0d385b28-aef1-11e5-8338-3da1eeb92df2.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12054524/3e15dfbc-aef2-11e5-8716-416c8f295373.png)

**Comment by ronenreinheimer** [comment]
I see, but the end date is correct – right?


We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Gr8, I’ll run another test.


We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
