### ISSUE TITLE
New Look - Initial Testing - Multi Passengers (Same as Contact Info check box)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#675]
Hi Brad,

if passenger #1 is using this check box, the DB should automatically eliminate this option for the rest of the passengers (when signing up) because i clicked it by mistake and it messed up the signup. does this make sense?

![image](https://cloud.githubusercontent.com/assets/10079829/12057691/ab9c6b9a-af11-11e5-9b92-ca1de05f179e.png)

**Comment by bradatkins** [comment]
I understand what you are saying, but not sure what you mean that it messed up your signup?

I think the option can remain, but if it's breaking on the second Pax I'd like to figure out why.

**Comment by ronenreinheimer** [comment]
It did have some kind of effect. I will do it again and make notes.



We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
