### ISSUE TITLE
New Look - Initial Testing - Pre / Post Tour - book now button + both pre and post tour added to same order

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#676]
Hi Brad,

When I completed the order, i only saw 1 book now button - for both the pre and post tour (1st SS). i selected the post tour, but it selected both the pre and post tours (2nd SS).

![image](https://cloud.githubusercontent.com/assets/10079829/12066439/ecf7df76-afb5-11e5-8067-b05addcc524d.png)

2nd SS:

![image](https://cloud.githubusercontent.com/assets/10079829/12066431/d86b8936-afb5-11e5-8d7e-bb46fce53849.png)

**Comment by bradatkins** [comment]
There can only be one book now because if a PAX wants to go on both a pre and post tour.

What tour they are on is determined by the checkbox

**Comment by ronenreinheimer** [comment]
That’s fine, but I only selected the post tour, but the DB added the pre tour as well.


We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Ahh ok. That is wrong

**Comment by ronenreinheimer** [comment]
I just ran another test and I was able to select a pre tour and continue without selecting any kind of payment method!



We Wish you a Blessed Christmas and a Happy New Year!

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Yes, because it's not required at this point...you still have to check with Sandy on it.

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12067535/27b38efe-afc9-11e5-8cc2-6fa71a617c7f.png)
