### ISSUE TITLE
New Look - Initial Testing - Order Issue - Melissa

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#677]
Hi Brad,

I am working with Melissa on this order.
1.  The DB thinks that it was booked via the customer, but it was placed by Melissa over the phone:

![image](https://cloud.githubusercontent.com/assets/10079829/12099098/606d7894-b2f4-11e5-9951-dad3de1e5316.png)
1.  In the DB, you can see that passenger #2 is Erwin Orlanes, but that info did not reflect in the invoice. it should also say male and not female.

![image](https://cloud.githubusercontent.com/assets/10079829/12099225/0a20cfda-b2f5-11e5-8ac6-def76095a90e.png)
1.    2nd PAX DOB is also reflecting 1st PAX:

![image](https://cloud.githubusercontent.com/assets/10079829/12099657/d55d9794-b2f7-11e5-8f17-4cfec7ee8567.png)

i will also try to rebook this from scratch

**Comment by bradatkins** [comment]
Fixed
