### ISSUE TITLE
New Look - Initial Testing - Sammie - customer comes up a 0 passengers

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#678]
check email for attached VIDEO.

(these are screen shots that Sammie took)

Sammie tried to book 2 passengers but it comes up as 0 passengers:

![image](https://cloud.githubusercontent.com/assets/10079829/12099406/3e2b43a4-b2f6-11e5-8f92-621a09344a9f.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12099425/68b00c5e-b2f6-11e5-976e-26c6c736d72c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12099434/770bb866-b2f6-11e5-963f-f8ec178134f8.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12099439/8310784a-b2f6-11e5-8905-89933e5c8f92.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12099465/b29d19ce-b2f6-11e5-9eb3-f3beb39ac5af.png)

**Comment by bradatkins** [comment]
Fixed
