### ISSUE TITLE
New Look - Initial Testing - Order Issue - Melissa  (replication attempt #1)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#679]
Hi Brad,

I was walking through the process with Melissa.

1. she said that i cant book as new client unless we delete existing client. so i proceed with existing client.

2. i selected with airfare, but the dropdown menu for airports did not show up:
![image](https://cloud.githubusercontent.com/assets/10079829/12099828/fcb5de04-b2f8-11e5-82be-c30a1a42ea2e.png)

3. i continued but i never got the option to select departure airport.

4. terms came up on the top of the review page, and the terms section was blank:

![image](https://cloud.githubusercontent.com/assets/10079829/12099850/304554d4-b2f9-11e5-90d7-3574122c447c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12099859/38b1517c-b2f9-11e5-9fa3-c158e593a646.png)

5. because i could not select the airport page, i did not attempt to book this order again from scratch.

**Comment by bradatkins** [comment]
Fixed
