### ISSUE TITLE
Reservation Options Not Showing:

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#681]
Hi Brad,
 
I noticed not all passengers are getting the same kind of options here. Is it just that we are assuming the arrangements selected for PAX 2 is going to be the same for PAX 1?
 
 
 
To	Subject	Sent	Size	Categories	
'Brad Atkins'	 Reservation Options Not Showing 	10:23 AM	142 KB

**Comment by bradatkins** [comment]
Fixed.
