### ISSUE TITLE
New Look - Initial Testing - Alaska

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#682]
Hi Brad,

I know i mentioned this to you before, but the DB is always defaulting back to Alaska. Even after a booking was made.

![image](https://cloud.githubusercontent.com/assets/10079829/12122440/0696356c-b3a9-11e5-8a69-d02d2af17cbe.png)

**Comment by bradatkins** [comment]
When you say defaulting back, I'm not sure what you mean?

Where are you at in the process...how do I replicate this error?

**Comment by ronenreinheimer** [comment]
i believe if you are pressing the back button or if client is already in the system it will always default to Alaska.

![image](https://cloud.githubusercontent.com/assets/10079829/12275633/264fad0c-b93f-11e5-9128-8617ac31f5c3.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/12647322/978c8282-c5a2-11e5-98d2-e25065dca69d.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
n1

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
i am going to close for now :)
