### ISSUE TITLE
New Look - Initial Testing - Passenger #2 - auto-filling with Passenger #1 Info

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#683]
Hi Brad,

when our CSRs are adding an additional passenger to a booking, the 2nd passenger info should be blank? right now it is auto filling with passenger #1 info.

![image](https://cloud.githubusercontent.com/assets/10079829/12122523/998108fc-b3a9-11e5-8d23-452b1c754184.png)

**Comment by bradatkins** [comment]
Fixed
