### ISSUE TITLE
New Look - Initial Testing - DB missing PAX 1 and thinks that PAX 2 is PAX 1 (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#684]
Hi Brad,

sorry to sound confusing. but we did a test to book 2 passengers on DB CODE: FK052016

after we entered in 2 passengers, on the following page, PAX 1 was missing and the DB showed that PAX 2 was PAX 1:

![image](https://cloud.githubusercontent.com/assets/10079829/12122738/e806dbfe-b3aa-11e5-945a-b25a4f343a5f.png)

**Comment by bradatkins** [comment]
Fixed
