### ISSUE TITLE
New Look - Initial Testing - Email Invoice

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#686]
![image](https://cloud.githubusercontent.com/assets/10079829/12127142/879c8f48-b3c3-11e5-898c-04edc6ad90ed.png)

**Comment by bradatkins** [comment]
This is because the email was surpressed.

**Comment by ronenreinheimer** [comment]
it was an appriver / spam thing?

**Comment by ronenreinheimer** [comment]
i am going to close this issue for now.
