### ISSUE TITLE
Insurance issue in NEW Version 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#689]
This isn’t right or it’s not represented properly. Cancel Protection Plan is always $299.
 
![image](https://cloud.githubusercontent.com/assets/8495740/12147617/dd28d4fe-b467-11e5-972e-d9aa915926a2.png)

**Comment by bradatkins** [comment]
Interesting, not exactly sure why it's showing that? Can you reproduce the error? If so, please list the steps

![image](https://cloud.githubusercontent.com/assets/8440255/12149827/dcf5c846-b473-11e5-99db-d7cd03b161dc.png)

**Comment by rinda206** [comment]
![image](https://cloud.githubusercontent.com/assets/8495740/12156244/d8fe359c-b497-11e5-9602-5cc445c3730e.png)

**Comment by bradatkins** [comment]
Fixed
