### ISSUE TITLE
New Version State ( in address) Issue 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#690]
![image](https://cloud.githubusercontent.com/assets/8495740/12147886/66a90914-b469-11e5-9442-0594dda230b2.png)

**Comment by bradatkins** [comment]
OK I found the issue. You sure do like that back button eh? :)

I'll fix it shortly.

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Rinda said it is good now.
