### ISSUE TITLE
New Look - Initial Testing - Email Invoices not going out (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#692]
Hi Brad,

the orders that i placed, i am not getting email confirmations. Additionally our CSRs are trying to send them out, but i dont think the customers are getting them.

![image](https://cloud.githubusercontent.com/assets/10079829/12153775/c763bbee-b489-11e5-9564-c7e72e64cf85.png)

**Comment by bradatkins** [comment]
I just did a test with this order, seemed to work OK?

![image](https://cloud.githubusercontent.com/assets/8440255/12159473/7aebf836-b4b0-11e5-8afe-483068814f74.png)
