### ISSUE TITLE
New Look - Initial Testing - DB Account Manager not receiving order emails (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#693]
Hi Brad

Although tours have dedicated account managers, they are not receiving booking emails:

![image](https://cloud.githubusercontent.com/assets/10079829/12154824/c6853a44-b48f-11e5-95a2-39d141e96e43.png)

**Comment by bradatkins** [comment]
The DB only emails rok@206tours.com because it's a Series Tour.

**Comment by Sandra206** [comment]
yes but they are not getting any emails. So even if its one of my departures where i am assigned. I am not getting the emails either.

**Comment by Sandra206** [comment]
Brad it was us! it seems that we were blocking ourselves.

**Comment by ronenreinheimer** [comment]
Sandy is a genius, it was an appriver issue. i am closing this issue.
