### ISSUE TITLE
New Look - Initial Testing - Refer a Friend

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#694]
Hi Brad,

Rinda and Patrick said they tested it and it is not working correctly yet. If that is the case, they want to know if you can remove it for the time being?

![image](https://cloud.githubusercontent.com/assets/10079829/12155071/2e916800-b491-11e5-93b3-2f0395c2e673.png)

**Comment by bradatkins** [comment]
Ahh ok, so this isn't a DB issue...The new website isn't live yet, so let's leave it there, and you guys can work through that.
