### ISSUE TITLE
421814 - not updating 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#695]
![image](https://cloud.githubusercontent.com/assets/8495740/12155377/bf6cf4a6-b492-11e5-8b0a-1c336b5a71fa.png)

![image](https://cloud.githubusercontent.com/assets/8495740/12155386/cd10b4c6-b492-11e5-8cb1-b08aaa0a2bb9.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12159853/058eca38-b4b4-11e5-8cd6-bdb317f92d22.png)

**Comment by ronenreinheimer** [comment]
Rinda said it is good now.
