### ISSUE TITLE
New Look - Initial Testing - Swap Land Only and With Airfare

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#696]
Hi Brad,

When you have a minute, please swap these. Please place them in the following order:

Top: With Airfare
Bottom: Without Airfare (land only)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY!

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
