### ISSUE TITLE
Commissions not showing correctly

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#697]
The commission is not showing correctly.
Its showing under the 1 passenger when in fact its 504.90 for 4 passengers.

I think its best not to have the PRO/commission show in the passenger info column and just have an area for it above the payment section. 
That way its shown as a deduction from the total. (that is if the client is set up as paying us NET).
If the Client is EARNING the commission and paying us Gross it will Not be taken from the total.
![image](https://cloud.githubusercontent.com/assets/8440601/12201362/ee8550a2-b5f1-11e5-9258-519822221c0a.png)

**Comment by bradatkins** [comment]
I've moved it here:

![image](https://cloud.githubusercontent.com/assets/8440255/12312179/40a55c14-ba2b-11e5-81f1-982ac0a9bd2d.png)

**Comment by Sandra206** [comment]
Nice!

Do not hesitate to contact me regarding any questions!

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>
