### ISSUE TITLE
Promos - not able to be applied per person on booking

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#698]
For instance I have 5 passengers on 421945 
4 passengers are to receive the JOY2015 $200 discount and 1 passenger is to receive a Clergy discount of 10%
I can not find a place where i can apply the discounts per person. WHen i click the coupon icon in Orders and adjust the promo for the one person. It eliminates the promo for everyone.
![image](https://cloud.githubusercontent.com/assets/8440601/12201422/5a7d6560-b5f2-11e5-8e92-8edd3996e25c.png)

then when i added it back on. Instead of it giving $200 per person (5 people in the booking). It gave everyone 1000 dollars off
![image](https://cloud.githubusercontent.com/assets/8440601/12201443/7a83414a-b5f2-11e5-8dbc-cce5bfc46c52.png)

We should have the discounts applied under where payments are applied.

**Comment by bradatkins** [comment]
That is the right place, it was broken. Fixed.

However, no PAX on this order are Fr, Rev, Br, Sr, Dcn so the CLERGY discount won't apply even if you try. Put the proper title on one of them then try the CLERGY discount.

**Comment by ronenreinheimer** [comment]
Sandy said to close this issue.
