### ISSUE TITLE
New Look - Initial Testing - DB Glitch with email / customer (Liz / Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#699]
Hi Brad,

Liz was trying to add a customer to the DB as a group leader. Client was in the DB and Liz was trying to book her - when she attempted to book her, the DB could not find the email. When she tried to register the client again the DB said that the email is already in the system. It appears to be some sort of glitch. the Customer is Kay or Katherine Coleman and the email address is kay.coleman@gmail.com (sorry if this all sounds confusing)

![image](https://cloud.githubusercontent.com/assets/10079829/12201947/16da488e-b5f5-11e5-9721-8e8df5720199.png)

**Comment by bradatkins** [comment]
Did she type in the right email address and password?

**Comment by ronenreinheimer** [comment]
From LIZ:


Hi Ronen,

I did enter correct email address which is kay.coleman@gmail.com<mailto:kay.coleman@gmail.com> and 206tours as password.   I also tried with you and we had the result.


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Closing, hasn't happened since
