### ISSUE TITLE
New Look - Initial Testing - DB not retaining Year in DOB for returning client

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#701]
![image](https://cloud.githubusercontent.com/assets/10079829/12204582/fb5626ec-b602-11e5-8574-22ad393e6966.png)

**Comment by bradatkins** [comment]
Seems OK now. Can you retest?

![image](https://cloud.githubusercontent.com/assets/8440255/12304562/2c678074-b9fe-11e5-8060-c7d803a3aa31.png)

**Comment by ronenreinheimer** [comment]
I tried 4 of my accounts and they still missing year:

[cid:image001.jpg@01D14E0B.505FD6C0]

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
You'll have to go back and reinput the year then try a new order after

**Comment by ronenreinheimer** [comment]
ok

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
i am going to close this issue for now.
