### ISSUE TITLE
New Look - Initial Testing - Custom Tours need setting for STAY or TOUR

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#702]
Hi Brad,

For series tours i am able to tell the DB if the tour will have a pre / post Stay or Tour (1st SS):

![image](https://cloud.githubusercontent.com/assets/10079829/12204882/1fe60a5c-b605-11e5-99bc-6392d4da264c.png)

But for Custom Tours, i don't have this ability:
![image](https://cloud.githubusercontent.com/assets/10079829/12204896/412f6578-b605-11e5-959e-990d52f5e76f.png)

Furthermore, unlike series tours, we want custom tours to have the pre / post TOURS come up prior to payment process.

Thank you.

**Comment by bradatkins** [comment]
What tour # is this?

For this portion, please log a separate issue, that will have to be a separate enhancement as this is a major change that wasn't previously mentioned.

"Furthermore, unlike series tours, we want custom tours to have the pre / post TOURS come up prior to payment process."

**Comment by ronenreinheimer** [comment]
DB Code:
DV021416

Tour:
www.pilgrimages.com/allsaintsparish<http://www.pilgrimages.com/allsaintsparish>


Hi Brad,

I realize that this is a separate issue, but we have these options on a lot of specials (none series tours) and it will become an issue with a lot of bookings. I will log it as a separate issue.


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
THANK YOU!!!!!!


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Thank you so much Brad. I ran a quick test, can you add a clear options link here:

[cid:image001.jpg@01D14ED8.226175D0]

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
ya I'm wokring on that now. I noticed it wasn't there in scenarios

**Comment by ronenreinheimer** [comment]
n1!

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
