### ISSUE TITLE
New Look - Initial Testing - AUTOMATIC INVOICE - URGENT (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#703]
![image](https://cloud.githubusercontent.com/assets/10079829/12207020/580fc46a-b612-11e5-9c65-1e385fceb71b.png)

**Comment by bradatkins** [comment]
I don't see that happening?

![image](https://cloud.githubusercontent.com/assets/8440255/12304645/99ead1aa-b9fe-11e5-8643-a7022294cfc7.png)

**Comment by ronenreinheimer** [comment]
we are going to close this issue for now.
