### ISSUE TITLE
New Look - Initial Testing - Client information missing from Invoice

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#704]
![image](https://cloud.githubusercontent.com/assets/10079829/12207037/7d1c04f8-b612-11e5-8183-fcf600879358.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12207119/cb3f5b8a-b612-11e5-9211-5a89d8d474db.png)

**Comment by bradatkins** [comment]
Fixed, it was the apostrophe in St. Peter's that was causing a problem

**Comment by ronenreinheimer** [comment]
Ah ha, is that something I need to inform the office about?

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
No. I missed it on my side

**Comment by ronenreinheimer** [comment]
OK

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
