### ISSUE TITLE
New Look - Initial Testing - RM is no longer linking Amadeus to booking (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#705]
![image](https://cloud.githubusercontent.com/assets/10079829/12208886/b10e329e-b61d-11e5-920d-8e511998ca42.png)

**Comment by bradatkins** [comment]
I had turned off the link (but was still collecting data) when we were experiencing those performance issues. I don't think the issues were related to Amadeus, so I'll turn it back on and we'll keep an eye on performance.

**Comment by ronenreinheimer** [comment]
OK, I’ll FW the info to chris and sandy

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Hold off, I'm going to check some things

**Comment by ronenreinheimer** [comment]
ok

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
OK I've re-enabled the Amadeus stuff

**Comment by ronenreinheimer** [comment]
OK, I’ll FW

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
