### ISSUE TITLE
New Look - Initial Testing - Tour# 206 Mexico - Back button / Clear button (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#708]
Hi Brad,

Our CSR Sammie tried to book a client with the pre stay - but then had to remove the option and could not clear it. When she tried to go back a page, she was moved forward. 

![image](https://cloud.githubusercontent.com/assets/10079829/12240239/572a517e-b85a-11e5-932e-2079aef6821c.png)

**Comment by bradatkins** [comment]
I see the clear options here:

![image](https://cloud.githubusercontent.com/assets/8440255/12312080/47c17fba-ba2a-11e5-9e98-9bb09e4e9bea.png)

What order # is this? or tour #?

**Comment by ronenreinheimer** [comment]
Hi Brad, my mistake, this is for tour 206 (mexico)   www.206tours.com/tour206<http://www.206tours.com/tour206>


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed
