### ISSUE TITLE
New Look - Initial Testing - Auto-Filled wrong passport #  (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#709]
Hi Brad,

Stefanie booked an existing client - but the DB auto-filled the wrong passport #

![image](https://cloud.githubusercontent.com/assets/10079829/12243125/d4066b28-b86a-11e5-86e3-88d26d00f536.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
OK, I’ll FW

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Any update?

**Comment by ronenreinheimer** [comment]
she said it is working now.
