### ISSUE TITLE
DB - Departure City - US Virgin Islands  Missing?

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#711]
Hi Brad,

I think Virgin Islands is missing from this list?

![image](https://cloud.githubusercontent.com/assets/10079829/12244404/82b3019e-b871-11e5-828e-83f6eede2ad2.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12244416/88f08a0e-b871-11e5-9006-f7053ae51c3a.png)

**Comment by bradatkins** [comment]
Added "Virgin Islands"

**Comment by ronenreinheimer** [comment]
n1

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
