### ISSUE TITLE
New Look - Initial Testing - Invoice confirmation showing $0 (Amanda, Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#713]
![image](https://cloud.githubusercontent.com/assets/10079829/12275416/08b47b16-b93e-11e5-9cb7-a039dd051794.png)

**Comment by bradatkins** [comment]
What order # was this again?

**Comment by ronenreinheimer** [comment]
420980


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
from Liz

![image](https://cloud.githubusercontent.com/assets/10079829/12455843/37e152fa-bf6b-11e5-8702-55f461f29ec7.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12455829/2972c352-bf6b-11e5-8e4e-488b4e21df4c.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12938456/e6beed0c-cf81-11e5-95ac-16e49e33bd2a.png)

**Comment by ronenreinheimer** [comment]
they said it is good now.
