### ISSUE TITLE
New Look - Initial Testing - Passenger name missing on invoice (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#714]
![image](https://cloud.githubusercontent.com/assets/10079829/12329876/60484bdc-bab0-11e5-8b06-8bf9576cc7e9.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12329884/6a38132a-bab0-11e5-87b2-6943cc134f2f.png)

**Comment by bradatkins** [comment]
Fixed. I goofed up on my fix for the apostrophe.
