### ISSUE TITLE
New Look - Initial Testing - Traveller Name issues! (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#715]
![image](https://cloud.githubusercontent.com/assets/10079829/12330657/4403dd2a-bab4-11e5-92e7-dc307e4f5884.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12330664/4c023d50-bab4-11e5-876e-bf00a03e3260.png)

**Comment by bradatkins** [comment]
I just fixed this one like 20 minutes ago. It should be good. Duplicate.

**Comment by ronenreinheimer** [comment]
OK thanks.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
I told Sammie, but she showed me that in the DB it is still not correct?

[cid:image001.jpg@01D14EC3.EB0704B0]


[cid:image002.png@01D14EC3.EB0704B0]

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Sorry, I fixed the bug that made this happen. Sammie will have to fix the info.

**Comment by ronenreinheimer** [comment]
understood

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
