### ISSUE TITLE
New Look - Initial Testing - Adjustment of travel insurance & DB issue with add-on cost (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#717]
From Liz:

Hello,

1.	The passengers added post –tour to Medj online.  The travel insurance premium  should be as per TravelEx. Please let me know if I can adjust the premium accordingly by cancel it DB and adding it manually.
2.	Also when you look at the post-tour option on below invoice,  it mentions the post-tour to  Shroud of Turin and post –tour to Medj.  There is only one post tour which is to Medj.  I don’t know where post-tour to Turin came from.

On PDF invoice and blue sheet, everything is as should be.
![image](https://cloud.githubusercontent.com/assets/10079829/12355705/8e583264-bb6c-11e5-8db1-14b99e6685f5.png)

**Comment by bradatkins** [comment]
How much should the insurance be for?

**Comment by ronenreinheimer** [comment]
$244.00

**Comment by bradatkins** [comment]
#1 is fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12938397/6933eaae-cf81-11e5-9ae6-ab33bee88857.png)


#2 seems fixed.

**Comment by ronenreinheimer** [comment]
she said it is good
