### ISSUE TITLE
New Look - Initial Testing - Discrepancy between PDF and HTML invoice and wrong information (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#718]
PDF is correct but HTML has wrong info from a totally different tour:

![image](https://cloud.githubusercontent.com/assets/10079829/12357001/9d0545d4-bb73-11e5-935a-7278e29acd73.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12357004/a16d8e1a-bb73-11e5-9168-e310dd57a817.png)

**Comment by bradatkins** [comment]
It is actually "the same" except for the HTML invoice shows additional information.

Previously Ronen asked for a stay to show the "Lourdes" portion of it.

The PDF version of it only has the "Description" column, whereas the HTML one has both columns.

Obviously, there's some duplication in the naming, you may want to remove some of that in the future.

![image](https://cloud.githubusercontent.com/assets/8440255/12357896/99cebad0-bb78-11e5-8bb2-39f8d93a0cd6.png)

**Comment by ronenreinheimer** [comment]
(from Yaritza)

Dear Brad, 

It is not the same. The description of the post tour in the HTML version is for a completely different trip (KG081615). The price is the same.  Fr. Gillespie has nothing to do with trip RL091916. Is there a way you can make the information on HTML and PDF mirror each other?

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/12365545/7987da92-bba3-11e5-8d05-0f7b9ebba3c6.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
i asked Yaritza to check it.

**Comment by bradatkins** [comment]
Any update?

**Comment by ronenreinheimer** [comment]
i just emailed her again.

**Comment by ronenreinheimer** [comment]
she said it is good now!
