### ISSUE TITLE
Tour Departures getting switched to Inactive (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#719]
from Donna:

I don’t know if Brad is able to look into this, but there are constantly tours Melissa and other Rok Team members are finding listed as inactive randomly throughout the database. Anytime I enter in a date I always make sure to do it the exact same way each time and always list them active. 
Today, Melissa notified me that 2 of the departures for Tour 47 have been marked Inactive somehow, and we don’t know why this is happening?

Is this something he can look into? I don’t want to be blamed for entering tours and pricing incorrectly as I always double check my entries before I email that I am done entering them.

**Comment by bradatkins** [comment]
Example please?

**Comment by ronenreinheimer** [comment]
from Donna:

![image](https://cloud.githubusercontent.com/assets/10079829/12399802/1ad89ad8-bdea-11e5-80d7-cd0dc86f535c.png)

**Comment by bradatkins** [comment]
Really old, haven't heard of this since, so we must have fixed it. If not, please provide new example
