### ISSUE TITLE
Incorrect Land Only price (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#721]
Hi Brad,

this is the DB code: JP041816
this is the url: pilgrimages.com/frpoirot

![image](https://cloud.githubusercontent.com/assets/10079829/12397687/c117654a-bddc-11e5-8da5-410f5fa05066.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12397649/839a34f4-bddc-11e5-9371-b46fbe5b0f72.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12397655/88467af8-bddc-11e5-8281-90d86b78867a.png)

**Comment by bradatkins** [comment]
I'm confused, what does this have to do with the new look?

**Comment by ronenreinheimer** [comment]
I wasn’t sure if this error occurred because we are switched to the new look? if it has nothing to do with the layout, you want me to just describe the issue?

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Did Liz book this through the new look website or the old one?

**Comment by ronenreinheimer** [comment]
I spoke with Liz: Apparently this is an old issue dating back to sept – client made the booking – so I would say with the old format.

[cid:image001.jpg@01D151EB.15E3F380]

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Seems to be OK

![image](https://cloud.githubusercontent.com/assets/8440255/12938293/b528b3e2-cf7f-11e5-866f-efcde10f8bab.png)

**Comment by ronenreinheimer** [comment]
she said it is good now.
