### ISSUE TITLE
Wrong information on blue sheet - Pre Stay (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#722]
Hi Brad,

Invoice should say:
Dynamic Catholic : Pre Stay Tel Aviv Double Occupancy $155.00
Dynamic Catholic: Pre Stay Tel Aviv Private transfer $78.00

but it is showing information from a different tour:

![image](https://cloud.githubusercontent.com/assets/10079829/12398246/5991b476-bde0-11e5-8b94-fc428489f0d4.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12398228/4163f102-bde0-11e5-8d21-7134ca5f6b14.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12455538/199d353a-bf6a-11e5-967f-fb987acc7886.png)

**Comment by ronenreinheimer** [comment]
Thank you, I will let Donna know.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
