### ISSUE TITLE
New Look - Initial Testing - DB deducting discount twice - promo code (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#723]
https://www.206tours.com/register/copysource/invoice_html.php?OrderID=418977&TravelerID=26552&GENERATED=TRUE&BLUE_SHEET=Y

![image](https://cloud.githubusercontent.com/assets/10079829/12401087/2a2470b8-bdf2-11e5-9af7-fd03aca282eb.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12401071/03117674-bdf2-11e5-8d04-2d74a7c8896d.png)

**Comment by bradatkins** [comment]
This order was placed a while ago, and we did a change to move discounts from the passengers and add them as a payment.

I clicked on update in the order and it adjusted the pricing

**Comment by ronenreinheimer** [comment]
OK, I’ll let Rinda know.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
fixed TY!
