### ISSUE TITLE
New Look - Initial Testing - back button (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#724]
DB CODE:  BG110716

![image](https://cloud.githubusercontent.com/assets/10079829/12401789/b9fb9f0a-bdf6-11e5-8444-1cfd83269e12.png)

**Comment by bradatkins** [comment]
My guess on the post stay is they picked 5 nights (5 * 799 = 3196). This would impact the insurance value

![image](https://cloud.githubusercontent.com/assets/8440255/12455760/e33f32da-bf6a-11e5-8bb8-7bbad5a98db8.png)

I couldn't reproduce the $345 insurance or the back button placing the order. Can you?

**Comment by ronenreinheimer** [comment]
the client was not supposed to have the ability to select # of nights, so i changed that in the DB. we made one good booking, but we were not able to correct older ones. i am going to close it for now and lets see how it works moving forward.
