### ISSUE TITLE
New Look - Initial Testing - Data Base Not Calculating Correctly (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#726]
![image](https://cloud.githubusercontent.com/assets/10079829/12422273/0bd9cfca-be94-11e5-800a-00ff672586a6.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12422255/faae5de2-be93-11e5-8ec7-fdcc66bc2097.png)

**Comment by bradatkins** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/8440255/12456339/4b60370e-bf6d-11e5-927b-a9d175b27833.png)

![image](https://cloud.githubusercontent.com/assets/8440255/12456421/b4550e06-bf6d-11e5-94a4-d21b7d350fd6.png)

**Comment by ronenreinheimer** [comment]
Thank you Brad, I’ll let them know.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
