### ISSUE TITLE
New Look - Initial Testing - ACCOUNT PAGE - missing from personal information section

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#727]
Hi Brad,

it looks amazing. this section is missing?

DOB
Passport #

![image](https://cloud.githubusercontent.com/assets/10079829/12423121/eee58c34-be97-11e5-9907-d100ffdcd01d.png)

**Comment by bradatkins** [comment]
Those are not on the "Traveler" record, but on the order itself; hence would not show up there

**Comment by ronenreinheimer** [comment]
But if a client wants to update their passport info or they made an error in DOB, they should be able to fix it in that section?

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
They would change it under "My Orders" against an existing order.

**Comment by ronenreinheimer** [comment]
How much work would it take you to make it show up in the Personal Information Section?

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
