### ISSUE TITLE
New Look - Initial Testing - Discrepancy between PDF and HTML Insurance price (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#728]
![image](https://cloud.githubusercontent.com/assets/10079829/12424117/b279b9be-be9c-11e5-9ae0-b3f8b083973f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12424175/e5ac4f36-be9c-11e5-84e8-785b49d1f85c.png)

**Comment by bradatkins** [comment]
It's 280 on both now. Is that correct?

**Comment by ronenreinheimer** [comment]
i think so, let me tell Melissa.

TY!

**Comment by ronenreinheimer** [comment]
from Melissa:

Dear Ronen, 

                Thanks for following up but it still reflects different on the .pdf Blue Sheet and .pdf invoice.  The digital blue sheet (new look blue sheet) is correct but if I go to print it up the trip base, insurance, discounts all are incorrect.  I tried again to update it through edit order and through the order number.  Thank you for your help.

**Comment by bradatkins** [comment]
This is actually a bug in the PDF Blue Sheet, because of currency. It's correct in the HTML version of both the invoice and Blue Sheet.

$280 USD or 408.80 CAD

![image](https://cloud.githubusercontent.com/assets/8440255/12938088/38f57ec4-cf7d-11e5-9ace-812b1c42e344.png)

![image](https://cloud.githubusercontent.com/assets/8440255/12938089/3d2ed896-cf7d-11e5-9c20-f9700dbce9a1.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Here is a reply from Rinda:

All need to match :

This is in USD 
https://www.206tours.com/register/copysource/invoice_html.php?OrderID=422075&TravelerID=28925&GENERATED=TRUE&BLUE_SHEET=Y 


The PDF form of the invoice is apparently in CAD but in my eyes nothing listed anywhere that this is CAD .

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=422075&TravelerID=28925&GENERATED=TRUE&SHOW_COMMISSION= 

Cannot have CAD  and USD reflect on same invoice. Brad needs to fix this.

![image](https://cloud.githubusercontent.com/assets/10079829/12957025/d7a4c7d4-cff8-11e5-904e-0a7f257c94d1.png)

**Comment by ronenreinheimer** [comment]
also from Melissa:

I guess I am confused because it shows CAD and USD in the same invoice.

Totals (trip base insurance) represent CAD on the .pdf and on the bottom reflects payments in USD.

For rok reference I can print the html version.
