### ISSUE TITLE
DB Payment Error - 422071 (Shannon)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#729]
Hello,

Yesterday, Elizabeth Marchand (422071) made a payment towards her trip. The database is showing she paid $1040.00, but she was actually charged $1878.00. 

Please advise the client and make sure this is the amount they wanted to pay.

**Comment by ronenreinheimer** [comment]
from Yaritza:

![image](https://cloud.githubusercontent.com/assets/10079829/12425621/a9998f3e-bea3-11e5-9161-00db3b2d5dad.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12425710/1506c2fa-bea4-11e5-8a65-9cbdc2e65f81.png)

**Comment by bradatkins** [comment]
Really old, haven't heard of this since, so we must have fixed it. If not, please provide new example
