### ISSUE TITLE
Ins. for priests still shows as TG pricing

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#73]
416661 - after SD is applied ins. automatically adjusts to $103 which is TG pricing. 

We need it to show as per Travelex at $108.00.

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=416661&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Looks to be OK now... 
![image](https://cloud.githubusercontent.com/assets/8440255/5714850/898da8e6-9a9c-11e4-8528-b7dd2a087bda.png)

**Comment by ali206** [comment]
That's because i told everyone in the office not to accept insurance and to let us know when they book a priest so we can manually add the insurance as an add cost so it will show correctly:

![image](https://cloud.githubusercontent.com/assets/8440903/5722631/c8ed0ddc-9b0b-11e4-8b19-e7862ed53084.png)

It's not just the booking above, it's any priest that is booked.
