### ISSUE TITLE
New Look - Initial Testing - business class upgrade - during booking test

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#730]
hi brad,

i was doing a test with 2 PAX and saw this (but did not select business class upgrade):

![image](https://cloud.githubusercontent.com/assets/10079829/12424585/dad135e8-be9e-11e5-9962-c0672cd73924.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY
