### ISSUE TITLE
New Look - Initial Testing - DB / Reservation Error- Incorrect 'Deposit & Ins.' Calculations (shannon)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#731]
*2 screen shots

![image](https://cloud.githubusercontent.com/assets/10079829/12425871/d0f241ba-bea4-11e5-98c7-d8f8d051122a.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12425902/fc21b816-bea4-11e5-8173-ffc92ac5cad4.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY, i'll ask Shannon to test it.
