### ISSUE TITLE
New Look - Initial Testing - PAX #2 TYPO

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#732]
PAX#2 has a typo:  (please remove the letter a)

Room Type: aWith Roommate - 1 Bed

![image](https://cloud.githubusercontent.com/assets/10079829/12432829/94c97114-becb-11e5-8675-7b33fe22db83.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY!
