### ISSUE TITLE
New Look - Initial Testing - Middle Name Space

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#733]
![image](https://cloud.githubusercontent.com/assets/10079829/12432910/12fcf1aa-becc-11e5-96bc-314e0f13facb.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12456576/6e57f4b2-bf6e-11e5-8843-b25cd7463043.png)

**Comment by ronenreinheimer** [comment]
TY
