### ISSUE TITLE
New Look - Initial Testing - Price Discrepancy between UI and Reg Page  - URGENT!

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#734]
![image](https://cloud.githubusercontent.com/assets/10079829/12457142/07099ac4-bf71-11e5-87df-cd53fcfbef13.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12457136/fcfb6526-bf70-11e5-9d6c-40538eb9e748.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY
