### ISSUE TITLE
New Look - Initial Testing - Meal Selection in Flight Bag Section / Missing Credit Card information / Misc Errors? (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#735]
![image](https://cloud.githubusercontent.com/assets/10079829/12459326/2d0fcfbc-bf7c-11e5-9fea-84cd2784ee46.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12459330/32206e30-bf7c-11e5-8586-fdaddcdd31f2.png)

**Comment by bradatkins** [comment]
So something fishy is going on. Can you reproduce the meal request vs flight bag thing? They look properly for me.

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/12462944/01525184-bf8f-11e5-8736-587d8259134a.png)

**Comment by bradatkins** [comment]
What browser is he using?

**Comment by ronenreinheimer** [comment]
from Patrick:

I made a registration earlier today, and those issues did not arise during the process. So I am not sure it was a glitch that has since been fixed or what. What was on the Snapped-Images is the issues that were happening at the time (as you requested us to do.)

**Comment by ronenreinheimer** [comment]
Me too

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
