### ISSUE TITLE
Pax #2 Name Missing / Replaced with Pax #1 Name (Elise / Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#736]
![image](https://cloud.githubusercontent.com/assets/10079829/12460896/198d3486-bf84-11e5-8e57-de0a53ad8389.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12460902/1ee155fc-bf84-11e5-89c2-584e5b9e2cf8.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12462832/5a5c7a6c-bf8e-11e5-9de0-02fde92e4693.png)
