### ISSUE TITLE
Google Conversion Code

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#737]
Hi Brad,

I am working with Google to track our sales conversions. Can you please do the following:

1.	Modify this conversion code:

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1071248600;
var google_conversion_language = "en_US";
var google_conversion_format = "1";
var google_conversion_color = "ffffff";
var google_conversion_label = "d555CJKmpwEQ2Onn_gM";
var google_conversion_value = 1.00;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1071248600/?value=1.00&amp;currency_code=USD&amp;label=d555CJKmpwEQ2Onn_gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

a.	replace the value 1.00 with the variable for the order total (in both locations)
b.	place code before the closing of the body tag of the order confirmation page

If you need to communicate with Google’s Tech, let me know and I will arrange it for you.

![image](https://cloud.githubusercontent.com/assets/10079829/12462261/54333f8e-bf8b-11e5-8747-1b15424fbfe9.png)

**Comment by ronenreinheimer** [comment]
i tried to paste in the code, but GH is blocking it? please refer to the email i sent you:

![image](https://cloud.githubusercontent.com/assets/10079829/12462312/9778efc8-bf8b-11e5-9d36-2acd4e06141c.png)

**Comment by bradatkins** [comment]
Done. Order #422120

![image](https://cloud.githubusercontent.com/assets/8440255/12462780/0c6ce422-bf8e-11e5-93f6-2762e8b4c2f1.png)

**Comment by ronenreinheimer** [comment]
THANK YOU BRAD!!!

I’ll have the google tech review it.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
from google tech:

Hey Ronen,

Please check if the value is the same on line 270 of the screen shot as well.The end of the line is not a part of it.It should be 2000 there as well.You could use the tag assistant extension as well which is available in the chrome webstore.Just place a test order and analyze it using the 
Tag assistant.Please send me a screen shot as well for documentation purposes.
