### ISSUE TITLE
Incomplete Name lists (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#739]
![image](https://cloud.githubusercontent.com/assets/10079829/12490259/9f116a8c-c042-11e5-8379-ba16ed42a8da.png)

**Comment by bradatkins** [comment]
How do you get to this screen? I can't seem to remember.

ST040116

**Comment by ronenreinheimer** [comment]
[cid:image001.jpg@01D1550C.9DB88860]

[cid:image002.jpg@01D1550C.9DB88860]


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/12517338/27dd4850-c100-11e5-84f8-9711bc675667.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12517334/2201db76-c100-11e5-98ef-d1caabff39f9.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12572204/080e5636-c3b7-11e5-8533-8748dca3743a.png)

**Comment by ronenreinheimer** [comment]
Thank you Brad - Yaritza wants to know if all the groups have been fixed or just the one she showed you?

**Comment by bradatkins** [comment]
Should be all.

**Comment by ronenreinheimer** [comment]
TY!
