### ISSUE TITLE
New Look - Initial Testing - Post Tour Cost on Invoice not correct (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#741]
![image](https://cloud.githubusercontent.com/assets/10079829/12490381/4a46c500-c043-11e5-993f-3d5ef450b544.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12490406/62af0e72-c043-11e5-9d0f-b9c8eca0224c.png)

**Comment by bradatkins** [comment]
Ronen, can you reproduce this?

**Comment by ronenreinheimer** [comment]
I was told the client made the booking, but I will do a test on my end.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad,

i asked Liz to recreate the booking and to take SS of any issues. She said everything was correct until she looked at the invoice (attached)

![image](https://cloud.githubusercontent.com/assets/10079829/12491459/284e212c-c049-11e5-833a-6e4314a68b19.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Sorry to bother you, I updated information about this issue in GH. This is kind of urgent because this booking is part of a huge pilgrimage group and we don’t want to upset the clients that are booking with incorrect invoices.

Please see what you can do and let me know if I can help.


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I can't seem to reproduce this, see the email I sent you.

**Comment by ronenreinheimer** [comment]
from Liz:

Hi Brad,

Attached please find the confirmation invoice from yesterday that has incorrect cost of post-tour to Medjugorje and incorrect calculation of prices.
According to DB, passenger registered online and DB sent incorrect confirmation invoice to client automatically. 

If you have any questions please feel free to contact me.   

![image](https://cloud.githubusercontent.com/assets/10079829/12517618/98769f84-c101-11e5-8b0a-d436d8d13c4d.png)

**Comment by ronenreinheimer** [comment]
Liz sent you an updated reply. I put it in GH.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Can you reproduce it?

**Comment by ronenreinheimer** [comment]
we did a test and the price looks correct. i will close this issue for now.
