### ISSUE TITLE
New Look - Initial Testing - DB made an automatic duplicate booking (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#742]
![image](https://cloud.githubusercontent.com/assets/10079829/12492207/29e75b80-c04d-11e5-8319-7568f4256998.png)

**Comment by bradatkins** [comment]
She double clicked the confirm button on the last page. I was able to reproduce it:

![image](https://cloud.githubusercontent.com/assets/8440255/12500460/68d58d60-c081-11e5-86a7-39b99f5b5563.png)

**Comment by ronenreinheimer** [comment]
I see, anything we can do to prevent this issue?

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
