### ISSUE TITLE
New Look - Initial Testing - Purchase Page - Separator between Pax 1 and Pax 2

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#745]
www.206tours.com/ronen/booking/new/page2/pax2-seperator/

Hi Brad,

In order to seperate duplicate information between pax's please add this HR Rule between each additional pax that is added by client.

![image](https://cloud.githubusercontent.com/assets/10079829/12561139/8f9794fa-c36c-11e5-85b0-5348a565374a.png)

**Comment by bradatkins** [comment]
What HTML code do you want?

**Comment by ronenreinheimer** [comment]
try this:
<hr class="page-splits5" />

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
n1
