### ISSUE TITLE
DB Fedex Label Print Glitch (Chris / Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#746]
![image](https://cloud.githubusercontent.com/assets/10079829/12563013/02ad5c6e-c376-11e5-8de5-2f0ff21f8c9a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12563020/08b035e6-c376-11e5-8657-49548270abce.png)

**Comment by bradatkins** [comment]
I added some additional checks on the address for the state which should resolve this issue.

**Comment by ronenreinheimer** [comment]
from Chris:

It seems to have done something, but I think it generated the labels for all passengers, but – instead of showing them all so that I can print them – it compressed them into a zip file and didn’t give me the option to download it….

![image](https://cloud.githubusercontent.com/assets/10079829/12584753/fb41a39e-c416-11e5-8d67-6100afdd6110.png)

**Comment by ronenreinheimer** [comment]
From Chris:

Now it is auto-downloading the zip file, but the file is empty.

“Creating FedEx_Labels_Tour_MC030616.zip
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_419937.pdf to zip file
________________________________________
Problem generating FedEx label with OrderID: 419980
________________________________________
Error returned in processing transaction
Severity: ERROR
Source: ship
Code: 3058
Message: Recipient Postal code or routing code is required
LocalizedMessage: Recipient Postal code or routing code is required

Request
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fedex.com/ws/ship/v12"><SOAP-ENV:Body><ns1:ProcessShipmentRequest><ns1:WebAuthenticationDetail><ns1:UserCredential><ns1:Key>9emjLehGV2QvyoOq</ns1:Key><ns1:Password>clifie3HzgcJTRu8kjd5uV1uJ</ns1:Password></ns1:UserCredential></ns1:WebAuthenticationDetail><ns1:ClientDetail><ns1:AccountNumber>253858427</ns1:AccountNumber><ns1:MeterNumber>104671700</ns1:MeterNumber></ns1:ClientDetail><ns1:TransactionDetail/><ns1:Version><ns1:ServiceId>ship</ns1:ServiceId><ns1:Major>12</ns1:Major><ns1:Intermediate>1</ns1:Intermediate><ns1:Minor>0</ns1:Minor></ns1:Version><ns1:RequestedShipment><ns1:ShipTimestamp>2016-01-27T15:21:11-05:00</ns1:ShipTimestamp><ns1:DropoffType>REGULAR_PICKUP</ns1:DropoffType><ns1:ServiceType>GROUND_HOME_DELIVERY</ns1:ServiceType><ns1:PackagingType>YOUR_PACKAGING</ns1:PackagingType><ns1:Shipper><ns1:Contact><ns1:PersonName>206 Tours Series Department</ns1:PersonName><ns1:CompanyName>206 Tours Inc.</ns1:CompanyName><ns1:PhoneNumber>1-800-206-8687</ns1:PhoneNumber></ns1:Contact><ns1:Address><ns1:StreetLines>333 Marcus Blvd</ns1:StreetLines><ns1:City>Hauppauge</ns1:City><ns1:StateOrProvinceCode>NY</ns1:StateOrProvinceCode><ns1:PostalCode>11788</ns1:PostalCode><ns1:CountryCode>US</ns1:CountryCode></ns1:Address></ns1:Shipper><ns1:Recipient><ns1:Contact><ns1:PersonName>Natalia Maher</ns1:PersonName><ns1:PhoneNumber>617) 259-8698</ns1:PhoneNumber></ns1:Contact><ns1:Address><ns1:StreetLines>182 Highland St</ns1:StreetLines><ns1:StreetLines></ns1:StreetLines><ns1:City>Holliston</ns1:City><ns1:StateOrProvinceCode>MA</ns1:StateOrProvinceCode><ns1:PostalCode></ns1:PostalCode><ns1:CountryCode>US</ns1:CountryCode><ns1:Residential>true</ns1:Residential></ns1:Address></ns1:Recipient><ns1:ShippingChargesPayment><ns1:PaymentType>SENDER</ns1:PaymentType><ns1:Payor><ns1:ResponsibleParty><ns1:AccountNumber>253858427</ns1:AccountNumber><ns1:Contact/><ns1:Address><ns1:CountryCode>US</ns1:CountryCode></ns1:Address></ns1:ResponsibleParty></ns1:Payor></ns1:ShippingChargesPayment><ns1:CustomsClearanceDetail><ns1:DutiesPayment><ns1:PaymentType>SENDER</ns1:PaymentType><ns1:Payor><ns1:ResponsibleParty><ns1:AccountNumber>253858427</ns1:AccountNumber><ns1:Contact/><ns1:Address><ns1:CountryCode>US</ns1:CountryCode></ns1:Address></ns1:ResponsibleParty></ns1:Payor></ns1:DutiesPayment><ns1:DocumentContent>DOCUMENTS_ONLY</ns1:DocumentContent><ns1:CustomsValue><ns1:Currency>USD</ns1:Currency><ns1:Amount>100</ns1:Amount></ns1:CustomsValue><ns1:Commodities><ns1:NumberOfPieces>1</ns1:NumberOfPieces><ns1:Description>Tour Details (Flight Tickets)</ns1:Description><ns1:CountryOfManufacture>US</ns1:CountryOfManufacture><ns1:Weight><ns1:Units>LB</ns1:Units><ns1:Value>1</ns1:Value></ns1:Weight><ns1:Quantity>1</ns1:Quantity><ns1:QuantityUnits>EA</ns1:QuantityUnits><ns1:UnitPrice><ns1:Currency>USD</ns1:Currency><ns1:Amount>0</ns1:Amount></ns1:UnitPrice></ns1:Commodities><ns1:ExportDetail><ns1:B13AFilingOption>NOT_REQUIRED</ns1:B13AFilingOption></ns1:ExportDetail></ns1:CustomsClearanceDetail><ns1:LabelSpecification><ns1:LabelFormatType>COMMON2D</ns1:LabelFormatType><ns1:ImageType>PDF</ns1:ImageType><ns1:LabelStockType>PAPER_8.5X11_TOP_HALF_LABEL</ns1:LabelStockType></ns1:LabelSpecification><ns1:RateRequestTypes>ACCOUNT</ns1:RateRequestTypes><ns1:PackageCount>1</ns1:PackageCount><ns1:RequestedPackageLineItems><ns1:SequenceNumber>1</ns1:SequenceNumber><ns1:GroupPackageCount>1</ns1:GroupPackageCount><ns1:Weight><ns1:Units>LB</ns1:Units><ns1:Value>1</ns1:Value></ns1:Weight><ns1:Dimensions><ns1:Length>108</ns1:Length><ns1:Width>5</ns1:Width><ns1:Height>5</ns1:Height><ns1:Units>IN</ns1:Units></ns1:Dimensions><ns1:CustomerReferences><ns1:CustomerReferenceType>CUSTOMER_REFERENCE</ns1:CustomerReferenceType><ns1:Value>Tour #MC030616</ns1:Value></ns1:CustomerReferences><ns1:CustomerReferences><ns1:CustomerReferenceType>INVOICE_NUMBER</ns1:CustomerReferenceType><ns1:Value/></ns1:CustomerReferences><ns1:SpecialServicesRequested/></ns1:RequestedPackageLineItems></ns1:RequestedShipment></ns1:ProcessShipmentRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
Response
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><env:Header xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/><soapenv:Body><v12:ProcessShipmentReply xmlns:v12="http://fedex.com/ws/ship/v12"><v12:HighestSeverity>ERROR</v12:HighestSeverity><v12:Notifications><v12:Severity>ERROR</v12:Severity><v12:Source>ship</v12:Source><v12:Code>3058</v12:Code><v12:Message>Recipient Postal code or routing code is required</v12:Message><v12:LocalizedMessage>Recipient Postal code or routing code is required</v12:LocalizedMessage></v12:Notifications><ns1:TransactionDetail xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fedex.com/ws/ship/v12"/><ns1:Version xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fedex.com/ws/ship/v12"><ns1:ServiceId>ship</ns1:ServiceId><ns1:Major>12</ns1:Major><ns1:Intermediate>1</ns1:Intermediate><ns1:Minor>0</ns1:Minor></ns1:Version></v12:ProcessShipmentReply></soapenv:Body></soapenv:Envelope>
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420140.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420184.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420226.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420270.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420277.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420514.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420568.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_420571.pdf to zip file
________________________________________
Fault

Code:Client
String:SOAP-ERROR: Encoding: string 'St. Mary\x92...' is not a valid utf-8 string
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_421548.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_421778.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_421852.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_421854.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_422066.pdf to zip file
________________________________________
adding /home/tours206/public_html/register/ labels/../labels/SHIP_LABEL_422128.pdf to zip file”

![image](https://cloud.githubusercontent.com/assets/10079829/12627189/8406d408-c50a-11e5-9d7d-0e1bd65bf698.png)
