### ISSUE TITLE
Tracking Fed Ex Packages (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#747]
![image](https://cloud.githubusercontent.com/assets/10079829/12564339/b088c5b6-c37c-11e5-80db-5b01f0c54468.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12564341/b4246d6a-c37c-11e5-856c-cc44c3c82cf3.png)

**Comment by bradatkins** [comment]
This shipping label was only created today:

![image](https://cloud.githubusercontent.com/assets/8440255/12570660/b981e8b6-c3a7-11e5-9d43-7e188369688b.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/12571087/6bdf2f20-c3ab-11e5-817f-66c29530dc30.png)

**Comment by ronenreinheimer** [comment]
from Patrick:

That “Tracking Number” is the only one showing in the file, and it was sent out last week (prior to the storm). I only sent one package to Cynthia. Below is an email from the client, on January 25th, noting that she received the package.

It was not sent “Same Day Delivery” – so could database be saving it in as the wrong dates? Or the wrong tracking number is being saved? 


From: Cecely Barneson [mailto:cecely@gmail.com] 
Sent: Monday, January 25, 2016 5:10 PM
To: Patrick McKenna <patrick@206tours.com>
Cc: Rinda Kanidinc <rinda@206tours.com>
Subject: Re: Updates: Transfers and Hotel Accommodations: Pilgrimage to the Holy Land with James Twyman

Hi Patrick,

To confirm, the package arrived.

Many thanks,

Cecely

**Comment by bradatkins** [comment]
Really old, haven't heard of this since, so we must have fixed it. If not, please provide new example
