### ISSUE TITLE
Invoice to reflect new dates if client selects pre / post stay or pre / post tour (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#748]
Hi Brad,

is it possible for the top of the invoice to reflect new dates if client selects pre or post options?

![image](https://cloud.githubusercontent.com/assets/10079829/12564998/5ad0e2a8-c380-11e5-95a1-90583f5e7825.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12565011/6d20a88a-c380-11e5-829b-cc8694e159de.png)

**Comment by bradatkins** [comment]
Not a bug. It was added as an "Addon cost" and not an option. The DB doesn't 'know' that it should change the dates. 

![image](https://cloud.githubusercontent.com/assets/8440255/12570533/643e49c2-c3a6-11e5-8795-cddee51116ad.png)

Here's an order where the option was added:

![image](https://cloud.githubusercontent.com/assets/8440255/12570540/6e0911f8-c3a6-11e5-8c02-c74f7c2c3aab.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Rinda wants to know if the invoice can reflect the change of dates in this area? Does that make sense?

![image](https://cloud.githubusercontent.com/assets/10079829/12584650/7e14bf50-c416-11e5-9dce-e2cf8ac35947.png)

**Comment by bradatkins** [comment]
Based on my above comments, no. The tour option was not applied correctly so it won't change any dates

**Comment by ronenreinheimer** [comment]
Hi Brad,

Rinda wants to know if the DB can adjust the tour dates on the fly if we manually enter in a pre or post tour for a client.

For example - A client books tour 98 (italy) which ends in Venice - now client contacts us and wants a post tour to Paris (which is not preset in the DB as a post tour for tour 98) so we manually create this post tour for the client. Can you have the DB change the tour dates to reflect that on the invoice?

did i explain this OK?

**Comment by bradatkins** [comment]
Yes it's possible. I'll mark it as an enhancement

**Comment by bradatkins** [comment]
Done:

![image](https://cloud.githubusercontent.com/assets/8440255/15695839/39afd90a-2779-11e6-9ab5-527db2ef7cba.png)
