### ISSUE TITLE
Clergy Discount problems

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#750]
Hi Brad, 
As you can see below, people are being registered with a clergy discount but it's applying the discount twice.  It's changing the subtotal (which it shouldn't) and then is applying it in the payments section as well.  

Can you please fix this problem? I fixed the booking below and another booking yesterday that I don't remember but if we don't catch this and there are more bookings out there we're potentially losing an additional 20% which is crazy.

![image](https://cloud.githubusercontent.com/assets/8440903/12583978/4a6f3b42-c413-11e5-8344-56a05c9305ac.png)

Thanks!

**Comment by bradatkins** [comment]
Closing, hasn't happened since
