### ISSUE TITLE
echeck option on USER side for payments

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#751]
Hi Brad,

Regular users do not have all these payment options. They only have credit card.
to get to this page i go to orders and click on the money icon.

Can you provide them with the option of Credit card and
echeck(ACH)

The Ach information should then get emailed over to accounting just like it does when the client makes the payment. 

![image](https://cloud.githubusercontent.com/assets/8440601/12591367/736ef42a-c435-11e5-9864-4675290e2e3d.png)

**Comment by bradatkins** [comment]
users have CC, ECHECK, CHECK/MONEY ORDER, Paypal.

I'm confused?

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/12600571/cb023f2a-c468-11e5-8ee7-3ff8078b4b47.png)

**Comment by Sandra206** [comment]
I mean admin so Users/206 Employees would be able to have that option.

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/13865906/d53f37b8-ec86-11e5-9eaa-4431312722a4.png)

**Comment by Sandra206** [comment]
Hi Brad,
We dont need Check or Money order or Wire you can take those two out. 
and for E check its showing confirmation. We need it to show Account and routing number - then when its submitted it needs to go to accounting.
