### ISSUE TITLE
Expired Tours - should be inactive and should not allow users to book them.

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#752]
![image](https://cloud.githubusercontent.com/assets/10079829/12595054/2c98fba6-c447-11e5-9d42-c4a12c563a64.png)

**Comment by bradatkins** [comment]
Rinda is not a "user". 206 Tours can book tours that are expired. This was previously requested.

**Comment by ronenreinheimer** [comment]
Hi Brad,

I spoke with Rinda and she saw your reply attachment email from the past - but she would like old / expired tours to disappear / not have the ability to book them for clients and all 206 Tours staff / users. Is that possible?

Ronen

**Comment by bradatkins** [comment]
I'll mark it as an enhancement for the future

**Comment by ronenreinheimer** [comment]
OK, thank you. I’ll tell Rinda.

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/15201518/b55e57e4-17bf-11e6-8a96-fde9f8286637.png)
