### ISSUE TITLE
New Look - Initial Testing - check box for same as previous passenger did not select bag type

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#754]
Hi Brad,

I ran a test and i selected a bag for PAX 1 and it didn't do the same for PAX 2

![image](https://cloud.githubusercontent.com/assets/10079829/12626243/b8f83792-c505-11e5-8c63-76de09629ba8.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
i tested it again and it did select the bag, but now it is not suppressing options for PAX #1. I'll log into GH as a separate issue.

![image](https://cloud.githubusercontent.com/assets/10079829/12652794/93755ce2-c5ba-11e5-82a8-a3fa51524287.png)
