### ISSUE TITLE
New Look - Initial Testing - After PAX #3 Airport Dropdown Menu is missing

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#755]
check video i FW to you.

![image](https://cloud.githubusercontent.com/assets/10079829/12628651/2c32c7f2-c512-11e5-8727-2cc5c79f4c45.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12628671/42e98242-c512-11e5-8f23-d7e88b7a8ce6.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
it looks like it is fixed, as a test i selected private rooms for all 3 pax but it didnt reflect correctly on the checkout page. i'll log as a separate issue in GH.

![image](https://cloud.githubusercontent.com/assets/10079829/12653328/0d072a02-c5bd-11e5-92f2-1bff5f65fe9c.png)
