### ISSUE TITLE
422075 - CAD payment showing incorrectly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#756]
Hi Brad, 

The payment made on the 18th is not showing correctly.

It was processed in Elavon as $1,360 CAD so it should be showing only as $1,360 CAD on the invoice, not $1,985.60 CAD right?  

I'm assuming that means the xchange rate etc is backwards?

It's wrong in Payments section also:
![image](https://cloud.githubusercontent.com/assets/8440903/12629672/db2f420e-c516-11e5-948c-7deab926cc64.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12629684/eeba3838-c516-11e5-9781-4ebc8ae66fd4.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12629616/a7c8bf58-c516-11e5-9d40-8ad0f58d0bcf.png)

**Comment by bradatkins** [comment]
That is correct:

1985.60 (CAD)  = 1360 (USD) x 1.46 (Ex Rt)

**Comment by ali206** [comment]
Just to reply here b/c i replied to the email last night...it's not correct.

$1,360 CAD was charged so in DB, it should show around $970 USD in the payments section and on the invoice remain as $1,360 CAD.

**Comment by ali206** [comment]
i know you're super busy but would like to get this issue resolved - any update?

**Comment by bradatkins** [comment]
I think you're getting confused.

Elavon only shows you the USD rate, that's why I have to do the conversion.

In this case, you charged then 1360, the DB calculates that to be 1985.60.

What's confusing you is the currency marker in Elavon.

Just to make it really clear, I *always* send Elavon the value to charge in USD.

**Comment by ali206** [comment]
Elavon is not only showing me the USD rate. 

Elavon is showing me the amount charged in that clients currency. 

The only time I know what was actually charged in USD is when I check the bank statement.  Maybe you're getting confused?

**Comment by bradatkins** [comment]
Apparently I am getting confused as per your last email :)

I'll re-read the docs...

**Comment by ali206** [comment]
Her January payment was $917.68 USD

**Comment by ali206** [comment]
im sending you an email about this woman - her invoice is super messed up

**Comment by bradatkins** [comment]
Have a look now

**Comment by ali206** [comment]
she was rebooked so i'm not sure what was done on her cxld invoice
