### ISSUE TITLE
421518 - CAD charge showing incorrectly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#757]
Hopefully i'm missing something or forgot how this works otherwise there's going to be a bunch of incorrect charges...

![image](https://cloud.githubusercontent.com/assets/8440903/12629793/680ed996-c517-11e5-9c1d-6d81186a746b.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12629837/9179a536-c517-11e5-8ccb-ea98a13d9691.png)

![image](https://cloud.githubusercontent.com/assets/8440903/12629809/75568bf8-c517-11e5-8a0e-ac000f3426d0.png)

**Comment by bradatkins** [comment]
That's correct

2846.48 = 2093.00 x 1.36

**Comment by ali206** [comment]
Replying here as well to keep track...

$2,093 CAD charged which should show in view payments around $1,490 USD in view payments. And on the invoice should remain as $2, 093.

**Comment by ali206** [comment]
Also I selected to view this invoice in USD and the #'s are not correct here either. 

$400 should be about $295 USD
and you already know about the $2,093:

![image](https://cloud.githubusercontent.com/assets/8440903/12648950/64f45dba-c5aa-11e5-86d9-e6514158a288.png)

**Comment by ali206** [comment]
This is a really big problem and we're lucky we caught this ahead of time because this guy would have left for his trip in 2 weeks paying only for half of his trip. 

Luckily we don't have many Int'l charges yet but this needs to be a priority for things that need to be fixed

**Comment by bradatkins** [comment]
I think this is the same as the ones from before...

**Comment by ali206** [comment]
?? they were never fixed though

**Comment by bradatkins** [comment]
Have a look now
