### ISSUE TITLE
422177 - ins and subtotals not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#758]
Hi Brad, 

Sammie went in to the booking and selected Yes for Travel Insurance for Darlene and it would not show on the invoice but added it to Arminda's subtotal. 

Since we could not fix this she manually added insurance for Darlene, but subtotals are still wrong. 

Can you please fix?

![image](https://cloud.githubusercontent.com/assets/8440903/12648871/f797060a-c5a9-11e5-9ada-323c4cce118b.png)

**Comment by ali206** [comment]
Anyway to fix this asap? Client keeps emailing to see if it's fixed yet

**Comment by bradatkins** [comment]
So only Darlene should have Travel Insurance, not Arminda?

**Comment by ali206** [comment]
Yes

**Comment by bradatkins** [comment]
Check now

**Comment by ali206** [comment]
thanks!
