### ISSUE TITLE
Issue with DB custom Insurance (WYD)

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#76]
Ronen was updating all the WYD pilgrimages with the WYD Terms, but after I press save it reverts back to our standard terms.

![ronen](https://cloud.githubusercontent.com/assets/8440903/4649380/0a7197c8-548a-11e4-91c0-81fec0ba9916.jpg)

**Comment by bradatkins** [comment]
Looks to be OK now:

![image](https://cloud.githubusercontent.com/assets/8440255/5714842/5bcaebd0-9a9c-11e4-86c2-21639f922810.png)

**Comment by ali206** [comment]
I asked Ronen to double check this and it's still not correct:

just fwded you his email from 1/13/15

**Comment by bradatkins** [comment]
Hey I do not have this email, can you resend?

**Comment by ali206** [comment]
Just resent
