### ISSUE TITLE
New Look - Initial Testing - Full Payment Amount - DB not calculating travel insurance properly (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#761]
![image](https://cloud.githubusercontent.com/assets/10079829/12651301/122432d6-c5b4-11e5-8125-6a25894f538f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12651320/20e08c16-c5b4-11e5-8ac3-bcd5668cf10b.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12938247/0bd988f2-cf7f-11e5-947a-a40eba4f7f31.png)


![image](https://cloud.githubusercontent.com/assets/8440255/12938248/0eda3006-cf7f-11e5-9aa1-910b5792c326.png)

**Comment by ronenreinheimer** [comment]
TY Brad, i'll ask Liz to test it.
