### ISSUE TITLE
New Look - Initial Testing - 3 Pax Test - Private Room Prices not reflecting on checkout page - BUT INVOICE LOOKS CORRECT (Ronen)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#762]
i tested 3 pax with private room - review page didnt show the prices and pax 2 it said undefined. but the good news the invoice looks correct.

![image](https://cloud.githubusercontent.com/assets/10079829/12653369/366661ec-c5bd-11e5-99de-2e4294db7ff8.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12653438/8f739340-c5bd-11e5-9c1f-c2ea6abbd53f.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by bradatkins** [comment]
Closing, hasn't happened since
