### ISSUE TITLE
URGENT - New Look - Initial Testing - need help with customer invoice (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#764]
![image](https://cloud.githubusercontent.com/assets/10079829/12720869/ec41ebd4-c8ca-11e5-81e6-a0de5891904c.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12720896/025f7c1a-c8cb-11e5-9b82-020483f553d0.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
i am going to close this issue for now.
