### ISSUE TITLE
New Look - Initial Testing - Submit Button Stuck? (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#765]
![image](https://cloud.githubusercontent.com/assets/10079829/12722161/9e097c78-c8d1-11e5-9c73-f8487bc047c8.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12722156/984db9ca-c8d1-11e5-8fc8-1870ac426da2.png)

**Comment by bradatkins** [comment]
I think we were having performance issues this day ...so it could be related, can you reproduce it?

**Comment by ronenreinheimer** [comment]
i am going to close this for now - lets see if it happens again - i think it is a glitch that comes and goes.
