### ISSUE TITLE
New Look - Initial Testing - DB not calculating insurance & deposit information correctly (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#767]
Hi Brad,

I think you had simliar issues, but i am not sure if this one is slightly different, so i am just going to log it anyway.

Stefanie is saying that with 2 PAX - it should be $400 x 2 + 308 x 2 = $1416

![image](https://cloud.githubusercontent.com/assets/10079829/12729044/c703897c-c8f2-11e5-9076-f905d24ab342.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
she said it was ok, going to close this issue.
