### ISSUE TITLE
DB sending emails to wrong account manager (Amanda / Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#768]
![image](https://cloud.githubusercontent.com/assets/10079829/12729854/c203b66e-c8f6-11e5-90e0-468911fa2df0.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12729818/983a8ec0-c8f6-11e5-9542-58284cab9d76.png)

**Comment by bradatkins** [comment]
It's sent to ROK because it's marked as SERIES tour as noted in your screenshot.
