### ISSUE TITLE
New Look - Initial Testing - DB Defaulting to Alaska

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#771]
workers are still emailing me about this issue.

![image](https://cloud.githubusercontent.com/assets/10079829/12756777/4324f9a4-c9a3-11e5-9fb4-2db9a3ab6bd3.png)

**Comment by bradatkins** [comment]
Is this a new pax or existing pax?

**Comment by bradatkins** [comment]
I can't seem to reproduce it...can you?

**Comment by ronenreinheimer** [comment]
the issues seems to be with existing clients?

**Comment by bradatkins** [comment]
Ok I was finally able to reproduce it. Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12937165/e14443e4-cf73-11e5-8819-fe3aa9f2a2a2.png)

**Comment by ronenreinheimer** [comment]
OK, super I’ll alert the office.


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
