### ISSUE TITLE
New Look - Initial Testing - Full Payment not Reflecting Insurance (Shannon)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#772]
1st SS
![image](https://cloud.githubusercontent.com/assets/10079829/12761725/26d0f624-c9ba-11e5-95d2-5e1e3837a6bb.png)

2nd SS

![image](https://cloud.githubusercontent.com/assets/10079829/12761731/2c1f5a12-c9ba-11e5-93e8-b9feb99434ea.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12770353/c27395fe-c9ed-11e5-9ab6-09f4f54bb7d6.png)

![image](https://cloud.githubusercontent.com/assets/8440255/12770355/c5049e3a-c9ed-11e5-9fdb-eb5aa331cf30.png)

**Comment by ronenreinheimer** [comment]
please see this GH entry:
New Look - Initial Testing - Inconsistency with insurance radio button (Ronen) #808
