### ISSUE TITLE
New Look - Initial Testing - Credit Card / Payment Information not coming up (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#774]
![image](https://cloud.githubusercontent.com/assets/10079829/12787536/cff516e6-ca63-11e5-82cd-3a88cd3d4c40.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12787553/de216cd8-ca63-11e5-89b4-ba52e78ef48d.png)

**Comment by bradatkins** [comment]
Can you get him to try again? It showed up for me today.

**Comment by ronenreinheimer** [comment]
I’ll ask him.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
he said it is ok.
