### ISSUE TITLE
URGENT ISSUE - Adding Passengers to Existing Order from Orders Page (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#775]
![image](https://cloud.githubusercontent.com/assets/10079829/12787739/b0367268-ca64-11e5-965a-7790c800ea06.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/12787862/2565365a-ca65-11e5-9a2b-00b854c0833c.png)

**Comment by bradatkins** [comment]
let me know if this is still happening, seems to be OK
