### ISSUE TITLE
New Look - Initial Testing - Account Section - Personal Information Section - states / title

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#777]
Hi Brad,

When i select title (mr.), it doesnt save it. The states drop down menu has a lot of additional information and doubling up of the same info.

1ss
![image](https://cloud.githubusercontent.com/assets/10079829/12794827/07756546-ca85-11e5-9bc0-c9c74d0085d7.png)

2ss
![image](https://cloud.githubusercontent.com/assets/10079829/12794788/d7972d1e-ca84-11e5-8eef-f4324aa9488f.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
