### ISSUE TITLE
421919 - discount was applied correctly but it didn't calculate in to invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#785]
![image](https://cloud.githubusercontent.com/assets/8440903/12828598/d43f063a-cb53-11e5-8610-783589e2f0a3.png)

**Comment by ali206** [comment]
Another example:
![image](https://cloud.githubusercontent.com/assets/8440903/12828727/6c573988-cb54-11e5-9882-b37af44dfe91.png)

**Comment by bradatkins** [comment]
Is it correct on the PDF invoice?

**Comment by ali206** [comment]
no

**Comment by bradatkins** [comment]
Both seem OK now
