### ISSUE TITLE
#422299 wrong passport exp date

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#787]
Im selecting as  July 2017, but on invoice is reflecting as Jun 30, 2017, and before was showing as Novem 30,2017. 

![11](https://cloud.githubusercontent.com/assets/14838466/12831194/f87ec06e-cb60-11e5-8a11-959379c38733.png)

![capture 22](https://cloud.githubusercontent.com/assets/14838466/12831224/2d6fe1a4-cb61-11e5-8f7e-ae713134171d.PNG)

**Comment by bradatkins** [comment]
You're not specifying a proper password expiry date, hence the DB is breaking. You specified Jul 2017
