### ISSUE TITLE
URGENT: Tr#208 not working 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#79]
If I go to existing client, type in James Flynn, click on shopping cart and then search by tour#208 which exists in All Tours and All Depts. nothing comes up as if the tour doesn't exist. 

I'm sending you the email from Melissa of all screenshots but this is just a reminder to fix it.

**Comment by bradatkins** [comment]
I can move them over if you want...

**Comment by ali206** [comment]
Move them meaning all clients on the wrong tor#208 can be moved to the correct tr#208 and then we can cxl the wrong Tr#208?

**Comment by ali206** [comment]
Rinda said this tour is actually no longer going so no need to transfer clients.  We will be cancelling their bookings anyway, thanks.
