### ISSUE TITLE
Credit Card Payment - DB did not ask to enter State? (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#793]
![image](https://cloud.githubusercontent.com/assets/10079829/12858031/8a874066-cc1b-11e5-804e-f053c14970b9.png)

**Comment by bradatkins** [comment]
Is this still a problem as it loaded OK for me?

![image](https://cloud.githubusercontent.com/assets/8440255/13164781/dbe9b672-d685-11e5-9b40-63cc53c12af7.png)
