### ISSUE TITLE
#422295 wrong amount is showing on invoice than actual went throught on Merchant 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#794]
MERCHANT - $4627 
000	534818	Settled	Credit Card	Sale	02/04/2016	12:43	Patricia	Shaughnessy	43**********3252
K	Z	M	4627.00

![capture222](https://cloud.githubusercontent.com/assets/14838466/12858169/754be9ee-cc1c-11e5-9a6d-3dc7f1ea0c38.PNG)

**Comment by bradatkins** [comment]
I think this was fixed as part of another fix. Let's close this and keep an eye out
