### ISSUE TITLE
New Look - Initial Testing - DB Deleting Random info from bookings (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#795]
![image](https://cloud.githubusercontent.com/assets/10079829/12920675/886d44ac-cf17-11e5-9b78-d6e5a12fce84.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12920742/cc98b5c6-cf17-11e5-89a1-c741626d8e4e.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/12936840/42c7d436-cf70-11e5-96e6-0cf0c9345683.png)

**Comment by ronenreinheimer** [comment]
he said it is good and will test it again. going to close it for now.
