### ISSUE TITLE
New Look - Initial Testing - Miscalculation in Order / Credit Card not processing payment correctly (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#797]
![image](https://cloud.githubusercontent.com/assets/10079829/12924451/279e504c-cf28-11e5-96f2-bcb94eced93a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12925552/ca292dce-cf2c-11e5-9471-bb2ce5a3919f.png)

**Comment by ronenreinheimer** [comment]
Donna said that the issue is that the Credit Card is not being processed correctly.

**Comment by ronenreinheimer** [comment]
from Donna:

The payment that went through on this clients card was more than I specified. 
FYI I put through payment on the new site for this invoice so I don’t know if it has anything to do with that?

**Comment by bradatkins** [comment]
I'm confused, I see the DB charging the correct amount:

![image](https://cloud.githubusercontent.com/assets/8440255/12937846/f04d3024-cf7a-11e5-8118-ef8fc79155cf.png)

**Comment by ronenreinheimer** [comment]
OK, I’ll show Donna.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
from Donna:

But irena said that $2727 was charged--- how could that have happened?

534818	Credit Card	Void	02/09/2016	11:53	Maria	Amezcua	48**********6922
K	2727.00

![image](https://cloud.githubusercontent.com/assets/10079829/12952146/744e9e86-cfe3-11e5-88ae-32ac853272a1.png)

**Comment by bradatkins** [comment]
I think this was fixed as part of another fix. Let's close this and keep an eye out

**Comment by ronenreinheimer** [comment]
OK

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
