### ISSUE TITLE
#419788  wrong math

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#798]
![capture 1](https://cloud.githubusercontent.com/assets/14838466/12926078/a3414158-cf2f-11e5-8fb0-857e30ec79b3.PNG)

**Comment by bradatkins** [comment]
It wasn't showing the processing fee:

![image](https://cloud.githubusercontent.com/assets/8440255/13164698/4f193d30-d685-11e5-8127-db935ee030c5.png)
