### ISSUE TITLE
New Look - Initial Testing - Order Not Confirming - has video (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#799]
Here is the video:
http://www.206tours.com/ronen/videos/booking-troubles.mp4

![image](https://cloud.githubusercontent.com/assets/10079829/12928577/354e4b2a-cf3c-11e5-90c5-892175e24c85.png)

**Comment by bradatkins** [comment]
K, I'm confused cause this video shows an order being confirmed?

**Comment by ronenreinheimer** [comment]
from Yaritza:

Yes, tell him to please watch from minute 2 and on, after I enter the credit card information and click on confirm, instead of providing me with a confirmation page it puts me back on that very same page where the payment information I had entered is no longer there.

**Comment by bradatkins** [comment]
Had this happen, fixed it...if it happens again let me know
