### ISSUE TITLE
URGENT: 420749 -- Math wrong and clients need invoice today

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#801]
There are no subtotals showing on the invoice first of all. 

Then if you open the pdf, the subtotal/total for pax # 1 is what should show for pax #2 and the math is wrong for pax #3 as well. 

Sammie just did all those add ons today and it messed everything up.

![image](https://cloud.githubusercontent.com/assets/8440903/12979252/dfeeb304-d0a3-11e5-98e9-acb3cf9f444d.png)

**Comment by bradatkins** [comment]
Checking...

**Comment by bradatkins** [comment]
I think it's fixed?

![image](https://cloud.githubusercontent.com/assets/8440255/12983193/2de7c476-d0b6-11e5-834d-2dd1d500442b.png)

**Comment by ali206** [comment]
Hi Brad, i didn't mean to switch the add ons for pax - just was saying the subtotals were showing in the wrong spot. 

As per Sammie, this is what invoice should look like:
![sammie](https://cloud.githubusercontent.com/assets/8440903/12984780/58f37e4c-d0bd-11e5-8e5f-ce9338351d77.jpg)

![sammie 2](https://cloud.githubusercontent.com/assets/8440903/12984795/77be0f68-d0bd-11e5-8b4a-ad9bebee4e0f.jpg)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
it's good now thanks!
