### ISSUE TITLE
419036 - can't open invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#803]
![image](https://cloud.githubusercontent.com/assets/8440903/12980187/42b39fb8-d0a9-11e5-9b6b-2e786322df81.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/12980358/24cbeab8-d0aa-11e5-9a1b-4a25a3cd0919.png)

**Comment by bradatkins** [comment]
Try again I was making some fixes.

**Comment by ronenreinheimer** [comment]
I was told it is ok now.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
