### ISSUE TITLE
414180 - commission re-applied but balance still showing in orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#804]
![image](https://cloud.githubusercontent.com/assets/8440903/12980721/c0f84f2a-d0ab-11e5-8e65-94a27e178ba9.png)
 
![image](https://cloud.githubusercontent.com/assets/8440903/12980781/f0f12044-d0ab-11e5-8db5-fa6e19238091.png)

**Comment by bradatkins** [comment]
Fixed. I had rolled this back previously as there was something wonky with the screen that Rinda posted. It's fixed now

If you see any orders that have an incorrect outstanding balance (and don't have any commission) let me know
