### ISSUE TITLE
Multiple Passengers showing up on invoice (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#805]
![image](https://cloud.githubusercontent.com/assets/10079829/12982797/6b4c7bce-d0b4-11e5-91bb-97ed2a5670fa.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12982794/6650fc4e-d0b4-11e5-9270-5f3d50f434c6.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
reply from Donna:

![image](https://cloud.githubusercontent.com/assets/10079829/13053144/ea8aca34-d3d0-11e5-80f3-3df53efd2234.png)

**Comment by bradatkins** [comment]
So only John should be on the invoice?

**Comment by ronenreinheimer** [comment]
reply from Donna:

Dear Ronen,

Who is John? I don’t even see a John on the invoice-

It should only be 1 pax named Livio Mazzocato and 1 passenger named Minke Mazzocato

**Comment by bradatkins** [comment]
You got me really confused

![image](https://cloud.githubusercontent.com/assets/8440255/13865714/c98bae12-ec84-11e5-888b-d2ad5313f00c.png)
