### ISSUE TITLE
Post Tour on invoice is showing 1 Night (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#806]
Hi Brad,

I don't know why the 1 night is showing up? I checked the post tour info in the DB and i set it that it nights can't be selected.

![image](https://cloud.githubusercontent.com/assets/10079829/12983327/d5741c94-d0b6-11e5-905f-e57eab1aee95.png)

**Comment by bradatkins** [comment]
It works fine on the new invoice, that functionality isn't enabled on the old invoices.

![image](https://cloud.githubusercontent.com/assets/8440255/12983843/1facf7c0-d0b9-11e5-92f9-44795e466159.png)

**Comment by ronenreinheimer** [comment]
OK, is there a way to replicate the invoice into the latest version?

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Unfortunately not.
