### ISSUE TITLE
Corrections to Invoice (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#807]
![image](https://cloud.githubusercontent.com/assets/10079829/12983523/9a409fac-d0b7-11e5-8169-5a4f5d69dc3b.png)
![image](https://cloud.githubusercontent.com/assets/10079829/12983585/d3bb07ea-d0b7-11e5-9ca1-05c6ee8d0a33.png)

**Comment by bradatkins** [comment]
Done the changes, except the "Please be aware..." portion as it didn't specify what she wants.

For the US Dollar note, it'd show:

All prices in CAD.

**Comment by ronenreinheimer** [comment]
OK, I’ll tell Sandy.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
from Sandy:

SS:
![image](https://cloud.githubusercontent.com/assets/10079829/12985428/901807fa-d0c0-11e5-88e6-97ca91fa5ba0.png)

TEXT:
For Payments you may:
• Log into your account: https://www.206tours.com/register/loginaccount.php
• Call our office and we gladly take the payment over the phone: 1-800-206-8687
• Mail payment to : 206 Tours ~ 333 Marcus Boulevard ~ Hauppauge , NY 11788
• All prices in US Dollars.
Terms and Conditions:
• Please be aware of our full terms & conditions as per: www.206tours.com/terms.
• Names on tickets must match names on passport (to avoid penalties or denied boarding).
• You can Expect final documents 3 to 4 weeks prior to departure.
• Valid passport & VISA are the sole responsibility of each passenger.

How to prepare for your journey:
For additional information about your destination and how to prepare for your trip please visit:http://www.pilgrimages.com/weible

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
I asked Sandy if it was good and she said:

[cid:image001.jpg@01D188DB.3C0A7A30]

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/14079832/bbe1f558-f4ce-11e5-8329-0e666d46ecf6.png)

**Comment by bradatkins** [comment]
looks OK?

![image](https://cloud.githubusercontent.com/assets/8440255/18809090/d5c1805a-8241-11e6-9a73-0475b27ff493.png)
