### ISSUE TITLE
New Look - Initial Testing - Inconsistency with insurance radio button (Ronen)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#808]
Hi Brad,

I was shown this by one of our CSRs. You can see if the insurance is checked the price remains the same and if deselected the price retains the insurance cost. It is basically unpredictable as the button is selected and deselected. Same thing happens with the cancel protection radio button.

(see video in email.)

![image](https://cloud.githubusercontent.com/assets/10079829/12991245/74a34810-d0dc-11e5-8456-f4c7564f2fd9.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12991259/7e01c300-d0dc-11e5-9419-d3d53b548eaa.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12991266/89605b30-d0dc-11e5-88ab-7e3080aa2c26.png)

![image](https://cloud.githubusercontent.com/assets/10079829/12991296/aa82b39e-d0dc-11e5-8487-b21ed7d067dc.png)

**Comment by bradatkins** [comment]
I've done some work on them, hopefully this will help stabilize them otherwise I'll have to rethink it.

**Comment by ronenreinheimer** [comment]
i was playing with it again and maybe we have to rethink this method?

**Comment by bradatkins** [comment]
I haven't heard of this in a bit with the work I did. Let me know
