### ISSUE TITLE
New Look - Initial Testing - Additional options price on invoice | HTML vs PDF (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#809]
![image](https://cloud.githubusercontent.com/assets/10079829/13013379/411298b0-d17d-11e5-8d32-92f851b08f8b.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13013367/2f01cf10-d17d-11e5-91d9-222bb1dcf718.png)

**Comment by bradatkins** [comment]
Fixed
