### ISSUE TITLE
URGENT URGENT URGENT:  Commission for Grp Leaders VS. individuals

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#81]
I think we're having an issue distinguishing in the DB btwn commissions. 

I told you that when I manually applied commission for individuals it was not showing on the invoice - which you corrected. 

However for Grp Leaders such as Jane Cihon (who wants things corrected immediately) - Commission should never post as a payment towards the clients booking when I approve it. I thought that was only for the grp leader's to see on their side or for the recaps.

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=414228&GENERATED=TRUE&SHOW_COMMISSION=Y  

Also, we cannot apply a $26 discount to this booking correctly - DB shows it as $0.00 and i'm assuming it's b/c the commission is pending??

![image](https://cloud.githubusercontent.com/assets/8440903/4744177/ddc4de48-5a2d-11e4-846c-50877b0b07e6.png)

HELP!

**Comment by bradatkins** [comment]
Looks OK now I think:

![image](https://cloud.githubusercontent.com/assets/8440255/5697629/2dab8e68-99c4-11e4-8e3b-e738176146ac.png)

![image](https://cloud.githubusercontent.com/assets/8440255/5697630/312618ce-99c4-11e4-9c66-c80e3bae2a22.png)

**Comment by ali206** [comment]
416969 - looks ok now, thanks

But for grp leaders i am still unable to approve pending commission payments in the DB b/c they show as actual payments on the invoice and then it looks like we owe them a refund:

![image](https://cloud.githubusercontent.com/assets/8440903/5704441/7860daf0-9a3f-11e4-8f09-b3b55a848b6f.png)
