### ISSUE TITLE
New Look - Initial Testing - Account Section - Refer A Friend

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#811]
Hi Brad,

I tried to refer myself with my personal email rrturbo6@gmail.com but i dont see the email.

![image](https://cloud.githubusercontent.com/assets/10079829/13015840/497f5c66-d189-11e5-8d7b-254e8a2c1108.png)

**Comment by bradatkins** [comment]
I just tested it with the new format and it worked OK. Try again
