### ISSUE TITLE
New Look - Initial Testing - Business Class Upgrade - Clear Options not working

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#812]
![image](https://cloud.githubusercontent.com/assets/10079829/13016004/34646e38-d18a-11e5-9e09-c00d20e0d1b1.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13016010/3bc663e8-d18a-11e5-81f4-c74dee2791f2.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY
