### ISSUE TITLE
New Look - Initial Testing - Passport # & Expiration Date not retaining when pressing back button

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#813]
1st SS
![image](https://cloud.githubusercontent.com/assets/10079829/13016179/30fe7e90-d18b-11e5-9e38-a8407dcd075c.png)

2nd SS
![image](https://cloud.githubusercontent.com/assets/10079829/13016197/44649104-d18b-11e5-99bd-510b3ae3bda8.png)

**Comment by bradatkins** [comment]
Hmm I tried to reproduce and couldn't. Are you pushing your browser back button or the button we put in? Can you reproduce it?

![image](https://cloud.githubusercontent.com/assets/8440255/13164247/c863dff0-d681-11e5-86c0-97b234cc3f8e.png)


![image](https://cloud.githubusercontent.com/assets/8440255/13164250/ccd54556-d681-11e5-9867-d43eac38b948.png)

**Comment by ronenreinheimer** [comment]
Here is  a quick video

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Really old, haven't heard of this since, so we must have fixed it. If not, please provide new example
