### ISSUE TITLE
New Look - Initial Testing - Invoice not calculating correctly (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#815]
![image](https://cloud.githubusercontent.com/assets/10079829/13018122/db559086-d195-11e5-8721-0885b4d69b28.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13018154/03fc83f0-d196-11e5-9919-01a9d3318a35.png)

**Comment by bradatkins** [comment]
Fixed. This was a bug that was around for a while. Glad that ones fixed

**Comment by ronenreinheimer** [comment]
cool

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
