### ISSUE TITLE
URGENT - Discrepancy between client and in-house invoice? (Sandy, Stef, Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#816]
![image](https://cloud.githubusercontent.com/assets/10079829/13020655/a902c23e-d1a4-11e5-8344-842b205fb685.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13020653/a4491482-d1a4-11e5-9e51-ffddbbe2b726.png)

**Comment by bradatkins** [comment]
Fixed
