### ISSUE TITLE
New Look - Initial Testing - client invoice coming up as $0 (Elise)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#817]
DB CODE:  CCSG100416

![image](https://cloud.githubusercontent.com/assets/10079829/13020912/fa808370-d1a5-11e5-9250-b0022b332d43.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13020931/1aba402c-d1a6-11e5-9920-0c34fddc6eb1.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13020941/2ae97ada-d1a6-11e5-8142-0012aad8a124.png)

**Comment by bradatkins** [comment]
This tour departure does not have a Land Only price...

![image](https://cloud.githubusercontent.com/assets/8440255/13023632/b756896a-d1b8-11e5-8471-e80dd4c78ab8.png)
