### ISSUE TITLE
What clients are seeing when they login to pay vs what we see on the invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#819]
this is probably why a lot of clients are overpaying:

![sammie](https://cloud.githubusercontent.com/assets/8440903/13021968/22697904-d1ac-11e5-8c85-646c46dc2e35.jpg)
![sammie 2 jpg](https://cloud.githubusercontent.com/assets/8440903/13021972/28041ee6-d1ac-11e5-8a50-41ac842665fa.png)

**Comment by bradatkins** [comment]
Fixed
