### ISSUE TITLE
Miscalculation at Payment pages (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#822]
![image](https://cloud.githubusercontent.com/assets/10079829/13054484/175c27d6-d3d8-11e5-9a5c-4e3151fb92f2.png)

**Comment by ali206** [comment]
422369 - same thing, $980 was showing on invoice as payment that was charged but the actual charge that went through was for  $1758

**Comment by bradatkins** [comment]
What was the correct payment amount Ali?

**Comment by ali206** [comment]
$1758

**Comment by bradatkins** [comment]
So I tried with this order to replicate the issue and I'm not sure where 1758 would come from, unless it was more than the deposit?

I added two PAX, selected insurance for both and the Deposit (which Katherine selected as her payment) and it came out correctly to $1,160 (400x2 + 180 x 2)

**Comment by ronenreinheimer** [comment]
Donna emailed you a video

**Comment by bradatkins** [comment]
Donna's video was not the same issue...

**Comment by bradatkins** [comment]
Fixed, I'm pretty sure :) Please keep an eye out

**Comment by ali206** [comment]
on 422369 the difference of what should've been charged and the $1758 is cxlation insurance per person. Not sure if you need to know that anymore, we'll keep an eye out moving forward

**Comment by bradatkins** [comment]
You got it...the insurance (travel and cxl) was the majority of the issue.
