### ISSUE TITLE
#422369 wrong amount and wrong insurance

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#824]
Wrong amount is reflecting on invoice than actual went through on Merchant, I just changed it manually. Was showing as $ 980, but actual payment that went through is $1758. Also, reflecting old insurance of $189 instead of $180, and they just registered. I'm going to update  insurance as well. 

![422369](https://cloud.githubusercontent.com/assets/14838466/13058468/73d04c2c-d3f1-11e5-890a-1b6a64731aa2.PNG)

**Comment by bradatkins** [comment]
Fixed - I did a test - #422732

![image](https://cloud.githubusercontent.com/assets/8440255/13590299/9c91e424-e4ac-11e5-88de-fa6fc0c790f5.png)
