### ISSUE TITLE
New Look - Initial Testing - Invoice Business Class Upgrade - East Bound or West Bound?

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#825]
Hi Brad,

Can you have the invoice indicate if the business upgrade is for east or west bound?

![image](https://cloud.githubusercontent.com/assets/10079829/13059018/48453ac8-d3f5-11e5-95c5-0f57671d1927.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/13060420/521e2082-d3ff-11e5-8a11-dfa2749ba015.png)

**Comment by ronenreinheimer** [comment]
n1
