### ISSUE TITLE
New Look - Initial Testing - Triple Room (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#826]
![image](https://cloud.githubusercontent.com/assets/10079829/13059658/c4a0d29a-d3f9-11e5-8521-d9f6840cab09.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13059665/cfaf538c-d3f9-11e5-893e-fbe7b9b3513a.png)

**Comment by bradatkins** [comment]
I think there may be some confusion then, because that is a triple...The wording is different but there's only ever been three options. Private, Double, Triple..

**Comment by ronenreinheimer** [comment]
reply:

Double room can be with one bed (when spouses are sharing room for example) or with two separate beds (when friends are sharing room)
That is what Double 1 bed and Double 2 beds stand for.
Triple was not chosen but that is what was listed on the invoice.

**Comment by bradatkins** [comment]
Sorry, but it's always been like the text because the "old db" never had 4
options, only 3.

I will change the text to have triple in the wording. There has only ever
been a single, double, triple. The DB had no idea how many beds there was,
just how many people in a room.

**Comment by ronenreinheimer** [comment]
i sent you an email today to revise this section:
www.206tours.com/ronen/booking/new/rooms/index2.htm

**Comment by bradatkins** [comment]
We will handle this under #839

**Comment by ronenreinheimer** [comment]
Agreed – Rinda needs this updated as soon as possible please.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
