### ISSUE TITLE
DB registration to match tour header images

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#828]
![image](https://cloud.githubusercontent.com/assets/10079829/13060234/fd626888-d3fd-11e5-8e44-6dbdf735ed3d.png)

**Comment by ronenreinheimer** [comment]
Can I just have the first part or last part of the file name match the tour name? I want to keep the name of the headers for SEO purposes.

http://www.206tours.com/tour161/greece-header6.jpg   (current)

http://www.206tours.com/tour161/greece-header6-tour161.jpg  (option 1)

http://www.206tours.com/tour161/tour161-greece-header6.jpg   (option 2)


or just have the DB grab it from the directory?
http://www.206tours.com/tour161/greece-header6.jpg   (current)

**Comment by ronenreinheimer** [comment]
is it possible for me to name the files like this?

Tour161_greece_pilgrimage_header.jpg

Tour96_shrines_of_italy_pilgrimage_header.jpg

**Comment by bradatkins** [comment]
It will add some overhead to the page load time because the DB will have to process all files in that directory to determine if there's an image.

**Comment by ronenreinheimer** [comment]
What if I put each header in a sub directory? And the DB will just need to go there to scan for the file?

www.206tours.com/tour161/header/Tour161_greece_pilgrimage_header.jpg



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Sure, I guess. Seems like a lot of work for nothing, but that's up to you :)

**Comment by ronenreinheimer** [comment]
I just want to keep file names for SEO purposes.


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
K, let's test one before you do a whole bunch..

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you test this one? Have the DB go directly to the header directory.

http://www.206tours.com/tour161/header/Tour161_greece_pilgrimage.jpg


Tour 161

[cid:image001.jpg@01D1689F.7781F770]

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done. Some notes:

- The image must be a .jpg
- It must be stored within the tour directory and within the header directory
- It must be prefixed by the word "Tour" (note Capital T) and then the tour # (eg Tour206). This applies to all tour numbers (eg Tour 161-A, custom tours, etc)
- If the DB can't find an image it uses /tour96/italy-catholic-pilgrimage-header2.jpg as a default (we can change the default)

**Comment by ronenreinheimer** [comment]
cool, let me test it and i'll build a default image.

**Comment by ronenreinheimer** [comment]
it worked, i am going to build some more and test them.

you rock!

![image](https://cloud.githubusercontent.com/assets/10079829/13152740/97c60988-d63e-11e5-9e56-8b197202596d.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

all the headers have the same width (950px) but the heights vary, can you please have the DB match the height of the header it pulls from the directory?

![image](https://cloud.githubusercontent.com/assets/10079829/13230768/ad30f10a-d974-11e5-8bd4-d114a398dd1e.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13230781/b88ee3c2-d974-11e5-8cf4-b5ce1c8309c0.png)

**Comment by bradatkins** [comment]
The DB cannot pull the height. What I can do is remove the hardcoding of
the height and width...

**Comment by ronenreinheimer** [comment]
Yes, please try that.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Forgot to ask, what's a couple of tours I can use to check?

**Comment by ronenreinheimer** [comment]
Tour 2 is one that is perfect to check

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Check now. I find it takes up to much vertical space myself...but that can
be fixed with making the image smaller...

**Comment by ronenreinheimer** [comment]
It is perfect! Most headers are not this tall but some are smaller and some bigger and this will fix the issue!

Thank you!!!!!!!!!!!!!!!!!!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
ITS PERFECT! TY

**Comment by ronenreinheimer** [comment]
I forgot – but what format do I use for Tour 10-A ?


1.       I tried Tour10-A and Tour10A and neither worked.
www.206tours.com/tour10a<http://www.206tours.com/tour10a>


2.       What format can I use for specials?
www.pilgrimages.com/krisak<http://www.pilgrimages.com/krisak>



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Whatever is stored in the Tour # field. If there's multiple, you'll need an
image for each tour #

[image: Inline image 1]

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/13233711/fdacec98-d982-11e5-8fdd-0c9447b0a657.png)

**Comment by ronenreinheimer** [comment]
Thank you, I’ll test it.

*What about series tours like 10-A ?
www.206tours.com/tour10a<http://www.206tours.com/tour10a>

I can’t get this one to work.


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
"10-A"...case probably matters...
[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
I tried the following:

Tour10-A-paris-pilgrimages.jpg

Tour10A-paris-pilgrimages.jpg

Neither worked.



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
That's because the directory itself

http://www.206tours.com/tour10a/header/

instead of

http://www.206tours.com/tour10-A/header/

**Comment by ronenreinheimer** [comment]
I would have to rename the directory from this
www.206tours.com/tour10a/header

to this?
www.206tours.com/tour10-A/header



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Correct...remember though any hyper links etc...or rename the tour number 10a

**Comment by ronenreinheimer** [comment]
Hi Brad,

This is the DB code for this tour: SK040416

URL:
www.pilgrimages.com/krisak<http://www.pilgrimages.com/krisak>

Tour Header:
[cid:image002.jpg@01D16E27.9A8B5EE0]

Did I set this up correctly?

[cid:image003.jpg@01D16E27.9A8B5EE0]

[cid:image004.jpg@01D16E27.9A8B5EE0]



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
