### ISSUE TITLE
URGENT: Wrong amount charged 422401

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#832]
was showing on invoice that $970 went through but in Merchant $1738 was actually charged:

I updated the payment in the DB so client could see a correct invoice. 

This was emailed to client:
![image](https://cloud.githubusercontent.com/assets/8440903/13090728/6697314a-d4c5-11e5-838f-48ea483365a0.png)

this is what's showing in merchant:
![image](https://cloud.githubusercontent.com/assets/8440903/13090732/6e8520ba-d4c5-11e5-9655-e0000b87b050.png)

**Comment by bradatkins** [comment]
Fixed. Keep an eye out and if you see it again let me know
