### ISSUE TITLE
Need help for Client - Invoice showing incorrect calculations (Bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#833]
![image](https://cloud.githubusercontent.com/assets/10079829/13091886/34da579e-d4cb-11e5-85a8-6a34da05ffe0.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13091916/59ff8daa-d4cb-11e5-9125-e19fb1f447bb.png)

**Comment by bradatkins** [comment]
Fixed a couple of long standing bugs on this one. Phewf!

**Comment by ronenreinheimer** [comment]
TY
