### ISSUE TITLE
database duplicated 2 of the passengers on the invoice where it’s only supposed to be 4 (Elise)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#834]
![image](https://cloud.githubusercontent.com/assets/10079829/13091970/94d42cce-d4cb-11e5-9d4b-c0908471982f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13091987/af361aa0-d4cb-11e5-911e-47786902d018.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13092079/2b4e6e08-d4cc-11e5-8c94-5ab361db9159.png)

**Comment by bradatkins** [comment]
Fixed
