### ISSUE TITLE
ORDERS not filtering correctly 

### ISSUE THREAD

**Issue by rinda206** [206Tours/DB#835]
Pull up by Tour Code:  JM071116  - 1 pax shows - 5 are on tour code. 

![image](https://cloud.githubusercontent.com/assets/8495740/13118247/667a4146-d571-11e5-9f64-17c93e8b2023.png)

**Comment by bradatkins** [comment]
How do you know there's 5? I only see one order on that Tour Code of JM071116

**Comment by rinda206** [comment]
Order # 421710 + 421837 

I think I figures out the problem. There is a code FM071116  which the other 4 are under but showing on invoice JM071116

**Comment by bradatkins** [comment]
Ah ok. I'll close this issue then :)
