### ISSUE TITLE
New Look - Initial Testing - DB error | cost reflects twice (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#836]
![image](https://cloud.githubusercontent.com/assets/10079829/13147827/769051d0-d628-11e5-8ebd-5616a334b2a5.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13147859/adfe00ae-d628-11e5-8530-3149b2ec9426.png)

**Comment by bradatkins** [comment]
Fixed
