### ISSUE TITLE
422478 - wrong amount showing to be processed again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#837]
Amanda just registered these clients and put through to process total balance due of $7,940 and the ACH email I got was showing as $8,538:

![image](https://cloud.githubusercontent.com/assets/8440903/13150347/5eaf3f1c-d633-11e5-8e8f-0bda222dd3ce.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13150359/6ac3127e-d633-11e5-947b-073d871296b9.png)

**Comment by bradatkins** [comment]
So what is the correct amount?

**Comment by ali206** [comment]
$7940

**Comment by bradatkins** [comment]
Seems like it's OK now. I just placed a test order:

![image](https://cloud.githubusercontent.com/assets/8440255/13620190/eb486e58-e55b-11e5-84e3-735e584f239d.png)
