### ISSUE TITLE
DB| INSURANCE PRICE NOT REFLECTING CORRECTLY   (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#840]
![image](https://cloud.githubusercontent.com/assets/10079829/13152220/15b8149c-d63c-11e5-8010-4dc243ff96eb.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13152214/11ae85c0-d63c-11e5-97f7-7c977ef7d550.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13163536/e8156342-d67b-11e5-9de0-cb794ae6a4b8.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13263798/3211bade-da39-11e5-8e68-89b9d1d0fd57.png)

**Comment by bradatkins** [comment]
All good

![image](https://cloud.githubusercontent.com/assets/8440255/14035336/51256a60-f203-11e5-83e9-5fa878641e15.png)
