### ISSUE TITLE
Database Issue from client: Payment: state form isn't working (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#841]
![image](https://cloud.githubusercontent.com/assets/10079829/13154721/5f9eaa2e-d648-11e5-9894-fa4945a86f47.png)

**Comment by bradatkins** [comment]
I don't see any information related to this guy? I couldn't find an existing order, or even an incomplete order under his email??

**Comment by ronenreinheimer** [comment]
we cant locate this client, so i am going to close this out for now.
