### ISSUE TITLE
Booking # 421456 | Dynamic Catholic Invoice

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#842]
https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=421456&TravelerID=25745&GENERATED=TRUE&BLUE_SHEET=Y

![image](https://cloud.githubusercontent.com/assets/10079829/13156768/1c0dcf2e-d652-11e5-858d-e7ebd970eb1e.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
from Donna,

![image](https://cloud.githubusercontent.com/assets/10079829/13179219/f664b1b2-d6f0-11e5-86f7-2b28174f6ea6.png)

**Comment by bradatkins** [comment]
Fixed
