### ISSUE TITLE
DB | Single supplement rate not showing (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#844]
![image](https://cloud.githubusercontent.com/assets/10079829/13179434/fbd63c46-d6f1-11e5-9a9b-f3b3adea5fc6.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13764835/1367d234-ea2a-11e5-9c33-67530aec4631.png)
![image](https://cloud.githubusercontent.com/assets/8440255/13764841/25a3437a-ea2a-11e5-8ab8-d967f734f083.png)
