### ISSUE TITLE
DB not reflecting payments made (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#846]
![image](https://cloud.githubusercontent.com/assets/10079829/13179517/3cf23194-d6f2-11e5-9ce2-72574bef11bb.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13497606/4d43a244-e124-11e5-83c8-a91b5194d143.png)

**Comment by bradatkins** [comment]
Odd, how is she getting to this screen?

[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
I will ask her

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Its all orders…. I’m not sure what he means by how am I getting to the screen

**Comment by bradatkins** [comment]
Current year? which page?

![image](https://cloud.githubusercontent.com/assets/8440255/13498419/e05c622a-e127-11e5-9905-e20abf3c4d3c.png)

**Comment by ronenreinheimer** [comment]
Current year

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13532690/d35cdfd6-e1fa-11e5-90fd-ff5fd2b7f7d9.png)

**Comment by bradatkins** [comment]
Seems to be OK.

If it happens again, please take a video of how she got there...

![image](https://cloud.githubusercontent.com/assets/8440255/13764931/20a6a320-ea2b-11e5-8f7b-e4e3693285fe.png)
