### ISSUE TITLE
Travel Insurance / Cancel Protection Pop up Links

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#847]
![image](https://cloud.githubusercontent.com/assets/10079829/13179597/984546da-d6f2-11e5-9742-cd24feafe34a.png)

**Comment by ronenreinheimer** [comment]
Please link them like this:
http://www.206tours.com/ronen/booking/new/page2/index.htm
 
please use the pop up javascript code.

**Comment by bradatkins** [comment]
Done, but do you really want me linking to these two files inside the "ronen" directory?

http://www.206tours.com/ronen/booking/new/page2/popupex.htm
http://www.206tours.com/ronen/booking/new/page2/popupex2.htm

**Comment by ronenreinheimer** [comment]
mmm… I guess I can move them to a location in the insurance directory.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
First link is our old insurance, I need to update that anyway.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Try these

http://www.206tours.com/insurance/popupex/popupex.htm
http://www.206tours.com/insurance/popupex/popupex2.htm


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
i see it is still linked to /ronen/ directory.

![image](https://cloud.githubusercontent.com/assets/10079829/14119644/26a4d772-f5bd-11e5-8e72-10c8427fcfca.png)

**Comment by bradatkins** [comment]
Fixed a while ago, forgot to close
