### ISSUE TITLE
#419036 -total amount is not correct (Irena)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#852]
![image](https://cloud.githubusercontent.com/assets/10079829/13186554/b8c180dc-d714-11e5-8496-de55c258cbca.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13187244/1a9eed46-d718-11e5-9fca-dcab0527dc63.png)

**Comment by bradatkins** [comment]
Sorry, that's not correct because of the processing fee. The original order is in fact $7,983.75, but you have to add $15.75 to the order total, making it $7,999.50
