### ISSUE TITLE
422489 - client had recurring payment somehow

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#853]
Somehow this client was able to select a recurring payment?!

$2299 was charged on the 18th and then again in the same report but as of the 19th at 12:11 am was the recurring payment. 

Only 1 transaction was showing on the invoice, i just manually added the one with this transactions ID:

190216A15-F17CB5B0-1A67-4250-866C-31D23477CD10

![image](https://cloud.githubusercontent.com/assets/8440903/13222513/33c7a10e-d94e-11e5-8022-c194e6c77b74.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13222499/26224a72-d94e-11e5-967f-8fe9952971b1.png)

**Comment by ali206** [comment]
did it charge the full amount b/c he's leaving in April?  I don't know what he expected to pay as his recurring payment.  

Does the recurring payment always have to start the day after initial payment? If so, there should be a message set up for clients maybe to let them know because that's not going to be expected and doesn't make sense.

**Comment by bradatkins** [comment]
It's been set to start the next period (eg next week, month,e tc)
