### ISSUE TITLE
422504 - installment payment

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#854]
Hi Brad, 

Im sure you've explained this before but can the charge the day after initial payment not happen? It doesn't make sense. 

Math seems to be correct on this one at the current moment though which is good:

![image](https://cloud.githubusercontent.com/assets/8440903/13224810/3d0fc3c2-d958-11e5-9eed-2ce5dd4f632d.png)

**Comment by bradatkins** [comment]
I can make it whatever you want. Not sure why I chose one day.

I will make it the following period (eg if weekly, next week, if monthly,
next month...etc)
