### ISSUE TITLE
DB - Passenger's Title on invoice (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#855]
![image](https://cloud.githubusercontent.com/assets/10079829/13225878/e16cfcba-d95c-11e5-836d-ed3515809c65.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13225914/0a1d1dde-d95d-11e5-889b-5b65f61a47c2.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/13467718/7676421e-e06d-11e5-98b3-a027bb516fca.png)
