### ISSUE TITLE
2016 / 2017 / 2018 etc.. UI Dates (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#856]
Hi Brad,

can you build this into the dark blue header of the UI?

CURRENT UI:
![image](https://cloud.githubusercontent.com/assets/10079829/13229925/1b9d4552-d971-11e5-99c2-bcf860339b60.png)

UI with DATES:
![image](https://cloud.githubusercontent.com/assets/10079829/13229937/37f85412-d971-11e5-8bb3-7c95a8462b48.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
n1!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
