### ISSUE TITLE
Australia not listed as an option on website as currency

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#859]
Hi Brad,

Shouldn't Australia be listed as an option for MC?
http://acquiring.elavon.com/documents/pdfs/norway/Multi-Currency_solution_sheet_eng.pdf

**Comment by bradatkins** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/8440255/13467133/cd3547e2-e06a-11e5-981a-99482e374959.png)
