### ISSUE TITLE
2 tickets associated to a land only passenger 415442

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#86]
These people are Land Only Passengers but Thomas has 2 tickets attached to his name that automatically went there when importing??!

![image](https://cloud.githubusercontent.com/assets/8440903/4772322/6ad9a312-5b97-11e4-8f2c-8593fd080825.png)

**Comment by bradatkins** [comment]
I've put in a check to see if they are land only now and rejected these two tickets so they will require classification
