### ISSUE TITLE
421930 - no payment made but emails sent out?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#860]
![image](https://cloud.githubusercontent.com/assets/8440903/13254433/4f92f37c-da0f-11e5-94cf-f7e707cac500.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13254449/57109d8e-da0f-11e5-9352-fc54afe4a802.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13254454/5d572d0c-da0f-11e5-8da9-b53e826027dc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13254469/6757a250-da0f-11e5-9198-6e6ba4c82b06.png)

**Comment by bradatkins** [comment]
Do you see anything in Elavon around that date / time?

**Comment by bradatkins** [comment]
Nevermind that. It looks like he put a $ in the amount field which messed things up.

I've limited it to only numbers
