### ISSUE TITLE
recaps exporting with a lot of "FALSE"

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#861]
![image](https://cloud.githubusercontent.com/assets/8440903/13254990/ee53a464-da11-11e5-85ab-d4a4ab1c8c9f.png)

How do we avoid that

**Comment by bradatkins** [comment]
Can you provide the example tour #?

**Comment by ali206** [comment]
woops sorry, here's an ex:
MC030616

**Comment by bradatkins** [comment]
The Excel doesn't like the "cross" symbol and explodes when it sees it.

Switch them to dashes or something and it'll be fine.
