### ISSUE TITLE
Incorrect LAND ONLY date listed (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#862]
![image](https://cloud.githubusercontent.com/assets/10079829/13256082/37e0cb2a-da17-11e5-93be-14b9a0c907db.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13256105/5d8b49b8-da17-11e5-92d2-e0b5f50a543d.png)

**Comment by bradatkins** [comment]
Fixed
