### ISSUE TITLE
421290 - commission not showing on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#864]
![image](https://cloud.githubusercontent.com/assets/8440903/13258029/65793da8-da1f-11e5-809d-9aee4b805599.png)

should be showing as $1009.80

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13466108/80eca758-e066-11e5-95a0-b802747ac5d7.png)
