### ISSUE TITLE
pdf link gone

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#865]
Hi Brad, 

Not sure if this was requested to be removed, but how come when we view an invoice we don't have an option to look at it in pdf format anymore?

**Comment by bradatkins** [comment]
Because we've switched to the HTML format? I'm confused

**Comment by ali206** [comment]
I don't know much about the "new look" and what was included in that, that's why i'm asking.  I liked looking at the pdf versions of invoices but the link is no longer there so i guess that was part of the new format, to get rid of that link.

**Comment by bradatkins** [comment]
The link to view the invoice should still be there, but it'll be the HTML
version.

Is the link gone, or is your concern that the PDF is gone (both should show
the same information of course)

**Comment by ali206** [comment]
Not sure we're talking about the same links...

The pdf link is gone, as is the blue sheet link. 

It's ok if they're gone as long as that's what Milanka asked for, which she might have i don't know.

![image](https://cloud.githubusercontent.com/assets/8440903/13259205/6a07afb2-da24-11e5-9152-69ae4c3dc116.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13259230/823581fe-da24-11e5-8faa-7549bfb8c075.png)

**Comment by bradatkins** [comment]
Oh ya, those were there to compare the PDF to the HTML one.

Just curious though, why would you need the PDF anymore?

**Comment by ali206** [comment]
I don't need it technically, just liked looking at that invoice better
