### ISSUE TITLE
clients are unable to log in to their accounts with email address and order #  (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#866]
![image](https://cloud.githubusercontent.com/assets/10079829/13260716/bb9032b8-da2a-11e5-86ee-0e7de6886e0a.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13260731/cc3d2652-da2a-11e5-93e4-76cef9856c8f.png)

**Comment by ronenreinheimer** [comment]
please build it like this:
http://www.206tours.com/ronen/booking/new/login/index2.htm

**Comment by bradatkins** [comment]
This isn't the way the other one was.

The other one was "email & password" or "email & order id"

The point was that if they forgot their password they could still login...

Please update the mockup

**Comment by ronenreinheimer** [comment]
updated

**Comment by bradatkins** [comment]
This functionality has been restored:

![image](https://cloud.githubusercontent.com/assets/8440255/13466371/a685f586-e067-11e5-9856-e373f89df365.png)

**Comment by ronenreinheimer** [comment]
You Da Man!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13467213/2bbc0918-e06b-11e5-9dc0-21aa107546fa.png)

**Comment by bradatkins** [comment]
Done
