### ISSUE TITLE
DB | CLIENT ACCOUNT DUE IS WRONG | CORRECT ON OUR INVOICE (Sammie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#868]
![image](https://cloud.githubusercontent.com/assets/10079829/13263675/96061108-da38-11e5-87ca-057f0908a8e7.png)

Dear Ronen,

Please see below an email from client. When he logs into his account he sees the balance of $6,177 however his balance should be $ 5,427 so the discounts are not being applied to his account. Unfortunately, as the new site is up we are not able to log into his account and see what he sees. 
 
Sammie Gough 
Travel Consultant
206Tours.com 	 

________________________________________

From: Paul Gorman [mailto:pauljgorm@gmail.com] 
Sent: Tuesday, February 23, 2016 12:02 PM
To: 206 Tours <206tours@206tours.com>
Cc: rok <rok@206tours.com>
Subject: Re: 206 Tours Inc. - Order #422164 Tour #111 April 16, 2016

Thank you, that is good news.  I logged onto my account to make a payment, and noticed the amount
due was $6,177.  This amount does not reflect the March for Life discounts for $750.  Would it be possible
to amend the invoice to show the proper amount due?

Regards,
Paul

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13272974/1ae7aeba-da6e-11e5-934f-74e2164b8c5c.png)

**Comment by ronenreinheimer** [comment]
from Sammie / Customer

![image](https://cloud.githubusercontent.com/assets/10079829/13364888/a3ac4caa-dc9f-11e5-8aad-58bed0f5f1b2.png)

**Comment by bradatkins** [comment]
Forgot that part.

Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13465048/ed7d0db8-e061-11e5-841b-eadb0421ccc4.png)
