### ISSUE TITLE
URGENT? Clients can book tours for $0

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#869]
Hi Brad,

I was running a test with one of our CSRs and I was told that clients can book tours that dont offer land only prices for $0. Can you please eliminate this possibility in the booking section?

example:
www.pilgrimages.com/froberle/greece

DB code:
**FJ061016A**

**does not offer land only option:**
![image](https://cloud.githubusercontent.com/assets/10079829/13268087/789a1cde-da4e-11e5-96b7-0fd7564e41fa.png)

**but in booking section it does:**
![image](https://cloud.githubusercontent.com/assets/10079829/13268097/8d28e662-da4e-11e5-9879-071352578453.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13268150/d853bbee-da4e-11e5-84df-4089ac81e9df.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
TY!
