### ISSUE TITLE
Payments not showing in View Orders for anyone

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#870]
![image](https://cloud.githubusercontent.com/assets/8440903/13288046/23e04f9e-dad8-11e5-9e79-c06818d46d24.png)

**Comment by bradatkins** [comment]
You need to click on Order Total...

**Comment by ali206** [comment]
No it wasn't for that specific payment, if you look at the picture you can see paid in full invoices that have the total balance still showing as due..

seems to be ok now though somehow
