### ISSUE TITLE
422429 - invoice is crazy

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#871]
Hi Brad, 

Few problems with this invoice..

#1. Client was not actually charged the cc fee of $32.87 on the first payment.  She paid that $32.87 in her 2nd payment and the fee of $131.98 showing on the invoice for the 2nd payment was not charged at all. 

#2. Tour was cxld and she's getting a full refund but we can't get the invoice to show a 0 balance b/c the cc fees are automatically being added in and i don't have the ability to change that amount anywhere

Total refund is the total amount she actually paid and cc fees should only be $32.87 included

**Comment by bradatkins** [comment]
This order was cancelled, let me know if this happens again
