### ISSUE TITLE
Back Button Registered Tour - URGENT

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#875]
![image](https://cloud.githubusercontent.com/assets/10079829/13296343/2ebfd90c-dafb-11e5-8f23-0444ffe7e26e.png)

**Comment by bradatkins** [comment]
It brought me back to the contacts page. Maybe I fixed it or I can't reproduce it?

**Comment by ronenreinheimer** [comment]
Let me try


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Looks like you fixed it

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
