### ISSUE TITLE
commission needs to show on invoices being emailed out to clients

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#876]
i think this might have been added already but for NET Agents we need commission to show on the invoice that gets emailed out to them so they can see what they received and what they owe. 

They see the correct balance now but there's no deduction of commission so it looks confusing:

![image](https://cloud.githubusercontent.com/assets/8440903/13297920/a6aa5292-db02-11e5-914d-1482875d1cfc.png)

**Comment by bradatkins** [comment]
Done:

![image](https://cloud.githubusercontent.com/assets/8440255/13621330/d77c8a40-e564-11e5-92c1-126cd569ae00.png)

**Comment by ali206** [comment]
I just emailed myself an invoice with commission and #1 - i can't open the pdf file but aren't they not supposed to be attached anymore since the invoice is in the body of the email?

#2 - commission's not showing

![image](https://cloud.githubusercontent.com/assets/8440903/14120539/35ebd402-f5c1-11e5-8473-5518394bdaf1.png)

**Comment by bradatkins** [comment]
1) I'll check into the PDF thing

2) Commission is only sent from the DB through regular routines, not when manually invoked.

**Comment by bradatkins** [comment]
The PDF thing is fixed

**Comment by ali206** [comment]
I'm sorry, can you explain #2 a little more?

what if i had sent that to the client and not myself? would they see it?

**Comment by bradatkins** [comment]
Clients don't see commissions? I thought only Agents do?

**Comment by ali206** [comment]
yes i meant agents - 422767 (my ex above) is an agent's booking

**Comment by ali206** [comment]
Ok that makes sense thanks. SOOO much to remember sorry

**Comment by bradatkins** [comment]
No worries, between all of us, we'll figure it out :) I forget stuff too
