### ISSUE TITLE
Subtotal column in wrong place on invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#879]
subtotal is in the wrong spot on the invoice now - where it currently is it might as well just say total balance due.  It should be before insurances b/c the subtotal is what determines the insurance

![image](https://cloud.githubusercontent.com/assets/8440903/13299836/e4fe08a6-db0a-11e5-8469-0bddb8aec26d.png)

**Comment by bradatkins** [comment]
It looks in the right spot to me?

**Comment by ali206** [comment]
how?

**Comment by ali206** [comment]
on old invoices this is how it used to look which was correct:
![image](https://cloud.githubusercontent.com/assets/8440903/13300032/3935a018-db0c-11e5-9412-fafc95d8fffa.png)

**Comment by bradatkins** [comment]
It's where Ronen told me to put it :)
