### ISSUE TITLE
421960 - applied free but balance due wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#880]
i applied the free amount for base and SS and it updated insurance correctly to $105 but the balance due is still showing old ins. cost of $280

![image](https://cloud.githubusercontent.com/assets/8440903/13299965/ac55b9c6-db0b-11e5-8e9c-71230d656a87.png)

**Comment by bradatkins** [comment]
The Honor Pricing is a great thing :) Fixed

**Comment by ali206** [comment]
but i shouldn't have to use that in this scenario right? it might solve the problem but if everything but the balance updated correctly i don't assume that i have to use the honor pricing thing

**Comment by bradatkins** [comment]
Yes, that I believe I have fixed as well. Sorry, should have been more clear
