### ISSUE TITLE
Pricing Error: Tour 40 - April Departure - discrepancy between DB price and invoice (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#881]
![image](https://cloud.githubusercontent.com/assets/10079829/13300079/7c7f62aa-db0c-11e5-8f53-1402d815aef3.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13300114/9fc24688-db0c-11e5-9549-89084831818d.png)

**Comment by bradatkins** [comment]
Seems to be OK now:

![image](https://cloud.githubusercontent.com/assets/8440255/13440658/18893230-dfc1-11e5-8eb2-9ef39c3a1b88.png)


![image](https://cloud.githubusercontent.com/assets/8440255/13440639/00438efa-dfc1-11e5-9ffa-e8a8f370ca6b.png)
