### ISSUE TITLE
No SS Price noted in Registration Process (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#883]
DB Code:  **BL061416**

![image](https://cloud.githubusercontent.com/assets/10079829/13325485/1a052d86-dbb0-11e5-9ecc-9a0dbb5ee901.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13416416/5803a06c-df30-11e5-91c1-bce14e61e0c0.png)
