### ISSUE TITLE
Credit Card Info Section NOT showing (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#884]
![image](https://cloud.githubusercontent.com/assets/10079829/13325589/7171cd04-dbb0-11e5-9180-ca182bd052b4.png)

**Comment by bradatkins** [comment]
I need more information like Order #, PAX name...something so I can look up his session...

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13432037/ef3c0276-df99-11e5-8ad4-2880b40a7455.png)

**Comment by bradatkins** [comment]
Fixed. There was something with the comments that was messing things up. All good now
