### ISSUE TITLE
 Travel Insurance not being reflected (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#885]
![image](https://cloud.githubusercontent.com/assets/10079829/13325633/aba19af4-dbb0-11e5-9702-34d5c215682b.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13325657/c7abba36-dbb0-11e5-87ce-5f65a87e64b9.png)

**Comment by bradatkins** [comment]
Fixed
