### ISSUE TITLE
e-mail did not arrive  |  Order #422512 (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#886]
![image](https://cloud.githubusercontent.com/assets/10079829/13329219/a66c2bd4-dbc0-11e5-8804-6c3a5b55d39e.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13329194/8a3763fc-dbc0-11e5-8bce-8cd0038ab9ef.png)

**Comment by bradatkins** [comment]
The DB sent the following emails.

If the client didn't receive it, it isn't a DB issue as this tells me the
DB sent it. Appriver or client issue. I did notice the three dots after the
email though...

[image: Inline image 1]

**Comment by bradatkins** [comment]
It's not a DB issue
