### ISSUE TITLE
FK011016 recap showing addt'l options header but no addt'l options exist

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#887]
![image](https://cloud.githubusercontent.com/assets/8440903/13329228/b7f4c9d8-dbc0-11e5-8841-c8f0097de4d7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13329247/cdea6446-dbc0-11e5-9f53-7d71fb8a267e.png)

**Comment by bradatkins** [comment]
Fixed
