### ISSUE TITLE
DB Issue | Registration process no drop down for dept city for pax 3 | Pax name repeats for pax 2 and 3 (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#889]
![image](https://cloud.githubusercontent.com/assets/10079829/13357533/d4a2c040-dc78-11e5-8dde-ba61d172eadf.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13357552/eec1aa86-dc78-11e5-9314-de0431a95268.png)

**Comment by bradatkins** [comment]
This should be fixed as per my email today
