### ISSUE TITLE
DB error | business class shown for the 2 that did NOT purchase it (Stefanie)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#890]
DB CODE: **MO061216**

![image](https://cloud.githubusercontent.com/assets/10079829/13357818/4be60e4a-dc7a-11e5-92db-174b93f5a2a4.png)

**Comment by bradatkins** [comment]
Fixed.

**Comment by bradatkins** [comment]
How come you removed the tag? It's fixed.

**Comment by ronenreinheimer** [comment]
I pressed close and I guess it didnt

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
