### ISSUE TITLE
DB error | extended cxl ins| FAT2017J   

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#891]
Hi Brad,

Extended travel protection is off in the DB but it is still showing up on the registration page.

![image](https://cloud.githubusercontent.com/assets/10079829/13358451/5f246044-dc7d-11e5-81f8-c445729ac9e7.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13358465/70188a56-dc7d-11e5-9e78-559e98b3b559.png)

**Comment by bradatkins** [comment]
Fixed, good catch

![image](https://cloud.githubusercontent.com/assets/8440255/13415562/d70f3378-df29-11e5-8139-bea8d240f8ef.png)
