### ISSUE TITLE
Please have Peter Ireland taken off of this invoice (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#895]
![image](https://cloud.githubusercontent.com/assets/10079829/13405696/b5a2cbf0-deed-11e5-8e60-8d9a5831358e.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13405704/c6d77088-deed-11e5-9d4e-1271b2c472b3.png)

**Comment by bradatkins** [comment]
Done
