### ISSUE TITLE
#422407 and  #422605- installment payments

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#896]
Hello Brad, 
So I have 2 payments one from 2/28 for $8098 that didn't post on DB and I had to add manually and also from 2/29 $899.80.

Wakley from #422707 was charged twice this month, and Law Rita from #422605 was charged 2 days in a row , can you please change and fix that ASAP ? ! 

![capture in](https://cloud.githubusercontent.com/assets/14838466/13406369/1cb5a3dc-def1-11e5-87d7-0630d665dfbc.PNG)

**Comment by bradatkins** [comment]
I see two payments for 422407:

1600 - Looks like placed by the customer
8098 - Placed by Irena

Am I missing something?

I see the next installment date for 422605 as March 29th...

You may need to check Elavon to see if that lines up

**Comment by Irena206** [comment]
422407 I added manually , 
422605 I added manually,

both payments were processed at the same time 00:09 am  , different dates 
As you can see statement from Elavon 

![capture28](https://cloud.githubusercontent.com/assets/14838466/13429517/a5ff78c8-df8e-11e5-9380-c2e2c3b42c71.PNG)


![capture29](https://cloud.githubusercontent.com/assets/14838466/13429523/ad403d70-df8e-11e5-9a2a-b1c05285504c.PNG)


Customers did not made those payments we checked, so why DB charged them I do not know.

**Comment by bradatkins** [comment]
00:09AM is not the time I run my installment routines. I run them at 3AM, so it looks like these payments may have been broken when we were having previous installment problems.
