### ISSUE TITLE
#422614 installment payment -new one from this morning 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#897]
Hello Brad, 
OK this happen again this morning, so at this time Im not going to add manually, so that you can track it maybe and see what happen. Instead of charging him on April 1, DB charged him on march1. 
Please help ! Thanks. 

![capture1](https://cloud.githubusercontent.com/assets/14838466/13429887/62360db2-df90-11e5-81f1-0f2564450ea1.PNG)

![capture422614](https://cloud.githubusercontent.com/assets/14838466/13429893/66e7fa28-df90-11e5-9fd6-daef434abb2e.PNG)

![captureinasta](https://cloud.githubusercontent.com/assets/14838466/13429935/a715cf44-df90-11e5-9ca0-1c60f7889fb1.PNG)

**Comment by bradatkins** [comment]
When you say the DB Charged him March 1st, I don't see a Payment on the invoice, so how do you know the DB charged him?

**Comment by Irena206** [comment]
I copied it for you in my previous message as you can see Elavon statement  ( first picture) because I didn't charge manually that payment  which means DB did it, right ?

**Comment by bradatkins** [comment]
Oh sorry, I didn't notice the screenshot...it shows up small. I see it now.

So just to be extra clear:

1) Elavon charged him 2532.67. Should he have been charged this value on this date?
2) Or is the issue it didn't post to his invoice?

**Comment by Irena206** [comment]
1 -client was charged $2532.67 on March 1, instead of April 1 ( installment payment) , he just paid deposit on Feb 29, which means he was charged a day after for $2532.67. (picture 3) 
2- and also payment did post on the invoice.

**Comment by bradatkins** [comment]
The database was setting the installments to begin the next day. I've changed it to begin the next period (week, month, quarter)

**Comment by Irena206** [comment]
OK, Thanks !
