### ISSUE TITLE
CC billing/shipping address not working

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#90]
The shipping address is in East Africa which has nothing to do with the CC payment we're trying to make. 

I put in the billing address which is in NY but the only drop down options for state are African??

I had to process this manually since it's not correct in the DB.  But the shipping address should not effect the billing address.

![image](https://cloud.githubusercontent.com/assets/8440903/4886393/d8370e90-637b-11e4-9d0a-c9e18a959f22.png)

**Comment by bradatkins** [comment]
The DB Isn't smart enough to know you typed in a US city / zip. It lists the states that are based on their Traveler record.

**Comment by ali206** [comment]
Can that be added to Phase 8 then?

**Comment by bradatkins** [comment]
Phase 8 is only the website. I've marked it for "future phase" and will
bring it up for the next phase.

**Comment by ali206** [comment]
does this still need to be added to a phase or this is taken care of now i think right?

**Comment by bradatkins** [comment]
It's done I believe.
