### ISSUE TITLE
IDEA: Rooming Selection errors (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#900]
Hi Brad,

Chris is reporting 2 issues:

![image](https://cloud.githubusercontent.com/assets/10079829/13465982/04e8f62a-e066-11e5-8b0d-fe36a222c42f.png)

**Comment by bradatkins** [comment]
Problem #1 is fixed

Problem #2 is a separate enhancement

**Comment by bradatkins** [comment]
Is this still an issue?
