### ISSUE TITLE
Foreign CC Charges

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#902]
If Irena processes a foreign CC through Elavon in euros let's say, we have to put the amount in USD in the DB then right? 

The problem i'm seeing with that is that the invoice if client wants to see it in their currency of euros, will never be correct b/c the DB can't switch the payment back and forth between currencies without the exch rate. But if it's a manual payment there is no where to put the xchange rate...

Am i confusing everything again?

**Comment by bradatkins** [comment]
No...if it's in Euro's you enter Euro's.

Again, the order must have originally been placed in Euro's.

The DB will tell you the currency to enter:

![image](https://cloud.githubusercontent.com/assets/8440255/13589156/b5a7778e-e4a3-11e5-919f-4ee5bb8dd724.png)

![image](https://cloud.githubusercontent.com/assets/8440255/13589157/bad53674-e4a3-11e5-87ef-a42f3b81dd5a.png)

Yes, you are confusing everything again, but that's OK :) Let me know if the answer I gave isn't clear

**Comment by ali206** [comment]
Ok if it's in euro's i enter euros - fine. 

But if anyone in the office looks at that clients invoice, they'll never know the amount charged in USD right?  B/c the DB can't convert a manually entered cc
