### ISSUE TITLE
URGENT - clients are not getting their Insurance PDF files (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#903]
Hi Brad,

Sandy said that clients who purchase travel insurance are not getting their .PDF file?

![image](https://cloud.githubusercontent.com/assets/10079829/13472308/4c7d0c94-e082-11e5-8b4f-0e9ea7631ef5.png)

**Comment by bradatkins** [comment]
I placed order #422660  as myself and got it OK.

Am I doing something different?

![image](https://cloud.githubusercontent.com/assets/8440255/13475008/92d937f6-e08e-11e5-8100-f5db1aa56063.png)

**Comment by bradatkins** [comment]
Seems to be working for me?

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13644713/3f8db5ec-e5f5-11e5-8c12-8fdddb25ed33.png)

**Comment by bradatkins** [comment]
I think this is a duplicate. It's fixed now. It wasn't working when emails were sent from the admin
