### ISSUE TITLE
a client was not able to get to a confirmation page while making reservation 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#904]
Hi Brad, a client was trying to register herself and had some trouble finishing it and getting to a confirmation page. Please see below what she is saying :

 | Dayona Nett | I was trying to confirm my reservation for the June 19-28 Holy Land Tour (111) on 3/2/2016 at 8:00 PM (CST) and wasn't able to get to a confirmation page. When I clicked 'Confirm', there was no indication that a page load was in progress and I was not able to get any further in the process. I want to double-check that my deposit and insurance didn't go through before trying to resubmit another time.

**Comment by bradatkins** [comment]
I found a situation where this the button doesn't work, and I've fixed it. Not really sure if this is the same  situation or not.
