### ISSUE TITLE
Serious DB Error: Deleted Emails From Bookings - example 422668 (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#905]
![image](https://cloud.githubusercontent.com/assets/10079829/13500264/d50dfe6c-e12f-11e5-91c8-7f8a8ef8c81f.png)

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/13506412/04acd014-e14c-11e5-9fe6-c32898a35dfd.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

Is it fixed? You didn’t write anything.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Yes, fixed...see the screen shot :)

**Comment by ronenreinheimer** [comment]
OK TY

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
