### ISSUE TITLE
Business Class || Seems not to Stick  (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#906]
![image](https://cloud.githubusercontent.com/assets/10079829/13501733/d5588e22-e135-11e5-8b1f-fe798aed7396.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13501729/cfd426a0-e135-11e5-9f07-3333087984d5.png)

**Comment by bradatkins** [comment]
This tour didn't have a business class dollar amount since it was created in June 2015 until it was added March 3rd, so it wouldn't show up on an order
