### ISSUE TITLE
Travel insurance - online reservation | DB   (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#907]
![image](https://cloud.githubusercontent.com/assets/10079829/13509738/01a7e188-e15b-11e5-8c24-91bb2995e7de.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13509734/fd5ef22e-e15a-11e5-9f03-86d29c2d2b1d.png)

**Comment by bradatkins** [comment]
Not really sure what's going on with this page, there's no radio buttons, there's no terms and conditions...there is the option to select insurance per pax, I think her browser was messed up
