### ISSUE TITLE
DB Error: 422680 Insurance is clearly being calculated, but not reflecting on invoice until we update | FJB070917 (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#908]
![image](https://cloud.githubusercontent.com/assets/10079829/13510711/d64d5180-e15f-11e5-9d34-4955952ae509.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13510728/e6f9a5ba-e15f-11e5-97fe-e92a590827e4.png)

**Comment by bradatkins** [comment]
They are showing as having not selected cancellation insurance, and based on that the order looks OK.

Please advise
