### ISSUE TITLE
Insurance showing in Registered Pax and Recaps but client never accepted insurance or paid for it?!

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#91]
As per the email Sandy and I sent to you from Yaritza:
From: Yaritza Rodriguez 
Sent: Tuesday, November 04, 2014 2:30 PM
To: Ali Boulanger (ali@206tours.com); Sandra Lippold
Subject: Email to Brad

Hi Brad, 

Please take a look at the discrepancy between a client invoice, group recap and list of registered passengers. As per invoice and payments this client did not purchase travel insurance. However, recap and other places on the invoice say that she did. This inaccuracy can get us in a lot of trouble. Why does this happen?

**Comment by bradatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/8440255/5930631/f32cff1c-a65f-11e4-8e4b-d7655265ca7e.png)
