### ISSUE TITLE
Incomplete Orders - unable to resume a session

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#910]
![image](https://cloud.githubusercontent.com/assets/8440903/13531382/44c833e8-e1f4-11e5-9478-0c8aec3d0c1a.png)

![image](https://cloud.githubusercontent.com/assets/8440903/13531379/3a2c5342-e1f4-11e5-80f2-4ca77a2ace6a.png)

**Comment by bradatkins** [comment]
That session is deleted so I can't resume it...keep the session
