### ISSUE TITLE
Database sent out email confirming new pax but new pax wasn't added |  Booking: 421064  (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#917]
![image](https://cloud.githubusercontent.com/assets/10079829/13538627/ba57ffd8-e219-11e5-9882-e2011618b195.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13538674/f4202984-e219-11e5-8038-e072cfad4135.png)

**Comment by bradatkins** [comment]
Fixed
