### ISSUE TITLE
DB to Mirror Addon Rates for Mexico, Canada, Argentina etc..

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#918]
https://www.206tours.com/ronen/mexico-addons

![image](https://cloud.githubusercontent.com/assets/10079829/13541475/71dca054-e22a-11e5-86f6-e71d74f48e80.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
Hi Brad,

Can you please walk me through this feature?


God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
See the email I sent at 3:15

**Comment by ronenreinheimer** [comment]
Thanks!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/16632671/39f1873e-4393-11e6-8f87-711918eed6a0.png)

![image](https://cloud.githubusercontent.com/assets/10079829/16632727/7c1f0852-4393-11e6-9ac2-da865d5420a4.png)

**Comment by ronenreinheimer** [comment]
copy base cities is now missing

**Comment by bradatkins** [comment]
Fixed
