### ISSUE TITLE
Booked pax in database and database create two bookings | Booking 422704 (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#919]
![image](https://cloud.githubusercontent.com/assets/10079829/13541530/d38ecb6a-e22a-11e5-8fda-43f0c493c877.png)

**Comment by bradatkins** [comment]
The Confirm order button was clicked at 04-Mar-2016 16:45:59 and again at 04-Mar-2016 16:46:04 ...5 seconds apart. Not a bug.
