### ISSUE TITLE
Foreign Currency - Australia (Sandy)  

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#921]
Hi Brad,

Our Australian clients are not getting automatically changed to the Aussie Dollar. Can you please check the configuration for this currency as soon as possible – a few clients have contacted us about this.

![image](https://cloud.githubusercontent.com/assets/10079829/13574462/35c3f53e-e452-11e5-9b63-1156c2d512a6.png)

**Comment by bradatkins** [comment]
What tour is this?

**Comment by ronenreinheimer** [comment]
It should be any of our series tours

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
From: rima <rima_trad87@hotmail.com>
Date: March 6, 2016 at 10:53:33 PM EST
To: Sales <sales@206tours.com>
Subject: Offline Message | Sales | rima | Hi, I would like to get a quote in AUD for Tour 96 please, inclusive of airfares for August 29 to September 7. thanks.
Offline Message:
ID:	568442
Name:	rima
Email Address:	rima_trad87@hotmail.com

Question or Comment:	Hi, I would like to get a quote in AUD for Tour 96 please, inclusive of airfares for August 29 to September 7.
thanks.
 
Language:	English GB (US)
 
City:	Greenacre
Region:	New South Wales
Zip Code:	2190
Country:	Australia
 
Referring Page:	http://www.206tours.com

Browser:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0
Remote Host:	203.55.211.53

**Comment by bradatkins** [comment]
This is working as per my previous email.
