### ISSUE TITLE
Database error - Defaulting to wrong address when making payment (Elise)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#922]
![image](https://cloud.githubusercontent.com/assets/10079829/13574916/442d6c7a-e454-11e5-9ed9-6fcb9d851a1c.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13574925/53959cd2-e454-11e5-8ff1-b322e0ccc8f6.png)

**Comment by bradatkins** [comment]
Sammie had previously entered that CC Address on Feb 19th. This is not a bug
