### ISSUE TITLE
KBYG link on Invoices (Milanka) 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#923]
Hi Brad,

Where can we control this link? This client booked tour 206, so we need the link to go here:  http://www.206tours.com/info/mexico

But it is different for every tour and some tours have multiple destination countries. Can you set something up for us in the setup portion of the DB that will allow us to select what url(s) will appear there?

![image](https://cloud.githubusercontent.com/assets/10079829/13575390/b2662a86-e456-11e5-96b0-132175a4d963.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/14446761/4818642c-0027-11e6-92e1-5cb9a87e3c40.png)

**Comment by ronenreinheimer** [comment]
TY!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
it is so strange, it shows the right link, but the actual url is wrong:

![image](https://cloud.githubusercontent.com/assets/10079829/14468457/b29be0c2-00ad-11e6-9026-f53f4a673c54.png)

**Comment by bradatkins** [comment]
Try again :)

**Comment by ronenreinheimer** [comment]
OK

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
n1

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
