### ISSUE TITLE
DB - Extended cxl plan | online reservation (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#925]
![image](https://cloud.githubusercontent.com/assets/10079829/13613409/fa07071e-e539-11e5-85d8-a6d76397aac1.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13613421/055a80f0-e53a-11e5-9838-6e12ed66768b.png)

**Comment by bradatkins** [comment]
Are you able to reproduce the steps you did to make this happen? I tried but it seemed to work OK:

![image](https://cloud.githubusercontent.com/assets/8440255/13621701/8d73d928-e567-11e5-847a-ff21134c7a61.png)

![image](https://cloud.githubusercontent.com/assets/8440255/13621705/9245d640-e567-11e5-8c4c-e7db8261e3c1.png)
