### ISSUE TITLE
DB | Invoice and online reservation | booking 422762 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#928]
![image](https://cloud.githubusercontent.com/assets/10079829/13675351/25d5909c-e6af-11e5-89eb-cdf80fd0574f.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13675376/4b64b342-e6af-11e5-8887-9ed893e67583.png)

**Comment by bradatkins** [comment]
Fixed except phone number was not provided

![image](https://cloud.githubusercontent.com/assets/8440255/13692006/92d37298-e70b-11e5-916f-5f370ee99ea4.png)
