### ISSUE TITLE
DB | Travel Insurance on invoice | booking 422765 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#929]
![image](https://cloud.githubusercontent.com/assets/10079829/13677112/b589177a-e6b6-11e5-945c-c9fd44165384.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13677150/d0637554-e6b6-11e5-9d13-9646323de240.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13681113/ac0310da-e6c9-11e5-896d-4a2eed8b2bbb.png)

**Comment by bradatkins** [comment]
After quite a few test orders I've fixed it. This fix may fix a few other things as well.

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13708400/68cc63da-e77c-11e5-8c9e-ba7eecd9658a.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13708784/7890360a-e77e-11e5-9f4e-40c32349398d.png)

**Comment by bradatkins** [comment]
Not sure what's going on, sent you a video. It works each and every time for me.
