### ISSUE TITLE
2 DB Errors - Multiple passenger problem and random unchangeable business class booking. (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#933]
![image](https://cloud.githubusercontent.com/assets/10079829/13752309/7ef49dac-e9e4-11e5-86d4-4d22abcfd570.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13752347/ae874056-e9e4-11e5-8aa3-169974a21d1d.png)

**Comment by bradatkins** [comment]
I can't read the second screenshot and there are no order numbers...

**Comment by ronenreinheimer** [comment]
from Chris:

**422821 **is the order number

**Comment by bradatkins** [comment]
The root cause of this has been fixed as per my email.
