### ISSUE TITLE
data base issue - additional comments not visible on a blue sheet + having issues when booking more than one person (Bika)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#935]
![image](https://cloud.githubusercontent.com/assets/10079829/13754758/8d9c45a8-e9ee-11e5-8ef7-9020498c4aee.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13754750/8674eb7c-e9ee-11e5-8be0-4fefd3102feb.png)

**Comment by bradatkins** [comment]
Do not use the PDF form anymore. Where did she find that as I need to
remove it.

Brad

**Comment by ronenreinheimer** [comment]
From Sandy:

![image](https://cloud.githubusercontent.com/assets/10079829/13786553/8fa0cdcc-eaae-11e5-8878-82c11d91930d.png)

**Comment by bradatkins** [comment]
They are there:

![image](https://cloud.githubusercontent.com/assets/8440255/13787646/1d8e7e6e-eab3-11e5-84d2-38a7dac521dd.png)

**Comment by ronenreinheimer** [comment]
Reply from Bika:

![image](https://cloud.githubusercontent.com/assets/10079829/13790227/c3e764ec-eabd-11e5-98a8-8a55beb66cf6.png)

**Comment by bradatkins** [comment]
We do not use the PDF anymore.

**Comment by ronenreinheimer** [comment]
Sandy said that they need it. I don’t deal directly with clients, so Sandy is the expert when it comes to this.

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
