### ISSUE TITLE
Github Issue: 206 Tours Inc.  - Order #422803 Tour #206 July 7, 2016  (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#936]
![image](https://cloud.githubusercontent.com/assets/10079829/13779387/1413f7b4-ea91-11e5-9794-28537876debb.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13779385/0f505592-ea91-11e5-912b-af9d3d384f89.png)

**Comment by bradatkins** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/8440255/13865586/334082c6-ec83-11e5-96f9-602ef3908444.png)
