### ISSUE TITLE
group leader - pilgrim confirmation (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#937]
![image](https://cloud.githubusercontent.com/assets/10079829/13779732/e574f370-ea92-11e5-9700-309313a2f234.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13779744/eef1d454-ea92-11e5-85ee-03c7e1e721c5.png)

**Comment by bradatkins** [comment]
Fixed
