### ISSUE TITLE
Not Able To Receive Emails from the Database  |  421537  | Order #421574  |  Order #421575 & Can't Access Online Account (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#938]
![image](https://cloud.githubusercontent.com/assets/10079829/13780814/618a5636-ea97-11e5-9b86-6ba080f75454.png)

**Comment by bradatkins** [comment]
That's because on Feb 29th, Yaritza disabled the wrong account.

It's fixed now.

**Comment by ronenreinheimer** [comment]
A leap day error :/

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
