### ISSUE TITLE
Booking 422837  - Travel insurance on online reservation | Tour CR082716

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#939]
![image](https://cloud.githubusercontent.com/assets/10079829/13780942/c7ea36ee-ea97-11e5-9106-21db959e54f4.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13780931/c2b16d3c-ea97-11e5-928a-3ecd721d5abd.png)

**Comment by bradatkins** [comment]
Fixed, it was related to the coupon code
