### ISSUE TITLE
Exporting All Travelers by year

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#940]
i magically got 2016 to export but i keep selecting other years and clicking export and nothing's happening:

![image](https://cloud.githubusercontent.com/assets/8440903/13783524/30d2c8ec-eaa2-11e5-9d59-e24040207de8.png)

I need it b/c i need to fix all emails that end in @206tours.com and this is the only way i know how to get an easy list of them

**Comment by bradatkins** [comment]
I just tried it, and it worked ok, can you try again?

![image](https://cloud.githubusercontent.com/assets/8440255/13901771/e93803e2-ee04-11e5-9f77-2eda073c5375.png)
