### ISSUE TITLE
DB problem: not asking / taking cc number (Natasha)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#941]
![image](https://cloud.githubusercontent.com/assets/10079829/13789380/177622f0-eaba-11e5-9233-6ba82b77efa4.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13789392/26acc4fe-eaba-11e5-900a-678f034293d6.png)

**Comment by bradatkins** [comment]
I need to know some info so I can look up the session, traveler email address, name? 

Try again with Developer tools turned on

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/13879164/52341058-ecec-11e5-9c5c-b882ce364acd.png)

**Comment by bradatkins** [comment]
As emailed previously, I believe this is resolved, please keep an eye out
