### ISSUE TITLE
Installments

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#943]
Can we have the option to delete INACTIVE accounts? Kind of like we do with incomplete orders?

Lots of testing ones that don't need to stay in here:

![image](https://cloud.githubusercontent.com/assets/8440903/13819940/ac7012dc-eb71-11e5-8ab3-19375f5d4a57.png)

**Comment by bradatkins** [comment]
Inactive is now hidden

**Comment by ali206** [comment]
Can we have the option to remove inactive though instead of having them hidden please?

**Comment by bradatkins** [comment]
I don't "delete" things per say from the DB, for historical reasons.

**Comment by ali206** [comment]
Ok that's fine. 

But we are able to remove inactive from other locations in the DB, that's all we're looking to do with installments as well.

**Comment by bradatkins** [comment]
No, they actually are still behind the scenes, I didn't delete them. Unless I'm thinking of something else?

**Comment by ali206** [comment]
Ok just leave it then, i don't think you understand what i'm asking but sandy said she'd prefer to remove inactive installments instead of them automatically being hidden like they are now
