### ISSUE TITLE
DB : Agent's Confirmation "Agency" -Anyone notice spelling? (Milanka / Ali)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#944]
![image](https://cloud.githubusercontent.com/assets/10079829/13820240/d23c4d18-eb72-11e5-8bf2-f1a611c74cf0.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13820265/f0e16848-eb72-11e5-87f3-b6e8ef05a81e.png)

**Comment by bradatkins** [comment]
The commission is not approved yet:

![image](https://cloud.githubusercontent.com/assets/8440255/13865382/420964c8-ec81-11e5-848f-fc0c5e611342.png)

**Comment by bradatkins** [comment]
What text should show up at the top instead of "...your upcoming pilgrimage..."?

**Comment by ronenreinheimer** [comment]
from Ali:

**commission doesn’t get approved until it’s requested.**

**Comment by bradatkins** [comment]
Closing, hasn't happened since
