### ISSUE TITLE
Unable to view past PDF fedex Lables  Please log (Milanka)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#948]
![image](https://cloud.githubusercontent.com/assets/10079829/13858198/f50a306c-ec53-11e5-96cf-f256ce4df5b4.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13858195/ef0bd5ee-ec53-11e5-97a7-dfd6ba1b37d4.png)

**Comment by bradatkins** [comment]
Fixed
