### ISSUE TITLE
Database - New Reservations (Donna)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#949]
![image](https://cloud.githubusercontent.com/assets/10079829/13858847/d7d5c3aa-ec56-11e5-9e86-f0eeafb66742.png)

![image](https://cloud.githubusercontent.com/assets/10079829/13858888/0294062e-ec57-11e5-8570-af8ae04a6f99.png)

**Comment by bradatkins** [comment]
Reproduced and Fixed!
