### ISSUE TITLE
DB UI Tour Dates Wrapping

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#951]
Hi Brad,

Can you please use a smaller font (or let me know what font is being used and i can supply you with a different one)

![image](https://cloud.githubusercontent.com/assets/10079829/13860655/e45c4b4a-ec5f-11e5-82b2-e6a57164f06d.png)

**Comment by bradatkins** [comment]
It is using tourinclusiontext-db

**Comment by ronenreinheimer** [comment]
Please try this one:
tourinclusiontext-db2


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Done, most are good but not all:

![image](https://cloud.githubusercontent.com/assets/8440255/13880908/ea2dca54-ecf4-11e5-9c72-3a806f33aee7.png)

**Comment by ronenreinheimer** [comment]
I don’t want to make the font any smaller.


1.       Colorado Springs is the largest entry in the drop down menu – about 2px or 3px space between ,CO and $ (1st SS)

2.       Looks like maybe 2px space between price and (USD) (2nd SS) see if you can make it 1px between them?

3.       Try to tighten up drop down menu by 3 pix (3rd SS)

[cid:image004.png@01D18102.C78895F0]

[cid:image003.png@01D18102.5BA0FD50]

[cid:image005.png@01D18102.C78895F0]



Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
I took 2 spaces away from the drop down it seems to be OK now

**Comment by ronenreinheimer** [comment]
You are the king!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Just double check if the same is being applied to pilgrimages.com

www.pilgrimages.com/ecolebiblique<http://www.pilgrimages.com/ecolebiblique>

[cid:image001.jpg@01D18104.6EBC9500]


Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
It is now...was just waiting for your confirmation. Check again

**Comment by ronenreinheimer** [comment]
It is still there ☹

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Looks OK for me?
[image: Inline image 1]

**Comment by ronenreinheimer** [comment]
Now its good! I will close it out of GH.

TY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
