### ISSUE TITLE
UI - to change all departure cities at once (Sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#955]
Hi Brad,

Sandy would like all the departure cities to change at once - after client makes the initial selection. So if they select **New York**, all the drop down menus will change to New York for all the departure dates. Does this make sense?

![image](https://cloud.githubusercontent.com/assets/10079829/13923364/b78adbbe-ef56-11e5-86d2-5073710d9b3a.png)

**Comment by bradatkins** [comment]
This is now complete.
