### ISSUE TITLE
Passport Info - Same as Previous Passenger (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#958]
![image](https://cloud.githubusercontent.com/assets/10079829/13953081/6662dace-f010-11e5-9eb4-08a737836a8c.png)
![image](https://cloud.githubusercontent.com/assets/10079829/13953188/0f084e98-f011-11e5-9c80-c02b92cb1e7d.png)

**Comment by bradatkins** [comment]
Fixed
