### ISSUE TITLE
Commission showing on invoice but not recap

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#96]
The below commission approved payment is showing on the invoice but not on the recap (?) so the balances are not matching.  Booking 416781

Oct 10, 2014 416781 JM110714 Mendonca / Johnny COMMISSION  206 Tours   $1,458.00  Pending Approved Declined Credit Discount Void Voucher Promo Refund Transferred 

![image](https://cloud.githubusercontent.com/assets/8440903/5033135/4efb4fa2-6b31-11e4-94de-0aea360c09e3.png)

![image](https://cloud.githubusercontent.com/assets/8440903/5035428/1d51105e-6b45-11e4-8740-f2c38c8c46a1.png)

**Comment by bradatkins** [comment]
For whatever reason, we were explicitly hiding commissions here. I've removed it

![image](https://cloud.githubusercontent.com/assets/8440255/5696353/33c4d922-999b-11e4-9f41-748b0b0d1b18.png)
