### ISSUE TITLE
Editing Add Costs

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#961]
Is there any way we can edit add costs in the future? The way we currently have to do it seems like to many unnecessary steps

![image](https://cloud.githubusercontent.com/assets/8440903/13958684/6c9b5a58-f027-11e5-8ccc-171059f71f31.png)

**Comment by bradatkins** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/8440255/23389918/f4d99550-fd38-11e6-86b4-2119afd1822b.png)
