### ISSUE TITLE
422885 - DB charged wrong amount

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#963]
She put in the DB to be charged $6,000 and the DB charged her full balance due:
![image](https://cloud.githubusercontent.com/assets/8440903/13959584/14388e54-f02b-11e5-9934-6693d2829d4d.png)

I voided the charge and declined it in the DB already

**Comment by bradatkins** [comment]
Fixed. She selected "OTHER" as her payment value, but didn't enter a value. For whatever reason the DB let her go through but assumed she meant full.

The DB will now prompt
