### ISSUE TITLE
422504 - installment payment pending

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#964]
I just approved the pending payment, that's how they normally show though right since Elavon doesn't communicate with DB?  And we're always going to have to update Transaction ID for each installment payment as well b/c currently they all show as the same?

![image](https://cloud.githubusercontent.com/assets/8440903/13989783/404278f8-f0e8-11e5-8b34-e32e830c6194.png)

**Comment by bradatkins** [comment]
100% Correct
