### ISSUE TITLE
Order Audit

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#965]
Is the order audit only keeping track of actions done when in All Orders?

Shouldn't it keep track of any action done in any part of the DB maybe?

**Comment by bradatkins** [comment]
It should be keeping track of all changes in theory, if you have an example
let me know

**Comment by ali206** [comment]
Ok order 422504 - i approved the pending installment payment but in the audit doesn't show anything about it:

![image](https://cloud.githubusercontent.com/assets/8440903/13990524/1a1682c0-f0eb-11e5-94e4-262b6e1d7d26.png)

**Comment by bradatkins** [comment]
Where did you update the status of this payment? I tried from the main payments list and it worked OK;;
![image](https://cloud.githubusercontent.com/assets/8440255/13995005/bb291be8-f0fd-11e5-8e78-5233583ed0f9.png)

**Comment by bradatkins** [comment]
Nevermind, found it. Fixed it
