### ISSUE TITLE
Order Audit 422767 - no email attachment included & not honoring orig price

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#967]
Orig price L/O should be $3,799 and the option to keep orig pricing was selected but pricing is remaining at $3,999. 

Also - no email included in audit:

![image](https://cloud.githubusercontent.com/assets/8440903/13991404/6b3f6614-f0ee-11e5-8641-8ce43fd606a4.png)

**Comment by bradatkins** [comment]
Fixed, both issues.
