### ISSUE TITLE
Website Broken Payments Issue | 419619 & 419617 (Chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#969]
![image](https://cloud.githubusercontent.com/assets/10079829/14020974/e15ed96c-f1af-11e5-90d8-fd90f6fe9eb8.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14020971/db7d42d6-f1af-11e5-82c2-43f7fd0c89e9.png)

**Comment by bradatkins** [comment]
Do you know if she tried today?

**Comment by bradatkins** [comment]
Found a couple things that I think have solved this, but please open a new issue if you hear of it again
