### ISSUE TITLE
Why are the dates missing on invoice? (Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#971]
![image](https://cloud.githubusercontent.com/assets/10079829/14028880/5c8e4e7c-f1d5-11e5-8aa1-7db766b3a995.png)

**Comment by bradatkins** [comment]
Well technically they aren't missing, but someone setup this option with bad dates:

![image](https://cloud.githubusercontent.com/assets/8440255/14034052/deb43d4c-f1f5-11e5-8487-74202365180e.png)


![image](https://cloud.githubusercontent.com/assets/8440255/14034049/d557b6ac-f1f5-11e5-968d-59cf77f3bf91.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/14148516/bf92671e-f66d-11e5-8f79-7ea8313d2cd3.png)
