### ISSUE TITLE
Database Error | Duplicate Bookings (Amanda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#973]
a7c30a62fdc8dbeecd0476851e26bb3c

![image](https://cloud.githubusercontent.com/assets/10079829/14081084/d236e91e-f4d6-11e5-9e45-243e93753672.png)

**Comment by ronenreinheimer** [comment]
![image](https://cloud.githubusercontent.com/assets/10079829/14081133/14efd1f8-f4d7-11e5-92d1-1ae26c5bc31b.png)

**Comment by bradatkins** [comment]
The button was double clicked:

![image](https://cloud.githubusercontent.com/assets/8440255/14081287/fdb0d7ca-f4d7-11e5-9648-883d7ea15c6c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/14081298/0f75be62-f4d8-11e5-84e3-8fce2b27d84d.png)

**Comment by bradatkins** [comment]
PS: The session identifier made this only take two seconds for me to figure out :)

**Comment by ronenreinheimer** [comment]
That’s awesome!

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
