### ISSUE TITLE
Order Audit 422767 - incorrect information listed

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#975]
I didn't approve a payment today, I actually declined the pending commission amount of $1,559.61.

![image](https://cloud.githubusercontent.com/assets/8440903/14081871/db2ba22c-f4da-11e5-920c-8234fd4f49f2.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14081891/f41b052a-f4da-11e5-8585-f2af75baa973.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
