### ISSUE TITLE
No names came through   FW: 206 Tours Inc. Confirmation - Order #423025  Tour #168 June 20, 2016 (Rinda)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#977]
![image](https://cloud.githubusercontent.com/assets/10079829/14082994/3d61283a-f4e1-11e5-9982-66b8722d4040.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14082991/38e3380c-f4e1-11e5-9e10-115d713713e9.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
