### ISSUE TITLE
422510 - CAD charged, wrong amt showing 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#979]
below image is from CAD invoice so charge should be showing as $4198:

![image](https://cloud.githubusercontent.com/assets/8440903/14085889/6ccfab0a-f4f0-11e5-964c-fca6e746a1a5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14085899/75ebfa86-f4f0-11e5-84ff-071ce7c7bdb5.png)

This is the USD invoice - charge should be less than $4198:

![image](https://cloud.githubusercontent.com/assets/8440903/14085923/8ae1551c-f4f0-11e5-83c5-a74c639f4580.png)

**Comment by ali206** [comment]
please update - same as issue#867

**Comment by bradatkins** [comment]
I've put the USD amount to 2644.74 since FX was 1.37.

Have a look

**Comment by ali206** [comment]
FX was actually CAD $0.71196 when processed so USD amount is $3,042.60 - i just updated invoice
