### ISSUE TITLE
Order Audit - 419439 has none basically

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#980]
Also the order created date doesn't make sense:

![image](https://cloud.githubusercontent.com/assets/8440903/14088064/4d46c39e-f4fb-11e5-9186-ea1fa6cee551.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14088057/4699c67c-f4fb-11e5-9702-67a1aaf5cdce.png)

**Comment by bradatkins** [comment]
That is an odd order audit date...I'm not sure I can explain that one...

**Comment by ali206** [comment]
ok what about the rest of the order audit, where is it?

**Comment by bradatkins** [comment]
Closing, hasn't happened since
