### ISSUE TITLE
419439 - Paypal payment posted twice to invoice?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#981]
from 3/21:
![image](https://cloud.githubusercontent.com/assets/8440903/14088153/e51a46dc-f4fb-11e5-936b-be45bf9cc72c.png)

only 1 was charged:

![image](https://cloud.githubusercontent.com/assets/8440903/14088162/eddf31ce-f4fb-11e5-88e8-4651e3226812.png)

**Comment by bradatkins** [comment]
Fixed
