### ISSUE TITLE
422625 - need installment info so i can cxl in elavon

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#982]
i made it inactive already by accident so i don't know what to look for in Elavon

**Comment by bradatkins** [comment]
Good thing I didn't delete the info :)

It doesn't seem to have a valid transaction from Elavon against it so it may have never registered.

Last 4 digits of the card are: 0003

**Comment by ali206** [comment]
Ok I don't see it in Elavon so i guess there's nothing to do then
