### ISSUE TITLE
Add to Github: Cannot Add Passenger (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#984]
![image](https://cloud.githubusercontent.com/assets/10079829/14109324/7d3bda82-f58f-11e5-9d31-345fe679e67d.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14109326/805996dc-f58f-11e5-9acf-69686daad68a.png)

**Comment by bradatkins** [comment]
Can you get him to try again, and this time do the "Developer Tools" thing
from the start?
