### ISSUE TITLE
Email Addresses Not Updating Properly (Melissa)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#985]
d80df1341ce85f596a11667d772f6cec

![image](https://cloud.githubusercontent.com/assets/10079829/14112993/ff33d904-f59e-11e5-85a6-666bd8c645de.png)
![image](https://cloud.githubusercontent.com/assets/10079829/14112983/f8e65c52-f59e-11e5-92bf-0e8185bd76d5.png)

**Comment by ronenreinheimer** [comment]
Please follow up on this it is still happening and caused an issue with an agent on a different invoice – 423038 Jimmy Hyland.

**Comment by bradatkins** [comment]
Try now
