### ISSUE TITLE
420647 - fix math if possible

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#986]
Natasa accidentally clicked the zero out button so now the math on this invoice is wrong. 

Can you fix it?

Balance due should be $0.00, each of their penalties are $200:

![image](https://cloud.githubusercontent.com/assets/8440903/14113954/1a6b2430-f5a3-11e5-8de4-4236ea4348fb.png)

**Comment by bradatkins** [comment]
I've updated the order
