### ISSUE TITLE
Add to Github: Selecting/Unselecting (Patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#987]
Hi Brad,

Can you please add a clear options link to this section.

![image](https://cloud.githubusercontent.com/assets/10079829/14114843/baf2e476-f5a6-11e5-84ae-d8a9d2de3804.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
