### ISSUE TITLE
423035 - transferred payment no in order audit

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#988]
Irena transferred payment to 423035 but it's not showing in order audit:

![image](https://cloud.githubusercontent.com/assets/8440903/14118475/ab7e5f1e-f5b7-11e5-84ce-75ea12f1586f.png)
Session ID: f2bd3fe64012f0635433b97d4e10779a

![image](https://cloud.githubusercontent.com/assets/8440903/14118508/c71c8e4e-f5b7-11e5-99ae-8c6e4aebe2f0.png)
Session ID: f2bd3fe64012f0635433b97d4e10779a

**Comment by bradatkins** [comment]
OK it wasn't set to audit transfers. It is now.
