### ISSUE TITLE
419010 - dates missing on invoice?

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#989]
![image](https://cloud.githubusercontent.com/assets/8440903/14118895/ab5b6cd2-f5b9-11e5-8f65-caac4ea33c9c.png)

**Comment by bradatkins** [comment]
The options on this one are setup in a little bit of a confusing way I think, which is generating a problem.

![image](https://cloud.githubusercontent.com/assets/8440255/14151138/7f19e56a-f67a-11e5-9edd-b714c280d1b3.png)


They are setup as PRE Tour Options, but the tour is also set for April 1st?

**Comment by ali206** [comment]
So should they get rid of PRE, and dates? It's just a shore excursion so nothing really applies except for option name and cost right?
