### ISSUE TITLE
Back to DB .index (main page) link for in house orders - on confirmation page (Patrick) 

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#991]
Brad, for inhouse orders can you please set this up?

**From Patrick:**
Below is the image of the Confirmation Page. Top right corner has no option to “Return to Main Page” or “Return to Index”. You’re stuck there. ROK told me that they just hit the “Back” button some 12 times to get back to the main page. So can we add that in there.

![image](https://cloud.githubusercontent.com/assets/10079829/14143427/1d4e65e8-f659-11e5-8351-d8545b2c0888.png)

**Comment by bradatkins** [comment]
Done

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
