### ISSUE TITLE
Tour Header Images

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#993]
Hi Brad,

why is this not working on tour 40?
www.206tours.com/tour40

![image](https://cloud.githubusercontent.com/assets/10079829/14149425/11553b5e-f672-11e5-83df-df92753ece4d.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14149438/218bc4de-f672-11e5-988f-7692532d7516.png)

![image](https://cloud.githubusercontent.com/assets/10079829/14149432/18c26e70-f672-11e5-9a08-595b4726640f.png)

**Comment by bradatkins** [comment]
you need a capital "T" on Tour

**Comment by ronenreinheimer** [comment]
TY

God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
