### ISSUE TITLE
TOUR JF072416 apply a payment 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#994]
Hi Brad,
 I tried to apply a check payment for $56, 524 under the tour JF072416  spreading it evenly , and somehow doesn't work, can you please take a look and help please ? 

![Uploading Capture.PNG…]()

**Comment by Irena206** [comment]
![capture](https://cloud.githubusercontent.com/assets/14838466/14149584/df16082a-f672-11e5-8218-aa555f3100f9.PNG)

**Comment by bradatkins** [comment]
Odd. I see Irena as trying to do it. I just tried it and it worked fine.

Of note, Irena hasn't closed her Browser since March 18th.

![image](https://cloud.githubusercontent.com/assets/8440255/14150881/3a07ab2a-f679-11e5-9a1f-646819d42fba.png)

**Comment by bradatkins** [comment]
And all I did was this:

![image](https://cloud.githubusercontent.com/assets/8440255/14150910/573133ec-f679-11e5-8f8f-ef5c8b32436c.png)

![image](https://cloud.githubusercontent.com/assets/8440255/14150933/71308842-f679-11e5-8000-70b2986fe6fe.png)

**Comment by Irena206** [comment]
I did the same thing  and for me didn't work, I guess DB likes you more than me :)
OK thanks !!!!
Im going to close my Browser !

**Comment by Irena206** [comment]
![capture1](https://cloud.githubusercontent.com/assets/14838466/14156893/b4e0e970-f696-11e5-8411-2ea069dead6f.PNG)

For 22 people the amount PP should be $2569.27, how come looks like the picture included ???

**Comment by Irena206** [comment]
ASAP, Please !

**Comment by Irena206** [comment]
any update on this ?

**Comment by bradatkins** [comment]
The DB calculates what's remaining on the order, and applies the max amount accross the orders. What's the issue?

**Comment by Irena206** [comment]
the issue is that we thought it was supposed to divide the total amount evenly for all remaining orders.  

so since you're telling us it's not set up to do that we're still going to need to manually divide payments evenly when we need to?  That's still time consuming.  Can we maybe have the option to enter in the amount to be entered on to each booking?

**Comment by bradatkins** [comment]
But what does it do with the remaining balance?

**Comment by Irena206** [comment]
there shouldn't be remaining money if it's being split up or split up evenly

**Comment by bradatkins** [comment]
Hmmm the DB is doing this because there is...otherwise it would split it
evenly.

**Comment by Irena206** [comment]
for example maybe you could put a box under the amount that says amount per order or something:

![jgjhgjhggjh](https://cloud.githubusercontent.com/assets/14838466/14353622/ca6d8e8a-fca7-11e5-95fe-8ce778cdb5c9.PNG)

Ok let me clarify, there shouldn't be remaining money from the payment were applying if it's being split up.  There might be money remaining on an order but we'll have more lump sum payments to divide between the bookings at a later date.  Some churches want to donate $ to tours for ex. like the $255 we tried to split up on another tour.  But the DB is not letting us do it correctly so now we have to manually fix all bookings that applied over $255

**Comment by bradatkins** [comment]
You'd need to take the amount you want applied per order times it by the
number of orders and then enter that as the payment amount.

For example, if you want 255 to be applied to 6 orders, enter a amount of
1530.

**Comment by Irena206** [comment]
that doesn't make sense to me...
this feature is supposed to save us time and help us out and it's only half way helping

for your example above, if we took $255 x 6 orders how is DB going to know which of the 6 bookings lets say out of 20 total bookings to apply it to?

**Comment by bradatkins** [comment]
It was an example. If you have 20, do it that way
