### ISSUE TITLE
Registration Problem

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#997]
Bika made this email address Inactive by accident and now is trying to register the clients but is unable to. 

The clients info is not showing anywhere but when she tries to create a new account with the email address she keeps getting this login error msg:

![image](https://cloud.githubusercontent.com/assets/8440903/14155610/6a9af9c4-f690-11e5-9643-799c1bd108dc.png)

Client's email:
debtucci@verizon.net

2af46e41ffc4d587bc9d7c6f7666d5bb

**Comment by bradatkins** [comment]
Try now, the DB wasn't checking to see if the account was active or not

**Comment by ali206** [comment]
still not working

**Comment by bradatkins** [comment]
You don't get this screen?

![image](https://cloud.githubusercontent.com/assets/8440255/14155988/2caa83a8-f692-11e5-9f54-fb4f72c8aa03.png)

**Comment by ali206** [comment]
No i get the same one i sent you before

**Comment by bradatkins** [comment]
Can you close and re-open your browser?

**Comment by ali206** [comment]
ok now it worked thanks
