### ISSUE TITLE
TOUR RO051616 

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#999]
![capture22](https://cloud.githubusercontent.com/assets/14838466/14157017/4832ca86-f697-11e5-8075-4dfb8cb4c8d7.PNG)

I applied a check $5610 between 22 people which should have been $255 PP m and looks like picture included ?

Please help !!!!

**Comment by Irena206** [comment]
Hi Brad, 
I need this to be fixed ASAP ! PLEASE

**Comment by Irena206** [comment]
any update on this ?

**Comment by bradatkins** [comment]
It all depends on the remaining balance and total payment. If there's remaining money, it'll apply it to the orders

**Comment by Irena206** [comment]
So you're saying for this tour/payment, the DB split the payment in this order:
PIF a few bookings first, then applied $600, $500, $400.71 to another few, and then smaller amounts to other bookings? Is it picking these bookings in any particular order or just randomly..

Also if you're saying it depends on the remaining balance/total payment, why wouldn't the DB just make all bookings necessary PIF with that one payment?  like this booking for ex:
421571 	Dec 14, 2015 	Tourville Jr. / Michael 	RO051616 	May 16, 2016 [Recap] [Yellow Sheet] 	$653.29 	$3,254.00 	1 	Deposit

![image](https://cloud.githubusercontent.com/assets/14838466/14354572/d10e309c-fcab-11e5-989c-64d7aa657302.PNG)
